### ISSUE TITLE
Posts containing comments with tags should appear on tag pages

### ISSUE THREAD

**Issue by ghost** [diaspora/diaspora#1567]
When someone #tags their comments, they should be visible on a #tag page. They aren't.

**Comment by gordon-morehouse** [comment]
Should this issue be closed as ancient?

If not, is there a potential for abuse? I can think of a scenario in which harassers can post a #dogwhistle tag on posts they don't like to target users for harassment.

**Comment by goobertron** [comment]
We've discussed this elsewhere ([here](https://www.loomio.org/d/kBTFlUWS/tag-comment-functionality), for example), but I definitely see the potential of abuse of the type you mention, and I would not be keen for this to be implemented.

I think this issue should be closed until there has been a vote in favour of this feature on Loomio.

**Comment by jhass** [comment]
Yes, please move this to loomio if you feel strong about it.
