### ISSUE TITLE
Photo export is not working

### ISSUE THREAD

**Issue by dmorley** [diaspora/diaspora#1802]
Photo export is broken. pod(s) return a 10k tar file with no images. No errors in log that I can see.

**Comment by margori** [comment]
This bug made irrelevant by PR #5634

**Comment by svbergerem** [comment]
@margori The feature is still in our codebase. ([UsersController#L154](https://github.com/diaspora/diaspora/blob/develop/app/controllers/users_controller.rb#L154)). #5634 only remove a button that said "Photo exporting currently unavailable".

**Comment by goobertron** [comment]
Yes, it's still very important to implement photo exporting, and @margori if you could fix it, that would be fantastic!
