### ISSUE TITLE
Contact list in an open aspect should be available across pods

### ISSUE THREAD

**Issue by bobiam** [diaspora/diaspora#1978]
Some of my friends have joined a different pod from me, and they're unable to see my contacts in a given aspect, even when I make the contact list of that aspect visible to other members of the contact list.

Members of the aspect on the same pod are able to see the other members of that aspect, as expected.

Steps to reproduce:
1) Register accounts on two different pods
2) Add each account to the other's friends aspect
3) Make the contact list of that aspect public
4) Note that you're unable to see the contact list.

Expected behavior: 
I should be able to see the contacts of any publicly listed aspect from any pod, not just the pod I'm on.

**Comment by svbergerem** [comment]
I'll close this one. If anyone would like to see this implemented I'd say we first need some proposal on Loomio because of the privacy issues that have been raised.
