### ISSUE TITLE
Public key in webfinger document should be moved

### ISSUE THREAD

**Issue by afeder** [diaspora/diaspora#2440]
I just had a look at the federation protocol description in the wiki and I noticed that in the webfinger document for a user, an element of this type is required:

    <Link rel="diaspora-public-key" type="RSA" href="((base64-encoded representation of the rsa public key))"/>

This is bad style in multiple ways:

1. The `href` attribute of `<Link>` elements is supposed to be an URI, per the [XRD 1.0 specification](http://docs.oasis-open.org/xri/xrd/v1.0/xrd-1.0.html#element.link). If you *must* include the verbatim public key in the document, you should use a [`<Property>` element](http://docs.oasis-open.org/xri/xrd/v1.0/xrd-1.0.html#element.property).

2. The `type` attribute of `<Link>` elements *must* be a valid MIME type, per the [XRD 1.0 specification](http://docs.oasis-open.org/xri/xrd/v1.0/xrd-1.0.html#element.link), and it applies to the resource that the `href` attribute is supposed to link to. `RSA` is not a valid MIME type.

3. The `rel` attribute of `<Link>` elements *must* be an URI or a registered type, per the [XRD 1.0 specification](http://docs.oasis-open.org/xri/xrd/v1.0/xrd-1.0.html#element.link). If you want to use the `diaspora-public-key` moniker, you have to either namespace it, e.g. `http://schema.diasporafoundation.org/diaspora-webfinger#public-key`, or register it.

4. Why invent a new relation type for specifying keys? Why not use an existing (or draft) ontology like [Cert](http://www.w3.org/ns/auth/cert) or [WOT](http://xmlns.com/wot/0.1/)?

Item 2 and 3 also applies to the "guid" element of the document.

**Comment by svbergerem** [comment]
Closing in favor of https://github.com/diaspora/diaspora_federation/issues/39.
