### ISSUE TITLE
User gets multiple notifications when another user starts sharing with them

### ISSUE THREAD

**Issue by mindaslab** [diaspora/diaspora#2483]
If a user shares with me. Even though he adds me in many aspects, it need not appear multiple times in my notification. Its quiet annoying.

See image https://joindiaspora.s3.amazonaws.com/uploads/images/scaled_full_e2b7def6a3ab9602c2ce.png

**Comment by bpichot** [comment]
Hello everyone !

I've been advised by the podmin of framasphere.org to comment on this issue, as it happened with my diaspora account recently.

![bug_diaspora](https://cloud.githubusercontent.com/assets/3040810/5990491/22590040-a9b4-11e4-88c3-0af69c5a41f6.png)

This screenshot has been taken by a contact of mine after he added me. I have the “follow back” option activated on my account, so I think I didn't do anything special to make that happen. On the same day another friend of mine added me, and he got dozens of notifications too, as well as dozens of emails in accordance with his account parameters.

And there is an even weirder thing: despite my “follow back” option checked, these two guys have not been automatically added to my contacts, and I got no notification at all as far as they were concerned… Dunno if it's related, but I don't want to miss anything relevant.

Thank you very much for working on this anyway!

**Comment by Flaburgan** [comment]
This is probably fixed now. What should we do, let open, or close and wait if someone reproduces once again?

**Comment by denschub** [comment]
I'll close it for now. We can reopen this if it happens again.

**Comment by Flaburgan** [comment]
This has been reproduced on diaspote.org (@augierLe42e and @dadall pod) which is running develop and by two contacts on the same pod. So that means that the federation is not involved, and that the bug is still there in 0.6...

**Comment by denschub** [comment]
#6579.
