### ISSUE TITLE
Javascript should support plural forms for time-based translations

### ISSUE THREAD

**Issue by one-dash** [diaspora/diaspora#2522]
Russian language needs support for plural forms for following things in javascript.yml:

javascripts.timeago.days
javascripts.timeago.minutes
javascripts.timeago.months
javascripts.timeago.years

Without plural forms for that translation currently looks ugly and really unprofessional.

According to MrZYX, this should be done:

> To fix this issue it's necessary to hack into the jquery timeago plugin to use our JS translation helper and the right interpolation variable.

whole note: https://github.com/diaspora/diaspora/pull/2498#issuecomment-3088011

**Comment by svbergerem** [comment]
Fixed by #6926.
