### ISSUE TITLE
Text-only notification mails should contain a link to the post that generated the notification

### ISSUE THREAD

**Issue by dertuxmalwieder** [diaspora/diaspora#2561]
I have been using Thunderbird as my mail client for years. Thunderbird usually does not display HTML mails (except if I tell it so). However, Diaspora notification mails fail to have a link to the particular posting in plain text mode which makes them rather useless to me.

http://i56.tinypic.com/debcic.png

**Comment by svbergerem** [comment]
Notification mails contain text/html content as well as text/plain. text/plain also contains a link to the post.
