### ISSUE TITLE
Email should be stored with the user-entered case preserved, and then matched case-insensitive

### ISSUE THREAD

**Issue by prellele** [diaspora/diaspora#2569]
email of some users are not downcased, so they couldn't reset the password.
just checked it, and emails are not downcased.

you could check in your db with this query:

     SELECT distinct email FROM diaspora.users
     WHERE (SUBSTRING(email, 1, 1) COLLATE utf8_bin) = UPPER(SUBSTRING(email, 1, 1));
(igonore thoose with numbers at the beginning)

**Comment by svbergerem** [comment]
We tell devise that email addresses should be case insensitive: https://github.com/diaspora/diaspora/blob/develop/config/initializers/devise.rb#L64

**Comment by svbergerem** [comment]
This has been fixed by #5967.
