### ISSUE TITLE
some public posts are missing between pods

### ISSUE THREAD

**Issue by lu-x** [diaspora/diaspora#2805]
i realized that for communication between joindiaspora.com and pod.geraspora.de

e.g. i can see [this](https://pod.geraspora.de/posts/379062) post on my account on geraspora, but not on joindiaspora.com.

on joindiaspora.com dennis is in one of my aspects. on geraspora he isn't.

on joindiaspora.com i don't see his posts (posts newer than about a week) in my stream (featured users) nor on his profile page. on geraspora i can see all of his posts in my stream and on his profile page.
##

**Comment by jaywink** [comment]
Not sure there is anything concrete to fix here, so suggest closing. Federation to and from joindiaspora is not a core code issue.

**Comment by svbergerem** [comment]
I agree with @jaywink here. Can we close this?

**Comment by SuperTux88** [comment]
Yes :+1:

**Comment by goobertron** [comment]
I also agree with Jay, plus since this was reported, federation code has been completely rewritten and JoinDiaspora has been overhauled and performs a lot better. So yes, let's close, and potentially reopen if anyone reports a similar issue in the future (with any two pods).
