### ISSUE TITLE
Tags with colon are not parsed correctly

### ISSUE THREAD

**Issue by enko** [diaspora/diaspora#2979]
I want to mark my public posts with a tag that indicates which language the post is written in. So when I add the tag #lang:en or #lang:ger only #lang is parsed as tag.

I would expect that the whole term '#lang:ger' would be used as tag.

**Comment by svbergerem** [comment]
We already have a PR that implements a language filter (#4998) and I don't think that using hashtags for a language filter would be the right solution.

Does anyone think that we need hashtags with colons?

**Comment by goobertron** [comment]
No.

**Comment by svbergerem** [comment]
Ok, I'll close this. If anyone still thinks that we need hashtags with colons, please discuss on loomio how we should define hashtags.
