### ISSUE TITLE
Users should be able to like comments again

### ISSUE THREAD

**Issue by ghost** [diaspora/diaspora#2999]
I haven't found an issue for that ;)
##

**Comment by qm3ster** [comment]
Heart requires no translation, and in Russian 'Like' is much dumber than +1 (Which people use in normal conversation sometimes.)
Also requesting this feature, convinced it should not cause bloat. :sweet_potato:

**Comment by Flaburgan** [comment]
@qm3ster as said by @jaywink https://github.com/diaspora/diaspora/issues/4920 is a blocker for this issue. Hopefully https://github.com/diaspora/diaspora/pull/6586 will be enough to close it.

**Comment by cmrd-senya** [comment]
How about removing `author_signature` for relayables which are not on the home pod of the author of a parent post? It'll be the best we can do to reduce the DB bloat.

@SuperTux88, doesn't your refactoring includes this change by any chance?

**Comment by SuperTux88** [comment]
Yes, I'm working on removing unused signatures

**Comment by cmrd-senya** [comment]
Great, then fixing this one should be a piece of cake

**Comment by Hypolite** [comment]
+1 for this feature. I like being able to notice someone I liked their comment without having to add a comment myself if I don't have anything meaningful to add to the conversation.

**Comment by Flaburgan** [comment]
Nice news, the new 0.6 version now released drastically reduced the database size. This feature could be activated again pretty easily I guess (I didn't look at the code at the moment). Does anyone here want to work on it or can I add the "help wanted" label on this one?

**Comment by cmrd-senya** [comment]
Looks attractive. I don't know whether I can dedicate enough time to that. I'm definetely interested to participate, but not right now.

**Comment by SuperTux88** [comment]
It is only a frontend thing, the backend is still functional and likes on comments from friendica are stored and relayed.

**Comment by SuperTux88** [comment]
At least I think it still works, I haven't tested it, but I have likes for comments from friendica in my DB. I don't know how relaying works, because the parent is the comment, maybe this needs improvements on the federation.

**Comment by Timoses** [comment]
+1!

**Comment by Flaburgan** [comment]
@SuperTux88 any chance you can check the current state of the federation regarding this? It would allow a possible contributor to know if he can solve it, a simple front-end or a modification of the federation are two very different tasks :)

**Comment by SuperTux88** [comment]
The federation already works in some cases (relaying is the tricky part here), and it should be easy to make it fully functional again. I already planned to fix this (because friendica already have likes on comments), but didn't have the time yet.

But I think we should also add a functionality that older/inactive posts are "archived", and likes are deleted and only the number of likes is kept, that way we can prevent that the database grows again over time. With the cleanups/refactorings from 0.6 it is less an issue than before (where likes on comments really blow up the database), but it is probably still something we should think about.

**Comment by Flaburgan** [comment]
>But I think we should also add a functionality that older/inactive posts are "archived"

Do you feel like this has to be done at the same time than the feature is bringing back or should we be "lean" and first see how the database is growing before putting energy on this?

**Comment by SuperTux88** [comment]
I'd prefer when it is done at the same time, but it isn't needed. (Because otherwise it's probably never done ;) )

**Comment by Flaburgan** [comment]
Just for the record, we're doing progress on that topic: the (just released) 0.7.1.0 version is using the federation v0.2.2 which relay likes for comments. It means that the federation part is done!

**Comment by MrPetovan** [comment]
Thanks! In Friendica I can see the like button on Diaspora, didn’t check if it actually shows up on Diaspora though.

**Comment by SuperTux88** [comment]
It doesn't show up, because there is now UI for it on diaspora, but it is stored in the database (so it can be displayed later, when the UI is done), and it is relayed to other servers, so if you like a diaspora comment on a diaspora post from friendica, it should show up on other friendica nodes (relayed `friendica (like-author)` -> `diaspora (post-owner)` -> `diaspora/friendica/... (other receivers)`).

**Comment by MrPetovan** [comment]
Great, thank you for the explanation!

**Comment by Flaburgan** [comment]
So if someone wants to tackle this issue, we currently hope that the optimizations done by @SuperTux88 regarding signatures are enough to avoid blowing the database. The only way to really know if it's true is to reactivate the feature and see what's going on :)

So what's need to be done is:
- Check if the backend currently works as expected (= same rules than for a post, users can like a comment only once, each user who has access to the comment can like it, users can delete their own like, etc.), by checking the code and writing some tests
- Write the front-end of the feature: no need to design something new here, simply take the UX from the "like a post" feature from the stream, and add it to comments in the stream and in the single post view (the view accessible by clicking on the timestamp of a post). I guess the mobile view can be dealt with in a second time.

**Comment by mcv** [comment]
I think Google stores likes in a noSQL database. I regularly see a mismatch between the number of likes and the number of people who liked it.

And Big Data is Google's thing. Not ours.

I don't mind fixing this if it's really just front-end, but based on this discussion, I'm not convinced it should be fixed, and if it requires database work, I'd rather not start here.

**Comment by Flaburgan** [comment]
@mcv I really think the bloated DB problem is gone. Please go ahead, and if you face difficulties, just ask. You're welcome to open an early WIP pull request to have feedback.

**Comment by mcv** [comment]
Alright. I'll have a look at it. I'm currently struggling to get diaspora working locally, though. Is there a better channel to ask basic questions about how to get stuff up and running, or can I do that here?

**Comment by mcv** [comment]
I'm afraid I'm not going to have time to look at this. I hope someone else can pick this up.

**Comment by Flaburgan** [comment]
I'm going to check the code this evening, I should be able to quickly see if I'm skilled enough to solve it or if it's bigger than me.

**Comment by dreamerchris** [comment]
please wolve this in order to have a broader acceptance liking comments is a must!

ty for your hard work (bumpity bump new here if bumbs are not allowed please dont ban me)

**Comment by tclaus** [comment]
Just for reference: 
I have picked up the Idea and WIP Pr and pulled it close to merge: #8203

**Comment by WebSpider** [comment]
Can I like this? :)

**Comment by glechapelain** [comment]
_Plus one_ =)

**Comment by Flaburgan** [comment]
For information, this feature has been developed and will be part of the next major release. No need to say "+1" 😉

**Comment by tclaus** [comment]
Plus 1.

**Comment by Flaburgan** [comment]
https://github.com/diaspora/diaspora/pulls/8203 has been merged, I'm closing this issue as Done :partying_face:

**Comment by tclaus** [comment]
Finally. Thanks to all who are involved in this.
