### ISSUE TITLE
Feature request: Configurable limit on uploaded image file size

### ISSUE THREAD

**Issue by andrejpodzimek** [diaspora/diaspora#3155]
The current image size limit of 4 MB is quite inconvenient. JPEG files from a 18 Mpix camera (which is not that uncommon today) are slightly above the limit of 4 MB (about 5 to 7 MB). Since images always get resized anyway (which means that their full size won't be stored on the pod), such a hard limit does not make sense.

Both Google+ and Facebook accepted a 22 MB big photo in TIFF format with no issue today; Google+ can even handle RAW files quite easily. :-) 

It would be nice if this limit could be made configurable, so that pod maintainers could change it according to their connection speed and other characteristics.

**Comment by flashcode** [comment]
:+1:
I cannot upload my DSLR photos which are ~6-10MB without resizing them, this is annoying.

**Comment by Flaburgan** [comment]
I created a pull request https://github.com/diaspora/diaspora/pull/6819 to fix this issue but @denschub told me it was not the way to go. So we're now tracking this problem with https://github.com/diaspora/diaspora/issues/4997 and this issue can be closed.
