### ISSUE TITLE
Re-build "Create account" system/first time login process (Facebook, twitter login)

### ISSUE THREAD

**Issue by hake** [diaspora/diaspora#3157]
Let users create, login to a diaspora accounts using their facebook, or twitter accounts, i recently have worked in a Node.js project and we use a library called Everyauth ( https://github.com/bnoguchi/everyauth) it's a really great library to simplify the create/login process, i'm not experience with Ruby on rails, but for sure that exist some library like Everyauth for rails that can be integrated in diaspora, "easily" at the same time i would like to suggest the rebuild of first time login process creating a more user friendly process, something in 3 steps like this:

1º- Let users create/login with facebook/twitter accounts
2º Ask users if they want connect more social accounts
3º Let users "follow" friends from connected accounts that use Diaspora

Check the image of the process : http://www.flickr.com/photos/23180430@N02/6942712058/sizes/l/in/photostream/

What do you think, anyone available to work on this ?

**Comment by jhass** [comment]
We shouldn't do this. We shouldn't encourage usage of centralized SNs, we shouldn't encourage creating accounts that are dependent on the account of a centralized SN.

Please open a Loomio thread if you feel strongly about this for some awkward reason.
