### ISSUE TITLE
When a user with a lot of contacts updates their profile, bad things happen...

### ISSUE THREAD

**Issue by kaylamh** [diaspora/diaspora#3164]
Whenever we update DiasporaHQ, the server has a heart attack. Max says there's probably something really dumb in our profile update action. Help please.
##

**Comment by svbergerem** [comment]
We moved the dhq account to another pod. Do those problems still exist on the new pod?

**Comment by goobertron** [comment]
That's one for @jaywink.

**Comment by jaywink** [comment]
@goobertron there are many people with access to the new HQ account - I haven't used it for a while so not sure what it is like, better ask someone who uses it more regularly.

I doubt however the amount of contacts the HQ account has is even close to what the old account has, so an educated guess would be that the same would not be seen there, yet.

**Comment by jaywink** [comment]
(ps, if someone wants to take ownership of the HQ pod at some point, feel free to ask for the backups - @Zauberstuhl also has access to them, I'll keep it running otherwise)

**Comment by Flaburgan** [comment]
The problem is not specific to an account, it's about the number of contacts. diasporahq@joindiaspora.com has 92 contacts and 371128 "only sharing with me". hq@pod.diaspora.software "only" has 12201 contacts.

I guess the test can be done again now that joindiaspora's host changed, I'll do it.

**Comment by svbergerem** [comment]
@Flaburgan ping.

**Comment by SuperTux88** [comment]
This is still a problem. I planned to improve this for public profiles, but I need to wait, because this doesn't work with 0.5.x

**Comment by goobertron** [comment]
Wow - ***so*** pleased to see this issue finally closed. Thank you @SuperTux88!
