### ISSUE TITLE
Improve NSFW experience!

### ISSUE THREAD

**Issue by mindaslab** [diaspora/diaspora#3233]
Diaspora must have a office mode / personal mode toggle switch in its top panel ;-)

**Comment by gordon-morehouse** [comment]
NSFW posts in one's stream now have a 'show all' button which achieves most of the same functionality.

**Comment by gordon-morehouse** [comment]
Can this issue be closed as resolved? See my prior comment.

**Comment by svbergerem** [comment]
#5756 deals with the same issue. @mindaslab If you still think there should be a switch in the header you could mention that in the other issue.
