### ISSUE TITLE
Markdown parsing of URI schemes

### ISSUE THREAD

**Issue by adoa** [diaspora/diaspora#3374]
I would like to make small pictures with links to different services that I use. The URI scheme for mail with 'mailto:' is parsed correctly by markdown. However, Markdown refuses to parse a URI that starts with 'xmpp:'.  On my profile adoa@despora.de you can see what i mean. Currently the XMPP icon does not contain a URI as it does not work.

The mailto scheme however is only parsed on my profile page. In a message for my aspects it does not work either. That puzzles me a bit.

Is that some kind of security rationale that only http, https, ftp and mailto are parsed by markdown? Are there other URI schemes that are supported? 

There is some definition about the xmpp URI scheme, as far as I can see: http://xmpp.org/extensions/xep-0147.html

**Comment by jhass** [comment]
Implemented by #5526.
