### ISSUE TITLE
Limited posts not displayed in streams

### ISSUE THREAD

**Issue by CyberDomovoy** [diaspora/diaspora#3397]
Lately, i get the same behavior as bug #2718:

I post from my account on a self-hosted Friendica installation ( https://social.errlock.org ).
Public posts appears just well on joindiaspora.com.
When i select who should be able to see the posts, this is what happens on joindiaspora.com:
* Posts don't show up on the streams pages (activity, aspects, followed tags), whoever you are.
* Posts ARE shown on the profile page ( https://joindiaspora.com/people/cbaf0c9c5da775d9 ), and as far as i know, to all the people who are authorized to see them. So this is not a federation problem.

Please fix this, as Diaspora is useless if you need to make your posts public for your contacts to be notified.

**Comment by svbergerem** [comment]
No further information for more than 2,5 years.
