### ISSUE TITLE
Pod in subdirectory of servers document root

### ISSUE THREAD

**Issue by jreinert** [diaspora/diaspora#3400]
I would love to see this. What i mean is having having a diaspora pod in myhost.com/diaspora for example. Like this one could use his/her server for other webhosting and still have a pod accessible in a subdirectory. For all who can't access Apache configs which is the case on shared hosts. A simple htaccess file in the root of /documentroot/diaspora would suffice to define the redirects like so:

Options +FollowSymlinks
RewriteEngine on

RewriteCond %{SERVER_PORT} !^443$
RewriteRule (.*) https://%{SERVER_NAME}%{REQUEST_URI}

RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ http://127.0.0.1:3000/$1 [P,QSA,L]

RequestHeader set X_FORWARDED_PROTO https

So please guys! Implement this. It'd be awesome!
##

**Comment by Flaburgan** [comment]
A diaspora* id is like a valid email address: username@sub.domain.tld. To allow to have a subfolder at the end of the path is risky and would imply to rewrite a lot of things, so this is not something we're going to do, sorry.
