### ISSUE TITLE
make a post privacy option "public to diaspora users only"

### ISSUE THREAD

**Issue by dia-bene** [diaspora/diaspora#3411]
I would like to see a post privacy option that allows my post to be visible to all diaspora users, but not the wider internet (people who do not have diaspora profiles).  This could be something designed into the post privacy settings, or alternately there could be a default aspect which includes the entire userbase of diaspora.

Someone mentioned that they think there is no use for this if there is at least one pod which allows anybody to join.  My opinion is that the use is in the fact that it puts a step which requires effort to complete in the way of everything essentially being plastered on the walls of the public square. It may be a simple step & of course it can be easily gamed, but each step eliminates an amount of people who don't care enough to take it.  That applies to every method of protecting privacy.  I think keeping things internal at a basic level is a good first layer of protection for a community that is interested in it.

**Comment by svbergerem** [comment]
This is a controversial feature. If someone would still like to see this implemented please open a thread on loomio first.
