### ISSUE TITLE
Searching for a user on another pod doesn't always trigger webfingering

### ISSUE THREAD

**Issue by ludovicchabant** [diaspora/diaspora#3528]
Searching for user `tyhalley@joindiaspora.com` from my own pod gives no result at first. After half a dozen attempts, the user is found at last. Looking at the `production.log`, it looks like webfingering wasn't even triggered!

    Started GET "/people.json?q=tyhalley%40joindiaspora.com&limit=4&timestamp=1346377862936&_=1346377862939" for 174.6.226.141 at 2012-08-30 18:51:02 -0700
    Processing by PeopleController#index as JSON
      Parameters: {"q"=>"tyhalley@joindiaspora.com", "limit"=>"4", "timestamp"=>"1346377862936", "_"=>"1346377862939"}
    Completed 200 OK in 7ms (Views: 2.6ms | ActiveRecord: 0.6ms)

    Started GET "/people?q=tyhalley@joindiaspora.com" for 174.6.226.141 at 2012-08-30 18:51:05 -0700
    Processing by PeopleController#index as HTML
      Parameters: {"q"=>"tyhalley@joindiaspora.com"}
      Rendered shared/_invitations.haml (3.5ms)
      Rendered people/index.html.haml within layouts/application (8.7ms)
      Rendered shared/_footer.html.haml (1.8ms)
    Completed 200 OK in 149ms (Views: 49.4ms | ActiveRecord: 19.9ms)

    Started GET "/people/refresh_search?q=tyhalley%40joindiaspora.com&_=1346377876456" for 174.6.226.141 at 2012-08-30 18:51:16 -0700
    Processing by PeopleController#refresh_search as JSON
      Parameters: {"q"=>"tyhalley@joindiaspora.com", "_"=>"1346377876456"}
    Completed 200 OK in 121ms (Views: 0.2ms | ActiveRecord: 0.6ms)

    Started GET "/stream" for 174.6.226.141 at 2012-08-30 18:51:25 -0700
    Processing by StreamsController#multi as HTML
      Rendered aspects/_aspect_listings.haml (0.6ms)
      Rendered tags/_followed_tags_listings.haml (0.6ms)
      Rendered shared/_public_explain.haml (4.0ms)
      Rendered photos/_new_photo.haml (1.5ms)
      Rendered shared/_publisher.html.haml (403.2ms)
      Rendered aspects/_no_posts_message.haml (0.3ms)
      Rendered aspects/_aspect_stream.haml (419.8ms)
      Rendered shared/_invitations.haml (3.2ms)
      Rendered shared/_donatediaspora.html.haml (0.5ms)
      Rendered shared/_right_sections.html.haml (12.2ms)
      Rendered layouts/main_stream.html.haml within layouts/application (462.2ms)
      Rendered shared/_footer.html.haml (2.7ms)
    Completed 200 OK in 715ms (Views: 520.5ms | ActiveRecord: 2.8ms)

    Started GET "/stream?_=1346377887754" for 174.6.226.141 at 2012-08-30 18:51:27 -0700
    Processing by StreamsController#multi as JSON
      Parameters: {"_"=>"1346377887754"}
    Completed 200 OK in 251ms (Views: 166.6ms | ActiveRecord: 43.6ms)

    Started GET "/people?utf8=%E2%9C%93&q=tyhalley%40joindiaspora.com" for 174.6.226.141 at 2012-08-30 18:51:30 -0700
    Processing by PeopleController#index as HTML
      Parameters: {"utf8"=>"✓", "q"=>"tyhalley@joindiaspora.com"}
      Rendered shared/_invitations.haml (4.6ms)
      Rendered people/index.html.haml within layouts/application (9.3ms)
      Rendered shared/_footer.html.haml (2.5ms)
    Completed 200 OK in 87ms (Views: 51.3ms | ActiveRecord: 25.6ms)

    Started GET "/people/refresh_search?q=tyhalley%40joindiaspora.com&_=1346377900895" for 174.6.226.141 at 2012-08-30 18:51:42 -0700
    Processing by PeopleController#refresh_search as JSON
      Parameters: {"q"=>"tyhalley@joindiaspora.com", "_"=>"1346377900895"}
    Completed 200 OK in 784ms (Views: 0.4ms | ActiveRecord: 45.8ms)
    webfingering tyhalley@joindiaspora.com, it is not known or needs updating
    Getting: https://joindiaspora.com/.well-known/host-meta for tyhalley@joindiaspora.com
    Getting: https://joindiaspora.com/webfinger?q=tyhalley@joindiaspora.com for tyhalley@joindiaspora.com
    Getting: https://joindiaspora.com/hcard/users/4ca7169d1cea8b51 for tyhalley@joindiaspora.com
    event=webfinger_marshal valid=false target=tyhalley@joindiaspora.com

    Started GET "/people?utf8=%E2%9C%93&q=tyhalley%40joindiaspora.com" for 174.6.226.141 at 2012-08-30 18:55:22 -0700
    Processing by PeopleController#index as HTML
      Parameters: {"utf8"=>"✓", "q"=>"tyhalley@joindiaspora.com"}
      Rendered shared/_aspect_dropdown.html.haml (72.6ms)
      Rendered people/_relationship_action.haml (455.4ms)
      Rendered people/_person.html.haml (521.0ms)
      Rendered shared/_invitations.haml (67.1ms)
      Rendered people/index.html.haml within layouts/application (765.8ms)
      Rendered shared/_footer.html.haml (2.3ms)
    Completed 200 OK in 3519ms (Views: 3036.8ms | ActiveRecord: 142.1ms)

As you can see, I searched for it several times. Only before the last time did it retrieve metadata from `joindiaspora`. Note that this was the very first time I was looking for that user (but not the first time I was looking for a `joindiaspora` user).

**Comment by svbergerem** [comment]
We trim the search query now so leading or trailing spaces shouldn't be an issue anymore. Is anyone still able to reproduce this? (no dispatched Webfinger request when searching for a user)

**Comment by JamesC1** [comment]
I have performed my standard abuse-test:
- list new users on joindiaspora
- search for all of them on iliketoast
and not had any of the searches fail.

Is there anything that I could do in the user interface, that might
cause a search to be aborted, that iliketoast might interpret as a
caheable absence of a hit?

**Comment by svbergerem** [comment]
Alright, I'll close this now. We can reopen this issue if anyone is able to reproduce it again.
