### ISSUE TITLE
Problem when you mix a language written from right to left and a language from left to right.

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#3529]
I try to mention  عادل عادل (adel_guennouni@joindiaspora.com) and I cannot continue to write after mentionning his name : the text changed and start to write from right to left. 
##

**Comment by Flaburgan** [comment]
This specific bug is not there anymore but there is tons of weird ux behaviors which happen when mixing rtl and ltr language. Do we want to list them? Should we recycle this issue to do so?

**Comment by denschub** [comment]
Probably. That depends, though. Individual issues are usually much easier to search, so if there are larger tasks, feel free to open individual issues.

**Comment by Flaburgan** [comment]
As this specific bug is not here anymore, I'm going to close this. We should open some specific issues when we discover them.
