### ISSUE TITLE
Deleted comments reappearing a day or two later

### ISSUE THREAD

**Issue by ThyArmageddon** [diaspora/diaspora#3577]
This issue has been happening to me and other people as well, as far as I can tell they happen on commenting on one person so far.

I am on joindiaspora, others are on other pods (including diasp.org) but the person we are commenting on and having this issue is on diasp.org.

We comment and submit the comment, then we fix it and delete the old comment and the comments (for me at least) reappear several hours up to a day or two later baring the timeline of when they reappered not posted. I don't know about other people but theirs reappear as well (not sure if it's under the same circumstances).

If any further information is needed please notify me, thank you.

@dmorley

**Comment by svbergerem** [comment]
Has anyone been able to reproduce this bug?

**Comment by SuperTux88** [comment]
I was not able to reproduce this bug, but I have seen it happen with a deleted Post (not Comment). I think this has something to do with the federation, but I haven't yet looked at the more accurate. I'll have a closer look at this, after my federation-rewrite is finished.

**Comment by Flaburgan** [comment]
@SuperTux88 federation-rewrite is over ;) Any news on that subject? Is it solved?

**Comment by SuperTux88** [comment]
I think this happened because the other pod federated the comment back to you, after you deleted it. The new federation doesn't do this anymore, so this is probably fixed.

**Comment by jhass** [comment]
We can reopen this or a new report if the problem resurfaces after everybody is on 0.6
