### ISSUE TITLE
Cryptocat plugin for Diaspora

### ISSUE THREAD

**Issue by ghost** [diaspora/diaspora#3580]
Hi guys. In response to user requests for a chat plugin on the pod, I have decided to take on this project. My preference is to not use any cloud services and run everything locally on the pod, so I've chosen to embed a cryptocat chat application into my pod. 

I'll be developing this to work just locally first, and then I'll attempt to branch out for federation. Basically, it will need to be able to check pods to see if any of a user's aquaintances (are logged-in and) have chat enabled, and then be able to open a data pipe between users across pods for the encrypted chat messages. There may be some shared encryption keys between pods necessary to make this work, like each pair of pods may need to share a private "pod-pair" key, maybe some system for auto-setup for that. The data piping part should become clearer on implementation once the local version is working. These ping checks for "chat enabled" aquaintances will increase traffic between participating pods, so data efficiency is a requirement there. 

The final phase of this project will be documentation and refining the make/install process for ease-of-use for new and existing pod owners, and, hopefully, a code pull request.

If anyone else is interested in this project and would like to help with development or federation testing, please comment here and we can start up a more normal outlet for communication. If you think this idea is fatally flawed and just won't work, let me know why you think that! Cheers~

**Comment by svbergerem** [comment]
We already implemented chat using XMPP. Do we still need a cryptocat plugin?

**Comment by jaywink** [comment]
I'd say definitely no. Also, the issue opener has deleted their account on GitHub, so.... closing.
