### ISSUE TITLE
Setting up a way to easily share diapora schemas

### ISSUE THREAD

**Issue by Marak** [diaspora/diaspora#3582]
Hey -

Hi. I'm a huge Rails noob. 

Would it be possible to setup an easy way to share the current schema of a diaspora node as a schema language like [xml-schema](http://en.wikipedia.org/wiki/XML_schema) and [json-schema](http://json-schema.org) ?

Ideally, I'd like an endpoint on the node that I could just curl and would return the entire schema of the current node's database as JSON-schema.

With the ability to introspect a diaspora's schema in real-time, and an assumption of some procotol, I can build polymorphic node.js / javascript interfaces reflected from the diaspora's schema. These interfaces and api clients would be relatively future-proof, as they will automatically update with future schema migrations. Sorry if that sounds like non-sense.
#3515
##

**Comment by cmrd-senya** [comment]
I don't think any of current contributors is interested in working on it. We can discuss that if anyone comes up with an intention of implementing this, but for now I think it is safe to close this.

**Comment by SuperTux88** [comment]
Closing this then. For now we have the documentation of the protocol here: https://diaspora.github.io/diaspora_federation/

If we still need this and someone is interested in working on it, we can create a new issue here: https://github.com/diaspora/diaspora_federation
