### ISSUE TITLE
Ability to revoke and reopen accounts

### ISSUE THREAD

**Issue by jzdm** [diaspora/diaspora#3677]
Currently if you do a complete new install of Diaspora and (re)open an account which existed at that pod-address before, it's not really possible to connect to other Pods, you have been connected to before, and it seems to be impossible to connect from that other Pod back to your new installed and new created account.

So there should be the possibility to revoke an account (or better the privatekey and every post which is signed with it), like you can revoke s/mime certificates. After revokation the username should be available again and should be accepted by every other pod.

If  a pod is deleted by accident, today it is not possible to reuse the address the pod was available at and to reuse the usernames which were active on that pod. With that disfunction, Diaspora is not for very long term use!
##

**Comment by Flaburgan** [comment]
The diaspora username is actually the only way a user can be sure to whom he is talking. To allow that we would need a way to make it perfectly clear for users that the person behind the account is not the one it was before. As you simply enter the username in the search bar, we can't do it. It would require to keep memory of the old account, saying "there is a new one" without giving any possibility to the user to know who is owning the new account. This is very dangerous, and I think we should not do it. You ID is your ID, do not lose it. See Google or any other email provides: you delete your account, you cannot recreate it, never.

If someone comes up with both a nice technical **and** UX solution, we can reopen this, but closing for now.
