### ISSUE TITLE
Link broken with special characters

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#3689]
The url with special characters (like à é è ç in french) are broken.

For example, [this post](https://diasp.org/posts/1447500) has a link to
http://www.dadall.info/blog/index.php?post/2012/10/29/Steam-pour-GNU/Linux%2C-inscriptions-%C3%A0-la-b%C3%AAta-ferm%C3%A9e-ouvertes but displayed as
http://www.dadall.info/blog/index.php?post/2012/10/29/Steam-pour-GNU/Linux%252C-inscriptions-%25C3%25A0-la-b%25C3%25AAta-ferm%25C3%25A9e-ouvertes which is not correct (404). There is %25 for each special character in the link generated by Diaspora.

If someone indicates me what is used to interpret markdown, this could be my first patch :) 

Ubuntu 12.04 and Windows XP
Firefox 15 and 16

**Comment by svbergerem** [comment]
@Flaburgan dadall.info seems to be down. Do you have another URL for a test?

**Comment by Flaburgan** [comment]
@svbergerem the most shared link with a special char in diaspora* is the famous french tutorial:
http://fr.wikibooks.org/wiki/Diaspora_:_Le_guide_du_parfait_d%C3%A9butant

**Comment by svbergerem** [comment]
I can't reproduce the bug with that link. (neither on develop nor on the master branch)

**Comment by Flaburgan** [comment]
Me neither. Awesome, closing.
