### ISSUE TITLE
the link "show this post" (german: "Beitrag betrachten") in notification-mails shouldn't lead to an 404 error...

### ISSUE THREAD

**Issue by kas70** [diaspora/diaspora#3738]
..., but should ask the user to sign in and redirect to the post after signing in. up to now you are redirectrd to your stream, which doesn't make sense in my opinion.
also the 404 is "scaring" users a little bit, i think.

**Comment by jaywink** [comment]
A simple "next=" parameter in the login url I guess would solve this, assuming Devise supports that kind of thing easily.

**Comment by jhass** [comment]
If not creating a route that requires authentication and simply redirects again should solve this.

```rb
before_action :authenticate_user, only: %i(... protected_post)

def protected_post
  redirect_to post_path(params[:id])
end

link_to "Sign in", protected_post_path(post)
```
