### ISSUE TITLE
Feature: Send Private Message from main post box

### ISSUE THREAD

**Issue by robinstent** [diaspora/diaspora#3743]
I think it would be a great idea if you could send a Private Message from the main posting box by having the following options on the dropdown:
Public
Private Message
Aspect 1
Aspect 2
etc

If you select Private Message rather than any of the other options you are telling D that you want to send a message rather than make a post, so a text box appears for you to type in the name(s) you want to send to. It seems like that would be fairly intuitive and slightly less clicking that going into the private messaging section, clicking on send, then typing in name(s)

**Comment by svbergerem** [comment]
Since this is a controversial feature I'll close this issue. If someone would like to see an implementation: please open a thread on [Loomio](https://www.loomio.org/g/EseV9p4X/diaspora-community) first.
