### ISSUE TITLE
Unable to create conversation with a contact (edited)

### ISSUE THREAD

**Issue by bobbywilson0** [diaspora/diaspora#3749]
This is the exception in the server log.

```
Completed 500 Internal Server Error in 3ms

NoMethodError (undefined method `split' for nil:NilClass): app/controllers/conversations_controller.rb:30:in `create' 
lib/rack/chrome_frame.rb:39:in `call'
```

Here https://github.com/diaspora/diaspora/blob/develop/app/controllers/conversations_controller.rb#L30 It is looking for `params[:contact_ids]` when the only param that makes sense is `contact_autocomplete` which contains the email address of the recipient.

**Comment by svbergerem** [comment]
You won't get a 500 anymore. There might have been some confusion about 'sharing' and 'receiving' so I will close this. If anyone witnesses this bug again feel free to reopen.
