### ISSUE TITLE
Feature: Post to facebook page

### ISSUE THREAD

**Issue by mdeboer** [diaspora/diaspora#3767]
Posting to my facebook page, this is my most wanted feature and I know it can be done, I really want to switch from Facebook to Diaspora\* as my main active platform for many reasons but for that to happen I would need the ability to post to my Facebook page.

What would be nice is to be able to be connected to your page(s) as well as your account so you can select where to post to. This is only optional for me though, even if you have to make a choice in the account services screen that would be fine for now as well :+1:

I read into it a bit and as far as I know its a case of asking 'manage_pages' permission on authentication and using the page tokens to publish posts, shouldn't be too much work I reckon.
#### Update 1:

I've looked in to it a bit more and in "/app/models/services/facebook.rb" the "/me" part of the needs to be replaced by the ID of the user's page if the user has granted permission using the 'manage_pages' permission. I am not sure where the URI is formed with the request to grant permissions though.

All of the users pages (ID's) can be found by requesting "https://graph.facebook.com/me/accounts" with as parameter the access_token of the user.

I've only had a brief look at the code, RoR is quite new for me but it's quite exciting. I'll see if I can make some changes by forking!
#### To discuss (I think):
- How to introduce this feature to the users?
  - Show multiple facebook icons while posting each with a title set to something like "Facebook (My Page)"
  - Set a default in the user services screen by a drop-down box (and thus showing only one facebook icon while posting) 
##

**Comment by apfelschnitz** [comment]
Has anybody continued to work on that?
I'd really love to see that feature in diaspora!

**Comment by svbergerem** [comment]
As far as I know no one started working on that so if you are interested feel free to work on that issue.

**Comment by apfelschnitz** [comment]
Unfortunately i have only a very basic coding knowledge, so i think i'm not up for the job.

I noticed that Friendica managed to implement that feature. Maybe this can help to get it done in diaspora:
https://github.com/friendica/friendica-addons/tree/master/fbpost
https://github.com/friendica/friendica-addons/tree/master/fbsync

deprecated facebook connector:
https://github.com/friendica/friendica/wiki/How-to:-Friendica%E2%80%99s-Facebook-connector
https://github.com/friendica/friendica-addons/tree/master/facebook

**Comment by Flaburgan** [comment]
@apfelschnitz we already allows to post to facebook, this is specific to Facebook pages.

**Comment by apfelschnitz** [comment]
I'm aware of that. But in Friendica you can actually post to Facebook pages, so i thought that might help.

**Comment by goobertron** [comment]
@spirosoik said just over a year ago that he had made a working commit and just needed to test it. If he's no longer able to complete this work, someone could pick up his commit https://github.com/spirosoik/diaspora/commit/ac7cd8187be99b5e8fb666c7e56792d59f73340b and if necessary fix it for the current code.

**Comment by mdeboer** [comment]
The changes required were quite simple if I remember correctly but require someone with more experience with the diaspora code base than me I guess. I just don't have the time nor the experience with diaspora to make and test those changes.

It boils down to adjusting the app permissions to request 'manage_pages' and requesting a list of user managed pages as I explained in the issue. There must be someone that can do this and maybe continue / use the code from @spirosoik ?

**Comment by HankG** [comment]
I believe the changes to the Facebook API prevent this now, correct?  At least that's true for posts to personal accounts. IF so this should probably be closed...

**Comment by denschub** [comment]
Obsoleted by #7874.
