### ISSUE TITLE
Wrong error message / weird behaviour

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#3771]
Step to reproduce

Click on your name and on contact
Select an aspect
Choose a person who is in this aspect and in another one
Open his profile in another tab
Remove this person from this aspect by clicking in the cross
In your other tab, on the profile of this person, click on the dropbox "aspect" (the one used to start sharing with him. The counter will display the right number of aspects ("In 2 aspects" for example) but still 3 aspects will be checked.
The old aspect is still checked. If you click on it, a message with mark "Impossible to start sharing with this person, do you ignore him ?" (don't know the exact message, mine is in french) will be displayed. This message is really weird..

**Comment by cmrd-senya** [comment]
> Choose a person who is in this aspect and in another one
Open his profile in another tab
Remove this person from this aspect by clicking in the cross
In your other tab, on the profile of this person, click on the dropbox "aspect" 

So you remove person from aspect and then expect changes on another tab? But how does another tab could get acknowledged of the changes you make on the different tab?

On current develop I see no changes on the second tab when I remove person from an aspect. If I had 2 aspects before removal I'd still have 2 aspect on the profile page unless I reload it.

Did I misunderstand the steps?

May that be that the apsect dropbox got loaded from the server at the moment you press on it back in 2012? Then that most probably have been changed by #3864.

**Comment by svbergerem** [comment]
Yes, looks like that has been changed. Just tried it again on develop. Of course the number of aspects doesn't change anymore and when you try to remove the contact from an aspect there is a flash message telling you
> Couldn’t remove username from the aspect :(

@Flaburgan Do you agree that we can close this?

**Comment by Flaburgan** [comment]
Yep, looks fixed.
