### ISSUE TITLE
Environment sanity checks in script/server

### ISSUE THREAD

**Issue by jhass** [diaspora/diaspora#3824]
Git:

* [x] <del>Check if available at all before attempting to create the tar</del>
* [ ] Check if in detached head state and if so print a warning and don't let the tar code fail
* [ ] Check if in merge conflict and abort if so

Other:

* [ ] Check if RVM available and if correct gemset if so, warning, not fatal
* [ ] Check if bundle is complete
* [ ] Check if database is migrated

**Comment by aka001** [comment]
@jhass The changes I make in script/server doesn't reflect when I run the command "rails server". The command "rails server" is also to the file "config/load_config.rb".
I don't know where am I going wrong. Please help me.

**Comment by jhass** [comment]
To run `script/server` you run, well, `script/server`. `bin/rails server` does not run the script and never will.

**Comment by aka001** [comment]
@jhass Got that. Thanks. I have created a pr https://github.com/diaspora/diaspora/pull/5708 .

**Comment by mrbrdo** [comment]
should be fixed by https://github.com/diaspora/diaspora/pull/5891
checking migrations not worth it as mentioned in the commit message
