### ISSUE TITLE
Can't send inbox on mobile

### ISSUE THREAD

**Issue by desyncr** [diaspora/diaspora#3852]
"To" input isn't populated with my contacts yet it let me send the message.

![diaspora-bug-mobile-6](https://f.cloud.github.com/assets/1857707/70820/c4fa44b8-5fc3-11e2-9b85-3d6b721e2262.png)

**Comment by desyncr** [comment]
Update: Autocomplete works and not 500 internal server error is shown when sending a message without "To".

Still allows to send a message without a "To". Dunno if that is enough to keep this issue open?

**Comment by goobertron** [comment]
> Still allows to send a message without a "To". Dunno if that is enough to keep this issue open?

I'd say so, yes. It's unexpected behaviour, therefore a bug, therefore definitely worth an open issue!

Thanks for the update.

**Comment by desyncr** [comment]
@goobertron Alright, thought that as this issue is quite old and address primarily autocomplete it was worth closing this one and opening a new one.

**Comment by goobertron** [comment]
Ah, I see what you mean. You're right, as this bug is now fixed it might be better to open a new issue for the remaining bug. But let's just page @Flaburgan and @taratatach to see if this remaining bug can be fixed quickly, to save opening a new issue.

**Comment by Flaburgan** [comment]
@goobertron I think I know where this comes from, and it is specific to Firefox for Android, see [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=737658)

**Comment by Flaburgan** [comment]
@denschub I already commented several times on the bug linked above but no reaction, what can I do to make people looking at it?

**Comment by desyncr** [comment]
@Flaburgan I'm using Chrome on Android. Are we talking about the same issue, now that autocomplete is fixed?

Just to clarify the remaining issue is regarding the form validation of the recipient field ("To"). Not the autocomplete functionality which is now working properly.

**Comment by Flaburgan** [comment]
@desyncr I think you should open another issue for the ability to send a private message with the To field empty.

**Comment by desyncr** [comment]
@Flaburgan Yeah that's what I thought. If @goobertron agrees I'll open a new issue.

**Comment by goobertron** [comment]
Yes, absolutely fine with me. Apologies; I understood your question to mean 'is this remaining bug worth having an issue for?' - to which I answered yes - rather than 'should I open a new issue for the remaining bug?'. I'm sorry if I confused the matter.

**Comment by desyncr** [comment]
@goobertron No problem :) I just created a new issue https://github.com/diaspora/diaspora/issues/5533

**Comment by Flaburgan** [comment]
Not sure this should be close, I think at least Firefox for Android has still troubles handling the auto-completion.

**Comment by desyncr** [comment]
@Flaburgan is right. The issue is still present in Firefox for Android showing the behavior reported at https://github.com/diaspora/diaspora/issues/3852#issuecomment-22794141

**Comment by denschub** [comment]
@Flaburgan 

> what can I do to make people looking at it?

Being patient usually helps a lot. ;)
