### ISSUE TITLE
Posts can be send to nonexistent aspect_ids

### ISSUE THREAD

**Issue by cocreature** [diaspora/diaspora#3862]
If you fake a post request and use a nonexistent aspect_id a post still get's created. It doesn't appear in the stream, but it can be accessed via the direct link.
This doesn't seem like a wanted behavior to me. Instead 404 or something like this should be returned.
##

**Comment by CSammy** [comment]
We just reproduced this, it's still an issue. In addition, posts show up in your personal page, but not in your stream. They show up in the "My Activities" stream.
