### ISSUE TITLE
Fetch facebook group's posts and post to D* under a #tag

### ISSUE THREAD

**Issue by jjjjjjjj** [diaspora/diaspora#3876]

**Comment by svbergerem** [comment]
I guess we aren't allowed to do that:
https://developers.facebook.com/docs/facebook-login/permissions/v2.2#reference-user_groups

> This permission is granted to apps building a Facebook-branded client on platforms where Facebook is not already available. For example, Android and iOS apps will not be approved for this permission. In addition, Web, Desktop, in-car and TV apps will not be granted this permission.

Would be great if someone could confirm and close this issue. @denschub ?

**Comment by jaywink** [comment]
@svbergerem is correct - Facebook has tightened their policy towards web apps pulling in content. Their API clearly states `user_groups` is not something that will be given to any app, so closing this.

If someone wants to make a hack and pull posts in via some mining script and post them via an account to d* - sure they can do that, but hacks such as that should not be part of the core d* server code :)
