### ISSUE TITLE
Tumblr service always posts to all blogs

### ISSUE THREAD

**Issue by Darael** [diaspora/diaspora#3938]
It would be nice if the Tumblr service could post to a subset of a user's blogs; many users run side blogs that general posts shouldn't go to.  Failing that, using their primary blog only is probably a saner default than the current approach, which is to post to all of their blogs.

A very nice feature indeed, but one that would require rather more extensive changes, would be the ability to effectively add a Tumblr blog (with the prerequisite that one had authorised its associated account in D*'s services, of course) to an aspect, so that posts to that aspect would also be sent to that blog.

**Comment by Darael** [comment]
...we've had a patch that provided at least a partial fix (posting to the primary blog only - suboptimal but a damn sight better than the current state) for two years now!  Can't we at least have that integrated?

**Comment by jaywink** [comment]
@Darael feel free to push the patch for review to the core if no one has done so yet! Patches don't magically get pulled in - someone has to submit them as PR's.

**Comment by Darael** [comment]
@jaywink Funny thou shouldst mention it - I'm in the process of doing just that.  Should I say in the PR that it closes this bug, and immediately open another one for actually choosing where to post, or should I just mention that it's partial progress on this one?  IIRC github's smartness means it does matter.

**Comment by gordon-morehouse** [comment]
Thanks for working on this.

**Comment by Darael** [comment]
@gordon-morehouse I just wish I'd got to it sooner - like two and a half years ago when I opened the ticket, or two years ago when @meitar first posted a patch.  Hopefully the PR (which has got to a functional state) will be accepted soon and we can actually use the feature.

**Comment by meitar** [comment]
Oh shit are you using my patch? Sorry, I've been meaning to come back to this but in the interim I stopped using Tumblr all together so I dropped the ball on this.

**Comment by Darael** [comment]
@meitar I based it on thy patch but it's been through a fair number of changes since then thanks to helpful feedback from @jhass (eg it uses `.find` with a fallback rather than `.each`) and I adjusted the spec to match.
