### ISSUE TITLE
Improve automatic scrolling in conversations

### ISSUE THREAD

**Issue by fhsdi2** [diaspora/diaspora#3998]
*Reproduction of misbehaviour #１:*

1. Click the conversation tab
2. Select a conversation that's longer than your page's height
3. Scroll down as much as you want
4. Select another conversation

- Expected result: the "another conversation" is shown from beginning
- Bugged result of now: "another conversation" is at the same height will scrolled "conversation" to

*Reproduction of misbehaviour #２:*

1. Click the conversation tab
2. Select a conversation that's longer than your page's height
3. Scroll down as much as you want
4. Go to any other page of D* or close the window (simply go away from the conversation page)
5. Click the conversation tab again
6. Open the same conversation from step 2

- Expected result: the conversation is auto-scrolled to where you left it
- Bugged result of now: it's shown from beginning again

**Comment by svbergerem** [comment]
I fixed this issue by scrolling to the first unread message. If there is no unread message right now I scroll to the top of the conversation. I could also scroll to the bottom and focus the form. Any opinions which solution is the preferred one? I will open a PR once #5417 has been merged to get rid of the conflicts first. I will also have to write some tests but the fix itself is ready.
