### ISSUE TITLE
Implement realtime chat, possibly using XMPP

### ISSUE THREAD

**Issue by leo-bogert** [diaspora/diaspora#4076]
I've searched all issues for "chat" and all which suggest implementing chat are closed.
There seems to be no explanation of why they are closed, so I am opening a new one.

This issue shall be about basic chat functionality:
- seeing who is online
- chat between two users

For multiuser chat, a separate issue is suitable.

I think it is critical for the success of Diaspora to have chat, so I am requesting that you add this to a milestone.Thank you.

**Comment by jaywink** [comment]
I think this should be closed as initial XMPP chat support has been merged in. Any additions to improve/stabilize it should be separate issues. We should allow @Zauberstuhl to have his $70 bounty after all the work he has put in :)

Agree?

**Comment by tubbo** [comment]
Agreed.

**Comment by davidbaumann** [comment]
I think I must believe you ;)
