### ISSUE TITLE
Add Yammer as a service

### ISSUE THREAD

**Issue by gavioto** [diaspora/diaspora#4137]
I thought yammer is an enterprise growing network. Integrate disapora with yammer could be the key for interoperable bussines.

https://developer.yammer.com/restapi/
https://www.yammer.com/partners/developers/
##

**Comment by davux** [comment]
Respectful bump. Any news?

**Comment by Flaburgan** [comment]
@gavioto @davux when this is indeed interesting, I know nobody on the core team who has time to work on it. So if you want to, or find someone who wants to, you are welcome.

**Comment by gavioto** [comment]
closed by inactivity
