### ISSUE TITLE
sidekiq get backed up and overflows redis limit

### ISSUE THREAD

**Issue by maxwell** [diaspora/diaspora#4159]
still investigating, but my redis 500mb limit overflowed in a single night from the new sidekiq workers.

**Comment by Flaburgan** [comment]
I guess @Zauberstuhl can confirm how things are going there?

**Comment by Zauberstuhl** [comment]
I have no objections. you can close it

**Comment by svbergerem** [comment]
@Zauberstuhl Thanks!
