### ISSUE TITLE
#nsfw posts should not be displayed at all if the user is under 18

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#4171]
This is a suggestion by mrquerelle@joindiaspora.com. He has a child on Diaspora and think that if the user is under 18 years old, #nsfw posts should not appear in the stream.

What do you think?

**Comment by svbergerem** [comment]
Looks like we have different opinions about this feature. If anyone still wants to implement this please open a proposal on loomio first. Otherwise we can close this.

**Comment by gordon-morehouse** [comment]
Can people put links to relevant things on loomio, and Diaspora-on-loomio itself, in any bug which ends up mentioning it? Forking conversations across silos is not helpful without at least a trail for the user to follow.

**Comment by svbergerem** [comment]
@gordon-morehouse [Link to loomio](https://www.loomio.org/g/EseV9p4X/diaspora-community)

**Comment by gordon-morehouse** [comment]
That's a link to the board, not a link to the thread. *sigh*

It is not a good practice to discuss features in >1 place.

In any event, there is no practical way of implementing this feature request. I recommend it be closed.

**Comment by svbergerem** [comment]
No one opened a Loomio thread yet so I'll close this issue. If anyone would like to implement this, please create a new proposal on Loomio first.

**Comment by gordon-morehouse** [comment]
Is github a place where new issues related to Diaspora can be opened, or not?

**Comment by jhass** [comment]
@gordon-morehouse see https://wiki.diasporafoundation.org/How_to_report_a_bug

**Comment by svbergerem** [comment]
@gordon-morehouse Since we use github issues you are of course allowed to open new issues. For this specific issue it was obvious that we don't agree whether it should be implemented so we need a decision first. We use [Loomio](https://www.loomio.org/g/EseV9p4X/diaspora-community) to let the community decide on controversial things.
