### ISSUE TITLE
Reenable Diaspora connect (login with Diaspora)

### ISSUE THREAD

**Issue by ghost** [diaspora/diaspora#4172]
Hi it would be better if can implement alternate login such as Facebook or Twitter.

**Comment by sougonnatakumi** [comment]
Wait. Was this about allowing logging in at diaspora* with a facebook/twitter account, or allowing a diaspora* account to be used to log into other sites the way facebook and twitter can be used?

**Comment by svbergerem** [comment]
Did we implement this with OpenID Connect in #6095?

**Comment by AugierLe42e** [comment]
> Did we implement this with OpenID Connect in #6095?

Yes, we did. I'm currently working on a [*Connect with diaspora**](https://github.com/AugierLe42e/diaspora-connect) button.

**Comment by denschub** [comment]
Cool. So this can be considered done.
