### ISSUE TITLE
New post link is not working in Mobile interface

### ISSUE THREAD

**Issue by Akhilan** [diaspora/diaspora#4176]
New post link is not working in mobile interface. Not known whether is seen in all pods. Me experienced in diasp.org. While clicking the link, it redirects to the stream itself.

**Comment by svbergerem** [comment]
Would be great if anyone could check again if this works now in Opera Mini.

@polsVoice which versions are you using? Are you still able to reproduce this?

**Comment by polsVoice** [comment]
@svbergerem Seems to be working okay now. I tried it on Opera Mini, the stock Android browser, and Firefox.

**Comment by svbergerem** [comment]
@polsVoice Thank you.
