### ISSUE TITLE
Facebook access_token is never refreshed

### ISSUE THREAD

**Issue by Ruxton** [diaspora/diaspora#4188]
If the user adds a facebook service, the access token is stored against the service, but it's never refreshed.  When the access_token becomes invalid, Service::Facebook stops posting the message to facebook.

Things that make the access_token invalid:
- It expires 60 days after it was created (in this case it can be refreshed prior to expiry or each use, so it becomes 60 days from last use, someone always posting would never have to do anything)
- It expires when the user changes their password (in this case, the service can be re-authed, sometimes requires user interaction)
- It expires when the user retracts access to your application (in this case, the user must re-auth the service, always requires user interaction)

from #4189: A workaround is to go to Diaspora\* settings, remove Facebook and add it back. We should fix this by somehow renewing the token in the background after some period of time.
##

**Comment by HankG** [comment]
I believe this should be closed since the Facebook API prevents posting and the whole feature is no longer available.

**Comment by denschub** [comment]
Obsoleted by #7874.

**Comment by jhass** [comment]
Do we have a similar ticket for another service?

**Comment by HankG** [comment]
@jhass not that I can see
