### ISSUE TITLE
Codeblock still parses some stuff

### ISSUE THREAD

**Issue by DeusFigendi** [diaspora/diaspora#4201]
Hey, I just recognized Diasporas codeblock still parses some stuff and I'd guess it should not parse anything.

I just used an url in a codeblock and it was extended to a markdown-link. And this markdown-link wasn't parsed itself.

So if I use http://www.example.com in a codeblock it's exteded by [] and ()

    http://www.example.com becomes
    [http://www.example.com](http://www.example.com)

And I remembered the same happens to hashtags, those are parsed too in codeblocks.

On reporting this bug I tested some more cases, these are all fine:

----

**markdown?**

    This **is** a *codeblock* with some [markdown](http://www.example.com) in it

**escaped markdown?**

    This is a \*codeblock\* with some escaped markdown in it.

**oEmbed?**

    This codeblock http://www.flickr.com/photos/64762592@N02/8949132474/ contains some https://www.youtube.com/watch?v=Qcl2fssnMkM oEmbed-urls

(here the urls still become markdown-hyperlinks but I'd guess they wouldn't become oEmbedes)

**markdown-images?**

    This is a codeblock with an ![image](https://pod.geraspora.de/uploads/images/thumb_small_b5cf389d2ac8c014d417.png) in it.

**more markdown?**

    * This is a multi-
    * line codeblock
    * that seems to
    * represent a list

----

Like I said, that stuff is fine and (more or less) un-parsed.

**Comment by jhass** [comment]
Fixed by #5526
