### ISSUE TITLE
Notification as a popup box

### ISSUE THREAD

**Issue by Akhilan** [diaspora/diaspora#4206]
Along with the notification panel at the top, new notifications should be appeared as a pop up box in order to get more attention.
##

**Comment by Flaburgan** [comment]
As @jhass said, I feel like the auto-updating counter in the header is enough. Error message / confirmation alerts are a different topic, see https://github.com/diaspora/diaspora/issues/4486

**Comment by SuperTux88** [comment]
And I think this was fixed with #6952 anyway :)
