### ISSUE TITLE
install script does not check for required binaries

### ISSUE THREAD

**Issue by chaosmatic** [diaspora/diaspora#4218]
I'm running Ubuntu 12.04

From the prereqs mentioned in http://wiki.diasporafoundation.org/Installing_on_Debian I had installed only nodejs, rvm, ruby, rubygems and rails. I had not installed any of the dependencies for imagemagick, redis, mysql, mysqlite, openssl or ffi.

The install script did not complain until it crashed during 'bundle install' due to the missing binaries.

**Comment by jhass** [comment]
We decided to drop the install scripts.
