### ISSUE TITLE
Receive email notifications for non-contacts posts

### ISSUE THREAD

**Issue by svbergerem** [diaspora/diaspora#4276]
I'd like to see "also commented" notifications for non-contacts posts in the header.

In the settings I can decide if I want to
"Receive email notifications when someone also comments on your contact's post"

I think the same thing should be possible for non-contacts.

**Comment by svbergerem** [comment]
While testing #5522 I received a notification email for a non-contacts post. (A contact also commented on that post) I guess the problem is that you don't receive a notification at all in most cases so I think that this isn't specific to email notifications. However, once we fixed #5522 we'll need to check again if email notifications are working properly. In that case we would just have to improve the wording on the settings page.

**Comment by Flaburgan** [comment]
Yeah IMO this can be closed, it is not related to email, simply that notifications are not trigged, so #5522 covers that.

**Comment by svbergerem** [comment]
@Flaburgan We would at least have to improve the wording on the settings page. That's where the confusion came from.

**Comment by jaywink** [comment]
AFAICT this can be closed as better described by #5522. Poke me if wrong.

**Comment by svbergerem** [comment]
@jaywink Did you read the discussion for this issue?

> However, once we fixed #5522 we'll need to check again if email notifications are working properly. In that case we would just have to improve the wording on the settings page.

This issue is related to #5522 but I don't think that this is a duplicate. If fixing #5522 also fixes email notifications (I am not sure if that is the case) the wording on the settings page would still be an issue. I am not going to reopen this because I don't want to start an 'edit war'. I'll leave it up to you to decide if this issue should be reopened or if we should expand #5522 by the aspects that were mentioned in this issue.

**Comment by jaywink** [comment]
Yeah I read the discussion and figured this could be closed ;) No need for edit war, my bad, I'll reopen. Once #5522 is fixed, we can come back to this :dancers:

**Comment by svbergerem** [comment]
#5522 has been fixed and #4912 improved the wording on the settings page.
