### ISSUE TITLE
Round user avatar

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#4288]
I saw that in the settings, where you can upload a new profile picture, your avatar is displayed rounded (<code>border-radius: 5px; box-shadow: 0px 1px 2px #666;</code>)

I wonder if it's a good idea to display it like that everywhere.

This how it can looks:

### before
![before](https://f.cloud.github.com/assets/930064/758667/4d2f3e6e-e747-11e2-8795-a93a1294eeaa.png)

### after
![after](https://f.cloud.github.com/assets/930064/758668/52dcbca6-e747-11e2-808b-7312d10abb8c.png)

What's your opinion about that?

**Comment by svbergerem** [comment]
Implemented by #5733.
