### ISSUE TITLE
Own template

### ISSUE THREAD

**Issue by max258** [diaspora/diaspora#4297]
Maybe for someone is it only brainstorm idea, but for me not.
Very usefull can be option use own template.
Not only changing some values in scss or something else, but complex solution.
Now is changing the template very hard and update can destroy new structure.
New folder with templates can be good idea and in confing specifing the template.

**Comment by efstrian** [comment]
We could create fixed color themes for the users to choose, i.e. dark red, dark green, magenta. This way, the ui would be a bit more customizable, but still elegant and true to diaspora's initial design. What do you think about it?

**Comment by efstrian** [comment]
Hi! We are working on implementing a way for the user to opt for one of a few fixed color themes, but we've run into a problem. The header is one of the elements that should change color, and this could be easily done with CSS3 shadows in order to recreate the gradient effect of the current implementation. The problem is that the current logo is not transparent. Any idea how to get past this?

(This feature is still desired, isn't it?)

**Comment by max258** [comment]
@efstrian Good work! I think you can change the header with contributing to git. But not sure if will be this accepted. I think yes, but inform in creators of diaspora*

**Comment by efstrian** [comment]
@max258 No problem if this does not get accepted, we're just trying to help after all. Going from the current png to a CSS background should be both visually impressive and highly configurable, yet one should carefully consider performance issues (if there are any).

We do need a transparent logo to use in the header to try it, though.

**Comment by Flaburgan** [comment]
We are talking about https://github.com/diaspora/diaspora/blob/develop/app/assets/images/branding/header-logo.png

No problem to remove the background of that file (and the @2x version). Just do it and open a pull request.

**Comment by efstrian** [comment]
@Flaburgan, I'm not sure how to remove the background, because of the relatively low resolution. There isn't any transparent version available, is it?

**Comment by jhass** [comment]
We decided to implement color themes and that's done by #6033.
