### ISSUE TITLE
Two factor authentication

### ISSUE THREAD

**Issue by raisty** [diaspora/diaspora#4299]
I think there should be two step verification as well.
Use open ID can be usefull too.
##

**Comment by jaywink** [comment]
I saw a bounty was posted on this issue which I guess means we should at least think about how this could be implemented. AFAIK, two-factor identification usually means SMS. I don't believe that is a possibility in the decentralized environment were hundreds of podmins would have to start signing up to SMS gateways, which probably are not free to use.

Are there any other possibilities outside SMS for two factor authentication which would work in a decentralized environment? If not, I suggest we strongly think about closing this issue from the core so that at least bounties will not be fruitlessly wasted on something that is not possible to implement in a decentralized world in a way that *most* of the podmins will be able to activate the feature.

**Comment by denschub** [comment]
Usually, two-factor authentication means TOTP, not SMS. I'm pretty sure there are devise plugins for TOTP out there, so besides the user preference storing and modifying the UI, this should be one of the easier features.

**Comment by ABISprotocol** [comment]
Hello, there may be a decentralized 2FA out there.  Possibly you could use one of a few different options depending on what you want to do. 
1) something like what has been already mentioned by @denschub - that is TOTB / devise, such as
https://github.com/authy/authy-devise
or
2) BitID for open / decentralized 2FA https://github.com/bitid/bitid

Or, maybe 2FA isn't what's needed.  Per Bruce Schneier, something else may be needed entirely:
https://www.schneier.com/blog/archives/2006/11/fighting_fraudu.html

**Comment by genma** [comment]
CozyCloud has implemented Two Factors authentication (https://forum.cozy.io/t/two-factor-authentication-in-cozy/2568) maybe it could help to choose "technology". My 2 cents.

**Comment by svbergerem** [comment]
Here is a devise plugin for TOTP: https://github.com/tinfoil/devise-two-factor

**Comment by ABISprotocol** [comment]
Thanks @svbergerem - that's a good one.

**Comment by tchncs** [comment]
Mastodon just got tinfoil/devise-two-factor - i really enjoy it.
Would be nice to see it in diaspora* as well.

**Comment by oliof** [comment]
I would like to see 2 factor authentication support for u2f/fido tokens. Sample implementation at https://github.com/TwoFactorAuth/ruby.

**Comment by tursiops33** [comment]
Hi, I'm also interested in this, and a quick look on the Web, found this https://dynalogin.org it supports openid which diaspora already has, and is open source.

**Comment by denschub** [comment]
Please stop using this issue as a platform to say "I want this, too!" or to publish links to to frameworks/services for 2fa. Either someone steps up and does the research, actually compares all solution and implements it or it's not going to happen. Causing traffic in this issue and mailspam just to share links isn't really worth it.

**Comment by SuperTux88** [comment]
This is still a valid feature request.

**Comment by SuperTux88** [comment]
at least I (and I think many others too) want this feature, I just didn't have the time yet to work myself on it :)

**Comment by tursiops33** [comment]
I'm not a coder but I can increase the bounty if that helps anyone get this done faster

**Comment by SuperTux88** [comment]
At least for me money isn't the problem, time is the problem. But if anybody want's to do that, but the bounty is too low, they can set a goal via bountysource.

**Comment by raisty** [comment]
If the time is problem, there is problem with dev team / planning also.
This is here from 2013.

**Comment by SuperTux88** [comment]
It's a hobby project, all devs work in their free time, and there aren't many active devs ... so there isn't a problem planning. We can't "plan" how other people use their free time and we can't force anybody to do something. it's up to everybody how much of their free time they use. So it's normal that it takes time.

**Comment by Oreolek** [comment]
Yes, it's been 5 years and the inflation ate a significant portion of the bounty (currently $40). You can help by spreading the link because more Ruby devs see this, the better are chances for someone to come in and implement it.

**Comment by Flaburgan** [comment]
@lislis don't forget to [claim your bounty](https://www.bountysource.com/issues/459025-two-factor-authentication). If you don't want to get the money for you, you can put it on new issues ;)
