### ISSUE TITLE
"Add contact" button should be visible when not logged in

### ISSUE THREAD

**Issue by mlinksva** [diaspora/diaspora#4317]
And should lead somewhere explaining that you need to log in to this pod, or if your account is on another pod, how to remote follow. Right now if one arrives at a profile page, via a link elsewhere on the web, perhaps their first time visiting a diaspora pod, it is a bit mysterious how to proceed.

http://quitter.se/conversation/1887485#notice-2079705 is what led me to submit this issue -- I linked to a profile, someone who saw that link said "Thanks for the weblink. Unlike Friendica I did not find any approach in Diaspora to 'follow' rysiek. Did I overlook sth?"

**Comment by Flaburgan** [comment]
https://github.com/diaspora/diaspora/issues/4317 also deals with this topic and contains mockups and more discussion. Maybe this issue can be closed and we should continue to think about it there, or we want to keep this one open because it's more specific?

**Comment by SuperTux88** [comment]
> #4317 also deals with this topic ...

This is #4317? 😉

**Comment by Flaburgan** [comment]
Sorry I was talking about https://github.com/diaspora/diaspora/issues/4773

**Comment by denschub** [comment]
Fla is right, #4773 contains more discussion, so I'm closing this.
