### ISSUE TITLE
User setting for default post visibility

### ISSUE THREAD

**Issue by mlinksva** [diaspora/diaspora#4319]
I usually intend to make posts public, but forget to change from "all aspects" to "public" before posting. I'd enjoy a preference which set my default to "public".

**Comment by Arcurus** [comment]
yea a default selection configuration would be great!

**Comment by unity100** [comment]
This feature would be VERY helpful for those of us who use their diaspora account for sharing news and activism.

**Comment by duncane** [comment]
Bumping cause this feature is definitly missing in Diaspora*.

**Comment by nielspetersen** [comment]
This issue is part of the current issue (13th) of the RubyIssues. https://rubyissues.ongoodbits.com/. :gem:

**Comment by hilkoc** [comment]
A [pull request](https://github.com/diaspora/diaspora/issues/7118) for this has now been opened.
