### ISSUE TITLE
Embedding Bandcamp audio

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#4325]
I've been looking into how we might embed audio from Bandcamp.

It seems that Bandcamp puts barriers in the way of doing a straight oembed.

However, I have noticed that there is link to an embedded player contained in the meta information for each Bandcamp page.

I've checked this out for several different artists, and it appears in the same format for each of them, so I'm assuming this is universal for Bandcamp. There is a separate https embed, which is the one we'd want.

See, for example, http://takedaband.bandcamp.com/album/edo-1

Under 
```meta property="og:video:secure_url" ```
there appears
```content="https://bandcamp.com/EmbeddedPlayer.swf/size=venti/album=55213112/" ```

Copying this URL and pasting it into a browser produces a nice little embedded player with artist and album titles, artwork, track listing and everything you need.

Could a way be found to embed this in Diaspora? If anyone wants to have a go, I'd be really grateful.

There are some artists who use Bandcamp's site and software but have a redirect to their own domain. See for example http://music.farblackfurlong.com/album/haidd-2

This is a Bandcamp page, but the domain is the band's own. If you could find a way to recognise it as a Bandcamp page (possibly by something in the header information) in spite of the domain being different, and still embed it, that would be fantastic.

I guess the presence of
```meta property="og:video:secure_url"content="https://bandcamp.com/EmbeddedPlayer.swf/ ```
in the header (which it is for this last example, even though the visible domain is different) would be a way to achieve this recognition.

I don't really understand the science of embedding, so you'll have to forgive me if I'm talking a load of nonsense here, but I was really pleased to find the existence of an embedded player hidden in Bandcamp's pages, and hope that something can be taken and used from this.

In hope, and with thanks in advance.

**Comment by svbergerem** [comment]
Fixed by #7043.

**Comment by goobertron** [comment]
I've only just noticed that Bandcamp embeds now work. Thank you so much, @svbergerem!
