### ISSUE TITLE
Accept CAcert certificates

### ISSUE THREAD

**Issue by cpt1gl0** [diaspora/diaspora#4345]
I think it would be a really good idea to accept CAcert as certificate authority. A lot of people have their server certificates signed by CAcert and will not be able to communicate with other pods properly if Diaspora does not accept CAcert. 

As apache (and any other web-server) supports only one SSL-identity per IP it's not possible to have startSSL for some diaspora.host.domain virtual host, so server admins already using CAcert would have to use a separate IP for diaspora or migrate to startSSL, which they will - because of being annoyed - not do most likely.

Is there a good reason not to accept CAcert certificates?
If not I would really beg the developers to accept CAcert for the benefit of a growing pod-network!

**Comment by jaywink** [comment]
The idea about accepting CACerts was rejected in [a community vote 2 years ago](https://www.loomio.org/d/RxIjdKFZ) - so closing this issue. Please continue the discussion or open a new vote on Loomio to get this reopened.
