### ISSUE TITLE
Crossposting to Twitter with @mentions in post fails

### ISSUE THREAD

**Issue by samtuke** [diaspora/diaspora#4391]
This message crossposted to twitter, I assume because it included a mention:

```
Crowdfunding campaign for superior Free Software #GIF alternative nears initial goal http://s.coop/1s227 via @tin_man@joindiaspora.com #ANPG
```

The characters remaining estaimation was also inaccurate - Diaspora states that 1 character remains of the 140 for Twitter, but the same message in the twitter composer UI states that the message is 2 characters over the maximum.

Tested on joindiaspora.com

**Comment by svbergerem** [comment]
No response for about a year. Feel free to reopen if anyone is able to reproduce this.
