### ISSUE TITLE
Expand all images in the single post view

### ISSUE THREAD

**Issue by jhass** [diaspora/diaspora#4421]
Currently the single post view has the same behavior than the stream when displaying images. It should use the extra space and display all images in full size.

**Comment by Anime-Machina** [comment]
Personally I believe Lightbox will br a nice solution. But personally I see the best solution for the end user. For examle some white space with a grid of images next to it would be a sweet solution.

**Comment by svbergerem** [comment]
I'm quite contented with the current situation. There is also #6649 which could be a further improvement for the UX. Therefore I think we can close this issue. Any objections?
