### ISSUE TITLE
Polish single post view

### ISSUE THREAD

**Issue by jhass** [diaspora/diaspora#4425]
This is an issue to track various little design glitches in the single post view. Send an individual pull request for each item.

* [x] <del>Replace blue border and box shadow around comment field with the standard one on all other pages</del>
* [x] <del>Make the notifications dropdown exactly look like on the other pages, see [this comparison](https://github.com/diaspora/diaspora/pull/4410#issuecomment-23061427)</del>
* [ ] Posting a comment scrolls to the top of the page.

**Comment by svbergerem** [comment]
Posting a comment doesn't always scroll to the top of the page. If the post is long enough it scrolls to the end of the post. I think that happens because we rerender the comment stream so for a short moment the height of the page decreases if the comment stream is longer than the post.

**Comment by denschub** [comment]
Closed with #7089.
