### ISSUE TITLE
Distorted elements in the new single post view

### ISSUE THREAD

**Issue by shmerl** [diaspora/diaspora#4453]
Some elements in the new single post view look distorted in Firefox 23.0.1 (current Debian testing). See the screenshot below:

![diaspora_bug1](https://f.cloud.github.com/assets/310927/1039218/d3bf41ca-0f7b-11e3-8845-2a6ac6663eab.png)

It seems to be some font issue. Here Diaspora is shown with a darkish stylish theme, but it doesn't affect this issue. It's present with the theme switched off the same way.

**Comment by maxwell** [comment]
Should be fixed!  Let me know if you see anything else

**Comment by shmerl** [comment]
Yes, it's fixed now. I uninstalled fonts-entypo for a test, and it still looks good.
