### ISSUE TITLE
Port everything to Bootstrap and drop Blueprint

### ISSUE THREAD

**Issue by jhass** [diaspora/diaspora#4466]
Disclaimer: As usual this is a meta issue, don't even try to solve it in one pull request, we more than happily accept partial contributions towards this goals.
# <del> Phase I </del>

Done!
# Phase II

Cleanup codebase. This can be started once the entire desktop site is on Bootstrap.
- [x] <del>Drop `@css_framework` hack from controllers</del>
- [x] <del>Stop importing Blueprint on the desktop site</del>
- [x] <del>Finally get rid of CSS code in application.sass. Convert still relevant code to distinct SCSS files</del>
- [x] <del>Drop all Blueprint files from app/assets/, lib/assets and vendor/assets</del>
- [x] <del>Make sure all unneeded CSS files are removed</del>
- [x] <del>Merge code in app/assets/stylesheets/new_styles with leftovers in app/asset/stylesheets and move everything out of new_styles/ into the parent folder.</del>
- [ ] Evaluate if Bootstrap overrides can be simplified and cleaned up.
- [ ] Reevaluate nested layout system, still needed? Can be reorganized?
##

**Comment by goobertron** [comment]
Congratulations to everyone involved in completing Phase I - great work, everyone!

**Comment by danger89** [comment]
Yeah! Congratz! :dancer:

**Comment by AugierLe42e** [comment]
Is this still relevant ?

**Comment by jhass** [comment]
Sure, if you actually read the original posts, there are still open items on the list.

**Comment by danger89** [comment]
Well done so far updating to Bootstrap! 

Ps. is there any update about how to make the decentralized network in a way "more" centralized via some protocol, so people can find each other without knowing all the pod names?

Similar to decentralized DNS systems or YaCy search engine.

**Comment by svbergerem** [comment]
Can we close this issue? I'd say the overrides have been reorganized and I don't see any reason for removing the nested layout system.

**Comment by jhass** [comment]
Sure

**Comment by Flaburgan** [comment]
Hm, so who should claim the bounty here?

**Comment by Flaburgan** [comment]
I would say @pablocubico @svbergerem and @blase did most of the job here.

**Comment by pablocubico** [comment]
Hi guys! No need for bounty, I didn't know there was one! Can I donate it back to the project or something?

**Comment by Flaburgan** [comment]
If you claim it on bountysource, you can then post it on other bounties on the website (either on diaspora* issues or on other projects). I guess you can also donate it to the diaspora* team there.

**Comment by SuperTux88** [comment]
I think bountysource can't split the bounty, so issues like this are bad for bounties in general. Also 100$ from @KentShikama were added after the work was already done (which is 95% of the bounty).

I think we should claim this as the diaspora* team (@denschub said that this should be possible, I don't know how) and then maybe Kent can tell us if he wants us to put his 100$ to another issue.

**Comment by goobertron** [comment]
> If you claim it on bountysource, you can then post it on other bounties on the website (either on diaspora* issues or on other projects).

I would say that is a bad way to donate funds back to diaspora\*, as that way Bountysource will rake off their 10% (or is it 15%?) cut. If there's a way of simply redirecting it internally to the project account, that would be better.

Is there a way to pay money out manually? That way it could be split according to who did the work. If that is not possible, it's just another reason I don't like using Bountysource, to add to the many already existing.

Anyway, thanks and congratulations to those who worked on and completed this issue.

**Comment by Flaburgan** [comment]
>I would say that is a bad way to donate funds back to diaspora*, as that way Bountysource will rake off their 10% (or is it 15%?) cut

It won't. They are taking a fee only when you're doing a cashout. The money can move between issues without anything being paid.
