### ISSUE TITLE
Mentions should fetch the profile if it doesn't exist locally yet

### ISSUE THREAD

**Issue by jhass** [diaspora/diaspora#4491]
I thought we had that functionality, but apparently we don't.

**Comment by Flaburgan** [comment]
This should have the federation label.

**Comment by pravi** [comment]
@cmrd-senya has added this issue as a stretch goal to his account backup/restore crowd funding https://www.indiegogo.com/projects/account-backup-and-restore-for-diaspora--3#/ He will work on this if he reaches 4200 €, he'll work on this.
