### ISSUE TITLE
@mentions not working for names in Malayalam language

### ISSUE THREAD

**Issue by balasankarc** [diaspora/diaspora#4493]
Cannot mention someone using @mentions if they are using their name in Malayalam Language (language code : ml) .. For eg: I cannot mention @ബിപിൻദാസ് in Diaspora, because his name is not written in English.

**Comment by cmrd-senya** [comment]
This is probably a blocker for the issue: https://github.com/podio/jquery-mentions-input/issues/117

**Comment by svbergerem** [comment]
This might have been fixed on the develop branch in #6728. Would be great if someone could try this again.

**Comment by denschub** [comment]
Closing this. Please reopen if this is still an issue (which I doubt :))
