### ISSUE TITLE
diaspora is broken on ipad (safari, chrome)/android (webkit based browsers/opera)

### ISSUE THREAD

**Issue by pravi** [diaspora/diaspora#4505]
Desktop version - stream not loading, can't post 

Mobile version - can post, can't upload photos, can't add friends.

It is not a pleasant experience at all.

Confirmed by Akhilan on Android - https://poddery.com/posts/775518

**Comment by svbergerem** [comment]
@Flaburgan could you try again with the current develop code?

**Comment by Flaburgan** [comment]
So, on diaspora-fr.org, updated this morning to the last develop code without any modification.
- With iPad 3rd (iOS 5.1) : The publisher is correctly working and the stream is loading on desktop version. The upload image button still doesn't work on mobile version (though I also encountered this problem with Android, so this is not iOS only).
- With iPad 2 (iOS 4.3.2) the design of the sign in page is broken, and I'm not able to log at all (once I tap the login button, I only have a white page. Not sure what to grep in the log).
![bs_ios_tablet_ipad 2-4 3 2](https://cloud.githubusercontent.com/assets/930064/12915292/8e32effa-cf2a-11e5-8a4d-10f405c3923f.jpg)

Which makes me wondering, which version do we want to support exactly? iOS 4 is **very** old.

**Comment by denschub** [comment]
SInce it's Apple, how about... the latest?

**Comment by Flaburgan** [comment]
Apple also doesn't provide upgrade for "recent" devices so I suggest to chose according to the actual market share. Good news: most of [the users upgraded](https://developer.apple.com/support/app-store/), we have 76% of iOS 9 and 17% of iOS 8 so those two looks enough to support imo. I just tested with iOS 8.1 on an iPad Air and was able to scroll the stream, open the publisher and post a message with the desktop version, and to upload a mobile picture with the mobile one, so I think this issue can be closed. Don't hesitate to tell me if you want something specific to be tested :)

**Comment by denschub** [comment]
I knew of apples version distribution, that's why I commented "the latest" ;) Great it's working on newer iOS versions.

\*happily closing issues\*
