### ISSUE TITLE
Conversation notification are not updated correctly

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#4572]
TL;DR: the mail notification does -1 instead of -n where n is the number of message displayed.

**Steps to reproduce:**

* Write a private message with an account A to an account B (this is called a conversation).
* Write 2 other messages in this conversation with A.
* Login with B. A red 3 will be displayed on the mail icon in the header.
* Click on the mail icon and then on the corresponding conversation

**Actual behavior:**
The notification will update, now displaying 2

**Expected behavior:**
The notification should go down to 0 instead of 2, because every message was displayed.

**Comment by svbergerem** [comment]
I fixed this bug and will open a PR soon. See https://github.com/diaspora/diaspora/issues/3998#issuecomment-73643220.
