### ISSUE TITLE
Improve Login button

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#4588]
I had feedback from different users who told me that the Login and Sign up buttons are not easy to find. The contrast is low, and it's not well located (that was their opinion).

![inscription](https://f.cloud.github.com/assets/930064/1529108/63ce5d36-4c27-11e3-949f-2df30400fc0f.png)

It's true that websites now tend to display a big box on the first page to allow user to login. (See Google, Facebook, Twitter...) So I was wondering, what is the point of the /users/sign_in? Do we really need a entire page dedicated to that?

I guess the login form are not in the middle of the first page because the page is set by the podmin himself. So if we don't want to add it there, what about adding the two fields (username and password) directly in the header? Or we can also put a stronger contrast, like https://diasporafoundation.org "Host a pod" and "Join us" buttons.

**Comment by Flaburgan** [comment]
We can have another look on that now that https://github.com/diaspora/diaspora/pull/6109 is merged. Maybe add the fields to log in on the default page with https://github.com/diaspora/diaspora/pull/6268 ?

**Comment by svbergerem** [comment]
@Flaburgan #6268 has been merged with a login form on the home page. The link in the header also changed. Would you mind closing this issue?

**Comment by Flaburgan** [comment]
Yep, good enough to me :)
