### ISSUE TITLE
Add support for posting to pump.io

### ISSUE THREAD

**Issue by cannycartographer** [diaspora/diaspora#4633]
Would be great to have this in the spirit of supporting other federated social networks. Cheers!
##

**Comment by svbergerem** [comment]
There are two open issues about [pump.io](https://github.com/e14n/pump.io). (This one and #4643) The last commit for pump.io has been a year ago, the builds are failing and the main author [confirmed a year ago](https://github.com/e14n/pump.io/issues/1033#issuecomment-46784862) that the master branch is broken. Does anyone know if there is still some activity around pump.io? Are there any users?

**Comment by jaywink** [comment]
The main pump.io dev Evan is working as one of the core people in the W3C SocialWG to make a new standard for federated web apps. I think he mentioned he will rewrite pump.io once that is done - so I'm guessing no there will not be any more commits to the current version, but yes, there are people using the current one.

**Comment by tonin** [comment]
pump.io is now again actively developed and the developer base is a bit wider. Last release (3.0.0) was about a month ago: https://github.com/pump-io/pump.io/releases

**Comment by strugee** [comment]
Correct; I'm the lead maintainer nowadays and you can mention me for questions, etc. We do monthly releases, alternating between betas and stables.

**Comment by Flaburgan** [comment]
Last release of Pump.io was in 2020, and the last one containing notable commits was in December 2017. Except if somebody stands up, I would propose to close this issue.

**Comment by strugee** [comment]
This makes sense to me. I'm still thinking about what to do but most of our users have moved to ActivityPub anyway and I'm strongly considering officially sunsetting the project, painful as that is to say
