### ISSUE TITLE
E-mail notification about reshare should always contain the content of the post

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#4649]
When someone is resharing one of your post, if it's a post that you reshared, you only have "a message" in the content of the email. The email should contain the post reshared instead, because a reshare is public.

**Comment by svbergerem** [comment]
Users now always reshare the original post so the original author will receive a notification. When you like a reshare, the notification email contains the content of the post. When you comment on a reshare, the notification email contains the content of the comment. (all cases tested on my dev pod) I think we can close this issue now. @Flaburgan what do you think?

**Comment by Flaburgan** [comment]
I don't get if this was the intentional behaviour but PostA reshared by UserB => ReshareB, UserC reshares ReshareB, now UserB doesn't have a notification at all... ??

**Comment by svbergerem** [comment]
UserC always reshares the original post. We changed that some time ago.

**Comment by Flaburgan** [comment]
Okay so yeah this can be closed, as UserB doesn't receive a notification anymore. But I guess to receive a notification was nice, so we should re-add that.
