### ISSUE TITLE
Remove the e-mail when deleting a user

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#4684]
When a user delete is account, we delete everything except his row in the users table to block a new user to register with the same handle to avoid identity fraud. But in consequence, the email is also kept, so if the user wants to register again, he has to choose another email. This is annoying, so I propose to update the email adding "-old" at the end when we delete a user, to still have the email in case we want to join him, but allow him to register again with the same email.

**Comment by svbergerem** [comment]
Closing an account sets the email to `deletedaccount_{id}@example.org`: https://github.com/diaspora/diaspora/blob/develop/app/models/user.rb#L537. I tried it on my dev pod and can confirm the behavior. It was implemented in 2011: [commit](https://github.com/diaspora/diaspora/commit/fe82cd66093beedf18ea0508532fef890cdc42f0). @Flaburgan feel free to reopen if we keep the email address somewhere else by mistake.
