### ISSUE TITLE
NSFW hides user name and avatar in mobile view

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#4685]
In the desktop view, when a post is hidden as NSFW, the name and avatar of the person who shared it is displayed. 

![nsfw_desktop](https://f.cloud.github.com/assets/2530168/1902394/ca99c88c-7c71-11e3-8f73-a76fd02fc66e.png)

However, in the mobile view, the entire post is hidden, including the name and avatar.

![nsfw_mobile](https://f.cloud.github.com/assets/2530168/1902395/da4af652-7c71-11e3-802c-0fd07bfbd5e4.png)

It is useful to have the name and avatar of the sharer displayed as seeing who posted it can help to decide whether it's worth displaying the post or not.

**Comment by RichKavanagh** [comment]
As this is by-design, is it a feature request and not a bug?

> It is useful to have the name and avatar of the sharer displayed as seeing who posted it can help to decide whether it's worth displaying the post or not.

Yup, I'd definitely agree with that :+1:

**Comment by jhass** [comment]
It's a bug because it's inconsistent between mobile and desktop.
