### ISSUE TITLE
Photo displayed in post multiple times

### ISSUE THREAD

**Issue by svbergerem** [diaspora/diaspora#4697]
Example: https://pod.geraspora.de/posts/1836156
The photo is displayed twice. When looking at the [json](https://pod.geraspora.de/posts/1836156.json) you see that the two photos have the same guid but a different id.

**Comment by aykevl93** [comment]
I still see the bug occurring on diasp.eu and pod.orkz.net. It looks like it only occurs while federating (people on the same pod don't see duplicated images) and that a photo is shown up to six times. So maybe it's related to federation and retrying to push images?
I'm using diasp.eu (version 0.4.1.2-p3c87df88) with a lightbox but that doesn't change anything. Multiple images are shown in the stream and even the notifications say there are six images while there was only one posted.

**Comment by Flaburgan** [comment]
>the notifications say there are six images

Where do you see that?

**Comment by aykevl93** [comment]
It says:

> &lt;person A> and &lt;person B> also commented on &lt;person B>'s post 6 photos by &lt;person B>.

**Comment by Flaburgan** [comment]
I think you have an addon or a script like Greasemonkey, I never saw that myself in diaspora*.

**Comment by aykevl93** [comment]
Well, no. It is exactly the same on Firefox for Android with no add-ons installed.
Note that it is a post without text, just one photo.

**Comment by denschub** [comment]
Closed by #6873.
