### ISSUE TITLE
Improvements for install.sh

### ISSUE THREAD

**Issue by Ryuno-Ki** [diaspora/diaspora#4750]
Good morning :)

I'm able to run a pod in development mode since 7 hours :D

But I have some suggestions to improve the script!

First, make sure (or check) to install ruby 2.0.0-p??? in forehand. <code>rvm get stable</code> pulls a v1.9 on my Sabayon Linux machine ;-)

Second, make sure (or check) for a login shell: <code>/bin/bash --login</code>.

Third, check, wether RUBYOPT is unset (common issue on Gentoo systems).

Fourth, maybe offer a hint to <pre>/usr/bin/mysqlaccess.conf</pre> for database credentials (this was my obstacle). I'm not sure, wether this file exist on non-Sabayon distros, though. But a little guidance for checking of a database user & permission is appreciated.

**Comment by jhass** [comment]
We decided to drop the install scripts.
