### ISSUE TITLE
Rendering a mention adds a space

### ISSUE THREAD

**Issue by Airon90** [diaspora/diaspora#4767]
You can see it here: https://diasp.eu/posts/1565811

I tagged my friend and before the question mark there is a space.
It should not appear: in Italian language is an error to add space before punctuations.

**Comment by svbergerem** [comment]
I think I fixed this [here](https://github.com/diaspora/markdown-it-diaspora-mention/commit/b899597dee88c8b4b3384604db6fa74b27ad211e). The fix will be in the next release of markdown-it-diaspora-mention.

**Comment by goobertron** [comment]
@svbergerem any way of testing your fix, so we could (hopefully) close this issue? Could we release the new version of markdown-it-diaspora-mention, or are there compatibility issues with diaspora code earlier than 0.5?

**Comment by svbergerem** [comment]
@goobertron markdown-it-diaspora-mention has been integrated after the last release and this is just a ui fix so there are no compatibility issues with earlier releases.

I guess there is not much you can do right now. I will release a new version of markdown-it-diaspora-mention (and other markdown-it plugins) soon and update the version in the Gemfile afterwards. I don't have much time right now but I'll be able to do that stuff in a few days.

**Comment by goobertron** [comment]
That's fantastic, thank you so much. Didn't want to put pressure on you, but I wasn't sure of the status of this. I really appreciate your work.
