### ISSUE TITLE
Sidebar should indicate proper way to report bugs on github

### ISSUE THREAD

**Issue by jaywink** [diaspora/diaspora#4779]
Now it says "use #bug". It should say to report issues on github. Maybe the whole text should be rewritten in this section.

https://iliketoast.net/posts/183549#23f45ca12300d9f3

**Comment by svbergerem** [comment]
@Flaburgan Are you going to fix this? Adding a link to https://wiki.diasporafoundation.org/How_to_report_a_bug sounds good to me. If you want this could be part of #6535.
