### ISSUE TITLE
RTL languages: Sidebar icons overlapping text

### ISSUE THREAD

**Issue by itais** [diaspora/diaspora#4783]
With RTL language (Hebrew, Arabic) selected as interface language in d* the sidebar icons overlap the titles.

![icons](https://f.cloud.github.com/assets/6691493/2178400/860da684-9666-11e3-8d6a-d1ad2d8a3e7f.png)

edited to reflect this issue being present in Arabic as well

**Comment by svbergerem** [comment]
I think we fixed this by porting the stream to Bootstrap:
![RTL](https://cloud.githubusercontent.com/assets/3798614/7036048/9685798a-dd8f-11e4-87aa-4bb8008ecfb1.png)
