### ISSUE TITLE
RTL languages: Can't change profile picture in Firefox

### ISSUE THREAD

**Issue by itais** [diaspora/diaspora#4784]
With Hebrew (edit: Arabic as well) selected as interface language in d* and while using Firefox under windows 7, clicking on the "upload a new profile photo" button ("העלאת תמונת פרופיל חדש" - I will improve this translation and others later in WebTranslateIt) in settings / profile doesn't do anything.
It is working fine in IE, or in Firefox while English is the selected language in d*.

Here is FF's console output for the page, hope this helps:

    19:24:12.594 GET https://diasp.eu/profile/edit [HTTP/1.1 304 Not Modified 140ms]
    19:24:12.682 The site specified an invalid Strict-Transport-Security header.[Learn More] edit
    19:24:12.690 Use of getUserData() or setUserData() is deprecated.  Use WeakMap or element.dataset instead. requestNotifier.js:64
    19:24:12.755 GET https://diasp.eu/assets/blueprint-7977ec448ebbf177077661bc8f8ac5b0.css [HTTP/1.1 304 Not Modified 90ms]
    19:24:12.756 GET https://diasp.eu/assets/login-6450c4771d601b64be857113eddd0fde.css [HTTP/1.1 304 Not Modified 230ms]
    19:24:12.756 GET https://diasp.eu/assets/application-6037758cb471678e2c48307d6b015b0b.css [HTTP/1.1 304 Not Modified 900ms]
    19:24:12.756 GET https://diasp.eu/assets/default-c8d85b9a7624bad2d099841fa16839cc.css [HTTP/1.1 304 Not Modified 430ms]
    19:24:12.756 GET https://diasp.eu/assets/rtl-a4f9df84ce07b56f5669e85f5889a3e3.css [HTTP/1.1 304 Not Modified 440ms]
    19:24:12.757 GET https://diasp.eu/assets/jquery-6cabf0a1b289276693e6e2e40c3971e1.js [HTTP/1.1 304 Not Modified 450ms]
    19:24:12.757 GET https://diasp.eu/assets/jquery_ujs-1aa15efbabf8747d72eab660f389339a.js [HTTP/1.1 304 Not Modified 250ms]
    19:24:12.757 GET https://diasp.eu/assets/main-a482caa60f14c4285ee9de8e80fdbfeb.js [HTTP/1.1 304 Not Modified 430ms]
    19:24:12.758 GET https://diasp.eu/assets/templates-35b2fc3ff6e7e556c774947ebf1ae9c0.js [HTTP/1.1 304 Not Modified 320ms]
    19:24:12.758 GET https://diasp.eu/assets/profile-915d66ad3dadc41192a4c9642987cc66.js [HTTP/1.1 304 Not Modified 420ms]
    19:24:12.884 Unknown property '-moz-box-shadow'.  Declaration dropped. login-6450c4771d601b64be857113eddd0fde.css:1
    19:24:12.884 Expected 'none' or URL but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. login-6450c4771d601b64be857113eddd0fde.css:1
    19:24:12.884 Unknown property '-moz-opacity'.  Declaration dropped. login-6450c4771d601b64be857113eddd0fde.css:1
    19:24:13.152 Unknown property 'zoom'.  Declaration dropped. default-c8d85b9a7624bad2d099841fa16839cc.css:1
    19:24:13.152 Unknown property '-moz-box-shadow'.  Declaration dropped. default-c8d85b9a7624bad2d099841fa16839cc.css:1
    19:24:13.152 Expected 'none' or URL but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. default-c8d85b9a7624bad2d099841fa16839cc.css:1
    19:24:13.152 Unknown property '-moz-opacity'.  Declaration dropped. default-c8d85b9a7624bad2d099841fa16839cc.css:1
    19:24:13.153 Unknown property '-moz-border-radius'.  Declaration dropped. default-c8d85b9a7624bad2d099841fa16839cc.css:1
    19:24:13.153 Unknown property 'box-sizing'.  Declaration dropped. default-c8d85b9a7624bad2d099841fa16839cc.css:1
    19:24:13.153 Unknown property '-moz-background-clip'.  Declaration dropped. default-c8d85b9a7624bad2d099841fa16839cc.css:1
    19:24:13.153 Error in parsing value for 'background-image'.  Declaration dropped. default-c8d85b9a7624bad2d099841fa16839cc.css:1
    19:24:13.153 Expected media feature name but found '-webkit-min-device-pixel-ratio'. default-c8d85b9a7624bad2d099841fa16839cc.css:1
    19:24:13.153 Expected end of value but found '\9 '.  Error in parsing value for 'border'.  Declaration dropped. default-c8d85b9a7624bad2d099841fa16839cc.css:1
    19:24:13.153 Error in parsing value for 'margin-left'.  Declaration dropped. default-c8d85b9a7624bad2d099841fa16839cc.css:1
    19:24:13.153 Error in parsing value for 'margin-top'.  Declaration dropped. default-c8d85b9a7624bad2d099841fa16839cc.css:1
    19:24:13.618 Error in parsing value for 'background-image'.  Declaration dropped. application-6037758cb471678e2c48307d6b015b0b.css:1
    19:24:13.618 Expected 'none' or URL but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. application-6037758cb471678e2c48307d6b015b0b.css:1
    19:24:13.618 Unknown property '-moz-box-shadow'.  Declaration dropped. application-6037758cb471678e2c48307d6b015b0b.css:1
    19:24:13.618 Error in parsing value for 'font-size'.  Declaration dropped. application-6037758cb471678e2c48307d6b015b0b.css:1
    19:24:13.618 Unknown property '-moz-border-radius'.  Declaration dropped. application-6037758cb471678e2c48307d6b015b0b.css:1
    19:24:13.618 Expected 'none' or URL but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. application-6037758cb471678e2c48307d6b015b0b.css:1
    19:24:13.618 Unknown property '-moz-opacity'.  Declaration dropped. application-6037758cb471678e2c48307d6b015b0b.css:1
    19:24:13.619 Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector. application-6037758cb471678e2c48307d6b015b0b.css:1
    19:24:13.619 Unknown pseudo-class or pseudo-element '-webkit-search-cancel-button'.  Ruleset ignored due to bad selector. application-6037758cb471678e2c48307d6b015b0b.css:1
    19:24:13.619 Expected declaration but found ':'.  Skipped to next declaration. application-6037758cb471678e2c48307d6b015b0b.css:1
    19:24:13.619 Unknown property '-moz-border-radius-bottomleft'.  Declaration dropped. application-6037758cb471678e2c48307d6b015b0b.css:1
    19:24:13.619 Unknown property '-moz-border-radius-bottomright'.  Declaration dropped. application-6037758cb471678e2c48307d6b015b0b.css:1
    19:24:13.619 Unknown pseudo-class or pseudo-element '-webkit-file-upload-button'.  Ruleset ignored due to bad selector. application-6037758cb471678e2c48307d6b015b0b.css:1
    19:24:13.620 Error in parsing value for 'min-width'.  Declaration dropped. application-6037758cb471678e2c48307d6b015b0b.css:1
    19:24:13.620 Unknown property 'zoom'.  Declaration dropped. application-6037758cb471678e2c48307d6b015b0b.css:1
    19:24:13.621 Error in parsing value for 'size'.  Declaration dropped. application-6037758cb471678e2c48307d6b015b0b.css:1
    19:24:13.621 Error in parsing value for 'display'.  Declaration dropped. application-6037758cb471678e2c48307d6b015b0b.css:1
    19:24:13.621 Error in parsing value for 'max-height'.  Declaration dropped. application-6037758cb471678e2c48307d6b015b0b.css:1
    19:24:13.621 Unknown property 'box-sizing'.  Declaration dropped. application-6037758cb471678e2c48307d6b015b0b.css:1
    19:24:13.622 Error in parsing value for 'cursor'.  Declaration dropped. application-6037758cb471678e2c48307d6b015b0b.css:1
    19:24:14.011 Unknown property 'box-sizing'.  Declaration dropped. edit
    19:24:14.784 GET https://diasp.eu/uploads/images/thumb_medium_6095d877dd8a7b6c5837.png [HTTP/1.1 304 Not Modified 80ms]
    19:24:14.785 GET https://diasp.eu/assets/mobile-spinner-d20711b7611ed57528d193ff5304d2b5.gif [HTTP/1.1 304 Not Modified 80ms]
    19:24:14.785 GET https://diasp.eu/assets/header-bg.png [HTTP/1.1 304 Not Modified 80ms]
    19:24:14.786 GET https://diasp.eu/assets/branding-s03fd5dc9f3-b70fd6cc25418e0d7c3a808025fb6d05.png [HTTP/1.1 304 Not Modified 80ms]
    19:24:14.786 GET https://diasp.eu/assets/ajax-loader.gif [HTTP/1.1 304 Not Modified 80ms]
    19:24:14.786 GET https://diasp.eu/uploads/images/thumb_small_6095d877dd8a7b6c5837.png [HTTP/1.1 304 Not Modified 80ms]
    19:24:14.787 GET https://diasp.eu/assets/icons-sc6cbb824ee-c3a0b7fbfd861a223e0a9344ab5c1e35.png [HTTP/1.1 304 Not Modified 150ms]
    19:24:15.658 Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery-6cabf0a1b289276693e6e2e40c3971e1.js:15

edited to reflect this issue being present in Arabic as well

**Comment by svbergerem** [comment]
I was able to change the profile picture with Hebrew selected as the user's language on the develop branch. (using Firefox 37)

The profile edit page has been ported to Bootstrap before the last release so this should also work on pods running the master branch. (0.4.1.2)

I'll close this issue. @itais feel free to reopen if you are still able to reproduce this bug.
