### ISSUE TITLE
RTL languages: Names are reversed

### ISSUE THREAD

**Issue by itais** [diaspora/diaspora#4785]
With RTL language (Hebrew, Arabic) selected as interface language in d* all the names which link to profiles in the home or user streams are reversed.
![names](https://f.cloud.github.com/assets/6691493/2178476/4df39a1c-9669-11e3-888a-983705f6e56e.png)

edited to reflect this issue being present in Arabic as well

**Comment by GreenLunar** [comment]
Perhaps adding a PDF character before name, preferably with space afterwards, not near name itself, would fix this.

PDF SPACE NAME

U+202C POP DIRECTIONAL FORMATTING

**Comment by jhass** [comment]
I believe this is a styling (CSS) issue.

**Comment by GreenLunar** [comment]
What sort of CSS code would cause this?  If I would know, I would seek a solution.

**Comment by jhass** [comment]
Something in https://github.com/diaspora/diaspora/blob/develop/app/assets/stylesheets/rtl.scss I'd assume.

**Comment by GreenLunar** [comment]
Is this the code responsible?

```
.aspect_list .name {
  right: 1em;
  left: auto;
}
```

Why do not you use this http://www.w3schools.com/cssref/pr_text_direction.asp ?
```
 div {
    direction: rtl;
} 
```

**Comment by jhass** [comment]
I doubt it is. And we are, `div` inherits that property from `body`.

**Comment by GreenLunar** [comment]
I still don't target the problematic code.  As long as this issue persists, new users of RTL languages might think that diaspora* is unworthy.

**Comment by denschub** [comment]
`unicode-bidi: bidi-override;` in [app/assets/stylesheets/stream_element.scss:60](https://github.com/diaspora/diaspora/blob/7fca5cf93a3822b5c5afeb2039563aeeac1d52a1/app/assets/stylesheets/stream_element.scss#L60) causes this issue.
