### ISSUE TITLE
Posts on the tag page can be reshared even if there were already reshared

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#4816]
The link "reshare" is still there but a pop up appears when we click on it saying that we already reshared that.
##

**Comment by svbergerem** [comment]
Now it also happens in the main stream. We display the reshare link if we are unable to find a reshare by the user in [`app/assets/javascripts/app/models/post/interactions.js`](https://github.com/diaspora/diaspora/blob/aefd727/app/assets/javascripts/app/models/post/interactions.js#L52). This works after we fetched the interactions but before the reshares have a different structure so we can't find the user's reshare with the linked function.

**Comment by goobertron** [comment]
Linked to #6594.
