### ISSUE TITLE
Add a contact to an aspect complexity depends of the total number of the contacts

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#4824]
Adding someone to a big aspect is taking a **lot** of time (most of the time it fails with diaspora HQ). To add a user to an aspect should not be proportional to the number of the users in this aspect, so there is something to check there.

**Comment by svbergerem** [comment]
This issue still lacks some additional info and is - as @goobertron wrote - likely a symptom of #3164. We moved the dhq account to a new pod. If there are similar problems on the new pod we can reopen this issue and debug on the new pod.
