### ISSUE TITLE
Unsubscribe button in detail view

### ISSUE THREAD

**Issue by axaluss** [diaspora/diaspora#4825]
Whenever i want to unsubscribe from a post such that i will not receive anymore notifications about it i have to scroll through all my stream and find that post again such that i can unsubscribe.

I request an "unsubscribe" button in detail view of a post.

**Comment by jaywink** [comment]
This will be solved by #5547

**Comment by jaywink** [comment]
Well, #5547 now merged which introduces post hiding from SPV. But I guess to close this unsubscribe would be needed, which is done on the stream in hopefully soon to be merged #5511 - but that doesn't cover SPV. So leaving this open.

**Comment by svbergerem** [comment]
This has been fixed by #5722.
