### ISSUE TITLE
Polish notifications view

### ISSUE THREAD

**Issue by svbergerem** [diaspora/diaspora#4866]
- [x] Don't display a grey zero if there are no unread notifications.
- [x] Add a separator between notifications of two different days.
- [x] Assimilate timeago tooltips (also applies to the dropdown)
- [x] Add a message if no notifications are available

**Comment by svbergerem** [comment]
Alright, #5417 fixed the two remaining issues. I'll close this issue now.

@goobertron you wanted to open a new issue about the post titles. I don't know if you did that so now you should get a notification as a reminder. ;)

**Comment by goobertron** [comment]
Thanks for your care, Steffen. I did open a new issue, #5066, but forgot to link it to this one. It's great that you notified me, just in case.
