### ISSUE TITLE
Add documentation for shortcuts

### ISSUE THREAD

**Issue by Akhilan** [diaspora/diaspora#4871]
Any shortcuts avail for Diaspora? If not create some based on [Access keys](https://developer.mozilla.org/en-US/docs/XUL/Attribute/accesskey) like [Facebook](http://www.facebook.com/help/156151771119453), [Twitter](http://mashable.com/2013/02/20/twitter-shortcuts/) & [Gmail](https://support.google.com/mail/answer/6594?hl=en)

**Comment by denschub** [comment]
Actually, we do have documentation nowdays (right at `/help/keyboard_shortcuts`)
