### ISSUE TITLE
Markdown conversion for Facebook

### ISSUE THREAD

**Issue by eferdi** [diaspora/diaspora#4877]
If creating a post in diaspora like this one:
 \["Some text"](http://example.com)

Then in Facebook only the content in the [ ] gets posted:
 "Some text"

So the complete URL information gehts lost. It would be nice when it is posted as followed to Facebook:
"Some Text" (http://example.com)

Thats only one example, but i think there are more wehre this makes sense.

//eferdi

**Comment by svbergerem** [comment]
The upstream issue https://github.com/vmg/redcarpet/issues/404 has been fixed in redcarpet 3.2.0 and we are using redcarpet 3.2.2. I have no account to test this but I guess this has been fixed.

**Comment by jhass** [comment]
Right, this should be fixed.
