### ISSUE TITLE
Avatars with alpha color looks wierd

### ISSUE THREAD

**Issue by ariktaurendil** [diaspora/diaspora#4881]
If you avatar has an alpha color region looks wierd due to the avatar backgound is light grey but the backgound of the rest of the page is white.

If we change the background color of the avatar to white it looks really better. I think I can make that little change if you think it is ok.

With light grey background
![alpha-color-avatar](https://cloud.githubusercontent.com/assets/1479841/2556973/1b5027fa-b6ea-11e3-8e01-efac1b95d63c.png)

With white background

![fix-alpha-color-avatar](https://cloud.githubusercontent.com/assets/1479841/2557023/b98b3b42-b6ec-11e3-89b5-619deff996e4.png)

**Comment by svbergerem** [comment]
We no longer have a grey background. I tried this in the desktop and mobile version.
