### ISSUE TITLE
Post preview for comments

### ISSUE THREAD

**Issue by jaywink** [diaspora/diaspora#4973]
Post preview for new posts is awesome, but due to same formatting possibilities in comments too, it would be nice to copy the feature there too (stream(s) and SPV sides).

Just tried 5 times to get formatting right for one comment :D - each time deleting the old comment and trying again..
##

**Comment by manwesulimo2004** [comment]
So, has this been implemented?

**Comment by Flaburgan** [comment]
Not at the moment, you can work on it if you want to.

**Comment by BBK-SDP-2015-dhassa02** [comment]
@manwesulimo2004 Hey! We got an implementation working for this feature, but was not in line with core teams vision of how the feature would be best approached - so got shelved... would be happy to link the branch we were working on, if this would be of interest to you :)

**Comment by goobertron** [comment]
@BBK-SDP-2015-dhassa02 would you be willing to complete your PR according to the current UX, as you said in a comment above? It would be great to get this implemented, and if you liked you could be part of creating an improved UX for all inputs in diaspora once everything has been ported to bootstrap.

**Comment by Flaburgan** [comment]
This will be fixed by https://github.com/diaspora/diaspora/pull/7214

**Comment by HankG** [comment]
I believe this feature is implemented.  Is there something missing from the current implementation that has this still open?

**Comment by SuperTux88** [comment]
Yes, that's fixed by #7482 in 0.7.0.0, we just forgot to close this.
