### ISSUE TITLE
More elegant icons for the mobile view

### ISSUE THREAD

**Issue by paugre** [diaspora/diaspora#4981]
It's great to see the mobile view revamped, but the new all-white icons don't look specially good. Currently it looks very much like a testing example (no offense, I know there where reasons to make them white, it just doesn't work very well now). So id suggest to change them prior to 0.4.0 release. I have no idea where these icons need to be placed in diaspora* but I can hopefully supply a first set of revamped example icons tomorrow. (sorry I couldn't help out earlier but I have been writing my exams.)

**Comment by svbergerem** [comment]
We use Entypo icons almost everywhere in the mobile view. Is there anything left to do?

**Comment by AugierLe42e** [comment]
AFAIK, #6509 gets rid of the last images-based icons on mobile.

**Comment by svbergerem** [comment]
Alright, #6509 has been merged, so I'll close this issue. If anyone has some specific changes in mind they can open a new issue.
