### ISSUE TITLE
Hover effect of contacts of private messages too fast

### ISSUE THREAD

**Issue by TheRadialActive** [diaspora/diaspora#5016]
If you are in a conversation (private messages) with more than one person and you move your cursor over the title of the conversation, you get a nice hover effect to look at the contacts of the conversation.

That's a cool effect, but maybe it should have a little delay, like the hovercards or it should not get activated if you hover the conversation title. Maybe the big avatar (where you see the numbers of participants ('+1')) should be the object to hover over, so then the animation gets activated.

![hover](https://cloud.githubusercontent.com/assets/828436/3352415/9a2e3e6a-fa45-11e3-9974-5b1796c80ac5.png)

**Comment by svbergerem** [comment]
@TheRadialActive @SuperTux88 #5776 improved the hover effect. The speed is still the same but it feels less buggy. It would be great if you could check if that fixes your issue.

**Comment by SuperTux88** [comment]
It's much better now! :+1:

**Comment by svbergerem** [comment]
@TheRadialActive It would be great if you could test this once geraspora has been updated and decide if you consider this issue as fixed.

**Comment by TheRadialActive** [comment]
It seems to be more fluent and the animation timing is perfect. Thanks for your awesome work! :)

**Comment by svbergerem** [comment]
I guess you would have to thank @lislis for these changes. :)

**Comment by lislis** [comment]
You're welcome :) Feel free to ping me for those kinds of things. I love css animation things!
