### ISSUE TITLE
Post excerpt in notifications has markdown syntax

### ISSUE THREAD

**Issue by TheRadialActive** [diaspora/diaspora#5018]
I often write "titles" in my posts, that are linked through markdown. I now got a notification with the cool new excerpt of the related post.

But you can see the markdown syntax:

![rendering](https://cloud.githubusercontent.com/assets/828436/3357201/304f11e4-facd-11e3-95fb-ff0164938c3e.png)

**Comment by Flaburgan** [comment]
Btw, it is not only in the notification dropdown, but everywhere we call the title of a post: In the subject of the notification email, in the `<title>` of the SPV, in the atom feed...
