### ISSUE TITLE
New poll feature text poorly aligned to buttons

### ISSUE THREAD

**Issue by Voter33** [diaspora/diaspora#5028]
![image](https://cloud.githubusercontent.com/assets/7981495/3381089/0697a502-fc15-11e3-9292-75ba2fca5a83.png)

**Comment by svbergerem** [comment]
Is anyone still able to reproduce this?

**Comment by polsVoice** [comment]
It appears to be fixed. I wasn't able to reproduce it, and diasp.org has a three-column layout now.
