### ISSUE TITLE
Post fetcher should include polls, photos or locations

### ISSUE THREAD

**Issue by jhass** [diaspora/diaspora#5032]
##

**Comment by svbergerem** [comment]
Fixed by #6873

**Comment by svbergerem** [comment]
Looks like I was wrong, sorry.

You'll find the fetcher code in [lib/diaspora/fetcher/public.rb](https://github.com/diaspora/diaspora/blob/27b4a44/lib/diaspora/fetcher/public.rb) and we call it in [app/workers/fetch_webfinger.rb](https://github.com/diaspora/diaspora/blob/develop/app/workers/fetch_webfinger.rb#L13).

**Comment by SuperTux88** [comment]
Yes, this is fixed now, I just didn't know this issue existed :+1:
