### ISSUE TITLE
Total user statistic shouldn't include closed accounts

### ISSUE THREAD

**Issue by jhass** [diaspora/diaspora#5041]
Currently it does. One way to determine and exclude closed accounts would be linking them to the AccountDeletions.

**Comment by Flaburgan** [comment]
Looks like https://github.com/diaspora/diaspora/commit/dc444852307cea66884c8b5aad220e4ec37c9207#diff-520128ea12a2d1b32ee237a81379305aR52 fixed that, so this issue and https://github.com/diaspora/diaspora/pull/5351 can be closed.
