### ISSUE TITLE
"max_time" GET parameter (stream) doesn't work on desktop version

### ISSUE THREAD

**Issue by eduardrock** [diaspora/diaspora#5051]
For example if I open the following link on the mobile version
https://joindiaspora.com/stream?max_time=1404244942

It will load the posts up to the specified timestamp.

BUT, in the desktop version, it doesn't work. Always will load until the last post.

**Comment by denschub** [comment]
Since this issue is dead for a while now (and we are working towards an API), I'm closing this. Feel free to reopen if you feel really strong about this.
