### ISSUE TITLE
Can not pick one of several contacts with the same name when sending a message

### ISSUE THREAD

**Issue by akerbos** [diaspora/diaspora#5091]
As it so happens, you can have multiple contacs with the same screen name: maybe a friend has old or multiple accounts, or two people just share a name.

However, when composing a message only the screen name is shown; neither avatar nor account name nor anything else are accessible. It is thus _impossible_ to pick the correct contact.

Please add (a small version of) the avatar and the account name to this and similar quicksearch result lists.
##

**Comment by svbergerem** [comment]
Fixed by #7129.
