### ISSUE TITLE
Remember me checkbox ?

### ISSUE THREAD

**Issue by Phyks** [diaspora/diaspora#5095]
Hi,

What about adding a remember me checkbox on login screen, to autoconnect the user ?

**Comment by svbergerem** [comment]
We already have a "remember me" checkbox on the sign in page which is hidden and set to true. Of course that only works as long as you don't delete your cookies or you log out.

I think we can close this issue. Any other opinions?

**Comment by goobertron** [comment]
Is there any benefit to allowing users to choose whether or not to be remembered when signing in? If not, I agree we can close this.

**Comment by svbergerem** [comment]
I don't see any benefit.
