### ISSUE TITLE
Can't see private conversation with 2 different account

### ISSUE THREAD

**Issue by SansPseudoFix** [diaspora/diaspora#5103]
Hi !
Well, I'll try to be clear (not easy).

Fla started a private conversation with 4 persons. With my account (SpF@diaspora-fr.org), I see his message. When I look at my podmin@framashpere account, I don't see his message, I just see 4 same conversation, but all are empty. SpF and podmin share with Fla.
"OK" on the screenshots are here to say "share each other". 
Here with SpF account : 

![mp1_masque](https://cloud.githubusercontent.com/assets/6507951/3795728/b949557e-1bbe-11e4-96a3-b3e845e0ae3e.png)

Here with podmin account : 

![mp2_masque](https://cloud.githubusercontent.com/assets/6507951/3795738/cba27908-1bbe-11e4-98c4-b950db3f4277.png)

I figured that if Fla share with all participants, we can all see messages, but...

Hope that's clear :)
##

**Comment by Flaburgan** [comment]
I'm gonna try to reproduce this during the hackathon. That means, now. :D

**Comment by jaywink** [comment]
Well, we managed to reproduce this and get some log info on the failure, in diaspora-fr.org side. Whether it leaves iliketoast.net ok is of course another question, but AFAICT it does and Fla showed a case where message was from Framasphere and had same symptoms.

Will have a quick look what `Parent is invalid` in this case could refer to, but of course any knowledge welcome.

    15-10-09T14:51:56] INFO  PID-11675 TID-169435722420 Sidekiq: Workers::ReceiveEncryptedSalmon JID-4f55cf42cab7e8f55e97971d: start
    [2015-10-09T14:51:56] INFO  PID-11675 TID-169435949560 Sidekiq: Workers::ReceiveEncryptedSalmon JID-6b8b3a25075a9b37e6e6e791: start
    [2015-10-09T14:51:57] INFO  PID-11675 TID-169435722420 Postzord::Receiver::Private: user:951 starting private receive from person:6e28e2bc57a73fae
    [2015-10-09T14:51:57] INFO  PID-11675 TID-169435722420 Participation: event=verify_signature status=complete guid=2818c4e050a50133fe0b00259069449e validity=true
    [2015-10-09T14:51:57] INFO  PID-11675 TID-169435949560 Postzord::Receiver::Private: user:982 starting private receive from person:7ed1555bc6ae03db
    [2015-10-09T14:51:57] INFO  PID-11675 TID-169435722420 Postzord::Receiver::Private: user:951 successfully received Participation from person b581d1803aaa0133fc85002
    59069449e: 2818c4e050a50133fe0b00259069449e
    [2015-10-09T14:51:57] INFO  PID-11675 TID-169435722420 Sidekiq: Workers::ReceiveEncryptedSalmon JID-4f55cf42cab7e8f55e97971d: done: 0.109 sec
    [2015-10-09T14:51:57] INFO  PID-11675 TID-169435949560 Message: event=verify_signature status=complete guid=c89d403050b10133bafa6c626dd55703 validity=true
    [2015-10-09T14:51:57] ERROR PID-11675 TID-169435949560 Postzord::Receiver::Private: failed to receive Conversation from sender:7 for user:982: Validation failed: Pa
    rent is invalid
    #<Conversation id: nil, subject: "test conversations 3", guid: "c89d439050b10133bafa6c626dd55703", author_id: 7, created_at: "2015-10-09 12:47:11", updated_at: nil>
    [2015-10-09T14:51:57] WARN  PID-11675 TID-169435949560 Workers::ReceiveEncryptedSalmon: failed to save received object: ["Parent is invalid"]
    [2015-10-09T14:51:57] INFO  PID-11675 TID-169435949560 Sidekiq: Workers::ReceiveEncryptedSalmon JID-6b8b3a25075a9b37e6e6e791: fail: 0.146 sec
    [2015-10-09T14:51:57] WARN  PID-11675 TID-169435949560 Sidekiq: <Hash> {"class"=>"Workers::ReceiveEncryptedSalmon", "args"=>[982, "    <?xml version='1.0' encoding=
    'UTF-8'?>\n    <diaspora xmlns=\"https://joindiaspora.com/protocol\" xmlns:me=\"http://salmon-protocol.org/ns/magic-env\">\n              <encrypted_header>\n      
        eyJhZXNfa2V5Ijoiek9RTVVHcHRWMDE5eWEwcFVtazVONWNRTVJyaHBNWUZNRUIzSmtlUm4xbFR3bDA0OFBIdGFnN3d1eUhIT05yQ1hFT0s4VWZoMFlybi91UUFzNDcyK2ZYWjVHa2FNdUFIM3QzV0pPZXVGU2Jt
    a3ViY0c4UzFsWk5Pb3BYSXVyQTNtNmxjWFBycVhCYTRjam9kbWptbGYvV2Jsb25YQXloa2o1NUhLeURxNkpkT3hyVlRwNmtMUXREYjA2YkZrWXRGZUpUSHUybjQwYmVGQXB4YzlWYjY5NCtTdFp1Tmx6RnFJSWZzdnAz
    eUZTUzFiYUtrYzhKSFJsZ2dNdUp3S0hBRHVqMlZ3anZTYU5TSnNObEpOL1A2dGJoaUxFUlVDd2JQaW5XdFRHcjBDRmlGYzJIK2pJcWp1Tk9yNVlNOWFvejVCdi81WlBTMjN0b2lTZ2NVd3dhYlJOYjdqOXhEeGNWOXBj
    MVpJLy9iR2ZabWZHeVdVQzNqTTJmN3RxS3lZMWdLZGU1ajFuSUVnNjZrLytkNjRkL2ZCK2laMUhMTHZ3Y2t4QTA4aXd4SjVpdkllaE4wcS94NlNaczVBa0FFYUFCTjdJek5jS0xqbG1pd0VFVWhvRXhRTkRBQUhCek5I
    NVNZU3RET081RVRBVXcxM2RkYUlobVVaSVpzWU5jZTRhZjVFZHJINzNwN3BSdVJ0Q3UrRVFNMVZmTk0rZ3lGQXJIMEJGV0xCMWdGbXMyUWlLcy9iajBSWEN5TFR6dmFTMzh6aEpUcm9CMktneldQSkFJbzVSek8zazJC
    cUE5TytsSmNhVGpxVFhLc2F4RVRlWnp3bHhtR3BEbit4d0xoVDRyTGk5Mmhkb2pLRkpaRUx4c2JvQkNvUTBQQTF5SzNKcDlwVnErSXlwRGRHM3c9IiwiY2lwaGVydGV4dCI6Ik1HVjEya0NXT0FFN1ZJM1VCQ0dRU3Y1
    VmhUNU1FVTk3YzNiRnM0MTltMHVtYWVjeGY0MEJFblFsSE01OFIwRDllTS9zdkxMN0VpUHFWMUgzNCszYXFOYnlHSnpySFJjZ01zSHlnODR5dStKVHA5cjRDWWpWRWJXZHVUQUxvOG8zTUtWWlpzR0FyaXd4T0RuSi9s
    TVN6bTUweG5TczhUQ1lnVklzMFhHRzN5MUVhdE1CRlZQUGZ5Ymd2Ti9lb2llL2tiSWpOT0hyeUs2NlVxdjJiVDgzemhLNElxd2swZ3hOd2RpakZaY25KNDYwbmlISjBMRVM3ZlZRbDVvYTNBZWl2Vkd3NmFEaEIvaGJx
    Rjg3YkpOUElBPT0ifQ==\n        </encrypted_header>\n\n      <me:env>\n  <me:data type='application/xml'>QUdncUdjd05zZlgvUk9QR0M3aWx1aTFHWFZ3czZwMXNjcjh2dnd4dkdqU0FxK
    zZHNWtMREJyTjMwR3FYQWhPNTVuaXhRekpCT1o0bmg0c245d2ZSRUFzcXJ2VWJHQUFTaVJ3MUZoWXhiUkdlWk9RQVoyY0h5U0RGK2pxY3hFczUwZmdmbnBhQ1JJUjVVMzdYRFBJamFQUXRrVFQxQlAwazdzL1hiOE4zd
    [...snip...]
    kY3lPTEY0SHlpMVFhSlZOWmJKYjdzNldqVXdtNFNHazQ3UGx0a0JkOFl3emplTC9TcDhvNVdtSExGMTBLdWZ1M1lXL25HS2dnSWJPWU5iekQyb1VnbjVGZW5ZVW55RllMK25XemdQd01zT00xTWp3MWl5UDhXLzVuYmZJUFlkZS9WbUg3RHZZUmF3akg2UDF2MWxqWlJJdEpoN2YvS2ZlWXlwR1NJRmFtMkxGTjk5YkdwbGZCOElSaE85R0dzWG04bHJlWHd1clB5dEUyMTVxSUp0a3BiS084bEhLWkZrNXoxTGVKcDZsSTlvajlLZ3ZkVFRsRUxGUTRSbFg5SXZzdGFLV0ZYR3ArYTJKWENOVUdWclpXTlc2ZnoxZFM4PQ==</me:data>\n  <me:encoding>base64url</me:encoding>\n  <me:alg>RSA-SHA256</me:alg>\n  <me:sig>GeJh74D_xeKsz22lBB_9zL9RzDzmWajhsYk1pA199YxjFw8sOrYYUxjBmhn1FrUm18_NX54T0KzsHOyCcvvj5---CYWwvqNe4UwxXZnZoi3twJMZ1_np51xDmh_xjjplcstqvyVytPfJMqIriVFnMBCoJiCe-ka-K1XuXISqVR0MVGEnbwt72Ac2_6L5Gb96Jx4U2W1M-ardn9EQfGpyP6-_ZZ1ge5OdZYCP-HCxb92OaSDQBI9d6PkZ8AWLVEpslrKZyG2NKvyADtkaWqxmbIIvQJ8wZTObXallEiRK3Ea2uYNST4zr--S3wbNk47_Z-QD0xhGLbm5rL34DGaMWvb7-AIiELucBlztmMsMkrrAM3eiwqDe46woWERN7N4h21QLFvUKbu_Jc3HeMlMwOrjmwlnqqiRaMqlxEGyjkwmr6ePNxqGwJTQXQDgUWqMns2PAzu1WV-j_Qf3VOmZXJUJR0c0z-p5O7d-wYdjKjmQEu19IIKszLPPRO4NULwlnoswtlKIQonUcBQaLBQ5Y_1qqD5UipgEkCsSpJ6hVNqx5yNs48FdbOhGUlgOFB9219OVdNquQGCYNnDSqeVd_VPnI21J5RJALbc3zNDXAIJh7siuAPnjsLP_sLGtcniZ7K1hIKzo2vZsIg9YDIWw5mGkB6ZtVyz4OjhZpP7pCczfA=</me:sig>\n  </me:env>\n\n    </diaspora>\n"], "retry"=>12, "queue"=>"receive_salmon", "backtrace"=>20, "jid"=>"6b8b3a25075a9b37e6e6e791", "created_at"=>1444394952.847577, "locale"=>"en", "enqueued_at"=>1444395116.9649088, "error_message"=>"Validation failed: Parent is invalid", "error_class"=>"ActiveRecord::RecordInvalid", "failed_at"=>1444394953.0873113, "retry_count"=>3, "error_backtrace"=>["lib/diaspora/relayable.rb:88:in `receive'", "app/models/conversation.rb:102:in `block in receive'", "app/models/conversation.rb:100:in `receive'", "lib/postzord/receiver/private.rb:42:in `receive_object'", "lib/postzord/receiver/private.rb:37:in `parse_and_receive'", "lib/postzord/receiver/private.rb:19:in `receive!'", "lib/postzord/receiver.rb:14:in `perform!'", "app/workers/receive_encrypted_salmon.rb:14:in `block in perform'", "app/workers/base.rb:15:in `suppress_annoying_errors'", "app/workers/receive_encrypted_salmon.rb:11:in `perform'"], "retried_at"=>1444395117.1155715}
    [2015-10-09T14:51:57] WARN  PID-11675 TID-169435949560 Sidekiq: ActiveRecord::RecordInvalid: Validation failed: Parent is invalid
    [2015-10-09T14:51:57] WARN  PID-11675 TID-169435949560 Sidekiq: lib/diaspora/relayable.rb:88:in `receive'
    app/models/conversation.rb:102:in `block in receive'
    app/models/conversation.rb:100:in `receive'
    lib/postzord/receiver/private.rb:42:in `receive_object'
    lib/postzord/receiver/private.rb:37:in `parse_and_receive'
    lib/postzord/receiver/private.rb:19:in `receive!'
    lib/postzord/receiver.rb:14:in `perform!'
    app/workers/receive_encrypted_salmon.rb:14:in `block in perform'
    app/workers/base.rb:15:in `suppress_annoying_errors'
    app/workers/receive_encrypted_salmon.rb:11:in `perform'

**Comment by jhass** [comment]
I'd guess there's a `Message` included and that fails to save for some reason, most likely the `Conversation` having another validation error that's not displayed.

**Comment by svbergerem** [comment]
Is anyone still able to reproduce this with the new federation code?

**Comment by Flaburgan** [comment]
Hm, @jaywink do you remember the steps to reproduce?

**Comment by jaywink** [comment]
The reproduce part was simply sending a conversation. Nothing special was done.

If no one has reported this for a while I guess you could close it. I don't personally use the conversation feature that much.

**Comment by SuperTux88** [comment]
Well, closing then (probably fixed with the new federation).
