### ISSUE TITLE
Extract federation code into a gem and integrate it in diaspora

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#5114]
@Raven24 did an awesome work rewritting all the federation code of diaspora* in a gem available on his repo: 
\- https://github.com/Raven24/diaspora-federation 
This gem was tested by @carolinagc and @juliaguar and worked pretty nicely.
\- https://github.com/Team-D/federation-testbed

The next step is to integrate it inside the diaspora* code and then remove all the code which does not use this gem. Once done, it will be way more easier to debug, test and improve the federation, and we will be sure that the gem doesn't have bugs, so we can promote it to the world.

* [x] dig out the testbed project, verify it still runs (optional)
* [x] document how to run it + extend to more test cases, eventually covering all federation events (optional)
* [x] use the gem for generating user discovery documents (hostmeta, webfinger, hcard) - this should be relatively easy
* [x] use the gem for parsing user discovery documents - this could mean some bigger changes to the core code. we may need some additional test coverage in this area.
* [x] use the gem for generating federation messags (salmon envelopes w/o encryption, payloads) - this will touch some of the oldest code in this project. creating a pull request as early as possible is strongly recommended. this part requires regression testing with an unmodified d* server.
* [x] use the gem for parsing federation messsages - same as above
* [x] publish the gem as 0.0.1(?) and move the repo to the d* organization on GitHub

**Comment by dimaursu** [comment]
Some of the specs do not belong in the main repository (and so do the same libraries): 
https://github.com/diaspora/diaspora/blob/develop/spec/lib/hcard_spec.rb, for example.
I started some work, but unfortunately there aren't that many tests for the federation itself - it's hard to tell if I broke it or it's still working. I'll work on the tests the following days.

**Comment by jaywink** [comment]
@Raven24 and others: @SuperTux88 is working [on a diaspora_federation gem also](https://github.com/diaspora/diaspora/pull/6151). Unless the plan has "changed" and raven24's gem isn't going to be used and supertux's gem will be used (between you guys), I'm worried there could be lots of effort lost from someone, so just calling out here for possibility for some work-together in this area?

Also, there is a $185 bounty to the person who integrates raven24's gem. I'm going to throw in the assumption that we can rename the issue to "implement diaspora federation through a gem" etc.

**Comment by Raven24** [comment]
we're on it: SuperTux88/diaspora_federation#1
;)

**Comment by Flaburgan** [comment]
First step, https://github.com/diaspora/diaspora/pull/6151 is merged! I didn't follow closely what have been done so I let someone else edit the task list.

**Comment by SuperTux88** [comment]
this is done: "use the gem for generating user discovery documents (hostmeta, webfinger, hcard) - this should be relatively easy" but I have no permissions to edit it.

**Comment by jaywink** [comment]
Mind if I rewrite the issue or can you @Flaburgan do it? To a more generic "move stuff to federation gem" :) I'm also not sure the testbed needs to be a "requirement".

**Comment by SuperTux88** [comment]
"use the gem for parsing user discovery documents" is done with #6310.

**Comment by cmrd-senya** [comment]
I have updated the testbed so that it passes tests now: https://github.com/cmrd-senya/federation-testbed

**Comment by cmrd-senya** [comment]
I'll look into extending tests for it.

**Comment by cmrd-senya** [comment]
Am I right that the @Raven24's gem is not used anymore, and now all the job is concentrated around the @SuperTux88's gem?

Actually, the testbed is a cucumber test suit for the federation gem, so maybe just merge it within the gem's repository?

**Comment by cmrd-senya** [comment]
I think the "dig out the testbed project, verify it still runs" can be marked as done.

**Comment by SuperTux88** [comment]
sorry, had no time to respond yesterday and also had not much time in the last weeks to work on the gem ;) maybe this weekend ...

yes, I'm writing a new gem (based on the one from @Raven24), but I have only finished the whole discovery stuff (webfinger/hcard), and I'm now working on the salmon part (but not finished yet, as you may have noticed already).

you can create a pull-request to merge the testbed, but maybe it is better to wait a little until the salmon stuff is finished.

**Comment by Flaburgan** [comment]
Can... Can this be closed? ... 

![](http://memesvault.com/wp-content/uploads/Okay-Crying-Meme-05.png)

**Comment by denschub** [comment]
Yes, you are very right! Thanks.

**Comment by AugierLe42e** [comment]
# YOLOOOOOOOOOOOOOO
