### ISSUE TITLE
Sprite asset paths wrongly generated

### ISSUE THREAD

**Issue by jhass** [diaspora/diaspora#5144]
If the sprites weren't previously generated, the path to them generated by compass-rails or sass-rails is wrong, as a workaround the compiled files are committed for now (see 2c6e9a9786b3941dc465b77463a1a7c7d62184c5), but that shouldn't be the permanent solution.

Revisit when there are new upstream versions.

**Comment by svbergerem** [comment]
@jhass Did you fix that with the rails4.2 update?

**Comment by jhass** [comment]
Oh, right. Forgot I opened an issue about it, thanks for the reminder.
