### ISSUE TITLE
Internet Explorer 9 and poll

### ISSUE THREAD

**Issue by SansPseudoFix** [diaspora/diaspora#5213]
Well, I don't think that is a priority, but a user tells me that a poll is automatically added when she posts something with Internet Explorer 9.
I tried to reproduce it (virtualbox and windows 7) and it bug when I post a link (website or mention). I tried on diaspora-fr.org and she is on framasphere.org.

![diaspora_bug_ie9](https://cloud.githubusercontent.com/assets/6507951/4237259/6122964e-39cd-11e4-9383-b4d18ce7fe94.png)

Tried with Internet Explorer 10 too, and no bug.

**Comment by cmrd-senya** [comment]
Do we still support IE9? Otherwise could be closed.

**Comment by denschub** [comment]
Closing. We do not support IE9 here.
