### ISSUE TITLE
Account creation screen font broken in Cyrillic

### ISSUE THREAD

**Issue by yurkobb** [diaspora/diaspora#5220]
There seems to be an embarrassing problem with certain languages that use the "щ" letter at the login screen as the used font doesn't display the letter correctly. Here's how it should look:
# Щ

But it looks almost like this:
# Ш

![diaspora-bug](https://cloud.githubusercontent.com/assets/479389/4265463/40e159a6-3c52-11e4-9346-902768e1ce3f.png)

The screenshot is in Firefox, but Webkit (Konqueror) looks the same.

(I've cheched the page source to make sure there's no mistake in the text itself).

Perhaps the font needs to be updated, because the letter is displayed correctly on FontSquirrel with this font: http://www.fontsquirrel.com/fonts/roboto

**Comment by svbergerem** [comment]
#5743 will fix this.

**Comment by svbergerem** [comment]
Should have been fixed with the new registration page. Could someone confirm this?

**Comment by cmrd-senya** [comment]
![livetester](https://cloud.githubusercontent.com/assets/10187586/8351747/3e5bbfee-1b38-11e5-9e60-fec2d0a97ee9.png)

Wrong text is not here anymore
