### ISSUE TITLE
Post/Comment controls don't reliably vanish when leaving the element

### ISSUE THREAD

**Issue by jhass** [diaspora/diaspora#5243]
On Bootstrap pages only. FF 32 here.

**Comment by svbergerem** [comment]
I'm not able to reproduce this with FF33 anymore.

**Comment by jhass** [comment]
I'm only on 65020004294a5982f36bb080c942e97da16abf18 but it still happens for me on FF35. The current behavior is that they don't vanish until scrolled off the screen.

**Comment by svbergerem** [comment]
I'm on https://github.com/diaspora/diaspora/commit/278ca84ec20fa446fe4134eae171c87eb4719772 and tested this with FF33 and FF35. I have no idea why that should have been fixed in between so I'll keep this open.

**Comment by jhass** [comment]
Just updated, still there for me.

**Comment by jhass** [comment]
Interestingly they also vanish after switching the tab, not after just tabbing away from Firefox.

**Comment by jhass** [comment]
Fixed by #5682
