### ISSUE TITLE
Sending anchors in URLs results in 404 previews

### ISSUE THREAD

**Issue by koehn** [diaspora/diaspora#5245]
When you paste a URL with an anchor reference into a post (`http://www.cnet.com/news/pi-top-the-3d-printable-raspberry-pi-laptop-anyone-can-build/#ftag=CAD590a51e`), diaspora incorrectly sends the anchor when fetching the URL to generate the preview (e.g., `GET /news/pi-top-the-3d-printable-raspberry-pi-laptop-anyone-can-build/#ftag=CAD590a51e HTTP/1.1` instead of `GET /news/pi-top-the-3d-printable-raspberry-pi-laptop-anyone-can-build/ HTTP/1.1`).

This results in a 404 preview instead of the correct preview. A simple regex should fix the issue.

**Comment by svbergerem** [comment]
Tested that on my dev pod with the URL given above and now it produces a correct preview. I guess we fixed that when switching to OpenGraphReader. @jhass can you confirm that? In that case we could close this issue and add the correct milestone.

**Comment by jhass** [comment]
Right, totally forgot this one.
