### ISSUE TITLE
Mobile interface random values at "Comments" "Reshares" or "Likes"

### ISSUE THREAD

**Issue by RDash21** [diaspora/diaspora#5250]
There is a bug in Diaspora* at the Mobile interface that shows duplicates or random values at interactions when refreshing it corrects the error. Screenshots should tell it all, they might get removed once this bug is fixed.

Before refresh:
![Mobile Bug in Diaspora*](http://i.imgur.com/kSwI9eS.png "Before Refresh")

After refresh:
![Mobile Bug in Diaspora*](http://i.imgur.com/7sPZFOj.png "After Refresh")

**Comment by Anime-Machina** [comment]
Any updates? O.o

It is still hapening

**Comment by Flaburgan** [comment]
@Anime-Machina are you running the last develop code? @jaywink fixed some javascript problem, but probably not that.

**Comment by Anime-Machina** [comment]
@Flaburgan I am not running latest develop due MySQL issue's which is being worked by dimaursu16 (IRC). The patch should be out soon after that ill try to verify it at the moment I am running head-p3674a5a0

**Comment by jaywink** [comment]
This is an old bug. WHen you comment on something, it messes up the counts.

I can't find an old issue for this but it's been there for a looong time afaict.

**Comment by Anime-Machina** [comment]
It happens before comments aswel, but comments do make it worse...

**Comment by Anime-Machina** [comment]
In the current dev version it still occours, but less occasional. I beleave it has to do with server rendering.

**Comment by jaywink** [comment]
Since the mobile view changes in development targeted for 0.6, this doesn't happen any more.
