### ISSUE TITLE
Expose Unicorns -o (bind host) and -l (socket listen) options to our configuration system

### ISSUE THREAD

**Issue by jhass** [diaspora/diaspora#5268]
Also for -o default to 0.0.0.0 in development and 127.0.0.1 in production.

if -l is specified -o and -p shouldn't be passed, but it should be possible to construct an argument for -l that does the same thing as passing -o and -p.
##

**Comment by Flaburgan** [comment]
We switched to Puma. Should we close this issue or does it make sense to expose some Puma settings too?

**Comment by jhass** [comment]
I don't remember what I was missing from the configuration back then. The current [`listen`](https://github.com/diaspora/diaspora/blob/develop/config/diaspora.toml.example#L157) directive seems to cover all potential usecases.
