### ISSUE TITLE
Low-contrast menus are hard to see on some displays

### ISSUE THREAD

**Issue by polsVoice** [diaspora/diaspora#5270]
I didn't notice this until I started using Diaspora on my laptop a lot. The options in the top menu bar are *very* hard to see on my laptop's screen, because grey on black is low contrast. I have to tilt the screen just right in order to see them. I think that the menu options should be higher contrast, such as white on black.

**Comment by svbergerem** [comment]
We are now using an inverted Bootstrap navbar with the default Bootstrap colors.

![navbar](https://cloud.githubusercontent.com/assets/3798614/8219401/2f55d2ee-154a-11e5-8b09-b9ebc4d1cc89.png)

@polsVoice Is this better?

**Comment by svbergerem** [comment]
I'll close this since there was no reaction for about half a year.
