### ISSUE TITLE
Nav badge icons icons should use Entypo

### ISSUE THREAD

**Issue by roymckenzie** [diaspora/diaspora#5283]
I noticed on high resolution screens that the nav badges for messages and notifications look fuzzy. This is due to the fact that we are using images for these assets that are not high resolution, obvi. Since we are using Entypo Pictograms in other places on the site, we should use Entypo for other places where we have icons that are image-based where possible. This includes the nav badges and probably the `.rightBar` sections as well. Entypo has a good range of icons we could easily replace many of these with. This will also allow us more control over the style, color, size of these elements without relying on images.

On my own branch I have replaced them in the Nav area. I am happy to do this for the right sidebar as well.

Before:
![screen shot 2014-10-04 at 6 51 42 pm](https://cloud.githubusercontent.com/assets/1065321/4517411/52e01c8c-4c33-11e4-9ae8-d7a0a681efe2.png)

![screen shot 2014-10-04 at 6 57 57 pm](https://cloud.githubusercontent.com/assets/1065321/4517412/5eb755e8-4c33-11e4-9241-d0ddc0223045.png)

After:

![screen shot 2014-10-04 at 6 52 23 pm](https://cloud.githubusercontent.com/assets/1065321/4517413/662684e8-4c33-11e4-9da7-9987354f908e.png)

**Comment by Flaburgan** [comment]
With the port to bootstrap, the rightSide bar is not using images anymore. We should rename this issue indicate that it's about the header now.
