### ISSUE TITLE
HTML Tag to obey line breaks over a block of text

### ISSUE THREAD

**Issue by balasankarc** [diaspora/diaspora#5290]
It would be good to have a tag that makes the included text obey line breaks. Like <poem> tag of mediawiki, so that we shouldn't give <br /> at end of each line while posting a poem or similar stuff.

Like
"poem tag "

Twinkle twinkle little star
How I wonder what you are
Up above the world so high
Like a diamond in the sky

"end of poem tag"

should render as the following

Twinkle twinkle little star 
How I wonder what you are
Up above the world so high
Like a diamond in the sky

**Comment by jhass** [comment]
We now use a CommonMark renderer on the desktop site, see #5526.
