### ISSUE TITLE
Let only valid contact be input in Conversation To

### ISSUE THREAD

**Issue by taro-k** [diaspora/diaspora#5302]
At this moment, we can put any contact or characters in To area of Conversation.
But we can start conversation only with person who puts us into his/her aspect.
Only valid contact should be inputable in Conversation To.
Error message is also misleading.

Previous dicussions:
https://github.com/diaspora/diaspora/pull/5258
https://github.com/diaspora/diaspora/issues/5222
##

**Comment by svbergerem** [comment]
This issue looks fixed to me. Is anyone still able to reproduce this?

**Comment by svbergerem** [comment]
No answer for more than a year. Let's close this. We can reopen if someone is able to reproduce this.
