### ISSUE TITLE
Comment written (not posted) gets deleted after liking post

### ISSUE THREAD

**Issue by TheRadialActive** [diaspora/diaspora#5305]
I went to the single post view of a post. Then I started commenting, but didn't posted/sended it. The written was just draft. Meanwhile I liked the post and the whole draft, all that I had written got deleted. *That shouldn't happen* ;)

**Comment by Flaburgan** [comment]
@svbergerem did https://github.com/diaspora/diaspora/pull/7040 improve the situation? Looks like the problem is still present but I wanted to check with you.

**Comment by svbergerem** [comment]
@Flaburgan no, it didn't. To fix this we will have to separate rendering of the interaction counts and the comment stream. Right now interaction count changes trigger a re-rendering of the  whole right side of the SPV. This is also related to #4425. If we manage to separate interaction counts and the comment stream then we can just append the new comment to the comment stream and rerender the interaction counts.

**Comment by denschub** [comment]
Closed with #7089.
