### ISSUE TITLE
Indicates in the setting that the email is not visibile to the other users

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#5315]
I have a user who asked me about that, we can make that more clear. I'm probably going to open a PR soon, just open this issue as a reminder.

**Comment by aka001** [comment]
I want to work on this issue. 
I have a query, please clarify this.
By design, the email is not visible to other users.
So, is the issue about specifying in the settings page that the email isn't public?

**Comment by Flaburgan** [comment]
Yes, just add a explanation about it, like "Your email will never be seen by other users".
Maybe this should be indicated on the registration page too.

**Comment by aka001** [comment]
Okay. I will do that and send a pr soon.

**Comment by aka001** [comment]
I will continue on this issue later. Meanwhile if someone wishes to fix this issue, feel free to do so.

**Comment by Flaburgan** [comment]
https://github.com/diaspora/diaspora/pull/5956 added this but looks like the port to bootstrap broke it. Should I close this and report it on https://github.com/diaspora/diaspora/issues/6063 ?
