### ISSUE TITLE
Admin page - correlations count broken 

### ISSUE THREAD

**Issue by amckinstry** [diaspora/diaspora#5323]
Hi
I'm on 0.4.1.1 but have always had this issue:
My /admin/correlations page looks like this:
````
Correlations with Sign In Count:

    posts_count, NaN
    comments_count, NaN
    invites_sent_count, NaN
    mentions_count, NaN
    contacts_sharing_with_count, NaN
````

**Comment by jhass** [comment]
The code around this wasn't very pretty and nobody felt an urge to maintain it, so we decided to drop it.
