### ISSUE TITLE
Create a new role: Moderator

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#5324]
Now that https://framasphere.org is launched, we already have 3000 users. So, there is a need to moderate content, at least to check the posts which are reported (accessible at /report) **but** to do so, one needs to be admin. An admin has access to **many** things, including every content of the database using the /admin_panel route. It would be nice to add a new role to diaspora*: "Moderator". Someone who would be allowed to check the reports and deleted posts if needed but who will not have all the access (sidekiq, etc) that an admin have.

**Comment by zaziemo** [comment]
@Realtin and I will be working on this issue.
