### ISSUE TITLE
Less ambiguous error page for locked posts

### ISSUE THREAD

**Issue by usernamenumber** [diaspora/diaspora#5327]
Currently the same 404 page is used for links that don't exist and for links that go to locked posts. If there's a significant security advantage to this ambiguity I don't see it, but I do see a lot of confusion when a post that links back to Diaspora, like an image, is cross-posted to other networks without the post being made public, leading non-Diaspora users to a 404 page.

Yes, the page says `The post you are trying to view is not public, or does not exist! `, but

1. What percentage of people are likely to actually read past the giant "404" on that page?
1. 404 doesn't mean "content not found or maybe locked". It means "content not found".

While there currently isn't much you can do after sharing locked content, once #4323 or #1762 get resolved there will be, provided people who hit the error page are given reason to say "hey buddy, I think you need to change the settings on this post", not "huh, Diaspora generated a broken link".

**Comment by polsVoice** [comment]
I agree. We shouldn't use 404 if it's not an actual HTTP error 404. Simply having "Item not found or inaccessible" should suffice.

**Comment by svbergerem** [comment]
The error page is now our generic 404 page. When we look for a specific post we go through the posts that a user is allowed to see and we are unable to find the specified post. In this context the 404 seems legit. I'll close this issue for now and we can always reopen if there has been a succeeding proposal on loomio.
