### ISSUE TITLE
Private messages do not make notification for new message when new thread is open

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/diaspora#5330]
Steps to reproduce : send a new private message to someone (not a new answer to a previous PM), he will receive no notification.

**Comment by svbergerem** [comment]
Here is a failing spec for this issue:

```diff
diff --git a/spec/controllers/conversations_controller_spec.rb b/spec/controllers/conversations_controller_spec.rb
index ae07609..5bc1878 100644
--- a/spec/controllers/conversations_controller_spec.rb
+++ b/spec/controllers/conversations_controller_spec.rb
@@ -127,6 +127,12 @@ describe ConversationsController, :type => :controller do
         expect(Conversation.first.author).to eq(alice.person)
       end
 
+      it 'increases the unread message count for the contact' do
+        post :create, @hash
+        visibility = ConversationVisibility.where(:conversation_id => Conversation.first.id, :person_id => alice.contacts.first.person.id).first
+        expect(visibility.unread).to eq(1)
+      end
+
       it 'dispatches the conversation' do
         cnv = Conversation.create(
           {

```

**Comment by svbergerem** [comment]
When a user creates a new conversation [deliver_to_local](https://github.com/diaspora/diaspora/blob/develop/lib/postzord/dispatcher.rb#L123) is called. That calls `Workers::Receive.perform_async` which calls [Postzord::Receiver::Private.parse_and_receive](https://github.com/diaspora/diaspora/blob/develop/lib/postzord/receiver/private.rb#L31).

In the logfile I can see `user:2 starting private receive from person:1e9a3f06d46616cb`. Then we call `receive_object` and we are in this line : [Postzord::Receiver::Private#L49](https://github.com/diaspora/diaspora/blob/develop/lib/postzord/receiver/private.rb#L49). The next line would create a notification. We call `@object.receive` which should call [Conversation receive](https://github.com/diaspora/diaspora/blob/develop/app/models/conversation.rb#L88).

In the logfile I see `failed to save received object: ["Guid has already been taken"]` which is created in [Workers::Base](https://github.com/diaspora/diaspora/blob/develop/app/workers/base.rb#L20) I guess that is the reason why we don't create notifications.

I don't know how to fix it and I don't even know if everything I wrote is right but that is all I was able to find out with my limited RoR knowledge.

**Comment by svbergerem** [comment]
Forget what I wrote, I fixed this in #5686.

**Comment by Flaburgan** [comment]
<3

**Comment by Flaburgan** [comment]
@svbergerem you can claim the bounty btw: https://www.bountysource.com/issues/5216010-private-messages-do-not-make-notification-for-new-message-when-new-thread-is-open
