### ISSUE TITLE
Feature: Mark the year of the notifications on the Notifications page (desktop/mobile)

### ISSUE THREAD

**Issue by Makailija** [diaspora/diaspora#5361]
At the moment, the year of the notifications is not explicitly stated on the Notifications page. This makes the page a bit confusing, especially in the case that you have just a few notifications from a longer period of time. At the moment, you could have a Notifications page which looks like this:

**24 September** XXX started to share with you *(a month ago)*
**15 February** YYY commented your post *(8 months ago)*
**4 July** ZZZ has mentioned you *(a year ago)*
**3 December** WWW has liked your post *(2 years ago)*

(This is of course a very crude mock-up, but it illustrates well what I am after.)

First you are probably confused by the odd chronological order: December, July, February, September. Then you figure out that the notifications are from different years. Then, if you want to know from which year a notifications is are, you have to *count* it backwards from its timeago comment. So, after some brain-twisting, you have found out that WWW liked your post in 2012. (Or if you are really lucky, you notice that a tooltip with the full date is shown if you hoover over the timeago comment. I only noticed that after reading about it on another issue discussion.)

Be that as it may, adding the year of the notifications would make the page much more intuitive. I think the best way to do it would be to separate the notifications of a certain year by a heading. So instead of the confusing list above, you would have a clearer list like this one:

### 2014 ###
**24 September** XXX started to share with you *(a month ago)*
**15 February** YYY commented your post *(8 months ago)*
### 2013 ###
**4 July** ZZZ has mentioned you *(a year ago)*
### 2012 ###
**3 December** WWW has liked your post *(2 years ago)*

No confusion, brain-teasing, or searching for hidden tooltips.

This applies both to desktop and mobile versions of the Notifications page. I didn't find a similar issue, but I think #4866  might be referenced.

**Comment by goobertron** [comment]
@svbergerem I've just thought of one possible non-cluttering (or not-particularly-cluttering) solution: place the year either *above* the list on each page, or *along with* the date at the top of the list on each page. If the page contained notifications from more than one year, add the year also to the most recent date from the previous year, wherever it appeared on the page. E.g.:

**04**
January
2015

**02**
January

**01**
January

**31**
December
2014

**29**
December

**26**
December

... and so on

I personally still don't think that we need to add the year to the list, but this issue has been linked again and this possible solution occurred to me, so I thought I'd mention it.

**Comment by jhass** [comment]
Why not add a separator when we go Jan -> Dec?

```
 05 Jan                          
                                 
                                 
 01 Jan                          
                                 
+------------+  2014 +----------+
 28 Dec                          
```

And also display that separator at the top if the first notifications year is not the current year.

**Comment by goobertron** [comment]
That could work!
