### ISSUE TITLE
Message pop-up not resizable

### ISSUE THREAD

**Issue by Cypouz** [diaspora/diaspora#5363]
Hi!

On diaspora-fr pod. When you start a private discussion from the contact page of a person, the pop-up is not resizable (the text field is resizable, but not the wrapper). It's a recent bug, because it was a good feature that worked recently.

**Comment by svbergerem** [comment]
Looks like Bootstrap 3 would fix this: http://getbootstrap.com/javascript/#modals-related-target (Open the modals and resize the textarea)

**Comment by svbergerem** [comment]
The Bootstrap 3 port fixed this issue.
