### ISSUE TITLE
[Federation] Send the mentionned user to pods with the post

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#5369]
When someone sends a post where he mentions a user, the mention will not appear in the post on the pods which don't know this user. The user should be either sent by the pod in the same time than the message or fetched by the pods which don't know him, to be able to display the mention.

**Comment by svbergerem** [comment]
I think this is a duplicate of #4491.

**Comment by Flaburgan** [comment]
You're right, we discussed about it with Jonne and I forgot to close this one, sorry.
