### ISSUE TITLE
Show user's contacts first in tags page, then the rest of the world.

### ISSUE THREAD

**Issue by balasankarc** [diaspora/diaspora#5370]
This is a feature request. When I go to a specific tag page (eg: poddery.com/tags/privacy) , on the left side, I get a list of people who also follow the same tag. I would like it to be sorted so that those who are in my contacts are listed there first and then the remaining world.

**Comment by svbergerem** [comment]
I'll close this. @balasankarc if you still want this feature please create a thread on loomio. We can reopen this issue after a loomio vote.
