### ISSUE TITLE
Markdown non working properly in a particular case

### ISSUE THREAD

**Issue by Airon90** [diaspora/diaspora#5379]
Give a look to this example: https://diasp.eu/posts/2476271

The bug is on the word "bug" and "developers": the "u" in "bug" should be italics and the "op" in "developers" should be bold.

It seems that italics and bold (do underline and strike exist on Markdown?) don't work properly on Diaspora when applied on a part of a word instead on the entire word, while it seems that Friendica correctly render markup. It seems that symbol substitution such as (r) → ® work properly (I made a misake in copy-paste the "code").

I think that this bug is somehow related to bug #4767 because it is related to the space character

**Comment by jhass** [comment]
Fixed by #5526
