### ISSUE TITLE
@mention drops two copies of the username into markdown textbox

### ISSUE THREAD

**Issue by gordon-morehouse** [diaspora/diaspora#5382]
## ACTUAL BEHAVIOR

If I type @ and then a letter to bring up a list of mentionable profiles, then click one, the user's name is dropped into the Markdown box both as plain text and in light blue linky text, with the cursor placed in between the plain text and the linky text. If I backspace one character of the plain text, it deletes the entire mention.

## EXPECTED BEHAVIOR

If I create an @mention, it should be dropped into the markdown box *once* with the cursor placed *after* the linky text. Backspacing or highlighting and deleting the linky text should delete the mention.

**Comment by svbergerem** [comment]
I'm also not able to reproduce the bug described in this issue. Feel free to reopen if you are able to reproduce it.

**Comment by gordon-morehouse** [comment]
I think it was fixed at or before 0.5.x. Thanks.
