### ISSUE TITLE
@mention general UX issues.

### ISSUE THREAD

**Issue by gordon-morehouse** [diaspora/diaspora#5383]
* What happens with the dropdown with a user with hundreds of contacts when that user types a common letter after the @?
* Is this a simple substring search? If so, shouldn't it do beginning-substring (startswith) and sort non-beginning (contains) matches below startswith matches?
* The tab completion feature is non-obvious to non-expert users and may cause users to use the mouse when it is unnecessary, slowing publish workflow. Maybe there should be a small tooltip-style header on the dropdown saying "hit tab to mention selected user", if a dropdown continues to be used. The tab can disappear after a number of times shown and/or a click on a UI element.
* ~~Is there a method of mentioning users who are not contacts? If not, why not? If so, it should be made obvious to the user, perhaps in a similar top-of-dropdown tooltip which can be cleared.~~ (not implemented to prevent mention-spamming)
* ~~If mentioning users who are not contacts and thus won't populate the dropdown is possible, what about users with whitespace in their names?~~
* ~~If mentioning users who are not contacts and thus won't populate the dropdown is possible, what about users with characters in their names which the mentioner cannot easily type?~~
* ~~Regarding the above two issues, when mentioning users who are not contacts, should they eventually populate the dropdown when the global match subset is small enough? This seems better but unsatisfactory, especially users with weird-character names.~~
* ~~Could mentioning users who are not contacts be accomplished with an either-or approach of "type the full username, possibly in quotes" or "click a UI element in the dropdown which opens global user search"?~~

**EDIT:** I've crossed out the questions regarding a settled feature. However, some of those questions (usernames with whitespace, usernames with weird characters) still do apply in the case of an unusable dropdown, so I'm rephrasing them below.

* If the dropdown is unusable due to being too long or other UI problems, how can a user mention a contact with whitespace in the contact's name?
* If the dropdown is unusable due to being too long or other UI problems, how can a user mention a contact whose username is made up of weird unicode characters, as so many people like to do?
* How can a user mention a contact **without Javascript enabled,** e.g. if the user disables Javascript for legitimate security reasons such as browsing over the Tor network?

Please feel free (or advise me) to split this into multiple issues if some of these have merit.

**Comment by witgithacker** [comment]
http://stackoverflow.com/questions/930716/alternatives-to-javascript
+1 @jhass

**Comment by svbergerem** [comment]
@gordon-morehouse 
> What happens with the dropdown with a user with hundreds of contacts when that user types a common letter after the @?

We will show you at most 5 of those users and you can refine the search results by typing more characters.

> Is this a simple substring search?

Yes.

> If so, shouldn't it do beginning-substring (startswith) and sort non-beginning (contains) matches below startswith matches?

I'm not sure if we should put prefix matches in front of other infix matches. Maybe you only know the last name of your contact. In that case you will only have an infix match and not an prefix match. 

> The tab completion feature is non-obvious to non-expert users and may cause users to use the mouse when it is unnecessary, slowing publish workflow. Maybe there should be a small tooltip-style header on the dropdown saying "hit tab to mention selected user", if a dropdown continues to be used. The tab can disappear after a number of times shown and/or a click on a UI element.

facebook does the same and also has no “tooltip-style header” so I'd say this is obvious enough for “non-expert users”. If you think that we need something similar to a tooltip it would be great if you could open a new issue.

> If the dropdown is unusable due to being too long or other UI problems, how can a user mention a contact with whitespace in the contact's name?

By adding @{User Display Name; user@pod.tld} to the publisher, but I don't see any UI problems that would make the dropdown unusable.

> If the dropdown is unusable due to being too long or other UI problems, how can a user mention a contact whose username is made up of weird unicode characters, as so many people like to do?

By adding @{W€ırÐ Unı¢Øð€ ¢Ħæ®æ©¢€Rẞ; user@pod.tld} to the publisher.    

> How can a user mention a contact without Javascript enabled, e.g. if the user disables Javascript for legitimate security reasons such as browsing over the Tor network?

Maybe from the mobile website when #4817 has been fixed but definitely not from the desktop version. As soon as we have a proper API you might also use that to mention contacts without javascript enabled.

Is there anything else I forgot or should we close this issue?

**Comment by svbergerem** [comment]
No answer for more than 6 months, so I'll close this issue.
