### ISSUE TITLE
Add public feed metadata to profile page (rel="alternate" for RSS and Atom)

### ISSUE THREAD

**Issue by mmn** [diaspora/diaspora#5385]
I figured I want to add some metadata to the HEAD element in pages rendered for `/u/nickname` but I'm not sure where to start with the templates.
What I want to add is a: `<link rel="alternate" href="..." type="application/atom+xml" />`
since the current machinery in StatusNet and GNU social is to fetch the profile page's HTML and find such an element, describing where the public feed is (if it wasn't retrieved via WebFinger in the first case).

The &lt;link/&gt; element will also allow RSS/Atom readers (including Firefox) to recognize the public feed from the user's profile page, letting you easily subscribe.

Check for example the output of a GNU social profile grep:ed for rel="alternate":
> $ curl -s https://social.umeahackerspace.se/mmn | grep 'rel="alternate"'
>   &lt;link rel="alternate" href="https://social.umeahackerspace.se/api/statuses/user_timeline/2.as" type="application/stream+json" title="Fl&#xF6;de av notiser f&#xF6;r mmn (Activity Streams JSON)"/&gt;
>   &lt;link rel="alternate" href="https://social.umeahackerspace.se/mmn/rss" type="application/rdf+xml" title="Fl&#xF6;de av notiser f&#xF6;r mmn (RSS 1.0)"/&gt;
>   &lt;link rel="alternate" href="https://social.umeahackerspace.se/api/statuses/user_timeline/2.rss" type="application/rss+xml" title="Fl&#xF6;de av notiser f&#xF6;r mmn (RSS 2.0)"/&gt;
>   &lt;link rel="alternate" href="https://social.umeahackerspace.se/api/statuses/user_timeline/2.atom" type="application/atom+xml" title="Fl&#xF6;de av notiser f&#xF6;r mmn (Atom)"/&gt;

From what I understand, the line outputting the metadata (at least for Atom, not sure if Diaspora has RSS feed generation capability) would be constructed like this:
`%link{:rel => 'alternate', :type => 'application/atom+xml', :href => "#{@person.public_url}.atom"}`

flaburgan on IRC hinted that this could be dropped into `app/views/people/show.html.haml` - just making sure it's in the `- content_for :head do` segment.

I'll try whipping up a patch, but I don't currently have a Diaspora pod to play with, so someone more experienced with the codebase is welcome to produce it :)

**Comment by svbergerem** [comment]
`<link rel="alternate" href="..." type="application/atom+xml" />` exists on profile pages on develop and master.
