### ISSUE TITLE
Chat todos, notes and improvements

### ISSUE THREAD

**Issue by Zauberstuhl** [diaspora/diaspora#5398]
I think it makes sense to great a TODO list (summary) for the chat application.
- [x] JSXC design tweaks (I appreciate any help here)
- [x] Clean up diaspora code e.g. https://github.com/diaspora/diaspora/pull/5073#issuecomment-63181652
- [x] Support OTR? https://github.com/diaspora/diaspora/pull/5073#discussion_r20215964
- [ ] Polish token API or replace it?! https://github.com/diaspora/diaspora/pull/5073#discussion_r14968688
- [x] FAQ for users, point out that you need to activate the chat for your aspects
- [ ] Think about a way how to introduce new people to the chat.
- [x] Add changelog entry
- [x] language and translation (see diaspora/jsxc#40)
- [ ] Make a clean installation process
...
##

**Comment by Zauberstuhl** [comment]
@Flaburgan you mentioned moving jsxc to more diaspora pages?!

Currently jsxc is available on:

* /commented
* /liked
* /activity
* /stream

In my opinion that is enough, no? Everything else are 'special' pages like SPV, profile and setting pages.

**Comment by Flaburgan** [comment]
Well, the problem is, now I have to think "wait, if I naviguate there, will that break my current conversation?". There is no indication to the user that they will logout if they go to the SPV, or on a user profile for example. So imo this is a problem: I should always be online.

**Comment by AugierLe42e** [comment]
I see design tweaks is not already checked. Can you detail this point a bit more ?

**Comment by ManiacTwister** [comment]
I would suggest to make the jabber server url used in bosh connections configurable. For example my diaspora instances runs under ```diaspora.domain.tld``` and my (e)jabber(d) server runs under ```jabber.domain.tld```. Or is this already possible?

**Comment by jhass** [comment]
Just add another reverse proxy to your configuration, the wiki has examples. As a bonus you'll be free from mixed content and CORS headaches.

**Comment by ManiacTwister** [comment]
@jhass Imho that doesn't help, because the application url ist used in the bosh payload. For example

**Comment by jhass** [comment]
And your server rejects that because...?

**Comment by ManiacTwister** [comment]
```[error] <0.16391.2>@ejabberd_http_bind:check_bind_module:1226 You are trying to use BOSH (HTTP Bind) in host <<"diaspora.domain.tld">>, but the module mod_http_bind is not started in that host. Configure your BOSH client to connect to the correct host, or add your desired host to the configuration, or check your 'modules' section in your ejabberd configuration file.```

**Comment by jhass** [comment]
Interesting, Prosody doesn't care about that.

So you wrote a plugin for ejabberd that supports our custom authentication (token authencation for JSXC and peppered BCrypt for other clients to sign into their diaspora account)?

**Comment by ManiacTwister** [comment]
Not yet, but since ejabbers supports auth_external im relatively optimistic that this shouldn't be too hard to implement. :)

**Comment by Zauberstuhl** [comment]
//added https://github.com/diaspora/diaspora/issues/6343#issuecomment-135394214

**Comment by AugierLe42e** [comment]
> Think about a way how to introduce new people to the chat.

What about a tour? Like what's done when first login into diaspora*?

**Comment by Zauberstuhl** [comment]
I am kinda frustrated right now. I just updated to the latest dev version and jsxc seams to be broken again. Since I haven't touched anything I assume it is related to latest diaspora-ui changes.

Could you do me a favor in future and include a quick test for jsxc if you change the ui interface?
You don't have to start any xmpp server.. Just check if all buttons are at the correct place if you open the chat-box.

Thanks in advantage, Lukas 

@AugierLe42e @svbergerem @Flaburgan

**Comment by AugierLe42e** [comment]
How is it broken?

**Comment by Zauberstuhl** [comment]
I am currently fixing it. That is not the problem :)

**Comment by AugierLe42e** [comment]
Nope, I just want to know because I haven't seen design changes for a while, so I wonder since when it has been broken and how. Be cause, it has indeed been broken on diaspote for a while but I thought it was a misconfigurtion.

**Comment by Zauberstuhl** [comment]
@AugierLe42e you cannot access several buttons anymore. why the bug appeared; I have no idea. with 0.1.4 it is fixed

---

Change of topics;

https://wiki.diasporafoundation.org/Vines should be renamed in something like https://wiki.diasporafoundation.org/Chat. Or separate stuff like JSXC, Vines and FAQ but in my opinion a single side is sufficient.

**Comment by AugierLe42e** [comment]
> @AugierLe42e you cannot access several buttons anymore. why the bug appeared; I have no idea. with 0.1.4 it is fixed

That's it. There were not connection button

**Comment by piraz** [comment]
Is anybody able to join a conference using prosody as back-end and JSXC as client?

**Comment by pravi** [comment]
@piraz https://github.com/diaspora/jsxc/issues/148

**Comment by lancegilbert** [comment]
I have submitted a new pull request which allows for the usage of HTTPS BOSH endpoints without modification to the jsxc helper:

https://github.com/diaspora/diaspora/pull/7100

Adding a simple proto: https in diaspora.yml inside the chat.server.bosh does the trick!

**Comment by denschub** [comment]
Unassiging all milestones. Nobody seems to be working on this, and I don't feel like blocking a release for this.

**Comment by denschub** [comment]
@Zauberstuhl what's the state of diaspora-jsxc in general? any plans on maintaining this?

**Comment by Zauberstuhl** [comment]
In general it works. There are still some design issue like "hiding offline contacts" will not working in firefox for some reason. I could use some help here

**Comment by SuperTux88** [comment]
The chat was removed with #8069, this is obsolete now.
