### ISSUE TITLE
Number of photos on the profile page is always <=15

### ISSUE THREAD

**Issue by svbergerem** [diaspora/diaspora#5402]
The photos controller uses `current_user.photos_from(..)` [here](https://github.com/diaspora/diaspora/blob/develop/app/controllers/photos_controller.rb#L28) which is defined in [/app/models/user/querying.rb](https://github.com/diaspora/diaspora/blob/develop/app/models/user/querying.rb#L152) and uses `prep_opts` which is defined [here](https://github.com/diaspora/diaspora/blob/develop/app/models/user/querying.rb#L160) and sets the limit of returned photos to 15.

**Comment by Faldrian** [comment]
I think the way to go would be to query a separate number from DB. Query for "number of all photos from the user" and deliver them as own property in the json response.

Unfortunately I have not enough knowledge to implement something like that...
