### ISSUE TITLE
Add links to /commented and /liked streams in sidebar

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#5469]
These views are available, but currently, as far as I know, it is only possible to access them by adding the relevant path manually to the pod domain in the URL bar.

It would be good to provide links to them under 'My Activity' in the sidebar menu, so that when 'My Activity' is clicked (or when /activity is loaded by some other method), the two options appear under 'My Activity' in the sidebar menu. As so:

![streams](https://cloud.githubusercontent.com/assets/2530168/5359434/47acd408-7fb5-11e4-9b87-5437e286b7f8.png)

I'd like to try implementing this myself, so I'm not just someone who says 'You should do this!', but on looking at the code it looks too complex for me, so I won't volunteer!
##

**Comment by Fensterbank** [comment]
Hm, what happened with this commit? This feature never came...

**Comment by Flaburgan** [comment]
I still have to fix the legend of the avatars in the right column. Waiting for #6535 to know if we keep it or not.

**Comment by noplanman** [comment]
I just came across this now and wanted to point out a userscript that I put together when I joined diaspora*.
You can find it [here](https://github.com/noplanman/DiasPlus) and it adds the 2 mentioned links in the top menu (and a few other features).

**Comment by Flaburgan** [comment]
I still plan to rebase my PR on develop, but that's not targeted for 0.6 so we have more urgent things to do.

**Comment by mahonrig** [comment]
Looks like this was completed, close this issue?

**Comment by SuperTux88** [comment]
You are right, closing 👍

**Comment by noplanman** [comment]
In which version were they added?
Will have to update my userscript to remove them to prevent any duplicate links being added.

**Comment by SuperTux88** [comment]
0.6.5.0 (I marked the issue with the milestone)

**Comment by noplanman** [comment]
Aaah right, just saw that they get added as submenu items, all clear!
Thanks @SuperTux88
