### ISSUE TITLE
It is possible to open two comment boxes for a single post on the mobile view

### ISSUE THREAD

**Issue by Makailija** [diaspora/diaspora#5483]
On the mobile view, it is possible to open two comment boxes for one and the same post, which is a bit confusing at the least. There are two ways of doing this:

a)
1. Click the "x reactions" button.
2. Click the "Comment" button that appeared below: the first comment box appears (below the possible already-existing comments).
3. Click the pencil icon on the right: the second comment box appears (below the first one).
![comments1](https://cloud.githubusercontent.com/assets/2229403/5489110/c03c9ba4-86ce-11e4-87e7-4c00de58da13.png)

b)
1. Click the pencil icon on the right: the first comment box appears.
2. Click the "x reactions" button. The possible already-existing comments and the "Comment" button appear below the first comment box.
3. Click the "Comment" button that appeared below: the second comment box appears below the possible already existing comments. (So in this case there is one comment box on the top, comments between and another comment box on the bottom.)
![comments2](https://cloud.githubusercontent.com/assets/2229403/5489106/b95232c2-86ce-11e4-919c-19036297a5c9.png)

The expected behaviour is that it would be impossible to open two comment boxes, but I'm not quite sure how this should be attained. One possibility would be greying out the pencil icon after clicking the "Comment" button. (I of course mean the one appearing after clicking the "x reactions" button, not the one next to the comment box.) In this case, however, it should be taken into consideration that in the case (i) that the "x reactions" button is clicked first and then the "Comment" button is clicked, the comment box would appear *below* the comments; by contrast, in the case (ii) that the pencil icon is clicked first and after that the "x reactions" button is clicked, the comment box would appear *above* the comments

Or maybe the problem could be solved just by getting rid of the "Comment" button altogether? (again, I mean the one appearing after clicking the "x reactions" button.) To me it seems that it would be the best solution.

**Comment by theworldbright** [comment]
Here is my plan to address this issue:

On reaction button tap/click
* If comment box is already open
  * Show comment/reactions as before
* If comment box is not already open
  * Show comment/reactions as before
  * Open new comment box

On comment submit
 * Show comment/reactions (with the comment that was just submitted)
 * Open new comment box

The comment box will always appear below the comment/reactions (if it is showing) and the "comment" button will always show with a text area.
