### ISSUE TITLE
Mobile: Comment button turns uresponsive when trying to submit an empty comment

### ISSUE THREAD

**Issue by Makailija** [diaspora/diaspora#5485]
Commenting on the mobile view, if you have an empty comment textarea and if you click the Comment button, the button turns unresponsive, saying just ”Commenting...”and staying like that infinitely. Curiously enough, the post that you tried to "comment" appears in your "My activity" stream after this.

I guess the expected behaviour would be to focus on the textarea, just like on the desktop view.

**Comment by polsVoice** [comment]
So, this has been fixed?

**Comment by jhass** [comment]
No, #5890 is not merged.

**Comment by theworldbright** [comment]
The desktop view has the following code block that causes the comment box to be focused again if the comment is empty.

```  
createComment: function(evt) {
    if(evt){ evt.preventDefault(); }
    
    var commentText = $.trim(this.$('.comment_box').val());
    this.$(".comment_box").val("");
    this.$(".comment_box").css("height", "");
    if(commentText) {
      this.model.comment(commentText);
      return this;
    } else {
      this.$(".comment_box").focus();
    }
  },
```

Is it sufficient to prevent the comment creation request from reaching the controller with a client side check in the mobile view as follows? 

```
  $(document).on("click", ".new_comment", function(evt) {
    var form = $(this);
    var commentBox = form.find('.comment_box')
    var commentText = $.trim(commentBox.val());
    if (!commentText) {
        commentBox.focus();
        return false;
    }
  });
```
