### ISSUE TITLE
500 error when trying to view page:  /admin_panel

### ISSUE THREAD

**Issue by RichKavanagh** [diaspora/diaspora#5503]
I get this error when trying to view mypod.com/admin_panel

>  500: Internal server error.
> Our bad! Sorry about that. :(

(which is the standard Diaspora 500 page)

The *production.log* file catches this:

> Started GET "/admin_panel" for (ip removed) at 2014-12-29 17:15:32 +0000
> Processing by RailsAdmin::MainController#dashboard as HTML
> Completed 500 Internal Server Error in 18.1ms
> 
> Errno::EPIPE (Broken pipe - <STDOUT>):
>   lib/rack/chrome_frame.rb:39:in `call'
>   lib/unicorn_killer.rb:35:in `call'

**Comment by jhass** [comment]
Yes, that trace is unfortunately very unhelpful, it's a general  error in a very general place.

**Comment by RichKavanagh** [comment]
That's a shame. I can't reproduce this bug on another pod as I don't know what actually cause of the issue is.  If you think of a way for me to gather some more diagnostic and/or some more detailed error information to help with this bug then I'll gladly provide it :+1:

**Comment by axilleas** [comment]
I guess you already tried to restart unicorn?

**Comment by RichKavanagh** [comment]
> I guess you already tried to restart unicorn?

Nope, that didn't even cross my mind.

So thank you for the suggestion, the admin panel is now working perfectly! :+1:

**Comment by axilleas** [comment]
Cool! Most of my encounters with 500 relate to unicorn :)

**Comment by RichKavanagh** [comment]
I'll remember that for next time, thanks again :)
