### ISSUE TITLE
"toggle mobile" should be "Toggle Mobile"

### ISSUE THREAD

**Issue by maliktunga** [diaspora/diaspora#5505]
Simple consistency issue. All words in the Mobile sidebar start with capitals except "toggle mobile". Same with the bottom of the page on the Desktop and at the bottom of the right-hand sidebar.

**Comment by jaywink** [comment]
Closing, [Sentence case was voted for](https://www.loomio.org/d/kY0wClao/capitalisation-of-the-entire-ui-in-the-english-language).
