### ISSUE TITLE
Provide a unicorn.rb.example and do not check unicorn.rb in version control

### ISSUE THREAD

**Issue by axilleas** [diaspora/diaspora#5507]
This is more of a discussion to see if you guys agree. My rationale is that `unicorn.rb` can be customized and if you do so it's picked by git as changed. Not a big issue, but for newbies it could be confusing when updating diaspora.

If we do that we'd have to update all the installation guides. I can work on that.
##

**Comment by axilleas** [comment]
Well, I believe all options in http://unicorn.bogomips.org/Unicorn/Configurator.html should be configurable.

Personally I change the pid and socket lines. Then one would like to change the `backlog` number, the user/group which the worker could run, etc.

Also, the [working directory](http://unicorn.bogomips.org/Unicorn/Configurator.html#method-i-working_directory) is useful.

**Comment by Flaburgan** [comment]
We are now using Puma and not Unicorn anymore, closing.
