### ISSUE TITLE
Conversations layout

### ISSUE THREAD

**Issue by Greezael** [diaspora/diaspora#5512]
I've seen bugs referencing the conversations section (https://github.com/diaspora/diaspora/issues/4818 for example), but I don't really see anything about something that to me is obvious:

**Why is the last message on the top of the page, and the reply input box on the bottom?**

I see that there seems to be a broken autoscroll functionallity, that I cannot really understand, but these two should go together, for pure convenience.

Also, if the original idea is to have the last comment with the reply box on bottom, and scroll there automatically when entering the conversation, a back to top button would be quite handy.

Sorry if this has been said or anything, but I'm starting to use Diaspora daily and this is really annoying.

**Comment by Flaburgan** [comment]
@Greezael I guess you are on diasp.org. This is a modification done by @dmorley, on the master codebase, the last message is at the bottom.

**Comment by Greezael** [comment]
O_O T_T

Thank you for leting me know this.


(Whyyyyy????????)
(I'll send him a message or something)
