### ISSUE TITLE
[deprecated] I18n.enforce_available_locales will default to true in the future

### ISSUE THREAD

**Issue by kkretsch** [diaspora/diaspora#5515]
As I'd like to be without any warning at all during start time, how can we get rid of that message?:

16:33:46 web.1     | [deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.
16:33:47 sidekiq.1 | [deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.

Some search gives the advice of adding a line to application.rb but I'd prefer some magick within my diaspora.yml file only.

**Comment by jhass** [comment]
Someone would need to research what should be added to where and whether we want to keep the old value or adopt the new one, then pull request the change.

**Comment by kkretsch** [comment]
I just added:
I18n.config.enforce_available_locales = false
to diaspora/config/application.rb at line 33 (after the commented config.i18n part) and it seems to start up normal, now without any warning.
The value false should be the explicit default from before, so I don't expect any change in behaviour.

**Comment by jhass** [comment]
Yet, I still do wonder if we don't actually want the new default value.

**Comment by svbergerem** [comment]
I don't remember seeing the warning recently and I also found nothing in my logfiles. @kkretsch can you confirm that the warning is gone?

**Comment by svbergerem** [comment]
@jhass Is there anything left to do or should we close this issue?

**Comment by jhass** [comment]
No idea, let's reopen once we see it again.
