### ISSUE TITLE
Title length (of Cyrillic) in the atom feed is too limited

### ISSUE THREAD

**Issue by poddage** [diaspora/diaspora#5517]
Cyrillic titles in the atom feed are shortened too much.

Only approx 16 characters are shown and then goes "..."

Is this hard coded feature? or configurable by pod configuration?

**Comment by Flaburgan** [comment]
It's 20 character and it's hardcoded, I agree this is too short, I talk about it here https://github.com/diaspora/diaspora/issues/4370

**Comment by svbergerem** [comment]
Fixed by #6020.
