### ISSUE TITLE
Modify /users/sign_in to /login and others

### ISSUE THREAD

**Issue by mykhael** [diaspora/diaspora#5518]
So I've been trying to work around changing /users/sign_in, /users/sign_up, and /users/sign_out to more simpler routes such as /login, /signup, and /logout which I recommend Diaspora implementing for a better MVC layout. I discovered during some documentation reading on devise. The current document can be displayed [here](https://github.com/plataformatec/devise/wiki/How-To:-Change-the-default-sign_in-and-sign_out-routes).

**Comment by jhass** [comment]
We already have https://github.com/diaspora/diaspora/blob/develop/config/routes.rb#L130 ?

**Comment by mykhael** [comment]
Hmm, I did not see this but does it automatically redirect from the /users/sign_in to just /login?

**Comment by Flaburgan** [comment]
Moreover, some external application, though not officially supported, are using the actual routes. I don't want to break that if there is no real benefit.

**Comment by mykhael** [comment]
I completely understand, I'll find my way around this issue locally.

**Comment by jhass** [comment]
It redirects /login to /users/sign_in

**Comment by mykhael** [comment]
@jhass This is interesting, I see how you guys have done things which is somewhat what I was looking for.
