### ISSUE TITLE
Standardise capitalisation throughout Diaspora

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#5520]
There has been a couple of PRs in the past couple of days changing capitalisation in individual strings. It would be a good idea to make a decision on how text will be presented in Diaspora and standardise all text to that decision in one go.

See #5513 and #5519. There's now a discussion in [Loomio](https://www.loomio.org/d/kY0wClao/capitalisation).

**Comment by goobertron** [comment]
And another: #5506.

**Comment by maliktunga** [comment]
I'm taking a look at https://github.com/diaspora/diaspora/blob/c6fc19c6d1211cda3b8f2c7776c9e88fb7fa6b35/config/locales/diaspora/en.yml

Which strings should _not_ begin with a capital letter? Currently, I would be tempted to capitalize [_photos: "photos"], not sure about [or: "or"], then I'd capitalize [next: "next"], [previous: "previous"] and [_terms: "terms"], strings like [invalid: "is invalid."] seem to be precedated with something, strings like [zero: "you currently have no invites left %{link}"] seem to be full sentences, [view_profile: "view profile"], [add_invites: "add invites"] and [close_account: "close account"] would be capitalized, [last_seen: 'last seen'] and [account_closed: 'account closed'] I'm not sure, [nsfw: '#nsfw'], [unknown: 'unknown'], ['yes': 'yes'], ['no': 'no'] not sure either, [2weeks: "2 Week"] would be lowercased but it makes no sense (it should be "2 weeks"), [go: "go"] I'm not sure, [unknown_person: "unknown person"], [zero: "no aspects"], [rename: "rename"], [update: "update"], [updating: "updating"], [done_editing: "done editing"], [edit_aspect: "edit aspect"], [community_spotlight: "community spotlight"], [remove: "remove"], [post_a_message: "post a message >>"],  I don't know, [introduce_yourself: "This is your stream. Jump in and introduce yourself."] has an extra space, [zero: "no comments"] I'm not sure, [zero: "0 reactions"] is inconsistent with the former, [zero: "contacts"] makes no sense, [zero: "contacts"], [add_to_aspect_link: "add contacts to %{name}"]... and it goes on and on.

Should I give a try at making the change in one shot and others will revert specific changes that I mistakenly make?

**Comment by RichKavanagh** [comment]
Wait for the Loomio vote to finish, it closes in two days.

**Comment by maliktunga** [comment]
The proposal ended, and the majority of voters are in favor of sentence case capitalization.

As promised, I made the ~200 changes in one commit: https://github.com/diaspora/diaspora/pull/5579

Please make sure I did not miss anything! Thank you.

**Comment by RichKavanagh** [comment]
Much appreciated @maliktunga !!!

I guess this issue #5520 can be closed now.

**Comment by maliktunga** [comment]
@RichKavanagh No problem! Thanks to you for supporting a uniform capitalization.

**Comment by goobertron** [comment]
Thanks, @maliktunga.

Rich, let's wait until the PR has been merged. I'd like to check the capitalisation first.

**Comment by maliktunga** [comment]
I'm pretty confident my PR can be merged now. https://github.com/diaspora/diaspora/pull/5579

**Comment by goobertron** [comment]
I'm working on this now maliktunga has stopped.

**Comment by goobertron** [comment]
I need to fix various tests which have been broken by the changes to capitalisation, e.g. 'My Aspects' to 'My aspects'. What I'd really like to do is to make these text-independent: that is, rather than changing the string in the test to 'My aspects', give the string ID (`javascripts.my_aspects` in this case).

@jhass I'd be grateful if you would help me with the syntax of this. I'm sure I did this for some tests last year, but can't now find that work. For example, in https://github.com/diaspora/diaspora/blob/develop/features/step_definitions/aspects_steps.rb#L47

    click_link 'My Aspects'

could perhaps become something like

    click_link 'javascripts.my_aspects'

... but that doesn't work. Is there a way to do this? If so, once this PR has been merged, I'd be happy to work on making all cukes in the test suite text-independent in this way, so that in future small changes to text strings won't break tests.

Hope that sounds like a good idea, and thanks in advance for any help you can give.

**Comment by jhass** [comment]
I see two ways:

The class way is to select the element with CSS and XPath selectors that don't depend on the text value, for example in this case that could be 'click_link "li.all_aspects:nth-child(4) > a:nth-child(1)"' or adding an ID to element and using that. That trades the breakages on text changes against breakages on DOM changes.

The other way we could try out is pulling the current translation via `I18n.t`, for the example at hand: `click_link I18n.t("javascripts.my_aspects")`. I haven't noticed that approach in the wild yet, so I'm unsure if there are any downsides I'm overlooking.

**Comment by goobertron** [comment]
Brilliant, thanks so much for your quick reply. I'll play with those and see if I can work something out.

If this is something worth doing throughout the test suite, I notice there's a currently open PR, #5580, with some new tests with text strings.

**Comment by goobertron** [comment]
The second way works (just tested it via `aspect_navigation.feature`) and will be a lot easier to implement in the test suite, I think, as specifying XPath selectors looks a lot more complex, and adding IDs to elements would involve poking around in various other parts of the code.

If you let me know which of the following approaches you'd like me to follow, I'll go ahead.

1. Just change the text to e.g. "My aspects" for now;
2. Use the `click_link "li.all_aspects:nth-child(4) > a:nth-child(1)"` approach;
3. Add IDs to elements;
4. Use the `click_link I18n.t("javascripts.my_aspects")` approach.

I may have trouble finding the correct element selector names to use in option (2), and may have trouble finding the relevant elements in (3) (although I'm fine with adding IDs to elements). (1) and (4) I can certainly do.

**Comment by goobertron** [comment]
> besides adding some obscurity of what's happening to the code I guess.

On this point, I don't see any more real obscurity than using the text itself ("My aspects"). Everyone using the test suite is likely to know that Diaspora uses i18n, and how to interpret code in the form `I18n.t("string_name")`. Indeed it could be said sometimes to be less obscure, certainly more precise, than using the text itself, as for example "My aspects" appears in `javascripts.my_aspects` and `streams.aspects.title`!

**Comment by jhass** [comment]
I think we can try out 4 for a while, gotta keep things interesting, no? ;)

**Comment by goobertron** [comment]
Hur hur hur [rubs hands with glee].

OK, I'll make the changes relevant to the broken tests from the changes to capitalisation, then if you're happy they're working OK, I'll start changing the rest of the test suite in a separate PR.

**Comment by Flaburgan** [comment]
@goobertron definitely not the option 2, we are currently rewriting too many things in the UI to do that, the html is likely to change.
