### ISSUE TITLE
Notifications for non-contacts interactions

### ISSUE THREAD

**Issue by svbergerem** [diaspora/diaspora#5522]
We had several issues which described similar problems. I tested some cases and here are the results:

### users on the same pod
- users Alice, Bob and Carol are on the same pod
- Alice and Bob have a mutual relationship
- Carol shares with Bob
- all posts are public

#### notification
- Carol comments on Alice's post -> notification for Alice
- Carol likes Alice's post -> notification for Alice
- Carol comments on Bob's post, Alice also comments on that post -> notification for Carol
- Bob comments on Carol's post, Alice also comments on that post -> notification for Bob
- Bob comments on Alice's post, Carol also comments on that post -> notification for Bob

#### no notification
- Carol comments on Alice's post, Alice also comments on that post -> no notificaton for Carol
- Carol comments on Alice's post, Bob also comments on that post -> no notification for Carol

#### summary
It looks like there has to be some relationship between you and the author of the post you commented on to receive a AlsoCommented notification.

### users on different pods
- users Alice and Carol are on the same pod
- user Bob is on a different pod
- Alice and Bob have a mutual relationship
- all posts are public

#### notification
- Bob comments on Carol's post, Alice also comments on that post -> notification for Bob

#### no notification
- Bob likes Carol's post -> no notification for Carol
- Bob comments on Carol's post -> no notification for Carol
- Carol comments on Bob's post, Alice also comments on that post -> no notification for Carol

**Comment by Flaburgan** [comment]
Thanks for testing all these scenarii!

**Comment by goobertron** [comment]
I always wondered what was the plural of scenario! :P

Steffen, thanks from me also.

**Comment by Anime-Machina** [comment]
***bump*** following it now!

**Comment by svbergerem** [comment]
#4727 might be the cause of a few of the listed issues.

**Comment by AugierLe42e** [comment]
Hmm could be milestone 0.6, couldn't it?

**Comment by jaywink** [comment]
> Hmm could be milestone 0.6, couldn't it?

Only if someone fixes things before that :) Maybe we could look at these things in Paris..

**Comment by Globulle** [comment]
I think this is a very important issue since lot of people certainly miss comments on their posts and may be strongly disappointed by the lack of reactivity of people on D* (it was my case a few months ago). Concerning #1851, I think it is also a really powerful way to help people come back to D* when they are not frequent visitors. You generally react when you are personally mentioned.

Good idea to have a look at those in Paris! ;-)

**Comment by cmrd-senya** [comment]
Notifications are issued from [this place](https://github.com/diaspora/diaspora/blob/develop/app/workers/notify_local_users.rb#L16).

[Here](https://gist.github.com/cmrd-senya/f52447b068f96a121c3d#file-gistfile1-txt) is a call stack printed from Notification.notify function.

Then it is decided from the [Notification.notify function](https://github.com/diaspora/diaspora/blob/develop/app/models/notification.rb#L17), whether to send the notification or not.

From the call stack dump, that the notify_local_users function is being called from the post_to_subscribers function. And in the source code of [post_to_subscribers](https://github.com/diaspora/diaspora/blob/develop/lib/postzord/dispatcher.rb#L79) we see, that notify_local_users receives a list of users based on the subscribers list of the current user. That explains why non-contact users don't receive notifications: they never get to this list.

**Comment by cmrd-senya** [comment]
[Postzord::Dispatcher](https://github.com/diaspora/diaspora/blob/develop/lib/postzord/dispatcher.rb#L24) has an option called ```additional_subscribers```, that could be used to add non-subscribed users to ```@subscribers``` list. ATM it isn't filled with anything. Maybe we could use it and fill with non-contact users to send notifications to them?
