### ISSUE TITLE
Cannot select database driver

### ISSUE THREAD

**Issue by aykevl93** [diaspora/diaspora#5527]
Ok, I know this bug isn't very specific, but I have no experience with the Diaspora codebase and practically no experience with Ruby.

While trying to install Diaspora on Debian Jessie (using https://wiki.diasporafoundation.org/Installation/Debian/Wheezy?db=postgres&mode=development), I get this error:

```
$ DB=postgres  bundle exec rake db:create db:schema:load
Faraday::Builder is now Faraday::RackBuilder.
Couldn't create database for {"adapter"=>"mysql2", "host"=>"localhost", "port"=>3306, "username"=>"root", "password"=>"", "charset"=>"utf8
", "collation"=>"utf8_bin", "database"=>"diaspora_development"}, {:collation=>"utf8_bin"}
Couldn't create database for {"adapter"=>"mysql2", "host"=>"localhost", "port"=>3306, "username"=>"root", "password"=>"", "charset"=>"utf8
", "collation"=>"utf8_bin", "database"=>"diaspora_test"}, {:collation=>"utf8_bin"}
[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you c
an set I18n.enforce_available_locales = false to avoid this message.
rake aborted!
Mysql2::Error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
/home/diaspora/.rvm/gems/ruby-2.0.0-p598/gems/mysql2-0.3.17/lib/mysql2/client.rb:70:in `connect'
/home/diaspora/.rvm/gems/ruby-2.0.0-p598/gems/mysql2-0.3.17/lib/mysql2/client.rb:70:in `initialize'
/home/diaspora/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.8/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/home/diaspora/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.8/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_con
nection'
/home/diaspora/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:435:in 
`new_connection'
[...snip...]
```

It looks to me like it's trying to use the mysql driver while I had asked for the postgres driver.
Actually, I tried MariaDB first, but it also kept getting stuck at the mysql2 driver, so I tried postgres after that.
Following the guide on a clean Debian machine *should* (I think) reproduce the issue.

**Comment by desyncr** [comment]
May be you configured `postgres` for another environment. First be sure in which environment you're running and then the database configuration such that environment.

For a quick check just verify your configuration [here](https://github.com/diaspora/diaspora/blob/develop/config/database.yml.example#L21). It should look like:

    common: &common
      # Choose one of the following
      #<<: *mysql
      <<: *postgres

Hope that helps!

**Comment by aykevl93** [comment]
Oops, yes. I didn't read the configuration far enough...
Anyway, thank you! Now my test pod is up and running, just to discover the issue I wanted to fix has already been fixed in the latest version.

**Comment by desyncr** [comment]
There are still many things to look after though, take a look at the [newcomer issues](https://github.com/diaspora/diaspora/labels/newcomer)!
