### ISSUE TITLE
Unexpected behavior on conversations on mobile

### ISSUE THREAD

**Issue by desyncr** [diaspora/diaspora#5533]
When I create a new conversation but leave the recipient field empty the message seems to be processed ("sending..." is shown in the send button) and then the conversations page is loaded.

Steps to reproduce:

- Go to conversations
- Click "New conversation"
- Fill the new conversation form BUT leave "to" empty
- Click "send"

Shown behavior:

- Conversations page is shown
- Message is discarded

Expected behavior:

- Error shown in form (such as "Empty recipient")
- Do not discard form content

Tested on
- Chrome for Android
- joindiaspora.com

**Comment by jhass** [comment]
> Chrome for Android

So this is for the mobile site only?

**Comment by desyncr** [comment]
@jhass Yes. Updated the title to reflect that. On web it shows an error message when following the steps to reproduce: "Hey, you need to add the contact first!"
