### ISSUE TITLE
Twitter cross-posting/export fails to utilize any URL shortening services

### ISSUE THREAD

**Issue by dgets** [diaspora/diaspora#5534]
I believe that this is exceptionally important, for the obvious reason of tweet length restriction.  While posting from Twitter, or most mainline Twitter-enabled apps will handle URL shortening, cross-posting via Diaspora does not.  I've had to deselect sharing to twitter, and manually modify, and/or cut and paste, to a freshly opened Twitter window the same content _many_ times.  This, obviously, negates the logic behind sharing to twitter being available on Diaspora, at least a good portion of the time.

Independent URL and (in particular) youtube links should be shortened appropriately; it'd be a great feature if the character limit reflected this correctly when attempting to crosspost, as well.

**Comment by jaywink** [comment]
AFAIK all Twitter links are *always* 20 characters - and the logic for crossposting does take this into account. However, it's not perfect, and has some bugs.

At least for me, I can post almost 99,9% times successfully to Twitter - regardless of the post length or link amounts. D* will cut the post if it is too long.

I'm closing this for now as there is no concrete information on what should be improved. Please if you can give a concrete example on a piece of text that fails to post for example, we can reopen. Thanks!

**Comment by dgets** [comment]
Understood.  I was taking the character count at face value.  Thank you.
