### ISSUE TITLE
Customize bootstrap with variables

### ISSUE THREAD

**Issue by dimaursu** [diaspora/diaspora#5537]
To clean up the CSS, we need to use the bootstrap variables to customize the build. That will drastically reduce the overrides that are now use. I recommend doing this after switching to BS3
Here are the variables than can be used: 
https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss

**Comment by svbergerem** [comment]
We switched to BS3 and override the Bootstrap variables now. @dimaursu Is there anything left to do before we can close this issue?

**Comment by dimaursu** [comment]
I guess this is done :) That "new_styles" directory still itches me when I see it, but it has nothing to do with the issue at hand
