### ISSUE TITLE
MySQL + Diaspora/Sidekiq Running and silently stops federating

### ISSUE THREAD

**Issue by Anime-Machina** [diaspora/diaspora#5538]
There is an issue on diaspora* develop version, my pod is running develop at code head-p98cb1bbb and there are several errors appearing like below. I personally think it has to do some thing with the MySQL sockets. This just did not happened with one pod at the moment 3 or more pods are suffering from this including mine. Although it happened once on mine but yet on an other pod it happens once in 12 hours.

```Receiving public object from person:7
Receiving public object from person:821
Validation failed: Guid has already been taken, Target has already been taken
failed to save received object: ["Guid has already been taken", "Target has already been taken"]
Receiving public object from person:132
Validation failed: Guid has already been taken, Target has already been taken
failed to save received object: ["Guid has already been taken", "Target has already been taken"]
Receiving public object from person:718
Mysql2::Error: Duplicate entry 'd39588c077670132b35200259069449e' for key 'index_posts_on_guid': INSERT INTO `posts` (`author_id`, `created_at`, `diaspora_handle`, `guid`, `public`, `text`, `type`, `updated_at`) VALUES (5732, '2015-01-06 00:21:05', 'someuser@diasporapod.tld', 'd39588c077670132b35200259069449e', 1, 'Escena de Navidad, encerrada bajo el brillo y la transparencia de una bola de nieve.\r\n\r\n---\r\n#Fotografía, #photography, #Navidad, #Christmas, #mywork.', 'StatusMessage', '2015-01-06 01:11:13')```

**Comment by jhass** [comment]
That log simply shows an object being sent or processed a second time after it succeeded the first time already. I see no evidence for your issue claims in there. None at all.

**Comment by Anime-Machina** [comment]
Still did not happen again, after aome time attempting to get the old logs fixed no results. We need to wait rill it happens at sone one else or my pod.

Work around: restart diaspora*

**Comment by Anime-Machina** [comment]
Wrong topic, ignore that

**Comment by jaywink** [comment]
@Anime-Machina any objections to closing this from the issue tracker? It's not something that can be fixed as there is no knowledge what is wrong except one random occurrance. Unless you have experienced this again?

**Comment by Anime-Machina** [comment]
I have no objections to close this.

It probably has been a fluke or some thing crashed on Linux level. Under the tripple load it still did not repeated this so I qualify this as a fluke and should be closed. Thanks of reminding totally forgot about this.
