### ISSUE TITLE
Interface needed for normal phones

### ISSUE THREAD

**Issue by Jop-V** [diaspora/diaspora#5539]
Install the Opera Mini emulator:
https://dev.opera.com/articles/installing-opera-mini-on-your-computer/
And try to use Diaspora with it.
There needs to be a "basic" interface for the time being, until the third party client API has been finished.

**Comment by Flaburgan** [comment]
We already have a mobile version. What are you talking about?

**Comment by Jop-V** [comment]
It is for smartphones only. It is very hard to use on a normal phone. Try using Diaspora with the linked emulator to see what I mean.

**Comment by Flaburgan** [comment]
Oh, by "normal phones" you mean featured phones? Well I'm sorry but I don't think we're going to develop a third interface for something which is probably under 0.1% of our visitors. So if you can point some specific points which can be improved for the mobile version, I'm okay to develop it, but if this about a whole new interface, I don't think we will do it. But it's free software, so if you want to, you can ;)

**Comment by jaywink** [comment]
Yup sorry, I'm thinking the same way as @Flaburgan - we already have a desktop and mobile view. When an API comes, any kind of things can be built on top of that.

Thanks for the issue. If you have more specific ways to improve the mobile view, please let us know :)

Closing.
