### ISSUE TITLE
500 on request for `people/.../contacts` with `accept: application/json`

### ISSUE THREAD

**Issue by bwesterb** [diaspora/diaspora#5540]

**Comment by jhass** [comment]
![](http://cloud.aeshna.de/u/mrzyx/screenshots/screenshot_20150110_142650.png)

**Comment by bwesterb** [comment]
Thank you for adding the traceback.  Is there a way I can enable it without being the administrator of the pod?

**Comment by jhass** [comment]
No.

**Comment by jhass** [comment]
Btw. The proper response for this probably should be a 406, not making it work.

**Comment by sam09** [comment]
Can you describe how to replicate the bug?

**Comment by Flaburgan** [comment]
@sam09 I think the title says all, you need to create a get request like described.
