### ISSUE TITLE
New markdown parser seems to not work on mobile version

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/diaspora#5546]
#5526 Seems to have no effect on mobile version. Markdown parsing seems to be still randomly failing. This is related to #5216.

![jsxxfnt](https://cloud.githubusercontent.com/assets/3429231/5696974/9e40e992-99e3-11e4-9d5c-4cdf3e9810d8.png)

**Comment by jhass** [comment]
The mobile site uses server side parsing via Redcarpet.
