### ISSUE TITLE
Reset password field does not display an error message when it fails

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#5549]
Trying to reset my password, I tried to set a too short password. The page then reloads without displaying any explanation to the user. A text like "Reset password failed, new password too weak" should be displayed.

**Comment by MothOnMars** [comment]
I'm new to the project, so I'll take a look at this one.

**Comment by MothOnMars** [comment]
PR opened: https://github.com/diaspora/diaspora/pull/5580

**Comment by svbergerem** [comment]
Fixed by #5580.
