### ISSUE TITLE
"privacy aware" should be "privacy-aware"

### ISSUE THREAD

**Issue by maliktunga** [diaspora/diaspora#5555]
In the README.md

Proof:
http://www.w3.org/2005/Incubator/socialweb/XGR-socialweb-20101206/
https://cs.uwaterloo.ca/~uhengart/publications/gis10.pdf
http://research.microsoft.com/pubs/152497/01main.pdf
http://www.amazon.com/Privacy-Aware-Knowledge-Discovery-Applications-Techniques/dp/143980365X

Pull request: https://github.com/diaspora/diaspora/pull/5550

**Comment by Flaburgan** [comment]
You already open a pull request, no need for an issue.

**Comment by maliktunga** [comment]
@Flaburgan I didn't know that, thank you for enlightening me. I didn't get any response on my pull request, so I thought I had done something wrong.

**Comment by Flaburgan** [comment]
We're just quite busy right now, sorry about that ;)
