### ISSUE TITLE
implement group-like-feature with modified-user in given diaspora structure(as experimental opt-in)

### ISSUE THREAD

**Issue by viisauksena** [diaspora/diaspora#5558]
Explanation general:
Groups and User do mainly the same thing, people connect to them and people get and send content to them. And the outer world (public) don't care anyway. 
A really missed feature and beside chatting the most important feature for people/groups which are stucked in facebook. 

Idea:
make it possible to have special type of user which act as a group. 
So basicaly everybody connectet to this "group" is in this group.

This special_User/Group mainly makes a reshare, so all the connected people see the content. 
All the basics are there - there only have to be some kind of regulary check, or autoupdate when some new post/message for "group" arrives.

The group have than own Avatar, new users could already be autoaccepted or "moderated" - in general all the things a normal user can have - are there

comfortfeature: 
(the same as all userposts, but this time its somehow reverse, normaly the diaspora concept is push structured - means: i post something and diaspora pushes all the needed things to all the pods (likewise an email). Now we want that the "group" checks whether i still want the content be shared with the group.
- delete content (even when they copied on other pods)
- edit content (same as delete - but - you know, not so deleted)
- not a copy from user who posts a post and the group. (difficult while the normal streaming would be my posts and others posts (and so the group post) are mixed up. You could try to not send the reshare to the original sender - which solves this. 

Limitations of this idea:
- you have to make an extra account as user account
- you have to tick the experimental group_like_user button somewhere
- you extra have to logout and login when maintainance is needed 
  (add,drop users or single messages)
- diaspora have to react instantly on incoming posts for this user
- diaspora have to check regulary for deleted / modified posts.
- this concept goes crazy when aplied to public posts, so it better limited to aspect/shared socalled Limited posts

superextradelicous features are:
- some kind of special available group content (pages, data, pictures, pdf ...)
- some special accessible and editable pages to work colaboratively 
(maybe like crabgrass, maybe like wiki, maybe like etherpad)
- Access Control Lists .. but this is something lightyears away/different 

(sorry for beeing so plain texty and not cody ... but this how to describe best where i want to go after digging in code and many many docs und irc questions)

**Comment by viisauksena** [comment]
i am startingto write a workaround script which does not affect diaspora code itself,
it uses msql querys and Curl to obtain the defined idea above - as a shellscript
see https://github.com/viisauksena/diasp_group

**Comment by jaywink** [comment]
I'm sorry but after core developer discussion we're closing this in favour of #6278. An acceptable groups feature would have to be well designed and not built on top of some existing feature which is not intended for this usage, ie a user in this proposal.

@stefangrotz - you have posted a $5 bounty on this issue. As per Bountysource [policy](https://github.com/bountysource/frontend/wiki/Frequently-Asked-Questions#what-happens-if-an-issue-ive-backed-is-closed-without-resolution), this bounty can be transferred to the new issue, in this case #6278, or you can ask for a refund. I can ask Bountysource to transfer the amount for you if you want - if you would like a refund instead, please contact Bountysource directly.
