### ISSUE TITLE
Hide community spotlight setting if not enabled

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#5560]
The setting 'Show Community Spotlight in stream' on the `/user/edit` view is displayed whether or not the podmin has enabled Community Spotlight for users of that pod.

It should be displayed as a setting only if the pod has enabled Community Spotlight.

**Comment by Flaburgan** [comment]
It is not the only place it appears even if the Community Spotlight are not enabled. If you have an empty stream for example, the message will advice you to add contact and check the community spotlight.
