### ISSUE TITLE
Lock account

### ISSUE THREAD

**Issue by marienfressinaud** [diaspora/diaspora#5564]
In order to improve admin moderation (in addition of #5324), it could be great to add a "disable account" feature to block spamming/illegal accounts for a certain time. It could be a great compromise between letting users do all what they want and deleting their accounts once for all. Some ideas:

- Set a limit of time (so after x days/weeks/months, the account is available again)
- Give possibility of removing only specific rights (e.g. don't allow to post new comments, don't allow to post new posts)
- A message should appear to the user to explain why their account is disabled or blocked. This message might be edited by the admin.
- Consider to give the possibility to select users by list (e.g. from a list of reported users?). It can facilitate the task on biggest pods.

**Comment by Flaburgan** [comment]
That's a great idea! Our admin panel definitely needs some love...

**Comment by jhass** [comment]
I think the rights idea is overcomplicating this a lot and prone to bugs. Devise already provides a lock account feature that prevents sign in and that we just need to expose to the admin panel.

**Comment by marienfressinaud** [comment]
It was just an idea I found interesting but it's with no doubts complicated! That's fine if the rest is easier to implement.

**Comment by Flaburgan** [comment]
So I dug in that and found that we have a `locked_at` field in the `users` table.

`Update users set locked_at = '2015-01-28 12:19:00' where username = 'test';` locked my account, with a nice message when I try to log in, and then `Update users set locked_at = null where username = 'test';` allowed me to log in again.

So something like `user.lock_account!` and `user.unlock_account!` should work, we just need to expose that method in the admin panel, like did for the `close` method.

**Comment by aka001** [comment]
I have made an attempt to solve this bug. Please review the pr:
https://github.com/diaspora/diaspora/pull/5643
