### ISSUE TITLE
[JSON exporter] bad email formatting

### ISSUE THREAD

**Issue by marienfressinaud** [diaspora/diaspora#5567]
The mail received once data has been processed is bad formatted:

- Subject: "Your personal data is ready for download, %{username}" => %{username} should be replaced by my real name
- Content:
  - "Hello marienfr" => I would prefer my real name instead my id
  - "Your data has been processed and is ready for download by following [this link][/uploads/users/marienfrdiasporadata.json.gz]." => The link is a Markdown one and don't mention my pod (which is actually https://diaspora-fr.org). Moreover, I'm pretty sure the filename is wrong (i.e. missing underscores): it should be marienfr_diaspora_data.json.gz

Related to #5499

**Comment by gdpelican** [comment]
I'll fix this one up.
