### ISSUE TITLE
[Markdown] Bad parsing of <, > and & in code

### ISSUE THREAD

**Issue by marienfressinaud** [diaspora/diaspora#5569]
There is no possibility to type HTML code such as a basic markup like `<div>` in Markdown code (between \`). `<`, `>` and `&` are replaced by their HTML values `&lt;`, `&gt;` and `&amp;`.

Here is a screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/1436309/5789209/acf58a7e-9e61-11e4-9212-a6676e0eae6f.png)

There is no problem on mobile so it is probably link to the introduction of markdown-it ( #5526 ). See also #5466

**Comment by svbergerem** [comment]
Thank you for reporting that. That is a bug of the markdown sanitizer. I wonder why we didn't have that problem before with pagedown because the sanitizer I wrote works basically like the pagedown sanitizer. I'll see what they do to prevent that.
