### ISSUE TITLE
Irretrievable submitted text when there are problems posting comments

### ISSUE THREAD

**Issue by dgets** [diaspora/diaspora#5573]
I've run into this problem a few times, but when it struck me today, I decided it was time to submit an issue.  I'm guessing it's related to pod limitations, but when someone types a detailed comment, clicks the 'comment' button, and then is rewarded with the entire amount of text disappearing and the little top-bar drop-down saying that there was a problem posting your comment, please try again later, or whatever, that's not exactly an ideal method for dealing with things.  I mean, I've learned with some web applications to do all of my composition in a text editor and then post it after that's saved locally, just in case, but with a distributed social network with aspirations as high as Diaspora, there should, at least, be a way to retrieve the text that's been submitted.

Perhaps just don't hide the text before it's posted?  After a notification comes back from the server that the post was successful, that could trigger the code to hide the original text.  A duplication being on the screen for a couple of seconds is certainly well preferable to the complete loss of a potentially huge amount of custom composition and research.

**Comment by dgets** [comment]
Okay, so please allow me to humbly update this.

This has been an issue on **joindiaspora.com**.  I don't know if it's affecting any other pods, but it seems to be hitting _multiple different AJAX functions_.  For instance:

1.  Posting a comment just made it disappear into the ether, but upon reload it was there. 
2.  Same thing when making an actual post.  Post fails, but it appears if you reload the feed.
3.  Same thing for deleting a post.
4.  Hitting 'like' on somebody's entry isn't reflected by the change in text, either.

**Comment by goobertron** [comment]
This is a long-standing issue, particularly with joindiaspora.com, which has many performance issues due to overloading. See #3688.

**Comment by dgets** [comment]
Well I guess I'll close this in lieu of that.  No need to be overloading developers as well as servers.  ;)
