### ISSUE TITLE
Wrong information on the new (HTML) statistic page

### ISSUE THREAD

**Issue by marienfressinaud** [diaspora/diaspora#5589]
I can see two types of errors:

- Registrations are shown as opened while they are not
- Services are all "Not available" while they are!

For example, you can compare Diaspora-fr information:

- That's ok on the JSON page: https://diaspora-fr.org/statistics.json
- But not on the HTML page: https://diaspora-fr.org/statistics

Related to https://github.com/diaspora/diaspora/pull/5464

**Comment by jaywink** [comment]
Also ummmm active users *monthly* cannot be higher than active users *half a year* :P Something has changed there too.

**Comment by Flaburgan** [comment]
Yeah @jaywink and this is affecting statistics.json which should not have been changed...

**Comment by marienfressinaud** [comment]
True. Another thing (it may be a feature, I don't know): on the JSON page there is a "services" array AND, at the end of the line, services with a boolean information. I guess services array is excessive…

**Comment by Flaburgan** [comment]
@marienfressinaud the service with a boolean is the old version (0.4), the array the new one. We keep both in 0.5 to be retrocompatible, 0.6 will only have the array.

**Comment by AugierLe42e** [comment]
@Flaburgan : JSON has changed as it include a big refactor by @jhass...

**Comment by jaywink** [comment]
JSON errors fixed by #5590

**Comment by AugierLe42e** [comment]
If nobody solved it before, I'll try to fix this tonight. I have an idea where it can come from, but I'm at work now.

**Comment by Flaburgan** [comment]
I fixed the monthly / halfyear and @AugierLe42e the services but we're still having the issue about registration: they are closed on diaspora-fr but displayed as open.

**Comment by Flaburgan** [comment]
PR from @AugierLe42e is now merged, this can be closed.
