### ISSUE TITLE
SPV Ignore, Hide and Delete actions misplaced when the post is a reshare

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#5591]
https://github.com/diaspora/diaspora/pull/5547 added Ignore, Hide and Delete actions to the SPV.

In case of a reshare, the icons are placed on the original post div:

![](https://cloud.githubusercontent.com/assets/930064/5893097/36d2ee40-a4d8-11e4-8d24-9252e0832300.png)

This is confusing, because the action will not impact the original post but the reshare itself. The icons should be placed on the reshare div.

**Comment by Flaburgan** [comment]
@Faldrian I'll not have time to work on this in the coming days so feel free to fix it ;)

**Comment by Faldrian** [comment]
I fixed it. :)

**Comment by jaywink** [comment]
Fixed via #5601
