### ISSUE TITLE
Codeblocks not parsed correctly

### ISSUE THREAD

**Issue by cpt1gl0** [diaspora/diaspora#5592]
Newlines inside codeblocks are not handled correctly:

    ````
    line1
    line2
    ````

gives
    
    line1 line2

In addition it is not possible to use four spaces instead of four backticks: Four spaces have no effect at all.

**Comment by jhass** [comment]
The parser used in the current released supports no code fences. #5526 replaced it with one adhering to the commonmark spec, thus this will be fixed in the next release.
