### ISSUE TITLE
Error 500 in the user settings when the string submitted is too long

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#5593]
Step to reproduce:
 * Go to your settings
 * Click on the Profil tab
 * Modify the location field putting more than 255 chars in it.

**Comment by goobertron** [comment]
This bug excludes community members from Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch. ;)

**Comment by SansPseudoFix** [comment]
As a member of Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch's community, I feel discriminated!

**Comment by AugierLe42e** [comment]
@SansPseudoFix : You're even not from a celtic region ! xD

**Comment by Polynomdivison** [comment]
I entered 6234 chars.
In my Profle the location looks like the picture.
I counted the letters and the number of the characters 255.
There was no Error 500.
I'm using Firerfox 35.0.1.
Pod is pod.geraspora.de.
![bug_5593](https://cloud.githubusercontent.com/assets/10708466/5973912/2266db6c-a86e-11e4-89f4-30800cdfdad8.png)

**Comment by Polynomdivison** [comment]
No Error 500 by editing my Profile with Android Firefox (mobile View).

So issue is fixed?

**Comment by jhass** [comment]
@Flaburgan please get the corresponding log snippet if you can reproduce.

**Comment by Flaburgan** [comment]
Just fill the location field with many chars and you'll have a 500:

<pre>
Started PUT "/profile" for 2001:67c:1810:f0ff:a96f:8ed1:ba1a:f3e3 at 2015-01-31 19:05:24 +0100
Processing by ProfilesController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"CZPAEgnE=", "profile"=>{"first_name"=>"Fla", "last_name"=>"", "tag_string"=>"", "bio"
=>"[FILTERED]", "location"=>"Francerrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr", "gender"=>"♂", "date"=>{"day"=>"", "month"=
>"", "year"=>""}, "searchable"=>"true"}, "tags"=>",#french,#podmin,#diaspora,#mozilla,#grenoble,", "commit"=>"Mettre à jour le profil"}
PG::StringDataRightTruncation: ERROR:  value too long for type character varying(255)
: UPDATE "profiles" SET "location" = $1, "updated_at" = $2 WHERE "profiles"."id" = 1
Completed 500 Internal Server Error in 25ms

ActiveRecord::StatementInvalid (PG::StringDataRightTruncation: ERROR:  value too long for type character varying(255)
: UPDATE "profiles" SET "location" = $1, "updated_at" = $2 WHERE "profiles"."id" = 1):
  app/models/user.rb:364:in `update_profile'
  app/controllers/profiles_controller.rb:51:in `update'
  lib/rack/chrome_frame.rb:39:in `call'
  lib/unicorn_killer.rb:35:in `call'
</pre>

**Comment by Flaburgan** [comment]
Maybe it's only broken in develop.

**Comment by jaywink** [comment]
Yeah, regression then - and not just psql:

    ActiveRecord::StatementInvalid in ProfilesController#update
    Mysql2::Error: Data too long for column 'location' at row 1: UPDATE `profiles` SET `bio` = '', `first_name` = '', `gender` = '', `last_name` = '', `location` = 'hgyggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggyuftyftyftyftyfyftyftyftyftyfytftyfytftyfyyyyyyyyyyyyyyyyyyyyyyyyyyyftyftyftyfytfytftyyyyyyyyyyyyyyyyyyyyyyyfftyftyhgyggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggyuftyftyftyftyfyftyftyftyftyfytftyfytftyfyyyyyyyyyyyyyyyyyyyyyyyyyyyftyftyftyfytfytftyyyyyyyyyyyyyyyyyyyyyyyfftyftyhgyggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggyuftyftyftyftyfyftyftyftyftyfytftyfytftyfyyyyyyyyyyyyyyyyyyyyyyyyyyyftyftyftyfytfytftyyyyyyyyyyyyyyyyyyyyyyyfftyftyhgyggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggyuftyftyftyftyfyftyftyftyftyfytftyfytftyfyyyyyyyyyyyyyyyyyyyyyyyyyyyftyftyftyfytfytftyyyyyyyyyyyyyyyyyyyyyyyfftyftyhgyggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggyuftyftyftyftyfyftyftyftyftyfytftyfytftyfyyyyyyyyyyyyyyyyyyyyyyyyyyyftyftyftyfytfytftyyyyyyyyyyyyyyyyyyyyyyyfftyftyhgyggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggyuftyftyftyftyfyftyftyftyftyfytftyfytftyfyyyyyyyyyyyyyyyyyyyyyyyyyyyftyftyftyfytfytftyyyyyyyyyyyyyyyyyyyyyyyfftyftyhgyggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggyuftyftyftyftyfyftyftyftyftyfytftyfytftyfyyyyyyyyyyyyyyyyyyyyyyyyyyyftyftyftyfytfytftyyyyyyyyyyyyyyyyyyyyyyyfftyftyhgyggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggyuftyftyftyftyfyftyftyftyftyfytftyfytftyfyyyyyyyyyyyyyyyyyyyyyyyyyyyftyftyftyfytfytftyyyyyyyyyyyyyyyyyyyyyyyfftyftyhgyggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggyuftyftyftyftyfyftyftyftyftyfytftyfytftyfyyyyyyyyyyyyyyyyyyyyyyyyyyyftyftyftyfytfytftyyyyyyyyyyyyyyyyyyyyyyyfftyftyhgyggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggyuftyftyftyftyfyftyftyftyftyfytftyfytftyfyyyyyyyyyyyyyyyyyyyyyyyyyyyftyftyftyfytfytftyyyyyyyyyyyyyyyyyyyyyyyfftyftyhgyggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggyuftyftyftyftyfyftyftyftyftyfytftyfytftyfyyyyyyyyyyyyyyyyyyyyyyyyyyyftyftyftyfytfytftyyyyyyyyyyyyyyyyyyyyyyyfftyfty', `updated_at` = '2015-02-01 10:11:23' WHERE `profiles`.`id` = 1
    Extracted source (around line #364):
    

    params.stringify_keys!
    params.slice!(*(Profile.column_names+['tag_string', 'date']))
    if self.profile.update_attributes(params)
    deliver_profile_update
    true
    else

    Rails.root: /home/jaywink/workspace/diaspora/diaspora
    Application Trace | Framework Trace | Full Trace

    app/models/user.rb:364:in `update_profile'
    app/controllers/profiles_controller.rb:51:in `update'
    config/initializers/silence_assets.rb:9:in `call_with_quiet_assets'
    lib/rack/chrome_frame.rb:39:in `call'
    lib/unicorn_killer.rb:35:in `call'

**Comment by Flaburgan** [comment]
Closed by https://github.com/diaspora/diaspora/pull/5614
