### ISSUE TITLE
Design of "More" button on mobile changed

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#5598]
I think this was break by https://github.com/diaspora/diaspora/pull/5532 (at least I saw the design changing just after I merged that in diaspora-fr) but it's also maybe related to https://github.com/diaspora/diaspora/pull/5400

Anyway, in 0.4.1.2 the button looked like this:
![capture du 2015-01-27 11 02 26](https://cloud.githubusercontent.com/assets/930064/5916768/09f06004-a615-11e4-8044-ec276b9ce3be.png)

and now it looks like that (with a weird box-shadow inside):
![capture du 2015-01-27 09 53 40](https://cloud.githubusercontent.com/assets/930064/5916773/139a97a0-a615-11e4-86ee-5ead3c31e85f.png)

@dimaursu wanna have a look to check if your refactor broke that?

**Comment by dimaursu** [comment]
Ok, I'll have a look this evening. Although the messages inside the box are wildly different, we are not looking at the same stuff. I think this is hardly a styling issue.

**Comment by dimaursu** [comment]
I might be the culprit, in a unintended way. The rule was obsolete, most browsers ignoring it. Since  I used the standard box-shadow, it became "usable" again.
https://github.com/diaspora/diaspora/commit/3e1b944121dff42b4780319e704fa7ef7a26d18e#diff-38434ef4ee8913974d8688509e15dadbR196

**Comment by Flaburgan** [comment]
Yeah as said the text changed between the stable release and the current develop version. It would be nice to see a different style between the "Show more" (when there is more than 15 posts to display) and the "There are no posts yet" (which should be "No more posts to display" imo), because one is simply an indication when the other one is a button.

**Comment by Faldrian** [comment]
I know that my PR introduced a new message / behaviour when you reach the end of the stream... maybe check that also. :)

**Comment by jaywink** [comment]
I thought the change was intended and kinda like the "new version" :D
