### ISSUE TITLE
Webfinger fails

### ISSUE THREAD

**Issue by dadall** [diaspora/diaspora#5600]
Hi,

I'running a new pod using the develop branch of Diaspora and I'm facing these errors :

> RuntimeError: there was an error getting the xrd from account mnbain@joindiaspora.com: Failed to fetch http://joindiaspora.com/.well-known/host-meta: 0

More than 90% of the my sidekiqs tasks are failing and I can't find out why. Most of them are similar to that one...

Server configuration : 
 - Debian Wheezy 7.8 64bits
 - Curl updated to 7.33
 - Ruby 2.1.5

Pod configuration : 
 - Url : diaspote.org
 - Version : head-paaadf292
 - DB : MySQL
 - Web : Apache2

**Comment by jhass** [comment]
This is likely a setup issue.

Please provide the output of the following:

```
$ bin/rails c production
>> Webfinger.new("mnbain@joindiaspora.com").fetch
```

**Comment by dadall** [comment]
Here we are : 

> 2.1.5 :001 > Webfinger.new("mnbain@joindiaspora.com").fetch
webfingering mnbain@joindiaspora.com, it is not known or needs updating
Getting: https://joindiaspora.com/.well-known/host-meta for mnbain@joindiaspora.com
ETHON: Libcurl initialized
ETHON: performed EASY effective_url=https://joindiaspora.com/.well-known/host-meta response_code=0 return_code=ssl_cacert total_time=0.19550999999999996
Failed to fetch: https://joindiaspora.com/.well-known/host-meta for mnbain@joindiaspora.com; Failed to fetch https://joindiaspora.com/.well-known/host-meta: 0
Getting: http://joindiaspora.com/.well-known/host-meta for mnbain@joindiaspora.com
ETHON: performed EASY effective_url=http://joindiaspora.com/.well-known/host-meta response_code=301 return_code=ok total_time=0.239858
ETHON: performed EASY effective_url=https://joindiaspora.com/.well-known/host-meta response_code=0 return_code=ssl_cacert total_time=0.177068
Failed to fetch: http://joindiaspora.com/.well-known/host-meta for mnbain@joindiaspora.com; Failed to fetch http://joindiaspora.com/.well-known/host-meta: 0
RuntimeError: there was an error getting the xrd from account mnbain@joindiaspora.com: Failed to fetch http://joindiaspora.com/.well-known/host-meta: 0
        from /home/diaspora/diaspora/lib/webfinger.rb:75:in `rescue in host_meta_xrd'
        from /home/diaspora/diaspora/lib/webfinger.rb:68:in `host_meta_xrd'
        from /home/diaspora/diaspora/lib/webfinger.rb:94:in `webfinger_profile_url'
        from /home/diaspora/diaspora/lib/webfinger.rb:100:in `webfinger_profile_xrd'
        from /home/diaspora/diaspora/lib/webfinger.rb:110:in `make_person_from_webfinger'
        from /home/diaspora/diaspora/lib/webfinger.rb:60:in `create_or_update_person_from_webfinger_profile!'
        from /home/diaspora/diaspora/lib/webfinger.rb:18:in `fetch'
        from (irb):1
        from /home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/railties-4.1.8/lib/rails/commands/console.rb:90:in `start'
        from /home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/railties-4.1.8/lib/rails/commands/console.rb:9:in `start'
        from /home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:69:in `console'
        from /home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from /home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/railties-4.1.8/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:8:in `require'
        from bin/rails:8:in `<main>'

And I have this when the server is running : 

> 08:27:59 web.1     | X-Accel-Mapping header missing
> 08:27:59 web.1     | X-Accel-Mapping header missing
> 08:28:04 web.1     | X-Accel-Mapping header missing
> 08:28:05 web.1     | X-Accel-Mapping header missing
> 08:28:05 web.1     | X-Accel-Mapping header missing
> 08:28:05 web.1     | X-Accel-Mapping header missing
> 08:28:05 web.1     | X-Accel-Mapping header missing
> 08:28:05 web.1     | X-Accel-Mapping header missing
>

**Comment by dadall** [comment]
Missconfiguration, sorry.

**Comment by gabsoftware** [comment]
What have you corrected in your configuration?

**Comment by pravi** [comment]
@dadall how did you fix it? I have the same error with diasp.in
