### ISSUE TITLE
non existent avatar picture mess up streamcontacts in top right corner

### ISSUE THREAD

**Issue by viisauksena** [diaspora/diaspora#5604]
when some of the mentioned contacts in the stream contact field on the top right corner dont have a avatar-picture the pod-email is shown, 
while this is very long it mess up this list

solution:
![diaspora-issue-stream-avatar](https://cloud.githubusercontent.com/assets/10057308/5951463/478858d2-a768-11e4-917f-9280fadcd2bd.png)
there should be something like a default - none,avatar

**Comment by jhass** [comment]
We had that once, it's broken in some places.

**Comment by jaywink** [comment]
Fixed via #5638
