### ISSUE TITLE
adress pod.tld/public/user should somehow not linkt to user/guid

### ISSUE THREAD

**Issue by viisauksena** [diaspora/diaspora#5605]
while its easy and nicely possible to have all the public posts like a blog under your user adress it should be accessible under 
pod.tld/public/username (which actually is a redirect) more than 
pod.tld/user/some_long_unrecognisable_morelong_guid

in my case 
public/jens_viisauksena   vs   people/592aee6030af01326b724dc49147e0ae
its cosmetic, but maybe easily done .. 

![diaspora-feature-bloglike](https://cloud.githubusercontent.com/assets/10057308/5951560/7048e65a-a769-11e4-97c8-d11c63798ce4.png)

Than a user could share his pod/public/username as his blogadress, which is easily memorizeable
in my case 

and maybe maybe maybe it would be nice to have it directly under the pod.tld 
(but that means some names are restricted as their are actually used for something else)

**Comment by jhass** [comment]
`/u/username` already works and does not redirect.

**Comment by viisauksena** [comment]
ah ok, shouldnt the subfolder /public do the same? i guess, 
however, nice

**Comment by jhass** [comment]
Any reasoning why you want to duplicate the /u/ route?

**Comment by viisauksena** [comment]
just that it seems intuitivly right that i can use bla.pod.tld/public/user_name and not get a mess of uid ...
realy more than this nice shortcut ...
its just a feeling - slight discomfort.
also a relink from public/name to u/name would be nice, but not to user/somesuperstrangenumber 
(but maybe this redirect is used to identify a foreign UID by its name, thats what you kknow better)
