### ISSUE TITLE
Markdown stripped during federation develop -> stable

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#5613]
I've noticed that this post made on diaspora-fr.org doesn't display properly (the Markdown has been stripped) on some pods: https://diaspora-fr.org/posts/550745708ba901325eb15a3f8ee1c128

diaspora-fr.org is currently running code `head-p9e169af4`.

It looks as though it is mainly a problem between that particular version of `develop` and pods running older versions.

The following pods (running `stable`) don't display the formatting:

- [pod-orkz.net](https://pod.orkz.net/posts/550745708ba901325eb15a3f8ee1c128)
- [framasphere](https://framasphere.org/posts/550745708ba901325eb15a3f8ee1c128)
- [diasp.org](https://diasp.org/posts/550745708ba901325eb15a3f8ee1c128)
- [joindiaspora.com](https://joindiaspora.com/posts/550745708ba901325eb15a3f8ee1c128)
- [nerdpol.ch](https://nerdpol.ch/posts/550745708ba901325eb15a3f8ee1c128)
- [joindiaspora.co.uk](https://joindiaspora.co.uk/posts/550745708ba901325eb15a3f8ee1c128)
- and so on.

The following pods (running `develop`) display the post and comments fine:

- [iliketoast](https://iliketoast.net/posts/550745708ba901325eb15a3f8ee1c128)
- [sechat.org](https://sechat.org/posts/550745708ba901325eb15a3f8ee1c128)
- [pod.jpope.org](https://pod.jpope.org/posts/550745708ba901325eb15a3f8ee1c128)

The following pods (running `develop`) display the post properly, but the comments and interaction icons are listed *underneath* the post, rather than on the right:

- [diasp.net](https://diasp.net/posts/550745708ba901325eb15a3f8ee1c128)
- [diapod.net](https://diapod.net/posts/550745708ba901325eb15a3f8ee1c128)
- [diaspora.com.ar](https://diaspora.com.ar/posts/550745708ba901325eb15a3f8ee1c128)

The formatting has gone on this pod, which runs `develop`:

- [spyurk.am](https://spyurk.am/posts/550745708ba901325eb15a3f8ee1c128)

Please note: these are the only pods I have checked. Others may show a different pattern.

**Comment by goobertron** [comment]
The same has also happened with https://diaspora-fr.org/posts/0b162b908c4d01325eab5a3f8ee1c128, so it's clearly a problem with more than an individual post.

**Comment by jhass** [comment]
I guess Fla simply is already used to the new, more robust parser. If we compare the text attribute in the [json](https://diaspora-fr.org/posts/550745708ba901325eb15a3f8ee1c128.json), we can see that it is [identical](https://pod.orkz.net/posts/550745708ba901325eb15a3f8ee1c128.json).

With some added newlines for readability:
diaspora-fr.org:
```
So after the first day of the #fosdem, I can say that:\r\n
* We talked with maybe 50 persons\r\n* A lot of people are interested by the project\r\n
* Many of them discovered that the project was not dead\r\n
* The most asked feature is the pod migration\r\n
* The #diaspora contributors are awesome\r\n
* 12 beers during the friday event is maybe too many when you have to speak the whole day after that\r\n
\r\n
Now it's time to eat!\r\n\r\n#fosdem2015 #beer #community #report
```
pod.orkz.net
```
So after the first day of the #fosdem, I can say that:\r\n
* We talked with maybe 50 persons\r\n
* A lot of people are interested by the project\r\n
* Many of them discovered that the project was not dead\r\n
* The most asked feature is the pod migration\r\n
* The #diaspora contributors are awesome\r\n* 12 beers during the friday event is maybe too many when you have to speak the whole day after that\r\n
\r\n
Now it's time to eat!\r\n\r\n#fosdem2015 #beer #community #report
```

**Comment by goobertron** [comment]
From what you say it sounds as though this is an expected change rather than a bug, and shouldn't be an issue from the next release, when most pods will upgrade. If so, shall I close this issue?

**Comment by jhass** [comment]
I think there's no bug yes.

What I've shown is that there's certainly no "Markdown stripped during federation develop -> stable" ;)

**Comment by Flaburgan** [comment]
Yeah I didn't put an empty line between the first sentence and the list, just remembered that this breaks the list display with the old parser, my bad.

**Comment by Flaburgan** [comment]
>the comments and interaction icons are listed underneath the post, rather than on the right:

Can you provide a screenshot of that?

**Comment by jhass** [comment]
Oh, and spyurk.am is not really running develop I guess, the commit it runs on is https://github.com/diaspora/diaspora/commit/15537e17c55a092ba4859557029a6282ca1af79d

**Comment by goobertron** [comment]
> What I've shown is that there's certainly no "Markdown stripped during federation develop -> stable"

Sure - it was the best title I could come up with in a few words! Thanks for checking it out.

> Can you provide a screenshot of that?

I was going to say 'click on one of the links', but on checking it appears to be browser-dependent, so don't worry about it.
