### ISSUE TITLE
Update AUTHORS file

### ISSUE THREAD

**Issue by marienfressinaud** [diaspora/diaspora#5620]
[AUTHORS file](https://github.com/diaspora/diaspora/blob/develop/AUTHORS) has been created 4 years ago and has never been updated since. It's not critical but there's a lot more people to thanks than the 4 initial developers! It could be nice to add some names or, at least, add a link to the [Github contributor page](https://github.com/diaspora/diaspora/graphs/contributors).

**Comment by phreaknerd** [comment]
I suggest to create an contributers.txt. Similiar to mediawiki.

**Comment by jhass** [comment]
Maybe we can just place a notice that directs to https://github.com/diaspora/diaspora/graphs/contributors ?

**Comment by phreaknerd** [comment]
Or place a humans.txt in root? Like https://github.com/humans.txt 
I thing the list should be in the repo as a "physical" credit for all devs/translators/testers...

**Comment by jhass** [comment]
We demanded contributors to do the changelog changes themselves for some time. That lead to an incredible amount of conflicts and delays in PRs, so if we can have something automatic, I'd prefer that highly, since we do have many short-lived contributors.

**Comment by phreaknerd** [comment]
Ack.
