### ISSUE TITLE
Disable sending Mails to User if already deleted

### ISSUE THREAD

**Issue by sammy8806** [diaspora/diaspora#5625]
Actually if a User deactivated his Account and somebody tries to send him a message an mail is sent to f.e. ```deletedaccount_30@example.org```.
This generates junk in the mailqueue.

**Comment by jhass** [comment]
Just something the AccountDeleter needs to do, plus a migration that does it for all already deleted users would be nice.

**Comment by jhass** [comment]
@sammy8806 can you check your DB whether disable_email is set to true for said user?

**Comment by giniouxe** [comment]
Is this still pending ?

**Comment by jhass** [comment]
See #5640

**Comment by giniouxe** [comment]
OK, thanks.
