### ISSUE TITLE
automatically refresh site after changing membership

### ISSUE THREAD

**Issue by sedrubal** [diaspora/diaspora#5628]
Hi,

It would be nice, if the site automatically reloads after changing the membership with somebody.

**Comment by jhass** [comment]
Which page are you talking about exactly?

**Comment by sedrubal** [comment]
Oh sorry.

I mean the user's page: `/people/<user hash/id>`

**Comment by jhass** [comment]
I believe your feature is already implemented in the current development head, if I misunderstood you and it's still not there after the next release (and after your pod updated to it), please reopen this issue.

**Comment by sedrubal** [comment]
:+1:
