### ISSUE TITLE
membership dropdown sometimes broken

### ISSUE THREAD

**Issue by sedrubal** [diaspora/diaspora#5630]
![snapshot](https://cloud.githubusercontent.com/assets/5571650/6088770/615d88e2-ae5a-11e4-9491-89a826bca22c.png)

**Comment by jhass** [comment]
Please try uploading the screenshot again, wait till it no longer says "Uploading" before you submit the issue/comment.

**Comment by sedrubal** [comment]
aah now it works ;)

**Comment by jhass** [comment]
That bug should be fixed in develop, although we have #5615 now.
