### ISSUE TITLE
Problem with contacts

### ISSUE THREAD

**Issue by rebeka-catalina** [diaspora/diaspora#5633]
I have got problems with the contact list. Already long time ago I have seen that several contacts in my list are listed more times. I don't mean same person with 2 or 3 accounts, I mean the same account is listed up to 3 and 4 times in my list. 
But yesterday I realised that other accounts aren't listet at all, but I know that it must be listed.
I know for sure, that the person still is sharing with me and I am sharing with her. I realised it now, because I moved to a smaller pod and wanted to start sharing with all the old contacts again and scrolled through my contactlist.
I just could solve the problem, that I wrote her a private message, because there the form putted her name from the contactlist as I started typing her name. Actually I know about this account, which does not appear in the list, for sure, but perhaps there are some more.

**Comment by Flaburgan** [comment]
Can you tell us which server you are registered on?

**Comment by rebeka-catalina** [comment]
Oh sorry, I forgot it :) Sure, it's diasp.de

**Comment by jhass** [comment]
Until somebody finds a way to reproduce, I'm not sure what we can do about this.

**Comment by rebeka-catalina** [comment]
Ok, just to clarify : Did you understand the problem as I described above ? My english is not the very best, I know and I'm sorry for it.
Or if you understood the problem : How can I give you more informations ?

**Comment by jhass** [comment]
Yes I think so and I doubt you can. We need a way to reproduce it with fresh accounts, so we can inspect the state in a local development installation.

**Comment by goobertron** [comment]
> But yesterday I realised that other accounts aren't listet at all, but I know that it must be listed.
 I know for sure, that the person still is sharing with me and I am sharing with her. 

To confirm this, you could go to the profile page for that person (in diasp.de) and check that they are allocated to one or more aspect in the aspects dropdown. (You can check whether they are sharing with you by the colour of the bar under their main profile picture: if green, they are sharing with you; if grey, they aren't. This doesn't of course affect whether they will appear in your list of contacts.)

**Comment by rebeka-catalina** [comment]
Some minutes ago I gave it a try with cliaspora.
I didn't think on it yesterday when I tried to find her in my contactlist.
`cliaspora list contacts | grep name` gave me back her ID, name and handle.
Perhaps not a Pod/Diaspora problem ?

**Comment by rebeka-catalina** [comment]
@goob : The problem with this is : When I send a search-query with her name she is not listed. Maybe she hasn't acitvated the search-option in her profile. In my contactlist she wasn't listed and that time I just remembered her name, but not her whole handle (name@somepod.org). 
Now as I tried it with cliaspora and got the information I could go to her profile and yes I can confirm, that we are still sharing with each other and that I put her into 2 aspects :)

**Comment by rebeka-catalina** [comment]
Others also confirmed the problem. I've posted the problem publicly and one person answered that he has also seen more than once listed contacts - I asked him for the pod, because he also moved yesterday to another pod and he said he has had the problem on the old pod, but he didn't answer yet. 
And just now I got an answer from another person, who's registered on wk3.org and she's got both problems like me. So she sees some contacts listed more than only one time and she also says, that there are some contacts she's sharing with, but not listed in contact list.

**Comment by goob** [comment]
@rebeka-catalina | @goobertron

**Comment by rebeka-catalina** [comment]
Sorry :-)

**Comment by svbergerem** [comment]
@rebeka-catalina With v0.5.0.0 the contacts page has been refactored. Are you still able to reproduce this bug?

**Comment by rebeka-catalina** [comment]
@svbergerem Just yesterday I've been thinking about it :D I'll check it an give you feedback the next days :)

**Comment by svbergerem** [comment]
@rebeka-catalina Ping.

**Comment by rebeka-catalina** [comment]
pong :
Oh, I'm sorry, dear. Yes, the problem was solved after the big update - I thought I already answered in here ... so thanks for the ping :-)
