### ISSUE TITLE
photo federation - develop

### ISSUE THREAD

**Issue by rivendale2010** [diaspora/diaspora#5636]
running develop

when i post an uploaded photo to public, and the photo appears for my person under /photos for users logged in to the remote pod -- the corresponding post is NOT ever entered into the stream on the remote pod     

on my local pod the post appears in the /stream and the photo is under my /photos as expected

**Comment by jaywink** [comment]
I'm not sure we can track single federation issues via the issue tracker. Especially as this could be very related to the remote pod sidekiq health.. :/

**Comment by rivendale2010** [comment]
it was happening with all remote pods. the photo would be there but the post not, there was one exception that i'm aware of which was pod.geraspora.de, so thought it might have been an issue with compatibility between new and old versions             

but it has since resolved itself :) not sure why. i did pull new updates and make some other config changes on my end, none of which i see a connection to, but something did it! :) i'll close this now, thanks!
