### ISSUE TITLE
[Notifications] Some people are not receiving notifications....?

### ISSUE THREAD

**Issue by Anime-Machina** [diaspora/diaspora#5645]
Had a ping today from some one on my pod that he or she is not receiving any notifications. It was a private post so I personally will not post his name unless he volunteers for it. Also I am not suffering from it my self so there must be some thing cache related.

Although facts on a row:

- I still get notifications by email,
- Last notification was about 5 hours ago, (I did not posted/reshared today)
- Server is running propperly and gives out no errors or what so ever in the logs,

So my question is:

- Is this contacts related?
- Is this a new feature? (Bug)
- What do you guys need?

Also here is a copy of his/her post:
Any idea what’s up with notifications not showing up? I’ve stopped getting them for when people like or comment on my posts or other posts I’ve commented on.

**Comment by goobertron** [comment]
Linked to #5522.

**Comment by jhass** [comment]
I think this is actually not only linked, but a duplicate. Our notification system is another thing that needs a redesign in the mid-term. As it is currently quite a bit weaved into the federation code, hopefully a nicer solution will fall at hand once that part is better decoupled from the application. For now, I don't think it makes much sense to have too many issues open about it.
