### ISSUE TITLE
The privacy page button has weird text

### ISSUE THREAD

**Issue by sam09** [diaspora/diaspora#5662]
Clicking on the profile page and then going to privacy settings, one can view the button with weird text.
![screenshot from 2015-02-07 02 52 50](https://cloud.githubusercontent.com/assets/6648290/6186402/e41b5964-b39e-11e4-997c-a9a064106e95.png)

The button text should be something more clear.

**Comment by Flaburgan** [comment]
Wow, right. This is the privacy settings page though, can you edit the title of your issue?

**Comment by sam09** [comment]
Sorry.Fixed it.

**Comment by Flaburgan** [comment]
This is because of a missing translation `translation missing: en.users.privacy_settings.change`

**Comment by svbergerem** [comment]
`users.edit.change` exists so we could just use that.

**Comment by giniouxe** [comment]
Just submitted a PR.
