### ISSUE TITLE
Image upload

### ISSUE THREAD

**Issue by awirstam** [diaspora/diaspora#5668]
cant upload images to my diaspora server.
I run it locally on one on my computers.
 get this message: A problem occurred while uploading file login.png
 the image is still uploaded to the folder on my server even though im uploading from another computer.

**Comment by jhass** [comment]
This is a setup issue. On IRC the following error message was provided:
> Incompatible library version: identify requires version 10.0.0 or later, but libfontconfig.1.dylib provides version 5.0.0

**Comment by awirstam** [comment]
So how do i fix it?
