### ISSUE TITLE
Refactor registrations

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/diaspora#5670]
Currently, the registration form block is written in [new.html.erb](https://github.com/diaspora/diaspora/blob/develop/app/views/registrations/new.html.erb#L22) and repeated in [new.mobile.haml](https://github.com/diaspora/diaspora/blob/develop/app/views/registrations/new.mobile.haml#L17).

 * [x] The form should be separated in _new.html.haml to let it be included in other pages (e.g splash page)
 * [x] [new.html.erb](https://github.com/diaspora/diaspora/blob/develop/app/views/registrations/new.html.erb#L22) should be rewritten in HAML.

**Comment by svbergerem** [comment]
#5391 fixes the second point.

**Comment by AugierLe42e** [comment]
@svbergerem right ! À propos, what is [resource and resource_name](https://github.com/diaspora/diaspora/blob/develop/app/views/registrations/new.mobile.haml#L17) about ?

**Comment by jhass** [comment]
Devise supports using more than one model for authentication, so you could for example have `User` and `Admin` as completely distinct stuff, see https://github.com/plataformatec/devise#configuring-multiple-models

**Comment by giniouxe** [comment]
I'd like to work on this one when https://github.com/diaspora/diaspora/pull/5391 will be merged, if it's OK.

**Comment by svbergerem** [comment]
@giniouxe Sure. :)

**Comment by giniouxe** [comment]
Hi,
Just to be precise, it's about creating a partial view for the desktop version of the form, or should I create one for the mobile version too ?
Thanks!

**Comment by svbergerem** [comment]
@giniouxe `_new.html.haml` would be only for the desktop version and I think that is what @AugierLe42e had in mind when opening this issue.

**Comment by AugierLe42e** [comment]
@svbergerem : Yes, it would let it to be included in another page e.g landing page like on diaspote.org :

![](https://cloud.githubusercontent.com/assets/3429231/6315310/b9d72712-b9fe-11e4-9b1d-25179bbd9234.png)

**Comment by giniouxe** [comment]
Hi,

Sorry it taked so long, but finally a submitted a PR : https://github.com/diaspora/diaspora/pull/5764
