### ISSUE TITLE
Notifications with the same date but a different year grouped together on the Notifications page

### ISSUE THREAD

**Issue by Makailija** [diaspora/diaspora#5673]
I have two notifications with the same date, February 11th, but a different year, 2015 and 2014, grouped together on the Notifications page. I don't believe this is intended behavior, because it does not make sense to me why they should be grouped. Can someone confirm this behavior? Here is a screenshot:

![notifications3](https://cloud.githubusercontent.com/assets/2229403/6207638/bf6a7b6e-b5af-11e4-923b-8a4b2e16aa3f.png)

#5361 is kinda related.

**Comment by goobertron** [comment]
Hmm, that's odd. And definitely not desired behaviour.

Have checked against two of my accounts: my main account (on a pod running 0.4.1.2) doesn't have this problem; my account on a pod running develop unfortunately doesn't have frequent enough notifications for there to be any two notifications on the same date from different years. We'll need someone else on a pod running develop to check that.

**Comment by svbergerem** [comment]
I don't know much about ruby but [this](https://github.com/diaspora/diaspora/blob/develop/app/controllers/notifications_controller.rb#L47) looks to me like we are only comparing month and day. This would have been an issue for quite some time. @goobertron The code looks like the two notifications have to be on the same page. Only in that case, and if they were created on the same day but in a different year, this issue could occur. I guess on your main account those notifications weren't on the same page.

**Comment by goobertron** [comment]
Hmm, interesting. That's plausible. If you're right, it would be a pretty rare use case (hardly any notifications during the year but two falling on the same date one year apart), but still a loophole worth fixing!

You're right, it's several dozen pages back to a year ago on my main account. @Makailija, can you confirm whether that notification from a year ago would have appeared on the same page even if it had been shown in its correct place?

**Comment by goobertron** [comment]
Fixed by #5676 so can be closed.

**Comment by Makailija** [comment]
@goobertron  Yes, the notification would have been on the same page, as you supposed.

Thanks for the great work, guys, you're awesome!
