### ISSUE TITLE
MessageRenderer#escape refactor

### ISSUE THREAD

**Issue by svbergerem** [diaspora/diaspora#5678]
In [message_renderer.rb](https://github.com/diaspora/diaspora/blob/develop/lib/diaspora/message_renderer.rb#L43) we have a TODO
> Special case Hex entities since escape_once
> doesn't catch them.
> TODO: Watch for https://github.com/rails/rails/pull/9102
> on whether this can be removed

That PR has been merged.

**Comment by jhass** [comment]
Seems to be in a 4.2 release, not sure about 4.1 though?

**Comment by svbergerem** [comment]
@jhass https://github.com/rails/rails/pull/9102#issuecomment-48091832

**Comment by jhass** [comment]
Yes, merged into the respective branch. Doesn't mean it's released.

**Comment by cmrd-senya** [comment]
It is in the Rails 4.2.5.2 version, the one we already use.
