### ISSUE TITLE
Allow additional profile fields (previously private profile) to be set public

### ISSUE THREAD

**Issue by svbergerem** [diaspora/diaspora#5684]
@jaywink tried to implement this in #4596 but closed the PR. I wasn't able to find a similar open issue.

**Comment by cmrd-senya** [comment]
In original PR there was mentioned a toggle slider as a way to switch beetwen private and public modes. Is there any examples of the toggle slider used in Diaspora? Is [this](http://www.bootstrap-switch.org/) is what we need?

**Comment by svbergerem** [comment]
Bootstrap-switch seems legit. There is even a [gem](https://rubygems.org/gems/bootstrap-switch-rails) which you can add to our Gemfile.

**Comment by jhass** [comment]
We decided to make this a local only feature for now, since it's a lot easier and the common usecase will be referring somebody to your `/u/username` anyway.
