### ISSUE TITLE
<span ... > visible in html page in privacy page

### ISSUE THREAD

**Issue by aka001** [diaspora/diaspora#5687]
Instead of "Edit" text "<span .... >" is visible in privacy page.
![screenshot from 2015-02-19 15 14 00](https://cloud.githubusercontent.com/assets/4049383/6264444/1abb6d2e-b84a-11e4-94f2-dcf85427e0d4.png)

**Comment by Flaburgan** [comment]
This is already fixed in develop see https://github.com/diaspora/diaspora/issues/5662, please update your code.

**Comment by aka001** [comment]
Okay got it. Thanks.
