### ISSUE TITLE
Re-sharing a post doesn't update the stream

### ISSUE THREAD

**Issue by WebDevFromScratch** [diaspora/diaspora#5690]
So, if you post a new message or comment, like, etc. the stream view updates. But when you re-share someone elses post it does not. Is it supposed to stay this way?

I hope I'm not repeating an issue here, I couldn't find a similar one (although it would be really weird if noone noticed this behaviour before).

**Comment by jhass** [comment]
Sure somebody noticed, but looks nobody cared to open an issue yet ;)

**Comment by WebDevFromScratch** [comment]
Okay ;) I can actually look into it, too.
