### ISSUE TITLE
pencil and check icons in left side bar, my aspect selection

### ISSUE THREAD

**Issue by rivendale2010** [diaspora/diaspora#5694]
On a fresh install of develop branch the icons pencil.png and check_yes_ok.png in my aspect selection return 404. Pre-compile was done and browser caches were cleared. 

The screen:
![untitled](https://cloud.githubusercontent.com/assets/1795059/6312032/41e378f2-b943-11e4-8327-7a3d760edb69.png)
 
The console log: 
![untitled](https://cloud.githubusercontent.com/assets/1795059/6312049/85e83e66-b943-11e4-8d33-aa1da867d023.png)

**Comment by Flaburgan** [comment]
I guess https://github.com/diaspora/diaspora/pull/5715 fixed that. At least, I can't reproduce.

**Comment by jhass** [comment]
I can: ![](http://cloud.aeshna.de/u/mrzyx/screenshots/screenshot_20150302_022732.png). That path is longer generated by Rails 4, you probably just happen to have an old version still floating around.
