### ISSUE TITLE
[Mobile] Clicking on right side of the screen activates a menu item

### ISSUE THREAD

**Issue by PolynomialDivision** [diaspora/diaspora#5696]
Hi,

when I'm using Diaspora on my mobile (LG P880) with Fierfox for Android and I'm clicking somewhere on the right side of the screen I'm clicking on a menu item but the menu isn't open.
So when I'm clicking on the right side I go to settings or my activitys ...

**Comment by Flaburgan** [comment]
Could you please tell me which version of Firefox for Android you are using?

**Comment by SansPseudoFix** [comment]
Oh, indeed oO
Tried with Android 4.4.4 and Firefox 35.0 (with your web app @Flaburgan )

**Comment by Flaburgan** [comment]
We have to review and merge https://github.com/diaspora/diaspora/pull/5556 I'm sure it can improve the situation.

**Comment by Polynomdivison** [comment]
I'm using Firefox for Android 35.0.1

**Comment by AugierLe42e** [comment]
I confirm this on Fennec F-droid (Firefox) 39.0.2 and not on [diaspora native webapp](https://github.com/martinchodev/Diaspora-Native-WebApp) (webkit-based).

**Comment by Flaburgan** [comment]
I can't reproduce this with Firefox OS nor Galaxy S5 Android 4.4 Google Chrome. So this is Firefox for Android specific.

**Comment by jaywink** [comment]
Can't reproduce Firefox for Android (on Jolla) 40.0. Tried:

iliketoast.net (0.5.99)
joindiaspora.com (0.5.2)

**Comment by svbergerem** [comment]
@AugierLe42e, @SansPseudoFix Are you still able to reproduce this?

**Comment by AugierLe42e** [comment]
Yes, I confirm I can reproduce on FF mobile 47.

**Comment by SansPseudoFix** [comment]
Seems fixed for me. Tried with android 4.4.4 and FF 47, on diaspora-fr.org. I tried to click everywhere, and nothing.

**Comment by Flaburgan** [comment]
@AugierLe42e can you still reproduce this? @SansPseudoFix says it's fixed for him. I guess you tried on diaspote.org so with https://github.com/diaspora/diaspora/pull/6233 already merged in but I want to confirm.

**Comment by AugierLe42e** [comment]
Seems fixed.

**Comment by Flaburgan** [comment]
Closing so.
