### ISSUE TITLE
[Design] Fixed footer ?

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/diaspora#5697]
I wanted to pu that on Loomio, but I don't see any design section.
Here is how it looks like on [diaspote.org](https://diaspote.org) :

![fixedfooter1](https://cloud.githubusercontent.com/assets/3429231/6315310/b9d72712-b9fe-11e4-9b1d-25179bbd9234.png)
![fixedfooter2](https://cloud.githubusercontent.com/assets/3429231/6315311/b9e33e1c-b9fe-11e4-8f83-f199b8bae940.png)

**Comment by jhass** [comment]
Sorry, but I don't like that at all.

**Comment by svbergerem** [comment]
I agree. Also let's wait until we ported everything to Bootstrap 3 and are doing the planned redesign before deciding if this should be implemented.

**Comment by goobertron** [comment]
Me neither, I'm afraid. It seems to unbalance the page to have the header bar reflected at the foot of the page; plus, it may look a bit odd especially on pages which have endless scrolling.

Thanks for coming up with new design ideas, Augier, and please don't stop, but I'm afraid this one doesn't work for me.

**Comment by AugierLe42e** [comment]
NP. I personally like that one. It shows off the '*powered by diaspora\* *' to me ;)

**Comment by Flaburgan** [comment]
I'm not a fan of the black background, but to see the footer at the bottom of the page even if there is no content before is a good idea imo, it currently looks not really smooth on the login page for example.

**Comment by AugierLe42e** [comment]
> I'm not a fan of the black background

Me neither. :s

**Comment by Raven24** [comment]
I think it might really work with the screen-filling picture, but not on the stream page, unfortunately

**Comment by AugierLe42e** [comment]
In fact, on the stream page, it' not  that weird. At the opposite, the current login page, for instance, with the footer at the three quarter of the page is really weird :

![footer](https://cloud.githubusercontent.com/assets/3429231/6318043/26b68e1e-ba7b-11e4-8237-4778120ee887.png)

**Comment by jhass** [comment]
> There's also a problem : with a not fixed footer on the stream page it is almost useless because link can almost never be clicked as the content always refresh when you read the en of the page.

That's why we replicated the footer contents in the right side bar. We should just hide the footer on the stream page though.

**Comment by AugierLe42e** [comment]
> That's why we replicated the footer contents in the right side bar. 

That's it... The right side bar is hidden on my computer and not clearly visible on my phone, which is why I've never noticed it.

**Comment by AugierLe42e** [comment]
So, if I understand well, fixed footer is not a problem except for the stream page ? What if I submit a PR for a fixed footer and a stream page without footer ?

**Comment by jhass** [comment]
What problem does the fixed footer solve? On the stream pages it's to see it, I get that, but do you really think that frame-ish look is better?

**Comment by AugierLe42e** [comment]
Well usually, the main principle of a footer is to be... at the foot. Not in the middle of the page:

![](https://cloud.githubusercontent.com/assets/3429231/6318043/26b68e1e-ba7b-11e4-8237-4778120ee887.png)

**Comment by Flaburgan** [comment]
Yeah I agree about that, it would be nice to put the footer at the bottom of the screen when the height of the page is < at the height of the screen.

**Comment by jhass** [comment]
Okay sure, that's quite different from having it statically there always though.

**Comment by AugierLe42e** [comment]
Well my proposition would be to have it fixed on page presentation pages (login, index, password change, etc...), none on social pages (stream pages, single post pages, conversations...) and unchanged on other pages (administration, configuration, etc...)

**Comment by jhass** [comment]
Do we have to special case that per page really? Is there no dynamic solution to this that adapts to the page content?

**Comment by Flaburgan** [comment]
Maybe @svbergerem has one. Not sure if we can do that with plain CSS, but we can definitely with JS, testing if windows.height > html.height then footer : position: fixed; bottom: 0px;

**Comment by AugierLe42e** [comment]
It can be a solution.

**Comment by AugierLe42e** [comment]
Is this issue still relevant ?
