### ISSUE TITLE
Update the help section

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#5698]
A lot of things changed in 0.5 so we need to update the help section. This task can be done by non-technical persons so don't hesitate to ask here if you want to help even if you know nothing about the codebase, we can help you.

**Comment by AugierLe42e** [comment]
Maybe worth to make a list of changes @Flaburgan ?

**Comment by aka001** [comment]
I would like to help with this issue. Please help me in getting started.

**Comment by Flaburgan** [comment]
@aka001 this is not a technical issue but only a check that actual help texts match the new version of diaspora*. So, simply open diaspora* running the last develop code, go to the help section, read and change it if needed to reflect the new diaspora* interface.

**Comment by aka001** [comment]
@Flaburgan Okay. I will create a pr for the same.

**Comment by aka001** [comment]
I have started with this pull request https://github.com/diaspora/diaspora/pull/5706 . Kindly have a look.

**Comment by Flaburgan** [comment]
I guess this should have the "next-major" milestone.

**Comment by goobertron** [comment]
If someone can list which functionality has changed and therefore which parts of the help section need updating, I'll write some new text. I don't have the energy right now to go through the whole UI testing for changes, I'm afraid.

**Comment by Flaburgan** [comment]
I have most of the changes in mind I think, I'll see if I can find some time to open a PR.

**Comment by goobertron** [comment]
Adding a location to the post: we should say where this information is obtained, and who your data are shared with. It looks to be Mozilla geolocator, which from their FAQ appears to send user data to Google Location Services: see https://www.mozilla.org/en-GB/firefox/geolocation/

Is this correct?

**Comment by goobertron** [comment]
Ah, got it from /app/assets/javascripts/osmlocator.js - it's OpenStreetMap.

**Comment by goobertron** [comment]
PR submitted: #5859

Please check the changes and make sure all the updates required have been made, and let me know of anything else I need to do.
