### ISSUE TITLE
no message if email is wrong while recovering password.

### ISSUE THREAD

**Issue by norayr** [diaspora/diaspora#5704]
when user tries to recover the password, fiils email address, presses "Forget Password" link, nothing happens, if email does not present in database. It does not say that no user with that email registered.

User has to guess that email he/she entered is wrong and enter right email. Only then message happens that email has been sent to that address.

**Comment by Flaburgan** [comment]
This has already been fixed in the coming version, see https://github.com/diaspora/diaspora/issues/5321
