### ISSUE TITLE
Safari Login Problem 

### ISSUE THREAD

**Issue by moormanator** [diaspora/diaspora#5720]
A friend complained to me that he was having difficulty accessing both of his pods from Safari On Mac OS X 10.7 and 10.6. So I set up from my own Mac two new accounts on different pods:

https://pod.orkz.net  (code 0.4.1.2-p5cabd692 )
https://kosmospora.net (0.4.1.2-p0bfad313)

My Mac OS X version is 10.10.2 (Yosemite)
Safari is running on build 8.0.3
Firefox is running on build 36.0
Chrome is running on build 40.0.2214.115

I was able to log in to https://pod.orkz.net on all three browsers.
I was able to log in to https://kosmospora.net on Chrome and Firefox
When I attempted to log into my account on Safari, I repeatedly received the error "Invalid login or password"

**Comment by jhass** [comment]
Can anybody reproduce this?

I'm sorry, but this sounds very much like you just entered the wrong credentials, I don't see how Browser choice could affect that.

**Comment by Flaburgan** [comment]
I confirm that I am able to log in on stable (diasp.org, framasphere.org and joindiaspora.com) and develop (diaspora-fr.org) pods using Mac OS Yosemite and Safari 8.

**Comment by moormanator** [comment]
OK, this is strange. When I was keying it in earlier this morning, I checked and double checked the login and password multiple times prior to submission. I even went back and forth 5 or 6 times between Chrome and Safari, logging in with chrome successfully, but having no luck with safari.  However, I stopped and waited 2 hours and now everything works.

However,  my friend in Berkeley is still having sign-in issues in Safari on Mac OS X 10.7.3.  He writes, 

On 3/2/15, 1:20 PM,  <a2b2@mcn.org> wrote:

>>>>Hi Joe,

I have to get to this later, but I just tested on the desktop and now I can no longer open orkz OR kosmo in either Ffox OR Safari !!!!!<<<

He has already cleared his browser cookies and cache, and reset his diaspora password numerous times.

**Comment by moormanator** [comment]
Thanks, by the way for responding so quickly. Any work around for my friend would be greatly appreciated.

**Comment by Flaburgan** [comment]
10.7 is mavericks right? I'm able to log in to joindiaspora.com and framasphere.org on Mac OS 10.7 using Safari 7 and Firefox

**Comment by moormanator** [comment]
Thanks for testing with Safari 7. Very helpful. I'm going to call my Berkeley friend back tonight and walk through every step with him.

**Comment by Flaburgan** [comment]
Ask him if he is sure to try to sign in the right pod.

**Comment by goobertron** [comment]
I have just logged in successfully to both pods using Mac OS 10.7.5 and Safari 6.0.5. So this issue is unreproduceable by me, using the OS and browser indicated.

If your friend now can't log-in using Firefox either, this suggests strongly that something is wrong in his set-up. I'd suggest using someone else's machine to see if he can log in; if that doesn't work, suggest he click the 'Forgot your password?' link, as perhaps that's the problem.

**Comment by jhass** [comment]
Closing for now, if anybody can reliably reproduce with a fresh account, please indicate so.
