### ISSUE TITLE
Mobile site: Menu is always present on Opera Mini (J2ME version)

### ISSUE THREAD

**Issue by DoctorJellyface** [diaspora/diaspora#5723]
While browsing the D* mobile site on Opera Mini 8.0.35625 (J2ME) on my Sony Ericsson Hazel, the menu (with aspects, profile, etc., present in the top right) is always present, behind the other content. It's very hard to post something, because the buttons interfere with the controls.

**Comment by jhass** [comment]
Maybe we should define which mobile browsers we support, I wouldn't be sure whether we want to support this one to be honest.

**Comment by DoctorJellyface** [comment]
I agree, but it works fine on all other pages. It seems like a minor fix.

**Comment by Flaburgan** [comment]
So, which page is this about?

**Comment by DoctorJellyface** [comment]
Oh, my fault, by other pages I meant **other sites**, sorry for that.

The bug seems present everywhere where the header bar is.

**Comment by denschub** [comment]
Works with Opera Mini 13. J2ME versions are.. well... old and will break in the future for us anyway, so I do not really see a point of even trying to achieve compatibility here. The amount of work we'd have to put into that would be insane. :/

**Comment by DoctorJellyface** [comment]
Oh, I thought this was closed ages ago. I don't really care anymore either, my old phone broke and I haven't seen a J2ME phone with wifi ever since.
