### ISSUE TITLE
UX: "X" to close in post textarea can sometimes overlay text

### ISSUE THREAD

**Issue by gordon-morehouse** [diaspora/diaspora#5726]
![diaspora x 2](https://cloud.githubusercontent.com/assets/304300/6475010/c71f1c0e-c1ba-11e4-82e4-a19d9f3e35b3.png)

Text in the post-entry textarea can sometimes be mashed together with the "X" to close, thus making it hard to see the "X." If a user clicks to place their cursor in the affected area, all text in the textbox is lost.

The X should be moved. See attached.

**Comment by Flaburgan** [comment]
The publisher has be completely rewritten in the next release so this bug is not here anymore. Thanks for reporting anyway ;)

**Comment by svbergerem** [comment]
This is the new publisher:
![](https://cloud.githubusercontent.com/assets/3798614/6475271/740e999c-c208-11e4-96d0-c3be0fa51b30.png)

**Comment by gordon-morehouse** [comment]
Sweet!
