### ISSUE TITLE
Use Formstone Boxer to display the photos

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/diaspora#5732]
[Formstone Boxer](http://formstone.it/components/boxer) is a jQuery plugin that lets you display the photos correctly in a full page. I'm using it in a school project. Very easy to use. It is MIT license. You can find demos on the website.

**Edit** : let me be a bit more precise : I don't propose this for design but to easier the code maintenance. Everything that let us reduce the code and rely on third-parties sounds good to me.
I fnd the current displayer buggy and weird. E.g : the arrows at the bottom should display the next image and the little carousel should move alone as a new image is displayed. And sometimes, big images get out of the window.

**Comment by jhass** [comment]
I don't like the white border around it.

**Comment by AugierLe42e** [comment]
This can be overriden by CSS rules. And it will always be better than what we have now.

**Comment by SansPseudoFix** [comment]
Yeah, with some CSS rules, it could be pretty cool. And it's mobile friendly.

**Comment by AugierLe42e** [comment]
@SansPseudoFix : Do you want to take care of it ?

**Comment by Flaburgan** [comment]
>And it will always be better than what we have now.

Why? What's bothering you in what we have now? I see no bug, I don't want to waste time on something which works when we have so many things to do.

**Comment by AugierLe42e** [comment]
Hmm... I suppose we can also use [Bootstrap's carousel](http://getbootstrap.com/javascript/#carousel) ?

**Comment by polsVoice** [comment]
I agree with @AugierLe42e. There are lots of awesome JS slideshows and lightboxes out there, and many of them are free or open source.

**Comment by AugierLe42e** [comment]
The port to BS3 enables the use of plugins for galleries like hightlighted in #6031. So closing this.
