### ISSUE TITLE
Weird error message on too long tag

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/diaspora#5737]
Not sur this is an issue but raising it anyway.

![Text displayed : {"status":"500", "error":"Internal Server Error"}](https://cloud.githubusercontent.com/assets/3429231/6541793/28dab18e-c4e4-11e4-91eb-8d6472f2a8dc.png)

Tested on diaspora-fr.org

**Comment by SansPseudoFix** [comment]
And worst with dev enironment (error message is too long to post here).

**Comment by AugierLe42e** [comment]
Yeah ! \m/

**Comment by jhass** [comment]
One of you wants to dig the actual error out of the log?

**Comment by jhass** [comment]
Also this is two bugs, please open a separate one about the incorrect failure response formatting in the new publisher.

**Comment by svbergerem** [comment]
@jhass 
```
NoMethodError (undefined method `to_sentence' for nil:NilClass):
  app/controllers/status_messages_controller.rb:96:in `block (2 levels) in create'
  app/controllers/status_messages_controller.rb:93:in `create'
  config/initializers/silence_assets.rb:9:in `call_with_quiet_assets'
  lib/rack/chrome_frame.rb:39:in `call'
```

**Comment by visualsayed** [comment]
ActsAsTaggableOn gem limits the tag name to a 255 chars length and it validates the length in the ActsAsTaggableOn::Tag model.

When the tag name length is greater than 255, an error is raised but not propagated to the StatusMessage model 

The create method in the StatusMessagesController fails and executes:
` format.json { render :text => @status_message.errors.messages[:text].to_sentence, :status => 403 }`
The messages hash is empty, so (@status_message.errors.messages[:text]) returns nil and we can't invoke to_sentence on a nil value.

@AugierLe42e  @SansPseudoFix  @svbergerem 
@jhass 
Please check this fix and if it's ok let me send a pull request.

**Comment by jhass** [comment]
LGTM, thank you!

**Comment by Flaburgan** [comment]
I think https://github.com/diaspora/diaspora/pull/5783 closed that, right?

**Comment by visualsayed** [comment]
Yes
