### ISSUE TITLE
Fetch remote user public posts on fetch user

### ISSUE THREAD

**Issue by jaywink** [diaspora/diaspora#5739]
Currently when adding a user previously unknown to current pod, profile of user is fetched but not earlier public posts. To allow seeing users previous public posts, a subset (10?) of them should be fetched also.

**Comment by jhass** [comment]
Uhm, we do this, don't we? https://github.com/diaspora/diaspora/blob/develop/app/workers/fetch_public_posts.rb

**Comment by Raven24** [comment]
#3482 well, if it doesn't work, that's a regression then

**Comment by jaywink** [comment]
Well, [looking at the code](https://github.com/diaspora/diaspora/blob/develop/lib/diaspora/fetcher/public.rb#L78), it fetches `/people/[guid].json` which doesn't contains any posts - which could be a problem ;)

Check mine for example: https://iliketoast.net/people/7ed1555bc6ae03db.json

**Comment by Raven24** [comment]
oh, you're right. that behaviour changed when I ported the profile page to backbone.js (#5180)
... that's why we tell people not to rely on our json endpoints :P

**Comment by jaywink** [comment]
Isn't this fixed by https://github.com/diaspora/diaspora/pull/5958?

**Comment by svbergerem** [comment]
@SuperTux88 confirmed that he fixed this issue.
