### ISSUE TITLE
Empty mention list

### ISSUE THREAD

**Issue by davidbaumann** [diaspora/diaspora#5748]
Hello,

some functions like the stream in Diaspora take some seconds to load.
My mention list is empty, and it just looks like it was still loading to me.

Maybe an empty list should be like "You have not been mentioned yet" or something like that.

What do you think?

David.

**Comment by Flaburgan** [comment]
Yeah, we should add a message when streams are empty, especially on the profile user, it looks really weird.

**Comment by davidbaumann** [comment]
I had a look into the source - but I have no idea where to fix this :D
