### ISSUE TITLE
Switch back to mobile version

### ISSUE THREAD

**Issue by davidbaumann** [diaspora/diaspora#5750]
In chrome for Android, I cannot switch back to the mobile version.
I scroll down, but then the page loads more entries, so even if I manage to click, it's not working.

**Comment by jhass** [comment]
Use the link in the right sidebar.

**Comment by davidbaumann** [comment]
Oh, thanks and sorry.
Maybe the link in the footer should be removed?

**Comment by svbergerem** [comment]
@davidbaumann #5298
