### ISSUE TITLE
Hovercard never disappears

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#5753]
Since https://github.com/diaspora/diaspora/pull/5714 is merged, we have a bug with persistent hovercard.

![capture du 2015-03-10 17 05 22](https://cloud.githubusercontent.com/assets/930064/6578982/af547582-c747-11e4-9260-6981cf1abe56.png)

It's not really easy to reproduce, try to mouse hover an avatar and when it appears move quickly elsewhere. I'm sure if you run the last develop code you already saw the problem.

**Comment by jhass** [comment]
Mmh, no, I can't reproduce.

**Comment by marienfressinaud** [comment]
I can't reproduce neither on diaspora-fr.org. Have you tried with different browsers?

**Comment by SansPseudoFix** [comment]
I have this bug too and it drives me crazy. It's hard to **reproduce** but I have this one many times. Tested with iceweasel 31.5.0.

**Comment by SansPseudoFix** [comment]
[Here](http://v.sanspseudofix.fr/diaspora_issue_5753.webm), a *wonderful* video to show you how to reproduce. But I'm surprised you didn't see it so far.

**Comment by goobertron** [comment]
> a *wonderful* video to show you how to reproduce.

Porn?? :P

**Comment by SansPseudoFix** [comment]
Oh. I didn't notice this way to understand this sentence. People will be disappointed I guess :D

**Comment by Anime-Machina** [comment]
Confirmed, diasp.net has the same issue. Simply hover over some thing and move out of the box. It is quite annoying since when I need that box it disapears :(

**Comment by AugierLe42e** [comment]
This bug is a bit random. Sometimes, the hovercard appears even if the mouse is not over an hovercardable.

**Comment by Flaburgan** [comment]
@AugierLe42e I guess you quickly moved the mouse on the screen and it crossed a name somewhere. I had this behavior too.

**Comment by AugierLe42e** [comment]
This is my theory, yes, but it should not appear that quickly and stay displayed then.

**Comment by Anime-Machina** [comment]
Tried to move my mouse around at empty space and it happens. Also when you are at the diaspora star top left. I did noticed it might be caused when going over certain kinds of grids when using firebug or developer tools.

**Comment by goobertron** [comment]
I'm unable to reproduce this on diaspora-fr.org, so it doesn't appear to be a pod issue. I've tested in two browsers, and all works fine, whether zooming over post and comments avatars or the avatars of people in the stream at top right.

Can anyone who does reproduce this locate any problem in the code? If not, should we allow this ticket to block release of 0.5.0.0?

**Comment by Flaburgan** [comment]
@goobertron I definitely can reproduce it on d-fr. Just use it ~10 minutes navigating between the stream and the SPV and I'm sure you'll see it too. Using Firefox here, I don't know about the other browsers.
