### ISSUE TITLE
Expanding the Comments on mobile view auto-scrolls to the very bottom

### ISSUE THREAD

**Issue by RichKavanagh** [diaspora/diaspora#5757]
When using mobile view, if you expand the comments the browser auto-scrolls all the way down to the very last comment.

You then have to manually scroll all the way back up again to read the first comment.

Expected behaviour would be click to expand comments - the comments expand and the current focus should not change, allowing the user to read the first comment, first.

**Comment by RichKavanagh** [comment]
We can't add/suggest labels to issues? Is this a github thing?

**Comment by jhass** [comment]
Only repository collaborators can set labels.

I'm tagging this as feature since this is essentially functionality you disagree with, not a bug.

**Comment by RichKavanagh** [comment]
> Only repository collaborators can set labels

Cool, good to know, thanks :+1: 

> I'm tagging this as feature since this is essentially functionality you disagree with, not a bug.

Nope, I completely disagree with that. Every single web site in the world that has expanding comments doesn't auto-scroll to the very bottom of all the comments and then make the users manually scroll all the way back up again.

How do I get this 'feature' tag changed to a 'bug' tag mate?

**Comment by jhass** [comment]
It's not broken functionality, [there's code](https://github.com/diaspora/diaspora/blob/develop/app/assets/javascripts/mobile/mobile.js#L144) to provoke the behavior you describe.

**Comment by RichKavanagh** [comment]
Oh sweet!

Thanks for the explanation mate :)

**Comment by RichKavanagh** [comment]
Oh sweet!

Thanks for the explanation mate :)

**Comment by jhass** [comment]
Ugh, I tried to explain that the current behavior is intentional. While I don't follow why it was chosen either, there might be people who disagree with you. I'm not sure if posting a bounty is wise at this point.

**Comment by RichKavanagh** [comment]
> Ugh

Ugh?

> I tried to explain that the current behavior is intentional

Yup, you explained it perfectly, I understood you :)

> While I don't follow why it was chosen either, there might be people who disagree with you.

Yup, that's life mate!

> I'm not sure if posting a bounty is wise at this point.

It'll never change if I don't.

**Comment by kas70** [comment]
i agree with RichKavanagh.  
this is very, very annoying for me.  
thanks for opening an issue for that!

**Comment by visualsayed** [comment]
Could we convert this to an option so a user can choose his favourite way at settings page?

**Comment by jhass** [comment]
> Could we convert this to an option so a user can choose his favourite way at settings page?

No, we should go with what the majority wants. Making everything configurable is just as confusing.

**Comment by Flaburgan** [comment]
The solution is easy: open comments when click on "Reaction", focus on the comment form when click on the comment icon.

**Comment by RichKavanagh** [comment]
Can we add a #mobile tag to this?

Also to add to the original issue, this does not happen on desktop mode, only on mobile.

If I click to expand a post in my stream (just tried one which had 49 comments), they all expand neatly downwards, nothing scrolls anywhere and the focus does not change. This behaviour only happens on mobile view and not on desktop view, it's quite inconsistent.

**Comment by RichKavanagh** [comment]
Thanks @jhass !

**Comment by RichKavanagh** [comment]
@Flaburgan 

> The solution is easy

Easy enough for you to code a fix? :)

**Comment by desyncr** [comment]
Should be labeled 'quickfix' then?, to attract new comers?

**Comment by RichKavanagh** [comment]
Has this been fixed?

**Comment by kas70** [comment]
yes, i thinks so.

Am 12. Mai 2015 22:21:56 MESZ, schrieb Rich <notifications@github.com>:

**Comment by RichKavanagh** [comment]
Who fixed it? There's a bounty on this which needs claiming by someone :)

**Comment by kas70** [comment]
i have to revoke my assumption. it still scrolls down to bottom of the comments :/
