### ISSUE TITLE
Incorrect hashtag split for Malayalam

### ISSUE THREAD

**Issue by balasankarc** [diaspora/diaspora#5765]
While giving hashtags in Malayalam language, the hashtag gets split at the character ്   (Unicode codepoint - +0D4D ) . This character is used to to join two consonants so as to form a conjunct and is part of a whole word. Hence, hashtag must not split at this character and must continue till a space is occured.
Example : ണ്മ is formed by ണ + ് + മ 
In the post https://poddery.com/posts/1672504 , the hashtag #മലയാണ്മ gets split at ്  and hence becomes #മലയാണ (് മ gets cut off).
##

**Comment by jhass** [comment]
To clarify, the frontend code seems to parse it correctly, but 04D4 is not in `[[:alnum:]]`, so the backend associates the wrong tag.

**Comment by svbergerem** [comment]
After changing the markdown parser from pagedown to markdown-it this also won't be parsed in the frontend code because we now use [[[:alnum:]]](https://github.com/diaspora/diaspora/blob/develop/lib/assets/javascripts/posix-bracket-expressions.js#L7).

**Comment by jhass** [comment]
> /[[:word:]]/ - A character in one of the following Unicode general categories Letter, Mark, Number, Connector_Punctuation

Am I missing something or would this be good to use?

**Comment by balasankarc** [comment]
Hi, any update on this?? This is actually breaking the hashtag functionality in Malayalam as there are numerous words which use +0D4D and are commonly used for hashtags.
