### ISSUE TITLE
password entry bypassed via Natural News Pod

### ISSUE THREAD

**Issue by offgridgal** [diaspora/diaspora#5768]
I never received the chance to enter my password when signing up via the natural news pod for Diaspora.

Now I have an account with a password which I am unaware of, its a Catch 22

Please help

Thank you

**Comment by jhass** [comment]
Please contact your podmin via mail at share@naturalnews.com.

**Comment by offgridgal** [comment]
Thank you Jonne for responding quickly.I have sent them an email. I
hope to hear from them soon. :)

Off grid Gal 

On 12/03/2015 at 5:33 PM, "Jonne Haß"  wrote:

	Please contact your podmin via mail at share@naturalnews.com.
