### ISSUE TITLE
Share "Reshares" to Facebook

### ISSUE THREAD

**Issue by gaupa** [diaspora/diaspora#5771]
Add a button to post reshares to Facebook, and let Facebook-users see how much awesome information that's flowing on Diaspora :)
##

**Comment by Motokiyo** [comment]
3 years ago 🙁 and this add seems really important. Like add some text when you repost. I hope an Angel come and see this ♥

**Comment by Flaburgan** [comment]
We're not cross-posting anything to Facebook anymore.
