### ISSUE TITLE
Infinite scroll doesn't display the correct loding image

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/diaspora#5779]
The current mobile image is the following:

![lodingimage](https://raw.githubusercontent.com/diaspora/diaspora/145aac4d2805eae332bd439c98a067b60c150668/app/assets/images/static-loader.png)

which is defined in [the spinner CSS](https://github.com/diaspora/diaspora/blob/145aac4d2805eae332bd439c98a067b60c150668/app/assets/stylesheets/new_styles/_spinner.scss#L24):

    mask-image: image-url('static-loader.png');
    animation: spin 1s infinite ease-in-out, fade-in 0.2s ease-in;
    
    background-image : image-url("static-loader.png");

and should be animated. Though, the [infinite scroll widget](https://github.com/diaspora/diaspora/blob/145aac4d2805eae332bd439c98a067b60c150668/app/assets/javascripts/widgets/infinite-scroll.js#L16) defines `loadingImg: ImagePaths.get("ajax-loader.gif")` so the loading image for the infinite scroll should be:

![](https://github.com/diaspora/diaspora/blob/145aac4d2805eae332bd439c98a067b60c150668/app/assets/images/ajax-loader2.gif?raw=true)

**Comment by AugierLe42e** [comment]
Inifinite scroll is one of the few [widgets left](https://github.com/diaspora/diaspora/blob/develop/app/assets/javascripts/widgets/infinite-scroll.js). I think, as there are there is at least three infinite scroll usage, we can use the infinite scroll component proposed by [Fuel UX](http://getfuelux.com/javascript.html#infinite-scroll). Fuel US is a library built on the top of Bootstrap.

**Comment by RichKavanagh** [comment]
Is this related to [loading spinner broken in streams](https://github.com/diaspora/diaspora/issues/6063#issuecomment-109581123) ?

**Comment by AugierLe42e** [comment]
Yes. There were 3 kind of spinners. I eliminated 2 of them for consistancy during the port.
