### ISSUE TITLE
Opening the dropdown doesn't update the notification count

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/diaspora#5780]
I though I solved the bug but seemd not. As @jhass  noticed [here](https://github.com/diaspora/diaspora/pull/5707#discussion-diff-25560611) I think the notifications should not be directly transmitted in HTML but in a JSON structure and rendered client side. This way, the total count of unread notifications could be transmitted too.
##

**Comment by goobertron** [comment]
Posted in #6181:
 
I've noticed that when I open a page by clicking on a notification and then click the browser's 'back' button, while the new notifications dropdown is updated (showing the notification you just clicked as read), the notification badge in the header still shows the previous number, as though that notification just clicked was in fact unread.

(Reposting here in case it provides extra information for debugging.)
