### ISSUE TITLE
Poll question field overflows publisher pane

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#5784]
![_poll](https://cloud.githubusercontent.com/assets/2530168/6656761/49c3540c-cb2c-11e4-8eab-1a79f426ea20.png)

**Comment by goobertron** [comment]
Wow, that's a lot of labels. I'm tempted to put a bounty on it just to add another label. ;)

**Comment by jhass** [comment]
Rainbows and unicorns!

**Comment by svbergerem** [comment]
I'm not able to reproduce this. The question input has `width: 100%` so it sounds unlikely that it overflows the publisher. Which browser are you using? (+ version)

**Comment by goobertron** [comment]
Ach, sorry. I saw this in my dev env using Selenium and 'confirmed' in diaspora-fr.org using Firefox, but of course Selenium runs in the same browser version (I guess), so it's not really confirmation at all. Doesn't appear in Opera or TorBrowser, so must be specific to my (old) version of Firefox. Thanks for pointing this out promptly, Steffen.

I'll close the issue. Sadly that means no rainbows or unicorns for anyone!
