### ISSUE TITLE
Reshare a post from a user profile adds it to the profile stream

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#5795]
![capture du 2015-03-18 10 24 18](https://cloud.githubusercontent.com/assets/930064/6705888/55e03d2a-cd59-11e4-9ce2-560a1368b01e.png)

Step to reproduce:
* Go to someone's profile
* Reshare a public post
* Scroll up to the top of the page
* Your post is here, first of the stream

I have in the JS console:
```
"no templateName specified" main-841d6199e14221ef58e534cb5b8f7ad0.js:9:21731
TypeError: e is null main-841d6199e14221ef58e534cb5b8f7ad0.js:11:5078
```

The post of course disappears when the page is reloaded, so this is a JS problem, probably caused by https://github.com/diaspora/diaspora/pull/5699

**Comment by svbergerem** [comment]
This issue is related to #4672.

**Comment by Flaburgan** [comment]
Btw I didn't tested but I guess that this is the same on the tag page.

**Comment by Flaburgan** [comment]
I think this should be part of 0.5.0.0 too.

**Comment by Flaburgan** [comment]
To solve this issue, one should test [here](https://github.com/diaspora/diaspora/blob/develop/app/assets/javascripts/app/models/post/interactions.js#L113) if ```app.stream``` is not a tag stream or a profile stream.
