### ISSUE TITLE
WebRTC in Diaspora

### ISSUE THREAD

**Issue by davidbaumann** [diaspora/diaspora#5800]
Hello,

actually I ask myself, if there's a way to integrate WebRTC into Diaspora?
Has there already been a discussion about this?

David.

**Comment by Flaburgan** [comment]
Hi @davidbaumann.
Yeah, we talked about it a lot [on loomio](https://www.loomio.org/d/0czigqsM/implement-realtime-chat-possibly-using-xmpp). We finally chose to use XMPP but the JavaScript interface we use to chat, JSXC, also allows to use WebRTC (see https://www.jsxc.org/). We need to first polish the XMPP chat, but it looks doable to use WebRTC with the same interface.

**Comment by davidbaumann** [comment]
Thank you for your reply. I was doing a search for WebRTC here, and it couldn't find anything.

**Comment by digitalhuman** [comment]
I thought most browsers (FF and Chrome) will disable and remove WebRTC in future releases due to security issues?

**Comment by denschub** [comment]
This is neither an issue nor a feature request. Feel free to create an issue if you found any issues or a discussion on Loomio for feature requests.
