### ISSUE TITLE
Order of comments on the mobile version is reversed

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#5804]
The most recent comment is now displayed first.
This regression is probably caused by https://github.com/diaspora/diaspora/pull/5790

**Comment by jhass** [comment]
No, I don't see how #5790 could have caused that.

**Comment by Flaburgan** [comment]
Well, last pull was https://github.com/diaspora/diaspora/commit/0856eb8f86b6e2d8fba53b5defbd2268d1668106 and everything worked fine, I updated this morning and now the order is inversed.

**Comment by jhass** [comment]
Oh you're right, that one was subtle. He switched from `@comments` to `@post.comments`, I didn't notice :/
