### ISSUE TITLE
Profile images from facebook accounts are fetched over HTTP not HTTPS

### ISSUE THREAD

**Issue by tomato42** [diaspora/diaspora#5808]
When a user has a profile photo imported from Facebook (served from facebook servers), the image URL is HTTP not HTTPS, causing a mixed content warning.

**Comment by Flaburgan** [comment]
We changed the way FB images are fetched in the current develop branch, so I think this is no longer the case (we do not send a request to FB anymore).

**Comment by jhass** [comment]
Yes, in fact duplicate of #5341 I'd say.
