### ISSUE TITLE
Video flicker on Diasp.net

### ISSUE THREAD

**Issue by RodL** [diaspora/diaspora#5810]
Running Firefox and everytime i log into Diasp.net my video flickers. Using Linux Mint Cinnamon.

Error message occaisonally says unresponsive script https://diasp.net/assets/jsxc-e660beffa5fa259ea8f528e10ad756d7.js:7

Firefox version 36.0.1 mint - 1.0
Diasp.net is running develop version.

**Comment by jhass** [comment]
I think this is a duplicate of https://github.com/diaspora/jsxc/issues/88

**Comment by RodL** [comment]
Similar but my screen does not freeze it just flickers (dims for split second) when i first log in and on rare occaisons i get the error message.
It does not happen on my other pods.
Podmin uses Firefox and has not noticed this problem.
I will close this issue and allow him to post if he feels it is different issue.

**Comment by Anime-Machina** [comment]
@jhass yes this is related to https://github.com/diaspora/jsxc/issues/88

And I can confirm this issue, at the moment I am having contact with RodL and will work together with him resolving it. There is a work around for it by clearing its cache till it happens again. Lets resume at diaspora/jsxc#88 for debugging/solving this issue.
