### ISSUE TITLE
The notification action should be updated when other interactions are triggered

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#5811]
**Step to reproduce:**
Open a post in the SPV
Click on the "like" icon

**Actual result:**
The like icon becomes red, but the notification icon stays grey. When you reload the page, the notification icon becomes black.

**Expected result:**
The notification icon should become black in the same time the like icon becomes red.

The behavior is expected for all kind of interaction which will activate notification for the post (like comment).

**Comment by AugierLe42e** [comment]
Related to #5780.
I've already though about that. It is possible, but it should involve to seperate the `setRead` and `setUread` actions in a seperate model or helper. This is needed in any case to simplify the updating of the notifications count.
