### ISSUE TITLE
option to show geo-location on a osm-map

### ISSUE THREAD

**Issue by kas70** [diaspora/diaspora#5813]

**Comment by Flaburgan** [comment]
@kas70 it is already possible to add geolocation using openstreetmap on the desktop version. Could use please precise what you have in mind? To display a map?

**Comment by kas70** [comment]
yep, would be cool to be able to show the location on a map (maybe with [openlayers](http://openlayers.org/)) below a post (maybe as fade-in with a location-button).
adding locations manually for posts (e.g. for events) could be also a use-case, but that would be another feature-request...  
simple mockup is following;)

**Comment by kas70** [comment]
**normal view:**
![location1](https://cloud.githubusercontent.com/assets/922628/6821551/06760f74-d2d8-11e4-9b28-d5dc174be35d.png)

**after clicking the location-button:**
![location](https://cloud.githubusercontent.com/assets/922628/6821502/b80f12d6-d2d7-11e4-9ad2-5e69869891b7.png)

**Comment by kas70** [comment]
this is inspired by @DeadSuperHero's [post](https://pod.geraspora.de/posts/3415814)

**Comment by zaziemo** [comment]
@Realtin and I would like to work on this issue.

**Comment by jhass** [comment]
That's great! I'd say just make the existing location text clickable and maybe always display the map in the SPV.

**Comment by denschub** [comment]
Some considerations:

- We are probably [not allowed](http://wiki.openstreetmap.org/wiki/Tile_usage_policy) to use `{a,b,c}.tile.openstreetmap.org` without prior permission.
- In any case, the tile server url should be configurable.
- Openlayers is probably not the best idea. [Leflet](http://leafletjs.com/) is more suitable for mobile applications.

**Comment by Flaburgan** [comment]
I didn't know Leflet, looks amazing!

**Comment by Realtin** [comment]
Great! We were also thinking to use Leaflet. 

@jhass yes that is exactly what we were planing to do! ☺️☀️
