### ISSUE TITLE
Armenian punctuation marks in tags.

### ISSUE THREAD

**Issue by ghost** [diaspora/diaspora#5815]
Hello,

In Armenian some of [these](https://en.wikipedia.org/wiki/Armenian_alphabet#Punctuation) symbols are used inside words, between letters.

Thus I would like to ask to make possible to use following symbols in tags
- [՜](https://en.wiktionary.org/wiki/%D5%9C)
- [՞](https://en.wiktionary.org/wiki/%D5%9E)
- [֊](https://en.wiktionary.org/wiki/%D6%8A)
- [՛](https://en.wiktionary.org/wiki/%D5%9B)

Thus we can write ինչո՞ւ, այո՜ո, սեւ֊սպիտակ, գժանո՛ց, etc. Thank you.
##

**Comment by jhass** [comment]
This should be uncontroversial. Solving this would involve patching our markdown it plugin for tag parsing and the regexp used in the backend code.

**Comment by svbergerem** [comment]
Just to clarify (because “patching our markdown it plugin” sounds like a bigger task): You only need to change the regexp [here](https://github.com/diaspora/diaspora/blob/3298373a7fd57b6f7f23cb5a36bce0806476b07d/app/assets/javascripts/app/helpers/text_formatter.js#L57). This is related to #5765.
