### ISSUE TITLE
'forEach' undefined in main.js

### ISSUE THREAD

**Issue by rivendale2010** [diaspora/diaspora#5823]
after update today the stream is blank and the javascript console shows "Uncaught TypeError: Cannot read property 'forEach' of undefined" on line 9 of main.js, mobile stream is ok :)

**Comment by jhass** [comment]
I updated my pod to the latest commit too and can't reproduce. Anybody else can?

**Comment by rivendale2010** [comment]
thanks. could be something off on my system, i nuked Gemfile.lock, ran "gem update" and "bundle update" and then the usual update instructions and now is okay :)

**Comment by jhass** [comment]
:(((( DO NOT DO THAT!

We can not support a setup doing that, you at least broke twitter integration with that action. Get back to a clean system: `git checkout Gemfile.lock; bundle install`. **Never** run `bundle update` on your own.

**Comment by rivendale2010** [comment]
i like to test with the latest gems just for fun, i know that is not going to work for regular updates, usually several have to be set back to get it to work, probably how i messed it up in the first place :) ... 

after doing those things i did checkout Gemfile.lock and run bundle as part of the usual update procedure so i think i'm in sync now-- twitter has always complained of a circular reference but i don't use it
