### ISSUE TITLE
Design problem in conversation

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#5828]
There are two vertical borders

![capture du 2015-03-31 19 13 07](https://cloud.githubusercontent.com/assets/930064/6924606/0d6df182-d7da-11e4-8588-8b3cd56e1fe3.png)

**Comment by desyncr** [comment]
The change was introduced [here](https://github.com/diaspora/diaspora/commit/3721861c94ac717da5625f4be65498c053a13e53). It follows the stream layout. I think we could eliminate the gap between the conversation list and the conversation details, like [this](http://i.imgur.com/V1klpHf.png).
