### ISSUE TITLE
[Mobile] Reaction count not consistent

### ISSUE THREAD

**Issue by lolsimon** [diaspora/diaspora#5829]
It seems that the number of reactions within the mobile version are the sum of real reactions + likes. This seems not really consistent. See screenshot below, where there are 3 counted reactions, 1 real reaction and 2 likes.

![screenshot_reactionscount](https://cloud.githubusercontent.com/assets/2278424/6929453/329eb858-d7fb-11e4-939b-de8f7d349277.png)
##

**Comment by desyncr** [comment]
Reactions are indeed the sum of likes, comments and I believe reshares. There is no such thing as "real reactions". What's inconsistent about it?

**Comment by lolsimon** [comment]
With real reactions I mean comments, that is what a user probably expects when he clicks the reactions button.
Now a user clicks on "3 reactions" and there seems to be only 1 (namely, the comment).
Maybe this can be picked up together with issue #5688 to make the UI better on this?

**Comment by desyncr** [comment]
It would be easier to rename "reactions" to "comments" and issue solved. Now I don't think reactions are an issue as they are but I'm not UX or UI expert so maybe someone else could raise a voice here.

**Comment by Makailija** [comment]
I am also far from being an UX or UI expert, but I recently made a suggestion of a redesign of the post interaction buttons on the mobile interface on Loomio: [link](https://www.loomio.org/d/CbqITyU6/suggestion-redesign-of-the-interaction-buttons-of-posts-on-the-mobile-interface). That would solve this issue, #5688 and a few others. You can comment on the suggestion on Loomio. If I will have time next week, I can open an issue on that here in Github, if there are no major objections to my suggestion.

And btw, @desyncr I don't think reshares are counted as "reactions" at the moment.

**Comment by goobertron** [comment]
> With real reactions I mean comments, that is what a user probably expects when he clicks the reactions button.

I think 'likes' are the biggest waste of time in the entire universe, but even I expect 'reactions' to include all possible ways of reacting to a post, including 'likes'. I don't see anything here that needs fixing.

**Comment by goobertron** [comment]
> I don't think reshares are counted as "reactions" at the moment.

You're right, thanks for pointing this out. While a reshare isn't a 'reaction' in the way that a comment or like is - it's more of an action than a reaction because you're effectively making a 'new' post rather than adding to the existing post - it would make sense for the count shown below a post to include all of the possible actions listed as icons at the right-hand side of the same bar. In which case, we probably need to include the number of reshares and to use a new term there. The term which comes immediately to mind is 'interactions', but I'll think whether I can come up with a better one.

@Flaburgan were you involved in coding this feature? If so, was there a particular reason to include only the numbers of comments and likes, and not the number of reshares?

**Comment by Flaburgan** [comment]
I was not involved. Let's move this discussion on loomio page linked by Makailija to see if we want to redesign the interaction panel on mobile. This issue is not a bug to me and can be closed.

**Comment by desyncr** [comment]
There isn't a technical issue behind this behavior. [Here](https://github.com/diaspora/diaspora/blob/develop/app/helpers/mobile_helper.rb#L33) is where the reaction count is calculated. Adding `post.reshares_count` does indeed work.

**Comment by polsVoice** [comment]
I'm not sure why you'd want a count of "reactions", anyway. I can see the value in knowing the number of likes and knowing the number of comments...but both, together? Likes and comments are so different, mixing the two doesn't make sense to me.

@Makailija Did you open a new issue for this (as you indicated above)?
