### ISSUE TITLE
source option is invalid for gem

### ISSUE THREAD

**Issue by pravi** [diaspora/diaspora#5840]
You passed :source as an option for gem 'rails-assets-diaspora_jsxc', but it is
invalid. Valid options are: group, groups, git, path, name, branch, ref, tag,
require, submodules, platform, platforms, type

This is ruby 2.1.0.1
$ gem --version
2.2.2

Is it a newly introduced option?

**Comment by jhass** [comment]
Update your bundler to 1.9 or later.

**Comment by pravi** [comment]
Thanks, updating bundler from 1.6 to 1.7 fixed the issue.
