### ISSUE TITLE
add stream loading feedback

### ISSUE THREAD

**Issue by kas70** [diaspora/diaspora#5842]
maybe with http://ricostacruz.com/nprogress/

**Comment by jhass** [comment]
I don't think we can do this, it's nothing we can estimate so it would be fake anyway and not any more useful than the current spinner.

If somebody can prove me wrong, please reopen this issue.

**Comment by kas70** [comment]
i think it would be an improvement of the ui, even if it is fake. it would show the user that something is loading (like the spinner did, just in a more beautiful, modern way).
also i don't get the spinner (neither on pod.geraspora (old code) nor on diasp.net (0.5.0.0-...)). this was the reason i thought about this point.

**Comment by jhass** [comment]
Then that's a bug IMO and should be reported as such. Please try to be more precise when doing so.
