### ISSUE TITLE
Auto-Follow-Back broken, when the selected aspect doesn't exist

### ISSUE THREAD

**Issue by SuperTux88** [diaspora/diaspora#5845]
When a user activates the auto-follow-back, and then deletes the selected aspect, and then someone starts sharing with him ... the job fails with "ActiveRecord::AssociationTypeMismatch: Aspect(#75260260) expected, got NilClass(#4716400)" but sends a "xyz started sharing with you." notification. This ends in a huge federation-spam with share-requests.

The auto-follow-back should be disabled, when the aspect doesn't exist anymore.

**Comment by Flaburgan** [comment]
This could be the cause of https://github.com/diaspora/diaspora/issues/2483

**Comment by jhass** [comment]
Good catch!

**Comment by SuperTux88** [comment]
@Flaburgan Yes, this is #2483

On the same Pod the user only gets <number-of-retries> notifications. But with federation, something is multiplying this ... I had > 400k jobs yesterday (before I saw it and cleaned up my queues) ... I don't know how many notification the user gets ;)

**Comment by SuperTux88** [comment]
Maybe we should also create a db-migration, which checks, if all auto-follow-back-aspects exist.
