### ISSUE TITLE
Help text for renaming an aspect is outdated

### ISSUE THREAD

**Issue by jhass** [diaspora/diaspora#5856]
The procedure changed.

**Comment by jhass** [comment]
Related to #5698

**Comment by goobertron** [comment]
I guess if this needs the next-major milestone, then #5698 does as well. I'll happily write new text, if someone will tell me what needs changing.

**Comment by jhass** [comment]
I assigned this to next-major since it has an concrete action point, opposed to some vague "somebody needs to check" in #5698
