### ISSUE TITLE
Alignment of loading-gif with tweets

### ISSUE THREAD

**Issue by Thor77** [diaspora/diaspora#5866]
The alignment of the loading gif is wrong in posts with tweets:
In versions < 0.5 you can see it only in post-view, since 0.5 you can see it in the stream, too.  
Stream
![d-twitter1](https://cloud.githubusercontent.com/assets/4989736/7233301/becf3a66-e780-11e4-984b-2e527508ea9d.png)  
Post-view
![d-twitter2](https://cloud.githubusercontent.com/assets/4989736/7233304/c1d4f28c-e780-11e4-8b0a-de42d538bab3.png)

**Comment by svbergerem** [comment]
It looks like twitter changed the design of the embedded tweets and I'm unable to reproduce this now. @Thor77 can you confirm?

**Comment by Thor77** [comment]
Yep, can confirm.
