### ISSUE TITLE
Fonts look bad in Diasp.org

### ISSUE THREAD

**Issue by teslasmoustache** [diaspora/diaspora#5871]
Still not sure if this is only on my end. I've tried Iceweasel, Midori, and Rekonq. Running Debian Jessie.
![](https://diasp.org/uploads/images/scaled_full_068e570a3829b98e46ca.png)

Can anyone verify?

**Comment by Flaburgan** [comment]
I can see your post without font problem from diasp.org with Firefox 37 under Ubuntu.

**Comment by RichKavanagh** [comment]
I think @teslasmoustache may have this fixed now: https://joindiaspora.co.uk/posts/260718

**Comment by denschub** [comment]
Browser issue, closing.
