### ISSUE TITLE
use user avatars in chat sidebar

### ISSUE THREAD

**Issue by kas70** [diaspora/diaspora#5880]
currently there is a smiley place holder.

**Comment by Flaburgan** [comment]
Please report chat front-end issue on [the corresponding repository](https://github.com/diaspora/jsxc/issues). There should be the users avatar, if it is not there, that means they didn't have the chat activated.

**Comment by kas70** [comment]
ok, sorry.  
i added some contact on diasp.net and there's no avatar, but i'm able to chat with that person.

**Comment by jhass** [comment]
Yes, please open the issue over on the other repo.
