### ISSUE TITLE
mixed content

### ISSUE THREAD

**Issue by igalic** [diaspora/diaspora#5894]
browsers warn that a stream is mixed content. main reason for that is that people can embed images, and those can be http or https or, well, anything a browser will load.

GitHub allows the same thing (here's an image link to http://www.alef.net/ALEFAnimatedGifs/Animals-CatsMoving/HoveringCats.Gif )

![demonstration of an image link: Hovering Cats](http://www.alef.net/ALEFAnimatedGifs/Animals-CatsMoving/HoveringCats.Gif)

but it then localizes said images on their asset servers (in this case: https://camo.githubusercontent.com/700c30eed92704906b7c63428d6b31aa89b0df3a/687474703a2f2f7777772e616c65662e6e65742f414c4546416e696d61746564476966732f416e696d616c732d436174734d6f76696e672f486f766572696e67436174732e476966 )

**Comment by jhass** [comment]
#5386  added Camo support and will be included in 0.5.0.0

**Comment by igalic** [comment]
\o/ thanks!
