### ISSUE TITLE
Repeated crashes with Chrome stable on OS X on joindiaspora.com

### ISSUE THREAD

**Issue by kzurell** [diaspora/diaspora#5895]
Have repeatedly crashed Chrome when loading additional content/infinite scrolling in stream.

To reproduce, 
- open Chrome, 
- open joindiaspora.com/stream, 
- scroll to bottom, and 
- wait. 

Chrome abruptly disappears. Behaviour seems new in past few days.

OS X 10.10.3, Chrome Version 42.0.2311.90 (64-bit)

Have opened an issue with Google: https://code.google.com/p/chromium/issues/detail?id=481387

**Comment by RichKavanagh** [comment]
I can't replicate this on joindiaspora.com or joindiaspora.co.uk

Did you have to use the infinite scroll a few times? Or does it do it on the first attempt to load more stream?

Also on OSX10.10.3 and Chrome 42.0.2311.90 (64-bit)

**Comment by kzurell** [comment]
Often the first infinite scroll, sometimes second or third. 

Display freezes, beach ball, entire app disappears.

Started chrome with --disable-extensions, exact same crash behaviour.

Tried it on both joindiaspora.com and diasp.eu.

The last crash I triggered left an entry in chrome://crashes, which didn't always happen.

**Comment by denschub** [comment]
I fear we're not able to give you any support, I cannot reproduce using 42.0.2311.90 and in tonights nightly. If you have crash reports in `chrome://crashes`, please share them with us. If not, report this issue to the Chrome developer team.

Is this also reproducible in Chromium?

**Comment by kzurell** [comment]
Thanks for looking into this. Good that it's not a general problem.

Will conduct a comprehensive examination when time allows.

**Comment by RichKavanagh** [comment]
@kzurell any luck mate or can this issue be closed now?

**Comment by kzurell** [comment]
Could no longer reproduce with Chrome 43.0.2357.124 and joindiaspora's 0.5.0.0 (or better?)
