### ISSUE TITLE
Bugged "is sharing" indication on the profile page

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#5897]
**Step to reproduce:**
Create two accounts A and B, and make them share together
Go to B profile being logged with A.
B is shown as sharing with you.
Click on the "ignore" action.
B is now shown as not sharing.
Cancel the ignore action
B is still shown as not sharing
Add B back to your aspect
B is still shown as not sharing
Refresh, do whatever you want...

This is because we test the sharing [that way](https://github.com/diaspora/diaspora/blob/develop/app/assets/javascripts/app/models/person.js#L15) in the JS, but [the presenter](https://github.com/diaspora/diaspora/blob/develop/app/presenters/person_presenter.rb#L49) immediately returns if the user is blocked.

**Comment by goobertron** [comment]
This looks like a duplicate (or almost a duplicate) of #4757. I don't blame you for not finding that old issue, but reading yours I'm pretty sure it's the same thing. Thanks for at least tracking down what is causing this anomaly.

**Comment by Flaburgan** [comment]
It is, closing and explaining there.
