### ISSUE TITLE
Issue parsing HTML in OpenGraph previews

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#5898]
I've found an example of an OpenGraph description containing HTML entities, which Diaspora's OG preview displays in a way which is not what (I'm sure) was intended. It is probably bad practice to include HTML entities in OG fields, and this is most likely where the problem lies; but I'm wondering whether, even so, it might be worth coding so that Diaspora presents such descriptions better than it does at the moment.

The example I have found is from http://www.theguardian.com/profile/first-dog-on-the-moon, where the OG description is set as follows:

`<meta property="og:description" content="&lt;p&gt;First Dog on the Moon is Australia&#x27;s only Walkley Award winning marsupial based cartoonist and has done all sorts of things including books, radio, stage shows and a lot of lying down. Find First Dog on Twitter &lt;a href=&quot;https://twitter.com/firstdogonmoon&quot;&gt;@firstdogonmoon&lt;/a&gt;.&lt;/p&gt;&lt;p&gt;Have First Dog cartoons delivered straight to your inbox by &lt;a href=&quot;http://www.theguardian.com/commentisfree/2014/jun/16/-sp-first-dog-on-the-moon-subscribe-by-email&quot;&gt;signing up for the email&lt;/a&gt;.&lt;/p&gt;"/>`

I posted a link to that page in the following post: /posts/4fc747e0cf5f0132039100163e5dbca2

The description appears as follows:

`<p>First Dog on the Moon is Australia's only Walkley Award winning marsupial based cartoonist and has done all sorts of things including books, radio, stage shows and a lot of lying down. Find First Dog on Twitter <a href="https://twitter.com/firstdogonmoon">@firstdogonmoon</a>.</p><p>Have First Dog cartoons delivered straight to your inbox by <a href="http://www.theguardian.com/commentisfree/2014/jun/16/-sp-first-dog-on-the-moon-subscribe-by-email">signing up for the email</a>.</p>`

Now, this is correct behaviour based on what the OG description code is telling a browser to do, but I'm sure it's not the intention of the author, who would have wanted something like this:

I see two options to improve the presentation of OG data in such cases:

1. Strip all HTML codes from OG fields when previewing the information.
2. Attempt to parse HTML entities such as `&lt;p&gt;` as the HTML codes they are intended to produce – in this case, `<p>` – and then parse the HTML generated.

In case 1, the result would be:  
> First Dog on the Moon is Australia's only Walkley Award winning marsupial based cartoonist and has done all sorts of things including books, radio, stage shows and a lot of lying down. Find First Dog on Twitter @firstdogonmoon. Have First Dog cartoons delivered straight to your inbox by signing up for the email.

In case 2, the result would be:  
> <p>First Dog on the Moon is Australia's only Walkley Award winning marsupial based cartoonist and has done all sorts of things including books, radio, stage shows and a lot of lying down. Find First Dog on Twitter <a href="https://twitter.com/firstdogonmoon">@firstdogonmoon</a>.</p><p>Have First Dog cartoons delivered straight to your inbox by <a href="http://www.theguardian.com/commentisfree/2014/jun/16/-sp-first-dog-on-the-moon-subscribe-by-email">signing up for the email</a>.</p>

I realise the problem here is not in Diaspora's code, but wonder whether we can (or even whether we should attempt to) improve the presentation of previews for pages which attempt to include HTML code in their OG fields.

**Comment by jhass** [comment]
I'd say this is a won't fix. People put all sorts of non-spec crap into these tags, we shouldn't make that our issue, it's very clearly theirs.

**Comment by goobertron** [comment]
OK, that's fair enough. Thanks for your quick reply. I thought it was worth pointing it out, although I suspected that might be the outcome. I'll leave it open just for now, in case any other core people want to express an opinion, then I'll close it soon if not (or you can close it).
