### ISSUE TITLE
Standalone Pod and white list

### ISSUE THREAD

**Issue by Proxiweb** [diaspora/diaspora#5899]
Hello,

I need :

A way to configure a standalone pod which can't communicate with other pods.
A way to create a white list of pods the pod is authorized to talk.

Use case : I would like to install a pod for a school / a list of school.

**Comment by jhass** [comment]
No, this goes against Diasporas ideals and core design, see also our FAQ: https://wiki.diasporafoundation.org/FAQ_for_pod_maintainers#Can_I_make_my_pod_private.2Fisolated.2Fnot_communicate_with_other_pods.3F

**Comment by Flaburgan** [comment]
Please note that diaspora* works the same way than e-mail. Imagine you are using Yahoo, you can't explicitly say that you don't want to receive emails from Gmail. If you never communicate your email to someone who is using Gmail though, you will never receive an email from Gmail ;)
