### ISSUE TITLE
Possible 0.5 regression: image not appearing via Markdown

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#5900]
For some reason diaspora-fr.org (running `develop`) won’t display this image when embedded in Markdown: http://www.tomgauld.com/files/tgns01tgcom.jpg

I’ve posted it from diaspora-fr.org, and from pod.orkz.net (`v0.4.1.2`), and whichever pod I post it from, the image displays fine in pods running 0.4.x (I also tested geraspora, diasp.org and jd.com) but not in d-fr.org.

As to other pods running `develop`, the image in the post made from pod.orkz.net displays fine in [iliketoast.net](https://iliketoast.net/posts/3acdf8d0cbda0132038300163e5dbca2), but not on [social.mrzyx.de](https://social.mrzyx.de/posts/3acdf8d0cbda0132038300163e5dbca2) or [nerdpol.ch](https://nerdpol.ch/posts/3acdf8d0cbda0132038300163e5dbca2). I haven't tested any more pods.

I tried another image (http://media-cache-ec0.pinimg.com/736x/2b/ac/52/2bac528dbe7e5afa2519d34b7a0c659d.jpg) as a test, and that displays fine on d-fr.org.

Might be a problem with the site which hosts the image, although I don’t see how that could happen, but anyway I bring it to your attention in case it’s a 0.5 bug. @svbergerem I think you've been working on various related things recently, do you have any idea why this might happen?

(Originally mentioned to Fla on d-fr.org, but he suggested I post it as a bug.)

**Comment by jhass** [comment]
![embed](http://www.tomgauld.com/files/tgns01tgcom.jpg)

```
[jhass@aeshna ~]$ curl -v http://www.tomgauld.com/files/tgns01tgcom.jpg > /dev/null 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 64.29.145.9...
* Connected to www.tomgauld.com (64.29.145.9) port 80 (#0)
> GET /files/tgns01tgcom.jpg HTTP/1.1
> Host: www.tomgauld.com
> User-Agent: curl/7.42.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Connection: close
< Cache-Control: no-cache
< Pragma: no-cache
< Content-Type: text/html; charset=utf-8
< Content-Length: 211
````

As you can see the `Content-Type` is incorrectly set to `text/html`, Camo, rightly so, refuses to proxy URLs with that content type. As you can see it doesn't work here on Github either, as it uses the same technology.

I'm sorry but this is another won't fix.

**Comment by Flaburgan** [comment]
@goobertron so this is not because of the markdown parser but because of camo. But I agree with Jonne, this is not our fault.

**Comment by goobertron** [comment]
@jhass Thanks for the explanation. I agree if something is incorrectly presented in that way (I guess this could make it a possible attack vector?) it shouldn't be proxied.

However, there is an issue here, although a different one: if Camo is not going to allow proxy of an asset, it should not appear in the post preview, which it currently does.

Further, it would be helpful for users, I think, to have a warning displayed when they attempt to preview or to post something containing an asset which Camo won't proxy to the effect: 'This message contains http://www.tomgauld.com/files/tgns01tgcom.jpg, which cannot be displayed.' Otherwise many people will assume either that they have messed up the markdown and keep trying, or think that there is a bug in Diaspora. Is that something you would consider?

If you'll reopen the issue I can change the title and OP to be about the preview anomaly, and we could discuss possible warnings as a separate issue.

**Comment by jhass** [comment]
Don't we already have an issue about requesting a camo-ified URL from the client side? I remember a discussion about that but can't find it.

**Comment by Flaburgan** [comment]
@jhass it's the one open by @SansPseudoFix about markdown links in a code section?

**Comment by Flaburgan** [comment]
Talking about this: https://github.com/diaspora/diaspora/issues/5608

**Comment by jhass** [comment]
Mh, I guess so.
