### ISSUE TITLE
Newly registered user wont see old private posts in his aspect

### ISSUE THREAD

**Issue by dest4131** [diaspora/diaspora#5905]
Here is the phenomenon that looks like a bug to me:
- user A has an aspect "Family" and posts something private to this aspect.
- user B registers to Diaspora
- users A and B follow each other in the aspect "Family"
- user B sees the public posts of user A, but not the private post.

tested with users A and B on the same node with code 0.4.1.2-p5cabd692
kind regards

**Comment by Flaburgan** [comment]
This is the expected behaviour.

**Comment by jhass** [comment]
Yes, this is by design, aspects define the recipients at the time of posting, not at the time of viewing. This is to avoid accidental leak of a private post to an unwanted recipient and makes the federation protocol a lot easier as a side effect.
