### ISSUE TITLE
Diaspora inaccessible with orbot

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora#5906]
Programmers: the scenario.

Mobile phone, display size 65x55 mm android, tor, orbot web browser (images disabled, ecmascript enabled and also disabled no effect).

Black menu bar at top, text links for stream, my activity, etc. all invisible

Unable to toggle from mobile to desk view because right menu inaccessible

See: https://diasp.eu/posts/3079755

**Comment by githubgnulinux** [comment]
In latest diaspora version (https://github.com/diaspora/diaspora/issues/5928), the menu layout in the orweb browser is static in both situations when ecmascript is enabled and disabled. The menu is visible, but the hyperlinks ('stream', 'my activity', etc.) fail and do not load the web pages.

**Comment by Flaburgan** [comment]
The header was rewritten in 0.6, is this issue still valid?

**Comment by githubgnulinux** [comment]
You close without testing?

**Comment by jaywink** [comment]
No one closed this issue, we want to know if it is still valid. Could you as issue reporter test against latest development, for example my pod iliketoast.net?

**Comment by denschub** [comment]
Works for me.
