### ISSUE TITLE
500 error on login after 0.5.0.0 upgrade

### ISSUE THREAD

**Issue by rev138** [diaspora/diaspora#5917]
I just ran through the upgrade, following the instructions. Tailing production.log shows a lot of traffic coming in with 200 responses, but when I try to log in I get a 500 error. The log reports:

```
Started GET "/" for 127.0.0.1 at 2015-05-03 17:15:31 -0400
Processing by HomeController#show as HTML
Completed 500 Internal Server Error in 143ms (ActiveRecord: 15.6ms)

NoMethodError (undefined method exported_photos_file_changed?' for #<User:0x8aa8c90>):
app/controllers/application_controller.rb:84:inset_locale'
lib/rack/chrome_frame.rb:39:in call'
lib/unicorn_killer.rb:35:incall'
```
Please advise!

**Comment by Flaburgan** [comment]
Did you modify this file?

**Comment by rev138** [comment]
"app/controllers/application_controller.rb" I presume? No. I've only ever modified stuff in the 'config' dir.

**Comment by rev138** [comment]
Is that a missing field in my users table? I kind of get the impression it is. Here's what I have now:

+------------------------------------+--------------+------+-----+---------+----------------+
| Field                              | Type         | Null | Key | Default | Extra          |
+------------------------------------+--------------+------+-----+---------+----------------+
| id                                 | int(11)      | NO   | PRI | NULL    | auto_increment |
| username                           | varchar(255) | YES  | UNI | NULL    |                |
| serialized_private_key             | text         | YES  |     | NULL    |                |
| getting_started                    | tinyint(1)   | NO   |     | 1       |                |
| disable_mail                       | tinyint(1)   | NO   |     | 0       |                |
| language                           | varchar(255) | YES  |     | NULL    |                |
| email                              | varchar(255) | NO   | MUL |         |                |
| encrypted_password                 | varchar(255) | NO   |     |         |                |
| invitation_token                   | varchar(60)  | YES  | MUL | NULL    |                |
| invitation_sent_at                 | datetime     | YES  |     | NULL    |                |
| reset_password_token               | varchar(255) | YES  |     | NULL    |                |
| remember_created_at                | datetime     | YES  |     | NULL    |                |
| sign_in_count                      | int(11)      | YES  |     | 0       |                |
| current_sign_in_at                 | datetime     | YES  |     | NULL    |                |
| last_sign_in_at                    | datetime     | YES  |     | NULL    |                |
| current_sign_in_ip                 | varchar(255) | YES  |     | NULL    |                |
| last_sign_in_ip                    | varchar(255) | YES  |     | NULL    |                |
| created_at                         | datetime     | NO   |     | NULL    |                |
| updated_at                         | datetime     | NO   |     | NULL    |                |
| invitation_service                 | varchar(127) | YES  | MUL | NULL    |                |
| invitation_identifier              | varchar(127) | YES  |     | NULL    |                |
| invitation_limit                   | int(11)      | YES  |     | NULL    |                |
| invited_by_id                      | int(11)      | YES  |     | NULL    |                |
| invited_by_type                    | varchar(255) | YES  |     | NULL    |                |
| authentication_token               | varchar(30)  | YES  | UNI | NULL    |                |
| unconfirmed_email                  | varchar(255) | YES  |     | NULL    |                |
| confirm_email_token                | varchar(30)  | YES  |     | NULL    |                |
| locked_at                          | datetime     | YES  |     | NULL    |                |
| show_community_spotlight_in_stream | tinyint(1)   | NO   |     | 1       |                |
| auto_follow_back                   | tinyint(1)   | YES  |     | 0       |                |
| auto_follow_back_aspect_id         | int(11)      | YES  |     | NULL    |                |
| hidden_shareables                  | text         | YES  |     | NULL    |                |
| reset_password_sent_at             | datetime     | YES  |     | NULL    |                |
| last_seen                          | datetime     | YES  |     | NULL    |                |
| remove_after                       | datetime     | YES  |     | NULL    |                |
| export                             | varchar(255) | YES  |     | NULL    |                |
| exported_at                        | datetime     | YES  |     | NULL    |                |
| exporting                          | tinyint(1)   | YES  |     | 0       |                |
| strip_exif                         | tinyint(1)   | YES  |     | 1       |                |
+------------------------------------+--------------+------+-----+---------+----------------+

**Comment by rev138** [comment]
See here: https://github.com/diaspora/diaspora/blob/abc42038408402cab2884b3ee6868523e1b285c5/db/migrate/20150220001357_add_photos_export_to_user.rb

**Comment by jhass** [comment]
Yes, this sounds like a migration failed and later migrations were canceled, I hope you still have the output from `bin/rake db:migrate`.

**Comment by rev138** [comment]
No, but I don't recall it showing any errors. Is there a way to retroactively fix it? Can I just add a column?

**Comment by jhass** [comment]
That would be very bad, you can try rerunning the `db:migrate` step and watch more closely for errors this time.

**Comment by rev138** [comment]
Ok. Early indications look like switching to utf8mb4 in mysql is neither trivial, nor automated by the migration script. I'm working on that now. I'll report back. Thanks.

**Comment by rev138** [comment]
Here's a snippet of the output around where it fails. I'm manually converting the db/tables to utf8mb4 and I'm going to try again.

-- add_index("notifications", ["target_type", "target_id"], {:name=>"index_notifications_on_target_type_and_target_id", :length=>{"target_type"=>190}, :using=>:btree})
   -> 0.3435s
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Database encoding is not utf8mb4!/home/diaspora/diaspora/db/migrate/20150106050733_set_mysql_to_unicode_mb4.rb:17:in `check_config'
/home/diaspora/diaspora/db/migrate/20150106050733_set_mysql_to_unicode_mb4.rb:23:in `change_encoding'
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/activerecord-4.2.1/lib/active_record/migration.rb:417:in `method_missing'
/home/diaspora/diaspora/db/migrate/20150106050733_set_mysql_to_unicode_mb4.rb:8:in `up'
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/activerecord-4.2.1/lib/active_record/migration.rb:569:in `up'
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/activerecord-4.2.1/lib/active_record/migration.rb:609:in `exec_migration'
/home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'

**Comment by jhass** [comment]
No, stop hold on!

**Comment by rev138** [comment]
Well, too late, but I do have a backup :)

What should I do?

**Comment by jhass** [comment]
Reload the page, I updated the comment.

**Comment by rev138** [comment]
No, I definitely did. Here's what the mysql stanza of my database.yml currently looks like:

mysql: &mysql
  adapter: mysql2
  host: "somehost"
  port: 3306
  username: "diaspora"
  password: "**************"
#  socket: /tmp/mysql.sock
  charset: utf8mb4
  collation: utf8mb4_bin

Did I miss something else?

**Comment by jhass** [comment]
>  Replace `charset: utf8` with `encoding: utf8mb4`, notice how the key changed!

**Comment by rev138** [comment]
Bah! ;)

Thank you.

**Comment by rev138** [comment]
Tag this one "pebcak"
