### ISSUE TITLE
bin/rake db:migrate updates diaspora_development, not diaspora_production

### ISSUE THREAD

**Issue by rev138** [diaspora/diaspora#5919]
When running the migrate for 0.5.0.0 I got an error that access was denied to the *diaspora_development* db (because it did not exist). I dumped an loaded *diaspora_production* to *diaspora_development*, ran the migrate, and then reversed the process, which worked, but seems wrong.

I've checked my settings, and I don't see why it would do this. It definitely uses the prod db when the site is running.

**Comment by jhass** [comment]
You skipped step 3 of https://wiki.diasporafoundation.org/Updating

Also see https://wiki.diasporafoundation.org/How_we_communicate

**Comment by rev138** [comment]
3. If you're on PostgreSQL run export DB=postgres RAILS_ENV=production, if you're on MySQL/MariaDB run export DB=mysql RAILS_ENV=production.

Nope. I definitely did that.

**Comment by rev138** [comment]
Ah, balls. I left off the 'export '. I'll shut up now.

**Comment by denschub** [comment]
For future reference: GitHub is not a support tracker. If you have issues, [join our IRC channels](https://wiki.diasporafoundation.org/How_we_communicate), do **not** open issues here.
