### ISSUE TITLE
Facebook crosspost silently fails, access token not removable, connection has no ID

### ISSUE THREAD

**Issue by oya3un** [diaspora/diaspora#5923]
Apologies if this is limited to joindiaspora.com, but apparently its connection to service "Facebook" for posting there via diaspora* is broken. Twitter works, Facebook doesn't (persistently since late last week). Just in case this is because FB blocks everything non-compliant with their API 2.x since last Thursday - has anybody seen this coming?

Unlike before, disconnecting-reconnecting in Settings --> Services doesn't solve the issue. What's different this time is that upon any renewed connection after a disconnect, the corresponding Facebook ID isn't mentioned any longer: the status message says "connected to Facebook as" like it's supposed to when there actually is a connection - but that message used to have an e-mail-address trailing that indicated the FB ID, that's gone now. 

By the way, remove the Facebook service/token altogether and install the whole connection afresh? I'd love to, but the removal feature has ceased to exist...

**Comment by Flaburgan** [comment]
Yeah, the bridge with Facebook is kinda broken... There is several issues already open about it, see https://github.com/diaspora/diaspora/issues/5260 and https://github.com/diaspora/diaspora/issues/5085

**Comment by denschub** [comment]
Closing this. Additional configuration available with 7c0e50c2c270e696b7dbd6540d00b4cc38e25375, additional information regarding this change and issues in #5085. Feel free to reopen if you feel the urge of doing so.

**Comment by Loelo** [comment]
Hi, any hope about this facebook cross-posting working anew ?

**Comment by denschub** [comment]
There is always hope, isn't it?

No, seriously, I see no reason why it should not work...
