### ISSUE TITLE
Diaspora update 0.5.0.1 and Mysql

### ISSUE THREAD

**Issue by dadall** [diaspora/diaspora#5935]
Hey guys,

I tried to update my pod and here is the error I got : 

```
Mysql2::Error: Table 'tags' already exists: CREATE TABLE `tags` (`id` int(11) auto_increment PRIMARY KEY, `name` varchar(255)) ENGINE=InnoDB
```

Any ideas ?

**Comment by Flaburgan** [comment]
@dadall @augierle42 started to upgrade your pod to develop already ;)

**Comment by dadall** [comment]
To develop !?....

**Comment by jhass** [comment]
Uhm, what command does produce that?

**Comment by dadall** [comment]
Here is the command I used :

``
RAILS_ENV=production bin/rake db:migrate
``

And the logs about in production :
``
Migrating to ActsAsTaggableOnMigration (20150507155731)
Mysql2::Error: Table 'tags' already exists: CREATE TABLE `tags` (`id` int(11) auto_increment PRIMARY KEY, `name` varchar(255)) ENGINE=InnoDB
``

And logs in development : 
``
ActiveRecord::SchemaMigration Load (0.2ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
Migrating to ActsAsTaggableOnMigration (20150507155731)
   (0.8ms)  CREATE TABLE `tags` (`id` int(11) auto_increment PRIMARY KEY, `name` varchar(255)) ENGINE=InnoDB
Mysql2::Error: Table 'tags' already exists: CREATE TABLE `tags` (`id` int(11) auto_increment PRIMARY KEY, `name` varchar(255)) ENGINE=InnoDB

``

**Comment by jhass** [comment]
`20150507155731` This sounds like you reran the acts-as-taggable-on migration generator, check `db/migrate` for untracked files.

**Comment by dadall** [comment]
I have this now : 

`` /home/diaspora/.rvm/gems/ruby-2.2.1@diaspora/gems/configurate-0.3.1/lib/configurate/provider/yaml.rb:36:in `block in lookup_path': present is not a valid setting. (Configurate::MissingSetting) ``

I believe it comes form a configuration error but I can't find it :/

**Comment by jhass** [comment]
Fixed that yesterday, please pull again.

**Comment by dadall** [comment]
Thanks, it's back again :)
