### ISSUE TITLE
provide source code for pre built/minified js files

### ISSUE THREAD

**Issue by pravi** [diaspora/diaspora#5939]
The following minified javascript files don't have their corresponding source.

vendor/assets/javascripts/mbp-respond.min.js
vendor/assets/javascripts/mbp-modernizr-custom.js
spec/javascripts/app/views/help_view_spec.js

I will try to generate those files in the meantime.

**Comment by jhass** [comment]
`spec/javascripts/app/views/help_view_spec.js` made me confused about your issue, what's the problem there exactly?

**Comment by pravi** [comment]
I think that is a false positive,     Diaspora.I18n.load({"... is falsely identified as minified.

P: diaspora source: source-contains-prebuilt-javascript-object spec/javascripts/app/views/help_view_spec.js mean line length is about 2697 characters
E: diaspora source: source-is-missing spec/javascripts/app/views/help_view_spec.js

in debian, all binaries should have their corresponding source code and minified javascripts need their corresponding non-minified version and minification should be done at build time.

**Comment by jhass** [comment]
`mbp-respond.min.js` can probably be replaced by `rails-assets-respond`. I traced `mbp-modernizr-custom.js` https://github.com/h5bp/mobile-boilerplate which dropped it with https://github.com/h5bp/mobile-boilerplate/commit/b514efbf36e1c3eb17249a562e134656002e88e0

**Comment by pravi** [comment]
This is a mojor blocker to upload a native diaspora package to debian. Once this is fixed I can upload diaspora package to debian. @jhass can you help fix this?

**Comment by jhass** [comment]
No, I'm focussing on the backend & infrastructure.

**Comment by pravi** [comment]
@Flaburgan would you be able to help with this?

**Comment by cmrd-senya** [comment]
Source code for modernizr lives here: http://modernizr.com/

I suppose it should be packaged to a gem with asset pipeline support before we can replace it in diaspora code.

**Comment by cmrd-senya** [comment]
Ok, file vendor/assets/javascripts/mbp-modernizr-custom.js was introduced in 70ba2651c36cfe22501ba94663587b95142f2b13. The only place, where this module was used was app/views/layouts/application.mobile.haml. Now class Modernizr used nowhere. So probably we can remove this file?

**Comment by jhass** [comment]
https://github.com/diaspora/diaspora/blob/develop/app/assets/javascripts/mobile/mobile.js#L9

**Comment by cmrd-senya** [comment]
> Modernizr runs quickly on page load to detect features; it then creates a JavaScript object with the results, and adds classes to the html element for you to key your CSS on.

Here is class tag added by Modernizr to our page's html tag:  
class=" js flexbox canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients no-cssreflections csstransforms csstransforms3d csstransitions fontface video audio localstorage sessionstorage webworkers applicationcache svg inlinesvg smil svgclippaths"

We shoud then check, if this classes defined somewhere in CSS.

**Comment by cmrd-senya** [comment]
And in #3122 they write:
>We actually want modernizerjs, as it marks up the DOM for our mobile boilerplate style sheet.

**Comment by cmrd-senya** [comment]
If we wipe modernizr and then have successful test runs, would it mean, that it is unnecessary?

**Comment by jhass** [comment]
Doubt it, our testsuite does not run on all kinds of browsers, just one.

**Comment by jhass** [comment]
But again,  I have no actual clue about that, figuring it out is part of solving this issue. The replacing/removing is just half of it.

**Comment by pravi** [comment]
@cmrd-senya while we work on modernizer, can we try and fix respond, which seems more straight forward?

**Comment by cmrd-senya** [comment]
rails-assets-response doesn't seem to exist. Maybe [respond-js-rails](https://github.com/RouL/respond-js-rails) would fit?

**Comment by jhass** [comment]
rails-assets- gems come from https://rails-assets.org/ not https://rubygems.org, so it does exist. But specifically crafted gems are usually to prefer, yes.

**Comment by pravi** [comment]
can we include the non-minified versions alongside the minified files as an interim solution?

**Comment by cmrd-senya** [comment]
Since these scripts are primarely used for old mobile platforms to let them support modern CSS, I will try to setup Android 2.3 emulator in order to test how these scripts affect on rendering. In modern web browsers there should be no difference, if the scripts are removed. After that, I could test some unminified replacements.

**Comment by cmrd-senya** [comment]
I've tested Android Browser 2.3 and it seem to support CSS3 media queries out of the box, so it doesn't need Respond.js. I've also tested IE8 on WinXP and it doesn't support CSS3 media queries, but diaspora is totally broken and unusable on IE8. Looking on [the table](http://caniuse.com/#feat=css-mediaqueries)  I consider that we won't have any significant regressions if we just wipe mbp-respond.min.js.

**Comment by Flaburgan** [comment]
@cmrd-senya we tend to only support modern browsers, so IE9+ and Android 4+

**Comment by cmrd-senya** [comment]
Next, about modernizr.

As it's mentioned [here](http://modernizr.com/docs/#whatis), Modernizr is used mainly in two ways - by using the Modernizr object and by defining the classes which are added in the html tag in our stylesheets. There is no usages of Modernizr object in Diaspora which is shown by a simple grep.

I wrote a regular expression for grep, that searches for usages of the Modernizr defined classes in the stylesheets:
```bash
rgrep --exclude-dir=config --exclude-dir=log --exclude=mbp-modernizr-custom.js --exclude=*.svg --exclude=*.feature --binary-files=without-match -P \\\.\(no-\)\{0,1\}\(\?=flexbox\|canvas\|canvastext\|webgl\|touch\|geolocation\|postmessage\|websqldatabase\|indexeddb\|hashchange\|history\|draganddrop\|websockets\|rgba\|hsla\|multiplebgs\|backgroundsize\|borderimage\|borderradius\|boxshadow\|textshadow\|opacity\|cssanimations\|csscolumns\|cssgradients\|no-cssreflections\|csstransforms\|csstransforms3d\|csstransitions\|fontface\|video\|audio\|localstorage\|sessionstorage\|webworkers\|applicationcache\|inlinesvg\|smil\|svgclippaths\|svg\)
```

As I ran the command in diaspora source tree, I saw that there are no usages of the Modernizr classes in Diaspora source.

So I consider that Modernizr is not used in Diaspora currently and mbp-modernizr-custom.js could be wiped harmlessly.

If nobody minds, I could make a PR removing these files.

**Comment by pravi** [comment]
@cmrd-senya, thanks a lot for working on this and fixing it.
