### ISSUE TITLE
set UUID.state_file mode to 0666

### ISSUE THREAD

**Issue by pravi** [diaspora/diaspora#5940]
Can we set the UUID state file mode more permissively?

See https://github.com/assaf/uuid/issues/45 for a discussion

**Comment by jhass** [comment]
Which processes do you need to share the state file with? Why aren't they run in the same way and in a way that they have access to a common home?

**Comment by pravi** [comment]
I use 'sudo -u diaspora' to run as diaspora user which will try to fall back to /root/.ruby-uuid when /tmp/ruby-uuid can't be accessed. /tmp/ruby-uuid was already created when I build the package (tests shipped with the gem will creates /tmp/ruby-uuid as another user). This may be an isolated case, but the issue will come up if any other app on the system tries to use ruby-uuid. For now I fall back to /tmp/ruby-uuid-uid instead of ~/.ruby-uuid.

**Comment by jhass** [comment]
Shouldn't you run with `sudo -iu diaspora` to properly set `$HOME` etc?

**Comment by jhass** [comment]
There's also:
>      -H, --set-home
                 Request that the security policy set the HOME environment variable to the home directory specified by the target user's password database entry.
                 Depending on the policy, this may be the default behavior.

**Comment by pravi** [comment]
But ruby-uuid is using ~, and not $HOME.

@state_file = File.expand_path('.ruby-uuid', '~')

**Comment by jhass** [comment]
```
[29] pry(main)> ENV["HOME"]
=> "/home/jhass"
[30] pry(main)> File.expand_path("~")
=> "/home/jhass"
[31] pry(main)> ENV["HOME"] = "/a/b/c"
=> "/a/b/c"
[32] pry(main)> File.expand_path("~")                                                                                                                                     
=> "/a/b/c"

**Comment by pravi** [comment]
I had to pass -E to pass RAILS_ENV and DB variables, so $HOME was also passed. I think adding -H will fix the issue. -i will not work as shell is set to /bin/false.

pravi@savannah:/opt$ sudo -E -u diaspora pry
/usr/lib/ruby/vendor_ruby/pry/pry_class.rb:81:in `realpath': Permission denied @ realpath_rec - /home/pravi/.pryrc (Errno::EACCES)
	from /usr/lib/ruby/vendor_ruby/pry/pry_class.rb:81:in `realpath'
	from /usr/lib/ruby/vendor_ruby/pry/pry_class.rb:81:in `real_path_to'
	from /usr/lib/ruby/vendor_ruby/pry/pry_class.rb:76:in `block in rc_files_to_load'
	from /usr/lib/ruby/vendor_ruby/pry/pry_class.rb:76:in `map'
	from /usr/lib/ruby/vendor_ruby/pry/pry_class.rb:76:in `rc_files_to_load'
	from /usr/lib/ruby/vendor_ruby/pry/pry_class.rb:64:in `load_rc_files'
	from /usr/lib/ruby/vendor_ruby/pry/pry_class.rb:126:in `initial_session_setup'
	from /usr/lib/ruby/vendor_ruby/pry/cli.rb:206:in `block in <top (required)>'
	from /usr/lib/ruby/vendor_ruby/pry/cli.rb:83:in `call'
	from /usr/lib/ruby/vendor_ruby/pry/cli.rb:83:in `block in parse_options'
	from /usr/lib/ruby/vendor_ruby/pry/cli.rb:83:in `each'
	from /usr/lib/ruby/vendor_ruby/pry/cli.rb:83:in `parse_options'
	from /usr/bin/pry:16:in `<main>'
pravi@savannah:/opt$ sudo -H -E -u diaspora pry
[1] pry(main)> File.expand_path("~")  
=> "/usr/share/diaspora"
[2] pry(main)>

**Comment by denschub** [comment]
> I think adding -H will fix the issue.

Since this issue was dead for a while, I guess that your issue is resolved.
