### ISSUE TITLE
Notification count says zero

### ISSUE THREAD

**Issue by balasankarc** [diaspora/diaspora#5942]
I don't know how, but I got the notification count displaying zero. See attachment.

This was what happened:
I was navigating to the post (to check if any activity happened. Notifications doesn't reach me always. Maybe a federation issue). 
While the page was loading, some guy commented on the post.
So, when I reached that post, an activity had happened. But, I couldn't understand why that caused a "0" notification count.

![diaspora-notification](https://cloud.githubusercontent.com/assets/2379271/7548817/64062c72-f638-11e4-8257-b8826d9f67b1.png)

**Comment by svbergerem** [comment]
You found that bug in v0.4.1.2. Are you able to reproduce this with v0.5.0.1? The code for the notifications has been more or less rewritten between those two versions.

**Comment by balasankarc** [comment]
Ok. Let me update poddery to latest version and get back to you (Even though I have no idea how to reproduce it). For the time being, I am closing this bug. Will reopen this if it happens on 0.5.0.1.
