### ISSUE TITLE
 Routes.notifications is not a function

### ISSUE THREAD

**Issue by rivendale2010** [diaspora/diaspora#5944]
The notification drop-down displays the spinner but never loads. Console reads 

`Uncaught TypeError: Routes.notifications is not a function
app.views.NotificationDropdown.app.views.Base.extend.getNotifications @ main-88c3ba4ae793a289c42da54e520a3a62.js:21
`

develop branch, May 10, Code 0.5.99.0-p5e5b475f

**Comment by svbergerem** [comment]
Try `bin/rake tmp:cache:clear`.

**Comment by rivendale2010** [comment]
thanks, that seems to have done it, i do already run 
 "RAILS_ENV=production bundle exec rake tmp:cache:clear assets:precompile"
in my script so i thought this cache had been clear, but apparently not... :)
