### ISSUE TITLE
public/tmp/ dirty image clean up

### ISSUE THREAD

**Issue by dmorley** [diaspora/diaspora#5946]
Images that are really code renamed as images are left in the public/tmp upload area after the system rejects them. Found a bunch when I was investigating an odd http call (unrelated it turns out). 
https://gist.github.com/dmorley/bfbe6c13f7570ebfbe63

**Comment by Flaburgan** [comment]
Yeah I have more than 14GB of images in public/uploads/tmp, this looks like a bug to me.

**Comment by jhass** [comment]
We probably should just schedule a daily job that does http://www.rubydoc.info/gems/carrierwave/CarrierWave/Uploader/Cache/ClassMethods:clean_cached_files!

**Comment by Flaburgan** [comment]
So I had 15655 files in public/uploads/tmp and 146816 in uploads/images.
I launched `CarrierWave.clean_cached_files!` in a Rails console and my uploads/tmp folder is now empty. Everything looks fine when visiting diaspora*, photos on profile page, etc.

**Comment by cmrd-senya** [comment]
Please review my commit before I make pull request.

**Comment by jhass** [comment]
Looks fine.

**Comment by cmrd-senya** [comment]
Should be closed as solved.
