### ISSUE TITLE
Sidekiq fail on Heroku

### ISSUE THREAD

**Issue by roymckenzie** [diaspora/diaspora#5947]
Sorry to come here for this issue, but I was not receiving any support on IRC and this place seems to get more traffic and is less ephemeral.

I am running the latest master and things are running smoothly save for Sidekiq on Heroku. Every time I try to start the process or Heroku starts it through the Procfile I get this error:

```
No such file or directory - 
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/logger.rb:601:in `initialize'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/logger.rb:601:in `open'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/logger.rb:601:in `create_logfile'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/logger.rb:596:in `open_logfile'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/logger.rb:551:in `initialize'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/logger.rb:318:in `new'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/logger.rb:318:in `initialize'
/app/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.3.3/lib/sidekiq/logging.rb:31:in `new'
/app/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.3.3/lib/sidekiq/logging.rb:31:in `initialize_logger'
/app/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.3.3/lib/sidekiq/cli.rb:344:in `initialize_logger'
/app/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.3.3/lib/sidekiq/cli.rb:39:in `parse'
/app/vendor/bundle/ruby/2.0.0/gems/sidekiq-3.3.3/bin/sidekiq:7:in `<top (required)>'
/app/vendor/bundle/ruby/2.0.0/bin/sidekiq:23:in `load'
/app/vendor/bundle/ruby/2.0.0/bin/sidekiq:23:in `<main>'
```

My Procfile is untouched from the master branch Procfile.

Thanks for any advice you can offer.

**Comment by roymckenzie** [comment]
OK so I found a "solution though it may be a hack. I had a guess that there was a problem creating the `sidekiq.log` file so I commented out line 4 in the `sidekiq.yml` file:

`# :logfile: "<%= AppConfig.sidekiq_log unless AppConfig.heroku? %>"`

And things seem to be working now. Might be a bug?

**Comment by jhass** [comment]
Maybe https://github.com/diaspora/diaspora/commit/138551112b7e78037f498fbaa8a8429200534991 fixed it?

**Comment by roymckenzie** [comment]
@jhass I tried implementing that, but still received the same error. Went back to commenting out that `sidekiq.yml` line.

**Comment by jhass** [comment]
Well, I welcome a patch fixing it for Heroku while retaining the functionality for regular deployments.
