### ISSUE TITLE
Chat sidebar not showing up

### ISSUE THREAD

**Issue by nicolasrpmaia** [diaspora/diaspora#5952]
My pod (DiasporaBR) has recently been updated to the 0.5 version, and even though I opted to allow contacts to chat with me, the gray chat sidebar is nowhere to be found.

I am using Abrowser (Firefox derivative) on Trisquel GNU/Linux 7.0. I have tried to clear cache and cookies, have reset with addons disabled and hit hard refresh (Ctrl+F5) and no sign of it working.

**Comment by Flaburgan** [comment]
The chat repository is diaspora/jsxc (front-end) or diaspora/vines (back-end). You should open an issue there. Though your problem looks really weird. Are you the podmin?

**Comment by nicolasrpmaia** [comment]
I'm not. Which of these repositories would you recommend me?

**Comment by Flaburgan** [comment]
jsxc, this looks like a front-end problem. Are you sure the chat is activated on your pod? I guess yes if you were able to turn chat on for some aspects on the /contacts page.

**Comment by nicolasrpmaia** [comment]
Yes, other users in DiasporaBR reported being able to use the chat normally. Thanks, I'll leave a note on jsxc.

**Comment by Flaburgan** [comment]
You are sure you don't have a grey small frame with a white arrow on left side of the stream page?

**Comment by jhass** [comment]
Closing in favor of https://github.com/diaspora/jsxc/issues/101
