### ISSUE TITLE
YouTube embedding is broken

### ISSUE THREAD

**Issue by polsVoice** [diaspora/diaspora#5959]
When I post a bare link to a YouTube video, there's no preview. I've reloaded the page several times, and it still doesn't show up. It just shows the link. I tested this in both Firefox 38 and Chromium 41.0.2272.76 Ubuntu 15.04 (64-bit).

**Comment by goobertron** [comment]
I've just tested three pods (including joindiaspora.com) on two browsers (including FF37), and the embedded preview appears as it should in each case.

**Comment by polsVoice** [comment]
This is on diasp.org.

**Comment by dmorley** [comment]
I just embeded https://www.youtube.com/watch?v=jQeCMGPs9dQ at with no issues. Can you share the youtube URL you were using to try?

**Comment by dmorley** [comment]
@ https://diasp.org/posts/4425620

**Comment by polsVoice** [comment]
The two posts are
https://diasp.org/posts/4423120 with video URI https://www.youtube.com/watch?v=oEek5PzbCf0
and
https://diasp.org/posts/4381426 with video URI https://www.youtube.com/watch?v=J4GW_fTezRA

**Comment by dmorley** [comment]
Sorry I think its you somehow, I posted both with success. and even copied the text from your posts exactly and pasted and both embedded with no issue. We are on the same OS and browsers. Maybe you are somehow blocking some code with a addon? privacy one some how.

**Comment by polsVoice** [comment]
@dmorley I'm really confused. Your video works, and now the first video works when I re-post it. The second one still doesn't show on re-post, though.

**Comment by dmorley** [comment]
There is/was a embed bug with any video with a _ in the name, I bet this bug is back or never got fixed.

**Comment by polsVoice** [comment]
@dmorley That was my first thought, too. That's the only difference I can see here.

**Comment by jhass** [comment]
http://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=J4GW_fTezRA

I don't think we can do anything about that.

**Comment by polsVoice** [comment]
According to Google, YouTube allows users to turn off embedding, so I guess that's what's happening here.

**Comment by jhass** [comment]
If anybody finds anything we can do about this, please open a new issue.
