### ISSUE TITLE
Implement RFC 7033 Webfinger

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#5963]
As voted on https://www.loomio.org/d/gfBaSiAE/implement-rfc7033-webfinger we should improve our webfinger implementation. @SuperTux88 I saw you were touching things like that recently, would you want to have a look?
##

**Comment by denschub** [comment]
We should not **update** our existing implementation, we have to add new methods. Our implementation needs to be backwards compatible.

**Comment by Flaburgan** [comment]
Thanks Dennis I edited the issue :) Feel free to edit my post when I make mistakes ;)

**Comment by Flaburgan** [comment]
For the record, https://github.com/diaspora/diaspora/pull/6310 is now merged.

**Comment by SuperTux88** [comment]
this is still the old webfinger. I have not implemented the RFC-webfinger yet. But it is prepared to add it :)

**Comment by yookoala** [comment]
Let's make a checklist for [RFC7033 Webfinger](https://tools.ietf.org/html/rfc7033) compatible implementation in case someone wants to work on it. From what I can see:

- [Section 4. Webfinger Protocol](https://tools.ietf.org/html/rfc7033#section-4)
  - [ ] The path component of a WebFinger URI MUST be the well-known path "`/.well-known/webfinger`".

  - [ ] A WebFinger URI MUST contain a query component that encodes the query target and optional link relation types as specified in [Section 4.1](https://tools.ietf.org/html/rfc7033#section-4.1).

- [Section 4.1. Constructing the Query Component of the Request URI
](https://tools.ietf.org/html/rfc7033#section-4.1)
  - [ ] A WebFinger client issues a query using the GET method to the well-
   known [[3](https://tools.ietf.org/html/rfc7033#ref-3)] "`resource`" identified by the URI whose path component is "`/.well-known/webfinger`" and whose query component MUST include the "`resource`" parameter exactly once and set to the value of the URI for which information is being sought.

  - [ ] If the "`resource`" parameter is absent or malformed, the WebFinger resource MUST indicate that the request is bad as per [Section 10.4.1 of RFC 2616](https://tools.ietf.org/html/rfc2616#section-10.4.1) [[2](https://tools.ietf.org/html/rfc7033#ref-2)].

**Comment by cmrd-senya** [comment]
So now this feature has been merged in `diaspora_federation`, so after merging #7436 this will be fixed.

**Comment by SuperTux88** [comment]
Diaspora now provides RFC 7033 webfinger (#7436), but I keep this issue open, because we don't query it yet.

**Comment by SuperTux88** [comment]
Closed via #7625
