### ISSUE TITLE
when a mentioned user's profile is not known, request profile

### ISSUE THREAD

**Issue by pravi** [diaspora/diaspora#5972]
Currently when a user is mentioned (especially #newhere posts), other pods won't see a link to the profile. I think a pod should request profile of a user it doesn't know if when it processes a post with @mention in it.

**Comment by Flaburgan** [comment]
I completely agree and thought I already opened an issue about that.

**Comment by pavi** [comment]
I faced the same issue.

**Comment by jhass** [comment]
Duplicate of #4491
