### ISSUE TITLE
Tags not highlighted

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora#5981]
See https://diasp.eu/posts/3158993

**Comment by jhass** [comment]
Looks like the backend correctly parses and associates them.

@svbergerem upstream bug or issue in the frontend regexp?

**Comment by svbergerem** [comment]
According to the commonmark spec those hashtags belong to an HTML block and are considered as raw HTML: http://spec.commonmark.org/0.19/#html-blocks

markdown-it-sanitizer escapes some of the HTML tags but it doesn't add new markup like hashtags or mentions (or anything else). If you want to see some markup after an HTML block you need to end that HTML block with an empty line.

 Btw. our backend also has some false positives like
```markdown
[markdown #hashtag tag](https://diasporafoundation.org)
```
or
```markdown
<a href="https://diasporafoundation.org">HTML #hashtag tag</a>
```

**Comment by svbergerem** [comment]
This is still compliant with the current CommonMark spec: http://spec.commonmark.org/0.23/#html-blocks

If you want to use HTML tags in your posts then please make sure that you follow the CommonMark spec. We even have a preview so you can check if everything was ok.
