### ISSUE TITLE
<hr> color in Markdown should be styled

### ISSUE THREAD

**Issue by abimelex** [diaspora/diaspora#5987]
The `<hr>` element in  class `markdown-content` has currently `border-top: 1px solid #eee;` inherited from bootstrap styling.
So the horizontal line is almost invisible, I would suggest to give it a more strong color, either like border color or text color, since horizontal line is actually text element in markdown content.

**Comment by EdzeronK** [comment]
a track : 

in `app/assets/stylesheets/bootstrap-complete.scss`,  line 2: 

 @import 'bootstrap';
 
the problem is in a gem 'bootstrap' ?

**Comment by jhass** [comment]
There's no problem, the issue simply asks for a prettier override for those used in posts.
