### ISSUE TITLE
Public posts fail full dissemination

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora#5993]
https://diasp.eu/posts/3171268

**Comment by jhass** [comment]
I doubt this is a generic issue.

Which pods are involved?

**Comment by githubgnulinux** [comment]
You should be able to replicate by choosing by random yourself two pods to test the scenario described.

**Comment by jhass** [comment]
I can't. Feel free to reopen once you can provide information to reliably reproduce your issue.

**Comment by githubgnulinux** [comment]
Create two accounts in two different pods

Add each account as a contact (e.g. Your account 1 on pod A is a contact on pod B; your account 2 on pod B is a contact on pod A)

Make a public post in account 1, pod A

The post is not visible in the list of posts for contact in pod B

**Comment by jhass** [comment]
I could imagine as much, the keyword here is *reliably*.
