### ISSUE TITLE
[0.6-dev] 500 when liking a post with the mobile version with JS disabled

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#5995]
```
[2015-05-27T09:14:23] INFO  PID-29696 TID-104756943240 Rails: Started GET "/posts/1287484/likes" for X.X.X.X at 2015-05-27 09:14:23 +0200
[2015-05-27T09:14:23] INFO  PID-29696 TID-104756943240 ActionController::Base: Processing by LikesController#index as HTML
[2015-05-27T09:14:23] INFO  PID-29696 TID-104756943240 ActionController::Base:   Parameters: {"post_id"=>"1287484"}
[2015-05-27T09:14:23] INFO  PID-29696 TID-104756943240 ActionController::Base: Completed 500 Internal Server Error in 14ms (ActiveRecord: 1.9ms)
[2015-05-27T09:14:23] FATAL PID-29696 TID-104756943240 Rails: 
ActionView::MissingTemplate (Missing template likes/index, application/index with {:locale=>[:fr, :en], :formats=>[:mobile], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :markerb, :haml]}. Searched in:
  * "/home/diaspora/diaspora/app/views"
  * "/home/diaspora/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rails_admin-0.6.7/app/views"
  * "/home/diaspora/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/kaminari-0.16.3/app/views"
  * "/home/diaspora/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/entypo-rails-2.2.3/app/views"
  * "/home/diaspora/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/devise-3.4.1/app/views"
):
  app/controllers/likes_controller.rb:48:in `block (2 levels) in index'
  app/controllers/likes_controller.rb:47:in `index'
  lib/rack/chrome_frame.rb:39:in `call'
  lib/unicorn_killer.rb:35:in `call'
```

I had this error launching the mobile first and tapping on the heart to like on the first post of the stream. After the 500, I go back, tried to like another post, and everything went fine. Then, I retried to like the first post, and everything went fine. Now I don't success to reproduce, but I wanted to post the stack trace just in case it's enough for someone to patch it.

**Comment by uniquefine** [comment]
I had a similar Problem on my mobile Phone this morning, it vanished when I activated Js in my browser and apeared again when I turned it of. Here are some Screenshots
![screenshot_2015-06-01-08-38-28](https://cloud.githubusercontent.com/assets/12694730/7911249/4b05b950-088e-11e5-9803-9a11a278e436.png)
![screenshot_2015-06-01-08-38-04](https://cloud.githubusercontent.com/assets/12694730/7911250/4b108592-088e-11e5-9a4c-8247974fb999.png)
![screenshot_2015-06-01-08-37-31](https://cloud.githubusercontent.com/assets/12694730/7911251/4b13ad12-088e-11e5-99b1-2580d4f56cf2.png)
