### ISSUE TITLE
Remove public posts from aspects stream

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora#5996]
https://diasp.eu/posts/3084394

**Comment by jhass** [comment]
I'm not sure if the added complexity is worth it here, too many options and possibilities make a UI hard to use.

**Comment by Ravenbird** [comment]
Hm whats about some tabs for the stream. Or is this to complicate for normal users?

**Comment by githubgnulinux** [comment]
>  Ravenbird:

No tabs please. A simple option 'no public posts' in 'my aspects' list would be sufficient

**Comment by githubgnulinux** [comment]
Loomio nonsense not required! See https://diasp.eu/posts/3507202#2de65b3035f2013340355404a6b20780

Discussions about diaspora should be in...diaspora!

**Comment by svbergerem** [comment]
> Loomio nonsense not required! [...] Discussions about diaspora should be in...diaspora!

Yeah right. None of the posts you linked arrived on my pod and I am glad that not all posts from all users on all pods are in the database of my small pod. However, this means that fair discussions and decisions about diaspora* (which should be binding) are not possible in diaspora* itself. This is why we use Loomio.

@jhass already explained why he thinks that this issue needs to be discussed on Loomio before an implementation could be merged. If there is no one who cares enough about this issue to discuss it on Loomio we can just close it.
