### ISSUE TITLE
Historic search function using external search engine

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora#5997]
https://diasp.eu/posts/3158993

**Comment by jhass** [comment]
Encouraging indexing by a third party is most certainly a very controversial idea.

**Comment by githubgnulinux** [comment]
The internal index is poor!

**Comment by svbergerem** [comment]
I think that we should improve the internal search function (we have several issues about that) but I disagree with the proposed feature. If you really think that we should use third party search engines please propose that on loomio. Otherwise you can close this issue.

**Comment by svbergerem** [comment]
Will close this now. Feel free to reopen once there is an accepted proposal on Loomio.
