### ISSUE TITLE
can't add tags on /profile/edit

### ISSUE THREAD

**Issue by haheute** [diaspora/diaspora#6006]
I can not add tags on my user profile on despora.de . When I try to add 2 tags, they do not appear. Chromium inspect tool gives an error (i tried to add '# cats' and ' # music' (without the whitespace)):

```
Uncaught SyntaxError: Invalid regular expression: /,#c++,/: Nothing to repeat
processData @ main-703de67a15baa288baa2a5aad19f48d9.js:24813
(anonymous function) @ main-703de67a15baa288baa2a5aad19f48d9.js:24779
fire @ jquery-fbac370b179359a49ece68f5e52545e1.js:3120
self.fireWith @ jquery-fbac370b179359a49ece68f5e52545e1.js:3232
done @ jquery-fbac370b179359a49ece68f5e52545e1.js:9276
send.callback @ jquery-fbac370b179359a49ece68f5e52545e1.js:9686
```
##

**Comment by svbergerem** [comment]
This sounds like a bug in jquery.autoSuggest.

**Comment by Flaburgan** [comment]
>Invalid regular expression: /,#c++,/

`#c++` is not a valid tag in diaspora*. I tried too add it with both Firefox and Chromium and it fall back to #c which is, I suppose, the expected behavior. So closing.
