### ISSUE TITLE
Thumbnails in right bar should lead to associated posts in the stream instead of people's page

### ISSUE THREAD

**Issue by Globulle** [diaspora/diaspora#6008]
The thumbnails at the top of the right bar are convenient to see in one glance who is present in our current stream. When you click on it, you get the profile of the person, which may not to be the expected behaviour (you presumably want to see what the person has posted, not his whole activity). Furthermore, being sent to the profile page of the person takes time since a new page has to be loaded, and you need to go back to the stream view after it.

In accordance with the "Stream" heading above this area, I think it should be better to remain in the stream view and simply get a focus on the related post. This should be smoother and lighter.

**Comment by svbergerem** [comment]
I don't think that those thumbnails are useful and would propose to drop them from all stream pages.

**Comment by Globulle** [comment]
I think they bring some life and colour to the page which would be very austere otherwise. They provide also a synthetic summary of recent activity. These are 2 good reasons to keep them in my opinion.    
But I agree, they have no clear function, that's why I suggest to use them as stream navigation shortcuts.
