### ISSUE TITLE
broken chronological order of posts in my activity stream

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora#6010]
With latest version of diaspora, posts do not appear in consistent reverse chronological order.

First (top) post appears with a time-stamp 3 months ago
Second post appears with a time-stamp 20 hours ago
Third post appears with a time-stamp 4 days ago.

**Comment by svbergerem** [comment]
In the activity stream posts were never ordered by the creation of the post but by the timestamp of the last interaction.

**Comment by githubgnulinux** [comment]
OK. Just checked the time-stamps of the last post of each thread
Top (first) post, 7 months, latest comment 2 hours
Second post, 1 month, latest comment 27 days
Third post, 3 days, no comments

**Comment by svbergerem** [comment]
It's not only comments. The posts are ordered by last activity, so last comment / like / reshare and AFAIK even deleted comments.
