### ISSUE TITLE
Deactivate autofollow if like a post

### ISSUE THREAD

**Issue by elektrollart** [diaspora/diaspora#6018]
I see a problem in the auto follow function, if someone likes a post. Users like less posts, cause they don't want to follow the comments in this posts and if they want only to like the post, they need four clicks to cancel the auto follow. It looks like, we don't need a like button, cause we have the follow button. I think it is better to change it back, like it was before 0.5. I see it on my own usage. Every time I want to like a post, I think "better not, cause I get all the notifications, I'm not interested." If I want to see the comments, I press the follow button or comment it.

**Comment by Flaburgan** [comment]
You can unfollow with only one click. This action button is not well placed for sure...

**Comment by elektrollart** [comment]
![Uploading Bildschirmfoto von »2015-05-31 18-33-05«.png…]()

Nope, first I must refresh the stream or open the spv, than I can change the follow stuff, than I must close or go back. This are 4 clicks for one like-only.

**Comment by elektrollart** [comment]
:o woa... fu... didn't want to close xD

**Comment by jhass** [comment]
I'm going to reopen #5881 since that has more discussion history.
