### ISSUE TITLE
Hovercard avatar deformed

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/diaspora#6039]
![](https://cloud.githubusercontent.com/assets/3429231/7902351/75019fe4-07b7-11e5-95fb-362f7c593fde.png)
##

**Comment by Flaburgan** [comment]
So, I checked that issue quickly. The difference between the avatar displayed next to comments for example and the one in the hovercard is the source image. The first one is the `small` image when in the hovercard, the `medium` one is used. The `small` image is always 50px width and 50px height, it is truncated sever side. The `medium` one is resized to have the width or the height at max at 100px, but keep its proportion. So if the original avatar is 150x300 for example, the medium image used by the hovercard will be 50x100. However, the height and width of the image is then fixed to 70px with CSS, resulting in a deformed image.

So, what do we want to do?
- Create a new type of image (70x70) as images already take a lot of disk space -> Nope
- Using the small (50x50) image with a 70x70 size results in a bad quality image -> Nope
- Using the small (50x50) image with a 50x50 size in the hovercard is not really useful, as that's already the image which is displayed elsewhere -> Nope
- We should keep using the medium image, so we will have an image with 100px max for either the height, or the width.
  - We can remove the CSS resize, for heigth, for width, or for both. It works (it is not ugly) but that means the hovercard size now depends of the size of the avatar, so hovercards size is not consistent across the application. Is that a problem?
  - If we find a way to load the image from CSS as a background image, then keeping the 70x70 size and using `background-size: cover;` will result to what's actually done for small images server-side: truncate the part of the image which is not in the 70x70. Is the "if" solvable? cc @svbergerem

**Comment by SuperTux88** [comment]
This issue will be solved with #7581 (at least for new avatars).

**Comment by Flaburgan** [comment]
Hm, I'm not sure we should force user to upload avatar with a 1:1 ratio, it can look very nice on the profile page. In any case, we still have to deal with old avatars ;)

**Comment by Fensterbank** [comment]
We don't **force the user to upload** an avatar with 1:1 ratio. The user can upload whatever he wants, even a 16:10 gigapixel photo. Afterwards the cropper is used to get a nice, resized 1:1 avatar.
It is therefore not more difficult for the user.

And yes, I think we should enforce that every avatar has the same ratio, this would solve many issues and it's standard everywhere.

PS: I know my pull request is already quite old. It will definiteley be finished during 34C3, so stay tuned. 🎊
