### ISSUE TITLE
Image URL recognition failure

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora#6056]
See https://diasp.eu/posts/3206920 and compare to subsequent post with local image copy uploaded to diaspora pod (https://diasp.eu/posts/3206923)

**Comment by jhass** [comment]
The source code of your post is
```json
"<h2>Plans and realities</h2>\r\n<p>Caught via another network...</p>\r\n<p>http://www.wordsonimages.com/pics/161789-Your+plan+vs+reality.jpg</p>\r\n\r\n#plan #reality #imperfection #humour #personal"
```

That's not how image embedding works. See https://diasporafoundation.org/formatting

**Comment by svbergerem** [comment]
And the URL is not rendered as a link because it is part of an HTML block and CommonMark (the markdown spec we are using) doesn't support mixing HTML and markdown.

**Comment by githubgnulinux** [comment]
Why does the source code of the original post successfully show the link to a html web page (e.g. https://diasp.eu/posts/3208484)? The expected behaviour would be a small view of the image, then the user activates the hyperlink to view the image in full size.

**Comment by jhass** [comment]
That's the OpenGraph preview feature, the target site needs to support it. URL extraction for that is performed completely distinct from client side post rendering.

**Comment by githubgnulinux** [comment]
Learned something new! THanks :)
