### ISSUE TITLE
Strange line-break in tags

### ISSUE THREAD

**Issue by abimelex** [diaspora/diaspora#6058]
Sometimes some tags have a linebreak in the middle of the word without any reason?!
When I remove the `word-break: break-all;` from the `a.tag` everything is fine. 

Environment: Chromium Version 41.0.2272.76 Built on Ubuntu 14.04, running on LinuxMint 17.1 (64-bit)

Example: 
<img src="http://666kb.com/i/cz80jrb9qrdj5yb76.gif" title="hosted by 666kb.com"/>
##

**Comment by Flaburgan** [comment]
Could you please give us the url of that post, if it is public?

**Comment by svbergerem** [comment]
I am not able to reproduce this using Chromium and different screen sizes.
(43.0.2357.130 Built on Debian stretch/sid, running on Debian stretch/sid (64-bit))

I agree with Flaburgan: the URL of the post would be really helpful.

**Comment by abimelex** [comment]
I'm still able to reproduce it in Chrome (Version 44.0.2403.130 (64-bit)) and Chromium Version 43.0.2357.130 Built on Ubuntu 14.04, running on LinuxMint 17.1 (64-bit).

Maybe it's also connected to the font? If I set a mono space font to the tags it renders also proper.

**Comment by svbergerem** [comment]
Firefox 39 (Arch Linux)
![ff39](https://cloud.githubusercontent.com/assets/3798614/9125142/d9ae1434-3c9d-11e5-9452-846565a9b5bd.png)

Chromium Version 44.0.2403.130 (64-bit) (Arch Linux)
![chromium](https://cloud.githubusercontent.com/assets/3798614/9125161/fc6ee110-3c9d-11e5-9a77-6df09632a229.png)

**Comment by jaywink** [comment]
Checked Firefox 41.0a2, Chromium 43.0.2357.130 and Ubuntu browser (webkit based I think) - all render fine.

Ubuntu 14.04.

**Comment by svbergerem** [comment]
Is anyone still able to reproduce this weird bug?

**Comment by abimelex** [comment]
I guess it was some strange combination of custom system fonts settings and browser font settings.  If nobody is able to reproduce it, this can probably be closed.
