### ISSUE TITLE
Translation broken in the aspect creation modal

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#6061]
![](https://cloud.githubusercontent.com/assets/3429231/7973135/bb43bfa8-0a52-11e5-85d6-e808df5cf037.png)

Step to reproduce:
* Go on someone's profile
* Click on the aspect dropdown in the top right of his profile
* Click on "Create an aspect"
The modal displayed is not translated.

**Comment by svbergerem** [comment]
I have no idea how and when we fixed this, but we did. I'm not able to reproduce the bug on the contacts page, on a profile page from the aspect dropdown or from the aspects stream page.

![german new aspect modal](https://cloud.githubusercontent.com/assets/3798614/8390878/2eafa6e6-1caa-11e5-8b9e-f9ee4962c457.png)
