### ISSUE TITLE
Add links to the empty stream message

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#6062]
When the stream is empty, it displays "you could search or invite contacts".
"search" should link to the search page and "invite contacts" to the invite modal (the same than in the left side bar of the /contacts page)

**Comment by giniouxe** [comment]
Hi. I'd like to work on this one if it's OK.

**Comment by jhass** [comment]
@giniouxe of course it's ok ;)

**Comment by Flaburgan** [comment]
@giniouxe I started to work on this but will not have time to finish it soon, feel free to base your work on this branch: https://github.com/Flaburgan/diaspora/commit/e72399128a2a0f76e172995faf13e21308203aea

**Comment by giniouxe** [comment]
ok :)

A little question though : I can't run a `bundle install` since I updated the develop branch : I got an `There is an error in your Gemfile` message. Any idea of a recent change that may cause this problem?

**Comment by jhass** [comment]
Make sure your Bundler version is 1.10.0 or later.

**Comment by giniouxe** [comment]
@jhass That was the problem, thanks.

**Comment by giniouxe** [comment]
https://github.com/diaspora/diaspora/pull/6189

One question though : is it user friendly to link to a search page where the is no actual search field, and, since you did'nt actually search anything by clicking, you're welcomed by a message saying you should actually search for something to get some results ?

**Comment by jhass** [comment]
Yeah, maybe don't link the search page, it should be obvious enough that you can search in the header.

**Comment by giniouxe** [comment]
OK

**Comment by marienfressinaud** [comment]
I started to continue on this in another branch https://github.com/marienfressinaud/diaspora/tree/6062-add-search-and-invte-links-when-no-contacts

Feel free to use my work if you want to continue yourself :)
