### ISSUE TITLE
ZWNJ character getting removed from posts and comments

### ISSUE THREAD

**Issue by balasankarc** [diaspora/diaspora#6067]
Hi,
The  ZWNJ character (character code U+200C in Unicode) is getting scrapped off in posts and comments. Tested in poddery.com, running latest stable version of Diaspora. 

This character is used in many languages, like Malayalam, to prevent two glyphs from forming a conjunct. So, for proper rendering of these languages, ZWNJ character is a must.

**Comment by jhass** [comment]
Could you have something to copy paste so we can try to reproduce elsewhere? What database is podddery.com using these days? In the case of MySQL/MariaDB, does it use utf8mb4 already? Is it lost in the database already or only when rendering the post? Is it lost in the post preview?

Please try to include as much information as possible in your bug reports.

**Comment by balasankarc** [comment]
@jhass  
Sorry for not adding details, didn't know what all to mention.

* poddery.com is using MySQL. 
* Running v0.5.0.1
* It has `encoding: utf8mb4` in  config/database.yml
* ZWNJ is not lost during post preview, but only after posting.
* Example:

ള +‌്   => ള്
ള + ്  + ZWNJ => ള്‍

So, in [this](https://poddery.com/posts/1835730) post, I had actually posted the second one, but somehow it became the first one.

**Comment by balasankarc** [comment]
This happens also in sechat.org . I just checked.

**Comment by jhass** [comment]
Looks like an issue in post processing:
```
irb(main):008:0> Post.find(475578).text.bytes                                                                                                                             
=> [224, 180, 179, 224, 181, 141, 226, 128, 141]
irb(main):009:0> Post.find(475578).message.plain_text_for_json.bytes
=> [224, 180, 179, 224, 181, 141]
```

**Comment by jhass** [comment]
Regression from 6a5a407e49eb1ef07a116c0aa899338a20c1aca4

**Comment by balasankarc** [comment]
Thanks for the quick response. :)
