### ISSUE TITLE
recent notifications - cannot mark read/unread notifications

### ISSUE THREAD

**Issue by ita1024** [diaspora/diaspora#6075]
With diaspora 0.5.0.1 in Firefox 38, desktop version (no problem in the mobile version), the links in the dropdown are broken:
* "Mark all as read" has no effect
* "Mark read" / "Mark unread" on a single comment has no effect

On the notification page accessed from "view all", the eyes to mark single comments as read/unread are also broken. The link https://server/notifications/read_all seems to work though.

The same problems are observed in Chromium 41.

**Comment by svbergerem** [comment]
I'm not able to reproduce this. Is there anything in the error console?

**Comment by ita1024** [comment]
It seems that there is:
PUT https://server/notifications/121 net::ERR_EMPTY_RESPONSE
send
it.extend.ajax
app.views.Notifications.Backbone.View.extend.setUnreadStatus
app.views.Notifications.Backbone.View.extend.setRead
(anonymous function)
it.extend.each
it.fn.it.each
app.views.Notifications.Backbone.View.extend.MarkAllRead
it.event.dispatch
g.handle

If i try to access that link directly i am getting a 404 error.


In the server logs I only see my manual requests though:
Started GET "/notifications/115" for 127.0.0.1 at 2015-06-07 17:08:07 +0200
ActionController::RoutingError (No route matches [GET] "/notifications/115"):
  lib/rack/chrome_frame.rb:39:in `call'
  lib/unicorn_killer.rb:35:in `call'

**Comment by ita1024** [comment]
This one is my fault. I have a firewall that filters PUT requests.

Sorry for the noise :-)
