### ISSUE TITLE
allow adding xmpp only contacts to aspects

### ISSUE THREAD

**Issue by pravi** [diaspora/diaspora#6089]
When chat is enabled, allow adding xmpp only contacts so it shows up in xmpp clients.  As second step, contacts added via xmpp clients could be added to aspects.

**Comment by jhass** [comment]
Duplicate of https://github.com/diaspora/vines/issues/10

**Comment by pravi** [comment]
I think it would be good to show such contacts in aspects and be able to modify them via the web interface.

**Comment by jhass** [comment]
I think I disagree, aspects should stay the management tool for your streams primarily.

**Comment by pravi** [comment]
Should we setup a vote on loomio?

**Comment by jhass** [comment]
If you care that much about it....

**Comment by pravi** [comment]
created a loomio vote https://www.loomio.org/d/UPWolQ8z/allow-managing-non-diaspora-xmpp-contacts-via-diaspora-aspects
