### ISSUE TITLE
Incorrect wording / functionality of the More button in Mobile view

### ISSUE THREAD

**Issue by RichKavanagh** [diaspora/diaspora#6093]
The introduction of v0.5.0.0 seems to have brought a new issue in with regards to the wording and/or functionality of the More button in Mobile view.

Steps to reproduce:

1. Switch to mobile view
2. Head over to something like */tags/exmachina* and you’ll see a small number of posts
3. At the bottom, where the 'More' button usually appears, you'll see a button saying, “There are no posts yet.”

Well, there *are* posts there...

![1](https://cloud.githubusercontent.com/assets/2150079/8126875/76a07c76-10ea-11e5-8c3c-090a87a10303.png)

**Comment by RichKavanagh** [comment]
This bug / issue also appears when viewing the profile of a user that does not have many posts.

Eg. https://joindiaspora.co.uk/people/fb34e860f4340132924f692f19e1a711

The same 'There are no posts yet.' button / wording appears, but there clearly *are* posts.

**Comment by jaywink** [comment]
Confirmed on 0.5.1.0-RC @ iliketoast.net

**Comment by RichKavanagh** [comment]
I've pinged @Faldrian ;)

**Comment by Faldrian** [comment]
Jajaja... I'm on my way and will have a look now... -.- ;)

**Comment by RichKavanagh** [comment]
Lol :) Thank you my friend :)
