### ISSUE TITLE
javascript issue freezes the whole browser

### ISSUE THREAD

**Issue by Label-papin** [diaspora/diaspora#6096]
I've searched about this issue, but couldn't find it. I posted this in diaspora and some users reported the same issue, intermitently, as is with me.

It seems to freeze the whole browser when loading new stream content.
Freezes for around 10 seconds, then Iceweasel prompts:

> A Script on this page may be busy, or it may have stopped responding. You can stop the script now, or you can continue to see if the script will complete.
> 
> Script: https://wk3.org/assets/main-12931230650816041485c6266df2b39f.js:137 

Even if I tick the "Don't ask me again", it repeats right after the first freeze, around 5 to 10 times, then stops freezing, until it happens again loading new stream. 

I don't know if it's the same numbers in the middle, but it always ends in ".js:137".

I'm running Iceweasel 36.1 in LMDE 2 on a Macbook A1181, in wk3.org, with NoScript addon 2.6.9.

**Comment by pizzamaker** [comment]
Same issue while running Abrowser 38 and Firefox 38.

**Comment by jhass** [comment]
These usually are caused by some issue while parsing some post, until we got that post (= a way to reproduce), it's impossible to debug this.

**Comment by Flaburgan** [comment]
It is really, really probable that this freeze is caused by the chat. Is it activated on your pod?

**Comment by pizzamaker** [comment]
The chat indeed freezes a lot, but in my case I disabled WebRTC so the chat doesn't even load.

I'm getting extreme lag while trying to open, for example, /tags/aaronswartz

**Comment by svbergerem** [comment]
@jhass wk3.org is still running version 0.4.1.2, so even if the browser freezes while parsing some post, the current version will behave completely different.

@pizzamaker I was able to open https://wk3.org/tags/aaronswartz with iceweasel 38.0.1 without any issues.

**Comment by pizzamaker** [comment]
@Label-papin These tweaks made my experience nearly perfect: https://www.reddit.com/r/linux/comments/39q6xt/some_useful_firefox_tips_to_fix_choppy_scrolling/

**Comment by goobertron** [comment]
> wk3.org is still running version 0.4.1.2, so even if the browser freezes while parsing some post, the current version will behave completely different.

I had this on pod-orkz.net for a while shortly after the upgrade to 0.5.0.0, so it's not related only to old code. Whether it's a software or server issue I can't say. I even thought it was possibly something to do with my computer or browser. I haven't experienced if for the past few days.

**Comment by Label-papin** [comment]
I don't think this is related to the browser, as some people has the same issue happening, and, if I get this right, with the same patterns. This seems to be a bad js script. 

Thanks for the link, pizzamaker!

**Comment by svbergerem** [comment]
@goobertron All I was trying to say is that if the browser freezes while parsing a post then we need a post that freezes the browser for d* version 0.5.1.0 or later. Since version 0.5.0.0 we use a completely different markdown renderer and with version 0.5.1.0 we fixed a bug that froze the browser.

**Comment by goobertron** [comment]
Thanks, Steffen. I assumed that the major change was implemented in 0.4 -> 0.5. Apologies. As I say, I haven't experienced it for a few days, which probably coincides with the ugrade to 0.5.1.0 on pod.orkz.net.

**Comment by Label-papin** [comment]
Wk3 upgraded! :) The issue is no longer there, it appears. No way to measure it again in previous versions. If anybody else has this issue too, this thread continues.

**Comment by jhass** [comment]
Alright, if anybody can (reliably) reproduce, please open a new issue.
