### ISSUE TITLE
Port to sandstorm.io

### ISSUE THREAD

**Issue by waldyrious** [diaspora/diaspora#6108]
[Sandstorm](http://sandstorm.io) is an open-source platform that allows one to run their own server and easily install web apps like GitLab, Etherpad, TinyTinyRSS, [and many more](https://sandstorm.io/apps/). They've been trying to port Diaspora for a while but recently [put it in the backburner](https://groups.google.com/d/topic/sandstorm-dev/4IKuo_Y4ZjY/discussion) due to difficulties in getting it to work properly.

I assume they have been in contact with diaspora devs, but in any case it's useful to have a public issue tracking this. /cc @jparyani

**Comment by jhass** [comment]
I'm not aware of any contact, and I'm also not sure what you expect to happen from our side, could you elaborate?

**Comment by waldyrious** [comment]
I hope at least some communication will emerge if it hasn't already happened (which seems to be the case). I assume it might be of the interest of the Diaspora project to eventually be [installable through Sandstorm](https://github.com/sandstorm-io/sandstorm/wiki/Packaging-Guide), so Jason's feedback about what has made it difficult to port so far may lead to relevant insights from the Diaspora team, and hopefully even collaboration in making both projects compatible. At the very least, it should provide information for anyone who might want to take a stab at this in the future.

**Comment by jhass** [comment]
I think you should suggest sandstorm to contact us, not the other way around.

This is our issue tracker for accepted feature requests, bug reports and other tasks related to the codebase, please see [How we communicate](https://wiki.diasporafoundation.org/How_we_communicate).

**Comment by waldyrious** [comment]
Fair enough. I've already pinged @jparyani on this thread, so I'll let him take the actions he might deem appropriate from the Sandstorm side.
