### ISSUE TITLE
user export - posts, comments - missing guid

### ISSUE THREAD

**Issue by redmatrix** [diaspora/diaspora#6115]
The guid isn't currently provided for posts and comments in the json export file. This makes it very difficult (if not impossible) to avoid duplicated content and "confused conversations" when importing.

[Comment dates would also be a "nice to have" so that the original times could be preserved by an importing process. Even though this isn't available in the protocol I'm assuming the arrival time is recorded in the DB, since it appears to be available to the stream.]

**Comment by Flaburgan** [comment]
Yeah the comment dates have to be saved, see https://github.com/diaspora/diaspora/issues/4269 and https://github.com/diaspora/diaspora/pull/4935

**Comment by redmatrix** [comment]
Would be nice if the timestamps federated, but I'm asking for something much simpler - putting whatever timestamp you have into the export data for comments. But the guid is much more important and I can provide a separate issue about including comment timestamps, even though it should only take a couple minutes to add all of them, and since there aren't any import clients currently and this would be upward compatible, there aren't any compatibility issues to worry about.

**Comment by Realtin** [comment]
Hey, @zaziemo and I will work on this.
* providing guid for comments and posts in the export file.

**Comment by Flaburgan** [comment]
#6185 is merged, this can probably be closed.
