### ISSUE TITLE
Terms of service design broken

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#6121]
The port to bootstrap 3 broke the ToS page which now uses the full width. It only misses a lg8 somewhere.

**Comment by svbergerem** [comment]
The ToS page has `col-md-8 col-md-offset-2` and looks good on my dev pod.

**Comment by Flaburgan** [comment]
Hm... My bad. Here is what I have: https://diaspora-fr.org/terms 
Because I modified the terms page with https://github.com/Flaburgan/diaspora/commit/d588e39c01ff1df2533c52e7a3f533ac623c3849, when it has been introduced. At this time the default file had a very minimalist structure. So that means that the layout has to be done in the overridden file now. Is that what we want?

**Comment by svbergerem** [comment]
I think podmins who modified the page should be able to apply their changes to the new page. This would imply that we mention the changes in the changelog. @Flaburgan do you agree?

**Comment by Flaburgan** [comment]
Yeah no problem, I like to be free :)

**Comment by Flaburgan** [comment]
https://github.com/diaspora/diaspora/pull/6122
