### ISSUE TITLE
Tree dots in an url are parsed to one dot and a ellipsis? Weird!

### ISSUE THREAD

**Issue by DeusFigendi** [diaspora/diaspora#6125]
…or something similar…

pretty strange, I found this bug [here](https://pod.geraspora.de/posts/e7268ef0f947013213e44860008dbc6c), the json says the author typed in `http://www.taz.de/Was-fehlt-.../!5205173/` (minus dot dot dot slash) and it was parsed to `http://www.taz.de/Was-fehlt-.…/!5205173/` (minus dot ellipsis slash) that is strange because that are four dots XD.

And **that** was interpreted like [http://www.taz.de/Was-fehlt-.](http://www.taz.de/Was-fehlt-.)…/!5205173/ instead of http://www.taz.de/Was-fehlt-.…/!5205173/ (GitHub does it right) and I'd say ellipsis (…) is allowed in urls (not sure if in domains).

My own try:

````
http://example.org/foo...bar/

http://example.org/foo....bar/

http://example.org/foo…bar/
````

becomes:

http://example.org/foo…bar/

[http://example.org/foo](http://example.org/foo)…bar/

http://example.org/foo…bar/

**Comment by svbergerem** [comment]
This has been fixed with markdown-it 4.2.2 which will be included in the next release.
