### ISSUE TITLE
Images do not work in mentions anymore.

### ISSUE THREAD

**Issue by DeusFigendi** [diaspora/diaspora#6127]
Again: Maybe this is not a bug but intended:

Once I wrote a little helper-script that generates markup/content like `@{ ![username](/useravatar) Username ; users@handle.pod}` and it did fine and generated a mention including the users avatar.

Nowadays this fails.

**Example code**

````
@{ Mention ; mention@user.pod} works

@{ ![Mention](https://pod.geraspora.de/uploads/images/thumb_small_f8685f65408911c93928.png)  Mention ; mention@user.pod} doesn't work
````

Like I said: Maybe it's intended so I have to change the script to `![username](/useravatar) @{Username ; users@handle.pod}` but I could not find any "spec" or something how a mention should look alike so I don't know how a valid mention looks and how an invalid mention looks like.

**Comment by svbergerem** [comment]
Mentions are parsed after all markdown inline rules so mentions must not contain any markdown code.

**Comment by DeusFigendi** [comment]
Ah okay, well once it worked ;D

So the mention-parser-thingy "sees" something like `@{<img alt="username" src="/useravatar" /> ; users@handle.pod}` and `<img alt="username" src="/useravatar" />` is no valid username **or** it "sees" a DOM-Tree and not a string (since it's done clientside)!?

Anyway

> mentions must not contain any markdown code

is kinda "spec" how mentions may look like :-)

**Comment by svbergerem** [comment]
markdown-it uses a list of tokens to parse markdown code and the mention plugin only parses those tokens that are inline text tokens. The texts that the plugin parser "sees" are in your example `@{` and ` ; users@handle.pod}`.

**Comment by DeusFigendi** [comment]
Erm I guess this one can be closed as `no issue` cause @svbergerem wrote

> mentions must not contain any markdown code.

And that means it works as it should doesn't it?

**Comment by svbergerem** [comment]
Thanks, you are right.
