### ISSUE TITLE
Autocomplete position bug

### ISSUE THREAD

**Issue by SansPseudoFix** [diaspora/diaspora#6133]
When I scroll, and I want to search somebody, I have this issue:

![bug-search-bar](https://cloud.githubusercontent.com/assets/6507951/8281596/d4d2e598-18e9-11e5-8f1f-a3d9185004f5.png)

Iceweasel 31.7.0 - Debian Jessie. Related to #6130.

**Comment by svbergerem** [comment]
Has #6130 been merged on your pod?

**Comment by SansPseudoFix** [comment]
Yes. On diaspora-fr.org. Version:  0.5.99.0-p0c6957cb.
