### ISSUE TITLE
Regression: overflow on #tag pages

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#6142]
Have just noticed that on `develop`, the '5 tags' row in the left-hand column overflows the stream:

![_fr](https://cloud.githubusercontent.com/assets/2530168/8391790/6d9ba298-1cc7-11e5-913a-3c95ee3f6cf2.jpg)

(diaspora-fr.org, 0.5.99.0-p0c6957cb)

compare with:

![_orkz](https://cloud.githubusercontent.com/assets/2530168/8391796/83f9d5aa-1cc7-11e5-9649-df5f02d77067.jpg)

(pod.orkz.net, 0.5.1.1-p56df5978)

**Comment by svbergerem** [comment]
This is closely related to https://github.com/twbs/bootstrap/issues/15958 which is a won't fix for Bootstrap 3.

**Comment by SansPseudoFix** [comment]
What about something like that:

Large screen

![capture d ecran de 2015-09-11 17 08 38](https://cloud.githubusercontent.com/assets/6507951/9818415/b48ba30c-58a8-11e5-83bc-3d704b45ae0a.png)

Smaller screen

![capture d ecran de 2015-09-11 17 09 14](https://cloud.githubusercontent.com/assets/6507951/9818416/b48f0e48-58a8-11e5-9ba0-bc6ebec9973f.png)

PR is ready, but I want to be sure this way is okay.

**Comment by svbergerem** [comment]
> I want to be sure this way is okay.

Yes. I'd like to keep `text-overflow: ellipsis` and `white-space: nowrap` but I guess that's not possible with Bootstrap 3.
