### ISSUE TITLE
404 error page Tom is missing

### ISSUE THREAD

**Issue by Zauberstuhl** [diaspora/diaspora#6145]
![](https://pod.tchncs.de/uploads/images/scaled_full_60a007293d8c2faa5308.png)
since [e7d0a978bad4ae403dbbfc5b142e51ee6d80a930](https://github.com/diaspora/diaspora/commit/e7d0a978bad4ae403dbbfc5b142e51ee6d80a930) Tom died ([error_pages.scss#L37](https://github.com/diaspora/diaspora/blob/develop/app/assets/stylesheets/error_pages.scss#L37))
There is something wrong with the CSS, if you remove `postion:fixed` from `error_404` Tom will rise again!

[original post](https://sechat.org/posts/4ee33940ff9801321b0b00163cfa796c#575adc90ffba0132e98014dae9b624ce)

**Comment by Haidy777** [comment]
Should be doable as my first contribution to diaspora.

**Comment by Zauberstuhl** [comment]
I have no idea about CSS and how my solution would work on multiple browser ... but still I want to throw some code into the pot:

replace `position:fixed;` with `background-attachment:fixed;` and at least in firefox it'll be the old 404 page.

lgl

**Comment by Flaburgan** [comment]
The CSS is dirty, I can clean it when I'll be back from vacations.

**Comment by Haidy777** [comment]
@Zauberstuhl That would also fix the problem of Tom, but the "html"-Tag would be still a very small height (sometimes even zero Pixel).
Which isn't a problem in most cases, but I think mobile Safari does sometimes strange things.
(Well, mobile safari does always strange things. ;) )
