### ISSUE TITLE
Remove account with forgotten mail/password

### ISSUE THREAD

**Issue by ItachiSan** [diaspora/diaspora#6148]
As I say in title.

Actually, I had a Diaspora account on a pod (http://joindiaspora.com) and it was associated with my old email, now dead and not avaible.
As for now, I would like to delete that old account to free its username and to delete everything that was posted by me (it was about 2/3 years ago...?).
Is that possible? Because I couldn't see such an option. :/

This should not be a just-dummy issue, in my opinion.

**Comment by jhass** [comment]
If you still know the password you can login and change the email in your account settings. If you forgot your password please contact your podmin by writing a mail to maxwell@joindiaspora.com.
