### ISSUE TITLE
/tags pages are slow

### ISSUE THREAD

**Issue by prellele** [diaspora/diaspora#6152]
Loading of tag pages takes up to 45 secounds. This seems to be an issue since 0.5.0.0.
Maybe a mysql only issue.

Post regarding this isssue: https://social.mrzyx.de/posts/79584d30f4ea0132c47000259069449e

Running version: 0.5.1.1 
DB: mysql Ver 5.5.43-0
OS: Debian 8.1

**Comment by RichKavanagh** [comment]
Approx 10 seconds to load on my pod, running diaspora0.5.1.2 and mysql5.5.43

**Comment by jaywink** [comment]
Seems to be a problem on diasp.org too - @diasporg, do you run MySQL?

We really need someone who knows something about MySQL to look into this as it is killing some pods..

**Comment by prellele** [comment]
@jaywink Diasp.org is runnig MySQL
> Updated pod. Does not look like using #tags got fixed, still takes 45-60 seconds to pull up a tag query :(
https://diasp.org/posts/79584d30f4ea0132c47000259069449e

**Comment by prellele** [comment]
MariaDB is also not affected by this

**Comment by dmorley** [comment]
Turns out this is from the ORDER BY at the end. Odd because it has an index for created_at so it should not make the query 95% slower but it does.

**Comment by Flaburgan** [comment]
I'd like to work on this, @ruxton can you tell me how you generated posts when fixing https://github.com/diaspora/diaspora/pull/4769 ?

**Comment by cmrd-senya** [comment]
A quick web search shows that it is likely a well known problem with mysql:
>The point is exactly because it has joins that it probably can't use that index. MySQL can use one index per table in a join (unless it qualifies for an index-merge optimization). If the primary key is already used for the join, thedatetime won't be used. In order to use it, you need to create a multi-column index on the join key + thedatetime index, in the correct order.
[source](http://stackoverflow.com/questions/4013301/mysql-datetime-index-is-not-working)

**Comment by cmrd-senya** [comment]
I generated test data and have
```
> StatusMessage.count
 => 333540 
> ActsAsTaggableOn::Tag.count
 => 257 
> ActsAsTaggableOn::Tagging.count
 => 333538 
> ShareVisibility.count
 => 227108 
```

This is roughly how I generated data:
```ruby
(1..56000).each { [alice,bob,eve].each {|u| u.post :status_message, text: "##{SecureRandom.hex(1)}" , public: true; u.post :status_message, text: "##{SecureRandom.hex(1)}", to: u.aspects.first}}
```

With that data the tags page load take from 2.5 to 7 seconds.
