### ISSUE TITLE
Reshare icon has a "retweet" class and is removed by AdblockPlus

### ISSUE THREAD

**Issue by shmerl** [diaspora/diaspora#6156]
It's a problem that appears in the single post view.

It's not a bug strictly speaking, but why should that class be called "retweet" to begin with? Diaspora isn't Twitter. The class should better be renamed to "reshare".

**Comment by svbergerem** [comment]
We use that class because Entypo suggests to use that class: https://github.com/lwe/entypo-rails/blob/master/app/assets/stylesheets/entypo.scss.erb#L143. I'd say this is a `won't fix`.

**Comment by shmerl** [comment]
Can it be fixed upstream? It's a generic thing, so it shouldn't be called "retweet". I can submit a bug there.

**Comment by jaywink** [comment]
I've tagged this as upstream and I'd vote to keep it open for tracking - @shmerl maybe post your bug report here, thanks.

**Comment by shmerl** [comment]
Submitted the bug [here](https://github.com/lwe/entypo-rails/issues/17).

**Comment by shmerl** [comment]
Developers created a "reshare" alias which can be used instead of "retweet". It's available in entypo-rails 3.0.0.pre.rc2.

**Comment by shmerl** [comment]
What version of Diaspora will this fix be available in? Joindiaspora still has this issue.

**Comment by denschub** [comment]
This fix will be released with 0.6.0.0.

**Comment by shmerl** [comment]
Thanks!

**Comment by shmerl** [comment]
Looks like it's working fine now on Joindiaspora pod.
