### ISSUE TITLE
Missing facebox assets since 0.5.1.0 update

### ISSUE THREAD

**Issue by tferreira** [diaspora/diaspora#6159]
Hello,

Since the 0.5.1.0RC update, I've found many HTTP 404 on my nginx access log : 

```"GET /assets/facebox/closelabel-23e1e49536abca87bcb290e290491a1b.png HTTP/1.1" 404 419 "https://diaspora.psyco.fr/stream" ```

```"GET /assets/facebox/loading-0185d82caf8a3509956f78485336119a.gif HTTP/1.1" 404 419 "https://diaspora.psyco.fr/stream"```

These errors occur when displaying the feed page.
This is also happening in other diaspora pods (I've tried on diasp.org).

By the way, these assets exists on the public folder : 

`user@server ~/diaspora/public/assets/facebox (master *) $ ls -al`
`-rw-r--r--  1 desktop desktop   168 déc.  13  2014 closelabel-3ff358873d688c110fffe5ee3caa443f.png`
`-rw-r--r--  1 desktop desktop   168 déc.  13  2014 closelabel-c1477cf7e12a835267a5be4aedda936d.png`
`-rw-r--r--  1 desktop desktop   168 déc.  13  2014 closelabel.png`
`-rw-r--r--  1 desktop desktop  2767 avril  5 21:50 loading-3fe0669c091325c261f267cc267a431c.gif`
`-rwxr-xr-x  1 desktop desktop  2767 déc.  13  2014 loading-a297497bfa40d2c5dfa8b8408d497bef.gif*`

**Comment by jhass** [comment]
Mmh, does it help if you rerun `assets:precompile` and restart diaspora?

**Comment by SuperTux88** [comment]
This was fixed with #6105 (0.5.2.0) and #6106 (0.6.0.0)

**Comment by jhass** [comment]
Uh, d'oh, shows my memory.

**Comment by tferreira** [comment]
Oh, thanks, good news! :+1:
