### ISSUE TITLE
all tags are empty in joindiaspora

### ISSUE THREAD

**Issue by johand** [diaspora/diaspora#6163]
all tags in joindiaspora are empty after the update to 0.5.1.2 even if you publish something in any tag

![tag_activity](https://cloud.githubusercontent.com/assets/1388644/8506055/d6852510-21ca-11e5-9fc2-4361c1e9e4a4.png)

**Comment by svbergerem** [comment]
This might be related to #6152.

**Comment by maxwell** [comment]
confirmed related to #6152  The queries are timing out.

**Comment by jhass** [comment]
Closing as a duplicate then.
