### ISSUE TITLE
translate email tooltip in sign up form

### ISSUE THREAD

**Issue by zaziemo** [diaspora/diaspora#6176]
currently the description text in the email tooltip in sign up form is not translated into german but says
"Your email will never be seen by other users."

**Comment by zaziemo** [comment]
@Realtin and I will fix this issue

**Comment by svbergerem** [comment]
@zaziemo It looks like that string has already been translated to German: https://webtranslateit.com/en/projects/3020-Diaspora/locales/en..de/strings/8585328

This will likely be part of the next release since @jhass updates the translations.

**Comment by zaziemo** [comment]
Ok, @svbergerem thanks for the info :)
