### ISSUE TITLE
User edit pages now too wide (BS3)

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#6178]
The new settings pages bases on Bootstrap 3 are in too wide a div (it stretches up to 1180px before resizing to a more narrow div for even larger screens).

![_settings](https://cloud.githubusercontent.com/assets/2530168/8593749/7189a106-2632-11e5-8e8b-9d6418c9d043.png)

I'm afraid I find this really ugly visually, and also ungainly to use, as you have to move the cursor (via mouse, trackpad, whatever) from extreme left to extreme right and back. I much prefer the layout of the previous settings page:

![_settings_old](https://cloud.githubusercontent.com/assets/2530168/8602343/c81393d8-2669-11e5-8a56-fbd1d4a590f8.png)

I understand that there are issues with some languages which have longer strings on average than English, and so perhaps a little more space is needed for text - but surely not this much. I hope we can find a compromise which allows enough space for the text required while keeping a neat, attractive and usable design.

**Comment by AugierLe42e** [comment]
Fits well on 1920px

![screen shot 2015-07-09 at 20 39 17](https://cloud.githubusercontent.com/assets/3429231/8603692/2f1affde-267a-11e5-8482-10cda61d3524.png)

**Comment by goobertron** [comment]
Yeh, @AugierLe42e, as I said in my previous post, when the screen gets up to approx 1180px, the content-width reduces to a fixed width.

**Comment by svbergerem** [comment]
Fixed by #6675.
