### ISSUE TITLE
Notiifcations number not consistent with unread notifications

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#6181]
I've noticed that when I open a page by clicking on a notification and then click the browser's 'back' button, while the new notifications dropdown is updated (showing the notification you just clicked as read), the notification badge in the header still shows the previous number, as though that notification just clicked was in fact unread.

This is still the case on the new Bootstrap header from #6109.

**Comment by AugierLe42e** [comment]
There's already an open bug : #5780. This basically would be solved finishing the refactor started with #5707 and #5761 and use a model for notifications client side.

**Comment by goobertron** [comment]
OK sorry, I did have a look but didn't find.
