### ISSUE TITLE
Users are able to select services in the publisher that are no longer supported

### ISSUE THREAD

**Issue by ronnicek** [diaspora/diaspora#6184]
Hi,

I linked facebook a long time ago with diaspora*. I would like to unlink it, but it´s not possible and I cannot see it in https://joindiaspora.com/services to "disconnect it".
##

**Comment by svbergerem** [comment]
joindiaspora doesn't support connections to facebook anymore: https://joindiaspora.com/statistics

**Comment by ronnicek** [comment]
I know, but I would like to disconnect that if it´s not supported anymore.. I still have that as option if I am writing a post.

**Comment by svbergerem** [comment]
Alright, this sounds like a bug.
