### ISSUE TITLE
jump to comment position if you click on a notification-link (... also commented on...)

### ISSUE THREAD

**Issue by kas70** [diaspora/diaspora#6186]
this is a feature-request.
could be done like on loom.io.

**Comment by Flaburgan** [comment]
I mentioned this idea on https://github.com/diaspora/diaspora/issues/4425

**Comment by jaywink** [comment]
Any object to closing #4425 in favour of leaving this specific issue open?

**Comment by jhass** [comment]
#4425 still has an open point, the comments are pretty much irrelevant to its scope.

**Comment by svbergerem** [comment]
This is a duplicate of #5203.
