### ISSUE TITLE
add a section about using xmpp chat in help

### ISSUE THREAD

**Issue by pravi** [diaspora/diaspora#6202]
And link to it from chat sidebar.

**Comment by jhass** [comment]
#5665 already added a help section for the chat.

**Comment by pravi** [comment]
can this be linked from the right side chat box? Currently it has "Mute" and "Hide offline contacts" options next to Online. Adding a "Help" menu there would be good.

**Comment by jhass** [comment]
That would need to be done at diaspora/jsxc
