### ISSUE TITLE
add a section about using external clients

### ISSUE THREAD

**Issue by pravi** [diaspora/diaspora#6203]
This was discussed, but it seems not implemented
https://github.com/diaspora/diaspora/pull/5665#issuecomment-75933183

It may also be a good idea to link to a dedicated campaign page like otr.works (I'm part of the team that runs the campaign, I feel its better to collaborate) or we could also create a similar section ourselves.
##

**Comment by SuperTux88** [comment]
The chat was removed with #8069, this is obsolete now.
