### ISSUE TITLE
Public stats on if XMPP is enabled on a pod

### ISSUE THREAD

**Issue by pavi** [diaspora/diaspora#6211]
There is no way knowing if a pod has enabled XMPP or not . Is there a way to know that via the normal statistics interface ? 
##

**Comment by jhass** [comment]
We probably finally should implement NodeInfo and then it can be exposed via https://github.com/jhass/nodeinfo/issues/5

**Comment by jaywink** [comment]
:+1: for merging in node info and deprecating statistics.json - I doubt there will be more discussion from other platforms, we'll just need to lead :)

**Comment by jhass** [comment]
#6239 Exposes this via NodeInfo. However I'm hesitant to display it on the user oriented /statistics page too, the feature is still in its alpha stage (and sadly not seeing much development lately) and we shouldn't really promote it by suggesting users that a pod with it is preferable.

**Comment by jaywink** [comment]
Awesome that NodeInfo is moving! :cookie:

**Comment by denschub** [comment]
Implemented with c928d6c117d44170be48b7f4eaa526b9fa77590f.

**Comment by jhass** [comment]
I'm reopening this, I think we do should display it on the /statistics page some day, just not yet.

**Comment by jaywink** [comment]
It would be great if Diaspora added `xmpp` to the protocols array in NodeInfo if the server has XMPP enabled. This way it would just automatically show on the-federation.info site. Relevant comment [here](https://github.com/thefederationinfo/the-federation.info/issues/135#issuecomment-445549752).

**Comment by SuperTux88** [comment]
Diaspora doesn't support federation over xmpp, so adding xmpp as a protocol would be wrong. In https://github.com/jhass/nodeinfo/pull/17#issuecomment-290699392 was decided to use xmpp in `protocols` for systems federating over xmpp like movim. For chat diaspora added `metadata.xmppChat` in c928d6c.

**Comment by HankG** [comment]
> Diaspora doesn't support federation over xmpp, so adding xmpp as a protocol would be wrong. In [jhass/nodeinfo#17 (comment)](https://github.com/jhass/nodeinfo/pull/17#issuecomment-290699392) was decided to use xmpp in `protocols` for systems federating over xmpp like movim. For chat diaspora added `metadata.xmppChat` in [c928d6c](https://github.com/diaspora/diaspora/commit/c928d6c117d44170be48b7f4eaa526b9fa77590f).

But one can log into the XMPP on a pod and talk to users on other Diaspora that are using it on their pod.  While the website UI is broken (for all intents and purposes anyway) I started using Pidgen to log into my pod's XMPP server.  I'm regularly chatting with people on Pluspora and elsewhere not just my pod.

**Comment by SuperTux88** [comment]
> But one can log into the XMPP on a pod and talk to users on other Diaspora that are using it on their pod.

You can talk to every other XMPP user, not only diaspora pods, it's a normal XMPP account.

But as said, diaspora doesn't federate messages through XMPP.

> Could it be added instead to the services array alongside Twitter, Tumblr and WordPress?

That was discussed too (https://github.com/jhass/nodeinfo/pull/17#issuecomment-290910079), but services are for things where you can forward posts to, and diaspora doesn't support that either.

**Comment by jaywink** [comment]
> Could it be added instead to the services array alongside Twitter, Tumblr and WordPress?

Only as outbound, since NodeInfo forbids inbound XMPP.. 🥇 🎖 🏅 🏆 

Anyway, if the Diaspora project doesn't want it to show in the protocols then it is their decision. I would argue the Diaspora server does have federating XMPP if the server maintainer installs an XMPP server and integrates it to Diaspora. 

Unrelated, but the reason I came to comment here. We can solve this on the-federation info side as it is anyway necessary to allow multiple platforms running on the same domain name. In this case XMPP server maintainers can expose for example NodeInfo2 for the XMPP server, thus getting both listed - thought as separate instances.

**Comment by SuperTux88** [comment]
The chat was removed with #8069, this is obsolete now.
