### ISSUE TITLE
Notification dropdown menu: if you scroll all the way down, the links become unclickable

### ISSUE THREAD

**Issue by pizzamaker** [diaspora/diaspora#6217]
Title says it all. Happens in version 0.5.1.1. Pod tested was DiasporaBR.

**Comment by jhass** [comment]
With "the links" you mean the "Mark all as read" button?

**Comment by svbergerem** [comment]
I am not able to reproduce this for the "Mark all as read" button.

**Comment by pizzamaker** [comment]
Sorry, the "Mark as all read" button is fine.

However,in inline links such as "[[User A]] commented on [[post X]]", I can neither click on User A or post X if I scroll the dropdown menu all the way down.

**Comment by svbergerem** [comment]
> inline links such as "[[User A]] commented on [[post X]]"

I am still not able to reproduce this.

**Comment by jhass** [comment]
Maybe browser specfic?

**Comment by pizzamaker** [comment]
I reproduced the issue in both Firefox and Abrowser (which is Firefox-based). Midori doesn't display this error, so I'm guessing Chrome also doesn't have this bug.

**Comment by svbergerem** [comment]
I am also using Firefox (39.0). Is there anything in the error console? How does such an unclickable link look like in the webconsole's “Inspector”?

**Comment by pizzamaker** [comment]
I get a few errors, maybe some aren't relevant, but I've screenshot them all:
https://imgrush.com/5jLbTHZQd2ER.png

**Comment by morashid92** [comment]
I get similar errors here on development mode, i'm guessing put a break-point on that line and traverse above the stack to see why the element is undefined:

![screenshot](https://cloud.githubusercontent.com/assets/11273288/8833210/91eded8a-30a5-11e5-8ed2-bed62494a2d8.png)

**Comment by svbergerem** [comment]
@morashid92 I'm not able to reproduce your errors but they are also unrelated. If you are able to reproduce them then please open a new issue.

@pizzamaker The screenshot you posted is not available anymore.
> How does such an unclickable link look like in the webconsole's “Inspector”?

**Comment by svbergerem** [comment]
This issue still lacks important information and I'm still not able to reproduce this. If you are able to reproduce this and have some of the information I asked for then please leave a comment.
