### ISSUE TITLE
Sidebar links are not fully clickable

### ISSUE THREAD

**Issue by maliktunga** [diaspora/diaspora#6235]
Here is the clickable zone of Stream:
![stream](https://cloud.githubusercontent.com/assets/6393838/8840115/f6d6c906-30aa-11e5-9396-3f77cc8f1ea0.png)

Here is the clickable zone of My Activity:
![myactivity](https://cloud.githubusercontent.com/assets/6393838/8840113/f032447c-30aa-11e5-8058-87049dd9d41e.png)

Here is the clickable zone of @Mentions:
![mentions](https://cloud.githubusercontent.com/assets/6393838/8840136/3762c9e8-30ab-11e5-8ab3-ea0c6c8fd7cc.png)

Here is the clickable zone of My Aspects:
![myaspects](https://cloud.githubusercontent.com/assets/6393838/8840166/7498c51a-30ab-11e5-9d04-b689c6d21b3d.png)

Here is the clickable zone of #Followed Tags
![followedtags](https://cloud.githubusercontent.com/assets/6393838/8840182/b6c04ff8-30ab-11e5-92db-e4b191d6845c.png)

I would expect the clickable zone to cover the blue zone just like with My Aspects and #Followed Tags.

I use Diaspora 0.5.99.0-p0713edaf on https://social.mrzyx.de/
Firefox 39.0 on Fedora 22

**Comment by Flaburgan** [comment]
https://github.com/diaspora/diaspora/pull/6112 should have solved this.
