### ISSUE TITLE
Mention popup doesn't work for Cyrillic names

### ISSUE THREAD

**Issue by yurkobb** [diaspora/diaspora#6242]
````@````-completion doesn't work for contacts who have Cyrillic names for me on 0.5.1.1-p9bef1053, only names with Latin characters appear.

**Comment by svbergerem** [comment]
Related to #4493.

**Comment by cmrd-senya** [comment]
This is probably a blocker for the issue: https://github.com/podio/jquery-mentions-input/issues/117

**Comment by svbergerem** [comment]
This might have been fixed on the develop branch in #6728. Would be great if someone could try this again.

**Comment by cmrd-senya** [comment]
Nope, it doesn't work

**Comment by svbergerem** [comment]
Then it definitely has nothing to do with jquery-mentionsinput since the mentioned PR dropped that dependency.
