### ISSUE TITLE
:thumb_large size should only resize width to 300px

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/diaspora#6248]
This is related to @Flaburgan 's comment [here](https://github.com/diaspora/diaspora/pull/6244#issuecomment-124727525):

> So, here is the real problem: thumb_large is not resized to be 300px width. It is its larger dimension, either height or width, which is resized to 300px. So, for images which have a big height and a small width, the result is catastrophic. Here is a good example: https://diaspora-fr.org/posts/901677

Furthermore, I think networks today are fast enough to support a little increase of that size. I think `thumb_large` size can be insreased to 400 or 500px.
##

**Comment by svbergerem** [comment]
I disagree. If the image has a width of 300px and a height of 3000px then I wouldn't call it a large thumbnail. Why don't we scale down the image size such that either the width or the height is at most 300px and then crop the image to 300x300px?

**Comment by AugierLe42e** [comment]
It coulnd't be used anymore as the image to display in the stream, then.

**Comment by svbergerem** [comment]
AFAIK we don't use `thumb_large` in the desktop stream. In the mobile stream it is a preview of one of the images of a post. (You can see all other images of the post and the preview image itself with full width when you click on the image.)

**Comment by AugierLe42e** [comment]
No, sorry, that's me, I understood something else than what you actually said.
But if we changed the way images are resized, what would happen to the previously uploaded images ?

**Comment by Flaburgan** [comment]
@AugierLe42e implemented the crop in #6244 but I'm actually not sure to crop is a good idea. I mean, how does the user understand that he is not seeing the full image? What's the ko size of a 300x3000px jpg image in the worst case? Is this acceptable on mobile? I think we should check at number to pick the good decision.

**Comment by AugierLe42e** [comment]
It's pretty standard to crop an image to offer only a preview on stream. As it concerns images heigher than 500px, it will be often pretty clear that the image is not fully displayed as the content will be hardly cut.
