### ISSUE TITLE
Link avatars to profiles in hovercards

### ISSUE THREAD

**Issue by teslasmoustache** [diaspora/diaspora#6281]
I always find myself clicking the profile pic of a hovercard to get to the profile page.

No biggie, just kind of a consistency thing.

**Comment by AntonTkachov** [comment]
@teslasmoustache I am new to diaspora, so I don't know where can i find there 'hovercards'. Can you please help me find this logic in the project?

**Comment by svbergerem** [comment]
@AntonTkachov To fix this issue you would have to modify the [hovercard template](https://github.com/diaspora/diaspora/blob/develop/app/assets/templates/hovercard_tpl.jst.hbs) (wrap the avatar with a link) and the [hovercard backbone view](https://github.com/diaspora/diaspora/blob/develop/app/assets/javascripts/app/views/hovercard_view.js#L114) (set the correct href for the link).

There is also some code in the [people controller](https://github.com/diaspora/diaspora/blob/develop/app/controllers/people_controller.rb#L116) and a [HovercardPresenter](https://github.com/diaspora/diaspora/blob/develop/app/presenters/hovercard_presenter.rb) but I don't think that one would have to modify those for this feature.

**Comment by AntonTkachov** [comment]
@svbergerem Thanks a lot

**Comment by svbergerem** [comment]
Fixed by #6297.
