### ISSUE TITLE
[Mobile] Error 500

### ISSUE THREAD

**Issue by iTaskmanager** [diaspora/diaspora#6282]
There is an error in the mobile view (mobile > notification)

> [2015-08-02T18:05:07] INFO  PID-25103 TID-3330860 ActionController::Base: Completed 500 Internal Server Error in 821ms (ActiveRecord: 18.3ms)
> [2015-08-02T18:05:07] FATAL PID-25103 TID-3330860 Rails: 
> ActionView::Template::Error (undefined method `profile' for nil:NilClass):
>     1: .notification_element{:data=>{:guid => note.id, :type => (Notification.types.key(note.type) || '')}, :class => (note.unread ? "unread" : "read")}
>     2:   .pull-right.unread-toggle
>     3:     %i.entypo.eye{ :title => (note.unread ? t('notifications.index.mark_read') : t('notifications.index.mark_unread')) }
>     4:   = person_image_tag note.actors.first, :thumb_small
>     5:   .notification_message
>     6:     = notification_message_for(note)
>     7:     %div= timeago(note.created_at)
>   app/helpers/people_helper.rb:35:in `person_image_tag'
>   app/views/notifications/_notification.mobile.haml:4:in `_app_views_notifications__notification_mobile_haml__1170938696909311737_63600940'
>   app/controllers/notifications_controller.rb:42:in `block in index'
>   app/controllers/notifications_controller.rb:41:in `each'
>   app/controllers/notifications_controller.rb:41:in `index'
>   lib/rack/chrome_frame.rb:39:in `call'
>   lib/unicorn_killer.rb:35:in `call'

"500: Internal server error"
> ActionView::Template::Error (undefined method `profile' for nil:NilClass):

**Comment by svbergerem** [comment]
Thanks a lot for your bug report. #6286 will fix this.

**Comment by iTaskmanager** [comment]
@svbergerem: Thanks for the temporary fix.
