### ISSUE TITLE
Reshare button missing in SPV

### ISSUE THREAD

**Issue by balasankarc** [diaspora/diaspora#6284]
Hi,
I can't see any reshare button in single post view of a public post. Attaching a screenshot below

Pod : [Poddery](http://poddery.com)
Version : 0.5.0.1-p6c164fe2 (as per [statistics](https://poddery.com/statistics.json))
Test post : https://poddery.com/posts/1930224

Please tell me if any more information is needed.

![reshare](https://cloud.githubusercontent.com/assets/2379271/9027217/516868da-396a-11e5-9cae-5ea758f3d719.png)

**Comment by jaywink** [comment]
Interesting. Just for this post or all public posts? @pravi aren't you one of the podmins?

**Comment by SansPseudoFix** [comment]
Do you use Adblock, AdblockPlus, uBlock Origin? I had this issue, and solve it by disabling rules for diaspora*. Related to #6156? If yes, fixed by #6158.

**Comment by balasankarc** [comment]
@SansPseudoFix  Yeah. AdBlock Plus was the issue. Removing it fixed the issue. Thanks.

@jaywink  I am also one of the podmins of poddery. :)
