### ISSUE TITLE
Replace entypo-mail by entypo-paper-plane in header?

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/diaspora#6287]
I think it would be a good idea to replace `.entypo-mail` by `.entypo-chat` for the conversation button in header. Here is how it looks:

![screen shot 2015-08-02 at 23 14 39](https://cloud.githubusercontent.com/assets/3429231/9028072/ea3e24da-396c-11e5-97a2-74ca4e520b70.png)

It fits better to me because the `.entypo-chat` icon is higher than `.entypo-mail` and reaches the same height than `.entypo-bell` so the two icons feel less unbalanced that `.entypo-bell` and `.entypo-mail`.

Here are the two compared:

![entypo-chat](https://cloud.githubusercontent.com/assets/3429231/9028084/4b2ee36a-396d-11e5-9816-89ab96cacdd2.png)

![entypo-mail](https://cloud.githubusercontent.com/assets/3429231/9028083/4b2df0cc-396d-11e5-8b54-b2909ecf8d55.png)

As you can see the chat icon is ~26*25px while the mail icon is ~27.6*19.6px. As a comparison, `.entypo-bell` is ~21*25px:

![entypo-bell](https://cloud.githubusercontent.com/assets/3429231/9028126/56b46ab0-396e-11e5-8dc3-399bbc21858c.png)

**Comment by svbergerem** [comment]
This would be weird in the contacts view where we use the mail icon for conversations and the chat icon for chat:

![contacts chat icon](https://cloud.githubusercontent.com/assets/3798614/9028149/f908a51a-396e-11e5-8802-3a97a66dbe5d.png)

**Comment by AugierLe42e** [comment]
Indeed. What about `.entypo-comment`, then?

![screen shot 2015-08-02 at 23 44 19](https://cloud.githubusercontent.com/assets/3429231/9028198/762b5dfc-3970-11e5-816e-5ecdcb429a09.png)

**Comment by svbergerem** [comment]
![comment icon header](https://cloud.githubusercontent.com/assets/3798614/9028238/061ff25a-3972-11e5-8e59-cf25e5be937a.png)

**Comment by AugierLe42e** [comment]
Meh :/

**Comment by AugierLe42e** [comment]
Ok, so what about the Bootstrap's `glyphicon glyphicon-envelope`?

![screen shot 2015-08-03 at 00 27 01](https://cloud.githubusercontent.com/assets/3429231/9028357/75e6991e-3976-11e5-8fb9-6e2b7eb79105.png)

**Comment by jhass** [comment]
That looks a lot more displaced than the current version to me.

**Comment by AugierLe42e** [comment]
Too big, or is it the icon you don't like?

**Comment by jhass** [comment]
I'm not sure, maybe it looks stretched? Something feels odd about it.

**Comment by AugierLe42e** [comment]
Yeah, it is more squared than the surrent one. Not as large. What about `glyphicon glyphicon-send` ?

![glyphicon-send](https://cloud.githubusercontent.com/assets/3429231/9034288/c3d475c6-39ce-11e5-901b-9285480eef9f.png)

**Comment by jhass** [comment]
If people want the change... I'm not sure I find it any better or worse than the current version.

**Comment by SuperTux88** [comment]
What has ```glyphicon glyphicon-send``` to do with "notifications"?

**Comment by AugierLe42e** [comment]
It's not notifications, it's conversations.

**Comment by svbergerem** [comment]
There is also `.entypo-paper-plane` which looks basically the same. However I agree with Jonne:

> I'm not sure I find it any better or worse than the current version.

**Comment by AugierLe42e** [comment]
Well, if there's no strong opposition, I'll open a PR tonight, then.

**Comment by jaywink** [comment]
In firefox the plane is "share". IMHO, doesn't suit the conversations at all anyway, sorry :) Why do we need to change the current? Haven't looked at develop recently.

**Comment by SuperTux88** [comment]
@AugierLe42e oh, sorry, I was confused because of the "comments" icon ...

But why change this? Or would you change the icon everywhere the conversations-icon is used?

**Comment by AugierLe42e** [comment]
> Why do we need to change the current?

As I explain in the first post, I find height of the current icon (the mail icon) too small compared to the bell icon next to it. This, IMHO, visually unbalances the whole header. Am I the only one to be disturbed by this?

> But why change this? Or would you change the icon everywhere the conversations-icon is used?

Only on the headers (desktop and mobile). While working on #6285, I did some expleriments with other icons and it all renders better.

**Comment by SuperTux88** [comment]
I have no problems with the different height, but I find it confusing to use the plane in the header and the mail-icon everywhere else. And I think the mail-icon best matches the meaning.

**Comment by AugierLe42e** [comment]
> I have no problems with the different height, but I find it confusing to use the plane in the header and the mail-icon everywhere else.

Where else is it used?

**Comment by SuperTux88** [comment]
> Where else is it used?

On the profile-page (send message to a user) and contacts-page (send message to an aspect).

> On Android, it is used to send a message :p

But it's not used to read messages.

**Comment by Flaburgan** [comment]
The "envelop" icon is the best for conversation imo. Maybe we can just increase the font-size of the current one?

**Comment by AugierLe42e** [comment]
Ok, as this does not seem to meet a consensus, I close it.
