### ISSUE TITLE
Diaspora Truck Factor

### ISSUE THREAD

**Issue by gavelino** [diaspora/diaspora#6313]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Diaspora** and obtained a value of **6**.

The developers responsible for this TF are:

Daniel Grippi - author of 26% of the files
Maxwell Salzberg - author of 20% of the files
Raphael - author of 12% of the files
Steffen van Bergerem - author of 10% of the files
Jonne Haß - author of 10% of the files
Florian Staudacher - author of 7% of the files

To validate our results, we would like to ask **Diaspora** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Diaspora**?

(b) Do you agree that **Diaspora** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Diaspora** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by DeadSuperHero** [comment]
This is an interesting experiment, but the first three people in your list
haven't pushed any significant code for the last year or two. I would
recommend looking at the last 1,000 commits or so to more accurately
determine a manifest of core developers.

**Comment by Flaburgan** [comment]
Too bad, the first three devs already quit 3 years ago and as you can see, the project is still really alive :p But yeah I agree that if these 6 people all quit the project, we'll probably have hard time.

**Comment by jaywink** [comment]
Please don't hesitate to continue discussion here, but I'll close this issue since it's not an issue but more like discussion regarding the project itself :)

**Comment by AugierLe42e** [comment]
> (e.g., if they win in the lottery, to be less morbid)

I think some devs wound be, on the contrary more present if they won in the lottery :p
I agree with @DeadSuperHero, you should better compute this factor on a period starting from aufust 2012, when the project became community-run and the founders stopped to push code.
