### ISSUE TITLE
Don't automatically load likers and resharers profile images if over X amount for post

### ISSUE THREAD

**Issue by jaywink** [diaspora/diaspora#6314]
See picture:

![11836869_10207752369516894_3820456825363901969_n](https://cloud.githubusercontent.com/assets/1174866/9224368/8b89982a-410a-11e5-8073-b18cbb9cf796.jpg)

The only thing that does is kill the browser when accessing a popular post in the SVP :) Maybe just show X amount and then some 'show X more' link that would fetch the rest.
##

**Comment by jhass** [comment]
How about displaying the first, say 20-25 and if there are more display a plus symbol or so?

**Comment by jaywink** [comment]
:+1:
