### ISSUE TITLE
email notifications settings not sticking

### ISSUE THREAD

**Issue by fczuardi** [diaspora/diaspora#6317]
### Steps to reproduce:

1 - On the settings page, change your email settings from this:

![screen shot 2015-08-13 at 1 04 10 pm](https://cloud.githubusercontent.com/assets/7760/9254833/fdd7de76-41bb-11e5-9122-630844e6e4e2.png)

to

![screen shot 2015-08-13 at 1 04 31 pm](https://cloud.githubusercontent.com/assets/7760/9254839/0831a3ac-41bc-11e5-9f63-1163f6c767e8.png)

2 - Wait a couple hours (or go to sleep, the bug happened with me from one day to another)

### Expected results

The user preference is respected and she no longer receives email notifications for comments on a post that she commented.

### Actual results

The user preference is changed back to "all checkboxes checked" and the email notifications comes back.

**Comment by fczuardi** [comment]
this bug have been reported by other therealtalk.org users here https://therealtalk.org/posts/10550 and here https://therealtalk.org/posts/9898

**Comment by jhass** [comment]
Can anybody on another pod confirm this?

**Comment by fczuardi** [comment]
I have asked 2 friends on different posts to try to reproduce this on diasp.org and joindiaspora.com, let's wait…

**Comment by jaywink** [comment]
Sounds weird. I've changed them on my pod (0.5.99) and diasp.eu (0.5.2) - will report back tomorrow too..

**Comment by jaywink** [comment]
Well, can't reproduce, on my pod and diasp.eu, settings stuck for 24h.

Maybe the "Change" to the server just timed out - I'd say this is not a code bug.

**Comment by fczuardi** [comment]
Yeah… it haven't changed back since I reported it, so I am closing this as can't reprocue / wfm, if it happens again and I get a reproduceable test case I'll reopen it. Thanks!
