### ISSUE TITLE
Ask diaspora foundation to host a cross-domain share for Firefox

### ISSUE THREAD

**Issue by fczuardi** [diaspora/diaspora#6327]
As for this firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1195333 Firefox currently does not list diaspora* as one of the providers in their Social Share providers page at https://activations.cdn.mozilla.net/en-US/ 

Shane Caraveo on comment 1 suggested that a trusted intermediary can host a sharer and be included on the directory.

>Having the share functionality on github is to ephemeral and wouldn't be something I would include on the share directory.  
>
>My first suggestion would be to get the share activation included in the diaspora distribution.  This would allow users to activate share directly on their own pod without any intermediary.  Due to the way activation works, this mechanism would not be something that would work from the directory (default options in the share panel or on the site via view more).
>
>My second suggestion is to get a trusted intermediary (e.g. diasporafoundation.org) to host the cross-domain share, that mechanism could be included in the directory.

Is this something easy to ask for the folks hosting diasporafoundation.org?

**Comment by jaywink** [comment]
If hosting the diaspora advanced sharing app on the project site would get diaspora sharing into firefox by default it would defo be worth it.

**Comment by mixedpuppy** [comment]
Hi, this is Shane from Mozilla, I replied in the bugzilla bug mentioned.
To be clear, it could be added to the directory at activations.mozilla.org if it were on a trusted domain, I would love to see more projects like diaspora there.  Users do get to the directory from the share panel.  It wouldn't be added to Firefox as a default unless there were *significant* user adoption and it made sense to that product team, it is not my decision to make.

**Comment by mixedpuppy** [comment]
And BTW, it does require the activation page is delivered over https.

**Comment by AugierLe42e** [comment]
> To be clear, it could be added to the directory at activations.mozilla.org if it were on a trusted domain

This would concern a lot of pods. I don't know about procedures to become a trusted domain, but if it force each podmin to go through them, it will be a problem.

**Comment by mixedpuppy** [comment]
You're reading too much into my use of that term.  diasporafoundation.org seems like a good place for this, people would be likely to trust that, maybe there are others.  somebodynobodyknows.com is a bad place for this.

**Comment by fczuardi** [comment]
@AugierLe42e today, anyone that visits https://sharetodiaspora.github.io/about/ and install the share provider by clicking on the "Activate Diaspora* Share Service" button, will use code hosted com sharetodiaspora.github.io to share links with Firefox.

The code currently hosted on sharetodiaspora.github.io already shows the user options to choose on which pod to share, and a copy of it hosted elsewhere (diasporafoudation.org for example) would have this same options to choose on which pod to share I suppose.

What we are talking about here is about the possibility of hosting a copy of the [sharetodiaspora/sharetodiaspora.github.io](https://github.com/sharetodiaspora/sharetodiaspora.github.io) code on a different domain that Mozilla is more confortable with promoting it on it's advertisement web page https://activations.cdn.mozilla.net/en-US/ they've signaled that if it was hosted under diasporafoundation.org instead of github.io, they could list it in this promotion website.

This is just an advertisement opportunity, a bug about "how to get one particular diaspora* sharer in a Firefox webpage spotlight".

**Comment by fczuardi** [comment]
Of course that might be better implementations of a firefox social api based sharers and they too would like to be listed in a mozilla page, the directory could even list several pod-specific sharers and that would be maybe the p2p-approved way of doing it, but this particular mozilla page is not open for several submissions (as opposed to their addons website) so having one centralized facebook link, one centralized twitter link and 20 individual diaspora* links is probably not going to happen :)

**Comment by AugierLe42e** [comment]
Ok, it looks a good idea to me.

**Comment by jaywink** [comment]
Created a [Loomio discussion](https://www.loomio.org/d/teUOzAXf) :dancer:

**Comment by denschub** [comment]
Closing. Please check my response in the linked Loomio thread and follow [bug 1195333](https://bugzilla.mozilla.org/show_bug.cgi?id=1195333) for updates.
