### ISSUE TITLE
Linebreak striped between pods? (possibly federation problem with friendica)

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/diaspora#6328]
[Comment on diaspora-fr](https://diaspora-fr.org/posts/1460697#1a03f5e028be0133d4132236faefa3bc):

![rmd4](https://cloud.githubusercontent.com/assets/3429231/9362670/29fd4a96-46a2-11e5-9fee-03a6c1d57d8e.png)

[Same comment on diaspote](https://diaspote.org/posts/86787#1a03f5e028be0133d4132236faefa3bc):

![rmd5](https://cloud.githubusercontent.com/assets/3429231/9362674/3642a846-46a2-11e5-9baf-4dde49d5e658.png)

The original post was issued from a friendica pod.

**Comment by svbergerem** [comment]
You wrote that comment on diaspora-fr where the comment looks exactly like to comment on the [friendica server](http://diaspored.s-pichard.fr/display/121271058514871347555d4a1c5b0961). The friendica server sent the comment to diaspote so it looks like a bug in friendica's federation implementation.

**Comment by jaywink** [comment]
@annando want to check the Friendica side?

**Comment by jaywink** [comment]
Oh damn sorry ignore, Augier already logged this as an issue :+1:

**Comment by annando** [comment]
The post is relayed via a Friendica server with a really old version (3.3.3). I can't reproduce this on the current version (3.4.3-dev).
