### ISSUE TITLE
Something is broken between JSXC and new design

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/diaspora#6341]
![screen shot 2015-08-23 at 12 45 21](https://cloud.githubusercontent.com/assets/3429231/9427904/e6c379ee-4994-11e5-8ec4-ed25fdc7bb59.png)

**Comment by AugierLe42e** [comment]
I've tried to find a solution for this but it seems like using `position: fixed` on sidebars is not a good solution. The only solution I found was to use `position: sticky` which [is not well-supported by most browsers](http://caniuse.com/#feat=css-sticky). In the end, in short-term, we'll need to solve this with a bit of JS. :/

**Comment by svbergerem** [comment]
Fixed by #6535.
