### ISSUE TITLE
CSS: overlay of right side-bar by new sliding drawer

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#6343]
In the new `develop` desktop stream view, there is a sliding drawer on the right, which overlays the right side-bar. When opened, the drawer has a 'no connection - relogin' option (which is odd in itself because I am logged in, but that's another matter).

Anyway, at present this drawer slightly overlays the text. See image:

![__](https://cloud.githubusercontent.com/assets/2530168/9445849/332bc222-4a86-11e5-874f-e9d701484807.png)

**Comment by AugierLe42e** [comment]
I confirm It happens between 992px and 1200px. Above that, there's a margin so chat doesn't overlays right side bar and under, chat is hidden.

**Comment by goobertron** [comment]
Oh, the drawer is related to chat, is it? Thanks for explaining that. There's nothing to suggest that in the drawer itself, so I didn't realise what it was for. @Zauberstuhl, it might be worth adding some text to that drawer to explain that it relates to the chat feature. Otherwise more stupid users, such as myself, won't realise what it's for!

**Comment by AugierLe42e** [comment]
Actually, it's likely that you didn't notice it was for the chat because it simply does not work on d-fr :p

**Comment by Zauberstuhl** [comment]
@goobertron haha yes I will think about something. In general we have to think about a way how to introduce new people to the chat.
@AugierLe42e diaspora/vines#63 fix was merged I want to release today

**Comment by goobertron** [comment]
Great. If you want any help with writing text, just let me know.

**Comment by Flaburgan** [comment]
There is no more right side bar in current `develop`. I guess the integration of the chat at the right side can be improved (it's actually completely hidden until you put your mouse there) but this can be listed in #5398. So this issue can be close in my opinion.
