### ISSUE TITLE
cannot start diaspora when tmp/pids directory is not present

### ISSUE THREAD

**Issue by pravi** [diaspora/diaspora#6350]
E, [2015-08-26T08:10:16.399368 #31309] ERROR -- : [diaspora:sidekiq:sidekiq1] p
rocess <31476> failed to start (:cant_write_pid)

script/server should create this if missing or we should ship with the directory included. After creating the directory, everything is working.

**Comment by jhass** [comment]
We do. https://github.com/diaspora/diaspora/blob/develop/tmp/pids/.gitkeep

**Comment by pravi** [comment]
Thanks for the quick reply, it was my mistake, I was not installing tmp directory in the debian package. It is fixed now.
