### ISSUE TITLE
Support apng image format

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora#6358]
https://diasp.eu/posts/3482634

**Comment by Faldrian** [comment]
Please include some description of what this is about.

**Comment by svbergerem** [comment]
> The PNG group officially rejected APNG as an official extension on April 20, 2007.

([source](https://en.wikipedia.org/wiki/APNG))

WebKit and KHTML don't support APNG:
https://bugs.webkit.org/show_bug.cgi?id=17022
http://bugs.kde.org/show_bug.cgi?id=88352

Imagemagick, which we use to convert images, won't support APNG:
https://github.com/ImageMagick/ImageMagick/issues/24

Thus I don't think that we should support APNG either.

**Comment by jhass** [comment]
Agreed, closing.

**Comment by GreenReaper** [comment]
The link you provided showed that Webkit does support APNG now, though.
Support was [committed in March 2015](http://trac.webkit.org/changeset/181553).

IM is still an issue, but it's something which should probably be pushed up to them.
