### ISSUE TITLE
/contacts and deleted account

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#6373]
A user reported that he still has deleted accounts listed on the /contacts page. When he clicks on it, he has a "this account has been closed" message. Should the link be dropped too when an account is closed? (Related to https://github.com/diaspora/diaspora/issues/6221 but with certainly more things to check in the background)

**Comment by svbergerem** [comment]
We'll need some info to reproduce this.

**Comment by svbergerem** [comment]
@Flaburgan Could you find out if the user is still able to reproduce this?

**Comment by Flaburgan** [comment]
Unfortunately, I forgot who it was :(
Did you try to reproduce by creating A and B accounts, making A sharing with B so B is listed in /contacts (but without B sharing back) then B closes its account, and check if B is still listed in /contacts of A, and what happens if A clicks on B?

**Comment by svbergerem** [comment]
Yes, I tried that with both, mutual and only sharing contacts (A sharing with B), and in both cases B didn't show up in `/contacts` or `/contacts?a_id=5`.

**Comment by Flaburgan** [comment]
Hm, so without any way to reproduce, I guess this can be closed. We can still reopen it if someone complains again.
