### ISSUE TITLE
Provide a "website" or URL field in the profile

### ISSUE THREAD

**Issue by strugee** [diaspora/diaspora#6387]
I should be able to link to my personal website in my diaspora\* profile.
##

**Comment by jhass** [comment]
You can just put a link into your Bio, it's markdown parsed.

**Comment by strugee** [comment]
Ah, okay. Thanks. That sort of works, but doesn't allow me to add a semantic `rel=me` attribute.

**Comment by tclaus** [comment]
@jhass Can this be closed? Even on distinct website-fields it should never be allowed for custom html-attributes in auch fields.

**Comment by strugee** [comment]
@tclaus `rel="me"` makes sense to automatically put on profile website fields, without asking users. IIRC Twitter, Google, Facebook(?) and GitHub already do this. See http://microformats.org/wiki/rel-me

Don't know why I didn't clarify that in 2015 🙄

**Comment by strugee** [comment]
Feel free to close though; I haven't used Diaspora* in a long time

**Comment by tclaus** [comment]
With this explanation, it sounds more interesting. 
I am just following suggestions from code-triage. Now I have more insights into this request. thank you.

**Comment by strugee** [comment]
No problem!

**Comment by tclaus** [comment]
Closed because this very old request has no serious use-case.
