### ISSUE TITLE
After updating to 0.5.3.0 chat is gone

### ISSUE THREAD

**Issue by Quetschwalze** [diaspora/diaspora#6390]
After Updating to version 0.5.3.0 the chat sidebar seems to be gone for me.
However Vines seems to be started and is working correctly:
> pgrep -f vines
> 5398

And the output of the vines.log:

> I, [2015-09-07T11:49:08.826452 #5398]  INFO -- : XMPP server started
> I, [2015-09-07T11:49:08.826774 #5398]  INFO -- : Accepting client connections on 0.0.0.0:5222
> I, [2015-09-07T11:49:08.826857 #5398]  INFO -- : Accepting server connections on 0.0.0.0:5269
> I, [2015-09-07T11:49:08.826901 #5398]  INFO -- : Accepting http connections on 0.0.0.0:5280

**Comment by Zauberstuhl** [comment]
@Quetschwalze could you execute `localStorage.clear()` via JS console in your browser and try again?

**Comment by Quetschwalze** [comment]
@Zauberstuhl yes:
>localStorage.clear
>clear()  

However the result is still the same. Tested with Firefox 40

**Comment by Zauberstuhl** [comment]
@Quetschwalze could you provide me with an test account on your pod? lukas@zauberstuhl.de

Cheers

**Comment by Quetschwalze** [comment]
@Zauberstuhl sure thing, I've send you an email. Thanks for all your help!

**Comment by Quetschwalze** [comment]
After testing this with different clients it seems that this is a local client problem only. I still don't know what is causing this but since I'm the only one on my pod affected I'll close the issue.  
Thanks for the support!
