### ISSUE TITLE
add bountysource to sidebar

### ISSUE THREAD

**Issue by pravi** [diaspora/diaspora#6396]
With 3 top bounties listed directly. This will give more visibility to most requested features.
##

**Comment by jhass** [comment]
I don't think our main target audience is developers, it's just annoying to the regular user.

**Comment by pravi** [comment]
Regular users can add bounties to features they want the most. This was suggested by a journalist friend.

**Comment by jhass** [comment]
I guess we should at most use it as fallback if the podmin didn't configure donations. There's also the question of adding a request to a third party API on every page load.

**Comment by pravi** [comment]
May be you can cache it so you don't have to call third party on every page load. It can be refreshed every month.

**Comment by Flaburgan** [comment]
Let's first integrate it on diasporafoundation.org and then see how it's going on.

**Comment by jaywink** [comment]
I wouldn't mind some link to a page, maybe on the Foundation:tm: page or the wiki, highlighting different ways users can sponsor the project. Even a direct link to bountysource I guess is fine, but one link to a collection of sponsorship methods would be nicer.

As for adding a list of tasks I don't think that is a good idea either. It will just make the sidebar look like a bug tracker :) It should be designed as normal users in mind, not developers. But the sidebar really does need an overhaul. Like a link to how to report a bug for example.

**Comment by cmrd-senya** [comment]
I would suggest a little bit different idea, which I think is better.

We could add an optional "information from diaspora foundation" block at the sidebar, which is off by default, and can be enabled by a podmin. If enabled it'll show some kind of "advertisement" provided and controlled by the Diaspora Foundation people.

This block can be used, to promote some campaigns. For example, if some developers sets the funding goal at bountysource.com as 100$ for some bug, then we could show this note in the block with a current bounty amount and a link, so user can quickly get to the bountysource's donation page and help the exact feature to be released. It's more likely a man would pay for the exact feature than just donate.

The block could even be used to promote projects not directly related to Diaspora, but that is considered to be good by the Foundation (funding Tox, Kontalk, MediaGoblin, etc).

**Comment by jhass** [comment]
We are currently reevaluating how we approach donations, Bountysource will play a less important role in the future.
