### ISSUE TITLE
Nav bar missing in mobile view when not logged in

### ISSUE THREAD

**Issue by ghost** [diaspora/diaspora#6403]
When viewing a public post on mobile view the nav bar is not visible.

This prevents the client from signing up, logging in and it also prevents them from being able to toggle back to desktop view.

Steps to reproduce *(on mobile)*:

1. View any public post - eg. https://joindiaspora.co.uk/posts/e84255303c5601332d0a6c626dd55703
2. You are now viewing the public post with no means of signing up, logging in or switching to desktop view (whereby the nav bar is then visible again)

Steps to reproduce *(on desktop)*:

1. View any public post - eg. https://joindiaspora.co.uk/posts/e84255303c5601332d0a6c626dd55703
2. Click 'toggle mobile' at bottom of screen
3. You are then taken to Signup screen for some reason (but that's another story), so click Back on your browser and refresh the page
4. You are now viewing the public post with no means of signing up, logging in or switching to desktop view (whereby the nav bar is then visible again)

![2015-09-14_094703](https://cloud.githubusercontent.com/assets/2150079/9845789/94162c4a-5ac5-11e5-9e0a-36b45366dc06.jpg)

**Comment by RichKavanagh** [comment]
Feature? Yeah, ok :)

**Comment by AugierLe42e** [comment]
Yeah ! Not a bug ! :D

**Comment by RichKavanagh** [comment]
Seriously? This was by design? :)

**Comment by AugierLe42e** [comment]
No idea, was just a joke.

**Comment by jaywink** [comment]
@jhass umm why feature? It's a clear bug. The header is missing, tested also on latest development head :)

**Comment by jhass** [comment]
thought it's just not implemented

**Comment by Flaburgan** [comment]
Working on that.
