### ISSUE TITLE
Broken mobile flow on limited post notification

### ISSUE THREAD

**Issue by jaywink** [diaspora/diaspora#6412]
Steps to reproduce:

* Sign out
* Click a notification  for a limited post mention in email
* Mobile view says no access and offers a login link in the text
* Click link and login

Expected: redirect to mention post after login

Actual: Stream is rendered

**Comment by svbergerem** [comment]
Duplicate of #3738?

**Comment by jaywink** [comment]
Hmm yeah sorry, was on mobile and searching for issues is kinda tricky without a proper client.

Thanks!
