### ISSUE TITLE
Public posts with followed tags is not shown in stream

### ISSUE THREAD

**Issue by juliaviluhina** [diaspora/diaspora#6420]
Steps
1. Sign in Diaspora account 1
2. Share public post which contain some tag followed in Diaspora account 2
3. Sign in Diaspora account 2, whose Stream was not contained Diaspora account 1 earlier.
4. Check stream in Diaspora account 2 using links <PodLink>/stream or <PodLink>/tags/<tagname> (links Stream or this followed tag on left navigation bar) (<tagname> - name of tag from step 2)

Expected result 
(According to paragraph 2 in https://wiki.diasporafoundation.org/FAQ_for_users#Why_is_my_stream_full_of_posts_from_people_I_don.27t_know_and_don.27t_share_with.3F)
In stream of Diaspora account2 public post from step 2 is shown

Actual result
In stream of Diaspora account 2 public post from step 2 is not shown

**Comment by Flaburgan** [comment]
Are account1 and account2 on the same pod?

**Comment by juliaviluhina** [comment]
Accounts are from different pods
account 1 from https://diaspora.koehn.com
account 2 from https://nerdpol.ch

**Comment by jhass** [comment]
Are they following each other?

**Comment by juliaviluhina** [comment]
They have the same followed tag
As I understood, is it enough for public posts, isn't it?

**Comment by Flaburgan** [comment]
Unfortunately, not when the users aren't in the same pod. You can read [this blogpost](http://geexxx.fr/2013/07/23/comment-ca-marche-la-federation-de-diaspora/#english) about it.

**Comment by jhass** [comment]
No it isn't: https://wiki.diasporafoundation.org/FAQ_for_pod_maintainers#Followed_tags_don.27t_work_on_my_pod

**Comment by juliaviluhina** [comment]
thank you for explanation

**Comment by jhass** [comment]
So that was the issue? Can we close this?

**Comment by juliaviluhina** [comment]
I think yes
