### ISSUE TITLE
Language of standart aspects is not changed after changing language in settings

### ISSUE THREAD

**Issue by juliaviluhina** [diaspora/diaspora#6423]
Steps
1. Windows display language = Russian (OS - Windows 8)
2. Sign up in Diaspora pod (registration occured in Russian)
3. Public one post
4. Change in settings of account language to English

Expected result
All terms of Diaspora should be written on English

Actual result
Standart aspects remained on Russian (everywhere on account)
Clarification - all terms apart aspects change language on English
![image](https://cloud.githubusercontent.com/assets/13263036/10084526/90089148-630c-11e5-9b55-437896609a5d.png)

**Comment by jhass** [comment]
I'm not sure if it's worth it, detecting whether to update the name or not will be hard, since the translation may change and then we get false positives or false negatives.

**Comment by juliaviluhina** [comment]
Thank you for explanation
