### ISSUE TITLE
State of aspect navigation panel do not changed after changing aspect of some contact

### ISSUE THREAD

**Issue by juliaviluhina** [diaspora/diaspora#6424]
Steps
1. Sign in Diaspora account
2. In user menu on header click Contacts (<PodLink>/contacts)
3. In aspect navigation panel (id="aspect_nav") select aspect which is contain some contacts
4. Change aspects in some contact

Expected result
In aspect navigation panel information about quantity of contacts should change afler changing aspects of contact

Actual result
In aspect navigation panel information about quantity of contacts do not change afler changing aspects of contact
It changes only after refresh.

**Comment by svbergerem** [comment]
#6240 fixed this some time ago.
