### ISSUE TITLE
Clarify aspects in limited posts

### ISSUE THREAD

**Issue by juliaviluhina** [diaspora/diaspora#6426]
May be, it is feature.

Posts, which were published for some aspects, are marked as Limited
Can I get information about aspects of this post?
I think, it would be helpful to know about limited posts written by owner of account.

**Comment by jhass** [comment]
We had this before but I can't find it atm. The issue is that it quickly is lying, it would suggest "those are the people who can see the post" but if you modify the aspects a contact is in or add or remove a contact that does not affect the visibility of your past posts.

**Comment by svbergerem** [comment]
Duplicate of #3181.

**Comment by Loelo** [comment]
Also duplicate of [#4995](https://github.com/diaspora/diaspora/pull/4995)

Seems to be a very needed feature !
