### ISSUE TITLE
setting up a new account impossible

### ISSUE THREAD

**Issue by Photocreator** [diaspora/diaspora#6432]
I do not know why it is made impossible to set up an account. I just can't get through: human verification failed. Think I know why: there's already something filled in, some kind of number and this cannot be changed. Other then that, there's only "diaspora" to be seen/read in the depicted image, so I would not know what to do. I have never had any problems with creating an account before and am an experienced pc user. So for some reason diaspora makes it very, very difficult to join. A pity really!!!

**Comment by jhass** [comment]
@Photocreator on which pod did you try to sign up?

**Comment by Photocreator** [comment]
I tried it on the general pod; the one which states: "confused? then sign up directly through this link". (or something similar; do not know the exact phrase) I also tried through another pod, one of the choices available. But then I got directed to the same link, which does not work. At least, as I said, I cannot be recognized as a human. Which, again, cannot be done in a different manner as far as I can see. A vicieus circle so to speak. 


     On Monday, September 28, 2015 10:10 AM, Jonne Haß <notifications@github.com> wrote:
   

 @Photocreator on which pod did you try to sign up?—

**Comment by jhass** [comment]
Can you please try again, keeping track of the URL you use to sign up?

**Comment by kas70** [comment]
is the site allowed to set cookies?

**Comment by svbergerem** [comment]
We can't do anything without any further info.
