### ISSUE TITLE
Replace compass-rails

### ISSUE THREAD

**Issue by jhass** [diaspora/diaspora#6433]
The compass-rails gem appears to be dead and locks us down on sprockets 2.12, which is a dead end in the long run. As far as I'm aware we only use it for sprite generation, so we could either try to get rid of the remaining sprites or look for alternatives.

Alternatives I have found so far are
- https://github.com/jakesgordon/sprite-factory
- https://github.com/flyerhzm/css_sprite
- https://github.com/agrobbin/spritely (looks like the easiest path since it was built out of frustration with compass)
##

**Comment by svbergerem** [comment]
There is a new compass-rails version with sprockets 3 support. Can we close this issue?

**Comment by jhass** [comment]
It still doesn't appear like a particularly healthy and active project to me. So might still be worth to look into IMO. But if you think otherwise feel free to close.

**Comment by jonassmedegaard** [comment]
Compass is now dead: https://github.com/Compass/compass-rails/pull/275

Generally Sass is replacing Compass, so I guess the direct replacement is https://github.com/rails/sass-rails
