### ISSUE TITLE
Resharing posts are not shown on My activity

### ISSUE THREAD

**Issue by juliaviluhina** [diaspora/diaspora#6434]
Steps
1. Sign in Disapora account
2. Reshare some post. (New resharing post appears in stream)
3. Click on My activity (<PodLink>/activity)

Expectected result
Resharing post from step 2 appears on My activity

Actual result
Resharing post from step 2 does not appear on My activity

**Comment by svbergerem** [comment]
Your own reshares now appear in the activity stream. (Possibly fixed by #6873)
