### ISSUE TITLE
close the new gallery when clicking outside an image

### ISSUE THREAD

**Issue by kas70** [diaspora/diaspora#6444]
for now it's only closable by pressing ESC or clicking on the X.

**Comment by AugierLe42e** [comment]
This is unhopfully impossible due to the way the new gallery manages image dispaying. The image is set as background image of the gallery so it's not possible to detect outside clicking as there is technically no outside of the image.

**Comment by kas70** [comment]
is it possible to recognize clicking inside the image? i think this could also be an option.

**Comment by svbergerem** [comment]
This is working in the [blueimp gallery demo](https://blueimp.github.io/Gallery/).

**Comment by kas70** [comment]
ok, i think we should adopt the behaviour: 
-  clicking outside closes the gallery
- clicking inside fades out the navigation

**Comment by AugierLe42e** [comment]
> This is working in the blueimp gallery demo.

That's right. They have probably released an update.

**Comment by svbergerem** [comment]
Not really. The current version is 2.16.0 and we already use that version.

**Comment by AugierLe42e** [comment]
Weird. Our implementation uses image as background on a `div`. There must be a configuration to do somewhere, then.
