### ISSUE TITLE
change login button color

### ISSUE THREAD

**Issue by kas70** [diaspora/diaspora#6449]
this looks dull.
before:
![login_button2](https://cloud.githubusercontent.com/assets/922628/10249881/06aa3ace-6928-11e5-8aa7-02dc2450d80b.png)

after:
![login_button1](https://cloud.githubusercontent.com/assets/922628/10249882/06d2ec1c-6928-11e5-9c06-aca0679f78f9.png)

same could be done on the registration page.

**Comment by svbergerem** [comment]
Seems legit.
