### ISSUE TITLE
[RTL] Are using the wrong Unicode Control Character?

### ISSUE THREAD

**Issue by GreenLunar** [diaspora/diaspora#6453]
It appears you are using RLO (U+202E RIGHT-TO-LEFT OVERRIDE)

‮It appears you are using RLO (U+202E RIGHT-TO-LEFT OVERRIDE)

See https://joindiaspora.com/u/willhill in Hebrew interface.

Will Hill appears as ‮Will Hill

**Comment by GreenLunar** [comment]
Original:
Are you sure the RTL "contributors" or alleged users, that you communicate with, serve diaspora* interests? (DELETED)

Correction:
Are you sure the RTL "contributors" or alleged **RTL** users, that you communicate with, serve diaspora* interests? (DELETED)

**Comment by jhass** [comment]
Duplicate of #4785
