### ISSUE TITLE
Different result site after search

### ISSUE THREAD

**Issue by juliaviluhina** [diaspora/diaspora#6461]
Steps
1. Sign in Diaspora account
2. Using search field (ID = q) input full name of searched user (name)@(podLink)

Expected result
Site about searched user is shown (PodLink)/people/(ID)

Actual result
Seldom (I couldn't understand completely in what case) site (PodLink)/people?q=(fullname) is shown (in site only one contact is searched)
However often site (PodLink)/people/(ID) is shown
In both options right contact is searched, but result site is different.

In what way can I predict which site will be shown after search?

**Comment by svbergerem** [comment]
Did you try this with the current develop version? We are now using a different search widget and AFAIK it should always open the search page unless you select a user using your mouse or keyboard.

**Comment by juliaviluhina** [comment]
I have this problem in account of pod https://diaspora.koehn.com
Often search of eve_tjvi@diaspora.koehn.com gives me unexpected result site - (PodLink)/people?q=(fullname)

**Comment by svbergerem** [comment]
The pod you linked runs the stable code. I still think that the issue you described is one of the things I fixed in #6293 which will be part of the next major release 0.6.0.0. https://sechat.org/ and https://iliketoast.net/ are pods that run the development code if you are interested in trying this again with the latest code.

**Comment by svbergerem** [comment]
@juliaviluhina v0.6.0.0 has been released and https://diaspora.koehn.com has been updated. Could you try this again?

**Comment by juliaviluhina** [comment]
Since I developed tests for Diaspora it was changed a lot )

I check this issue on pod https://diaspora.koehn.com

These steps lead to opening page (PodLink)/people?q=(fullname)
1. Sign in Diaspora account
2. Using search field (ID = q) set full name of searched user (name)@(podLink) and press Enter

These steps lead to opening page  (PodLink)/people/(ID)
1. Sign in Diaspora account
2. Using search field (ID = q) set full name of searched user (name)@(podLink) 
3. In drop-down menu select appropriate item and click

The problem with different options after the same actions is done. 

I would like to propose  - if a user set full name of searched user (name)@(podLink) and press Enter, page  (PodLink)/people/(ID) of that user should be opened. Shouldn't it?

I checked this manually on browsers - chrome & firefox - all right
I checked this using Selenide tests 
   - in chrome - all right,
   - in firefox - I got a problem in opening page  (PodLink)/people/(ID) scenario - step 3(In drop-down menu select appropriate item and click) doesn't give the right result - basic account page is opened instead of (PodLink)/people/(ID) 
However, rather it is not Diaspora problem )

**Comment by svbergerem** [comment]
@juliaviluhina Thank you for testing this again. Since the bug has been fixed I'll close this issue.

> I would like to propose - if a user set full name of searched user (name)@(podLink) and press Enter, page (PodLink)/people/(ID) of that user should be opened. Shouldn't it?

There might be user@pod.com and user@pod.community.net and users who search for user@pod.com might be trying to find the other one.
