### ISSUE TITLE
change the default jsxc-emoticons

### ISSUE THREAD

**Issue by kas70** [diaspora/diaspora#6477]
imho they are really ugly.
![emoticons](https://www.jsxc.org/images/features/0006.png)

**Comment by jhass** [comment]
Agreed, they're horrible.

**Comment by Zauberstuhl** [comment]
@kas70 could you open this in https://github.com/diaspora/jsxc/. This is no diaspora issue

**Comment by kas70** [comment]
done. https://github.com/diaspora/jsxc/issues/132
