### ISSUE TITLE
Can't create a new post from my profile page depending of the link

### ISSUE THREAD

**Issue by moshpirit** [diaspora/diaspora#6501]
We have two different link associated with our accounts: "https://pod.url/u/username" and "https://pod.url/people/4l0t0fnumb3rs4ndl3tt3rs".
If I try to create a new post from my "https://pod.url/u/username" profile URL I can't, but if I do it from the "https://pod.url/people/4l0t0fnumb3rs4ndl3tt3rs" link then there's no problem. 

I noticed this in two different servers for months and now I'm seeing that a new big release is coming and the error is not fixed.

**Comment by denschub** [comment]
Fixed with #6503.
