### ISSUE TITLE
Receiving notifications for own comment on own reshare

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/diaspora#6506]
Related to #6498

**Comment by jhass** [comment]
@cmrd-senya want  to look into this?

**Comment by cmrd-senya** [comment]
Oops, sorry, I'll take a look!

**Comment by jaywink** [comment]
This should be a blocker for 0.5.4 imho if it is confirmed - 6 weeks is a long time to live with this ;)

Awesome work @cmrd-senya btw, but a little surprised the change was pushed to stable *after* code freeze.

**Comment by jhass** [comment]
@jaywink stable targets 0.5.5 already, the freeze creates a release branch.

**Comment by jaywink** [comment]
Ha, sorry, my bad ;)

**Comment by AugierLe42e** [comment]
Ok, it looks like I receive notifications for *some of my original posts* too. That disturbing. I have the impression of talking to myself.

**Comment by cmrd-senya** [comment]
Weird, but the problem reproduces randomly, mostly not reproducing. How about totally blocking a possibility to notify oneself?

I'll post a PR including tests and the block.

**Comment by cmrd-senya** [comment]
@Flaburgan, @svbergerem, any of those who manage to reproduce the issue.

Could you please apply a patch for enabling extended logging: 5ce13b6b4d6f0455af10c4a3808ababe7451dfed

Then, reproduce the issue and send me logs?

**Comment by cmrd-senya** [comment]
I managed to reproduce it locally.
It is a federation issue. It reproduces only when a user sharing with someone on a different pod. At the same time, it is not necessary to share a post of a remote user.

**Comment by cmrd-senya** [comment]
#6512 should fix it.
Please test.

**Comment by cmrd-senya** [comment]
I think it would have been nice if some of the reporters have tested it on their pods, before merge, but ok.

**Comment by jhass** [comment]
Well, it's a valid edge case to guard against, I wouldn't revert it if it doesn't resolve the problem and we can always reopen the issue.

**Comment by svbergerem** [comment]
#6512 fixed this for me. Let's see if @AugierLe42e is still able to reproduce this since he had more tests.

**Comment by Flaburgan** [comment]
FTR this is merged in d-fr since 9AM this morning, UTC+1. If anyone wants to test it again there.

**Comment by cmrd-senya** [comment]
Looks like it's fine now.

**Comment by AugierLe42e** [comment]
NTR on my side. Thx.
