### ISSUE TITLE
Protip dialog displays for too long in share bookmark

### ISSUE THREAD

**Issue by allinfinite** [diaspora/diaspora#6511]
"Protip: Auto-Shorten a url..." covers the message so I can't type and is displayed for way too long.. I find myself waiting half time it takes to post something.. maybe a 'tooltip' isn't the best solution for this.. Thanks!
![screen shot 2015-10-19 at 10 36 17 pm](https://cloud.githubusercontent.com/assets/2475429/10602073/eba8f61a-76b1-11e5-8096-9b2e62ccf7fc.png)

**Comment by jhass** [comment]
This is a custom modification by diasp.org. /cc @dmorley
