### ISSUE TITLE
Start conversation with youself

### ISSUE THREAD

**Issue by korun** [diaspora/diaspora#6513]
Why not?

I think this feature could be useful. Users will be store their ideas, some notes, etc.

**Comment by cmrd-senya** [comment]
vk.com supports it

**Comment by jhass** [comment]
I disagree, if we want to provide a notebook we should provide a notebook, not abuse another feature for it.

But I don't think we should provide a notebook, we're a social network, not a PIM application.

**Comment by cmrd-senya** [comment]
Well, after all, a user could add an empty aspect and store his notes there

**Comment by korun** [comment]
> user could add an empty aspect and store his notes there

Yes... But it even more strange than self-assigned private messages. %)

**Comment by korun** [comment]
BTW, I heard that facebook supports it too, but I'm not sure.

**Comment by theworldbright** [comment]
> I heard that facebook supports it too

It does indeed; I know a friend who uses it as a notebook.

**Comment by deXterbed** [comment]
> I heard that facebook supports it too

really?

**Comment by svbergerem** [comment]
I think that we should neither misuse the conversations feature, nor implement a notebook. I'll close this issue. We can always reopen it if there has been a succeeding proposal on loomio.
