### ISSUE TITLE
Suggested tag should not be selected by default

### ISSUE THREAD

**Issue by Globulle** [diaspora/diaspora#6515]
Problem : Let's pretend I'm interested by 'music' and I want to see the posts or the persons who are associated to that. I type #music in the search field and suggestions appear. If I press *enter*, the first suggestion is then selected and research is based on it (e.g #musical-humor) instead of what I typed.

It happens very often since you can easily find another tag which is longer than the one you are interested in and which begins by the same letters.

Maybe the suggested tags should be selected only when you press the down arrow?

**Comment by kas70** [comment]
Hi Globulle,
i just tested this on a pod running the dev-version. It seems like this has changed with the header overhaul. so it's working like intended.
can someone confirm this?

**Comment by svbergerem** [comment]
Yes, the search input has been ported to typeahead.js and selects the first search result only if you press the down arrow or click on the search result. This will be part of the 0.6.0.0 release.

**Comment by Globulle** [comment]
Great! Thank you!
