### ISSUE TITLE
Captcha not loading

### ISSUE THREAD

**Issue by mhzawadi** [diaspora/diaspora#6518]
Hi,

I have updated to the latest stable version and found the captcha image is not loading, I do get an http 200 back. But if I remove the code & time from the URL I get the below.

$("#").attr('src', '/simple_captcha?code=b04657610e7125fc3ff771e5fedb16b61e6e0582&amp;time=1445504672');
$("#simple-captcha-hidden-field-").attr('value', 'b04657610e7125fc3ff771e5fedb16b61e6e0582');

Log: [2015-10-22T09:04:42] INFO  PID-21317 TID-15186096 Rails: Started GET "/simple_captcha?code=250c4929c82c32bda55beb532ef0f008b496acf8&time=1445504681" for IPHERE at 2015-10-22 09:04:42 +0000
Pod version: 0.5.4.0-pbdc55f05
Pod URL: https://diaspora.horwood.biz/

**Comment by jhass** [comment]
Your ImageMagick setup has issues. If I curl the captcha URL it does return image data, but starts with
```
convert.im6: unable to access configure file `type.xml' @ warning/configure.c/GetConfigureOptions/591.
convert.im6: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1123.
convert.im6: unable to access configure file `delegates.xml' @ warning/configure.c/GetConfigureOptions/591.
convert.im6: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1123.
convert.im6: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1123.
convert.im6: unable to access configure file `colors.xml' @ warning/configure.c/GetConfigureOptions/591.
```

**Comment by mhzawadi** [comment]
Thanks @jhass, that make sense as I upgraded to Jessie.
Will run the install process and make sure everything is updated

**Comment by mhzawadi** [comment]
that did it, thanks.
