### ISSUE TITLE
Inconsistent Error 500 when it should be 403

### ISSUE THREAD

**Issue by noplanman** [diaspora/diaspora#6532]
I'm busy writing a [diaspora\* API class for WordPress](https://github.com/gutobenn/wp-to-diaspora/blob/master/lib/class-api.php) and have come across inconsistent error code responses.
When trying to delete a comment that I'm not authorised to, I correctly get a "403 Forbidden" response.
If I try the same with a post, I get a "500 Internal Server Error". This should also return "403 Forbidden" in my view.

This behaviour is forcing me to tweak my class in an illogical way, so I'm hoping this can be fixed at the source.

Looking at the diaspora\* code, `comments_controller.rb` has a [`respond_destroy_error`](https://github.com/diaspora/diaspora/blob/develop/app/controllers/comments_controller.rb#L66) method, which handles the issue correctly when a [`destroy`](https://github.com/diaspora/diaspora/blob/develop/app/controllers/comments_controller.rb#L28 "method in comments_controller.rb") fails.
Looking at the [`destroy`](https://github.com/diaspora/diaspora/blob/develop/app/controllers/posts_controller.rb#L51 "method in posts_controller.rb") method in `posts_controller.rb`, there is no error handling in case of a failure, which is why I assume an internal server error occurs.

P.S. Maybe this would be an issue to get me started into developing for diaspora\* and finally getting into RoR. If you feel this is a newbie issue, I'd love to try and give it a shot :smiley:

**Comment by noplanman** [comment]
Ok, digging a bit deeper, I saw that `aspect_memberships_controller.rb` has a [`rescue_from`](https://github.com/diaspora/diaspora/blob/develop/app/controllers/aspect_memberships_controller.rb#L78).

Is maybe just that missing in the `posts_controller.rb`?
I saw that the [post deletion method](https://github.com/diaspora/diaspora/blob/develop/app/services/post_service.rb#L36) correctly raises the `Diaspora::NotMine` error.

**Comment by theworldbright** [comment]
@noplanman Meh I missed that when I refactored the `post_controller` a couple months ago. I'll send over a fix.

**Comment by noplanman** [comment]
:+1: Thanks
