### ISSUE TITLE
Internationalize controller rescue_from text

### ISSUE THREAD

**Issue by theworldbright** [diaspora/diaspora#6534]
- https://github.com/diaspora/diaspora/blob/develop/app/controllers/posts_controller.rb#L25
- https://github.com/diaspora/diaspora/blob/develop/app/controllers/aspect_memberships_controller.rb#L71
- https://github.com/diaspora/diaspora/blob/develop/app/controllers/aspect_memberships_controller.rb#L75
- https://github.com/diaspora/diaspora/blob/develop/app/controllers/aspect_memberships_controller.rb#L79
- https://github.com/diaspora/diaspora/blob/develop/app/controllers/invitation_codes_controller.rb#L5

**Comment by tamatsyk** [comment]
Hi @theworldbright,
What would be the best way to test that i18n actually works after I update it.
And is it worth to cover such improvement with tests?

**Comment by tamatsyk** [comment]
Guys @theworldbright , @jhass,
I am really happy to improve at least somehow the diaspora project, however what I think you should know is that it is pretty hard to understand what is going on in some spec/controllers tests and I was not able to cover with rspec tests some of translations I added.
