### ISSUE TITLE
Replace Sidetiq

### ISSUE THREAD

**Issue by jhass** [diaspora/diaspora#6538]
Sadly it looks like Sidetiq turned into abandonware and is preventing Sidekiq upgrades now, in particular it it will prevent upgrading to the highly anticipated Sidekiq 4.0, which drops the Celluloid dependency.

So we need to find and adopt a replacement.

Candidates:

* [sidekiq-dejavu](https://github.com/felixbuenemann/sidekiq-dejavu)
* [sidekiq-cron](https://github.com/ondrejbartas/sidekiq-cron)
* [sidekiq-repeat](https://github.com/FlavourSys/sidekiq-repeat)
* [sidekiq-scheduler](https://github.com/Moove-it/sidekiq-scheduler)

**Comment by AugierLe42e** [comment]
Do you have propositions in mind?

**Comment by jhass** [comment]
I didn't do an extensive research yet, else I would've included that.

**Comment by AugierLe42e** [comment]
What about replacing Sidekiq itself? @jaywink talked about [goworkers](https://www.goworker.org/)?

**Comment by Raven24** [comment]
@AugierLe42e That's not a simple drop-in replacement. It's a background-worker system implemented in Go, where we can't re-use any of the existing ruby/rails models - we'd have to reimplement them in Go. I'm not saying that's necessarily a showstopper, but someone would have to do the porting of everything worker-related.

**Comment by jaywink** [comment]
I don't think I proposed it, it was more like "hey look goworker" just like I say "hey look neat" about 100 other things during a week :)

Anyway, we could always just use crons + rake tasks :P That could be kept as one option, but would require additional configuration for podmins.

**Comment by AugierLe42e** [comment]
@Raven24: From what I see on the web site, the workers can be called from ruby code. So only the workers would have to be rewritten, right? I don't know the amount of work this represent. Anyway, it's just some idea.

@jaywink : Hmm, I don't think this is a good idea to increase the amount of work for podmins :/

**Comment by jhass** [comment]
Yeah, I would strongly prefer to not use cron.

**Comment by AugierLe42e** [comment]
A quick research gave me three options:

 * [sidekiq-cron](https://github.com/ondrejbartas/sidekiq-cron),
 * [sidekiq-repeat](https://github.com/FlavourSys/sidekiq-repeat),
 * [sidekiq-scheduler](https://github.com/Moove-it/sidekiq-scheduler).

**Comment by balasankarc** [comment]
GitLab uses sidekiq-cron without any issues I think.

**Comment by pravi** [comment]
gitlab uses sidekiq-cron, so that could be a preferred option.

**Comment by tsigo** [comment]
See https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1982 for more discussion about GitLab moving to sidekiq-cron.

**Comment by jaywink** [comment]
Looks ok to me. Confusingly doesn't require messing with crontabs :P

Removing sidetiq seems pretty urgent due to better performance in new sidekiq.

**Comment by cmrd-senya** [comment]
Sorry for stealing a job from a newcomer maybe? :)

**Comment by cmrd-senya** [comment]
Hmm, but test fail with ```/home/travis/build/diaspora/diaspora/vendor/bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:332:in `rescue in establish_connection': Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED) (Redis::CannotConnectError)```.

What could that mean? Locally runs fine.

**Comment by balasankarc** [comment]
Redis server not getting started?

**Comment by cmrd-senya** [comment]
Yeah, but it runs fine locally. Maybe some bundler ```bundle install``` issues?

**Comment by denschub** [comment]
Closes via #6616
