### ISSUE TITLE
add participation button on mobile site

### ISSUE THREAD

**Issue by lu-x** [diaspora/diaspora#6540]
##

**Comment by netoeuler** [comment]
What's participation button? 'Report', 'Ignore', 'Active notification' and 'Hide"?

**Comment by jaywink** [comment]
'Active notification' - ie enable notifications.

![selection_212](https://cloud.githubusercontent.com/assets/1174866/12521888/1619741c-c156-11e5-9f76-06a0396985e8.png)

**Comment by netoeuler** [comment]
Yes. I use in portuguese, so I try to translate it. 
So, the answer to my question is 'yes'? If yes, I can do it.

**Comment by jaywink** [comment]
Go for it! :)

**Comment by Flaburgan** [comment]
@netoeuler I guess you're not working on it anymore?

**Comment by netoeuler** [comment]
No, I had problems to set up an enviroment to contribute to Diaspora and I don't have time to do this right now. Sorry about that. :/

**Comment by Flaburgan** [comment]
This actually is a duplicate of https://github.com/diaspora/diaspora/issues/4225, closing.
