### ISSUE TITLE
Error on page https://diasporafoundation.org

### ISSUE THREAD

**Issue by Petrouchka** [diaspora/diaspora#6553]
On the page https://diasporafoundation.org (in french), the link toward pods list is missing :
"Une liste des pods de la communauté est disponible ici %{poduptime}."

**Comment by jhass** [comment]
Please open the issue at https://github.com/diaspora/diaspora-project-site

Thank you.

**Comment by Petrouchka** [comment]
Done, thank you for your information.
https://github.com/diaspora/diaspora-project-site/issues/78
