### ISSUE TITLE
Upgrade to jQuery 2

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/diaspora#6557]
diaspora currently relies on jQuery 1.11.2. Nothing stops us to upgrade to jQuery 2.1.4 except diaspora_jsxc which requires exactly 1.11.2. I just tested which a patched version of the diaspora_jsxc locally, everything seems to work well. @Zauberstuhl, do you have an opposition onn patching diaspora_jxsc so we can upgrade to jQuery 2?

**Comment by svbergerem** [comment]
> jQuery 2.x has the same API as jQuery 1.x, but does not support Internet Explorer 6, 7, or 8. [...] Since IE 8 is still relatively common, **we recommend using the 1.x version unless you are certain no IE 6/7/8 users are visiting the site**.

Is there any reason why we should switch to jQuery 2.x?

**Comment by Flaburgan** [comment]
@svbergerem we don't actually support IE 6/7/8 at all. I don't know about the current code but 3 years ago diaspora* wasn't working at all with those browsers and we didn't work on this since that moment, so I assume this is not a blocker.

**Comment by AugierLe42e** [comment]
> Is there any reason why we should switch to jQuery 2.x?

jQuery 2.x code is lighter so I suppose that optimises performance. Originally, this is related to #6555 whiwh uses Hammer.JS. The jQuery plugin depends on jQuery 2. This is not really blocking as I've just copied the file in `vendor/assets/javascripts` instead of using th rails-asset gem, but I though it could be interresting to raise this issue to discuss the topic.

**Comment by Zauberstuhl** [comment]
that could hurt. but I can try it in the next view days. also I have to talk with upstream about it

diaspora/jsxc#134

**Comment by Zauberstuhl** [comment]
//adding @pravi 

he is currently checking if we can use jquery 2 out of the box with the debian package

**Comment by AugierLe42e** [comment]
Ping.

**Comment by pravi** [comment]
@AugierLe42e https://github.com/diaspora/jsxc/issues/134#issuecomment-160160358

**Comment by svbergerem** [comment]
Fixed by #6944.
