### ISSUE TITLE
Ergonomy suggestion

### ISSUE THREAD

**Issue by EricC-59** [diaspora/diaspora#6559]
Diaspora's robot sends e-mails with headers such as:

```
From: "podmin@podname.org (diaspora*)" <no-reply@podname.org>
To: "me@podname.org" <me@example.com>
```

… or:

```
From: “Firstname Lastname (diaspora*)” <no-reply@podname.org>
To: “Myfirstname Mylastname” <me@example.com>
```

Given the fact that (too) many mail user agents hide e-mail addresses, the users may see this:

> From: podmin@podname.org (diaspora*)
> To: me@podname.org

This can be disturbing for some users, because it seems that they get an e-mail on me@podname.org… which is not an e-mail address, nor podmin@podname.org!

Worse: those users can see that:

> From: Firstname Lastname (diaspora*)
> To: Myfirstname Mylastname

In this case, it seems logical to use the "reply" button to reply to "Mr Lastname"...  which, of course, results in an “Undelivered Mail Returned to Sender” (no-reply@podname.org).

Here is my suggestion:
- Do not directly use the sender's name in the From: field. Instead, use a text like "Diaspora\* (on behalf of Firstname Lastname)"
- **Never** use Diaspora\* identifiers in an e-mail address description. Using nothing is less disturbing.

See with my two examples:

```
From: "podmin@podname.org (diaspora*)" <no-reply@podname.org>
To: "me@podname.org" <me@example.com>
```

becomes

```
From: "Diaspora*” <no-reply@podname.org>
To: <me@example.com>
```

and the end-user sees:

> From: Diaspora*
> To: me@example.com

and

```
From: “Firstname Lastname (diaspora*)” <no-reply@podname.org>
To: “Myfirstname Mylastname” <me@example.com>
```

becomes

```
From: "Diaspora* (on behalf of Firstname Lastname)” <no-reply@podname.org>
To: "Myfirstname Mylastname” <me@example.com>
```

and the end-user sees:

> From: Diaspora\* (on behalf of Firstname Lastname)
> To: "Myfirstname Mylastname”

More newbie-friendly, isn't it?

Note that my suggestion comes from a real life case, where I tried to convince a Facebook user to join me on Diaspora*. With this e-mail issue, he told me:

> I don't understand anything to your diaspora thing. It's too complicated. (..) I even couldn't reply to _your_ e-mail from diaspora. I did reply and send, and the e-mail came back with "undelivered mail returned to sender"
##

**Comment by Flaburgan** [comment]
It's a good point. In a perfect world, I would have loved to see the diaspora server handling a mail to a diaspora* id to make it appear as the private message in diaspora*, but this is probably not going to happen so I guess your suggestions can be applied.

**Comment by polsVoice** [comment]
Yah. I would love to see D* have support for email, because email is the biggest "social network" on Earth. I keep thinking that if somebody could engineer an email client that had a social-network interface, it would be a game-changer. However, I don't know when or if such a thing is possible for Diaspora.

**Comment by jaywink** [comment]
It's more of a "requires a hell load of additional configuration" thing. A pod is already hard to configure. Having email as a core feature would make that *at least* 2x more harder.

**Comment by Globulle** [comment]
@jaywink Would it be possible to have the feature available, and only activate it on pods whom admin is capable/willing to configure it? This could be listed as an optional service, in the same way as Fb/Twitter/wordpress support.

**Comment by jaywink** [comment]
Anything is possible if someone writes good code to make it work :)

**Comment by Rete2** [comment]
Hello community :)
@netagonen and me are doing the Rails Girls Summer of Code (July - September) on the diaspora* project. We started working on this issue as a first issue for our summer. We have found the file app/mailers/notification_mailers/base.rb (line 42) to include the code that needs to be changed for this issue. 
So far our approach is to
- change app/mailers/notification_mailers/base.rb (line 42) into: `headers[:from] = "\"Diaspora* (on behalf of #{@sender.name})\" <#{AppConfig.mail.sender_address}>" if @sender.present?`
- change app/mailers/notification_mailers/base.rb (line 37) into from: `"\"Diaspora* \" <#{AppConfig.mail.sender_address.get}>"` (We are not sure yet if this works)

However, we have a few questions/remarks regarding the issue:
1.There are different email cases:
	a) sender present: in the examples above it says that the user gets emails from:  `"podmin@podname.org (diaspora*)" <no-reply@podname.org>` or `"Firstname Lastname (diaspora*)" <no-reply@podname.org>`. Does line 42 apply for both cases? That means could `sender.name` be `podmin@podname.org` or `Firstname Lastname`?  
	b) no sender present: there should be only the `no-reply@podname.org` (AppConfig.mail.sender_address), which is true e.g. when I get a password reset link.
2. Also I sometimes get emails from `"username@podname.org"` not `"Firstname Lastname"` even though there is a sender present in this case. Where are the sender attributes defined? We found so far only the `sender_address` set to `no-reply@podname.org`, but couldn't figure out the other sender attributes. We guess that it must be stated somewhere that emails will be sent as `Firstname Lastname` or as `username@podname.org`
3. One small thing: When I get emails the name of the sender doesn't show as `"Firstname Lastname" (diaspora*)`but `Firstname Lastname (diaspora*)`. I guess it is not so important but from the code I read that I should get emails the quotes.

We hope our questions are not too confusing :slightly_smiling_face:
Thanks for your help!

**Comment by Flaburgan** [comment]
As far as I know, there is no automatic fallback on the name property from the name (concatenation of first and last name) to the diaspora ID (sometimes found as diaspora_handle in the code). So there is a `author = (sender.name != null) ? sender.name : sender.diaspora_handle` somewhere. I'm not familiar with that part of the code sorry but something sure is, the user can have a empty name, so you have to handle that case.

I'm actually doing something a bit similar in https://github.com/diaspora/diaspora/pull/7484

**Comment by Flaburgan** [comment]
Actually forgot what I just said, the name is always set: https://github.com/diaspora/diaspora/blob/develop/app/models/person.rb#L244 So it is the first name + last name if at least one of them is not null, else the handle. So I'm not sure about what we want to do if the name is actually the handle.

**Comment by SuperTux88** [comment]
First: @Rete2 and @netagonen thanks for working on this.

So:
> Does line 42 apply for both cases? That means could `sender.name` be `podmin@podname.org` or `Firstname Lastname`?

Yes, as @Flaburgan already mentioned, `sender.name` has the diaspora ID as fallback when there is no name. So we probably need to add a method that returns the name or `nil` when there is no name, so we can handle that case better. That could also be used for the issue @Flaburgan is solving.

> b) no sender present

As you mentioned, that is for when there is no direct sender (password reset for example).

> 2. Also I sometimes get emails from `"username@podname.org"` not `"Firstname Lastname"` even though there is a sender present in this case.

There is always a `@sender` present for comments, likes, mentions, messages or start sharing. The difference is, that one has a name set in the profile, and the other doesn't.

> 3. One small thing: When I get emails the name of the sender doesn't show as `"Firstname Lastname" (diaspora*)` but `Firstname Lastname (diaspora*)`.

It is `"Firstname Lastname (diaspora*)" <no-reply@podname.org>`, but your email client removes the quotes when displaying it. Just look at the sourcecode of an email (Ctrl+U in Thunderbird for example)

**Comment by netagonen** [comment]
Working on this issue, we noticed that in the notifier_spec.rb file, there are no tests for the FROM header in case there is no sender. We found two cases like this in this spec file, in line 471 -
 confirm_email, and line 502 - csrf_token_fail. We added a test for each one of the cases and were wondering: are there any other cases of emails with no sender, so we could add a test for them too? (you can find the commit [here](https://github.com/codebearsteam/diaspora/commit/2381602269b2fdcaf115cd760a74d9a6ac422419))

**Comment by SuperTux88** [comment]
When a user reports a post/comment the mail doesn't have a @sender either.

By the way: When you change the from to `Diaspora* (on behalf of #{@sender.name})`, that should be translatable.
