### ISSUE TITLE
/public cannot accessed public

### ISSUE THREAD

**Issue by DeusFigendi** [diaspora/diaspora#6564]
The - pretty new - feature to view all public posts on a pod asks me to sign up or sign in. For exaple: https://nerdpol.ch/public/ https://diasp.org/public https://wk3.org/public try whereever you're **not** logged in.

I'd guess it is not intended that public posts can't be accessed from public.
##

**Comment by Zauberstuhl** [comment]
+1

**Comment by grahamperrin** [comment]
I was steered to this issue after mentioning that https://framasphere.org/public is not public. 

Please, is there any technical or design obstacle to this issue?

**Comment by Flaburgan** [comment]
This would be nice to answer people [like this](https://twitter.com/kozman14/status/978576469302693888). To give a small taste of diaspora* to the external world.

**Comment by grahamperrin** [comment]
Thanks 🥇 

![public](https://user-images.githubusercontent.com/192271/40861152-f0586ec8-65df-11e8-976b-e11aded308f7.png)
