### ISSUE TITLE
Signatures in the retractions federation seem useless

### ISSUE THREAD

**Issue by cmrd-senya** [diaspora/diaspora#6566]
Derived from [here](https://github.com/SuperTux88/diaspora_federation/pull/17).

Signatures presented in federation entites RelayableRetraction and SignedRetraction seem useless. (verification present [here](https://github.com/diaspora/diaspora/blob/develop/lib/diaspora/federated/relayable_retraction.rb#L46-L53) and [here](https://github.com/diaspora/diaspora/blob/develop/lib/diaspora/federated/signed_retraction.rb#L92-L94)).

It seems to me that signature checks for Retractions of every kind doesn't make much sense. In fact every Retraction is proved only by the signature of its sender (it's different from the Relayable federation where we had to pass the author signature, because parent author is allowed to retract comments of any author). And the signature of the sender has been checked at the Salmon level already([here](https://github.com/diaspora/diaspora/blob/develop/lib/postzord/receiver/public.rb#L21) and [here](https://github.com/diaspora/diaspora/blob/develop/lib/postzord/receiver/private.rb#L18)). So maybe abolishment of signatures for Retractions (done gradually) won't make any harm.

For retractions abolishment of signatures can be done pretty softly, by just moving to Entities::Retraction.

More information on how signatures of retractions work can be found [here](https://github.com/cmrd-senya/diaspora_federation/commit/747ee240d7df50fa06dd72b6fd4d4cfded12c83f#diff-436c79af9721bbd73ef39c04d11b0fc7R3).

Also, in fact, for the Relayables it's only necessary to pass author signature and the parent author signature is redundant for the same reasons - it just repeats Salmon signature check.

The good thing is that the abolishment of the redundant signatures will reduce load on the servers and bandwith usage by diaspora pods.

TODO:
- [ ] Send Retraction instead of SignedRetraction
- [ ] Send Retraction instead of RelayableRetraction
- [ ] When all the federation adopts sending Retractions instead of the two other entities, wipe SignedRetraction and RelayableRetraction from the source.

The other possible solution, is to make signed_retraction and relayable_retarction xml entities alias to usual retraction on receive process. Thus we could wipe the other retractions sooner from the up-to-date code.
##

**Comment by SuperTux88** [comment]
Fixed with #7436
