### ISSUE TITLE
Spinner won't disappear when loading delted twitter post

### ISSUE THREAD

**Issue by manuelVo** [diaspora/diaspora#6571]
If a tweet that is linked in a post gets deleted a loading spinner will be rendered above the post.

![tweetloadbug](https://cloud.githubusercontent.com/assets/1705157/11475893/1db02a7c-9780-11e5-85c7-195b877d40bf.png)

The post in the screenshot is public. [It can be found here](https://pod.geraspora.de/posts/4265752).

**Comment by jhass** [comment]
Probably not a bug, look into your browsers error console please.

**Comment by manuelVo** [comment]
Indeed Chrome does report an error (while Firefox doesn't). I think that error still should be handled in some way. IMO that sticking spinner makes the page look broken...

**Comment by jhass** [comment]
I don't think the spinner is from us, but rather from the Twitter embed code.

**Comment by manuelVo** [comment]
Just talked with DenSchub a bit. This really seems to be a bug in the Twitter embed code.

**Comment by Flaburgan** [comment]
Can you please report a bug there, link it here and then close this issue?

**Comment by denschub** [comment]
I'm closing this as an upstream bug. (and because I doubt twitter will change this behavior.)
