### ISSUE TITLE
duplicate "also commented" note from local users 

### ISSUE THREAD

**Issue by tchncs** [diaspora/diaspora#6579]
1. like something on a post from an user on my pod
2. someone also commented something on this post
3. i receive two notifications

This pod is on the master branch... .
Other users dont have this problem.
I guess it only happened, if the "also commented" user is from an external pod... .
The last time, it happened from nerdpol.ch - to reproduce it with my old Geraspora acc has failed.

**Comment by tchncs** [comment]
So...its labeled now... .
I will love to give more information. 
I cant find anything interesting in the logs. Sadly.
Also it doesnt happens on *every* post.
Also again, it doesnt only happens on my "own" pod. 
I maintaining an second one, which is not public yet. 
The first guys from the community where the pod is for, joined a few hours ago. 
I received two notifications for just one comment under a #newhere post i just commented.

Its Debian sid with stable-updates and Ruby 2.1.7.
My Pod is using Ruby 2.1.5 on Debian 8.2.

**Comment by denschub** [comment]
@SuperTux88 didn't you some time in the past talk about this?

**Comment by denschub** [comment]
Closed by #6873.
