### ISSUE TITLE
Result of liking is shown only after refresh (in contact's stream of unlinked user) 

### ISSUE THREAD

**Issue by juliaviluhina** [diaspora/diaspora#6583]
Problem appears for unlinked users of one pod
Prerequisites
User2 has a public post

Steps
1. Sign in Account of user1
2. Search user2
3. Contact's stream of user2 is loaded (<pod>/people/<id>)
4. Like public post of user2

Expected result
Information about liking appears straight away

Actual result
Information about liking appears only after refresh site

However, similar problem with unliking does not appear. Also similar problem in stream does not appear too.

**Comment by denschub** [comment]
I am not able to reproduce this. Which diaspora version is running on the pod you've tested and what browser do you use?

**Comment by juliaviluhina** [comment]
I saw this problem in pod - https://diaspora.koehn.com , in browser - firefox
However, now I test it and this error isn't
I think, this problem solved yet

**Comment by denschub** [comment]
Thank you! :)
