### ISSUE TITLE
Message has redundant "conversation_guid" in it XML representation

### ISSUE THREAD

**Issue by cmrd-senya** [diaspora/diaspora#6588]
In its federated XML representation Message model have property [conversation_guid](https://github.com/diaspora/diaspora/blob/develop/app/models/message.rb#L10) and property [parent_guid](https://github.com/diaspora/diaspora/blob/develop/lib/diaspora/relayable.rb#L12) from the Relayable inclusion. Looks like these properties duplicate each other. I think the former could be removed in favour to the latter. However it could ruin signature verifications, so it's not possible, before the new method of signature computation is adopted for the whole federation.
##

**Comment by SuperTux88** [comment]
see: https://github.com/SuperTux88/diaspora_federation/issues/36

**Comment by SuperTux88** [comment]
Fixed with #7436
