### ISSUE TITLE
Add settings for types of notifications in dropdown

### ISSUE THREAD

**Issue by svbergerem** [diaspora/diaspora#6609]
Some users receive a lot of notifications and are thus only interested in notifications of some type (e.g. only comments). Those users could decide with a few checkboxes in the settings which notifications they would like to see in the dropdown. All types are enabled by default.
##

**Comment by AugierLe42e** [comment]
:+1:

**Comment by goobertron** [comment]
Yes please. I was sure I had started a ticket for this ages ago, and have just looked for it but can't find it. Would love to see the possibility to enable/disable notifications within the app (in the dropdown) as well as email notifications.

**Comment by svbergerem** [comment]
Duplicate of #7686, which already has a linked PR.

**Comment by goobertron** [comment]
Oh sorry, I didn't find this issue when I created #7686.

**Comment by svbergerem** [comment]
No problem. The description of the issue you opened is much better and it even has a mock-up. :+1:
