### ISSUE TITLE
Feed is frozen after upgrade to 0.5.5.1

### ISSUE THREAD

**Issue by nazar-pc** [diaspora/diaspora#6614]
I was using something slightly below 0.5.5 and everything worked fine (probably, 0.5.4 or something).
But when I upgraded to 0.5.5.1 everything seems working, I can browse posts from users on other pods (including ones I've never seen before), but my feed is frozen - I do not see any new posts or comments since upgrade.
I'm not Ruby developer, what should I do to determine an issue and fix it?
My pod is diaspora.mokrynskyi.com, ruby version is latest 2.1.
##

**Comment by jhass** [comment]
Make yourself an admin and check `/sidekiq`, are jobs being processed or are the counters only ever increasing?

**Comment by nazar-pc** [comment]
Looks like they are frozen as well and plot have only zeros at the end. What does this mean?

**Comment by jhass** [comment]
This means your sidekiq worker isn't running or not listening to the same Redis instance. Check your `log/sidekiq.log` and `log/eye_*.log`

**Comment by nazar-pc** [comment]
There was nothing in logs, last line in sideiq log was `INFO: Booting Sidekiq 3.4.2 with redis options {:namespace=>nil, :url=>nil}`
I hate this kind of magic, I've tried to restart instance multiple times (Docker container), but this time it helped, everything is up and running fine.

**Comment by nazar-pc** [comment]
I'm on 0.5.6.3 and feed is frozen again.
The interesting thing is that sidekiq logs for today are absent even though I've restarted server few times.
There are no errors in eye_processes_stderr.log and eye_processes_stdout.log files.

**Comment by jhass** [comment]
[Insert previous question here.]

**Comment by nazar-pc** [comment]
Situation is exactly the same - sidekiq plot for today contains only zeroes.
There is some inconsistency, it worked magically and after upgrade+restart (multiple restarts even) stopped working magically as well.

**Comment by nazar-pc** [comment]
Why might sidekiq not running if logs do not contain anything about this?

**Comment by jhass** [comment]
I don't know, I've only seen issues that produced some log output somewhere.

**Comment by nazar-pc** [comment]
Unbelievable... just wanted to capture output (I have diaspora in Docker container) and it started fine once again...
I'll reopen when encounter it next time.

**Comment by nazar-pc** [comment]
The same again, was stuck on previous release, now I have 0.5.7.0-p56ebcc76 and still the same.

Starting Redis (stdout + stderr):
```
[6] 22 Feb 18:08:22.500 # Warning: no config file specified, using the default config. In order to specify a config file use /usr/bin/redis-server /path/to/redis.conf
                _._..................................................
           _.-``__ ''-._.............................................
      _.-``    `.  `_.  ''-._           Redis 2.8.17 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._...................................
 (    '      ,       .-`  | `,    )     Running in stand alone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 6
  `-._    `-._  `-./  _.-'    _.-'...................................
 |`-._`-._    `-.__.-'    _.-'_.-'|..................................
 |    `-._`-._        _.-'_.-'    |           http://redis.io........
  `-._    `-._`-.__.-'_.-'    _.-'...................................
 |`-._`-._    `-.__.-'    _.-'_.-'|..................................
 |    `-._`-._        _.-'_.-'    |..................................
  `-._    `-._`-.__.-'_.-'    _.-'...................................
      `-._    `-.__.-'    _.-'.......................................
          `-._        _.-'...........................................
              `-.__.-'...............................................

[6] 22 Feb 18:08:22.501 # Server started, Redis version 2.8.17
[6] 22 Feb 18:08:22.501 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.o
[6] 22 Feb 18:08:22.661 * DB loaded from disk: 0.160 seconds
[6] 22 Feb 18:08:22.661 * The server is now ready to accept connections on port 6379
```
Starting diaspora (stdout + stderr):
```
WARNING: Project gemset is diaspora but you are using ruby-2.1.5
WARNING: Setting port via configuration is deprecated, set listen instead. See the updated config/diaspora.yml.example.
WARNING:
*****************************************************************
curl does not support async DNS, this can cause Sidekiq to crash!
Please update curl to version 7.32, see issue
https://github.com/diaspora/diaspora/issues/4202 for details
*****************************************************************

Starting Diaspora in production mode on port 3000 with 1 Sidekiq worker(s).
```
eye_processes_stderr.log:
```
I, [2016-02-22T18:08:31.077282 #604]  INFO -- : Refreshing Gem list
I, [2016-02-22T18:08:37.587908 #604]  INFO -- : listening on addr=0.0.0.0:3000 fd=11
I, [2016-02-22T18:08:37.602796 #604]  INFO -- : master process ready
I, [2016-02-22T18:08:37.613731 #615]  INFO -- : worker=0 ready
I, [2016-02-22T18:08:37.624619 #618]  INFO -- : worker=1 ready
*.*.*.*, 172.17.42.1 - - [22/Feb/2016:18:09:34 +0000] "GET /stream HTTP/1.0" 200 - 0.3806
*.*.*.*, 172.17.42.1 - - [22/Feb/2016:18:09:35 +0000] "GET /stream?_=* HTTP/1.0" 200 - 0.4340
```
eye_processes_stdout.log:
```
Rack::SSL is enabled
```
production.log:
```
[2016-02-22T18:08:37] INFO  PID-604 TID-13857720 DiasporaFederation: successfully configured the federation library
[2016-02-22T18:09:34] INFO  PID-615 TID-13857720 Rails: Started GET "/stream" for *.*.*.* at 2016-02-22 18:09:34 +0000
[2016-02-22T18:09:34] INFO  PID-615 TID-13857720 ActionController::Base: Processing by StreamsController#multi as HTML
  Rendered aspects/_aspect_listings.haml (0.8ms)
  Rendered tags/_followed_tags_listings.haml (0.8ms)
  Rendered publisher/_aspect_dropdown.html.haml (3.1ms)
  Rendered shared/_public_explain.haml (6.2ms)
  Rendered publisher/_publisher.html.haml (66.8ms)
  Rendered aspects/_no_posts_message.haml (0.8ms)
  Rendered aspects/_aspect_stream.haml (143.7ms)
  Rendered shared/_links.haml (2.1ms)
  Rendered shared/_right_sections.html.haml (10.8ms)
  Rendered streams/main_stream.html.haml within layouts/with_header (169.5ms)
  Rendered layouts/_header.html.haml (1.5ms)
  Rendered layouts/_open_graph.haml (1.5ms)
  Rendered layouts/application.html.haml (23.4ms)
[2016-02-22T18:09:34] INFO  PID-615 TID-13857720 ActionController::Base: Completed 200 OK in 348ms (Views: 182.0ms | ActiveRecord: 70.1ms)
[2016-02-22T18:09:35] INFO  PID-615 TID-13857720 Rails: Started GET "/stream?_=*" for *.*.*.* at 2016-02-22 18:09:35 +0000
[2016-02-22T18:09:35] INFO  PID-615 TID-13857720 ActionController::Base: Processing by StreamsController#multi as JSON
[2016-02-22T18:09:35] INFO  PID-615 TID-13857720 ActionController::Base:   Parameters: {"_"=>"*"}
[2016-02-22T18:09:35] INFO  PID-615 TID-13857720 ActionController::Base: Completed 200 OK in 430ms (Views: 206.3ms | ActiveRecord: 150.8ms)

```
sidekiq.log: not even created

**Comment by svbergerem** [comment]
```
*****************************************************************
curl does not support async DNS, this can cause Sidekiq to crash!
Please update curl to version 7.32, see issue
https://github.com/diaspora/diaspora/issues/4202 for details
*****************************************************************
```

Did you check the issue? Sounds to me like this could have caused Sidekiq to crash and then you wouldn't receive any updates.

**Comment by nazar-pc** [comment]
I do not see any crash anywhere, according to mentioned issue I'd get it somewhere.
And everything worked in past with this very configuration (and occasionally works again, but I don't know why).

**Comment by Flaburgan** [comment]
@nazar-pc we released a new major version, can you please upgrade your pod to 0.6 and ruby 2.3 following [this guide](https://wiki.diasporafoundation.org/Updating#Updating_diaspora.2A_0.5_to_diaspora.2A_0.6) and tell us if you are still experimenting this issue?

**Comment by nazar-pc** [comment]
I know, but I've tried few times older releases, saw no difference and stopped upgrading. My instance is basically dead for last half a year.
I'll upgrade everything today and let you know whether it works.

**Comment by nazar-pc** [comment]
After update and few refreshes of stream page, besides 7 moths old posts I see a single post from 4 hours ago, few minutes later I see 1 more profile from 10 hours ago.
I  think there should be a bit more than 1 post from last 7 months, or this is an expected behavior?
Any profile looks very outdated, for instance, your profile:
![2016-09-05 22-53-12](https://cloud.githubusercontent.com/assets/928965/18256266/a2590aa6-73bb-11e6-9989-9da970548bf5.png)

**Comment by Flaburgan** [comment]
Was your pod online during this time? Can you check at `/sidekiq` if you have jobs in queues? If you have a lot of errors? Can you please try to write a public post, to see if I can see it? You ssl config [looks ok](https://www.ssllabs.com/ssltest/analyze.html?d=diaspora.mokrynskyi.com) so I guess the problem is not here (you correctly added the intermediate .pem certificate and uncommented the good line about authorities in diaspora.yml?)

**Comment by nazar-pc** [comment]
It was online most of that months, however, it didn't get any updates because of this issue, or what did you mean?

I'm slowly getting more posts, 8 of them right now.

Here is how sidekiq looks in my dashboard (I'm not Ruby developer, not familiar with it at all):
![2016-09-06 04-24-51](https://cloud.githubusercontent.com/assets/928965/18259203/246a8c30-73ea-11e6-805e-76823d963028.png)

Just added new post myself, can you see it?

My setup is a bit more complex than that. Diaspora is running in Docker container (as HTTP, with proper reverse proxy config in Nginx), on host system I have another reverse proxy with Nginx (HTTP/2, LetsEncrypt) into mentioned container and on top of all this there is CloudFlare (which reduces SSL test results from A+ to just A).

**Comment by Flaburgan** [comment]
So you have posted enqueued and I receive your post, so the situation looks better than before 0.6. However, your ratio Processed / Failed is still to high. Did you solve the "Too old curl" warning? You need at least curl 7.32 to run diaspora*. 0.6 comes with a whole new federation which could have mitigated the problem, but you should still upgrade your curl. The number of posts enqueued is too high too, your pod looks too slow to process the data. So the posts have been received but waiting in Sidekiq to be processed. Maybe you could increase the number of workers.

**Comment by nazar-pc** [comment]
I wouldn't say Core i7-4770 @ 3.40GHz with 32 GB of DDR3 RAM and SATA3 SSD is that slow server and I didn't enforce any particular limit on Diaspora container.

Upgraded Wheezy to Jessie in container, now curl is at version 7.38, so it should be fine now anyway.

I'm wondering if sidekiq should really look like this now (I've also removed old versions of ruby with `rvm cleanup all`):
![2016-09-06 14-44-25](https://cloud.githubusercontent.com/assets/928965/18272478/adbff4d8-7440-11e6-8add-e15553737f44.png)

Few more posts appeared, but nothing groundbreaking. I'm curious whether I can force it to clean caches and re-fetch all posts in stream again?

**Comment by Flaburgan** [comment]
Wow why is the enqueued queue empty now? You lose all the incoming posts :sdiaspora/diaspora a écrit :I wouldn't say Core i7-4770 @ 3.40GHz with 32 GB of DDR3 RAM and SATA3 SSD is that slow server and I didn't enforce any particular limit on Diaspora container.

Upgraded Wheezy to Jessie in container, now curl is at version 7.38, so it should be fine now anyway.

I'm wondering if sidekiq should really look like this now (I've also removed old versions of ruby with rvm cleanup all):


Few more posts appeared, but nothing groundbreaking. I'm curious whether I can force it to clean caches and re-fetch all posts in stream again?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




Envoyé depuis Firefox OS

**Comment by nazar-pc** [comment]
I have no idea, what are they and are they lost forever?

**Comment by nazar-pc** [comment]
While Redis is expected to store data to disk, I suspect something happened to it during upgrade.
As data on my pod and other pods are still OK, there should be a way to get everything in sync.
I'm not sure what will happen to my and to other pods if I restore backup of the container (with some recent data being lost).

**Comment by Flaburgan** [comment]
Do you still have this problem? Mind joining #diaspora on IRC Freenode to solve once and for all? We don't like having setup issue handling for months on github.

**Comment by nazar-pc** [comment]
Issue was never fixed. Now I feel like instance was stuck at some task in queue, but since I've lost everything in Redis on upgrade (not sure whose fault is that, but I didn't make anything special) I can see all new posts. However, old and not updated posts from the period while my feed was frozen are not available to me and I feel like they will never be, since I'm not aware of any possibility to trigger complete synchronization.

I don't want to chat on IRC since this is not a big enough issue for me honestly right now. Feel free to close this issue, but there is still something inside that might cause similar issue to someone in future.

**Comment by cmrd-senya** [comment]
> Feel free to close this issue, but there is still something inside that might cause similar issue to someone in future.

Since you don't provide steps to reproduce, it can only be considered as "works for us" right now. If there is a bug in our software, we can know that only if it's proved it's not a misconfigured environment that causes it. And in order to do so, we need to know how you got there in details. It's impossible to guess it.
