### ISSUE TITLE
Signup/login with supported social networks.

### ISSUE THREAD

**Issue by iHateInventNames** [diaspora/diaspora#6619]

**Comment by denschub** [comment]
Please elaborate your idea.

**Comment by svbergerem** [comment]
No answer for almost 3 months.

**Comment by iHateInventNames** [comment]
Sorry, I did not understand how you wanted me to elaborate this. Login with Facebook, login with google account...

**Comment by Flaburgan** [comment]
I don't know the opinion of other contributors but I personally feel bad about that: we don't want to encourage usage of those disrespectful services and try to create an alternative to them. To allow to log in with them looks incoherency to me. In the other side, I can understand that it would simplify the migration from one service to another. If you want to discuss about it please port the discussion to [loomio](https://www.loomio.org/g/EseV9p4X/diaspora-community).
