### ISSUE TITLE
Yes/No questions (l10n request)

### ISSUE THREAD

**Issue by akerbeltz** [diaspora/diaspora#6620]
I’d like to make a general suggestion for future development, since Diaspora still seems to be at a relatively early stage. In general, getting l10n right will ultimately help Diaspora itself as it will make it come across more human than some of the alternatives.

In terms of l10n/l20n, it would be better if Yes/No questions were associated with individual Yes and No answer strings. In about half the worlds languages (including some big ones like Chinese, not just “weird ones” like Gaelic) there is no single word for Yes and No. These languages rely on echoing the verb i.e. in English you have
Are you sure? > Yes/No
but in those other languages you’d answer
Are you sure? > Am / Am not

This means that each answer depends on the verb in the question i.e. if the question was
Did you save? > Yes/No
Did you save? > Did / Did not

Having a single pair of Yes/No strings cover ALL these for the purpose of l10n creates big headaches and forces translators to come out with really twisted translations (often much longer than necessary) to allow answers via a single verb pair. For example, something like
Save? > Yes/No
which could be as short as?
Sàbhail > Sàbhail/Na sàbhail
in the current setup I have to make
A bheil thu airson sàbhaladh?
so the “generic” Tha/Chan eil answer can be user.

**Comment by svbergerem** [comment]
The only place where we seem to use "Yes" and "No" is on the admin page to tell the admin if a user closed their account. Can we close this?

**Comment by jhass** [comment]
Yes, the key is actually namespaced to its usage there.
