### ISSUE TITLE
Workers::ExportPhotos -> NameError: uninitialized constant User::Zip

### ISSUE THREAD

**Issue by schleup** [diaspora/diaspora#6625]
When trying to export photos, nothing happens. 

The message "Wir sind gerade dabei, deine Fotos zu verarbeiten. Bitte guck in ein paar Augenblicken noch mal vorbei." and the corresponding value 1 in the DB users->export_photos appears and doesn't change again.

![bildschirmfoto 2016-01-08 um 10 52 50](https://cloud.githubusercontent.com/assets/9998060/12195237/ff6ebec2-b5f5-11e5-90db-ac37a96d2be4.png)

In sidekiq the job Workers::ExportPhotos reports an error: NameError: uninitialized constant User::Zip

![bildschirmfoto 2016-01-08 um 10 52 29](https://cloud.githubusercontent.com/assets/9998060/12195238/ff70b164-b5f5-11e5-8459-f0619a4718bf.png)

I installed diaspora*  (Code 0.5.5.1-p9cb4b732) according to the tutorial on

https://wiki.diasporafoundation.org/Installation/Debian/Jessie?db=mysql&mode=production

that is: Debian Jessie, MySQL and I'm using Apache as a frontend to the internet, using this config:

https://gist.github.com/jhass/719014

If you need to check something on my pod diaspora.poleni.com please let me know.

**Comment by jaywink** [comment]
Could you check for any errors at the time the job fired (timestamp in sidekiq, prob around when you clicked export) in logs/production.log ?

**Comment by schleup** [comment]
![screenshot_2016-01-09-07-54-12](https://cloud.githubusercontent.com/assets/9998060/12214900/46d21f1a-b6a6-11e5-97f9-7a68c8b534ff.png)

At the moment I'm mobile only, so please see the screenshot attached for the errors

**Comment by jhass** [comment]
Does this reproduce for anybody else?

**Comment by Flaburgan** [comment]
This only error related to ExportPhotos I found in my logs is:
```
2015-04-24T11:54:13.134Z 22098 TID-h3btnj8 Workers::ExportPhotos JID-271f65fcfc59a4f2756c3ab8 INFO: start
2015-04-24T11:54:13.264Z 22098 TID-h3btnj8 Workers::ExportPhotos JID-271f65fcfc59a4f2756c3ab8 INFO: fail: 0.13 sec
2015-04-24T11:54:13.265Z 22098 TID-h3btnj8 WARN: {"retry"=>12, "queue"=>"export", "backtrace"=>20, "class"=>"Workers::ExportPhotos", "args"=>[663], "jid"=>"271f65fcfc59a4f2756c3ab8", "enqueued_at"=>1429876453.1323
96, "locale"=>"fr", "error_message"=>"Too many open files @ rb_sysopen - /tmp/damien20150424-22098-6q8708_photos.zip", "error_class"=>"Errno::EMFILE", "failed_at"=>1429876453.2638292, "retry_count"=>0, "error_back
trace"=>["app/models/user.rb:328:in `perform_export_photos!'", "app/workers/export_photos.rb:12:in `perform'"]}
2015-04-24T11:54:13.265Z 22098 TID-h3btnj8 WARN: Too many open files @ rb_sysopen - /tmp/damien20150424-22098-6q8708_photos.zip
2015-04-24T11:54:13.265Z 22098 TID-h3btnj8 WARN: app/models/user.rb:328:in `perform_export_photos!'
app/workers/export_photos.rb:12:in `perform'

```
From my sidekiq logs. I grepped all the 2015 logs.

**Comment by Loris1123** [comment]
I can reproduce this. 
I have a clean DB and the latest source. I haven't post anything (not even photos).
The first thing I do is exporting the photos and get same errpr.  

    NameError (uninitialized constant User::Zip):
    app/models/user.rb:338:in `perform_export_photos!'
    app/workers/export_photos.rb:12:in `perform'
    app/models/user.rb:332:in `queue_export_photos'
    app/controllers/users_controller.rb:153:in `export_photos'
    lib/rack/chrome_frame.rb:39:in `call'
    lib/unicorn_killer.rb:35:in `call'

When I visit the settings page again it says "We are currently processing your photos. Please check back in a few moments." all the time.

**Comment by visualsayed** [comment]
@schleup @jhass I think that a " require 'zip' " is missing so the rubyzip gem is not loaded.

 ```ruby
require 'zip' 
class User
  ...
end
```

**Comment by visualsayed** [comment]
It is interesting that the rspec tests passed cause the [selenium-webdriver] gem has a runtime-dependency on [ruby-zip] gem, so selenium actually do the (require 'zip') but diaspora code doesn't.
