### ISSUE TITLE
Errors with Sidekiq jobs "Workers::ReceiveUnencryptedSalmon" and "Workers::FetchWebfinger"

### ISSUE THREAD

**Issue by schleup** [diaspora/diaspora#6629]
With mostly one other diaspora* pod (joindiaspora.com) I get a lot of errors with "Workers::ReceiveUnencryptedSalmon" and "Workers::FetchWebfinger" on my new pod:

```
DiasporaFederation::Discovery::DiscoveryError: Failed to fetch http://joindiaspora.com/.well-known/host-meta for linux@joindiaspora.com: RuntimeError: Failed to fetch http://joindiaspora.com/.well-know...
```

As a result (so I guess) I can't search users on joindiaspora.com or see their messages, even if forwarded from a contact on another pod. For example from pod.geraspora.de where reading posts from joindiaspora.com is no problem.

In a similar bug the reporter was asked to do a query in the rails console, so I tried it as well (though it doesn't make much sense to me):

```
diaspora@sana:~/diaspora$ bin/rails c production
Loading production environment (Rails 4.2.5)
2.1.5 :001 > Webfinger.new("mnbain@joindiaspora.com").fetch
NameError: uninitialized constant Webfinger
	from (irb):1
	from /home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/railties-4.2.5/lib/rails/commands/console.rb:110:in `start'
	from /home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/railties-4.2.5/lib/rails/commands/console.rb:9:in `start'
	from /home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/diaspora/.rvm/gems/ruby-2.1.5@diaspora/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'
2.1.5 :002 > 

```
I installed diaspora* (Code 0.5.5.1-p9cb4b732) according to the tutorial on

https://wiki.diasporafoundation.org/Installation/Debian/Jessie?db=mysql&mode=production

that is: Debian Jessie, MySQL and I'm using Apache as a frontend to the internet, using this config:

https://gist.github.com/jhass/719014

Yes, and I'm using a letsencrypt.org SSL certificate.

**Comment by jaywink** [comment]
Can you search for and follow people from other pods? joindiaspora.com is buggy and if something fails with that - it means nothing regarding core code :)

For example, try mine: jaywink@iliketoast.net

**Comment by schleup** [comment]
Actually searching for people and following people on other pods is no problem. It's mostly joindiaspora.com which creates the problems.  Only one more pod appeared in Sidekiq with similar errors: dia.jl42.de

So, no code error, no config issue on my pod (?), so I'm closing the bug.

**Comment by gabsoftware** [comment]
I have the same issue as well on my pod. Example:

DiasporaFederation::Discovery::DiscoveryError: Failed to fetch http://joindiaspora.com/.well-known/host-meta for xxxxxxxx@joindiaspora.com: RuntimeError: Failed to fetch http://joindiaspora.com/.well-kn...

**Comment by Flaburgan** [comment]
@gabsoftware as said, this is because joindiaspora.com is overloaded, there is nothing we can do from our side.
