### ISSUE TITLE
notification for hidden and muted private conversation

### ISSUE THREAD

**Issue by schubeda** [diaspora/diaspora#6632]
I got an email notification for a private conversation that was already hidden and muted. Obviously I couldn't see the message when I clicked the link. The other person in the conversation actually sent a message, but I guess I shouldn't get a notification if it's muted.

**Comment by jaywink** [comment]
Could you list your diaspora pod version please? It is in the right sidebar, or go to `/statistics` on the pod you are on, thanks!

**Comment by schubeda** [comment]
The version is 0.5.5.99-p0a02e81b

**Comment by svbergerem** [comment]
Fixed by #6873, test added by #6899.
