### ISSUE TITLE
Failure to run `rake assets:clean` during 0.5.6.0 update caused problems

### ISSUE THREAD

**Issue by rev138** [diaspora/diaspora#6637]
This morning, my D* stream suddenly had no content and all of the icons/buttons were missing. I looked in chrome’s error console and saw:

    Failed to load resource: the server responded with a status of 525 (OK)
    main-63c5f337709144a22070158b3b87aa41.js:15 Uncaught ReferenceError: HandlebarsTemplates is not defined

I recalled that during yesterday’s upgrade there was a message that due to an update of handlebars it would be necessary to run `rake assets:clean`, but I skipped this because that’s what the wiki says to do. I went ahead and ran this anyway. It took a while, and removed at least a thousand files from the assets directory. When it was done I re-ran `rake assets:precompile` and restarted the server process. Things are back to normal.

I think I was spared noticing this issue immediately following the update to 0.5.6.0 because I use a CDN in front of my pod, so I was getting cached assets.

**Comment by denschub** [comment]
I've tried this several times and so far, nobody else has complained. I guess you ran into an edge case here and I am not able to reproduce this... Feel free to reopen if you have further details.
