### ISSUE TITLE
Strip Markdown from conversation title.

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#6642]
![capture du 2016-01-16 11-27-58](https://cloud.githubusercontent.com/assets/930064/12371905/3be894f0-bc44-11e5-8d43-513bf741b418.png)

**Comment by noplanman** [comment]
Similar thing applies to the notifications.
It doesn't show the whole markdown though, just the URL of a link.

**Post:**
Just a [link](http://somewhere).

**Notification popup:**
Just a link (http://somewhere).

*(GitHub is having issues with image upload, will update this comment and add a screenshot as soon as it works again)*

**Comment by Flaburgan** [comment]
That's a choice, to not have an external link inside the notification.

**Comment by noplanman** [comment]
Here the screenshot of the notification showing the URL:

![url-in-notifications](https://cloud.githubusercontent.com/assets/9423417/12861485/077f5c1e-cc64-11e5-8dd6-7f5931c942e9.png)

Since the link isn't clickable on the notification anyway, it would make sense to not have it there.

**Comment by SaiVardhan** [comment]
@Flaburgan  can you elaborate to fix this issue

**Comment by Flaburgan** [comment]
@SaiVardhan what do you need to know? Simply create a new conversation (private message) with some markdown in the subject and at the beginning of the message, and you will see in the right list that the markdown is not stripped (**subject** will appear `**subject**`). As in the notification panel, it should be stripped.

@noplanman to completely hide the link or to show it is another question, you can open an issue about it if you feel so. At the moment, I'd like to see the markdown stripped the same way in the conversation and in the notification.
