### ISSUE TITLE
Incorrect german localization for "Join us!" button

### ISSUE THREAD

**Issue by bennythomae** [diaspora/diaspora#6645]
The "Join us!"-button's text should read "Tritt bei!" instead of "Trete bei!" to be grammatically correct. See https://de.wiktionary.org/wiki/beitreten 2nd person, singular.

![bildschirmfoto 2016-01-18 um 22 26 19](https://cloud.githubusercontent.com/assets/856906/12403466/49107c50-be34-11e5-82d5-1e95463d13a0.jpg)

**Comment by denschub** [comment]
This is an issue in the project site, not in diaspora itself. The sites code is at https://github.com/diaspora/diaspora-project-site. You can contribute to translations at https://webtranslateit.com/en/projects/7017-Website

**Comment by bennythomae** [comment]
Thank you. I will gladly do so.
