### ISSUE TITLE
Two different blues used for links in UI

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#6656]
One is used for #tags and profile name links.

The other, a brighter blue, is used for 'normal' links (posted links and side-bar links), plus the 'Like', 'Reshare' and 'Comment' links under each post.

(There are probably other cases in which each blue is used.)

I think it would look better if we used one blue across the UI. Personally I prefer the darker, less vivid blue used for #tags. Would it be desirable to change the others to this blue?

Apologies if there has already been discussion of this: I've done a search and didn't find anything.
##

**Comment by noplanman** [comment]
@goobertron I totally agree with you.
The darker shade feels nicer and I think having the tags / user links bold is a good method of emphasizing them, no need to have a different colour too.

I'd volunteer to change this if everyone agrees.

(This would be my first PR, so I'm still learning about the workflow/process etc. please bear with me :blush:)

**Comment by svbergerem** [comment]
I'd like to mention that there are currently 3 different variables for blue colors: `$blue`, `$link-color` and `$brand-primary`. `$link-blue` is used for most links, `$blue` is used for hashtags, usernames for authors, opengraph/oembed links and some navigation elements. We use `$brand-primary` for buttons, highlighting for keyboard navigation, blue borders in the profile and for different Bootstrap elements.

While I agree that some unification could be a good idea, I'd also like to keep some distinction between hashtags (and maybe also mentions) and other markdown links since we create the first two links and thus the user already knows the URL while for the other ones they need to be more careful. Especially for `#hashtag` vs. `[#hashtag](http://someevilurl.com/)`.

**Comment by AugierLe42e** [comment]
Well, in the end, `#hashtag` is turned into a link, too.

**Comment by noplanman** [comment]
@AugierLe42e I think what @svbergerem means is that the 2 hashtag links that he's talking about are different links, the first one being a diaspora\* internal link to "the.pod/tags/hashtag" whilst the second one is a link to "someevilurl.com".
If you copy them to the diaspora\* post entry field and preview it, you'll see that they produce different links visually. Internal hashtag is bold and a darker shade of blue, whereas the second is a "normal" bright blue link.
So it's easy to see that the bold one is automatically "safe".

Comparing the following 2 screenshots, which links look nicer to you (all)?
![link-lighter](https://cloud.githubusercontent.com/assets/9423417/12861390/3e120d7c-cc63-11e5-87b9-ee07a7f27fdd.jpg)
![link-darker](https://cloud.githubusercontent.com/assets/9423417/12861389/3e11b020-cc63-11e5-8a44-a23d8f04566c.jpg)

To my eyes, the bright links (top) are a bit distracting and thus I prefer the darker ones, but this is really something subjective.
@svbergerem The darker links are a different colour to the bold links. Maybe this is an option?

**Comment by svbergerem** [comment]
i think one should compare the bold versions:
`#diaspora vs. **[#diaspora](https://evillink.com)**`

![hashtag vs link](https://cloud.githubusercontent.com/assets/3798614/12869689/9550459a-cd26-11e5-9528-8d3f2b95c5fc.png)

Looking at this again I'm not sure anymore if the difference is currently big enough to show users immediately which one is a markdown link and which one is the hashtag.

Thus I guess it would be also ok for me if we really unify those colors. Any other opinions?

**Comment by noplanman** [comment]
You're right about comparing the bold versions.

Additionally as it is now, the link hover colour for usernames and hashtags stays the same, whereas those of normal links become noticeably darker. Of course this is only a factor on devices that allow hovering.

Considering that, having them the same colour would still differentiate them on hover.

**Comment by Flaburgan** [comment]
Maybe we're trying to solve the wrong issue here. For example, mentions are internal links but displayed with the light blue. Maybe we should just use the same blue everywhere, and add a symbol like [those](https://duckduckgo.com/?q=link+external&iax=1&ia=images) when the link is an external one.

**Comment by goobertron** [comment]
I take Steffen's point about differentiating internal links (hashtags, mentions, profiles, etc.) from external ones. However, the two blues look jarring next to each other, so it would be good to find a different solution, if the feeling is that this is necessary. Fla's icon is one possibility; underlining links is another, although I find that a bit ugly too.

One point is that some intra-Diaspora links (Like, Comment, Reshare), plus the links in the side-bar, some of which are external but all of which are checked and 'authorised' are also in the bright blue. If we're trying to warn people that a link takes them to an unknown and unchecked location, all those 'authorised' links should be in the same blue as tags and mentions.

If we choose colour to differentiate the two types, I'd suggest making the colours more different so there isn't a visual clash between them.

Thanks for your thoughts on this, everyone. I didn't consider the possible 'security' implications of unifying the various sorts of link.

**Comment by AugierLe42e** [comment]
> I take Steffen's point about differentiating internal links (hashtags, mentions, profiles, etc.) from external ones. However, the two blues look jarring next to each other, so it would be good to find a different solution, if the feeling is that this is necessary.

I may have one: since adding a lot of hashtags inside a post can transform it into an unreadable mess, why not escape hashtags inside the post and aggregate them at the end of the post as labels?

**Comment by SuperTux88** [comment]
Fixed by #7318
