### ISSUE TITLE
Routing Error when clicking Download my photos link

### ISSUE THREAD

**Issue by visualsayed** [diaspora/diaspora#6661]
To reproduce this:

1- Navigate to: pod/user/edit

2- Click [Request my photos] link if you didn't request it before otherwise click [Download my photos] link.

You will get a Routing Error: No route matches [POST] "/user/download_photos"

The reason behind this is that we defined a get route only while in views/users/_edit.haml partial we use the [link_to] helper method to create a link tag with {method: :post} option which dynamically creates an HTML form and submit it using the HTTP post verb.

Removing the {method: :post} should fix this issue by falling to the default HTTP get method.

I'll managed to check and complete the cucumber scenario at features/desktop/download_photos.feature then send a PR. 

Worth noting that the mentioned cucumber feature is marked with @wip tag and by completing it we should have test for #6625

Thanks,
Sayed

**Comment by visualsayed** [comment]
Sure we can define the missing route which I prefer as a security wise solution as rails automatically create and append authenticity_token [a CSRF token] to post requests.

Not sure which solution you guys want me to go with.

Thanks,
Sayed

**Comment by jhass** [comment]
All data modifying actions should happen through `POST`, `PUT`, `PATCH` or `DELETE` requests, otherwise they're easier to trigger by a malicious party.

**Comment by visualsayed** [comment]
@jhass You are correct but I though that you might would like to keep the GET route for photos download which won't modify any data it will only trigger the download dialog in behalf of the user.

**Comment by jhass** [comment]
Oh, I misunderstood the issue, sorry.
