### ISSUE TITLE
Very large images from embedded links result in a broken image and thumbnail in post

### ISSUE THREAD

**Issue by rev138** [diaspora/diaspora#6664]
See here:
https://diaspora.hzsogood.net/people/bf98f8e0067101334cc43827eb73f2e3

The linked page contains a very large jpeg (~16MB). 
https://www.nasa.gov/image-feature/jpl/pia20316/curiosity-self-portrait-at-martian-sand-dune
https://www.nasa.gov/sites/default/files/thumbnails/image/pia20316-main_take6dune.jpg

**Comment by rev138** [comment]
I tried embedding the image in a post directly via `![](https://www.nasa.gov/sites/default/files/thumbnails/image/pia20316-main_take6dune.jpg)` and got the same broken link, so this looks like it's probably a camo issue.

**Comment by rev138** [comment]
Just read on the wiki that you guys prefer to make the determination, so re-opening.

Potentially helpful thread: https://diaspora.hzsogood.net/posts/275405

**Comment by jhass** [comment]
Your image most likely is simply bigger than what your podmin configured for `CAMO_LENGTH_LIMIT`.

**Comment by rev138** [comment]
I thought that might be the case, so I set it to 20971520 (the image is ~16MB) and it's still returning a 404.

**Comment by rev138** [comment]
I assume that value is in kb, since the wiki refers 10485760 as equal to 10Mb

**Comment by jhass** [comment]
Well I don't know, it loads on my pod with Camo enabled.

**Comment by rev138** [comment]
Can you share what your `CAMO_LENGTH_LIMIT` is set to?

**Comment by jhass** [comment]
`20971520` too.

**Comment by rev138** [comment]
Thanks
