### ISSUE TITLE
Valley Girl stream time-stamp spacing issue

### ISSUE THREAD

**Issue by theatre-x** [diaspora/diaspora#6689]
There's a weird spacing issue with the post time-stamp on the stream when using the "English (Valley Girl)" language.

It reads like this:

"Theatre X - 10 minslike... ago"

[Insert post content here]

When it SHOULD read like this:

"Theatre X - 10 mins like... ago"

[Insert post content here]

I tried to fix it myself and then send a pull request but I could not find the bit where that text is in the sauce code.

Cheers!

**Comment by svbergerem** [comment]
[javascript.timeago.wordSeparator](https://webtranslateit.com/en/projects/3020-Diaspora/locales/en..en-valspeak/strings/5143008) should be a blank but is an empty string in the Valley Girl translation. I don't have the rights to change that but I guess you should be able to do that on webtranslateit.

**Comment by denschub** [comment]
This is fixed on webtranslateit and will get pulled in whenever the next translation update happens.

**Comment by denschub** [comment]
Fixed with fbabc541ae19331a85b6529caad887f58c0b95f1.
