### ISSUE TITLE
Gallery navigation arrows are misplaced

### ISSUE THREAD

**Issue by denschub** [diaspora/diaspora#6690]
See:

![screen shot 2016-02-09 at 19 36 37](https://cloud.githubusercontent.com/assets/344777/12926615/942362a2-cf64-11e5-9276-de98b0d9a357.png)

(Firefox 47.0-20160209)

**Comment by denschub** [comment]
This might eventually be a OSX font rendering "issue".

**Comment by AugierLe42e** [comment]
> This might eventually be a OSX font rendering "issue".

Not at all. I also have this error.

**Comment by denschub** [comment]
Ah, great. Because @svbergerem was not able to reproduce this at all in the same Firefox versions. Thanks for testing!
