### ISSUE TITLE
API privilege scope escalation

### ISSUE THREAD

**Issue by denschub** [diaspora/diaspora#6696]
I just discovered a rather odd OpenID Connect implementation flaw that allows applications to escalate their permission scope after they were authenticated once.

STR:

1. Generate a authorization URL without any scopes, for example `/api/openid_connect/authorizations/new?response_type=id_token+token&redirect_uri=http%3A%2F%2Fexample.com%2F&nonce=foo&client_id=foo`
2. The user authorizes the application that "requires no permissions" and the app receives the access token.
3. Build another authorization URL, this time including all possible scopes: `/api/openid_connect/authorizations/new?response_type=id_token+token&scope=aud+name+nickname+openid+picture+profile+read+sub+write&redirect_uri=http%3A%2F%2Fexample.com%2F&nonce=foo&client_id=foo`

Expected behavior:

The user receives another authorization dialog, asking for authorizing the new permissions.

Actual behavior:

The app immediately receives a new `access_token` with additional privileges. Looking at `/api/openid_connect/user_applications` does confirm that the app has extended its privileges.

Since the API is not in any stable release and there are no real endpoints, I've decided to make this issue public. @theworldbright, could you take a look?

**Comment by theworldbright** [comment]
Yup thanks for the catch! Sending in a fix right now.
