### ISSUE TITLE
I can't find local user

### ISSUE THREAD

**Issue by exmatrikulator** [diaspora/diaspora#6701]
I have to search with the complete diaspora ID to find a new user. Only the name gives me no result.
When I created the user, I had problems with redis.
How can I reload the redis data?

**Comment by denschub** [comment]
What? What issues do you have? What do you need to reload? Do you get any error messages?

**Comment by exmatrikulator** [comment]
No, error. Just can't find the local user by name. Only if I enter the complete diaspora ID.
As I remember, there was a problem with the redis server when I register this account.

Thanks!

**Comment by svbergerem** [comment]
Did the user allow other users to find them? There is a checkbox on the privacy settings page. Otherwise this behavior would be intended.

**Comment by exmatrikulator** [comment]
Ah, ok. sorry.
It was in the profile settings.
Thanks!
