### ISSUE TITLE
Back to top arrow is not displayed anymore

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/diaspora#6704]
HTML element is still here but it is not displayed anymore.

**Comment by svbergerem** [comment]
On which page? I still see it in the main stream on develop.

**Comment by AugierLe42e** [comment]
Main stream. Both on d-fr and diaspote :/

**Comment by svbergerem** [comment]
Here is a screenshot I took with my test account on diaspora-fr:

![back to top diaspora-fr](https://cloud.githubusercontent.com/assets/3798614/13144612/f246214c-d64b-11e5-8401-ce5a218562f6.png)

(I reduced the height of the window for the screenshot. The button is still at the bottom of the window.)

**Comment by AugierLe42e** [comment]
Ok, it comes from my browser. The script which displays it gets blocked by µBlock.
