### ISSUE TITLE
Can't connect other clients to XMPP server, web stuff built in works fine

### ISSUE THREAD

**Issue by Zelex** [diaspora/diaspora#6705]
For some reason, the XMPP server won't work with external clients. Not sure why. The web-stuff built-into diaspora works fine though.

**Comment by prellele** [comment]
I think there is further information needed to look into this issue.

I've tested Pidgin and its working like a charm.

**Comment by terokorp** [comment]
I have created new pod few days ago and I got external XMPP client(s) work fine.
Using Mozilla Thunderbird.

**Comment by Zauberstuhl** [comment]
@Zelex have you adjusted your firewall? -> https://wiki.diasporafoundation.org/Integration/Chat#Firewall_Ports

**Comment by svbergerem** [comment]
No answer for more than 2 months and it seems to be working for everyone else.
