### ISSUE TITLE
need help deleting information from my locked account

### ISSUE THREAD

**Issue by jnki** [diaspora/diaspora#6714]
Hello! I can't sign in to my accounts via joindiasp or diasp.org.

I 'closed' the accounts thinking they would be deleted them some years ago, so now it gives me 'Your account is locked' when I try to sign in.

I noticed today that there is some of my personal information is still viewable, and I need to have it deleted.

How can I go about doing this? I really need this stuff gone.

Thanks for your help!

**Comment by Zauberstuhl** [comment]
@jnki contact the podmin's directly

diasp.org -> https://diasp.org/people/4d0564183dac139f3d0008e0
joindiaspora.com -> https://joindiaspora.com/people/4cec08f12c17431ff40000c5

**Comment by jnki** [comment]
Thanks! Just to be clear, I have to make an account again to contact these peoples?

**Comment by denschub** [comment]
Write emails to `support@diasp.org` and `maxwell@joindiaspora.com` if you do not want to greate another account.
