### ISSUE TITLE
Problems with caching in v5.7.0

### ISSUE THREAD

**Issue by rev138** [diaspora/diaspora#6716]
My [pod](https://diaspora.hzsogood.net) is running behind the CloudFlare CDN. As soon as I updated to v5.7.0 the page rendering became broken. If I purge/disable the CF cache the problem disappears, but when I re-enable it it comes back.

![snapshot8](https://cloud.githubusercontent.com/assets/1538633/13287883/3396c8ba-dad7-11e5-93ce-6ad219a20177.png)

**Comment by Flaburgan** [comment]
I see nothing in 0.5.7.0 which could have broken that. Can you try to clear the assets with `bin/rake tmp:cache:clear assets:precompile` and restart the pod?

**Comment by rev138** [comment]
No dice. The problem persists. I tried hitting the site with Chrome developer tools open, but I see no errors.

**Comment by denschub** [comment]
I'm going to close this one. External asset hosting is not really supported by us and GitHub is not a support platform. Feel free to join [our IRC channel](https://wiki.diasporafoundation.org/How_we_communicate#IRC) and check if somebody has ideas. If not, try asking the community behind the cloudflare plugin or deployment system you are using for help (that is, fog, I presume?), maybe they know what's up.

**Comment by rev138** [comment]
>  GitHub is not a support platform

I don't understand what this means.

**Comment by denschub** [comment]
GitHub issues are not the place for fixing setup issues and answering questions regarding troubleshootings. This is a place for tracking coding issues, which this is not.
