### ISSUE TITLE
Upload progress-bar of multiple files working incorrectly

### ISSUE THREAD

**Issue by syamgk** [diaspora/diaspora#6721]
progress-bar which shows the status of upload seems to go backwards while uploading multiple images
whereas there is no issue while uploading a single file
on diaspora version Code 0.5.6.3-pad20bb05
##

**Comment by Flaburgan** [comment]
Yes I noticed this behaviour a while ago. Only the first progress bar is updated by every uploaded document.

**Comment by svbergerem** [comment]
I'm unable to reproduce this on the develop branch. (diaspora-fr and pod.omgsrsly.net)

**Comment by Flaburgan** [comment]
Steps to reproduce (on diaspora-fr):
* In the publisher, click the camera icon
* In the opening pop up, hold ctrl and pick 3 big images.
* Validate the pop up.

**Comment by Flaburgan** [comment]
More precisely, the bug is [here](https://github.com/diaspora/diaspora/blob/develop/app/assets/javascripts/app/views/publisher/uploader_view.js#L60), it should not be `.first()` but the correct image.

**Comment by Flaburgan** [comment]
Btw the display of #fileInfo, the line before, is also broken.
