### ISSUE TITLE
Support apng image format 

### ISSUE THREAD

**Issue by sandrokensan** [diaspora/diaspora#6725]
I add some news about apng support. Now Firefox support apng, Safari for desktop support apng and safari for iOS support apng.

http://caniuse.com/#feat=apng

For Chrome there is not built in support but a plugin.

Ref: https://github.com/diaspora/diaspora/issues/6358

It is notorious that PNG group don't support apng but more and more browser support it. The browser share that support apng is now about 15% and grow.

**Comment by denschub** [comment]
As discussed in the issue you linked, our library to resize images (ImageMagick) will never support APNG, so handling them is impossible for us. In addition, APNG is a rejected standard so there is no point in hoping it will ever be supported.
