### ISSUE TITLE
assert failure in lint.rb - feed not updating

### ISSUE THREAD

**Issue by amckinstry** [diaspora/diaspora#6730]
I'm getting the following errors in unicorn-stderr.log:

XX.XX.XX.XX - - [24/Feb/2016:17:03:23 +0000] "HEAD /users/sign_in HTTP/1.0" 200 - 0.1355
E, [2016-02-24T17:03:23.035792 #31991] ERROR -- : app error: Response body was given for HEAD request, but should be empty (Rack::Lint::LintError)
E, [2016-02-24T17:03:23.035964 #31991] ERROR -- : /root/.rvm/gems/ruby-2.1.5@diaspora/gems/rack-1.6.4/lib/rack/lint.rb:20:in `assert'
E, [2016-02-24T17:03:23.036023 #31991] ERROR -- : /root/.rvm/gems/ruby-2.1.5@diaspora/gems/rack-1.6.4/lib/rack/lint.rb:688:in `verify_content_length'
E, [2016-02-24T17:03:23.036078 #31991] ERROR -- : /root/.rvm/gems/ruby-2.1.5@diaspora/gems/rack-1.6.4/lib/rack/lint.rb:716:in `each'
E, [2016-02-24T17:03:23.036267 #31991] ERROR -- : /root/.rvm/gems/ruby-2.1.5@diaspora/gems/rack-1.6.4/lib/rack/body_proxy.rb:31:in `each'
E, [2016-02-24T17:03:23.036320 #31991] ERROR -- : /srv/diaspora/home/.rvm/gems/ruby-2.1.5@diaspora/gems/unicorn-5.0.1/lib/unicorn/http_response.rb:54:in `http_response_write'
E, [2016-02-24T17:03:23.036373 #31991] ERROR -- : /srv/diaspora/home/.rvm/gems/ruby-2.1.5@diaspora/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:573:in `process_client'
E, [2016-02-24T17:03:23.036426 #31991] ERROR -- : /srv/diaspora/home/.rvm/gems/ruby-2.1.5@diaspora/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:658:in `worker_loop'
E, [2016-02-24T17:03:23.036479 #31991] ERROR -- : /srv/diaspora/home/.rvm/gems/ruby-2.1.5@diaspora/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
E, [2016-02-24T17:03:23.036532 #31991] ERROR -- : /srv/diaspora/home/.rvm/gems/ruby-2.1.5@diaspora/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:132:in `start'
E, [2016-02-24T17:03:23.036584 #31991] ERROR -- : /root/.rvm/gems/ruby-2.1.5@diaspora/gems/unicorn-5.0.1/bin/unicorn:126:in `<top (required)>'
E, [2016-02-24T17:03:23.036637 #31991] ERROR -- : /root/.rvm/gems/ruby-2.1.5@diaspora/bin/unicorn:23:in `load'
E, [2016-02-24T17:03:23.036689 #31991] ERROR -- : /root/.rvm/gems/ruby-2.1.5@diaspora/bin/unicorn:23:in `<main>'

This is with my pod, at 0.5.7.0-pe45cf2e3. I can post, but I'm not getting updates from other pods.
Any ideas?

**Comment by denschub** [comment]
That error is not related to a federation failure, but rather some automated bot trying to login with invalid credentials and spoofed headers.

Check that your sidekiq is running. Access `/sidekiq` and verifiy that you have active workers and empty queues. If sidekiq is running or you are not able to fix the issue, please [join our iRC channel](https://wiki.diasporafoundation.org/How_we_communicate#IRC) and ask for help. This is not a software issue, so I'll close this as GitHub is not really a support platform. :)
