### ISSUE TITLE
Delete oldest messages

### ISSUE THREAD

**Issue by qwertygc** [diaspora/diaspora#6737]
Hello!
I write in french, because i'm better in french, but i translate after my post.

[FR] C'est une suggestion : supprimer nos vieux messages, like, repartage que l'on a écrit.
Option : supprimer les messages vieux d'au moins un mois, un an...
Pourquoi : pour le droit à l'oubli ? je sais qu'il existe des sites qui font pour Twitter. Pourquoi pas en natif en diaspora.

[EN]
It's a suggestion: remove our old messages, like, report that we wrote.
Option: delete old messages at least a month, a year ...
Why: for the right to be forgotten? I know that there are sites that are for Twitter. Why not natively diaspora.

**Comment by denschub** [comment]
You can always delete everything. If you delete your account, everything will be gone. If you delete a post, we try to federate the removal to all pods. The only thing you cannot delete are private messages, which is tracked in #4209. We already had a discussion about automatically deleting "old" stuff in the past on Loomio and the majority disliked it. If you feel like you need this, please reopen the discussion on Loomio.

**Comment by qwertygc** [comment]
my suggestion it's just for the posts.

**Comment by denschub** [comment]
https://www.loomio.org/d/70t8W4zG/public-posts-that-expire is one of the possible threads on loomio to re-active if you feel strong.
