### ISSUE TITLE
Account locked

### ISSUE THREAD

**Issue by luigikurihara** [diaspora/diaspora#6752]
Good morning people,

has a sometime I don't use Diaspora and when I sign in again, the message from my acount appear locked. I search in site, but don't encounter how to unlock my account.
Anyone can help me?

Thanks for attention.

**Comment by kas70** [comment]
Hi, 
which pod are you on? Please contact your podmin.

**Comment by luigikurihara** [comment]
Right, I use diasporabr and make a contact to solve it. Thanks.

Em ter, 15 de mar de 2016 às 13:04, kas70 <notifications@github.com>
escreveu:

**Comment by luigikurihara** [comment]
Olá, diaspora/diaspora.

Gostaria que você fizesse parte da minha rede do LinkedIn para compartilhar atualizações e manter contato.

- Luigi

Confirme que você conhece Luigi: https://www.linkedin.com/e/v2?e=0-imav5lvn-gn&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=YH-CZVG_&invitationId=6119913738771451904








Você recebeu um convite de conexão. O LinkedIn utiliza seu endereço de e-mail para fazer sugestões a nossos usuários em recursos como Pessoas que talvez você conheça. Clique aqui para cancelar a inscrição: https://www.linkedin.com/e/v2?e=0-imav5lvn-gn&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEpToIEP8V_hgAAAVO5NNdvsFH_4rnJgy1wFwAUY9Sb1fthgnTC6wk1k6qW_P7jsL8_g_PXyEtFRMXtuWIe4CuyHYxzID6lZgnwD-JRmbrSHBN2iX9nJHP3GBRGsdlBxGjJa9D-FC_1hQJnPnabnBQwqYpnbDLyjMq2IUSUsTgTIPDUVL4L3d6pkcHfRlALurBt&eid=0-imav5lvn-gn


Este e-mail foi enviado para reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-imav5lvn-gn&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View, CA 94043. LinkedIn e a logomarca do LinkedIn são marcas registradas da LinkedIn.

**Comment by luigikurihara** [comment]
Luigi Kurihara would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-mttkdp-img97jza-66&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=YH-CZVG_&invitationID=6119913738771451904

View Luigi Kurihara&#39;s profile: https://www.linkedin.com/e/v2?e=-mttkdp-img97jza-66&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=YH-CZVG_&invitationID=6119913738771451904

Gostaria de adicionar você à minha rede profissional no LinkedIn.





Você recebeu um convite para se conectar. O LinkedIn utiliza seu endereço de e-mail para fazer sugestões a nossos usuários em recursos como Pessoas que talvez você conheça. Cancelar inscrição: https://www.linkedin.com/e/v2?e=-mttkdp-img97jza-66&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-mttkdp-img97jza-66&loid=AQHiobp28NjWlQAAAVPNMH43WShFWJIlu9fqIgMujb0waxmWAhzURqWVOE9MSxx10pksgMBIZCkS0tw0LF29GJ-7XasD439V6_ZFKaa8w9I2yqRX044hc9MrHldPM5OMWNo1FuqdKHevibVuGra5Z-Bc4sNKN3zNWzSDLWDTcUIlrPOFTaR4aXv4UM3brJK47hG6

Este e-mail foi enviado para reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-mttkdp-img97jza-66&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View, CA 94043. LinkedIn e a logomarca do LinkedIn são marcas registradas da LinkedIn.

**Comment by denschub** [comment]
@luigikurihara please stop spamming linkedin invitations to github.
