### ISSUE TITLE
Make a start screen to auto-add yourself too groups that bear your name and family.

### ISSUE THREAD

**Issue by nicubuga** [diaspora/diaspora#6753]
Let's say John Doe makes an account. Let him be added automatically to "John" group and "Doe" group - groups for people with the same names. And also to make a search based on this groups.

**Comment by svbergerem** [comment]
When you write “groups” do you mean “aspects”? So you would like the software to create aspects for your first and last name and add everyone with the same first or last name to those aspects?

While this definitely should only be opt-in I don't think that it's worth the effort. Especially when having in mind how the diaspora* userbase currently looks like.

> And also to make a search based on this groups.

You can just put “John” or “Doe” in the search bar. Did I miss anything?

**Comment by nicubuga** [comment]
Yup, aspects probably - but it defies the idea of aspects into something bigger cause a name isn't really an aspect. 

I had in my mind an image of an advanced search on names and their significances.

**Comment by svbergerem** [comment]
Could you give some more details? How should these groups work? What is their purpose? How does the “advanced search on names and their significances” differ from the current search?

**Comment by nicubuga** [comment]
Every name and family name has it's significance - thus for example Goldman makes suggestion towards Gold, etc. I'd like to see this idea somehow stack in a social network (IMHO)... i guess it has something with big data too.

**Comment by Flaburgan** [comment]
@nicubuga I guess this could be interesting for sociology experiences, but 99.9% of our users would not care about that, and besides, most of the names used on diaspora* are nicknames, not real names, so I'm sorry but I think this suggestion is not going to be implemented. We are releasing an API in our next major version though if you want to hack on this.

**Comment by nicubuga** [comment]
How much can I alter diaspora code so that it can be federated?

**Comment by denschub** [comment]
I'm closing this issue. Honestly, I do not entirely get the point why we should implement this in our core. As Fla said, 99.9% of the users (and probably even more) will not care. Doing "network wide" analysis of aspect names would require pods to transfer the aspect names, which is a huge privacy issue. Adding people automatically to aspects is also something we really should not do.

If you feel strong about this feature, please head over to loomio and prepare a full description on why and how this should work and why you think this would add benefits for all users.
