### ISSUE TITLE
"Hide offline contacts" only hides profile picture 

### ISSUE THREAD

**Issue by prellele** [diaspora/diaspora#6756]
Hitting the "Hide offline contacts" button in the chatsidebar only has the consequence that "profile pictures"/"colorfull chars" of offline contacts are hidden

**Comment by svbergerem** [comment]
@prellele Could you move this issue here? https://github.com/diaspora/jsxc

**Comment by prellele** [comment]
@svbergerem Sorry, I was not aware of this repo. I've moved theese issues over.
