### ISSUE TITLE
re: certificate 

### ISSUE THREAD

**Issue by stoneartist** [diaspora/diaspora#6758]
am in Uruguay, signed into https://joindiaspora.com in Ecuador and when i tried here in Uruguay i got the attached - wishing you all the best ; may we survive - thanks for all you do . 
![screen shot 2016-03-18 at 11 46 55 am](https://cloud.githubusercontent.com/assets/4060960/13888623/9ea89c2a-ecff-11e5-97fb-d6406e94dc28.png)

**Comment by SuperTux88** [comment]
I think your system/browser is too old and doesn't know the relatively new certificate of joindiaspora.

**Comment by denschub** [comment]
Yeah, it works well on 10.10 and 10.11. Also, this is a installation issue and not a software issue, so please contact the administrators of joindiaspora.com if you need assistance.

**Comment by stoneartist** [comment]
bingo - thanks .
