### ISSUE TITLE
security failures between frames

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora#6759]
Use xombrero web browser (start via command terminal) to sign in to diaspora.

Read the various security failures, eg.

** Message: console message: https://...stream @0: The page at https://...stream displayed insecure content from http://...

**Comment by svbergerem** [comment]
diaspora\* allows podmins to use [camo](https://github.com/atmos/camo) which is a SSL image proxy. It looks like your podmin doesn't run the camo proxy. Please contact your podmin if this is important for you.
