### ISSUE TITLE
html css ecmascript error image upload error

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora#6773]
Using xombrero web browser, unable to post a new conversation with a local image file uploaded. Dialogue window appears, then disappears after < 10 seconds:

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> <html xmlns="http://www.w3.org/1999/xhtml"> <head> <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" /> <title>THE SYSTEM IS **DOWN**</title> <style type="text/css"> /* You are allowed to do whatever you want with this layout. Though I would be pleased if you placed a link on your site to csseasy.com or to profit42.com (best "blog about hacking" ever). Donations are also welcome: paypal@profit42.com (or follow the donation button on csseasy.com) */ body { font-family: "helvetica", 'arial', 'sans-serif'; width:750px; margin:0 auto; margin-top:30px; } /* ----- HEADER ----- */ #header { width:750px; height:100px; text-align: center; } #header h1 { font-size: 60px; } /* FAUX LAYOUT WRAPPER */ /* This div is optional: When you delete it the navigation bar and the content block won't have the same size when one of them has a larger height then the other. I recommend you to leave this faux layout wrapper here. IMPORTANT: In order to make this work you have to download http://csseasy.com/layouts/fixed/background_4.gif (copy past in your address bar) and place it in the same folder as this html file. DON'T HOTLINK to this file. */ #wrapper{ width:750px; overflow:auto; /* USE FIREFOX GUYS! WE ONLY NEED THIS LINE BECAUSE INTERNET EXPLODER ISN'T READING CODE PROPERLY */ margin-top:10px; } /* ----- NAVIGATION ----- */ #navigation { width:250px; min-height:500px; /* for modern browsers */ height:auto !important; /* for modern browsers */ height:500px; /* for IE5.x and IE6 */ float:right; } /* ----- MAIN CONTENT ----- */ #content { width:490px; min-height:300px; /* for modern browsers */ height:auto !important; /* for modern browsers */ height:300px; /* for IE5.x and IE6 */ margin-top:10px; } /* ----- FOOTER ----- */ #footer { width:750px; height:0px; margin-top:10px; } </style> </head> <body> <div id="header"> <h1> OH NOES!</h1> </div> <div id="wrapper"> <div id="navigation"> <script src="http://widgets.twimg.com/j/2/widget.js"></script> <script> new TWTR.Widget({ version: 2, type: 'profile', rpp: 5, interval: 6000, width: 240, height: 300, theme: { shell: { background: '#333333', color: '#ffffff' }, tweets: { background: '#ffffff', color: '#000000', links: '#2eabff' } }, features: { scrollbar: true, loop: false, live: true, hashtags: true, timestamp: true, avatars: false, behavior: 'all' } }).render().setUser('diasp_eu').start(); </script> </div> <div id="content"> <h1>Sorry we are closed for Maintenance!</h1><br> <h1>See the current status on <a href='https://twitter.com/diasp_eu'>Twitter.</a><h1>  </div> </div> <div id="footer"> </div> </body> </html>

**Comment by denschub** [comment]
Read the text that's written in 32px font.
