### ISSUE TITLE
Migration from #5852 removes manually created participations

### ISSUE THREAD

**Issue by SuperTux88** [diaspora/diaspora#6786]
After running the migration from #5852 all manually created participations (clicking on the bell-icon without liking or commenting) are removed. This is because all participations without other interactions are removed. We should keep all this participations as manually created, because its better to keep some participations that were created automatically (but the interaction which created it was removed again), than remove manually subscribed posts of a user. The user can always manually remove one of these automatically created participations if it is annoying, but the user wouldn't notice if a manually created subscription is removed, which is bad.

**Comment by Flaburgan** [comment]
@SuperTux88 this is listed as a blocker of 0.6, do you plan to work on it?

**Comment by SuperTux88** [comment]
yes
