### ISSUE TITLE
reverse "J" / "K" hotkeys

### ISSUE THREAD

**Issue by paskalito** [diaspora/diaspora#6794]
ok, maybe this is stupid but is there any logic/reason why "j" jumps down und "k" jumps up?
because my experience is that hit the wrong one on a regular basis, when im just reading articels and have my fingers on those two keys.
I think it's caused by the fact that in fileexplorers and such you can go down and up ( in tree views) by using the arrow keys (left and right) where right goes down (want's to go further right and there it falls down. (because its a treeview)) and left goes up.

so current j / k behavior is contrary to that. so maybe we can switch that if theres no significant reason to not do that.
I'm aware that people may have learned the other way now. - but maybe they experince the same as i do..

**Comment by Flaburgan** [comment]
This comes from [Vim](https://en.wikipedia.org/wiki/Vim_%28text_editor%29), the famous (geek) text editor, and is used in many projects.

**Comment by denschub** [comment]
`j` is a fixed home key on many keyboards (i.e. it has an indent), it is the first key on the right home row on qwerty keyboards and top-to-bottom and it's the default in many projects, including vim, github, google mail, ...

Feel free to start a loomio discussion if you feel really strong about reversing it, but I fear you won't get a very far.
