### ISSUE TITLE
Invite email would be a lot more useful if it told the Diaspora username

### ISSUE THREAD

**Issue by Mikaela** [diaspora/diaspora#6796]
I got invite to Diaspora from "Some Person". The invite email only named "Some Person" in the subject field.

I would otherwise join Diaspora, but I happened to already register to another pod before I was invited and now I am wondering who is "Some Person" on pod.example.com.

I think the invite email should say that their Diaspora ID is `some.person@pod.example.com`, so I could just immediately add them in the pod I am currently using.

**Comment by goobertron** [comment]
That's a good idea.

**Comment by svbergerem** [comment]
Fixed by #6817.
