### ISSUE TITLE
Timeago in notifications

### ISSUE THREAD

**Issue by zweipi** [diaspora/diaspora#6798]
Marking a notification as unread resets the timeago stamp causing the times to look wrong. 
It can be reproduced by marking an old notification as unread. 

(0.5.99 Development Branch)

![bildschirmfoto 2016-04-16 um 08 38 06](https://cloud.githubusercontent.com/assets/9757393/14579551/929ecce0-03ae-11e6-8c23-d5a72c7f3934.png)

**Comment by svbergerem** [comment]
I guess this could be a regression from #6573.
