### ISSUE TITLE
Disabled publisher on photo page

### ISSUE THREAD

**Issue by zweipi** [diaspora/diaspora#6799]
When you make a post on the photo page, the loader beneath the publisher doesn’t stop spinning.
Upon refreshing the site your post is published but the publisher is now disabled.

(0.5.99 Development Branch)

![bildschirmfoto 2016-04-16 um 08 42 57](https://cloud.githubusercontent.com/assets/9757393/14579595/af9c6450-03af-11e6-92b6-7fa96df9a62d.png)

**Comment by svbergerem** [comment]
This has been fixed by #6851.
