### ISSUE TITLE
CSS on settings page

### ISSUE THREAD

**Issue by zweipi** [diaspora/diaspora#6801]
When you make changes and update them on the settings page, the layout looks different afterwards.
The background-color of the body and the padding of  .framed-content get assigned to „.page-users.action-edit“ but not to „.page-users.action-update“.

(0.5.99 Development Branch)

**Comment by svbergerem** [comment]
Related to #5847.

**Comment by wildaces215** [comment]
Is this bug still open?

**Comment by cmrd-senya** [comment]
Yes
