### ISSUE TITLE
opera failure

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora#6808]
Unable to sign-in using opera web browser.

Access possible using firefox, xombrero
Unable to sign-in using opera, lynx, elinks, icecat

**Comment by jhass** [comment]
Can't reproduce with Opera 36.0.2130.65

**Comment by githubgnulinux** [comment]
Reproduce with icecat?

**Comment by jhass** [comment]
See #6194 for Icecat, you opened this for Opera, let's keep on focus.

**Comment by denschub** [comment]
duplicate of #6775, #6194 and #5906. If you disable JS, stuff won't work.
