### ISSUE TITLE
Photos - CSS floats causes ugly spaces when using different image sizes

### ISSUE THREAD

**Issue by codesune** [diaspora/diaspora#6809]
This applies to the photos page. Grid style is broken in the new layout (0.6.0.0 milestone), when different image sizes come into play. The reason for this is that floats without fixed heights are used.

See attached screenshot:

![photos-issue](https://cloud.githubusercontent.com/assets/18570528/14692927/00fe52c8-075b-11e6-9f71-d15aa2e661d1.png)

**Comment by Flaburgan** [comment]
I'm going to work on this one.

**Comment by Flaburgan** [comment]
PR opened https://github.com/diaspora/diaspora/pull/6838
