### ISSUE TITLE
Post to facebook is broken in develop

### ISSUE THREAD

**Issue by Zauberstuhl** [diaspora/diaspora#6815]
I haven't debugged it much yet, but you cannot post to your FB stream even with the pulish_actions permissions. It works on the stable branch.

I will have a look at this later..

(Maybe a sechat issue only.. please let me know if you have a working setup with the develop branch)
##

**Comment by cmrd-senya** [comment]
Is it present in current stable version?

**Comment by Flaburgan** [comment]
It is currently working on framasphere, and there is very few info here, so I'm closing it. Please reopen if you have something more specific to share (logs or anything).
