### ISSUE TITLE
Diaspora JSXC no OTR and no encryption

### ISSUE THREAD

**Issue by jh-mq135** [diaspora/diaspora#6825]
Hello, I have DIASPORA PRODUCTIVE with PROSIDY on Ubuntu Server 14.04 and as CLIENT Ubuntu 16.04 Pidgin, Diaspora, Firefox 46. Here it will not work in JSXC functions "Encrypt" (Castle) and verifying. For other users, the problem is similar. About Pidgin OTR works flawlessly.

![unbenannt](https://cloud.githubusercontent.com/assets/15912276/15111941/c77cc428-15ea-11e6-8486-78bbb7a35e34.PNG)

New connection jsxc-d79c40bdff3244835c978ce54f1680a4.js:18:21430
CONNECTING: null jsxc-d79c40bdff3244835c978ce54f1680a4.js:18:21430
CONNECTED: null jsxc-d79c40bdff3244835c978ce54f1680a4.js:18:21430
I am master. jsxc-d79c40bdff3244835c978ce54f1680a4.js:18:21430
close dialog jsxc-d79c40bdff3244835c978ce54f1680a4.js:18:21430
Discover muc service jsxc-d79c40bdff3244835c978ce54f1680a4.js:18:21430
Request server capabilities jsxc-d79c40bdff3244835c978ce54f1680a4.js:18:21430
: NetworkError: A network error occurred. <unbekannt>
Presence (@pod.gleisnetze.de): 0 jsxc-d79c40bdff3244835c978ce54f1680a4.js:18:21430
Presence (@pod.gleisnetze.de): 0 jsxc-d79c40bdff3244835c978ce54f1680a4.js:18:21430
Presence (@pod.gleisnetze.de): 0 jsxc-d79c40bdff3244835c978ce54f1680a4.js:18:21430
Variable name doesn't exist in [object Object]. It was created. jsxc-d79c40bdff3244835c978ce54f1680a4.js:18:21430
Variable sub doesn't exist in [object Object]. It was created. jsxc-d79c40bdff3244835c978ce54f1680a4.js:18:21430
Variable name doesn't exist in [object Object]. It was created. jsxc-d79c40bdff3244835c978ce54f1680a4.js:18:21430
Variable sub doesn't exist in [object Object]. It was created. jsxc-d79c40bdff3244835c978ce54f1680a4.js:18:21430
Variable name doesn't exist in [object Object]. It was created. jsxc-d79c40bdff3244835c978ce54f1680a4.js:18:21430
Variable sub doesn't exist in [object Object]. It was created. jsxc-d79c40bdff3244835c978ce54f1680a4.js:18:21430
Load bookmarks from local storage jsxc-d79c40bdff3244835c978ce54f1680a4.js:18:21430
Roster loaded jsxc-d79c40bdff3244835c978ce54f1680a4.js:18:21430
[webrtc] Could not update icon, because could not find jid for pod.gleisnetze.de jsxc-d79c40bdff3244835c978ce54f1680a4.js:18:21430
Presence (@swissjabber.de/e72266f4-0789-400e-b740-4f151fd31922): 3 jsxc-d79c40bdff3244835c978ce54f1680a4.js:18:21430
Presence (@pod.liebeleu.de/14bb5271): 5 jsxc-d79c40bdff3244835c978ce54f1680a4.js:18:21430
Presence (@pod.liebeleu.de/Xabber_J7CISPu8): 5 jsxc-d79c40bdff3244835c978ce54f1680a4.js:18:21430
[ERROR] [XMPP] undefined remote-server-not-found jsxc-d79c40bdff3244835c978ce54f1680a4.js:18:21430
webrtc.initWindow jsxc-d79c40bdff3244835c978ce54f1680a4.js:18:21430
Gemischte (unsichere) Anzeige-Inhalte von "http://i1-news.softpedia-static.com/images/news2/manjaro-linux-15-12-gets-linux-kernel-4-6-support-latest-cinnamon-3-0-desktop-503825-2.jpg" werden auf einer sicheren Seite geladen[Weitere Informationen] jquery-b4ef257e78e641d9a21c659ca472bba2.js:2:31073
Gemischte (unsichere) Anzeige-Inhalte von "http://i1-news.softpedia-static.com/images/news2/parsix-gnu-linux-8-5-atticus-receives-the-latest-debian-8-jessie-updates-503827-2.jpg" werden auf einer sicheren Seite geladen[Weitere Informationen] jquery-b4ef257e78e641d9a21c659ca472bba2.js:2:31073
Gemischte (unsichere) Anzeige-Inhalte von "http://www.technobuffalo.com/wp-content/uploads/2014/06/Google-IO-2014-Android-Figure-630x419.jpg" werden auf einer sicheren Seite geladen[Weitere Informationen] jquery-b4ef257e78e641d9a21c659ca472bba2.js:2:31073
Gemischte (unsichere) Anzeige-Inhalte von "http://i.creativecommons.org/l/by-sa/3.0/88x31.png" werden auf einer sicheren Seite geladen[Weitere Informationen] jquery-b4ef257e78e641d9a21c659ca472bba2.js:2:31073
Gemischte (unsichere) Anzeige-Inhalte von "http://52w.de/dias/nun_nazarener_kl.jpg" werden auf einer sicheren Seite geladen[Weitere Informationen] jquery-b4ef257e78e641d9a21c659ca472bba2.js:2:31073
Gemischte (unsichere) Anzeige-Inhalte von "http://pod.dapor.net/uploads/images/thumb_small_fd830fe1a108be2282c4.jpg" werden auf einer sicheren Seite geladen[Weitere Informationen] jquery-b4ef257e78e641d9a21c659ca472bba2.js:2:31073
Gemischte (unsichere) Anzeige-Inhalte von "http://www.spiegel.de/images/image-991021-thumbsmall-evqt.jpg" werden auf einer sicheren Seite geladen[Weitere Informationen] jquery-b4ef257e78e641d9a21c659ca472bba2.js:2:31073
Gemischte (unsichere) Anzeige-Inhalte von "http://miniature-calendar.com/wp-content/uploads/2016/05/160509mon-1024x1024.jpg" werden auf einer sicheren Seite geladen[Weitere Informationen] jquery-b4ef257e78e641d9a21c659ca472bba2.js:2:31073

**Comment by denschub** [comment]
We're tracking issues for our JSXC in an own repository, so please file a bug there: https://github.com/diaspora/jsxc/issues
