### ISSUE TITLE
mysql2 is needed on a postgresql installation

### ISSUE THREAD

**Issue by exmatrikulator** [diaspora/diaspora#6832]
I wanted to update to v0.5.8.0 and I got the error

`$ RAILS_ENV=production DB=postgres bin/rake db:migrate`
`Could not find activesupport-4.2.5.2 in any of the sources`
`Run 'bundle install' to install missing gems.`

`$ bundle install`
`...`
`An error occurred while installing mysql2 (0.4.3), and Bundler cannot continue.`
`Make sure that 'gem install mysql2 -v '0.4.3'' succeeds before bundling.`

Looks like that its happend in the commit 92fcbfbedea3a57979a99b93842848058f55c362

**Comment by SuperTux88** [comment]
You need to run `RAILS_ENV=production DB=postgres  bin/bundle install`, then it installs `pg` instead of `mysql2`

**Comment by exmatrikulator** [comment]
:+1:  Ok, thanks!
