### ISSUE TITLE
Do not add OpenGraph tags to all pages

### ISSUE THREAD

**Issue by beroal** [diaspora/diaspora#6840]
The canonical URL of a page for a tag ([example](https://espora.social/tags/xmpp)) is the main page ([example](https://espora.social/)).

**Comment by jhass** [comment]
I don't follow.

**Comment by beroal** [comment]
The canonical URL is the value of the attribute "content" of the tag "meta" with the attribute "property" equal to "og:url". It belongs to Open Graph data. For example,

> <meta property="og:url" content="https://espora.social/" />

I can't tell if a page for a tag is a node in the social graph or not. Either way.

1. If it is not a node, than it must not contain Open Graph data.

2. If it is a node, I doubt that pages with different content may have identical canonical URLs.

This issue is practical because a certain Firefox extension copies canonical URLs to the clipboard.
