### ISSUE TITLE
mobile web ui: like / reshare of posts from a user profile not possible.

### ISSUE THREAD

**Issue by kr428** [diaspora/diaspora#6841]
Seen on Android device, using Chrome or Firefox: Clicked on a user pic in my stream to get to the user profile. Scrolled down. Clicked on "heart" or "reshare" to interact with some post on the profile page. Outcome: The browser will scroll back to the top of the profile page without performing the action I actually tried to do. Known issue?

**Comment by Flaburgan** [comment]
@kr428 can you please tell us which pod you are using?

**Comment by kr428** [comment]
I'm on pod.geraspora.de.


Am 23. Mai 2016 15:01:43 schrieb Fla <notifications@github.com>:

**Comment by cmrd-senya** [comment]
Regression of #6670

**Comment by cmrd-senya** [comment]
The fix is easy as hell, however I have to think on a test to catch the issue.
