### ISSUE TITLE
Don't include subjects of private messages in email notifications

### ISSUE THREAD

**Issue by svbergerem** [diaspora/diaspora#6850]
As reported in this comment:
https://github.com/diaspora/diaspora/issues/4266#issuecomment-222394415

Changing [these two lines](https://github.com/diaspora/diaspora/blob/348a7b/app/mailers/notification_mailers/private_message.rb#L11-12) should fix this issue.

**Comment by SaiVardhan** [comment]
@svbergerem  Can you give me a road map for this to kick start as I am a newcomer.

Right now, I can see the private message(Lets say "Hi" is the subject) is getting displayed as "**Hi** *There’s a new private message in diaspora* for you to check out.* "

So how it should be changed

**Comment by svbergerem** [comment]
@SaiVardhan [These are the two lines](https://github.com/diaspora/diaspora/blob/348a7b/app/mailers/notification_mailers/private_message.rb#L11-12) that set the subject of a private message. For comments on private posts [we already don't add any private information to the subject](https://github.com/diaspora/diaspora/blob/aa6b590/app/mailers/notification_mailers/comment_on_post.rb#L12) so that might be something to compare this to. Right now we add a “Re:” in front of the subject for private messages if this isn't the first message in the conversation. If we remove the private information I think the “Re: ” will be useless so we could also remove that extra case. The translations for the private posts are [here](https://github.com/diaspora/diaspora/blob/bef5241/config/locales/diaspora/en.yml#L678) and there are [already some for private messages](https://github.com/diaspora/diaspora/blob/bef5241/config/locales/diaspora/en.yml#L685) so you might want to add the translation for the subject of private message notifications there. Afterwards you will have to add or modify tests in [spec/mailers/notifier_spec.rb](https://github.com/diaspora/diaspora/blob/0f04414/spec/mailers/notifier_spec.rb#L190-L233).

So here is your roadmap:

1. Replace the current subject of private message notification mails with a translated subject that doesn't include any private information
2. Drop the extra “Re: ” case
3. Add/Modify tests

Feel free to ask if you have any further questions. If you get stuck while working on this then please open an pull request with the work you did so far. That's the easiest way for us to help you with your code.

**Comment by SaiVardhan** [comment]
can you suggest subject I am thinking to have it as "Diaspora: Private Message"
