### ISSUE TITLE
really long usernames "break out" of their ui/css boxes (on /tags pages)

### ISSUE THREAD

**Issue by paskalito** [diaspora/diaspora#6853]
see example

https://therealtalk.org/tags/love

![love 2016-06-07 10-22-01](https://cloud.githubusercontent.com/assets/8012793/15850738/e5e9df98-2c99-11e6-8daa-69b7c2c8654d.png)

it's really a minor thing. but it's even doing it when "maxwith" is hit.
i think soloution should be something like they're get cut and dottet out (while link stays valid of course)

affects 0.5.99

**Comment by Flaburgan** [comment]
Look in the sky, it's a bird, it's a plain, it's @SansPseudoFix coming to fix overflow again!
