### ISSUE TITLE
No way to distinguish users when drafting a new message

### ISSUE THREAD

**Issue by gsantner** [diaspora/diaspora#6855]
Currently there is no way to distinguish which user is who when drafting a new message and start typing a name. Please add the id in the search popover e.g. `username <pod.mypod.com>`.

Pod-Version: 0.5.99.0-pbea9d795  

![unbenannt](https://cloud.githubusercontent.com/assets/6735650/15857837/c081e600-2cbd-11e6-817f-965b0eeaaabd.png)

**Comment by Flaburgan** [comment]
I was sure we already have an issue about this, but I don't find it.

**Comment by gsantner** [comment]
I also spent some time on searching, and couln't find it, but you're maybe right.

**Comment by svbergerem** [comment]
Duplicate of  #5091.

**Comment by denschub** [comment]
Good catch, thanks, @svbergerem!
