### ISSUE TITLE
consider xmpp login via app as activity

### ISSUE THREAD

**Issue by pravi** [diaspora/diaspora#6859]
If someone is logged into xmpp service using a native app, that should be considered an activity and counted towards active users.

More than statistics, this is important for account deletions. It would be very bad if people see their account is deleted even when they use the chat service every day.
##

**Comment by Zauberstuhl** [comment]
this can be handled by the xmpp server only. Since we will continue with the wrapper I suggest moving the issue to https://github.com/Zauberstuhl/gem_diaspora-prosody-config ?!

**Comment by SuperTux88** [comment]
The chat was removed with #8069, this is obsolete now.
