### ISSUE TITLE
Profile Picture

### ISSUE THREAD

**Issue by UbiSmith** [diaspora/diaspora#6865]
I just signed up for GitHub and found two things rather disconcerting:
1) How did GitHub have/get a profile picture for me?  I don't believe I ever signed up for an account in the past.
2) How can I delete my profile picture.  I prefer to have no photo.

**Comment by denschub** [comment]
We're not the [GitHub support](https://github.com/contact).

**Comment by UbiSmith** [comment]
Thanks.  I was not aware and I was not finding a support link easily on GitHub.  I will redirect my questions there.
