### ISSUE TITLE
eslint produces warnings about unknown rules

### ISSUE THREAD

**Issue by cmrd-senya** [diaspora/diaspora#6866]
Given we have a test commit https://github.com/cmrd-senya/diaspora/commit/3581e55d8f50c8db29350d74db59fa81023a3be9.

Running `pronto -c develop` with the commit checked out produces following output:
```
app/assets/javascripts/app/pages/getting_started.js:2 W: Definition for rule 'no-empty-function' was not found
app/assets/javascripts/app/pages/getting_started.js:2 W: Definition for rule 'no-self-assign' was not found
app/assets/javascripts/app/pages/getting_started.js:2 W: Definition for rule 'no-unsafe-finally' was not found
app/assets/javascripts/app/pages/getting_started.js:2 W: Definition for rule 'no-unused-labels' was not found
```

**Comment by denschub** [comment]
Okay, this is somewhat ridiculous. The eslint version shipped by `eslintrb` is heavily deprecated because of what I think is an error in the release process. I've opened a PR over ther (see https://github.com/zendesk/eslintrb/pull/7) and pinned a forked version in our `Gemfile` for now. Good catch!

**Comment by cmrd-senya** [comment]
I tested it and verify the issue has gone. Thanks!
