### ISSUE TITLE
Use released version of eslintrb after upstream merge

### ISSUE THREAD

**Issue by denschub** [diaspora/diaspora#6867]
@cmrd-senya discovered an issue in `eslintrb` in #6866, which made me open an upstream PR at https://github.com/zendesk/eslintrb/pull/7. I included a forked version of `eslintrb` in f9e0469183d3f6a37373c704ae3c5ad379543a84 so we have useful codestyle reviews... As soon as my PR is merged upstream, we need to switch back to a released `eslintrb` version.

This is a tracking issue to make sure the changes are not lost... Nothing to do here (yet).

**Comment by cmrd-senya** [comment]
fixed by #6880

**Comment by svbergerem** [comment]
Thank you @cmrd-senya. :)
