### ISSUE TITLE
Clicking two times on the aspects dropdown closes the publisher

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/diaspora#6879]

**Comment by svbergerem** [comment]
You mean a doubleclick on an aspect name? The first click closes the dropdown, the second one is a click outside of the publisher and thus closes it. What's the problem with this behavior?

**Comment by AugierLe42e** [comment]
No, I mean opening the aspect dropdown and then closing it.

**Comment by svbergerem** [comment]
I'm unable to reproduce this on the develop branch.

**Comment by AugierLe42e** [comment]
Hmm... I can only reproduce on FF dev 49.0a2...

**Comment by svbergerem** [comment]
I tried Firefox 47, 49.0a2 (2016-06-19, arch linux) and Chromium 51.0.2704.84. I'd say if you are unable to reproduce this with a stable browser version then we should close this. We can always reopen this later.
