### ISSUE TITLE
sign-in fails via mobile web browsers

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora#6884]
Using various mobile phone web browsers hosted in fdroid (e.g. lightning), unable to sign-in to diaspora

See https://github.com/diaspora/diaspora/issues/5906
https://github.com/diaspora/diaspora/issues/6807
https://github.com/diaspora/diaspora/issues/6194

**Comment by denschub** [comment]
Duplicate of the issues you already mentioned.
