### ISSUE TITLE
alt text attributes for diaspora menu

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora#6897]
For improved accessibility, please add alternative text for the 'notifications' and 'conversations' hyperlinks. This would be useful for graphical browsers in text mode (unlike https://github.com/diaspora/diaspora/issues/6884#issuecomment-228169055), whereby images/graphics are only viewed on demand (to minimise bandwidth)

**Comment by denschub** [comment]
The link has a `title` attribute, which my lynx shows and all screenreaders will read out loud.

<img width="718" alt="screen shot 2016-06-28 at 23 18 07" src="https://cloud.githubusercontent.com/assets/344777/16432713/ae8cb540-3d86-11e6-84ee-c6e5446d38a8.png">
