### ISSUE TITLE
Grammerly Plugin disables comment submission

### ISSUE THREAD

**Issue by AlexanderMcNulty** [diaspora/diaspora#6916]
Perhaps this is a part of your security, but I thought I would mention this issue that I discovered.
I just joined the community and I wanted to leave a comment. I was unable to while I had my Grammerly plug-in running; however, once i turned off the chrome plugin everything worked fine.

See images below:

(with plugin vs without plugin)
<img width="659" alt="screen shot 2016-07-13 at 1 44 23 pm" src="https://cloud.githubusercontent.com/assets/20212292/16819164/ffc64230-48ff-11e6-8c3d-9b197fa9aa49.png">
<img width="699" alt="screen shot 2016-07-13 at 1 44 33 pm" src="https://cloud.githubusercontent.com/assets/20212292/16819165/ffc7c1e6-48ff-11e6-8d85-f96b43eeefe7.png">

**Comment by denschub** [comment]
Interesting. Are there any error messages in the browsers error console? In chrome, press F12 and Ctrl-Alt-I/Cmd-Option-I and select Console.

**Comment by svbergerem** [comment]
We display the submit button if the comment box is focused or the input is valid (non-empty). We do that for the submit button next to the comment box here: https://github.com/diaspora/diaspora/blob/c7e3f2f/app/assets/stylesheets/comments.scss#L46

Grammarly wraps the comment box with `grammarly-ghost` and `grammarly-btn` elements and thus the submit button isn't next to the comment box anymore. I tend to consider this a Grammarly bug rather then a diaspora\* bug.

**Comment by jhass** [comment]
Agreed.
