### ISSUE TITLE
Add hovercards to recipients in conversation composer

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#6933]
I've just discovered that when you have more than one contact for a person, it is impossible to tell which account is which in the conversation composer if their screen name is the same, as that is all that is shown.

I suggest adding a hovercard here. I think it would be good to add them both to the recipients in the list and to the auto-complete results when typing, so that you can find which account is which before adding that account to the recipients list.

(Apologies if this has already been raised - I've done a search but not found anything.)

**Comment by Flaburgan** [comment]
I thought we had an issue about that too. I don't feel like we should have an hovercard here, but this should work like mentions (indicating the diaspora id), and https://github.com/diaspora/diaspora/pull/6917 should add that ;)

**Comment by goobertron** [comment]
Ah, I see what you mean. The pod I use is on 0.5.9.1, but I've just checked out one running develop and there's now an ID included. Nice change! Yes, that would be a good solution in the conversations composer. I suppose it's best if I leave this open until #6917 has been tested and merged and it's certain that this functionality will be included.

**Comment by svbergerem** [comment]
@goobertron I guess this is a duplicate of #5091?

**Comment by goobertron** [comment]
Ah, well found, that man! Closing this now.
