### ISSUE TITLE
conversations mailing list functionality

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora#6936]
Loomio is inaccessible via anonymous internet (e.g. tor) and probably also inaccessible via diaspora account sign-in.

The 'conversations' function in diaspora should be used as a mailing list tool, to subscribe to specific discussion threads concerning diaspora

https://diasp.eu/posts/4498087

**Comment by denschub** [comment]
https://github.com/diaspora/diaspora/issues/6938#issuecomment-237523692

**Comment by cmrd-senya** [comment]
BTW, [there are](https://wiki.diasporafoundation.org/How_we_communicate#Mailing_Lists) mailing lists of diaspora project. They aren't widely used, but since they are on that page, I guess they may be considered as an official place for discussions of non-technical questions. You can use it from tor and it doesn't require cloudflare captchas or google account.

**Comment by githubgnulinux** [comment]
The geevil mailing lists seem inaccessible via anonymous internet. What is wrong with mailman?

**Comment by githubgnulinux** [comment]
Also note that the geevil mailing list system requires ability to render images, not possible in a text mode browser and further evidence of discrimination.

**Comment by jhass** [comment]
Please learn to read: https://wiki.diasporafoundation.org/How_we_communicate#Joining_a_mailing_list

**Comment by githubgnulinux** [comment]
Please learn to read: 

"...requires ability to render images, not possible in a text mode browser..."

Read familiar? For example: https://github.com/diaspora/diaspora/issues/6897

**Comment by jhass** [comment]
As outlined in the wiki, you don't even need a browser to participate on the mailing lists. If you're unable to use your own MUA, there's only yourself to blame.

**Comment by githubgnulinux** [comment]
Seems you are unaware of the mailing list instructions which unless mistaken, require redirect to a web page hyperlink which requires graphics mode rendering...

**Comment by cmrd-senya** [comment]
Do you mean this email?
![2016-08-04 15 34 49](https://cloud.githubusercontent.com/assets/10187586/17401939/2c7d6622-5a59-11e6-9aef-b0a6cee7e509.png)

**Comment by githubgnulinux** [comment]
If you have posted an image, not visible using a text-mode browser. Anyway, mailing list subscription instructions below:

"We received your request to join diaspora-discuss. In order for us to complete the request, please reply to this email or visit the following confirmation URL:

https://groups.google.com/group/diaspora-discuss/subscribe

If you have questions related to this or any other Google Group, visit the Help Center at https://groups.google.com/support/.

Thanks,

Google Groups"

However, just noticed that this instruction includes the option to reply to the message, avoiding the need to use the web page; if so, sorry for this mistake

**Comment by cmrd-senya** [comment]
> this instruction includes the option to reply to the message, avoiding the need to use the web page; 

That's what I meant.

**Comment by githubgnulinux** [comment]
OK understood, sorry and thanks.
