### ISSUE TITLE
monitor diversity in diaspora

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora#6938]
Inspired by a post (https://diasp.eu/posts/4504438), proposal to answer the following:

1. How many women are diaspora programmers?
2. How many women are diaspora users?
3. What is the strategy of diaspora to achieve parity?

**Comment by prellele** [comment]
Thank you for posting this issue! I think this would be much better preserved on Loomio, please consider opening a thread there.

**Comment by githubgnulinux** [comment]
Unable to use loomio for various practical and strategic reasons. Others are of course free to post to loomio...

https://github.com/diaspora/diaspora/issues/6936

**Comment by Flaburgan** [comment]
I can access loomio without any troubles using Tor and you can register as on github without having to use any third party service. Please open a topic on loomio, this is not related to the code.

**Comment by githubgnulinux** [comment]
> Flaburgan:

As you know, loomio is hosted by cloudflare who provide a proprietary reverse proxy web service. Whilst you may (or not) have selected a specific tor relay/exit node that is not marked by cloudflare, that decision is random. At the time of writing, access to loomio is denied until a proprietary geevil/recapta image is selected (impossible on a text-mode browser).

As for relation to code quality, politely referred to the diaspora post ;)

**Comment by denschub** [comment]
As I told you many times before, GitHub is not the place to discuss about project management decisions and I will not repeat this anymore. You've opened enough issues you can read about the reasons in detail.

Please be aware that, starting now, I'll simply close all issues you create which are not suitable for GitHub with a link to this comment.

**Comment by githubgnulinux** [comment]
> Please be aware that, starting now, I'll simply close all issues you create

Good for you! Surprising you haven't automated your discrimination. Maybe you should create a bug: "Automatically close bugs unpalatable due to title and/or original poster". It would probably take minutes to make top priority, test, application, closure...

**Comment by jhass** [comment]
Leaving out context when quoting is just too much fun to not do it, isn't it?

>  I'll simply close all issues you create **which are not suitable for GitHub**

**Comment by githubgnulinux** [comment]
As is the failure to declare in an open non-discriminatory, transparent explanation of what is (not) "suitable".

So, in common with the open decision framework, what is your reference that you use to declare "suitability"?

**Comment by border0464111** [comment]
Sorting what is off topic and what's no is a quite easy thing to do. It seem clear to me that it a politic problem not a bug.

From my understanding some if not most programmers really dislike politics inside project devlopement operations due to the fact that is generate a lot of tentions and distractions from the actuals task. This is a work place, and people are acheiving stuff. 
 
Your problem does not seem to be about discrimination and sensorship. But from your innability to use loomio. Forcing your way on github Is a lack of respect for devlopers and undermine  the establish politic-free safeplace that devs request.

Plz respect people triggers and requests for safeplaces. 
  

 

.

**Comment by githubgnulinux** [comment]
Assuming equal access is a lack of respect for those affected by barriers to equal participation.

**Comment by border0464111** [comment]
Plz look for solutions not way to make a point and force your self here.

If you need an ssh ssh tunnel you need to ask one, People are looking foward for solutions, and will be happy to help you if you ask, But if you came in with a fighting attitude and does not respect community, Poeple will try to fight you just by reflex. Seem like common sense to me.

**Comment by githubgnulinux** [comment]
> Poeple will try to fight you just by reflex

A documented defence mechanism in the industry; unable to tolerate criticism.

**Comment by border0464111** [comment]
Yeah and im rly trying to defuse it in my last two post. 
- By explaining people expectations and how some behaviours can be rude for them, 
- narrowing the real root of the problem, 
- And come up with positive and inclusive solutions. 

But it look like you prefer to continue the internet fight, and don't care much about a way to access loomio.
Im not gonna play this game it's just sucking my energy for no result.

**Comment by jhass** [comment]
Thank you for your time @border0464111, @githubgnulinux [is just a regular](https://github.com/diaspora/diaspora/issues?q=is%3Aissue+author%3Agithubgnulinux+is%3Aclosed).

**Comment by githubgnulinux** [comment]
How does an ssh tunnel from a (cloudflare banned) ip address enable access through cloudflare?

**Comment by border0464111** [comment]
@jhass  Oh damn. I see, 
@githubgnulinux  http://www.catb.org/~esr/faqs/smart-questions.html

This is my last comment in this tread.

**Comment by denschub** [comment]
Locking this thread since it's leading nowhere but into an area with personal attacks.
