### ISSUE TITLE
update interface instructions for stream and public activity

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora#6941]
As a result of 

https://github.com/diaspora/diaspora/issues/6938#issuecomment-237536275

Descriptions of bugs/enhancements/comments will be published within diaspora

Therefore, for this feature request, see

https://diasp.eu/posts/4489425

**Comment by jhass** [comment]
The contents of the project website are managed at https://github.com/diaspora/diaspora-project-site
