### ISSUE TITLE
Generate wrong url for "protocol relative URL" in profile's bio

### ISSUE THREAD

**Issue by AndreySV** [diaspora/diaspora#6958]
Steps to reproduce:

1. In profile's 'Your bio' field enter code 

`<a href="http://u.fsf.org/16e"><img src="//static.fsf.org/nosvn/images/badges/fsfs_icons_beige-bg.png" alt="Free Software, Free Society"></a>`

2. Click 'Update profile'
3. Check profile page and notice that alternative text is show instead of image.

The problem is here "protocol relative URL" in img tag. All is working if protocol relative URL is replace with 'http://' or 'https://' URL.

**Comment by jhass** [comment]
Just always use `https` if available, this technique is an anti-pattern these days.
