### ISSUE TITLE
Opening the aspect dropdown and clicking anywhere closes the publisher on FF dev

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/diaspora#6979]
I'm not sure what's going on but opening the aspect dropdown in the last Firefox developer edition (50.0a2 (2016-08-13) here) inserts a div that take the whole page and triggers the closing of the publisher when clicking anywhere in the page except the dropdown menu (this means when clicking on the dropdown button itself too).

![dropdown-backdrop](https://cloud.githubusercontent.com/assets/3429231/17644886/8fdc1758-6194-11e6-9c5c-5e1bc710e41a.png)

According to the Bootstrap's docs:

> On mobile devices, opening a dropdown adds a `.dropdown-backdrop` as a tap area for closing dropdown menus when tapping outside the menu, a requirement for proper iOS support.

This is browser specific and do not reproduce on Firefox 48 but maybe it is worth neutralizing this `.dropdown-backdrop` element?

**Comment by svbergerem** [comment]
Clicking anywhere on the page outside of the publisher closes the publisher. It has been like that for quite some time and it behaves the same on the current master branch. Clicking on the dropdown button itself shouldn't close the publisher and I'm neither able to reproduce this with Firefox 50.0a2 (2016-08-05) nor with Firefox 50.0a2 (2016-08-13). I'm also unable to find the `.dropdown-backdrop` element here.

**Comment by AugierLe42e** [comment]
> Clicking anywhere on the page outside of the publisher closes the publisher. It has been like that for quite some time and it behaves the same on the current master branch.

I meant it also closes the publisher when you click *inside* the publisher. That's weird you can't reproduce it. I've reset my local develop branch to upstream's develop branch to be sure and I confirm that it is still happening on FF 50.0a2 (2016-08-13). I'll test with Firefox for Android but if everything goes normal, I'll close this.

**Comment by AugierLe42e** [comment]
I confirm that it's happening both on Firefox for Android and [diaspora for Android](https://github.com/Diaspora-for-Android/diaspora-android) (Blink) on diaspora-fr.org. I opened #6981 to fix this.

**Comment by svbergerem** [comment]
The `ontouchstart` event has to be available to add the backdrop: https://github.com/twbs/bootstrap/blob/df08d95495cf3cd9278099dc91c630423eccc846/js/dropdown.js#L69

After enabling the touch events in the responsive design mode I was able to reproduce the bug.

**Comment by AugierLe42e** [comment]
Ah, yes! I was testing #6555 earlier so I did enable the touuch events.
