### ISSUE TITLE
[mobile] Markdown rendering horizontal line

### ISSUE THREAD

**Issue by gsantner** [diaspora/diaspora#6988]
The markdown below renders differently/inconsistent on mobile and desktop view:
There should be a horiziontal line below the 3 underscores.  

```
## Headline
- text
- more text
___
#### Another Headline

text
```

Desktop:
![bildschirmfoto von 2016-08-15 12-00-15](https://cloud.githubusercontent.com/assets/6735650/17661525/f66fbe2e-62df-11e6-839b-e3030e814942.png)

Mobile:
![bildschirmfoto von 2016-08-15 11-59-36](https://cloud.githubusercontent.com/assets/6735650/17661531/fe31a38e-62df-11e6-8433-244275883d62.png)

BTW: I know it works if there are empty lines between, but that's what the issue is NOT about.

**Comment by jhass** [comment]
We really need to replace redcarpet with something following the commonmark spec.

**Comment by AugierLe42e** [comment]
Could rendering post client-side be a viable solution?

**Comment by cmrd-senya** [comment]
Is using server-side markdown rendering in mobile is a design decision made on purpose to reduce complexity/loading?
