### ISSUE TITLE
Aspect membership dropdown doesn't show on search if ID is being fetched

### ISSUE THREAD

**Issue by cmrd-senya** [diaspora/diaspora#6989]
When you make a search query for a yet unknown diaspora ID, the `PeopleController` initiates WebFinger query in the background. In this case, the search result list is populated after the discovery has been finished. In this case aspect membership dropdown doesn't get populated properly.

regression from #6864

**Comment by svbergerem** [comment]
https://github.com/diaspora/diaspora/blob/df440ed/app/assets/javascripts/contact-list.js#L19

**Comment by cmrd-senya** [comment]
Yep, thanks, found that already. I'm currently seeking the way to write a test for the feature.
