### ISSUE TITLE
More-button of mobile views' public activities stream points to my activities stream

### ISSUE THREAD

**Issue by vanitasvitae** [diaspora/diaspora#6999]
When I'm on mobile view at /public, scroll to the bottom of the stream and click the "more"-button, I end up at /activity?max_time=XXXXXXXX instead of /public?max_time=XXXXXXXX

Is this intended?

**Comment by vanitasvitae** [comment]
PS: My pod is geraspora.de

**Comment by svbergerem** [comment]
This might be a duplicate of #5037.

**Comment by denschub** [comment]
Yeah, dope of #5037.

**Comment by denschub** [comment]
Erm, dupe.

**Comment by AugierLe42e** [comment]
Dope is nice too :p

**Comment by vanitasvitae** [comment]
Is this bug fixed in 0.6.0.0?

**Comment by svbergerem** [comment]
@vanitasvitae No, this hasn't been fixed yet, but #5037 describes the same issue so there is no need to have a second open issue for the same bug.

**Comment by vanitasvitae** [comment]
Okay, I just wanted to know. Thanks.
