### ISSUE TITLE
Possible regression: Change in scope of mentions and conversations

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#7007]
In `develop`, it's possible to @mention and start conversations with people not in your contacts. This was not previously possible. In 0.5.10, you can only @mention people in your aspects, and you can only start a conversation with someone with whom you had mutual sharing.

I've just tested this in two pods running `develop` (diaspora-fr.org and sechat.org), to check it wasn't a pod customisation.

For both @mentions and addressing a conversation, when you start typing a name, the auto-complete suggestions include people who are sharing with me but who aren't in my aspects.

I don't know whether this is a regression or an intended feature, but thought I should 'mention' it in 'conversation' (sorry) before the code freeze takes place. I've searched issues but couldn't find anything relating to it.

**Comment by svbergerem** [comment]
#7001 should've fixed the issue for conversations and it [looks like](https://github.com/Flaburgan/diaspora/commits/diaspora-fr) that fix is not available on diaspora-fr right now.

For mentions I thought that you don't need a mutual contact to mention them. Am I wrong? Do we have some rules who you should be allowed to mention?

**Comment by cmrd-senya** [comment]
> Do we have some rules who you should be allowed to mention?

IIRC, one may mention in post anyone who can see that post.

**Comment by svbergerem** [comment]
We filter mentions server-side when creating posts. Since the suggestions don't depend on the aspects you selected (even on the master branch) I don't see a problem with suggesting contacts with a non-mutual relationship (only sharing or only receiving).

**Comment by goobertron** [comment]
> #7001 should've fixed the issue for conversations and it looks like that fix is not available on diaspora-fr right now.

Ah, thank you. My search didn't catch that PR.

> For mentions I thought that you don't need a mutual contact to mention them.

My understanding is that to be able to @mention someone, you don't need mutual sharing, but you need to be sharing with that person (i.e. they need to be in your aspects). If they are sharing with me but they're not in my aspects, I can't @mention them. This is certainly how it's always worked for me, and is still the case in 0.5.10 (I've just double-checked). At the moment, it can work with a one-way sharing relationship in either direction.

I don't have a problem with the scope being increased in this way, which is why I wondered whether it was intended or not. If anything, it makes more sense to be able to @mention someone who is sharing with you, as they have indicated that they want contact with you. With the old behaviour - you can @mention anyone you have added to your aspects, regardless whether they are sharing with you - there is more risk of unwanted messages. So I don't see any privacy/spam issue with the scope being increased like this, keeping the old behaviour but adding the ability to mention people who share with me. If everyone's happy with this change, let's keep it this way! (I'll just update the tutorials to include this.)

**Comment by svbergerem** [comment]
In public posts you should've already been able to mention everyone as long as you do it manually. (`@{name; diaspora_id@pod.tld}`) This release 'just' changes the frontend so you are able to select someone in the dropdown who is _only_ sharing with you. Thus I also don't see any privacy issues but it would be great if you could update the tutorials accordingly. :)

**Comment by goobertron** [comment]
> In public posts you should've already been able to mention everyone as long as you do it manually. (@{name; diaspora_id@pod.tld})

I thought that was an unwanted loophole.

Anyway, if this is an intentional change, I'm happy with that. I'll close this now.
