### ISSUE TITLE
Can't disable notifications of a freshly liked post

### ISSUE THREAD

**Issue by noplanman** [diaspora/diaspora#7008]
When liking a post, it does not automatically update the little bell notification icon.
So in the background, the notifications have been enabled, yet this is not visible on the front end.

When I then click the bell icon, to disable the notifications, I get a `422 Unprocessable Entity` error.

After a refresh of the page, the icon is properly set and enabling/disabling notifications works properly again.

**Comment by svbergerem** [comment]
This is a duplicate of #5811. Thank you anyway for reporting this issue.

**Comment by noplanman** [comment]
D'oh, didn't find that one with my search, sorry!

**Comment by svbergerem** [comment]
No problem. I also needed two tries to find it and I knew it was there.
