### ISSUE TITLE
ui: strange duplication of tag on tag search

### ISSUE THREAD

**Issue by paskalito** [diaspora/diaspora#7015]
when i search for an "nonexisting" tag.

![bildschirmfoto vom 2016-08-21 13-44-22](https://cloud.githubusercontent.com/assets/8012793/17836957/e2b91220-67a5-11e6-8aab-f9e1ad8bf8a3.png)

![bildschirmfoto vom 2016-08-21 13-44-01](https://cloud.githubusercontent.com/assets/8012793/17836958/f3d5a992-67a5-11e6-9a69-2600a83ea628.png)

(the lower (white one) seems to be wrong)

**Comment by paskalito** [comment]
also appears on non empty tags.

**Comment by goobertron** [comment]
Which pod are you on, and which version of the software?

I've just tried this one several pods (one using 0.5.10; the other two using `develop`) and none reproduced this behaviour. Indeed, on each of them I get the 'closed' publisher window, with the buttons underneath it. See below.

![_tagsearch](https://cloud.githubusercontent.com/assets/2530168/17837121/ce2cedee-67a1-11e6-9196-5721cda9b210.png)

**Comment by svbergerem** [comment]
I was able to reproduce this on the latest develop branch but I saw a similar result like @goobertron on an earlier version. There the `closed` class for the publisher was missing and instead it had a `mention_popup` class. I don't know yet which commit changed this but I think the new version is the correct one.
