### ISSUE TITLE
XMPP Videochat 

### ISSUE THREAD

**Issue by ShalokShalom** [diaspora/diaspora#7046]
[feature request]

**Comment by svbergerem** [comment]
JSXC already supports video chats. @Zauberstuhl I guess our version also does that?

**Comment by Zauberstuhl** [comment]
yes, but in our version its pretty unstable. the latest update should fix the issue https://github.com/diaspora/jsxc/issues/156

**Comment by cmrd-senya** [comment]
Damn XMPP Jingle is unstable nearly everywhere

**Comment by svbergerem** [comment]
Ok, but since our version supports video chats I guess we can close this issue. Issues about improving the feature could be opened in the [diaspora/jsxc](https://github.com/diaspora/jsxc/) repo.
