### ISSUE TITLE
iOS native application

### ISSUE THREAD

**Issue by MartinDelille** [diaspora/diaspora#7047]
Is there any plan for an iOS native client for diaspora? I'll be happy to help if it is coded in swift.

**Comment by svbergerem** [comment]
#3467 has to be fixed first. I heard some devs discussing the possibility of having native apps afterwards but I don't see any plans right now.

**Comment by jhass** [comment]
In any case it's nothing that will be developed in this repo. #3467 is there to track API progress, everything else should go to the ML.
