### ISSUE TITLE
[API] With authorization code flow the state parameter is missing in the callback URI

### ISSUE THREAD

**Issue by cmrd-senya** [diaspora/diaspora#7052]
I'm playing around with omniauth with an aim to build an omniauth strategy for diaspora. I'm trying to reuse this library: https://github.com/jjbohn/omniauth-openid-connect.

The request to diaspora I managed to get generated was following:

```
GET "/api/openid_connect/authorizations/new?client_id=df90d24ecc6dde9d8bae32af2ac7fdff&nonce=ec1e2c533cea5ca445a82e78ceda6aac&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fusers%2Fauth%2Fdiaspora%2Fcallback&response_type=code&scope=openid+name+profile&state=d3f0755568c16544937a52a76fa1a130
```

There is `state=d3f0755568c16544937a52a76fa1a130` among the parameters.

The OpenID Connect specification in [this section](https://openid.net/specs/openid-connect-core-1_0.html#AuthResponse) says

> When using the Authorization Code Flow, the Authorization Response MUST return the parameters defined in Section 4.1.2 of OAuth 2.0 [RFC6749] by adding them as query parameters to the redirect_uri specified in the Authorization Request using the application/x-www-form-urlencoded format, unless a different Response Mode was specified.

Section [4.1.2](https://tools.ietf.org/html/rfc6749#section-4.1.2) of the OAuth 2.0 spec says that the `state` parameter is

> REQUIRED if the "state" parameter was present in the client authorization request.

However when I push the "Approve" button at the 

```
/api/openid_connect/authorizations/new?client_id=37c5044f1491004aaeb6f6e89c27c7cb&nonce=723fe2fc78594dbed50f9134d5a3306b&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fusers%2Fauth%2Fdiaspora%2Fcallback&response_type=code&scope=openid+name+profile&state=996af52c79f3ff5136c3ae92c776df44
```

I'm redirected to this callback URI

```
http://localhost:3000/users/auth/diaspora/callback?code=7fd09699ced2c27455533399e9c195d0ffaed0e7a3ffe265cbba9220c4cb517f
```

The `state`  parameter is clearly missing, and because of this [omniauth-openid-connect](https://github.com/jjbohn/omniauth-openid-connect) panics and returns 401 response to a client.

**Comment by KentShikama** [comment]
Yeah, it is recommended for the request but required in the response indeed. I missed that for sure. I don't have time to write the tests and test it out but I believe something like the follows should work for a fix:

```
WL-217-234:openid_connect kent$ git diff
diff --git a/app/controllers/api/openid_connect/authorizations_controller.rb b/app/controllers/api/openid_connect/authorizations_controller.rb
index 7103ad9..8e552e8 100644
--- a/app/controllers/api/openid_connect/authorizations_controller.rb
+++ b/app/controllers/api/openid_connect/authorizations_controller.rb
@@ -125,6 +125,7 @@ module Api
         session[:response_type] = @response_type
         session[:redirect_uri] = @redirect_uri
         session[:scopes] = scopes_as_space_seperated_values
+        session[:state] = params[:state]
         session[:nonce] = params[:nonce]
       end
 
@@ -149,6 +150,7 @@ module Api
         session.delete(:response_type)
         session.delete(:redirect_uri)
         session.delete(:scopes)
+        session.delete(:session)
         session.delete(:nonce)
       end
 
@@ -162,6 +164,7 @@ module Api
         req.update_param("redirect_uri", session[:redirect_uri])
         req.update_param("response_type", response_type_as_space_seperated_values)
         req.update_param("scope", session[:scopes])
+        req.update_param("state", session[:state])
         req.update_param("nonce", session[:nonce])
       end
 
diff --git a/lib/api/openid_connect/authorization_point/endpoint_confirmation_point.rb b/lib/api/openid_connect/authorization_point/endpoint_confirmation_point.rb
index 08e99b2..e46f4d3 100644
--- a/lib/api/openid_connect/authorization_point/endpoint_confirmation_point.rb
+++ b/lib/api/openid_connect/authorization_point/endpoint_confirmation_point.rb
@@ -32,6 +32,7 @@ module Api
         def approved!(req, res)
           auth = find_or_build_auth(req)
           handle_approved_response_type(auth, req, res)
+          res.state = req.state
           res.approve!
         end
```

**Comment by cmrd-senya** [comment]
I hope I'll take care of it as soon as #7059 is sorted out.

**Comment by Flaburgan** [comment]
#7156 is merged, is this issue solved?

**Comment by KentShikama** [comment]
@Flaburgan Yeah imo
