### ISSUE TITLE
When I add someone to an aspect the page refreshes and I lose my work

### ISSUE THREAD

**Issue by kapcom01** [diaspora/diaspora#7072]
Hello,

Today I was commenting on a post and I had written about 500 words. Before I finish my comment I thought it would be nice to add this person to my aspects so I can follow similar posts of him but doing so I lost my comment.

Maybe a solution is not to refresh the page when we add someone to an aspect but I guess it can be solved in many other ways.

Thanks.

**Comment by svbergerem** [comment]
I guess we could re-render the profile header instead of re-rendering the whole profile. Am I missing anything?
