### ISSUE TITLE
'What’s new?' Link in footer references 404 page

### ISSUE THREAD

**Issue by prellele** [diaspora/diaspora#7073]
Clicking 'What’s new?' in the footer guides you to a 404 page on Github.

**Comment by Flaburgan** [comment]
Hi @prellele can you please tell us which pod you are using?

**Comment by svbergerem** [comment]
@Flaburgan: @prellele is the podmin of despora.de

**Comment by denschub** [comment]
That link links to `https://github.com/diaspora/diaspora/blob/[git revision]/Changelog.md`, which is a 404 if the commit your pod running on a non-upstream commit id. Maybe we should expose a config for that, though.

**Comment by prellele** [comment]
Ah, I thought its just a static url. Checked it only on despora.de and pod.geraspora.de.
I like @denschub proposal, configurable the git repo would be great.

**Comment by svbergerem** [comment]
This also works with non-upstream commit ids, as long as they exist on GitHub. On my pod the "What's new?" link links to https://github.com/diaspora/diaspora/blob/8f053409f42b19c60f71405821e3e79c6369de8f/Changelog.md and https://github.com/diaspora/diaspora/commit/8f053409f42b19c60f71405821e3e79c6369de8f is a non-upstream commit id.

**Comment by denschub** [comment]
[Only if the repo is a fork](https://github.com/diaspora/diaspora/blob/eee3bf19c6a9d57ea18198eb50ed7f33c416de26/Changelog.md).
