### ISSUE TITLE
Tag-URLs in People Hovercards incorrect

### ISSUE THREAD

**Issue by prellele** [diaspora/diaspora#7074]
Linked URLs of Tags in the Hovercards of People are incorrect - the first char of the tag gets removed.

E.g: Tag Diaspora
URL is: /tags/iaspora
URL should be: /tags/diaspora

**Comment by svbergerem** [comment]
This might be a regression from #6864. The '#' symbol is now missing in front of the tags. Adding it client side or in the profile presenter should fix the problem.

**Comment by cmrd-senya** [comment]
I'll take a look
