### ISSUE TITLE
Disable swipe animation in gallery

### ISSUE THREAD

**Issue by paskalito** [diaspora/diaspora#7078]
To me the swiping animation that leads to next/previous picture in the gallery is veery disruptive and anoying.
And i can't find any positive side of it.
I first thought oh at least it makes sense for touch devices, since they can drag their pictures further, but then i found out that this gallery isn't even used ( at least in mobile where definitely most touch is going on)

from a usability standpoint: the arrows clearly indicate i can go left or right, and the fact that the picture just changed is also indication enough that the picture actually changed. so no need for a screenfilling animation

a quick fix could possibly be just increasing the speed of that animation to a point one does not notice it anymore. this would allow clean enjoyable picture viewing and let those who whant to touch and drag still with the possiblity to do so.

**Comment by AugierLe42e** [comment]
It's possible to disable the animation. I'm personnally against. I find the animation makes the interface more lively.

**Comment by paskalito** [comment]
So what do i have to do?
Must i start a vote/discussion on loomio?

Other thought would this also easily be archieved via userscript? if yes i would appreciate a hint to the code fragment that needs to be changed.

**Comment by denschub** [comment]
Nah, sorry.

I don't think we're gonna start discussing about animation that a third party library provides and which makes actually sense from an UX perspective. If you feel strong, feel free to raise your point on loomio, but for now, I'm going to close this.
