### ISSUE TITLE
New Publisher: Doesn't show embedded image in preview

### ISSUE THREAD

**Issue by TheRadialActive** [diaspora/diaspora#7103]
The new publisher is really awesome. One bug seems to be, that embedded images aren't shown in preview view (as you can see at the "![]()"-Syntax

![pub2](https://cloud.githubusercontent.com/assets/828436/18544191/c9f2cadc-7b33-11e6-8b7b-f619c1c01b9e.png)
![pub1](https://cloud.githubusercontent.com/assets/828436/18544192/c9f4c954-7b33-11e6-83f5-ef7bab08055a.png)

But after posting everything is fine.

**Comment by SansPseudoFix** [comment]
Actually, it works for me (diaspora-fr.org):

![preview](https://cloud.githubusercontent.com/assets/6507951/18552824/71caa250-7b5e-11e6-8f1b-b1b9662958de.png)
![preview2](https://cloud.githubusercontent.com/assets/6507951/18552825/71e37582-7b5e-11e6-8dfb-a1d193750522.png)

**Comment by goobertron** [comment]
Works fine for me as well, using the same image and code:

`[![](http://alsenstrasse.com/wp-content/uploads/2016/08/Strassenfest2016-724x1024.jpg)](http://alsenstrasse.com/?p=2292)`

Tested on diaspor-fr.org and pod.diaspora.software.

**Comment by SuperTux88** [comment]
I close this, because it is a geraspora-only problem. @denschub allows only images loaded with https, and that's why the preview with http images doesn't work. After posting they are loaded through camo with https and therefore work.

**Comment by goobertron** [comment]
If it's related to camo, won't that affect all pods that use camo? As camo support is in the core code base, it would probably be a good idea to find a UI solution that will explain to users why their embedded image isn't showing in the preview, as a missing image preview with no explanation can be considered a bug.

It could be a dummy image, something like a blank rectangle saying something like 'this non-secure image will be displayed after posting'.

It could be better phrased; 'non-secure image' might frighten people without really explaining to them what's happening...

I think it's probably worth keeping this issue open, if you agree with the above.

**Comment by SuperTux88** [comment]
No, it's not related to camo, it's a header (`Content-Security-Policy`) that is not set by default, only on geraspora (or maybe other pods too. But it's something the podmins do and not default. I have the same header with different settings on my Pod, and I allow http images, because of the preview and because camo doesn't work everywhere, see #6124)

**Comment by goobertron** [comment]
Oh, OK. Thanks for explaining!

**Comment by SuperTux88** [comment]
With #7128, this is now fixed on geraspora :)
