### ISSUE TITLE
Admin user search not finding an existing user

### ISSUE THREAD

**Issue by Hypolite** [diaspora/diaspora#7106]
I have [this spam user](https://diaspora.aeriesguard.com/people/01623a905e650134a38b0242ac110007) I want to block from the admin panel.

However, no matter the search field I fill (GUID or username, two pieces of information I have), the search turns up negative. See the following screenshots:

![screen shot 2016-09-16 at 6 04 38 pm](https://cloud.githubusercontent.com/assets/925415/18602557/20e2638e-7c38-11e6-8c9b-68a761473ad1.png)

![screen shot 2016-09-16 at 6 04 58 pm](https://cloud.githubusercontent.com/assets/925415/18602560/2590e220-7c38-11e6-96eb-eede5087d703.png)

Is there any way I can debug the search myself?

Also tested:
- username=marina
- username=marina*
- username=marina88889
- email=marina88889@joindiaspora.com

I tried to find my account, without success:
- username=mrpetovan
- username=mrpetovan*
- username=mrpetovan@diaspora.aeriesguard.com

**Comment by SuperTux88** [comment]
The search in the admin panel is only for users on your pod.

**Comment by Hypolite** [comment]
Thanks for the answer, but I can't find myself either. Also, isn't there a copy of some user data of the people that I encounter on my pod? In the Report interface, the button "Details about the author" goes straight to the Admin User Search, if you can't find anyone who didn't subscribe on your pod that's a problem.

**Comment by SuperTux88** [comment]
you should be able to find yourself (by username, email or guid).

Maybe we should display the "Details about the author" button only, if the author is local. Or link it to somewhere else (profile?), or also display remote people when searched with guid?

**Comment by Hypolite** [comment]
I'm able to search myself by username or guid now on a different computer. Weird, I was sure those tests failed the first time.

> Maybe we should display the "Details about the author" button only, if the author is local. Or link it to somewhere else (profile?), or also display remote people when searched with guid?

After a cursory research, it appears that accounts that didn't register on the pod are "People", while accounts registered on the pod are proper "Users". Is there any admin action that can be performed at the People level, like pod-wide ignore?

**Comment by SuperTux88** [comment]
> Is there any admin action that can be performed at the People level, like pod-wide ignore?

At the moment: no.

You can change the public key of that person in your database, and that would break federation for that person, but that is no clean solution. You will also miss the close-account message (if the podmin of the person closes the account), if you do that.

**Comment by Hypolite** [comment]
Then in that case it just is the problem a button that exists but doesn't lead anywhere. I may submit a PR for that.
