### ISSUE TITLE
Implement title bar notifications for JSXC chat messages

### ISSUE THREAD

**Issue by enbylenore** [diaspora/diaspora#7111]
I'm interested in adding support for putting notifications in the title bar when the user has received JSXC chat messages.

This is especially relevant when the user is on another tab, etc.

I would propose the following design:
- When there are unread JSXC messages, the number of unread chat messages from all chats is totaled
- When the number of unread messages is > 0, the title bar alternates between it's normal contents and: (N) (Comma delineated list of users who have pending chat messages) on a 2-3 second interval. 

For example:

(5) John Doe, Foo Bar, Alan Smithy

(Browsers should automatically truncate this, but we could also truncate ourselves at 64 or 128 characters, etc.)

If people think this is a good idea I will start the work on it myself and begin preparing a pull request. If needed I can create a loomio thread as well.

I'm also open to suggestions regarding verbiage for the title bar!

**Comment by SuperTux88** [comment]
The chat was removed with #8069, this is obsolete now.
