### ISSUE TITLE
Add reports for posts owners

### ISSUE THREAD

**Issue by SansPseudoFix** [diaspora/diaspora#7112]
Users can report comments on other posts, but not on their own posts (only ``delete`` is available).

Tested on diaspora-fr.org and framasphere.org.

**Comment by SuperTux88** [comment]
On your own posts, you can directly moderate comments (delete them if you want so), you don't need to ask your podmin to do it. Why do you need a repport-button then?

**Comment by SansPseudoFix** [comment]
For spam, like recently with marina-something on joindiaspora. I'd should be more specific :)

**Comment by SuperTux88** [comment]
Just delete the spam?

**Comment by SansPseudoFix** [comment]
Well. There was a logical process in my mind when I posted this issue (something like "let's warn podmin about spammer"), but you actually right. Podmins just delete spams, so eh...

Sorry for the noise :)
