### ISSUE TITLE
More User infmation on conversations

### ISSUE THREAD

**Issue by exmatrikulator** [diaspora/diaspora#7117]
I'd like to send a new message, but I can't verify that I have selected the right User.
More information about the User would be helpful.
Also, the possibility to select a User by Diaspora\* ID.

![unbenannt](https://cloud.githubusercontent.com/assets/4461145/18709001/1104571e-7ffe-11e6-92ec-5ee57152a65e.png)

**Comment by Flaburgan** [comment]
@AugierLe42e is working on that, I thought that we already have an issue about it but can't find it at the moment.

**Comment by Flaburgan** [comment]
Follow https://github.com/diaspora/diaspora/pull/7108 and the following PRs to know about it.

**Comment by SuperTux88** [comment]
Closed by #7129
