### ISSUE TITLE
Include first/last name in invitation emails

### ISSUE THREAD

**Issue by kas70** [diaspora/diaspora#7126]
Invitation emails should look like:

> Hello!
> 
> You have been invited to join diaspora\* by Bob Surname (bob99@pod.geraspora.de)!
> (...)

Currently they look like:

> Hello!
> 
> You have been invited to join diaspora\* by bob99@pod.geraspora.de!
> (...)

**Comment by betsythefc** [comment]
By "username" do you mean the users' name, or their username, which in the case above would be "bob99".

**Comment by kas70** [comment]
The name of the user. Take a look at my example :wink:

**Comment by Flaburgan** [comment]
Actually, the name of the user is in the e-mail subject. 

>*name* invited you to diaspora*!

Done there: https://github.com/diaspora/diaspora/blob/develop/app/mailers/notifier.rb#L48

Is that enough or do you still want to replace the first occurrence of the diaspora* id in the e-mail by the name?

(FTR the e-mail looks like that:)

>Hello!
> 
> You have been invited to join diaspora* by podmin@diaspora-fr.org!
> 
> Click this link to get started
> 
> https://diaspora-fr.org/i/the-code
> 
> Or you can add podmin@diaspora-fr.org to your contacts if you already have an account.
> 
> Love,
> 
> The diaspora* email robot!
> 
> P.S.: Just in case you don't know (yet) what diaspora* is, here is the answer!

**Comment by Flaburgan** [comment]
Btw this is only available for the podmin, everywhere else we only provide the invitation link to the user now.

**Comment by Flaburgan** [comment]
I opened a PR nevertheless. It adds the name before the first diaspora ID. Please see https://github.com/diaspora/diaspora/pull/7484
