### ISSUE TITLE
Export and import contact list

### ISSUE THREAD

**Issue by dcapeletti** [diaspora/diaspora#7135]
Hello,
a feature that can facilitate the migration of pods, may be to export the list of contacts to import it into the new pod.
Thank you

**Comment by AugierLe42e** [comment]
Duplicate of #908.

**Comment by dcapeletti** [comment]
I just want to export the contact list in a file. Then in the new pod, you can import contacts and tell them all via a message (if you wish).
A migration wizard is to migrate other issues, is to migrate an entire account, files and all imagine, so do not apply.

**Comment by denschub** [comment]
It, in fact, is a duplicate and if you'd have read the entire discussion, you'd agree. ;)
