### ISSUE TITLE
Private Message gets deleted if you click 'send' and didn't enter a recipient

### ISSUE THREAD

**Issue by TheRadialActive** [diaspora/diaspora#7136]
If I click on the 'message' button on a diaspora profile of one of my contacts, there is no recipient entered automaticly on the appearing private message form. And there is no auto-search for contacts, like on the 'private message'-page.

If I write some text in "message" and "subject", but don't enter a recipient and click on 'send', the whole message + subject gets deleted.

[Maybe we could fix that, by linking the "private message"-button to the private message page and enter the profile owner as a recipient automaticly, so then we have to support only one private message editor/publisher.]

**Comment by svbergerem** [comment]
Might be a regression of #7108.
