### ISSUE TITLE
Topics that need to know to edit Diaspora project

### ISSUE THREAD

**Issue by strivemag** [diaspora/diaspora#7146]
What topics I need to know(RoR) or what skills i need to know to edit Diaspora?
I want use this open-source project to create social network, that have more functionality.
@jhass Please, answer if you know solution.

**Comment by goobertron** [comment]
Please read https://wiki.diasporafoundation.org/How_we_communicate

GitHub is for solving specific technical issues through code. For general queries, try the mailing list or IRC. Or, even better, ask the question in a public post in Diaspora itself.

**Comment by AugierLe42e** [comment]
There is a short introduction to the involved technologies available [here](https://wiki.diasporafoundation.org/An_introduction_to_the_Diaspora_source).

**Comment by denschub** [comment]
What good said.
