### ISSUE TITLE
Bug: Chat stays online after logout

### ISSUE THREAD

**Issue by ecky-l** [diaspora/diaspora#7157]
I configured prosody as XMPP backend, following the instructions [here](https://wiki.diasporafoundation.org/Integration/Chat). Now I have a separate XMPP server with users in the diaspora database. I can use any XMPP/Jabber client and my diaspora login to chat.

What happens is now: I login to diaspora (on my pod), then "go online" in the chat by clicking in the menu in the lower right corner in the JSXC panel. Afterwards I log out of my diaspora account, then login in the same browser window with a different testuser on the same pod - and the chat session is still connected and online with the _first_ (my) login. This is obviously not what I'd expect. 

Only when I "go offline" via the lower right menu and then log out, the browser chat session is closed. Or by closing the browser window.

**Comment by SuperTux88** [comment]
The chat was removed with #8069, this is obsolete now.
