### ISSUE TITLE
Tag a non-NSFW post as NSFW

### ISSUE THREAD

**Issue by elacheche** [diaspora/diaspora#7159]
Hey!

So, I just invited a friend to join D*

He published a "#newhere" and I was surprised to see it as a NSFW post..

Here are screenshots of the post before and after I asked D* to show it to me:
- http://i.imgur.com/dGuy1Hf.png
- http://i.imgur.com/gmrXdCu.png

PS: If you need any other proves that this is not a fake case, tell me what I need to do to prove it (I know the screenshots are not a much).

**Comment by SuperTux88** [comment]
He probably marked his whole profile as NSFW, so every post is marked as NSFW, this is normal.

**Comment by elacheche** [comment]
My bad, he wasn't aware of that NSFW checkbox was about.. and I forgot about that option as well.. Sorry..
