### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by Hostile** [diaspora/diaspora#7172]
Hi anyone would be so kind to install it on my Ubuntu 16.04 server pls. 
If someones fluent with it I can give ssh access no probs.

I tried 3 times got to the end of it looks like it starts with some error and worst part is nginx conf for me. 

Whatsapp me +66997843134

**Comment by denschub** [comment]
* GitHub is not a support forum.
* Check the wiki for installation guides. https://wiki.diasporafoundation.org/Installation
* Spamming "hi" seven times in IRC won't get you any help. If you see an error message, link to that. If you have questions, ask them. You're chances for getting a reply to " Who can install pod for me please" are very low, but people usually help if you have actual questions. See https://workaround.org/getting-help-on-irc/
* The community is spread all over the world and might not live in your timezone. Wait a bit before leaving IRC...

Closing as invalid.

**Comment by denschub** [comment]
Also, I have removed your phone number from this issue.
