### ISSUE TITLE
No "Stay or Leave Page" prompt when writing a comment

### ISSUE THREAD

**Issue by theatre-x** [diaspora/diaspora#7173]
Hey folks,

I ran into this by accident.
I noticed that when I comment on a post, I don't get a prompt in Firefox for "Staying or Leaving" the page like I do when I write a post if I click a link or use the Back button.

Does this pertain to anyone else?

**Comment by Flaburgan** [comment]
With https://github.com/diaspora/diaspora/pull/7473 merged, `jquery.are-you-sure` has been included so this should be easier to solve.

**Comment by theatre-x** [comment]
Excellent.

**Comment by svbergerem** [comment]
Fixed by #7530.

**Comment by theatre-x** [comment]
Fantastic! Thanks for the work!
