### ISSUE TITLE
Help with starting diaspora and apache config

### ISSUE THREAD

**Issue by Hostile** [diaspora/diaspora#7177]
Hi followed instructions, but it not start, Im on new ubuntu 16.04 updated server.

Heres Diaspora console log : https://gyazo.com/388dc1649a05cca515b6475ac0f2c190

Apache2 log https://gyazo.com/0e51a49c748c91d2eb12c4316ed91134

Heres apache config http://vodeoo.com/vodeoo.conf   (should displays in chrome)

I looked at https://gist.github.com/jhass/719014

I got all apache mods enabled

**Comment by SuperTux88** [comment]
GitHub is not a support forum. (See #7172)
