### ISSUE TITLE
FixPhotosShareVisibilities failed Mysql2::Error: Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by wiegelmann** [diaspora/diaspora#7178]
While upgrading to diaspora version 0.6.1.0

https://github.com/diaspora/diaspora/blob/master/db/migrate/20160906225138_fix_photos_share_visibilities.rb#L17

> gem "mysql2", "0.4.4"

> ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

> mysql --version
mysql  Ver 14.14 Distrib 5.5.52, for debian-linux-gnu (x86_64) using readline 6.2

> mysql> describe share_visibilities;
+----------------+--------------+------+-----+---------+----------------+
| Field          | Type         | Null | Key | Default | Extra          |
+----------------+--------------+------+-----+---------+----------------+
| id             | int(11)      | NO   | PRI | NULL    | auto_increment |
| shareable_id   | int(11)      | NO   | MUL | NULL    |                |
| hidden         | tinyint(1)   | NO   |     | 0       |                |
| shareable_type | varchar(255) | NO   |     | Post    |                |
| user_id        | int(11)      | NO   | MUL | NULL    |                |
+----------------+--------------+------+-----+---------+----------------+
5 rows in set (0.02 sec)

== 20160906225138 FixPhotosShareVisibilities: migrating =======================
-- execute("DELETE s1 FROM share_visibilities s1, share_visibilities s2 WHERE s1.user_id = s2.user_id AND s1.shareable_id = s2.shareable_id AND s1.shareable_type = s2.shareable_type AND s1.id > s2.id")
   -> 11.6137s
-- remove_index(:share_visibilities, {:name=>:shareable_and_user_id})
   -> 1.7537s
-- add_index(:share_visibilities, [:shareable_id, :shareable_type, :user_id], {:name=>:shareable_and_user_id, :unique=>true})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Specified key was too long; max key length is 767 bytes: CREATE UNIQUE INDEX `shareable_and_user_id`  ON `share_visibilities` (`shareable_id`, `shareable_type`, `user_id`) 
/usr/local/app/diasp/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `_query'
/usr/local/app/diasp/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `block in query'
/usr/local/app/diasp/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `handle_interrupt'
/usr/local/app/diasp/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `query'
/usr/local/app/diasp/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
/usr/local/app/diasp/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/usr/local/app/diasp/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/app/diasp/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/usr/local/app/diasp/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
/usr/local/app/diasp/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
/usr/local/app/diasp/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:541:in `add_index'
/usr/local/app/diasp/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:665:in `block in method_missing'
/usr/local/app/diasp/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/local/app/diasp/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `say_with_time'
/usr/local/app/diasp/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:654:in `method_missing'
/usr/local/app/diasp/db/migrate/20160906225138_fix_photos_share_visibilities.rb:17:in `up'

**Comment by SuperTux88** [comment]
`shareable_type` should be `VARCHAR(60)` see [schema.rb](https://github.com/diaspora/diaspora/blob/develop/db/schema.rb#L538).

I don't know why it isn't `VARCHAR(60)` in your case, because it was `VARCHAR(60)` for a long long time now (I don't even know if it was something else sometime?)

**Comment by wiegelmann** [comment]
Thanks, it works with varchar(60). Reason: failed migration from 2011:

https://github.com/diaspora/diaspora/commit/f7e70f8d936193d4a7416ece314a12fdbc4dde73#diff-8db4472bfa97c37cf958fff686177433

**Comment by SuperTux88** [comment]
Ok, so I close the issue.

By the way: If you have differences (`git diff`) in your schema.rb after `db:migrate` on mysql, you should fix that, so your database has the same state as in the schema.rb in the repo. You can update the schema.rb by running `db:migrate` again. But this works only on mysql and not on postgres (postgres has always a diff and that is normal, because the schema.rb in the repo is generated with mysql).
