### ISSUE TITLE
Insecure cross-site requests are made

### ISSUE THREAD

**Issue by ghost** [diaspora/diaspora#7189]
One example:
Currently previews of youtube videos embedded in the stream happen to use for example http://i.ytimg.com/vi/EWdz8_uQhHE/hqdefault.jpg instead of https://i.ytimg.com/vi/EWdz8_uQhHE/hqdefault.jpg

This should not happen at all, the software should default to TLS.

Reproducible: using the current icecat in Guix (firefox 45.3.0 based).

**Comment by ng-0** [comment]
Actually this was the wrong example.
http://i1.ytimg.com/vi/hpPYKJAnwUo/hqdefault.jpg  is what I meant to include.

**Comment by denschub** [comment]
This is not our decision, the youtube embedding widgets decides what image it shares with us. Also probably related to #6377.
