### ISSUE TITLE
Make the CSRF message less disturbing and indicate actions for the users

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#7193]
Since https://github.com/diaspora/diaspora/pull/7050 is merged we have a lot of support by people don't understanding what's going on and what they should do. The translations aren't been pushed on webtranslateit so the users even receive this e-mail in english.

We need to make the content more clear about what happened (what could have possibly caused that) and that they can now log in again safely (we even had someone wanting to delete her account, misinterpreting the e-mail).

**Comment by Flaburgan** [comment]
Can someone please explain here what can cause this? (A special add-on, a connection from two devices in the same network maybe?) We need to be able to reassure the users waiting for this issue to be solved.

**Comment by SuperTux88** [comment]
You already mentioned some reasons:
* An add-on manipulating the request or making requests without the token.
* An old open tab from the past.
* Another website making requests (that is what CSRF is).
* Some other external tools (trying to use the non-existing API without the token).

But two devices in the same network is no problem.

**Comment by denschub** [comment]
This is quite easy to simulate: open two tabs, wait a day, then come back to your browser. If you reload the first tab, nothing really happens. You've sent an old CSRF token, but the session is valid otherwise, so you just receive a new token and an updated session and you'll be fine. However, if you reload the second tab, you'll make that request using an old, now expired CSRF token and an old session. This could, in theory, be an attack caused by session stealing and diaspora kills the old session, logging you out and sending an email.

**Comment by SansPseudoFix** [comment]
What about:

> Hello %{name},
>        
> A unsure way to use your account has been detected by diaspora*. To prevent any damage, you have been disconnected. You can safely reconnect right now.
> 
> We detected a request made with a wrong/missing CSRF token, this can be caused by:
> 
> * An add-on manipulating the request or making requests without the token
> * An old open tab from the past
> * Another website making requests
> * Some other external tools
> 
> If you're seeing this message multiple times, please check that your browsing settings are right. 
> 
> For more information on CSRF see [%{link}](%{link}).
> Sorry,
> The diaspora* email robot!

?

**Comment by Flaburgan** [comment]
Adding the 0.6.2.0 milestone to this as we definitely have a lot of support because of it.
I reviewed the text with @SansPseudoFix before he wrote the comment so it's fine to me. What do other contributors think? @goobertron is the english okay?

**Comment by goobertron** [comment]
@Flaburgan, thanks for alerting me. I'd recommend a few alterations, both to polish the English\* and to (I hope) make the explanation even more clear:

> 
>
>    Hello %{name},
>
>    diaspora* has detected an attempt to access your account which might be unauthorised. This might be completely innocent, but it could be a cross-site request forgery (CSRF). To avoid any chance of your data being compromised, you have been signed out.
>
>    A request made using a incorrect or missing CSRF token can be caused by:
>
>    - An add-on manipulating the request or making requests without the token;
>    - A tab left open from a past session;
>    - Another website making requests, with or without your permission;
>    - Various other external tools;
>    - Malicious code trying to access your data.
>
>    For more information on CSRF see %{link}.
>    
>    Don’t worry; you can safely sign in again now.
> 
>    If you see this message regularly, please check your browsing settings.
>
>    Thank you,
>    The diaspora* email robot!

I hope I've understood the circumstances correctly. If there is anything incorrect or less than clear in this text, please let me know.

It might be worth adding an explanation to the final sentence of what browser settings are likely to cause this message to be generated, and what changes the user can make to fix this.

\* I mean, of course, to make the English more polished, not make it more like the Polish language!

**Comment by SansPseudoFix** [comment]
Nice! We tried to make it the less alarming we could, but you do it much better 👍

**Comment by goobertron** [comment]
Maybe you could do a more alarming one for Hallowe'en!

**Comment by Flaburgan** [comment]
Thank you goob! I'm just not to sure about the "access your account", which could make the user believe that someone tried to log in which his username where it's not the case here. Also as most of person only read the few first lines of e-mails, I'd like `Don’t worry; you can safely sign in again now.` to remain as close to the top as possible. Apart from that, nice improvements, thank you again!

**Comment by goobertron** [comment]
Sure, change anything you want to. How about, at the beginning:

> diaspora* has detected a browser request using your account credentials which might be unauthorised. To avoid any chance of your data being compromised, you have been signed out. Don’t worry; you can safely sign in again now.
>
> This request might be completely innocent, but it could be a cross-site request forgery (CSRF).

Not sure about the technical details myself so please amend anything which isn't right, and don't be afraid to ask for another polish from me once it's finished.
cheers, goob

**Comment by SuperTux88** [comment]
@goobertron I like your first text. 👍 

> It might be worth adding an explanation to the final sentence of what browser settings are likely to cause this message to be generated, and what changes the user can make to fix this.

I think it is most times about browser add-ons instead of settings (or it can be anything of the above points), but I don't know how to write that so that people understand it. Maybe just something like "check the points above"?

> ... using your account  credentials ...

This is wrong, because it sounds like somebody knows your password and you need to change it. It is more like "using your session cookie" (which we destroy with the logout). But I don't know if that helps somebody to understand it better.

**Comment by goobertron** [comment]
Thanks for your feedback. I was going to suggest:

> diaspora* has detected a browser request which appears to be from you but which might be unauthorised.

but thought I'd try to be more detailed and therefore clear. Is that version better?

For the final sentence, let's try:

> If you see this message repeatedly, please check check the points above, including any browser add-ons.

Hope that's better, and thanks.

**Comment by SuperTux88** [comment]
> Is that version better?

I'm unsure about that. I personally like the first version the best ("diaspora* has detected an attempt to access your account which might be unauthorised."). Because it is generic and I think the least confusing one, for people who don't understand what happened. And for everybody who wants more details, they either already know the term "CSRF" or the can read about it. But you can't summarize "CSRF" in one sentence with more details without confusing people.

> ... please check check the points above ...

So they need to double check it? ;)

> Hope that's better

Yes 👍

**Comment by goobertron** [comment]
Fine, thanks. I'll let you and @Flaburgan fight it out over 'access your account', then!

**Comment by SuperTux88** [comment]
Maybe "access your account using your session" or "access your session"?

**Comment by SansPseudoFix** [comment]
"diaspora* has detected an attempt to access your session which might be unauthorised." is less alarming imho.

* account: "my data omg!"
* session: "meh? Ok."

**Comment by SuperTux88** [comment]
Fixed by  #7238
