### ISSUE TITLE
Save new email address without confirmation when mail is disabled in config

### ISSUE THREAD

**Issue by svbergerem** [diaspora/diaspora#7195]
When a user changes their email address on the settings page we will send a confirmation mail and save the new email address after it has been confirmed. If the podmin didn't enable `mail` in the pod's config we won't send a confirmation mail. Thus we should save the new email address without any confirmation.

**Comment by zenara** [comment]
This is solved right? I have tested this and works fine. I didn't get any confirmation mails for changing my email address.
