### ISSUE TITLE
Incorrect message when attempt to reshare with connection down

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#7200]
If I attempt to reshare a post when my internet connection is down, I get the flash alert 'That good, eh?  You've already reshared that post!'

Steps to reproduce: 1) switch off internet connection; 2) try to reshare a post!

I think the above message should be displayed *only* if the pod's server replies that the signed-in user has already reshared that post, if it's possible to test that. If the browser can't get a response from the server, a general alert 'Unable to connect to the pod at this moment' would be more appropriate (for all cases; not just a failed reshare attempt); or if, it's not possible to determine that as the cause of the error, a more general alert such as 'Unable to reshare this post at this moment'.

**Comment by SuperTux88** [comment]
Closed by #7202
