### ISSUE TITLE
photo download in profile section includes old photos

### ISSUE THREAD

**Issue by Spamiad** [diaspora/diaspora#7212]
previously deleted photos should have been deleted from the server?

The pod is diasp.org

**Comment by svbergerem** [comment]
Did you start exporting your photos before deleting them? When you export your photos they are packed in a zip file and that doesn't change as long as you don't click “Refresh my photos”. When you click “Download my photos” you are just downloading the already existing zip file.

**Comment by Spamiad** [comment]
Yes, I did "Refresh my photos" and waited one hour just to be sure.

**Comment by denschub** [comment]
Please contact @dmorley for questions regarding diasp.org. Deleting photos works fine in our default codebase, so this is a setup issue.
