### ISSUE TITLE
human-friendly URL's instead of alphanumericals when sharing profile. 

### ISSUE THREAD

**Issue by shirishag75** [diaspora/diaspora#7231]
If I try to share my diasp.eu profile I need to share https://diasp.eu/people/91dace909e8001325ab95404a6b20780 instead of sharing https://diasp.eu/people/shirish.agarwal or something similar in case the first choice is taken up by somebody else. Currently I am unable to find this feature anywhere.

**Comment by SuperTux88** [comment]
You can share https://diasp.eu/u/shirishag75

**Comment by shirishag75** [comment]
@SuperTux88 this isn't easily known, I tried and that URL works, is there a way to make it automated so that I don't have to remember it. By automating I mean, letting me at all times use that as a link, similar to what facebook or/and twitter does. User-friendly URL's.

**Comment by SuperTux88** [comment]
We linked to this url somewhere in the interface, but I don't know if this is still the case. But it isn't hard to remember, it is `<podurl>/u/<username>`. You can use this link all the time, it works since years and it isn't planned to remove it.

**Comment by goobertron** [comment]
The /u/username URL has been there from the early days, but it is not transferrable across pods. If you provide https://diasp.eu/u/shirishag75 to someone, they can only view your profile in your pod, even if they are signed up to a different pod. That means that they can't share with you.

If you provide https://diasp.eu/people/91dace909e8001325ab95404a6b20780, they can take /people/91dace909e8001325ab95404a6b20780 and append it to their own pod's domain, and can then view your profile in their own account and share with you, mention you, etc.

The reason for using a guid (long string of random hex numbers) is that the same user name might well be taken by different people on different pods, whereas this random string is unique to your account throughout Diaspora. It doesn't look so personal, but it works. The /u/username URL is not useful for anything other than passive viewing of your profile page.

**Comment by DeusFigendi** [comment]
@goobertron well withing diaspora it's easier to share the whole handle `hirishag75@diasp.eu` or a valid mention `@{shirish agarwal ; hirishag75@diasp.eu}` so people can copy it to the search or just click it, that's way more comfortable but splitting and re-assembling the URL.

So I guess this issue is more about sharing it outside Diaspora.

**Comment by shirishag75** [comment]
at bottom :-

On 08/12/2016, DeusFigendi <notifications@github.com> wrote:
> @goobertron well withing diaspora it's easier to share the whole handle
> `hirishag75@diasp.eu` or a valid mention `@{shirish agarwal ;
> hirishag75@diasp.eu}` so people can copy it to the search or just click it,
> that's way more comfortable but splitting and re-assembling the URL.
>
> So I guess this issue is more about sharing it outside Diaspora.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/diaspora/diaspora/issues/7231#issuecomment-265536816

This is/was more about sharing in different pods and being able to
converse with members/users of different pods. As of date, there
doesn't seem to be a sane way to do conversations with people of
different pods within diaspora itself.

Even diasp.eu/u/shirishag75 was not known to me unless people told me
about it. This bit should be entirely self-discoverable which it isn't
atm.

-- 
          Regards,
          Shirish Agarwal  शिरीष अग्रवाल
  My quotes in this email licensed under CC 3.0
http://creativecommons.org/licenses/by-nc/3.0/
http://flossexperiences.wordpress.com
EB80 462B 08E1 A0DE A73A  2C2F 9F3D C7A4 E1C4 D2D8

**Comment by basxto** [comment]
@shirishag75 The sane way is to put “shirishag75@diasp.eu” into the search bar, visit your profile and add you. This handle is mentioned on top of every profile within diaspora, therefore easy to find out. This only fails when the searching pod doesn’t know your pod yet, it will then contact your pod and it will work on the next try (afaik).

If that’s not sane, then neither is e-mail.

Having a link for non-diasporians would be handy, though. Showing your own profile always as https://diasp.eu/u/shirishag75 could make sense. Most users most likely won’t be aware, that they ‘just’ have to modify the pod url when they get a link with a guid.

**Comment by SuperTux88** [comment]
> This only fails when the searching pod doesn’t know your pod yet, it will then contact your pod and it will work on the next try (afaik).

No, it doesn't fail, it just takes longer (or fail if the pod of the searched person is down or too slow to respond, but normally it doesn't fail)

**Comment by denschub** [comment]
I'm closing this, mainly for the points Good has pointed out in https://github.com/diaspora/diaspora/issues/7231#issuecomment-263873459.
