### ISSUE TITLE
Onboarding - finding new friends

### ISSUE THREAD

**Issue by bkarst** [diaspora/diaspora#7239]
Mark Zuckerberg said the most crucial thing to growth was finding friends that had already joined facebook or inviting friends to join. This feature should be implemented to grow this open source platform too.

**Comment by SuperTux88** [comment]
You can find friends by searching their diaspora-ID. Or find new friends by #hashtags. So this feature is already there.

**Comment by bkarst** [comment]
But you can't find friends that have already joined?

**Comment by SuperTux88** [comment]
Just search for their diaspora-ID and you will find them. (If they used their realname and your pod already knows them, you can also search the name.)

**Comment by bkarst** [comment]
How would anybody know their friend's dispora-id?

**Comment by SuperTux88** [comment]
Don't you talk to your friends? Just ask. (The same way you know somebody's telephone number, email address or XMPP-handle)

**Comment by bkarst** [comment]
None of my friends, real or imaginary, have heard of Diaspora. Is there a feature to invite them using my contacts or fb friends list?

**Comment by SuperTux88** [comment]
Yes, you can send them an invite link.

**Comment by denschub** [comment]
**Stop**. This is not a support chat. Please [hop to IRC](https://wiki.diasporafoundation.org/How_we_communicate#Channels) if you need support or have questions. GitHub is for tracking code issues only.

**Comment by bkarst** [comment]
Maybe you're spending a bit too much energy thinking about **how** to implement things than **what** you are implementing. 

When someone suggests "Why don't you just lookup their dispora-id?", doesn't that give you a red flag that you might have a bit of an issue? To your left brain, that may be perfectly sensible, but people don't care. People want something **easy as fuck**. I want this to be successful (that's why I brought up the issue) but if it's not easy as fuck nobody will be bothered. I'm telling you from experience and cause I care.

**Comment by SuperTux88** [comment]
And what is too hard with clicking an invite link? That's as easy as we can make it, people still need to talk to each other. If that's too hard, then they probably should stay on facebook.

**Comment by SuperTux88** [comment]
And if the person already has a diaspora* account, then you also need to talk to each other and ask for the ID (or give them yours), that's nothing we can replace.

**Comment by bkarst** [comment]
How do you feel about a mass invite tool for Gmail Contacts, Yahoo Contacts, and Facebook friends?

**Comment by SuperTux88** [comment]
You can just send an email to all of your contacts with your invite link and diaspora-ID (so people can either register or connect with your diaspora-ID if they already have an account). Mass email is something Gmail already has, so there is no need we add something like this.

**Comment by denschub** [comment]
Okay, apparently I was not clear enough.

This is neither the place to ask questions nor the right place to discuss on how we do things.

Locking this thread.
