### ISSUE TITLE
'Comment' and 'Like' in "My activity"

### ISSUE THREAD

**Issue by patdum** [diaspora/diaspora#7257]
Feature request ! 

When an user subscribes to watch my activity using "add contact" feature, he will read in his stream all my posts I will create or share.

But, he will not read all post I "like" or I "comment", although **this is an integral part of my activity**.
(like on facebook website, look at this screenshot http://blog.shareaholic.com/wp-content/uploads/2012/05/Facebook-2010.jpeg  "commented on" caption ).

I would like, each time I like or comment a post, my contact can read in his stream : 
"nickname" has liked this post 
"nickname" write this "comment content" about this post.

Thanks and sorry for my poor english ...

**Comment by SuperTux88** [comment]
Please no ... if you really think that your contacts need to read a post, then you can reshare it, but I don't want my stream full with likes and comments of other people.

**Comment by denschub** [comment]
This sounds... controversial. Let's discuss on loomio if you feel strong.

**Comment by patdum** [comment]
I agree that it is not obliged to do the same facebook, but in my opinion a "like" or "comment" is an activity, as well as a "post" or a "re-share". A "Like" is actually listed in "my activity", so, logically, it should also be listed in what appears in the stream that follows my contact. Otherwise it would not make sense, because thecontact asked to follow my activity. Everywhere or nowhere. Same argument for a comment action. ( ~denschub : I am new user and don't know how to do with loomio )

**Comment by Flaburgan** [comment]
hi @patdum and welcome. Even if this suggestion looks simple, it's not as easy as "display the user's actions (XXX has commented XXX post) on his profile". On diaspora*, we give the control to the user. So, who is going to be able to access those indications? Maybe some of them can be public. Some have to be very restricted. Maybe I don't want most of them to be visible at all. That means, many settings, a dedicated interface, and suddenly a way more difficult feature to develop.

[Loomio](https://www.loomio.org/g/EseV9p4X/diaspora-community) is the tool we use to discuss, imagine and vote features. If you feel attached enough to this feature, you can open a discussion thread there. Try to solve those questions first though ;)

**Comment by SuperTux88** [comment]
diaspora is not Facebook. If I add somebody to my contacts, I'm interested in his posts, but not what he likes or comments (I didn't ask to follow his activity). If the person likes something so much, that he thinks it is important for his contacts, there is a reshare-feature. Likes and comments are between the post-author and the like/comment-author and not between other contacts.

The "My activity" is a stream where you find posts where you were active, that is a stream for you, not your contacts.

**Comment by patdum** [comment]
I understand your position. Best regards.
