### ISSUE TITLE
Other files(images not included) can't upload

### ISSUE THREAD

**Issue by desaiyatin** [diaspora/diaspora#7260]

**Comment by Flaburgan** [comment]
diaspora* is not a system to share files between users. We only support images attachment. So is this a feature request or are you talking about something else?

**Comment by desaiyatin** [comment]
okkkk
then how can i add this new feature in my project...?????
have you any idea about that?

**Comment by denschub** [comment]
We have issues for video and document uploads, so this is a duplicate. We don't support anything else, so GitHub is the wrong place. You can try asking in IRC to see if anyone has hints for you.

**Comment by desaiyatin** [comment]
okay,,, thanks for your time.
