### ISSUE TITLE
Camo mime-types update

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#7261]
Not sure where I should have open this issue as Camo is an external tool, feel free to move if there is a better place.

I moved d-fr to a new server recently and reinstalled Camo. [The wiki](https://wiki.diasporafoundation.org/Installation/Camo#Mime_types) currently recommends to add 3 lines to `mime-types.json`, `"application/octet-stream"`, `"binary/octet-stream"`, and an empty one: `""`, to avoid trouble with S3 and CloudFare. @Zauberstuhl moved joindiaspora.com from S3 months ago, so I decided to check what was really needed. When I try to display [a jd user profile](https://diaspora-fr.org/people/4cf059aa2c174350c60006a9) with the default `mime-types` file, I do have the default diaspora* avatar instead of the good one. `"application/octet-stream"` and `"binary/octet-stream"` don't change anything to that, but the empyt `""` fixes the problem. I feel weird about this fix: accepting anything doesn't seem safe to me, and especially I don't get why I still need that fix now that jd is not on amazon hosting anymore. @Zauberstuhl @denschub any explanations?

**Comment by SuperTux88** [comment]
I also tried to remove these 3 lines some time ago, but JD still delivers images with wrong Content-Types from S3 (Some images have `"application/octet-stream"` and some have `""`, I didn't find any with `"binary/octet-stream"`). I hope @Zauberstuhl can fix this sometime and we can remove this hack.

**Comment by denschub** [comment]
> moved joindiaspora.com from S3 months ago

No. Unless he updates all profiles, the image url is still set to S3 paths.

This is a setting @Zauberstuhl has to do on Amazon S3. We've talked about this before and he said he'll do it eventually. There is neither a diaspora-fix nor a camo-fix for that. Closing.

**Comment by Zauberstuhl** [comment]
yes looks like you cannot update recursive s3 buckets. which means that it will take a while. if someone knows a better way then updating every single file via the api please let me know.

```
MAXCNT=$(wc -l list.txt |cut -d' ' -f1); CNT=1;

while read line;
do
  if [ "$(echo $line |cut -d' ' -f3)" -ne "0" ];
  then
    NAME=$(echo $line |cut -d' ' -f4);
    echo "set $NAME to image/${NAME##*.} ($CNT of $MAXCNT)";
    aws s3api copy-object --bucket joindiaspora \
      --copy-source "joindiaspora/$NAME" \
      --key "joindiaspora/$NAME" \
      --metadata "Content-Type=image/${NAME##*.}" \
      --metadata-directive "REPLACE";
    ((CNT+=1));
  fi;
done < list.txt
```
