### ISSUE TITLE
Remove Vines mention in diaspora.yml.example

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#7262]
https://github.com/diaspora/diaspora/blob/develop/config/diaspora.yml.example#L252

I don't know if it should be replace by "prosody" or if this setting doesn't make sense anymore.

**Comment by SuperTux88** [comment]
It is still used here: https://github.com/diaspora/diaspora/blob/develop/config/initializers/prosody.rb#L7

So I think we should simply replace "vines" with "prosody". But maybe @Zauberstuhl knows more?

**Comment by Zauberstuhl** [comment]
this option is still used here https://github.com/Zauberstuhl/gem_diaspora-prosody-config/blob/master/etc/prosody.cfg.lua.tpl#L88

> we should simply replace "vines" with "prosody"
