### ISSUE TITLE
Display @ before mentions

### ISSUE THREAD

**Issue by SuperTux88** [diaspora/diaspora#7269]
Before mentions in comments were there, I wrote @Person by hand when I answer to multiple persons in one comment, that looks like this (I don't make space between @ and the name normally, but did it here, because I didn't want to mention Alice and Bob on github ;) ):

> @ Alice: answer to alice
>
> @ Bob: answer to bob

Now with mentions in comments we can use mentions for this, that would look like this:

> [Alice](https://example.org/u/alice): answer to alice
> 
> [Bob](https://example.org/u/bob): answer to bob

But I like the @ before a name in the comment, so I would add it manually which would generate a code like this: `@@{Alice; alice@example.org}` and look like this: @[Alice](https://example.org/u/alice)

And friendica supports diaspora-mentions now, but they display an @ before mentions, so if I add an extra @ before the mention, there would be two @@ on friendica (@@[Alice](https://example.org/u/alice)). They could add a hack do remove one of the double @@, but I don't know if they want to do that. ;)

I actually like the idea to mark a mention with an @ (so you know it is hoverable) and I suggest to also add the @ in the frontend on diaspora, and I also think that it doesn't annoy when it is in the middle of a sentence:

> I did something cool with @[Alice](https://example.org/u/alice) today.

What do you think about this idea?

**Comment by Flaburgan** [comment]
I don't think it's specially needed (the link is already clearly displayed) but it became a convention everywhere so I'm not opposed to it. So up to you ;)

**Comment by annando** [comment]
I prefer having the @ before a name to make clear that it is a mention. This is some quasi standard among all networks, I think. But I think this should be done at the receiver side so that there is no need to add it twice.

BTW: At the Friendica side we can - of course - filter ````@@```` and transform them to ````@````.

Most important for me at the moment is that Diaspora hopefully will display mentions in comments soon.

**Comment by SuperTux88** [comment]
> But I think this should be done at the receiver side so that there is no need to add it twice.

Yes, the @ is only a display thing, so that `@{Alice; alice@example.org}` in the code looks like @[Alice](https://example.org/u/alice) in the frontend. No double @@ needed and no need to filter it on friendica side, because there is no @@ in the text :)

**Comment by goobertron** [comment]
Conversely I don't like the @ before the name, so I'm happy with the UI as it is. It's displayed as a link (in a different shade of blue from a standard link) and this matches the UI in posts, so I think it's best to leave it as it is.

**Comment by SuperTux88** [comment]
I created a PR for the markdown-it plugin (diaspora/markdown-it-diaspora-mention#2), after this is released I can add the same to the diaspora backend.

@goobertron the "different shade of blue" is only minimal, visible when you have both blues side by side. Also it is only in the default theme, not in the colored-themes and not in the dark-theme.

**Comment by goobertron** [comment]
If you're going to implement displaying an @ symbol before mentions, please could you make it an option in user settings?

**Comment by SuperTux88** [comment]
I don't think it's worth to add the complexity of a setting here.
