### ISSUE TITLE
Support command+enter on MacOS to submit post

### ISSUE THREAD

**Issue by pellaeon** [diaspora/diaspora#7273]
Facebook and Twitter allow you to use ctrl+enter (on Macs are command+enter) keys to submit a post. It would be nice if Diaspora has that.

**Comment by SuperTux88** [comment]
That does already work with diaspora.

**Comment by pellaeon** [comment]
Ah, I'm sorry, but may I point out that on MacOS Command+Enter does not work on 0.6.2.0 .

**Comment by SuperTux88** [comment]
I don't have a Mac, so I can't test that, but ctrl+enter works on Linux and Windows, so maybe it is also ctrl+enter on Mac?

**Comment by pellaeon** [comment]
Yes, ctrl+enter works on Mac, but Mac users are more used to command+enter.
Twitter.com : both ctrl+enter and command+enter work
Facebook: only command+enter
Tweetdeck (popular twitter web client): both ctrl+enter and command+enter
work


2017-01-12 22:02 GMT+08:00 Benjamin Neff <notifications@github.com>:

**Comment by denschub** [comment]
We should probably replace all instances of

```js
if(evt.which === Keycodes.ENTER && evt.ctrlKey)
```

with

```js
if(evt.which === Keycodes.ENTER && (evt.metaKey || evt.ctrlKey))
```

(Hint: there are three of those.)

**Comment by goobertron** [comment]
Confirmed on two pods (one running 0.6.1.0-pb88f53a3, the other 0.6.2.0-p020ceaab) using Mac OS 10.7.5.

**Comment by ivantedja** [comment]
seems like @rajanak is not working on this anymore, can I take this? @denschub

**Comment by svbergerem** [comment]
@ivantedja Sure, go ahead. :)

**Comment by ivantedja** [comment]
somehow test for `app.views.Publisher plain publisher publishing a post with keyboard should submit the form when ctrl+enter is pressed` didn't pass when I tried to run jasmine and open `http://localhost:8888/?spec=app.views.Publisher`
so right now it didn't make sense for me to create test for `cmd+enter` if I'm unable to pass `ctrl+enter` test

any idea what's going on? @svbergerem

**Comment by svbergerem** [comment]
Did you run `bin/rake tests:generate_fixtures` as described [here](https://wiki.diasporafoundation.org/Testing_workflow#Jasmine)?

**Comment by ivantedja** [comment]
@svbergerem duh I overlooked that 🙈
thanks!

**Comment by SuperTux88** [comment]
(also, for next time: if you stayed 5 minutes longer on IRC, you would already have this answer. people don't look at it all the time, but when they answer when the asking person already disconnected again ... that's bad ;) )

**Comment by ivantedja** [comment]
@SuperTux88 actually my IRC tab is still opened right now but it seems that it got disconnected without me realizing it (I saw a popup but I accidentally clicked it before seeing what it said, probably it said "disconnected")
