### ISSUE TITLE
Integrated help section is missing a note on ignoring users

### ISSUE THREAD

**Issue by denschub** [diaspora/diaspora#7291]
And we probably should add one as we get a lot of questions about that.

**Comment by Flaburgan** [comment]
@goobertron do you want to try to do that?

**Comment by goobertron** [comment]
I'll be happy to draft some text. I won't, at the moment, be able to make a PR with code, I'm afraid.

**Comment by goobertron** [comment]
Here's a first draft. Please comment and criticise. I know I tend to be wordy. Also, @SuperTux88 recently corrected me on some of the current functioning of the ignore feature (e.g. can no longer comment or like, I think), but I didn't make a note of the exact functioning, so please check the technical accuracy too.

------

[Menu item title:] **Ignoring users**

#### What does ignoring a user mean?
diaspora* wants you to have control of what content appears in your stream. You can do this by, for example, following people and tags. If, however, a particular person regularly posts things you don’t want to see in your stream, you can ignore that person. Perhaps this person’s posts don’t interest you, or you find them offensive, or they post so much material that other posts you want to read are getting drowned out by them. Whatever the reason, you can stop that person’s posts appearing.

#### How do I ignore someone?
To ignore someone, hover over any of their posts and click the ‘ignore’ icon (a circle with a diagonal line through it) that appears in the top right-hand corner of the post. You will no longer see this person’s posts in your stream. They will be removed from your aspects, so they will not be able to read your limited posts.

Ignoring does not act as a total block, however. The person you have ignored will still be able to read your public posts. They won’t be able to comment on or like your public posts, but they can still reshare them. You will also see any comments made by that person on other people’s posts. And if at any time you want to see this person’s public posts, you can do this by visiting their profile page.

#### How do I stop ignoring someone?
If for any reason you decide that you no longer want to stop someone’s posts from appearing in your stream, you can stop ignoring them. There are two ways to do this:

1. Visit that person’s profile page, and click the red ‘Stop ignoring’ button.
2. Click your name at the right of the header bar (or from the drawer in the mobile version) and select ‘Settings’. Then choose ‘Privacy’ from this page’s menu to see a list of all the people you are currently ignoring. Click the red button next to any user’s name in the list to stop ignoring that person.

**Comment by goobertron** [comment]
Not related, but I noticed that the 'Public profile' and 'Private profile' sections in the Help need to be updated, as the private profile (now called 'extended profile') can be made public. Whoever wants to update this (could be in the same PR) let me know and I'll update the text.

**Comment by denschub** [comment]
Fixed by #7572.
