### ISSUE TITLE
Facebook and Twitter sharing does not work

### ISSUE THREAD

**Issue by mneuschaefer** [diaspora/diaspora#7304]
I tried to connect via settings > services, authentification went ok but posts do not appear on twitter or facebook

**Comment by Flaburgan** [comment]
That's probably a misconfiguration by the administrator of your server. Please contact them. Which pod are you using?

**Comment by mneuschaefer** [comment]
joindiaspora.com

**Comment by Flaburgan** [comment]
For how long did you connect the service? Can you please try to disconnect and reconnect them?

**Comment by mneuschaefer** [comment]
I've been connected since half an hour, but a friend who is longer on diaspora also has this problem since today

I disconnected and connected the services, still does not work.

**Comment by Flaburgan** [comment]
So pinging your podmin @Zauberstuhl here, but unless he just did the migration to 0.6.3.0 and there is a regression with the release, I think that it's a setting issue on joindiaspora and then should not be tracked here.

**Comment by Zauberstuhl** [comment]
@mneuschaefer we have some issues currently https://joindiaspora.com/posts/8668294
please contact next time support@zauberstuhl.de. this is not the right place for support questions

@Flaburgan not related to diaspora please close

**Comment by mneuschaefer** [comment]
thanks, please also add the support adress on https://wiki.diasporafoundation.org/How_to_report_a_bug , easier to find that way
