### ISSUE TITLE
#nsfw post showing up when post is directly called by URL

### ISSUE THREAD

**Issue by k0sebamse** [diaspora/diaspora#7306]
Hi,

I made a post today and sent it to my colleagues: https://diaspora.kosebamse.com/posts/377352

One of my colleagues realized the counter at the end and subtracted 1. Unfortunately this is a NSFW post which showed up without any interaction. I don't follow or share with the author of this post. The post was tagged with #nsfw

Because of federation I understand that my pod must pull the post. But it would be better if nsfw-posts called by an URL react like nsfw posts in the timeline: I must actively request that the post is shown.

Cheers
Mirco

**Comment by svbergerem** [comment]
There is a loomio vote against this: https://www.loomio.org/d/MuYgnrbf/nsfw-content-and-the-single-post-view

If this is important for you, then please start a new proposal on loomio.
