### ISSUE TITLE
Diasporafoundation.org internal server error

### ISSUE THREAD

**Issue by anuyts** [diaspora/diaspora#7308]
The website diasporafoundation.org has a language menu. When I pick "Nederlands", I get an internal server error (500). Because the language setting is not stored in the URL, going back without language menu seems impossible, and the menu is gone.

(This is likely not the best place to report bugs about the diaspora foundation website, feel free to move it elsewhere.)

**Comment by Flaburgan** [comment]
Hi anuyts and thank you for your bug report. The website repository is hosted here: https://github.com/diaspora/diaspora-project-site/issues
The Nederland translation is broken at the moment. I will write a message with the HQ account to ask for contributions. Maybe we should even go to each translations and just add the missing variables if it's broken?
For your personal usage, try to go to `/tutorials` for example and you should be able to switch the language to english.

**Comment by anuyts** [comment]
Filed it there: [https://github.com/diaspora/diaspora-project-site/issues/98](url).
