### ISSUE TITLE
Share with people that do not hava a diaspora account

### ISSUE THREAD

**Issue by habruening** [diaspora/diaspora#7320]
I would like to share posts with people that do not have a diaspora account. I know I can public share. But then it is public, which is unacceptable for me.

I could imagine two ways how to implement this:

- Share public but with a password or

- Share with an anonymous password protected guest account that has very limited privileges to see only the list of shared posts and their comments but nothing more and especially not any of the profile or contact information.

I think this feature could even be very good to make diaspora more popular. If my friends can visit me anonymously, they might feel invited to join diaspora, too.

**Comment by cmrd-senya** [comment]
Hello!

Please use [Loomio](loomio.org/g/EseV9p4X/diaspora-community) for feature proposals. GitHub issue tracker is a place for technical discussions. Conception discussions should be raised on Loomio first.

**Comment by SuperTux88** [comment]
> Share with an anonymous password protected guest account

You can just register an account and send username/password to the people ... But I don't see how this should be better than when you just send an invitation to the people and they register their own account.

**Comment by habruening** [comment]
@cmrd-senya OK, I will place this to Loomio.
@SuperTux88 Of course the best would be if my friends register with an own account. But they don't do this. They always ask for news and photos from my family but are not willing to register to diaspora. I think this is a very common problem for users of alternative instant messaging, social media or cloud services.

**Comment by SuperTux88** [comment]
> but are not willing to register to diaspora.

And why should they use a guest account that you register for them?

**Comment by habruening** [comment]
I don't know. This is how humans think. If something is no effort and no cost, they use it. If there is effort/cost/risk/unknown, they do not.

**Comment by habruening** [comment]
But I'll close this issue now. I don't want to busy developers with this discussion. I think there is enough to do. There are enough very good ideas. I'll probably come up with this issue in some years again. For now I can live with regular accounts that I create for my guests.
