### ISSUE TITLE
UI: Giant Receiver fields in New Message popup from a profile site

### ISSUE THREAD

**Issue by paskalito** [diaspora/diaspora#7321]
![new conversation](https://cloud.githubusercontent.com/assets/8012793/22857698/59b6cb00-f0aa-11e6-8efb-1a65863c879e.png)

the receiver fields seem unproportionally big against compared to the rest on the screen.
also the whitespace between lines of new receivers should is to big.

i found out it also applies to the view in /conversations. But in the (very nice by the way) popup from the profileview its more obvious.

**Comment by goobertron** [comment]
How about we collapse that 'receiver' field when unfocused so that it shows just the names in normal-sized type, no avatars, no blue boxes?
