### ISSUE TITLE
Invite link in contacts while invites are closed

### ISSUE THREAD

**Issue by Zauberstuhl** [diaspora/diaspora#7340]
I only did a quick issue search so I hope this is not already known. Forwarded from a JD support ticket:

> I cannot invite people to this pod, which is fine because it is full. However if I go to `https://<your-pod>/contacts`, it still shows me a link "Invite someone to join diaspora*! “, when I click it it offers me a link to send to my friends to invite them to diaspora. However, if they follow this link it fails because the pod is full. This might confuse people or put them off. How about removing this link while the pod does not allow new subscriptions? Or offer an alternative?

**Comment by denschub** [comment]
Hm, yeah, we probably should allow invitees to sign up anyway. Thanks for reporting.
