### ISSUE TITLE
option to ignore *comments* from people on 'ignore' list

### ISSUE THREAD

**Issue by teslasmoustache** [diaspora/diaspora#7341]
Users should have the option, when ignoring a user, to ignore their comments on other users' posts as well. When you want to 'ignore' a user, you should be able to *ignore* a user.

I brought this up on [Loomio](https://www.loomio.org/d/A4NdcmGJ/option-to-ignore-comments-from-people-on-ignore-list) a while back and then I didn't keep up with it. It seems that the few people who participated in the poll agree with the proposal, however.

Thanks

**Comment by svbergerem** [comment]
This is very similar to #5074 where the proposed solution is a nsfw-shield. Closing in favor of the existing issue.
