### ISSUE TITLE
Add contributor tag/icon next to avatar/profile?

### ISSUE THREAD

**Issue by tr37ion** [diaspora/diaspora#7362]
How about rewarding people who successfully contributed to the project (pull request) with a tiny (optional) special icon next to their avatar/profile if they want?

This could attract new people to develop new features. It might go further with icons for people who regularly donate or support the pod somehow.

**Comment by denschub** [comment]
This is technically impossible (we do not control all pods, so setting the flags is literally impossible) and also, we decided to not be a place for easy bounty hunting... :)
