### ISSUE TITLE
I can't add admin

### ISSUE THREAD

**Issue by Andrysky** [diaspora/diaspora#7366]
I'm trying to add an admin but not get (

> diaspora@diaspora:~/diaspora$ bin/bundle exec rails console production
WARNING: You are running Diaspora in production without Sidekiq
         workers turned on.  Please set single_process_mode to false in
         config/diaspora.yml.
Loading production environment (Rails 4.2.8)
2.3.3 :001 > Role.add_admin User.where(username: "<USER>").first.person
NoMethodError: undefined method `person' for nil:NilClass
        from (irb):1
        from /home/diaspora/diaspora/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/console.rb:110:in `start'
        from /home/diaspora/diaspora/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/console.rb:9:in `start'
        from /home/diaspora/diaspora/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /home/diaspora/diaspora/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /home/diaspora/diaspora/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:11:in `require'
        from bin/rails:11:in `<main>'

in config/diaspora.yml admin not set

**Comment by cmrd-senya** [comment]
In the command you use to add the admin you're missing the username. You **must** specify the username of the user you're giving the admin role to. So instead of 
```
Role.add_admin User.where(username: "").first.person
```
you must write
```
Role.add_admin User.where(username: "your_username").first.person
```
Where `"your_username"` matches the username of the user that will be the admin (can be `"admin"` or `"andrysky"` or whatever). This user must be registered in your pod beforehand.

**Comment by Andrysky** [comment]
![_ _031617_092353_am](https://cloud.githubusercontent.com/assets/5894390/23984375/497ae386-0a2a-11e7-9d5f-43cfe1ba5a2d.jpg)
This git lab has eaten "<" user ">"
Of course I enter the user name there, the user is registered.

**Comment by Flaburgan** [comment]
Then check if you didn't do a typo. Also note that username is only the part before the `@`.
