### ISSUE TITLE
Relative time on mobile broken

### ISSUE THREAD

**Issue by denschub** [diaspora/diaspora#7396]
Relative timestamps in the mobile version are broken and only show a date:

<img width="369" alt="screen shot 2017-03-27 at 02 53 56" src="https://cloud.githubusercontent.com/assets/344777/24337119/d3e691ba-1299-11e7-855b-456a7f61ec52.png">

This is on the latest develop, no idea when that regression popped up.

**Comment by SuperTux88** [comment]
Latest `next-minor` is OK, so it is something that is only in `develop`.

**Comment by SuperTux88** [comment]
It's a regression of #7303 (jquery3), b2d0feb00d25e8cbee8905f4d9b0e1b2af36d9c3 is broken, and ca6ce912d390a8beb44e45ffd6d5f34272f5de8f is OK.

@cmrd-senya maybe you can have a look at it?

**Comment by cmrd-senya** [comment]
Sorry, I missed this mention, I'll have a look!

**Comment by svbergerem** [comment]
Fixed by #7419
