### ISSUE TITLE
Add spacing between list items

### ISSUE THREAD

**Issue by Waithamai** [diaspora/diaspora#7400]
Lists with more than a few words per item are difficult to read with no extra spacing between the individual points (both for numbered and unnumbered lists). I'm not sure how much spacing would be necessary (perhaps the same as between paragraphs?)

![screenshot_2017-03-27_19-51-09](https://cloud.githubusercontent.com/assets/3577985/24370204/d96c6244-1326-11e7-9915-bbe5c1a2c273.png)

**Comment by denschub** [comment]
I agree that this looks somewhat suboptimal. However, simply adding the paragraph margin to list points (which is, jftr, a `margin-bottom` of `0.8em`) is not really an option. It would look nice on multi-line points:

<img width="543" alt="screen shot 2017-03-27 at 20 08 03" src="https://cloud.githubusercontent.com/assets/344777/24370965/96e1fb7a-1329-11e7-881d-c074b8fad437.png">

However, single-line items look weird:

<img width="260" alt="screen shot 2017-03-27 at 20 08 09" src="https://cloud.githubusercontent.com/assets/344777/24370968/9eb0665c-1329-11e7-94ac-3d77efe06b01.png">

---

With `0.5em`, the spacing between multi-line items is still noticable:

<img width="560" alt="screen shot 2017-03-27 at 20 08 40" src="https://cloud.githubusercontent.com/assets/344777/24371010/c4a9a288-1329-11e7-807e-ab4ecf7a241b.png">

But single-line points do not look as broken:

<img width="221" alt="screen shot 2017-03-27 at 20 08 46" src="https://cloud.githubusercontent.com/assets/344777/24371015/cbb88f08-1329-11e7-9729-40f4405fd148.png">

---

Let's see what others have to say.

**Comment by SuperTux88** [comment]
`0.5em` looks good to me 👍 (better than without spacing and better than paragraph spacing)

**Comment by denschub** [comment]
Since I added the newcomer tag, here's a hint: `app/assets/stylesheets/markdown-content.scss` is a good file to start!
