### ISSUE TITLE
Support for the IPFS protocol

### ISSUE THREAD

**Issue by MirceaKitsune** [diaspora/diaspora#7416]
I've recently found out about the IPFS protocol and ZeroNet project. I believe this is a system Diaspora absolutely should consider. Therefore I'm opening this issue to discuss the status of IPFS support, and progress on implementing it as a builtin option available for pods.

Brief description: IPFS is a new web protocol aiming to replace HTTP. It uses a mix between torrents and blockchain technology; This allows websites to be seeded by their viewers rather than being hosted on a central server, while at the same time the owner maintains editing access through the use of private keys. This not only increases network speed and efficiency, but makes websites entirely censorship and DDoS resistant... granted they aren't hosted on any central server, and will be available as long as at least one peer remains online. I believe this perfectly fits the goals of Diaspora, which is why I'm suggesting that the standard is adopted.

More info on IPFS:

https://ipfs.io
https://github.com/ipfs/ipfs
https://en.wikipedia.org/wiki/InterPlanetary_File_System

More info on ZeroNet:

https://zeronet.io
https://github.com/HelloZeroNet/ZeroNet
https://en.wikipedia.org/wiki/ZeroNet

**Comment by goobertron** [comment]
My thought as a non-technical person is that Diaspora may not comply with the fully distributed status of something like torrent. In Diaspora, each pod (instance) is held on one server, and therefore if that server is taken down, its data (accounts, images, posts) are lost. Diaspora is a long way from a state in which if that server was taken down, users could enter a private key into another instance and retrieve their data and continue to use the network. If, indeed, that were ever possible or desirable for this project. So IFPS might not be such a useful protocol for Diaspora; I don't know, but just putting some thoughts out there.

**Comment by MirceaKitsune** [comment]
@goobertron It's fair to mention that there already is a social media project based on IPFS support called Akasha. Others would know better how viable it is for Diaspora too, but I felt this is something worth putting up and considering as optional functionality.

**Comment by denschub** [comment]
That was proposed on Loomio before and nobody was even remotely interested: https://discourse.diasporafoundation.org/t/migration-to-ipfs/586. In addition to what @goobertron said, nobody seems to be able to highlight any useful outcomes from a users perspective, so I'm closing this. Also, if anything, this is nothing to discuss on GitHub.  Feel free to continue that discussion on Discourse if you feel really strong.

**Comment by MirceaKitsune** [comment]
To further iterate why I consider IPFS (or cloud) an essential feature for Diaspora and its goals, I would like to bring to everyone's attention a newly proposed law in Germany know as the Social Media Law:

The law proposes that companies such as Facebook and Twitter are fined up to €50, with individual employees facing fines up to €5, for failing or refusing to censor speech deemed illegal by the German state. Any commercial website with more than 2 million users will be forced to police its content, under the pretext of fighting hate speech and fake news, resulting in a perfect system of censorship that can be used to gag any individual expressing inconvenient thoughts. Social media sites are given between 24 hours and 7 days to remove content deemed illegal, based on how obvious the legality of the content is considered.

Because Diaspora uses single pods located in fixed physical locations, pod owners refusing to censor content and not interfering with the free speech of their users may face colossal fines! For this and other reasons, many of which have been explained by the founders of the IPFS protocol, I ask Diaspora to please consider a system for distributed hosting of content in order to prevent reliance on single servers that represent points of failure.

**Comment by denschub** [comment]
> Any commercial website with more than 2 million users will be forced to police its content

No diaspora* pod has 2 million users and if there was a pod this big, we probably would totally have failed our goals of decentralization, so... 

And please read the last sentence of my previous reply.

**Comment by MirceaKitsune** [comment]
No one says it's impossible for a Diaspora pod to ever reach that many users, just like no one says they might not modify the law and take that number even lower. And I'm sorry for missing that sentence... indeed a forum would be a better place.
