### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by tursiops33** [diaspora/diaspora#7418]
Hi,
Does diaspora already support HTTP/2
If not is that something that is planned?

Thank you.

**Comment by jhass** [comment]
Hello, HTTP/2 is nothing diaspora would implement itself directly, rather as with most Rails apps you're supposed to put a reverse proxy in front of its application server. The HTTP/2 support would happen there and thus becomes a deployment question.

Please check https://discourse.diasporafoundation.org for any support or general questions, thank you!
