### ISSUE TITLE
Add podmin account name to the statistics collected

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#7421]
If someone has set the `configuration.admins.account` setting in `config/diaspora.yml`, it would be useful to include this in the statistics output. This wouldn't result in any privacy leak that I'm aware of, because it would be opt-in (only if a podmin has enabled stats collection and if they have set a podmin account), and it would only give away the account name of the nominated podmin account (such as podmin@pod.example.com) rather than an email address or anything like that.

What think you?

**Comment by denschub** [comment]
> What think you?

Not why yeah!
