### ISSUE TITLE
Untranslatable "file input" hovering translatable "Upload photos" (shared.publisher.upload_photos)

### ISSUE THREAD

**Issue by pskosinski** [diaspora/diaspora#7427]
When you mouse over camera icon in the bottom-right corner of the post composing box you can see "file input" hover text (untranslatable) instead of expected "Upload photos" (or proper translation).

The source code the end-user gets looks more or less like that:

````html
<div class="btn btn-link file-upload" id="file-upload" title="Upload photos">
  <i class="entypo-camera publisher_image"></i>
  <input title="file input" multiple="" name="qqfile" type="file">
</div>
````

**Comment by svbergerem** [comment]
The title is set in the [FineUploader](https://github.com/FineUploader/fine-uploader/blob/24ed927e890331b6c4cbe39e926be2ae81ad30e3/client/js/uploader.basic.js#L133) and the text can be overridden via options that we set [here](https://github.com/diaspora/diaspora/blob/45c623c262cebc3c1b5ae245123c9833ab4a3291/app/assets/javascripts/app/views/publisher/uploader_view.js#L13-L45).
