### ISSUE TITLE
default aspect for chat.

### ISSUE THREAD

**Issue by norayr** [diaspora/diaspora#7444]
i suggest to discuss if it's reasonable to add a new default aspect with the name which somehow refers to chat. by default ability to chat with people who have been added to that group should be turned on.

why? as far as i understand it is not intuitively understandable that you cannot see anyone in chat because you haven't enabled that option for the aspect because you does not know that option exists.

**Comment by SuperTux88** [comment]
The chat was removed with #8069, this is obsolete now.
