### ISSUE TITLE
Broken streams if messages contain @mention

### ISSUE THREAD

**Issue by ita1024** [diaspora/diaspora#7454]
Users reported that their streams were incomplete and that messages were lost. After inspection, it appeared that the history would jump back directly to a few years back after the first few messages. We discovered that the key was a message containing "@" mentions of the target users.

Missing messages were also discovered in "view all messages from the user that mentioned me a long while ago". After deleting the messages with mentions, the streams are displayed again as expected.

A dumping of the SQL queries revealed that the messages are initially selected properly:

```sql
(SELECT DISTINCT posts.id, posts.updated_at AS updated_at, posts.created_at AS created_at FROM "posts" LEFT OUTER JOIN share_visibilities ON share_visibilities.shareable_id = posts.id AND share_visibilities.shareable_type = 'Post' WHERE "posts"."author_id" IN (SELECT people.id FROM "people" INNER JOIN "contacts" ON "contacts"."person_id" = "people"."id" INNER JOIN "aspect_memberships" ON "aspect_memberships"."contact_id" = "contacts"."id" WHERE "aspect_memberships"."aspect_id" IN (5, 6, 8, 7)) AND ("share_visibilities"."user_id" = 2 AND "share_visibilities"."shareable_type" = 'Post' AND "share_visibilities"."hidden" = 'f' OR "posts"."public" = 't') AND "posts"."type" IN ('StatusMessage', 'Reshare') AND ("posts"."created_at" < '2017-05-15 20:03:48.000000')  ORDER BY posts.created_at DESC LIMIT 15) UNION ALL (SELECT DISTINCT posts.id, posts.updated_at AS updated_at, posts.created_at AS created_at FROM "posts" WHERE "posts"."author_id" = 3 AND "posts"."type" IN ('StatusMessage', 'Reshare') AND ("posts"."created_at" < '2017-05-15 20:03:48.000000')  ORDER BY posts.created_at DESC LIMIT 15) ORDER BY created_at DESC LIMIT 15;
```

Yet a second query returns one very old post:

```sql
SELECT  posts.id FROM "posts" INNER JOIN "mentions" ON "mentions"."post_id" = "posts"."id" WHERE "posts"."type" IN ('StatusMessage') AND "mentions"."person_id" = 3 AND (posts.created_at < '2017-05-15 23:03:48.000000') AND "posts"."type" IN ('StatusMessage', 'Reshare')  ORDER BY posts.created_at DESC, posts.id DESC LIMIT 15;
 id
----
 19
(1 row)
```

After that, the next query uses that old post instead of discarding it:

```sql
SELECT  "posts".* FROM "posts" WHERE "posts"."id" IN (302, 301, 299, 297, 296, 295, 294, 293, 292, 292, 291, 291, 290, 290, 288, 19) AND (posts.created_at < '2017-04-13 14:14:09.000000') AND "posts"."type" IN ('StatusMessage', 'Reshare') AND (posts.id NOT IN ('61'))  ORDER BY posts.created_at DESC, posts.id DESC LIMIT 15
```

Since the last post in the list is used for pagination, the next messages would "jump" to a few years back and give the impression of data loss. It would seem that the lists of messages are merged incorrectly in the business layer.

**Comment by cmrd-senya** [comment]
That seems to be stable diaspora version, since `"mentions"` have `"post_id"` column, which was changed during mentions refactorings. It is useful to check whether this happens on the latest develop, since some things have changed in mentions implementation since then.

**Comment by SuperTux88** [comment]
The last query

```sql
SELECT  "posts".* FROM "posts" WHERE "posts"."id" IN (302, 301, 299, 297, 296, 295, 294, 293, 292, 292, 291, 291, 290, 290, 288, 19) AND (posts.created_at < '2017-04-13 14:14:09.000000') AND "posts"."type" IN ('StatusMessage', 'Reshare') AND (posts.id NOT IN ('61'))  ORDER BY posts.created_at DESC, posts.id DESC LIMIT 15
```

contains 16 post-IDs, and should return only 15 posts, so `302, 301, 299, 297, 296, 295, 294, 293, 292, 292, 291, 291, 290, 290, 288`, but `19` shouldn't be in the result. Can you check why `19` is still included in the result?

**Comment by ita1024** [comment]
This was found in both 0.6.4.1 and reproduced in 0.6.5. The posts have been removed since then so the problem will be difficult to reproduce.

**Comment by ita1024** [comment]
@SuperTux88 Here is another example:

```sql
SELECT  "posts".id FROM "posts" WHERE "posts"."id" IN (302, 301, 299, 297, 296, 295, 294, 293, 292, 292, 291, 291, 290, 290, 288, 18) AND (posts.created_at < '2017-04-13 14:14:09.000000') AND "posts"."type" IN ('StatusMessage', 'Reshare') AND (posts.id NOT IN ('61'))  ORDER BY posts.created_at DESC, posts.id DESC LIMIT 15;
 id  
-----
 302
 301
 299
 297
 296
 295
 294
 293
 292
 291
 290
 288
  18
(13 rows)
```

**Comment by SuperTux88** [comment]
Oh, I just realized that `292` and `292` is twice in the first list, that make the 16 IDs only 15 unique IDs (and that's why the `19` is in the final result) ... so the double 292 is probably the problem here.

**Comment by spixi** [comment]
Changing the `UNION ALL` to a `UNION` should do the trick.

**Comment by SuperTux88** [comment]
This issue maybe is already fixed by #7503 or #7715 (or at least improved).

@ita1024 can you test if this still exists? If it still exists, it would be interesting what the 15 (or probably less) other posts are in the last batch (posts from contacts or posts from followed tags)?

**Comment by ita1024** [comment]
@SuperTux88 I do not have any testcase, and we have stopped using this feature by fear that it would cause problems. If there is no good way to know if it is fixed, how about removing the functionality altogether?

**Comment by SuperTux88** [comment]
I don't know what you mean with "this feature", and which functionality we should remove to fix this. I don't know what exactly is broken (if it's still broken, but I think it should be fixed by one of the linked fixes). And we can't remove the stream functionality, otherwise diaspora would be pretty useless ;)

**Comment by ita1024** [comment]
I could not verify that posts with `@mention` still result in missing posts because I and all the people I know stopped using those. If you believe that the join works now, do not hesitate to close this issue.
