### ISSUE TITLE
diaspora.yml lies about disabling jobs retry

### ISSUE THREAD

**Issue by cmrd-senya** [diaspora/diaspora#7456]
diaspora.yml [says](https://github.com/diaspora/diaspora/blob/develop/config/diaspora.yml.example#L85) that I can disable job retry by setting it to `false`.

However, here is what happens when it is set to `false` and `Send*` workers run:
```
[2017-05-16T16:49:45] INFO  PID-17212 TID-7532760 ActionController::Base: Completed 500 Internal Server Error in 256ms (ActiveRecord: 46.1ms)
[2017-05-16T16:49:45] FATAL PID-17212 TID-7532760 Rails: 
NoMethodError (undefined method `to_i' for false:FalseClass):
  app/workers/send_base.rb:5:in `<class:SendBase>'
  app/workers/send_base.rb:2:in `<module:Workers>'
  app/workers/send_base.rb:1:in `<top (required)>'
  app/workers/send_public.rb:2:in `<module:Workers>'
  app/workers/send_public.rb:1:in `<top (required)>'
  lib/diaspora/federation/dispatcher/public.rb:18:in `deliver_to_remote'
  lib/diaspora/federation/dispatcher.rb:42:in `deliver_to_subscribers'
  lib/diaspora/federation/dispatcher.rb:27:in `dispatch'
  app/workers/deferred_dispatch.rb:14:in `perform'
  lib/diaspora/federation/dispatcher.rb:22:in `defer_dispatch'
  lib/diaspora/federated/generator.rb:15:in `create!'
  app/models/user/social_actions.rb:3:in `comment!'
  app/services/comment_service.rb:8:in `create'
  app/controllers/comments_controller.rb:16:in `create'
  lib/rack/internet_explorer_version.rb:34:in `call'
```

[`retry` in `workers/base.rb`](https://github.com/diaspora/diaspora/blob/develop/app/workers/base.rb#L9) is no better: it uses `AppConfig.environment.sidekiq.retry.get` as value and it seems to return the default value of `"10"` when `sidekiq.retry` is set to `false`.

**Comment by SuperTux88** [comment]
So we should change the text to say `0` to disable it.

**Comment by cmrd-senya** [comment]
Looks like that for SendBase 0 won't work:
https://github.com/diaspora/diaspora/blob/develop/app/workers/send_base.rb#L10

With 0 value it'll raise MaxRetriesReached everytime. Or am I wrong?

**Comment by SuperTux88** [comment]
No, and yes, it raises `MaxRetriesReached` everytime, but only if there is something left to retry when trying to schedule that for retry, because the check is in `schedule_retry`.
