### ISSUE TITLE
massive problems with wordpress <code> and <pre> -plugin-> diaspora

### ISSUE THREAD

**Issue by cares** [diaspora/diaspora#7470]
Hello,

thanks for your hard work and commitment.

Diaspora is a great and cool tool with cool people doing cool content... (mostly)

i can not use `<code>` or `<pre>`

 in my blog posts because they come out ugly as sh**** on diaspora.

check this out:

https://nerdpol.ch/posts/3646070

this is what it is supposed to look like:

http://dwaves.de/2017/05/24/umask/

plugin used:

https://de.wordpress.org/plugins/wp-to-diaspora/

can you resolve this?

best regards

thanks! #ROCKON!

**Comment by goobertron** [comment]
Surely you need to approach the developer of the plugin to correct this?

See https://github.com/DiasPHPora/wp-to-diaspora/

**Comment by SuperTux88** [comment]
Yes, this is a problem with the plugin, not diaspora.
