### ISSUE TITLE
Enable "Mobile Web App Capable"

### ISSUE THREAD

**Issue by alxlg** [diaspora/diaspora#7485]
Chrome/Chromium for Android let you add web pages to home screen and if they are marked as web app the address bar is hidden.

Diaspora should work well as web app in both mobile and desktop versions.

It should be enough to simply add the following in the header:

```
<meta name="mobile-web-app-capable" content="yes">
```

For more info: https://developer.chrome.com/multidevice/android/installtohomescreen

**Comment by oneturkmen** [comment]
Would like to work on this issue. Could you please guide me through (newcomer)?

**Comment by SuperTux88** [comment]
Cool, that's great 👍 

Do you already have a local installation for development? If not, that would something to start, so you can test your changes. You can find the installation guides in the [wiki](https://wiki.diasporafoundation.org/Installation). If you have any problems, feel free to join our IRC channel `#diaspora-dev` on freenode and ask for help.

The header where this should be added is here: https://github.com/diaspora/diaspora/blob/develop/app/views/application/_head.haml
