### ISSUE TITLE
Find user by email, phone number etc

### ISSUE THREAD

**Issue by alxlg** [diaspora/diaspora#7490]
This is an idea to find contacts on Diaspora. Some proprietary services like Facebook, Twitter, Whatsapp and Telegram let users find their contacts' accounts using email and/or phone number. Another federated service, matrix.org, implemented the same feature using some identity servers that basically links an email address or phone number to a Matrix id (`@name:domain.com`). In Matrix implementation when you associate your email or phone number it's hidden to other users, but who already has your email or phone number can find you on Matrix.

I suppose that (I'm not an expert):

* there is no need to store emails and phone numbers on servers, the hash should be enough (for privacy)
* maybe Matrix's identity servers implementation could be used by Diaspora too

I opened the same feature request on [Mastodon](https://github.com/tootsuite/mastodon/issues/4186)

**Comment by SuperTux88** [comment]
I think this will never happen on diaspora. Diaspora only uses the email address for notifications and password recovery, it never leaves the server. So other servers don't know it. And diaspora doesn't even ask for the phone number.

If you already have the email address or the phone number, you can just write the person an email or sms or whatever and ask for the diaspora ID* (or invite them to diaspora if they don't have an account yet).

**Comment by denschub** [comment]
Yeah. Let's close this as WONTFIX. If anything, this should be a discussion on Discourse.

**Comment by alxlg** [comment]
> If you already have the email address or the phone number, you can just write the person an email or sms or whatever and ask for the diaspora ID*

If you apply this to everything we wouldn't have any improvement. Of course you can do that, thanks.

Mine is a suggestion since it's how proprietary services work and Matrix demonstrated that it's possible to do the same with federated services.

Of course this is an improvement. Every optional feature is an improvement, because who don't want it can just ignore it.

I'm against closing issues like this. If you don't like it, just ignore it.

The comments below should be about _how to implement this_ not about one liking it or not or very manual workarounds.

**Comment by Flaburgan** [comment]
>I'm against closing issues like this. If you don't like it, just ignore it.
The comments below should be about how to implement this not about one liking it or not or very manual workarounds.

If you're feeling strong about this and propose a way to implement that which respects user privacy (= with hashes and opt-in not opt-out) then you can open a discussion on https://discourse.diasporafoundation.org. If the feature is widely accepted the issue will be reopened, and you will be able to work on it.
