### ISSUE TITLE
Add a new stream containing only posts by authors from my pod

### ISSUE THREAD

**Issue by 8spinach** [diaspora/diaspora#7493]
pods don't have much of a sense of identity anymore. it'd be pretty grand to have an option in navigation to view specifically the posts of your local pod. i'd like to be able to get to know my neighbors some.

**Comment by Flaburgan** [comment]
I saw that a lot in the mastodon ecosystem (pod dedicated to a specific subject) but didn't observe that trend in diaspora*. Nothing in the software encourage anyone to interact more with the users on the same pod. In my opinion, this could lead to users wanting to be on the same pod, which is bad for decentralization. So I would be tempted to say no to this. Opinions?

**Comment by SuperTux88** [comment]
Agreed, we can always discuss this on discourse and reopen if needed.

**Comment by 8spinach** [comment]
a lot of users already want to be on the same pod because of uptime, features, available themes, admin responsiveness and so on. on other federated platforms, such as mastodon, this hasn't stymied federation – in fact, new instances pop up all the time and have dozens of hundreds of registered users. the problem mastodon had initially of everyone pooling to a single instance resulted from several marketing pushes advertising a single instance, and not from instances having unique identities.

i don't understand why discussion needs to move from this space.
