### ISSUE TITLE
Sudden sign-out by CSRF protection violation on iOS 10

### ISSUE THREAD

**Issue by cmrd-senya** [diaspora/diaspora#7515]
Recently I was asked to research an issue that happens to a user of diaspora. The issue was referenced [here](https://diasporing.ch/posts/ef2c51a046d30135dd930242ac150006) on diaspora.

Visually it looks like a person during diaspora usage just gets log out suddenly and redirected to the login page. The standard CSRF protection violation email is being issued as well.

This issue seem to happen with iOS/Safari users only.

I checked the log files of the pod, and here is what I saw.

Being logged in the user requests `/stream`:
```
[2017-08-03T17:27:17] INFO  PID-31741 TID-16535760 Rails: Started GET "/stream" 
```

During the page load there is a post request to `/user/auth_token` which is made by our jsxc chat integration:
```
[2017-08-03T17:27:17] INFO  PID-31741 TID-16535760 Rails: Started POST "/user/auth_token" 
```

But then, after some hours I see that this `/user/auth_token` request happens again, but without the `/stream` page reload. This leads to CSRF protection fault:
```
[2017-08-04T05:50:31] INFO  PID-31741 TID-16535760 Rails: Started POST "/user/auth_token"
[2017-08-04T05:50:31] INFO  PID-31741 TID-16535760 ActionController::Base: Processing by UsersController#auth_token as JSON
[2017-08-04T05:50:31] WARN  PID-31741 TID-16535760 UsersController: Can't verify CSRF token authenticity
```

Since this happens hours after the page load, then probably the CSRF simply expires.

The only place that I found that makes this request is [in jsxc.js](https://github.com/diaspora/diaspora/blob/develop/app/assets/javascripts/jsxc.js#L15). This should only happen on page load. But here for some reason it seems to run the initialization JS again without the page reload (I can see other page load related AJAX requests in the logs). Is it possible that this is some Apple specific behavior that runs JS initialization again sometimes without page reload (some kind of cache)? 

I actually managed to borrow an iPad from a friend and tried to reproduce it but with no luck. However it was iOS 9 for me, while reported it happeed on iOS 10.

Since the problem persists and I don't have enough data and hardware to debug it, I open this issue in case that someone wants to help with it.

**Comment by tursiops33** [comment]
I have switched from safari on my ipad to Firefox and I haven't had any case of csrf issue since then. It's been now two weeks, so I think it's a representative time. I will keep using Firefox so that this can be definitely be called.

**Comment by cmrd-senya** [comment]
So if it is a Safari bug, then we can make a minimal reproducible test case and report that to the Safari dev team.

**Comment by SuperTux88** [comment]
The chat was removed with #8069, since this issue was related to jsxc.js, I'm closing this.
