### ISSUE TITLE
New publisher not extending in comment when inserting markdown

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#7521]
A small issue regarding #7482, when the publisher is "full" and you continue to tape text, its height increases. However, this does not work when you add content using the markdown buttons (like inserting a link or an image). The height stays the same and a scrollbar appears. If you enter a character with the keyboard then the height extends accordingly. The post publisher works correctly.

I don't think that this is a release blocker but I wanted to report it.

**Comment by SuperTux88** [comment]
> I don't think that this is a release blocker but I wanted to report it.

Yes, it's also no regression, because you can still use the editor the old way without the button and everything works :)

But I'll add it to the milestone so we have it in the list and can try to fix it, because when it already works in the publisher, it's probably something small.
