### ISSUE TITLE
N + 1 queries

### ISSUE THREAD

**Issue by lelelelemon** [diaspora/diaspora#7540]
line 61 in StatusMessage.rb can be changed to self.mentions.includes(:person => :profile).map{ |mention| mention.person } which eager load the profile for person.

**Comment by svbergerem** [comment]
Could you add a link to the line you are talking about? I'm unable to find it. Line 61 in `app/models/status_message.rb` doesn't seem to be the right one:

https://github.com/diaspora/diaspora/blob/0ae9dbf77f9e61dd8d4730e1dc73bc33dfc1b0bb/app/models/status_message.rb#L61

**Comment by denschub** [comment]
User never replied in the other issues, and I see a lot of similar comments in other projects. I have the suspicion that this is a bot, so I'm going to close this as well.

**Comment by lelelelemon** [comment]
Sorry for the late reply to make you feel me like a bot. Really we did get some code to be merged by other developers. I thought I made a pull request a few days ago in this projects. Our purpose is to find some easily mis-used API across different rails applications.
