### ISSUE TITLE
Ignorelist RC 0.7.0.0

### ISSUE THREAD

**Issue by hfroese** [diaspora/diaspora#7541]
> Was mir eben aufgefallen ist, ist das wenn ich jemanden aus der Ignoreliste schmeiße, bekomme ich nur ne weiße Seite angezeigt anstatt das er einfach von der Liste verschwindet. Die URL die da aufgerufen ist hat folgendes Schema:
> 
> https://diaspora.zone/blocks/177

**Comment by svbergerem** [comment]
The text says that one only sees a white page after removing someone from the ignore list. This is a regression introduced by #7514. (changes in the blocks controller)

**Comment by SuperTux88** [comment]
I can't reproduce this, stop ignoring somebody is an ajax JSON request (tested on the profile of the ignored person), that's why I removed the html response, where do we still need it?

**Comment by svbergerem** [comment]
Settings -> Privacy -> Ignored users

**Comment by SuperTux88** [comment]
Oh, didn't remember that. Can we change to the json ajax request there too? Or is it too complicated and we should just bring back the old redirect route?

**Comment by svbergerem** [comment]
We would have to add the JavaScript code for both mobile and desktop pages and we can't reuse the code from the profile page, so I'd say let's bring back the old redirect route for 0.7.0.0.

**Comment by SuperTux88** [comment]
Oh, that's a problem on mobile too? Because the old controller didn't have a `format.mobile`, so I thought it's not possible to ignore/unignore on mobile. But I'll have a look at this later. Thanks.

**Comment by svbergerem** [comment]
Yes, we use the same privacy settings page for desktop and mobile.
