### ISSUE TITLE
When you hover "Upload a new profile photo!" button in basic profile settings you get untranslatable "file input"

### ISSUE THREAD

**Issue by pskosinski** [diaspora/diaspora#7549]
Go to pod/profile/edit, mouse over "Upload a new profile photo!" and you will get "file input". That hover text should be either removed or replaced with a translatable string.

Related, fixed issue: #7427 

Fix for this one should be similar.

Related file: https://github.com/diaspora/diaspora/blob/develop/app/views/photos/_new_profile_photo.haml

Edit. I think simply replacing `title="file input"` with `title=""` should be enough, because the button is already well-described.

**Comment by svbergerem** [comment]
The JavaScript code for the profile photo uploader is in `app/assets/javascripts/helpers/profile_photo_uploader.js`. The fix for the above mentioned issue is #7429.

**Comment by oneturkmen** [comment]
I think this hover occurs at `apps/views/profiles/_edit_private.haml`. There is no ```Title``` in the file you mentioned (`_new_profile_photo.haml`). 

What do you think?

**Comment by pskosinski** [comment]
Ah, yes. Sorry for misinformation. Seems like I thought that it works differently than it actually works.

Modifying mentioned by @svbergerem file: `app/assets/javascripts/helpers/profile_photo_uploader.js` should probably be enough, in a similar fashion to: https://github.com/diaspora/diaspora/pull/7429/files#diff-de13bca30d4296da38f9bc7d95390450R17
`_new_profile_photo.haml` probably won't need editing, sorry.

If I remember correctly the text `file input` is hardcoded in original FineUploader: https://github.com/FineUploader/fine-uploader/blob/24ed927e890331b6c4cbe39e926be2ae81ad30e3/client/js/uploader.basic.js#L133 and it has to be overwritten in `app/assets/javascripts/helpers/profile_photo_uploader.js`.

**Comment by oneturkmen** [comment]
@pskosinski just made a PR. Thank you for helping with source of the problem (override)!

**Comment by svbergerem** [comment]
Fixed by #7551.
