### ISSUE TITLE
where.first could be find_by

### ISSUE THREAD

**Issue by lelelelemon** [diaspora/diaspora#7552]
diaspora/app/models/user/querying.rb:    self.blocks.where(person_id: person.id).first
diaspora/app/models/user/querying.rb:    Contact.where(:user_id => self.id, :person_id => person_id).includes(:person => :profile).first
diaspora/app/models/user/social_actions.rb:    participation = participations.where(target_id: target).first
diaspora/app/models/service.rb:      where( type: service_type, uid: options[:uid] ).first
diaspora/app/models/person.rb:          Person.where(:guid => params[:id]).first
diaspora/app/models/person.rb:    diaspora_id = Person.where(guid: guid).where.not(diaspora_handle: diaspora_handle).pluck(:diaspora_handle).first
diaspora/app/models/post.rb:    reshares.where(:author_id => user.person.id).first
diaspora/app/models/post.rb:    likes.where(:author_id => user.person.id).first
diaspora/app/models/user.rb:        block = self.user_preferences.where(:email_type => key).first
diaspora/app/models/user.rb:    where(conditions).first
diaspora/app/models/user.rb:      return Like.where(:author_id => self.person.id, :target_type => target.class.base_class.to_s, :target_id => target.id).first

since where.first will issue an extra order by primary key which is actually unnecessary

**Comment by denschub** [comment]
I'll close this with the same reason as in https://github.com/diaspora/diaspora/issues/7555#issuecomment-323504344.

**Comment by Flaburgan** [comment]
Is the remark still valid though?

**Comment by denschub** [comment]
I tested a few of their earlier remarks and it didn't make any difference. I'm honestly not willing to spend a lot of time figuring out all of the (what looks like) grep output in this issue, especially since there has been zero interaction at all in any of the issues.

**Comment by lelelelemon** [comment]
Sorry for the late reply. The difference between find_by and where.first is that, where.first will issue the query will unnecessary order by the primary key, which is indeed unnecessary. As a result, find_by is a better API than where.first.

**Comment by 6temes** [comment]
Basically, `where(...).first` will bring all the registers from the Database that meet the `where` condition, will instantiate them in memory, then take the first one, and let the others for the GC to deal with them.

In contrast, `find_by` will only retrieve one register from the DB. The change could make sense from a performance POV.

**Comment by SuperTux88** [comment]
> Basically, `where(...).first` will bring all the registers from the Database that meet the `where` condition, will instantiate them in memory, then take the first one, and let the others for the GC to deal with them.

No, `.first` adds `LIMIT 1` to the query, so it only instantiates the one object that is actually used.

**Comment by denschub** [comment]
That statement actually was true a long time ago, but ActiveRecord and underlying layers gut much, much smarter these days... ;)
