### ISSUE TITLE
Error while Updating diaspora* 0.6 to diaspora* 0.7 (bundle and sigar)

### ISSUE THREAD

**Issue by Oviked** [diaspora/diaspora#7560]
Hi,

I'm having some troubles with diaspora 0.7.0 dependencies, specially with sigar during `bundle` : 

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /data/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/sigar-0.7.3/bindings/ruby
/data/diaspora/.rvm/rubies/ruby-2.4.0/bin/ruby -r ./siteconf20170820-19910-x4pnw.rb extconf.rb
--with-cppflags=\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"-fgnu89-inline\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"
Ruby platform=x86_64-linux
rbsigar_generated.rx needs update
generating rbsigar_generated.rx
../../src/sigar_signal.c -> sigar_signal.c
../../src/sigar_ptql.c -> sigar_ptql.c
../../src/sigar_getline.c -> sigar_getline.c
../../src/sigar_fileinfo.c -> sigar_fileinfo.c
../../src/sigar_cache.c -> sigar_cache.c
../../src/sigar_util.c -> sigar_util.c
../../src/sigar_format.c -> sigar_format.c
../../src/sigar.c -> sigar.c
../../src/os/linux/linux_sigar.c -> linux_sigar.c
creating Makefile

current directory: /data/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/sigar-0.7.3/bindings/ruby
make "DESTDIR=" clean

current directory: /data/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/sigar-0.7.3/bindings/ruby
make "DESTDIR="
compiling linux_sigar.c
gcc: error: \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"-fgnu89-inline\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\": No such file or directory
Makefile:241: recipe for target 'linux_sigar.o' failed
make: *** [linux_sigar.o] Error 1

make failed, exit code 2

Gem files will remain installed in /data/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/sigar-0.7.3 for inspection.
Results logged to /data/diaspora/diaspora/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/sigar-0.7.3/gem_make.out

An error occurred while installing sigar (0.7.3), and Bundler cannot continue.
Make sure that `gem install sigar -v '0.7.3'` succeeds before bundling.

In Gemfile:
  eye was resolved to 0.9.2, which depends on
    sigar
```

**Comment by goobertron** [comment]
Hi there,

Github is for bugs/issues in the code-base itself. For support, try the [Podmin support section of our Discourse instance](https://discourse.diasporafoundation.org/c/support/podmin-support) or pop onto our [IRC channel](https://wiki.diasporafoundation.org/How_we_communicate#IRC).

**Comment by SuperTux88** [comment]
That is or was a bug with bundler, and not diaspora itself. I don't know exactly where it comes from, but you can fix it by deleting `.bundle/config` in the diaspora folder and then running the commands from the installation again:
`bin/bundle config --local build.sigar '--with-cppflags="-fgnu89-inline"'`

And then if you have postgresql:
`RAILS_ENV=production bin/bundle install --jobs $(nproc) --deployment --without test development --with postgresql`

Or if you have MySQL/MariaDB:
`RAILS_ENV=production bin/bundle install --jobs $(nproc) --deployment --without test development --with mysql`

**Comment by SuperTux88** [comment]
OK, only running this should be enough:
`bin/bundle config --local build.sigar '--with-cppflags="-fgnu89-inline"'`

(Don't delete the file before, if you already deleted the file, do what's in the comment above. After that you should be able to finish the upgrade.)

**Comment by SuperTux88** [comment]
I added that to the upgrade guide [in the wiki](https://wiki.diasporafoundation.org/Updating#Updating_diaspora.2A_0.6_to_diaspora.2A_0.7) to prevent that error for future podmins. So I close this issue.
