### ISSUE TITLE
User jaya Cannot sign in after migration to 0.7.0.0

### ISSUE THREAD

**Issue by diasporabrazil** [diaspora/diaspora#7562]
After a smooth migration from 0.6.7.0 to 0.7.0.0  I cannot sign in with login 'jaya' to Diaspora.
I followed the step-by-step carefully, turning off Diaspora and turning back on after finishing the whole process.
My issue is that I cannot sign in with user 'jaya' but I do sign in with some other login like podmin (thanks God!).
After consulting the user by using the Rails Console, there's nothing stored on the database? What happened to this user data?

2.4.0 :003 > u=User.where(username: 'jaya').first
ActiveRecord::SerializationTypeMismatch: can't load `hidden_shareables`: was supposed to be a Hash, but was a ActionController::Parameters. -- <ActionController::Parameters {"Post"=>["12274"]} permitted: >

Here are the logs when trying to sign in:
https://bpaste.net/show/77c98eaf96e0

Hope to get some hints about how to fix the issue above. Thanks.

**Comment by SuperTux88** [comment]
Hmm, something went wrong here, but I think that's something that went wrong in the past, but is now a problem with the new rails version. Can you check directly in the database what's in the `hidden_shareables` column in the `users` table for this user? You can probably fix it by resetting this to `NULL`.

**Comment by diasporabrazil** [comment]
The query result is in the link
https://bpaste.net/show/30e570852ab8

Can you tell me how to do so?

**Comment by SuperTux88** [comment]
Fixed via IRC with `UPDATE users SET hidden_shareables = NULL WHERE username = 'jaya';`
