### ISSUE TITLE
Auto-complete tags

### ISSUE THREAD

**Issue by MathiasRenner** [diaspora/diaspora#7564]
Auto-completion of tags in posts or comments is IMHO a very important feature. 

I couldn't find any evidence that someone is workin on it, even if I doubt that this is true - given that diaspora is kinda stable for so long now. So let's join forces and see if this feature could get into the next (sub)release :-)

**Comment by Flaburgan** [comment]
Duplicate of https://github.com/diaspora/diaspora/issues/6076
