### ISSUE TITLE
AccountDeleter typo on mark_account_deletion_complete?

### ISSUE THREAD

**Issue by Zauberstuhl** [diaspora/diaspora#7567]
Is `&` in https://github.com/diaspora/diaspora/blob/develop/lib/account_deleter.rb#L111 a typo?
I can run the application (ruby 2.2.7) only by removing it or is it a 2.4 thing?

**Comment by svbergerem** [comment]
It's not a typo. The safe navigation operator has been introduced in ruby 2.3:

http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/
https://bugs.ruby-lang.org/issues/11537

diaspora\* v0.7.0.0 dropped ruby 2.1 support and only supports 2.3 and 2.4.
https://github.com/diaspora/diaspora/blob/develop/Changelog.md#supported-ruby-versions
