### ISSUE TITLE
Add explanation of ignore function to in-app help section.

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#7572]
I want to add a section on the ignore function to the help. Unfortunately my diaspora installation is in such a mess I'm unable to test this, so I'd be grateful if someone else could check and correct the code and then make a PR.

I've pushed the changes to my fork in this commit: https://github.com/diaspora/diaspora/commit/850cafc89253c4f04092bf3a7c26354179904260

Note: I also found a few instances of `<b>` coding in lines 943–5, so I have changed those to `<strong>`.

Hope this is useful, and thanks to whomever takes it on.

**Comment by SuperTux88** [comment]
Thanks @goobertron 🍪

I fixed a syntax error and splitted the change with `<strong>` in a separate commit and created a PR here: #7585

**Comment by goobertron** [comment]
Thank you for making this work!
