### ISSUE TITLE
Poll design is broken with long label

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#7573]
Post: https://diaspora-fr.org/posts/d7ac69e0687e013535bc457cf5a075a6
![poll-design](https://user-images.githubusercontent.com/930064/29615125-01132a0c-880d-11e7-91cb-bc58141ad5e6.png)
![poll-design-not-voted](https://user-images.githubusercontent.com/930064/29615126-011c240e-880d-11e7-8c04-762985ec4bdd.png)

**Comment by DeusFigendi** [comment]
Since @SuperTux88 talked hard to me to get my hands on diaspora and this issue seems to be fixed by a single line, I'd like to adopt this.

**Comment by svbergerem** [comment]
@DeusFigendi You can ping us on #diaspora-dev, #diaspora or #diaspora-de if you run into any problems when setting up the development pod or working on the code. :)
