### ISSUE TITLE
Move the notification icons next to the like / comment / reshare icon

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#7582]
The "Enable notification for this post" icon is barely visible (in fact, I just show it to a user who ignored its existence) and hidden in the middle of "bad" action (hide, ignore, report...). He suggests that it can be moved next to the like / comment / reshare icons so it is more visible and more "positive". What do you think?

**Comment by goobertron** [comment]
I think it is best where it is, from a logical point of view at least. The icons top right are actions to do with post/user visibility in your stream, and notifications are a form of visibility.

Like/reshare/comment are all participations in the post itself. Enabling/disabling notifications is not a participation.

In addition, like/reshare/comment are currently all text strings, not icons. Would you suggest changing the bell icon to 'enable/disable notifications for this post'? That would be fairly ugly.

If there's a significant number of users who don't know about this icon, let's aim to educate them about where it is and what it does.

**Comment by Flaburgan** [comment]
>In addition, like/reshare/comment are currently all text strings, not icons. Would you suggest changing the bell icon to 'enable/disable notifications for this post'? That would be fairly ugly.

I was talking about the SPV there, but the stream has to be coherent for sure.

I agree about your points here @goobertron. Maybe we could just move that icon to be the first of the fours then?

**Comment by denschub** [comment]
> Maybe we could just move that icon to be the first of the fours then?

No objections!

**Comment by goobertron** [comment]
> Maybe we could just move that icon to be the first of the fours then?

Sounds fine to me.

**Comment by Flaburgan** [comment]
#7592 is enough for us at the moment, closing this.
