### ISSUE TITLE
Featured photo doesn't appear until all the thumbnails propagate

### ISSUE THREAD

**Issue by SkewsMe** [diaspora/diaspora#7610]
When I go to Photos and click on an image, the screen darkens and the wheel spins until all of the tiny round icons underneath it get their images before the main image finally appears.

**Comment by denschub** [comment]
Just checked, and we do not block displaying or loading the main image based on the thumbnails. This is just a matter of connection speed, and obviously, the larger images tend to take longer than small ones.
