### ISSUE TITLE
Allow full stop in Hashtags

### ISSUE THREAD

**Issue by spixi** [diaspora/diaspora#7619]
# User Story
As a user I want to allow hashtags like **#cc-by-sa-4.0**, because the full stop is sometimes an elementary part of the tagged term.

# Acceptance Test
    context 'when formatting status messages' do
      it 'should leave tags with dots intact' do
        expect(
          message("foo #cc-by-sa-4.0 bar").markdownified
        ).to match  %r{foo <a class="tag" href="/tags/cc-by-sa-4.0">#cc-by-sa-4.0</a> bar}

        expect(
          message("Licensed under #cc-by-sa-4.0. Made with #love.").markdownified
        ).to match  %r{Licensed under <a class="tag" href="/tags/cc-by-sa-4.0">#cc-by-sa-4.0</a>. Made with <a class="tag" href="/tags/love">#love</a>.}

        expect(
          message("The #F.A.Z.\u8204 had an article about #K.I.Z.\u8204}").markdownified
        ).to match  %r{The <a class="tag" href="/tags/f.a.z.">#F.A.Z.</a> had an article about <a class="tag" href="/tags/k.i.z.">#K.I.Z.</a>}

        expect(
          message("Heute ist der #16.09.\u82032017.").markdownified
        ).to match  %r{Heute ist der <a class="tag" href="tags/16.09.">#16.09.</a>2017.}
      end
    end

**Comment by tclaus** [comment]
It is discussed here: https://discourse.diasporafoundation.org/t/feature-request-using-in-tag/3719/3
and in #8200
A hashtag is a hash (#) and a tag, which is a keyword, without any special characters. 
@denschub => could also be closed IMHO
