### ISSUE TITLE
Please add crossposts onto gab.ai, minds.com, youtube.com

### ISSUE THREAD

**Issue by balloonguy** [diaspora/diaspora#7623]
This would be perfect for getting around the major social networks if needed.

**Comment by piraz** [comment]
It seems like minds.com don't have a way to do that. I'm reaching out them to see if they are open to add an API level so we can publish on their environment.

Here is a bug that somebody opened on their side: https://github.com/Minds/engine/issues/14

**Comment by DeadSuperHero** [comment]
Cross-posting to YouTube doesn't exactly make sense, since Diaspora is really only cross-posting statuses. However, anything that supports OAuth could in principle be supported as a service integration.

Additionally, Gab does not appear to provide an API.

**Comment by piraz** [comment]
It seems like minds api is available.

**Comment by SomethingNewNow** [comment]
Is there a way to auto post to GAB.AI from other social platforms, or how do i add this option to the AddToAny plugin for Chrome?! Please post the solutions below thanks!

**Comment by tclaus** [comment]
Should be closed.
It makes no sense to add XY network to the crosspost-list. It makes even less sense to post to YouTube.

**Comment by SuperTux88** [comment]
I agree, if somebody really wants to maintain an additional service, they can open a new issue for that service and then we can discuss that there. But as long as nobody wants to maintain them, then there is no need to keep this open as a wishlist, and also youtube doesn't make sense for crossposting for diaspora anyways.
