### ISSUE TITLE
page jumps to top after deleting a post

### ISSUE THREAD

**Issue by haheute** [diaspora/diaspora#7628]
I hope this is not a duplicate and a relevant issue:

After deleting a post by clicking the trash icon, a hashmark (#) is appended to the URL in the browser and the page jumps to top. That is a bit disturbing when deleting multiple posts which are far down in the stream.

I have this with despora.de (Code 0.7.0.1-p1d569cea) and at least in chromium and firefox on a desktop pc.

**Comment by pskosinski** [comment]
It seems like something wrong happens somewhere around confirmation window but only when comes to confirmation windows related to post deletion. You can click the trash icon, click "Cancel" in the window, the post doesn't get deleted but the site moves to the top anyway. That doesn't happen when you try to report, ignore or hide a post.

**Comment by haheute** [comment]
Maybe [here](https://github.com/diaspora/diaspora/blob/d9b02418b651d3aedf2bbbce29e0e129b1997f8f/app/assets/javascripts/app/views/post_controls_view.js#L81) the `preventDefault()` like above , is missing? I don't know how to check, fix or test it :/
