### ISSUE TITLE
Incorrect date displayed in notifications list

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#7647]
Bit of an odd one this: I found dates out of order in the notifications list on pod.diaspora.software.

![out-of-order](https://user-images.githubusercontent.com/2530168/31783414-126614e8-b4f6-11e7-93f2-0575a46c85af.png)

On investigation, some of the timestamps don't match the date listed. The four notifications marked **13 October** are in fact listed in order (albeit the first two under the wrong displayed date): from the top, their timestamps are:
- 15/10/27, 17:36:14
- 15/10/27, 04:52:06
- 13/10/27, 15:49:38
- 13/10/27, 15:44:00

The one listed below as **15 October** is in fact out of order; its timestamp is:
- 15/10/27, 05:13:50

Any ideas why this might have happened? Pinging podmin @Zauberstuhl in case it's a configuration issue.

**Comment by SuperTux88** [comment]
Thanks for reporting this, this is a regression of #7568 and I created a PR to fix it here #7648 so we can fix it before the release \o/

**Comment by goobertron** [comment]
Thanks! 🍰
