### ISSUE TITLE
Incompatibility with Bundler 1.6

### ISSUE THREAD

**Issue by denschub** [diaspora/diaspora#7653]
When Bundler 1.6 gets released, we most likely have an issue. We depend on `Bundler::settings#with` in our application initializer here:

https://github.com/diaspora/diaspora/blob/635139919775f8eed8aa8dd845a0575fe01d3706/config/application.rb#L9

But this function got removed in https://github.com/bundler/bundler/commit/8ccf49c3b4a086f1e0cad2130dc30c04304175b7, so we throw a no method error for people who *accidentally* upgraded to 1.6. Given the PR behind it, https://github.com/bundler/bundler/pull/5811, this may or may not be an accident, but since we use internal APIs which were never documented, this is pretty much our fault and not Bundler's. :)

We should be able to replace the function call with `Bundler.settings[:with]`. Maybe, there is an even nicer option.

**Comment by denschub** [comment]
Second thoughts about the PR I linked. The `with` CLI argument will be deprecated in 1.6 and removed in 2.0. Honestly, understand this decision since remembering CLI flags always felt like a bit dark magic. Instead, they want people to use [`bundle config`](http://bundler.io/v1.15/man/bundle-config.1.html). So we should have our install docs say:

```
bin/bundle config --local with mysql
bin/bundle config --local without test:development
bin/bundle install
```

instead of

```
bin/bundle install --deployment --without test development --with postgresql
```

Which isn't as nice, but works... 

Also, `Bundler.settings[:with]` even is set in current bundler versions for whatever magic, but it's a string joined with `:` for 1.5. As it looks like in the PR, it may be that 1.6 returns an actual array instead. Should probably test that...

**Comment by grinapo** [comment]
(Makes impossible upgrade from 5.x to 6.x unless manually applied, so the upgrade instructions are broken because of this.)

**Comment by SuperTux88** [comment]
The [update instructions for 0.5.x to 0.6.x](https://wiki.diasporafoundation.org/Updating#Updating_diaspora.2A_0.5_to_diaspora.2A_0.6) say `gem install bundler --version 1.15.4` which is the last compatible version, so if you follow that, it should work. (I just noticed that the title says 1.6, but I'm pretty sure that's a typo, because the linked commit is only in 1.16 and newer)

**Comment by grinapo** [comment]
Yes but very unfortunately reality seem to defeat theory this time. Either --version doesn't get used automagically or else, but I've tried and even 1.14.1 fails with the same error so I guess something needs to be changed as well to use that. I don't know ruby so I can only follow the Holy Upgrade Instructions, and those won't work.
