### ISSUE TITLE
Do session-handling in database, Redis, or on disk, so app can be load-balanced without TCP session stickiness

### ISSUE THREAD

**Issue by jas612** [diaspora/diaspora#7659]
The app is so close to being able to be round-robin load-balanced in a sane way.  TCP session stickiness is a kludge that causes hot-spotting of individual nodes, and I would like to stop doing that with this app.

**Comment by SuperTux88** [comment]
The session is stored in the `_diaspora_session` cookie, there is no need to do any stickiness.

**Comment by Flaburgan** [comment]
@SuperTux88 the cookie is managed by the app itself, so if you deploy two unicorn and the users switch from one to the other, they will be disconnected, won't they? (I think this is the point of that issue. Maybe @jas612 wants to precise).

**Comment by jhass** [comment]
You need to share the secret key base (the one generated by https://github.com/diaspora/diaspora/blob/develop/lib/tasks/generate_session_secret.rake and stored in `config/initializers/secret_token.rb`) among all appserver processes, then it should just work.

**Comment by SuperTux88** [comment]
@Flaburgan: We already deploy two unicorns by default in production (and bigger pods have more), and you can also deploy them on different servers if you want. But as Jonne mentioned, when you configure different secrets then it doesn't work, because they can't read the cookie.
