### ISSUE TITLE
Change Twitter limit characters from 140 to 280

### ISSUE THREAD

**Issue by modInfo** [diaspora/diaspora#7661]
how to change twitter limit characters from 140 to 280 on my diaspora pod?

**Comment by Flaburgan** [comment]
This is something we need to do inside diaspora*, I'm reopening the issue.

**Comment by jhass** [comment]
Well, maybe we just sit it out until they rolled it out to everybody?

**Comment by modInfo** [comment]
https://github.com/diaspora/diaspora/pull/7662

**Comment by Flaburgan** [comment]
@jhass they are [currently doing it](https://blog.twitter.com/official/en_us/topics/product/2017/tweetingmadeeasier.html), so it will definitely be out for everybody when we release the next version of diaspora*.

However, the blog post says "Japanese, Korean, and Chinese will continue to have 140 characters". I'm wondering if we should deal with that language from the diaspora* side too. That would probably mean call the Twitter API to check the account language...
