### ISSUE TITLE
Fetch of articles when posting a heise.de link breaks the link.

### ISSUE THREAD

**Issue by paskalito** [diaspora/diaspora#7671]
example:
https://nerdpol.ch/posts/4255088

actual link is
https://www.heise.de/newsticker/meldung/25-Jahre-SMS-Die-Jubilaeumsfeier-faellt-aus-3907274.html
the link that gets fetched is:
https://www.heise.de/ho/meldung/25-Jahre-SMS-Die-Jubilaeumsfeier-faellt-aus-3907274.html

which is 404.

I've seen this on nerdpol.ch in the last month often ( maybe on every heise link)
no idea where the fault is, but i didn't find any ticket closed or open containing heise yet so.. here it is.

**Comment by goobertron** [comment]
I'm not sure what's happening in your case, but I've just tested this:

- I've clicked the link in the post https://nerdpol.ch/posts/4255088
- I've also pasted the link into a post of my own on pod.orkz.net

In both cases, hovering over the link displays the correct URL, and clicking the links takes me (correctly) to https://www.heise.de/newsticker/meldung/25-Jahre-SMS-Die-Jubilaeumsfeier-faellt-aus-3907274.html

So there might be something with your individual set-up that is redirecting you to incorrect URLs. When you hover the cursor over the link, is the correct URL displayed, or the 404 one that you are taken to when you click it?

**Comment by paskalito** [comment]
Hmm 

I just retested it with my completely unhardened chromium.

and i get the exact same results.
When i click on the link in the text it is working.
when i click on it in the title of the automagically loaded preview i get the wrong /ho 404 link.

the previews of the link work correctly. (hovering on the top shows the correct link. / hovering on the lower one shows the wrong link) clicking on either of these open the links they previewed..


i also stumbeld upon a heise post once where someone commented that the link is not working and then commented again that the top one seems to work. so i doubt its only me. thus i tried again to explain more precise where i clicked. :)

**Comment by goobertron** [comment]
>  i get the exact same results.
When i click on the link in the text it is working.
when i click on it in the title of the automagically loaded preview i get the wrong /ho 404 link.

Ah – you didn't explain that you were referring to the OpenGraph preview below the post. I tested clicking the link in the post itself. I have just tested again, and the OpenGraph preview does indeed return the 404 page you stated.

It would be worth making clear in your post that you're referring to the OpenGraph preview: perhaps changing your subject title to something like 'OpenGraph preview returns 404 when posting a link to heise.de'. This will make sure your issue is understood.

**Comment by SuperTux88** [comment]
That's because heise tells us the wrong url when fetching the OpenGraph data ... I doubt there is anything we can do about it. Maybe you could write to heise that they fix that wrong URL on their side.

```html
<meta property="og:url"              content="https://www.heise.de/ho/meldung/25-Jahre-SMS-Die-Jubilaeumsfeier-faellt-aus-3907274.html">
```

**Comment by paskalito** [comment]
@goobertron thanks for helping to find the right words to describe the issue :) - i didnt know its called that way.
@SuperTux88 thanks for checking the cause. I wrote heise a short note, im positive they will either fix it or give us usefull feedback.

**Comment by sehkunde** [comment]
Hi, thanks for bringing this to our attention. We fixed the url in the `og:url` meta-Tag.

**Comment by paskalito** [comment]
@sehkunde u welcome thanks for the fast reaction and fix :)
