### ISSUE TITLE
Notifications permissions dialog Tor Browser

### ISSUE THREAD

**Issue by miadia** [diaspora/diaspora#7677]
When using Tor Browser the dialog asking for permission to send notifications to the browser (https://support.mozilla.org/en-US/kb/push-notifications-firefox?as=u&utm_source=inproduct) reappears on every new tab or reload. Tor Browser only has the options "Receive for this session" and "Not now" so the user cannot do anything about it.
![screenshot-notification](https://user-images.githubusercontent.com/10815520/34083158-9cabeaba-e363-11e7-9ae8-d9adb7f6ab84.png)

**Comment by SuperTux88** [comment]
This looks like a problem in tor browser to me, because in firefox you can deny the permission permanent with "Never Allow". Can you please report this to tor browser?

**Comment by miadia** [comment]
I think they did this on purpose on Tor Browser. Any chance the choice for the push permission could be set in the user settings in diaspora? This would have the advantage that the setting would stay the same in any new browser that diaspora users are using.
