### ISSUE TITLE
Posts containing links are not cross-posted to Facebook

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#7678]
I finally activated cross-post to facebook on framasphere last September. I now have several users reporting that cross-post is working well for plain text messages, but that messages with links never reach Facebook. Can anyone else confirm this problem? Is that a wrong settings on framasphere or something in the diaspora* side? (as nobody tracks the Facebook API changes, it could have broke).

**Comment by HankG** [comment]
I am experimenting with this linkage and I am not having a problem with this.  I am testing it from the diasp.org pod.

**Comment by goobertron** [comment]
@Flaburgan, was this solved by #7774? I realise that wasn't specifically about fixing cross-posts including links, but as that PR adds a link to any cross-post, it might have fixed this bug incidentally.

**Comment by Flaburgan** [comment]
I can't tell, maybe @HankG who worked on it can tell us more. Facebook connection is broken from diaspora-fr and framasphere, as they probably changed their API again, and I don't care about it enough to check what's going on.

**Comment by dmorley** [comment]
I keep getting alerts from Facebook they want me to do some shit for some crap on their API, been ignoring it for months

**Comment by Flaburgan** [comment]
Maybe we should do an official announcement / call for volunteers to fix the problem, as many users are complaining and Facebook service will be (maybe is already) not working from diaspora* until somebody fixes it. So it would be nice to at least inform users.

**Comment by Flaburgan** [comment]
We're not cross posting anything to facebook anymore.
