### ISSUE TITLE
Search bar results don't include accounts at other pods

### ISSUE THREAD

**Issue by divoka** [diaspora/diaspora#7680]
Hey! I created an account at a new pod and I noticed that if I searched for profiles I had setup in another pod they wouldn't show up in the results unless I entered the profile's full ID, and vice versa. That doesn't happen with all accounts in that other pod, only some. I tested this with different pods and got the same results. I have activated the option "Allow for people to search for you within diaspora*" in all those accounts. Maybe the issue is that these accounts have been created recently and aren't indexed yet? Or am I doing something wrong? :/ I'm running some news bots and I need that every user is able to find them - and make sure I'm not running a duplicate.

**Comment by Waithamai** [comment]
Searching for people by name only works for profiles that your pod already knows (= that somebody on your pod is contacts with). For everything else you have to search the full ID. Your pod doesn't know where to search for that account if you don't include the pod's name.

**Comment by goobertron** [comment]
This is an unfortunate effect of the way federation works, what I call 'new pod syndrome'. The answer is to quickly make connections with as many pods as you can, by sharing with an account on that pod. Finding an account to share with on the largest couple of dozen pods listed in https://podupti.me/ should do the trick!

You should soon find that this is no longer a problem for your pod.

There's no software fix for this – the federation has been set up as it is to prevent network overload and make sure that performance is optimal – so I suggest closing this ticket. There are some answers about why federation has been set up to work in the way it does in response to my question about [adding push to pull](https://discourse.diasporafoundation.org/t/add-pull-to-diasporas-push-model-in-federation/231) in our Discourse forum.
