### ISSUE TITLE
Images are pixelated in mobile view on Ipad

### ISSUE THREAD

**Issue by scottrlarson** [diaspora/diaspora#7693]
When viewing images in a stream in mobile view, it looks like the platform up scales images past their dimensions. Is it possible for the platform not to upscale images past their uploaded dimensions?
![img_2221](https://user-images.githubusercontent.com/28913453/34637629-25895f4c-f26f-11e7-84c3-0bd36e19ffb7.PNG)
![img_2222](https://user-images.githubusercontent.com/28913453/34637630-25c118a6-f26f-11e7-827d-52d53c30fdf0.PNG)

**Comment by goobertron** [comment]
Hi there,
Images in the stream are scaled down to max 300px in the mobile version to avoid killing people's data allowances on mobile networks. There was a long discussion about it in #6244.

If you have a handheld device with a large screen and want high-resolution images, you can either click on the thumbnail image to see a high-res version or toggle to see the desktop view, which is responsive and should work fine on your ipad.

**Comment by scottrlarson** [comment]
The problem isn't the down scale, the problem is the upscale of the dimensions of the image on larger screens to fill the whole screen. Is there a way to maintain the physical characteristics of the image dimensions with out having to upscale the images past the available pixel resolution?

-- 
Thank you for your continued business,
by : Scott : Larson
Computer Repair | Data Recovery
Connecting your world by simplifying technology
707-536-1527

http://www.scottrlarson.com
inquiries@scottrlarson.com

Private Communication
This is strictly a two party communication between myself and the recipient. All of it's contents are my exclusive property and all rights are reserved.

**Comment by SuperTux88** [comment]
The mobile interface is optimized for phones, not tables. Displaying that image only with 300px width just wouldn't work on small phones (with high resolution but small screens), because it would be too small. That's why it is always displayed with full width.

On a tablet it works probably better when you just use the desktop interface, which doesn't have that problem.
