### ISSUE TITLE
Mentions not displaying under some conditions

### ISSUE THREAD

**Issue by rev138** [diaspora/diaspora#7695]
I recently made a post with two mentions on separate lines, like so:

@{someone@somepod.diaspora}
@{someone_else@somepod.diaspora}

Once published, only the first mention was visible. The other one disappeared.

This is version 7.2.0

**Comment by rev138** [comment]
I deleted the post and tried again. Same result.

**Comment by goobertron** [comment]
Confirmed (pod.orkz.net, v0.7.1.1).

**Comment by Waithamai** [comment]
it works if you put a blank after the first mention, before the newline. 
only without blank the second mention gets lost.
