### ISSUE TITLE
UI: add to Aspects Dropdown needs autoscroll

### ISSUE THREAD

**Issue by paskalito** [diaspora/diaspora#7696]
or else at some point you cannot create a new aspect anmore for some new contact. ( and i guess also not put them into the ones you've already mafe ) 

![bildschirmfoto vom 2018-01-13 15-48-59](https://user-images.githubusercontent.com/8012793/34907289-7e69652c-f87c-11e7-8d72-f46c3f19d839.png)

i hope one understands despite the massive blurring..

**Comment by Flaburgan** [comment]
Wow, I didn't imagine one could have that much aspects.

**Comment by paskalito** [comment]
same thing is actually also the case when using the https://share.diasporafoundation.org/about.html thing just more drastic ( since the window  has just minimal height at opening)
![bildschirmfoto vom 2018-01-13 16-50-44](https://user-images.githubusercontent.com/8012793/34907667-5532f1f4-f882-11e7-9aab-988bec85249b.png)
