### ISSUE TITLE
Username pattern is bad

### ISSUE THREAD

**Issue by Ofenhed** [diaspora/diaspora#7697]
The username in the login page contains a regex which is verified client side. The regex, however, does not include the + character, which is valid to include in emails. Logging in after disabling the pattern works.

**Comment by SuperTux88** [comment]
But the `+` isn't valid in usernames, and there are probably other chars that are valid in mail-addresses but not in the username. You can just use the username to login, and everything works. Using the mail-address also works, but isn't an official feature (the text only says "Username").
