### ISSUE TITLE
Please consider versioned downloads for diaspora (as part of the URL)

### ISSUE THREAD

**Issue by shevegen** [diaspora/diaspora#7704]
Hello diaspora devs,

Diaspora can be downloaded in various ways:

- git from the commandline
- homepage zip button to create/download a .zip file
- download from https://github.com/diaspora/diaspora/releases

I personally use the last option in general. The primary
reason is because it is the simplest for me  to 
use wget on a versioned tarball (I use a set of ruby scripts
to use remote URLs for all these programs).

On the download page above, diaspora is available as:

    https://github.com/diaspora/diaspora/archive/v0.7.2.1.tar.gz

Extracting this yields the directory **diaspora-0.7.2.1/**.

- Would it be possible to also offer tarball releases that are
named e. g. https://github.com/diaspora/diaspora/archive/diaspora-0.7.2.1.tar.gz
? It is not a big deal to me per se, since I can use ruby to automatically
repackage the above and infer the program name from other means -
but it would still be simpler (for me) to be able to just rely on a simple
(program_name)-(program_version) theme. If this is too much work for
no real gain, no worries - feel free to close this issue request at any
moment in time.

Thanks for reading!

**Comment by jhass** [comment]
Our installation guides recommend to just clone the repo and keep the master branch checked out. Thus it's is the only official method we support.

The tarballs are automatically created by Github for tags. Therefore we have no influence on their naming or content structure at all.
