### ISSUE TITLE
Feature: Post&Send Files (PDF, Zip, ...)

### ISSUE THREAD

**Issue by 6543** [diaspora/diaspora#7707]
how easy is it to integrate to post "PDFs, archives ... and other file"?
of course if you upload to big files this become wors -> limit set by podmins?
and virus -> optional virus scan avter upload via ClamAV?

what do you think?

**Comment by blackfireburn** [comment]
I would vote against this. Not only does it mean a pod hosts the files which could possibly be copyright infringing it adds to the hosting cost. There are enough file transfer services out there. And most of them already have security protocols in place to scan for infected / malicious files.

**Comment by CSammy** [comment]
Meanwhile, a [topic on Discourse](https://discourse.diasporafoundation.org/t/post-send-files-pdf-zip/1125) was created, and since this is more an idea than a specific feature request, I'll close this.
