### ISSUE TITLE
The CSRF token is invalid on Chrome

### ISSUE THREAD

**Issue by 6543** [diaspora/diaspora#7713]
I already have this issue quite a time, hoped this will be solved in the next release...
Is this an config issue at my pod or is it in general?

![csrf](https://user-images.githubusercontent.com/24977596/36075872-cfaa268a-0f54-11e8-95c3-372699cb76ee.jpeg)

**Comment by 6543** [comment]
it dosent depend on the host device mobile/desktop it is all about chrome :C

**Comment by denschub** [comment]
What's your Pod's URL?

**Comment by 6543** [comment]
diaspora.altinsystems.de
-> at the moment the server is down because my hoster thought ipfs is a maliscious attach :( give them a vew hours

**Comment by denschub** [comment]
There is an `Referrer-Policy: no-referrer` header in your response, and it should not be there. We don't set it, it's not in our example configurations, and there are reasons for that. Remove it.

Closing as a duplicate of #7603.

**Comment by 6543** [comment]
@denschub thanks for your tip!

i added 
> add_header 'Referrer-Policy' 'origin-when-cross-origin';
to my nginx proxy configuration and now it works quit well :+1:

**Comment by hasandiwan** [comment]
I'm getting this as well and adding @6543's line to nginx.conf doesn't seem to help.

**Comment by denschub** [comment]
Which pod?

**Comment by hasandiwan** [comment]
One I just set up, in development mode.
