### ISSUE TITLE
notifications.index.and_others: Wrong German translation

### ISSUE THREAD

**Issue by spixi** [diaspora/diaspora#7720]
As I am unable to comment proofread translations on WebTranslateIt, I am posting this issue here:

The German translation of `notifications.index.and_others` uses the wrong case (dative instead of nominative).

It must say

>und ein anderer
>und `{%count}` andere

instead of

>und einem anderen
>und `{%count}` anderen

![benachrichtigung](https://user-images.githubusercontent.com/3192596/36442809-368c79a6-1677-11e8-906a-002aeea20067.png)

There is also a superfluous comma. As defined [here](http://www.unicode.org/cldr/charts/32/summary/de.html#6780) the locale DE does not have a comma before the last list item.

**Comment by SuperTux88** [comment]
Translations happen at WebTranslateIt and I think there is no special permission needed (and everybody in the German team has the same permissions) to start a discussion, so please discuss this there.

**Comment by spixi** [comment]
@SuperTux88 Thank you, I just noted that I need an invitation. I will continue the translation on WebTranslateIt.
