### ISSUE TITLE
This site is lacking responsiveness .

### ISSUE THREAD

**Issue by riyak1998** [diaspora/diaspora#7723]
Hi ! i really liked the concept of this website but it lacks responsiveness for tablet-versions . The title of the website is not completely visible because of the overlapping of navigation bar. 
I am enclosing an image for the same .
![screenshot from 2018-02-24 23-08-44](https://user-images.githubusercontent.com/32415489/36633262-2cdc429e-19b8-11e8-85b4-8902b0fa29f7.png)

**Comment by goobertron** [comment]
Hello,
There is a separate repository for the project website (what you are commenting about) at https://github.com/diaspora/diaspora-project-site/issues

This repository here is for the Diaspora software itself, that runs the social network the website introduces. It would be worth posting your message at the link above. It should be a simple CSS fix.

**Comment by goobertron** [comment]
Oh, and it would be good to close this issue (button below) when you post it in the project site repo. Thanks.

**Comment by riyak1998** [comment]
Yes ! It's a very small CSS fix.
