### ISSUE TITLE
Disable back-to-top button when publisher is open

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#7733]
I frequently find when I write a post (while at the top of the page) and then go to submit the post that the back-to-top button appears over the Share button and means I can't submit without scrolling up a bit.

This is also the case when trying to submit a comment further down the page, when the back-to-top button would zoom the page to the top. Of course, the button is visible always in that case, so it's easier to avoid.

The solution is, I think, to disable the back-to-top button when the publisher (new post or comment) is open, as a user is unlikely to want to zoom to the top of the page having written a comment, as they're most likely to want to submit it. To give the option of zooming up, even when the publisher is open, another option is to disable the back-to-top button when and only when it overlays the Share button of an open publisher. That way someone could scroll up or down just enough to move the submit button away from the location of the back-to-top button and then be able to click to zoom up.

Currently the back-to-top button is hidden when viewing the top of the page, but appears on hover. This is not normally a problem, although unnecessary behaviour. I think it would also make sense to disable back-to-top when already at the top of the page, because the button is useless there. That might be a separate issue; if you want me to open a separate ticket for that, please let me know.

Hope this makes sense. I'm operating on about 90 minutes' sleep so am a bit ragged.

**Comment by SuperTux88** [comment]
> Currently the back-to-top button is hidden when viewing the top of the page, but appears on hover. This is not normally a problem, although unnecessary behaviour. I think it would also make sense to disable back-to-top when already at the top of the page, because the button is useless there. That might be a separate issue; if you want me to open a separate ticket for that, please let me know.

That's already fixed by #7729, the back-to-top button is either visible and clickable, or unvisible and unclickable and doesn't suddenly appear when you hover it. That also means that you at least see the button when it's above the submit button before you hover it, or when you don't see it, it's save to click.

**Comment by Flaburgan** [comment]
@goobertron the code is deployed on https://diaspora-fr.org if you want to test it there.

**Comment by goobertron** [comment]
Thanks both, I'll check it out soon.
