### ISSUE TITLE
Native video player not working in comments in the SPV

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#7736]
See for example [this comment](https://diaspora-fr.org/posts/3390448#abb872900373013680d74be2ca51701c): from the SPV, the video can't be played. However, if you go to [my profile](https://diaspora-fr.org/u/fla) and scroll to the post to find the same comment, you'll be able to play the video.

**Comment by goobertron** [comment]
It's great that video embedding is now possible in comments!

In case it helps to debug this, I just tried your links and confirmed the bug. In the stream, I found that NoScript was blocking JS from imgur.com, so had to enable it; in the SPV, NoScript didn't even mention imgur.com. So it seems that JS is prevented from being loaded in comments in the SPV, at least when video embedding is concerned.
