### ISSUE TITLE
Why is open source projects of diaspora magnitutde riddled with tech ppls?

### ISSUE THREAD

**Issue by nicubuga** [diaspora/diaspora#7741]
Hi,

I wonder why diaspora is full of tech people, it's not a social network only for linux fans and stuff (same goes for Mastodon, where there's a lot of chinese ppl).

Is this a problem?

**Comment by goobertron** [comment]
Um, this is an issue tracker for development of the software that runs Diaspora. For general discussion, the best thing to do would be to make a public post in Diaspora itself.
