### ISSUE TITLE
db:create fails on initial setup

### ISSUE THREAD

**Issue by kkretsch** [diaspora/diaspora#7743]
I try to follow the install faq for ubuntu 16.04.4 LTS. Everythings works fine until I try to create the database and tables.
`RAILS_ENV=production bin/rake db:create db:migrate`
fails with

> Rack::SSL is enabled
> /home/diaspora/diaspora/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:61:in `async_exec': PG::UndefinedTable: ERROR:  relation "people" does not exist
> LINE 8:                WHERE a.attrelid = '"people"'::regclass
>                                           ^
> :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
>                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
>                      c.collname, col_description(a.attrelid, a.attnum) AS comment
>                 FROM pg_attribute a
>                 LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
>                 LEFT JOIN pg_type t ON a.atttypid = t.oid
>                 LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
>                WHERE a.attrelid = '"people"'::regclass
>                  AND a.attnum > 0 AND NOT a.attisdropped
>                ORDER BY a.attnum
>  (ActiveRecord::StatementInvalid)

I can manually connect to postgres using the credentials from config/database.yml

**Comment by goobertron** [comment]
Hi, this is a tracker for issues in and development of the core diaspora* software, not for support with individual instances.

For support, use either our [IRC channel](https://wiki.diasporafoundation.org/How_we_communicate#IRC) or the [support section of our Discourse instance](https://discourse.diasporafoundation.org/c/support).

**Comment by kkretsch** [comment]
OK, I tried an a second instance with enough coffe. Now it's working again.
