### ISSUE TITLE
"What's New" link broken

### ISSUE THREAD

**Issue by eddietejeda** [diaspora/diaspora#7753]
![screen shot 2018-03-27 at 7 22 10 pm](https://user-images.githubusercontent.com/669988/38005115-51224c6c-31f4-11e8-8870-2e19d8bd628c.png)

The "what's new" link is broken. It's currently pointing here: https://github.com/diaspora/diaspora/blob/c690727c19896aaa5362bd10ca90924ca8791ecd/Changelog.md

**Comment by SuperTux88** [comment]
That's a "bug" of your pod and happens for pods with modified sourcecode which isn't hosted at GitHub, but in that case the podmin can set the correct changelog url in the [config](https://github.com/diaspora/diaspora/blob/develop/config/diaspora.yml.example#L541-L544).
