### ISSUE TITLE
Reduce font-size used to display titles in users posts

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#7757]
We only kept the `h1`, `h2` and `h3` titles in markdown posts a while ago and I think this is enough. However, the font-sizes used to display these titles are, in my opinion, too big. The h1 really looks like yelling out loud. So I only use the h3 title for my main title. But that means I can't have any subtitles!
There is plenty of room between the h3 size and the normal font size, I would suggest reduce the size used to display those titles so they all can be used.

**Comment by goobertron** [comment]
I agree that `h1` is far too big. The current size of `h2` is the biggest anyone could need.

> But that means I can't have any subtitles! There is plenty of room between the h3 size and the normal font size

Don't forget about `h4`... (four # at the start of the line)

Personally I think users should have to earn a gold star for not using huge type for at least 6 months before being allowed to use the higher heading levels...

I'd be happy for `h1` to be reduced to something close to what `h2` is currently, and `h2` to be reduced to half-way between that and `h3`, if that's what you want to do.

**Comment by Nimmyjv** [comment]
Hi Where can i see this issue?

**Comment by Flaburgan** [comment]
What do you mean by "See"? How to reproduce it?

**Comment by svbergerem** [comment]
FYI we do use `h1` to `h6`. The font sizes are:

`h1`: 33px
`h2`: 27px
`h3`: 23px
`h4`: 17px
`h5`: 13px
`h6`: 12px

The default font-size for text is 13px.

**Comment by Nimmyjv** [comment]
@Flaburgan yeah I mean how to reproduce it

**Comment by goobertron** [comment]
As this is not a bug but a preferential UI change, I think it would make sense for one of our Design Team® (mainly @svbergerem and @Flaburgan) to make this change, or at least to make the decision over what sizes should be used.

**Comment by Flaburgan** [comment]
So I had a quick look at that issue, here is my proposition:

**Before** (With the sizes listed by @svbergerem above)

![Screenshot_2019-06-11 diaspora (1)](https://user-images.githubusercontent.com/930064/59268263-9bc08780-8c4c-11e9-8743-9b6b2a4042e3.png)

**After**

![Screenshot_2019-06-11 diaspora ](https://user-images.githubusercontent.com/930064/59268264-9bc08780-8c4c-11e9-869e-55873ce12dde.png)

With the following sizes:
```
h1 {
    font-size: 27px;
  }

  h2 {
    font-size: 23px;
  }

  h3 {
    font-size: 20px;
  }

  h4 {
    font-size: 18px;
  }

  h5 {
    font-size: 16px;
  }

  h6 {
    font-size: 14px;
  }
```

As you can see, the sizes are more consistent and the h1, h2 and h3 titles are less prominent. I'm going to open a pull request with that patch, but don't hesitate if you have any feedback.

**Comment by goobertron** [comment]
The changes looks good.

I've just thought of one potential drawback: This is going to affect rendering of all past posts. For instance, I always use `h3` as the top-level heading in my posts because I want my main headings to be the size of the current `h3` style. After this change, the main headings in my posts will be quite a bit smaller. (And the same will apply to all users who have entered headings in their posts.)

Would it be (a) feasible and (b) desirable to code so that this change in heading sizes is only applied to posts made after the release date?

**Comment by Flaburgan** [comment]
I thought about that too, as I have the exact same behaviour than you actually: using h3 instead of h1 because they are too big. Unfortunately, I see no easy way to display differently posts depending of their date. Even harder, pods will not upgrade at the same time so some posts may be written with the old sizes and rendered with the new sizes on updated pods. So... I'll keep it simple imo.

**Comment by goobertron** [comment]
> Even harder, pods will not upgrade at the same time so some posts may be written with the old sizes and rendered with the new sizes on updated pods.

I thought of that, but it would only affect posts created over a few weeks on some pods, rather than posts on all pods stretching back 8 years, so a far smaller impact.

But if it would add code complexity that might impact performance, it would probably not be worth it.
