### ISSUE TITLE
test fails on specific days (and time?)

### ISSUE THREAD

**Issue by devkral** [diaspora/diaspora#7763]
At least one test fails because of day of month (and time?).
See:
https://travis-ci.org/diaspora/diaspora/builds/360605850
Proof:
I could "fix" the bug by triggering the build next day and the build worked the day before. The only change were on comments to trigger travis builds.
the date was 31.3.2018

**Comment by jhass** [comment]
That's just one of the last unreliable ones, I highly doubt it's related to the current date

**Comment by SuperTux88** [comment]
Yes, that's just a random fail.
