### ISSUE TITLE
No login button

### ISSUE THREAD

**Issue by RoaldSchopenhauer** [diaspora/diaspora#7766]
![2018-04-04_202201](https://user-images.githubusercontent.com/38082942/38326690-b56832d8-3846-11e8-9ed8-6242457e00f9.jpg)
I am not able to login to Diapora* since there is no login button anywhere. Se screendump above (Danish).
I am using Chrome for Windows 11.

**Comment by SuperTux88** [comment]
You can't login on the project site, you need to login on your pod. I don't know on which pod you created your account.
