### ISSUE TITLE
Emails timing out

### ISSUE THREAD

**Issue by kindlyfire** [diaspora/diaspora#7768]
Hello,

After testing my email configuration for a while, I cannot get it to work. They keep timing out with the following error: [link](https://paste.angristan.xyz/?9d8251907faebde0#Pw4CjxZBJ1NqpFlU+Q1aldwMWa1UTSgjEABNW7oGOok=).

Here is my email configuration:

```
    ## Ignore if method isn't 'smtp'.
    smtp: ## Section

      ## Host and port of the smtp server handling outgoing mail.
      ## This should match the common name of the certificate sent by
      ## the SMTP server, if it sends one. (default port=587)
      host: '<domain>'
      port: 465

      ## Authentication required to send mail (default='plain').
      ## Use one of 'plain', 'login' or 'cram_md5'. Use 'none'
      ## if server does not support authentication.
      authentication: 'login' # I tried 'plain' as well

      ## Credentials to log in to the SMTP server.
      ## May be necessary if authentication is not 'none'.
      username: '<hidden>'
      password: '<hidden>'

      ## Automatically enable TLS (default=true).
      ## Leave this commented out if authentication is set to 'none'.
      starttls_auto: false # I tried with true as well

      ## The domain for the HELO command, if needed.
      domain: '<my instance domain>'

      ## OpenSSL verify mode used when connecting to a SMTP server with TLS.
      ## Set this to 'none' if you have a self-signed certificate. Possible
      ## values: 'none', 'peer'.
      openssl_verify_mode: 'none' # Tried 'peer' as well
```

I tried all sorts of different combinations. The catch is, my email server is SSL/TLS only, meaning no starttls, just plain SSL/TLS. How can I specify this ? Per example, on Mastodon, I can set "SMTP_TLS=true".

**Comment by goobertron** [comment]
This looks like a support issue rather than a bug in the core software, as emails work for most pods. Try the [Podmin Support](https://discourse.diasporafoundation.org/c/support/podmin-support) section of our Discourse forum.

**Comment by KindlyFire** [comment]
To me it seems like there is an option missing from the configuration file, the option to connect using TLS (without using STARTTLS). I'll ask on the Discourse forum to be sure.

**Comment by KindlyFire** [comment]
Sorry, I couldn't find a way to get it working. I got around it by using a transactional email provider instead of using my own email server.

**Comment by ansorg** [comment]
hi @goobertron I wonder: in diaspora.yml we are supposed to set smtp host. 
But in mailer_config.rb I find a reference to AppConfig.mail.smtp.domain but not to host.
`smtp_settings = {
        address:              AppConfig.mail.smtp.host.get,
        port:                 AppConfig.mail.smtp.port.to_i,
        domain:               AppConfig.mail.smtp.domain.get,
        enable_starttls_auto: false,
        openssl_verify_mode:  AppConfig.mail.smtp.openssl_verify_mode.get,
        ca_file:              AppConfig.environment.certificate_authorities.get
}`

On the other hand, even setting the `#domain for the HELO command, if needed` to the same value as `host` does not help

So, a bug or not a bug in the smtp settings/mailer_config?
