### ISSUE TITLE
Optimizing MySQL for stream load

### ISSUE THREAD

**Issue by tferreira** [diaspora/diaspora#7789]
Hi,

I wanted to know if any podmins or developers on the project already made some optimizations on MySQL side (not optimizing the query on the code itself) to make the stream load faster ?

I was trying to find the potential bottlenecks when loading my stream page on my pod, as it takes roughly 6-8 seconds to display it.

FYI, I'm following ~35 tags.

I found it was this query:
```
 SELECT DISTINCT posts.*,
                posts.id
FROM   `posts`
       INNER JOIN `taggings`
               ON `taggings`.`taggable_id` = `posts`.`id`
                  AND `taggings`.`taggable_type` = 'Post'
WHERE  `posts`.`type` IN ( 'StatusMessage' )
       AND `posts`.`public` = 1
       AND ( taggings.tag_id IN ( 291, 79, 948, 181,
                                  15, 24, 1153, 10855,
                                  1043, 97, 2413, 115,
                                  180, 15390, 53, 226,
                                  2, 5, 57, 59,
                                  10861, 192, 210, 25,
                                  49, 5155, 28007, 48,
                                  52817, 151, 88, 1017,
                                  13596, 1599, 5270 ) )
       AND ( posts.author_id NOT IN ( 24524 ) )
       AND ( posts.created_at < '2018-04-15 23:55:38' )
       AND `posts`.`type` IN ( 'StatusMessage', 'Reshare' )
ORDER  BY posts.id DESC
LIMIT  15
```
```
15 rows in set (6.80 sec)
```

An EXPLAIN on this query shows the reason why it's slow. It is creating a temporary table for the **posts** table part:
```
*************************** 1. row ***************************
           id: 1
  select_type: SIMPLE
        table: posts
   partitions: NULL
         type: index
possible_keys: PRIMARY,index_posts_on_author_id_and_root_guid,index_posts_on_person_id,index_posts_on_id_and_type_and_created_at,index_posts_on_id_and_type
          key: PRIMARY
      key_len: 4
          ref: NULL
         rows: 66
     filtered: 0.23
        Extra: Using where; Using temporary
```

But removing a few tags in the query avoids that:
```
*************************** 2. row ***************************
           id: 1
  select_type: SIMPLE
        table: posts
   partitions: NULL
         type: eq_ref
possible_keys: PRIMARY,index_posts_on_author_id_and_root_guid,index_posts_on_person_id,index_posts_on_id_and_type_and_created_at,index_posts_on_id_and_type
          key: PRIMARY
      key_len: 4
          ref: diaspora_production.taggings.taggable_id
         rows: 1
     filtered: 5.00
        Extra: Using where
2 rows in set, 1 warning (0.00 sec)
```
And the query takes a lot less time:
```
 SELECT DISTINCT posts.*,
                posts.id
FROM   `posts`
       INNER JOIN `taggings`
               ON `taggings`.`taggable_id` = `posts`.`id`
                  AND `taggings`.`taggable_type` = 'Post'
WHERE  `posts`.`type` IN ( 'StatusMessage' )
       AND `posts`.`public` = 1
       AND ( taggings.tag_id IN ( 291, 79, 948, 181,
                                  15, 24, 1153, 10855,
                                  1043, 97, 2413, 115,
                                  180, 15390, 53, 226,
                                  59, 10861, 192, 210,
                                  25, 49, 5155, 28007,
                                  48, 52817, 151, 88,
                                  1017, 13596, 1599, 5270 ) )
       AND ( posts.author_id NOT IN ( 24524 ) )
       AND ( posts.created_at < '2018-04-15 23:55:38' )
       AND `posts`.`type` IN ( 'StatusMessage', 'Reshare' )
ORDER  BY posts.id DESC
LIMIT  15  
```
```
15 rows in set (1.53 sec)
```

I want to add that I already have done some tweaks.

- Disabling SWAP on my server by changing the system variable `vm.swappiness = 0`
- `innodb_buffer_pool` is already bigger than the database dataset size, so it's all on RAM
- Tried lowering the `optimizer_search_depth` mysql setting value to make the query engine change its behavior.

Do you have any opinions on this ? Is it purely an optimization that should be done directly on the query within the codebase of the project ?

Thanks

**Comment by maxolasersquad** [comment]
There is some weirdness in this query. Personally I don't like putting non-joining statement in the `on` clause, but in my testing the `AND posts.public = 1` does produce a lower-cost explain plan. The first part of the where clause does a comparison against posts.type as does the last part, but the pre-processor seems to take care of that as it doesn't affect the explain plan.

I think a guide on optimizing MySQL for Diaspora would be a good idea, but I think optimizations would depend largely on the specifics of the install.

**Comment by tferreira** [comment]
I've run `OPTIMIZE TABLE` on Diaspora tables, and I think it changed how the engine is making the queries, as it is not using a temporary table anymore, and it takes 1.83 seconds instead of 6.80 seconds.

I should have done this first, but I didn't think it would help that much. Not sure if this is the ultimate solution though.
