### ISSUE TITLE
Wrong link for Jamendo open graph preview

### ISSUE THREAD

**Issue by SansPseudoFix** [diaspora/diaspora#7801]
Steps to reproduce:

* add any track link from [jamendo](https://www.jamendo.com/) into a post
* publish
* preview image is ok, but link is always `https://www.jamendo.comundefined/`

Tested on Framasphère and diaspora-fr. (Tested on a mastodon instance too to be sure it's not a Jamendo issue, and it works).

**Comment by SuperTux88** [comment]
This is a jamendo issue, because diaspora just uses the `og:url` and jamendo has `<meta property="og:url" content="https://www.jamendo.comundefined" />` in the response.
