### ISSUE TITLE
Server Question

### ISSUE THREAD

**Issue by g-monk** [diaspora/diaspora#7802]
I am new to exploring all of the projects listed on privacytools.io: https://github.com/privacytoolsIO/privacytools.io/issues/453. Referring to this issue I want know what are the differences between Friendoca and Diaspora? Are all things mentioned by the Friendica developer also applicable to Diaspora servers in terms on server admin having access to messages?? Please clarify my concerns 

Thanks,

G-Monk

**Comment by goobertron** [comment]
This is not the place to ask general questions. This is an issue tracker for developing the software.

There are explanations of how Diaspora works on [the project's website](http://diasporafoundation.org/) and [wiki](https://wiki.diasporafoundation.org/) (try the [FAQ for users](https://wiki.diasporafoundation.org/FAQ_for_users) to start with), and a [series of tutorials](https://diasporafoundation.org/tutorials) describing how to use the network.

I personally don't know much about Friendica, but [that project's website](https://friendi.ca/) seems to have similar descriptions of how that network works.

**Comment by SuperTux88** [comment]
Friendica and diaspora are compatible and work pretty similar in many points. But as @goobertron already said, this is an issue tracker, if you want to know more, please open a thread in [discourse](https://discourse.diasporafoundation.org/).
