### ISSUE TITLE
Pod didnt work after Upgrade

### ISSUE THREAD

**Issue by 6543** [diaspora/diaspora#7809]
./script/server :

 > ERROR -- : [diaspora:web] process <19885> failed to start (:bad_identity)

**Comment by goobertron** [comment]
I think it's been mentioned to you before that GitHub is not a place for support requests. Either contact the developers on [IRC](https://wiki.diasporafoundation.org/How_we_communicate#IRC) or in the [Support category of Discourse](https://discourse.diasporafoundation.org/c/support).
