### ISSUE TITLE
SSL/TLS: Missing `secure` Cookie Attribute

### ISSUE THREAD

**Issue by tursiops33** [diaspora/diaspora#7811]
Hi everyone,
I use a third party service to check my server for security flaws, and it detected the following, which I wanted to have everyone's opinion on:

Summary

The host is running a server with SSL/TLS and is prone to information
  disclosure vulnerability.

Description

The cookies:

Set-Cookie: _diaspora_session=aFVBTTQrSGZWUVllUlBxVHQ5dHdwS0V1UytON3NtRi9MK1g2ZXM0R2FFdkpqYW9qTWpCeUw1d0Y5aytpbjZZWU5DY3NldUJlcTRaZk5HSE9LWGc3V0hDdW8rYVVISUhvM1kyYzEvTjI4TjF0aUlmZzVrWkNOREVCQWlEdUM5c0lWSThSUldaUlYzdWNNNDhJVFprZUo1cWFtWlBFZk5qYW14dVVPT2tUcVBxOHhJSm1LYmxnRHRIb2JxSzVxdlhwM1QyQkZvTzJhd280aStDVFFESTlLQT09LS1PZ2xsdDg4Wm5NZEtkSWQ2R2cwV3NRPT0%3D--da0e18de81aacd2cbb2f8f79b97a390c5ca6ef6c; path=/; HttpOnly 

are missing the "secure" attribute.

Solution

Set the 'secure' attribute for any cookies that are sent over a SSL/TLS connection.

Affected

Server with SSL/TLS.

Insight

The flaw is due to cookie is not using 'secure' attribute, which
  allows cookie to be passed to the server by the client over non-secure channels (http) and allows attacker
  to conduct session hijacking attacks.

  Impact Level: Application

Is it me that has not activated a specific option or is it something that is just missing or not implemented yet ? 

Thank you very much!

**Comment by SuperTux88** [comment]
Diaspora sets the `secure` flag if the pod is configured correctly. You need to enable `require_ssl` in the [diaspora.yml](https://github.com/diaspora/diaspora/blob/develop/config/diaspora.yml.example#L55-L61), which is even enabled by default in production. So when you disabled it, you should enable it again.
