### ISSUE TITLE
http://localhost:31000/i... instead of https://mydomain.com/i/...

### ISSUE THREAD

**Issue by lesamarien** [diaspora/diaspora#7813]
Hello
My server is on Yunohost and I installed my Diaspora pod with a docker as described at the following address: https://github.com/aymhce/diasporadocker_ynh

As described in the attached image, if I want to invite friends, I have the address http://localhost:31000/i... instead of https://mydomain.com/i/...

My server uses only Nginx and in the configuration nginx diaspora, I have the following line which corresponds to the address seen above:

proxy_pass http://localhost:31000;
proxy_read_timeout 30s;

Can you help me fix this problem?
Thank you for your help

![capture](https://user-images.githubusercontent.com/35960036/40107709-48a8fd0c-58f9-11e8-9cd1-e863e68bf4c6.JPG)

**Comment by goobertron** [comment]
Github is for developing and fixing bugs in the core software. It is not a place to seek support.

Please see https://wiki.diasporafoundation.org/How_we_communicate

Have you tried the instructions here? [FAQ for pod maintainers: Troubleshooting](https://wiki.diasporafoundation.org/FAQ_for_pod_maintainers#I_installed_diaspora.2A_on_my_machine.2C_went_to_http:.2F.2Flocalhost:3000_and_signed_up._But_my_friends_can.27t_add_me.21)

If that doesn't work, try IRC or [Podmin support](https://discourse.diasporafoundation.org/c/support/podmin-support) on Discourse, as described in the 'How we communicate' article.

Please would you close this ticket now? Thank you.

**Comment by lesamarien** [comment]
Yes I close the ticket
