### ISSUE TITLE
Allow to override config dir location

### ISSUE THREAD

**Issue by cyberb** [diaspora/diaspora#7817]
Is it possible to add an option to override config location to be outside the main tree?
I maintain a few patches here to make it possible:
https://github.com/syncloud/diaspora/tree/master/patches

Do you want me to create a pull request with this feature?

**Comment by SuperTux88** [comment]
You can just set a symlink to the location where your config is, for example somewhere in /etc (at least the arch package already does this). That's much easier and less error prone because it can't be forgotten when somebody wants to do `bin/rails console` or follows other guides in the wiki where the env-var isn't mentioned.

**Comment by cyberb** [comment]
I am doing for snap where app code is mounted read-only, so symlinks or any other file system modification is not possible.
Doing this at build time (to overcome runtime read-only mode) is not ideal either as you do not want to hardcode runtime details which are available through $SNAP* variables.
So ideally diaspora would allow config location override using non filesystem specific way, like command line args or env variables.
So I consider this issue is not resolved yet.

**Comment by SuperTux88** [comment]
Read-only filesystem wouldn't work for diaspora anyway, because there are other files/directory which need to be writeable (or symlinked to another location), for example `public/upload`, `log`, `tmp` or `config/initializers/secret_token.rb` (or maybe more).

**Comment by cyberb** [comment]
Correct.
That is the point of this issue. As I said I have managed to create few patches and run Diaspora as a snap package (https://github.com/diaspora/diaspora/issues/7141)
I can create more tests as we have automated test runs of a package (ex: http://artifact.syncloud.org/diaspora/ci/203-sam-amd64/screenshot/login.png)

**Comment by SuperTux88** [comment]
And how did you manage to make the other files/directories writable or create a symlink and why can't do do the same for the config?

**Comment by cyberb** [comment]
I have modified diaspora code as you can see from the patches. But I would like it upstream.
Many apps allow some form of config location override (actually usual thing).
Hardcoded location should not be the only option.
I am not saying you should support snap specific variables, something like DIASPORA_CONFIG_DIR would be be perfect. If set use otherwise fallback to default current implementation.

I can prepare a pull request with the initial files I am aware of. But I need to understand if anyone is willing to review and merge it.

**Comment by jhass** [comment]
All settings can also just be set as environment variables, as explained on the top of the file. database.yml is passed through erb, so you can just ship a version that reads from the environment as well.

**Comment by cyberb** [comment]
There are a lot of Rails.root references in the code, is it possible to override it using environment variable?

Also after spending a week trying to override tmp, public/upload I ended up symlinking them at build time, at least storage directory for them is the same across snap and non snap packages. Messing around with carrierwave initializer did not get me anywhere :(

**Comment by amorphous** [comment]
Did this get anywhere?

This would be an excellent way to spread Diaspora, and Snap#s are fast becoming trusted as a good way to sandbox apps (not to mention make them easy to set up on a system). A Boost in instances would be a definite benefit to botht the community, and a 'giant leap' for distributed social media, but the store is the point of trust.

Please consider it(!)
