### ISSUE TITLE
Precompiling fails with exception using procedure from official wiki

### ISSUE THREAD

**Issue by Maikewng** [diaspora/diaspora#7820]
Hello everyone!
I'm following the procedure from the official wiki to make a diaspora pod out of a Raspberry Pi 3:
https://wiki.diasporafoundation.org/Installation/Debian/Jessie?db=mariadb&mode=production
However, when I get to the precompiling part, I get an exception. You can find the stack trace here: https://tdd1.ddns.net/nextcloud/s/oGXmf7faLJmGMEX
I am using the latest release of Raspbian, which is based on Debian 9.

Let me know how I can help.

**Comment by goobertron** [comment]
Hi,

Github is for developing and fixing bugs in the core software. It is not a place to seek support.

Please see https://wiki.diasporafoundation.org/How_we_communicate

Try IRC or [Podmin support](https://discourse.diasporafoundation.org/c/support/podmin-support) on Discourse, as described in the 'How we communicate' article.

One of the people who has set up a pod on a Pi is Brian Ó (blacksam@social.gibberfish.org). You could ask him in Diaspora if he can help.

Please would you close this ticket now? Thank you.

**Comment by Maikewng** [comment]
Understood, thank you. I opened a new topic on discourse.
