### ISSUE TITLE
Improve description of web+diaspora:// handler

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#7838]
When the user clicks on the Register button after he already registered, nothing happens. The button should not be displayed anymore. Instead, there should either be a button allowing to unregister, or a text explaining how to manage handlers inside the browser.

**Comment by SuperTux88** [comment]
AFAIK there is neither a way to tell if a user installed the handler nor is there a way to unregister the handler, so I think we can't solve this?

But you can extend the current text if you like and write something about that the button only does something if the handler isn't installed already and that the users need to remove the handler from the browser settings.

**Comment by Flaburgan** [comment]
Let's do that then.

**Comment by denschub** [comment]
> AFAIK there is neither a way to tell if a user installed the handler nor is there a way to unregister the handler, so I think we can't solve this?

Just dropping by to say that this is true.

**Comment by develaper** [comment]
Hi! I am planning to start to work on this issue but not very sure about how to reproduce it. Are we talking about the "register button" that takes the user to "/users/sign_up" ?

**Comment by Flaburgan** [comment]
No, we're talking about the *web+diaspora:// protocol handler* section in the settings. You can read there what's this about.

**Comment by cmrd-senya** [comment]
@Flaburgan does your comment missing a link at the _there_ word?

**Comment by cmrd-senya** [comment]
> AFAIK there is neither a way to tell if a user installed the handler nor is there a way to unregister the handler, so I think we can't solve this?

If this is true then perhaps we should change the issue topic, shouldn't we?

**Comment by Flaburgan** [comment]
> @Flaburgan does your comment missing a link at the _there_ word?

No, I was talking about the settings inside diaspora*. Sorry if that wasn't clear.
