### ISSUE TITLE
Chat profile picture 

### ISSUE THREAD

**Issue by GeigerCounter** [diaspora/diaspora#7858]
The chat lists in Diaspora's chat client do not match with the diaspora user's profile picture, instead providing a generic picture.

**Comment by sjain1107** [comment]
Would you like to add a screenshot?

**Comment by HankG** [comment]
Here's what it looks like on mine (my username starts with H which it seems to cue off of): 
![screenshot at 2018-10-07 16 06 36](https://user-images.githubusercontent.com/1683691/46586330-0466bd00-ca4b-11e8-98e0-c7e36e1215f6.png)

**Comment by SuperTux88** [comment]
The chat was removed with #8069, this is obsolete now.
