### ISSUE TITLE
Diaspora rejects OAuth redirect_uri which is not http: or https:

### ISSUE THREAD

**Issue by btnsoc** [diaspora/diaspora#7862]
Trying to use https://github.com/openid/AppAuth-Android with Diaspora, but I just get a "Invalid client id or redirect uri" error message.

The format of the redirect_uri is: net.openid.appauthdemo:/oauth2redirect

This would be handled by the android application. I have tried looking at the code to see where it is validating the redirect_uri but my knowledge of ruby is fairly minimal.

**Comment by btnsoc** [comment]
Problem was that I hadn't registered my app with the OpenID API.
Now, I can get the access_token, but I get a 401 error when trying to use it within the android app I'm attempting to write.
I have tried passing the client_id with the access_token as GET parameters to 
eg: /api/v1/aspects?access_token=[token]&client_id=[clientid]

Seem to be missing something...
Can somebody point me in the right direction as to the relevant documentation?

**Comment by Flaburgan** [comment]
Hi btnsoc, please note that the diaspora* API is currently a work-in-progress. You should be able to authenticate and allow your app but not access any actual data. Please see https://github.com/diaspora/diaspora/pull/7462 to follow (or maybe participate ;)) to the API work.

Also note that [dandelion](https://github.com/gsantner/dandelion) is an Android diaspora* app which, although unofficial, is already pretty advanced. If you want to improve the diaspora* experience on Android, you can maybe help there ;)
