### ISSUE TITLE
Fair moderation and Hatespeech, Lack of moderation tools

### ISSUE THREAD

**Issue by Tectract** [diaspora/diaspora#7865]
Hello, 

   I've been a podmin since 2012, and right now, my support for D* is looking like it may be coming to an end. I was just banned from the Discourse site because I had created a thread about lack of moderation tools available for podmins to fight hatespeech on D*. I'm requesting a review of that action and a re-instatement of my account there. 

   We need tools to fight against users that abuse D* and habitually violate TOS, jumping from pod to pod, and we need to consider taking action against pods that host hatespeech accounts, imho. If there is already a discussion on this specific topic, I'd gladly contribute there. However, having my account suspended from Discourse for starting a discussion about fair moderation seems pretty egregious. 

I'd like a discussion about this topic, not just a unilateral ban from Dennis because he's angry right now.

**Comment by SuperTux88** [comment]
@denschub and @goobertron already said everything about this topic (and I completely agree with them). You don't make it better by starting spamming on discourse and now start spamming on github after your account was suspended there. So please stop!

Your problem is already covered by #7464, so I'm closing this as duplicate.

**Comment by Tectract** [comment]
Look, I apologize for getting angry about seeing hatespeech posted to my pod. That thread was not mentioned to me, in the original discussion, for which I was banned. Please unban my account at discourse, I will contribute in the proper threads. Getting angry about a heated issue like this is not to be unexpected, guys.

**Comment by Tectract** [comment]
Spam is an usolicited advertisement for a paid product or service. That's not AT ALL what I have done. Show me where is the rule about "posting too often" in your TOS?

I want to contribute to this important aspect of moderation on D*, but I won't do that unless you guys show me that you can be reasonable and unban my discourse account.
