### ISSUE TITLE
tmp/diaspora.sock failed (111: Connection refused)

### ISSUE THREAD

**Issue by Maca00** [diaspora/diaspora#7886]
Hello,

I have this error when I try my domain : 
 *1 connect() to unix:/home/diaspora/diaspora/tmp/diaspora.sock failed (111: Connection refused) while connecting to upstream

I can not find a solution...

Any ideas ?

Thank you

**Comment by SuperTux88** [comment]
Check if diaspora is running properly and if the permissions are correct so the webserver can access the socket. But this is a bugtracker and not a support forum, if it's still not working, check the [Podmin Support](https://discourse.diasporafoundation.org/c/support/podmin-support) section in our discourse or join our IRC channel.
