### ISSUE TITLE
Provide configuration option to suppress link preview at end of post

### ISSUE THREAD

**Issue by justinpletzfeld** [diaspora/diaspora#7889]
After inserting a link (to a youtube video for example) a preview/player for that link/video is appended to the end of the post. IMHO that preview/player is sometimes a bit distracting and draws attention away from the post. Can we have a configuration option for this?

**Comment by Flaburgan** [comment]
Hi @justinpletzfeld and thank you for your suggestion! This request has already be made, see https://github.com/diaspora/diaspora/issues/7506, so I'm closing this one.

**Comment by justinpletzfeld** [comment]
Thanks @Flaburgan ! Didn't see that one when I searched for this topic. Or better - didn't understand that this was the same as my request :-)))
