### ISSUE TITLE
Support for the webp image format

### ISSUE THREAD

**Issue by hansw-nlo** [diaspora/diaspora#7893]
Dear team, 

As a feature request I would like to hear if it is possible to enable the support for the webp format. Modern camera's create a jpg format that is showing a size of around 10 Mb. Converting it to webp results in some 1 to 3 Mb per picture. 

Best regards,

Hans

**Comment by Flaburgan** [comment]
@hansw-nlo and thank you for your suggestion! At the moment, webp is not supported by all the major browsers, I know that [at least Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1294490) doesn't support it. So although this is a good idea, I'm not sure diaspora* should allow users to upload webp images at the moment as every Firefox users (which represent the majority of diaspora* users on the pods I administrate) will not see anything and think that it is a bug in diaspora*.

I'll keep that issue open but I propose to wait for a better browser support before implementing it.

**Comment by SuperTux88** [comment]
It's not only firefox, [half of the browsers don't support webp yet](https://caniuse.com/#feat=webp), so until more browsers support it, I think it's not a good idea to support webp. It's confusing when you can upload an image and half of the users don't see it, that only leads to more support questions (as fla already wrote).

**Comment by hansw-nlo** [comment]
Ah, indeed. I tested it on Firefox now. Working with Chromium over here. 
thanks for the info

**Comment by Flaburgan** [comment]
For the record, the today released Firefox 64 now supports WebP.

**Comment by bkil** [comment]
Also in general, it would be possible to transcode media during upload to various formats and the client could decide which version they would like to see depending on local software support and hardware acceleration (JPEG/WebP, MP4/WebM/AV1, OGG/Opus etc).

**Comment by Flaburgan** [comment]
WebP support has been considered good engouh now, so with https://github.com/diaspora/diaspora/pull/8358 we not only allow users to upload WebP images, but this is now the default format used to store images in diaspora*. Closing this issue as solved ;)

**Comment by hansw-nlo** [comment]
Wait, after 4 years someone fixes this? :-)

**Comment by hansw-nlo** [comment]
it would even be more great if those users would be able to edit posts and comments :-)

**Comment by tclaus** [comment]
> Wait, after 4 years someone fixes this? :-)

Yes.
