### ISSUE TITLE
error 500 when posting smileys

### ISSUE THREAD

**Issue by georg-h** [diaspora/diaspora#7894]
Hi,
I get error 500 (internal server error) when a comment or a post contain a smiley.
This error happens on

- FF 62.0.3 on win10 
- Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)
(pasting smileys from "Emoji for Chrome" , see attached screens dia_fehlerEla.jpg and error_FF.jpg)
- Android 7.1 with dandelion and Diaspora Native WebApp 

![dia_fehlerela](https://user-images.githubusercontent.com/5622476/46946889-76f22100-d079-11e8-983b-0ace6bb5534a.jpg)
![error_ff](https://user-images.githubusercontent.com/5622476/46946890-76f22100-d079-11e8-9270-c7767523c865.jpg)
When using Chrome on Android 7 it just reloads the page when posting without showing an error but the post isn't stored.

**It works when using Android 8.1** (with dandelion) but these comments/posts don't show up on above mentioned browsers or android 7 devices. They are completely missing in the history. (see attached screenAndroid7.png and screenAndroid8.png

![screenandroid7](https://user-images.githubusercontent.com/5622476/46947230-7908af80-d07a-11e8-8d4a-e0118989b123.png)
![screenandroid8](https://user-images.githubusercontent.com/5622476/46947231-7908af80-d07a-11e8-8c30-f55fba445361.png)

kind regards
Georg

**Comment by Flaburgan** [comment]
Hi @georg-h and thank you for taking time to report an issue!
I guess you are using the pluspora.com pod. There currently is a problem with pluspora database encoding. It already has been reported https://github.com/diaspora/diaspora/issues/7887 and the discussion to solve it will happen [in discourse](https://discourse.diasporafoundation.org/t/help-migrating-a-mysql-database-from-utf8-general-ci-to-utf8mb4-bin/1965/2). You can follow the progress there.
Thank you again.

**Comment by georg-h** [comment]
@Flaburgan you are right. I've checked it with a local post on dia.goexchange.de where it worked without problems. I'll inform my peers. thx
