### ISSUE TITLE
Deleting comment doesn't update counter

### ISSUE THREAD

**Issue by HankG** [diaspora/diaspora#7900]
When deleting a comment in the post view the counter of the number of comments doesn't decrement when the comment is deleted. It does successfully update when the comment is added though.  Before deletion of comment:
![image](https://user-images.githubusercontent.com/1683691/47171374-8d48e880-d2d6-11e8-83eb-eb67cf3e36ca.png)

After deletion but before refresh:
![image](https://user-images.githubusercontent.com/1683691/47171406-9df95e80-d2d6-11e8-86c1-2afcb00cd1b0.png)

After refresh:
![image](https://user-images.githubusercontent.com/1683691/47171431-ab164d80-d2d6-11e8-9cf7-fdbf8dfa1b78.png)

This is true with multiple comments but the whole icon stays with the old count.

**Comment by tclaus** [comment]
Seems to be a javascript / frontend problem. Adding a comment immediately increases the counter. Maybe I take this.

**Comment by tclaus** [comment]
In file 'model/post/interaction.js' there is a comment function with a line
`self.set({"comments_count": self.get("comments_count") + 1});`
I think we need a file "delete/interactions" and a 'removeComment' function with a line
`  self.set({"comments_count": self.get("comments_count") - 1})`;

No clue if this is an easy task or if it is even desirable.

**Comment by HankG** [comment]
@tclaus I'm not as familiar with the front end code but have dabbled in it so wanted to give an idea of what I found and would look into next.  In the comment_stream_view.js is where the append/remove bindings are (in setupBindings).  The remove binding points to the CommentStream.removeComment method in the same class.  That should fire after the model is updated to remove a post, so is the equivalent of the success path.  In the CommentStream.presenter method you can see where the model interactions with commentCount appear from a read perspective, showing how to get to that data object with that information.  

What I would attempt to do is update the removeComment method to make sure the update event is triggered.  I think the data in the comments collection should already be updated, otherwise the removeComment method wouldn't have fired.  I'd confirm that by putting a break point in and playing with it.  After that it's a question of the respective control not getting the update event.  Perhaps there needs to be an interaction like forceRefresh or something on the interactions.js.  which invokes the `self.trigger("change");` like you see in the various interactions methods.  That may be too kludgy even if it works but that'd be how I'd try to approach it.

**Comment by tclaus** [comment]
Created #7938 
Updated the removeComment in comment_stream_view.js to update counter after the second remove event appears. First event removes the comment itself, second removes the part with the 'deleting' -class

**Comment by tclaus** [comment]
There are Unit Tests requested but I struggle with the Jasmine tests. Can someone assist me or take over?

**Comment by denschub** [comment]
Resolved with #7938.
