### ISSUE TITLE
Idea: Requirements for the future

### ISSUE THREAD

**Issue by 001101** [diaspora/diaspora#7901]
Hello my Diaspora friends,

as Diaspora will grow in the future and bringing more content, it also offers big risks for podmins determine what content they are serving from their pod, so I just got the idea that there should be some options to prevent abusing the network.

1. Posts must have a tag, this is elementary to built a stream which suits your needs, prevents for unwanted content and semantically the content which is posted right from the start

2. podmins can block content tags from receiving via the Federation and from posting over their pod

greets Kalipus aka 001101

**Comment by MasterOfTheTiger** [comment]
Number two is something I really want for my pod.

**Comment by goobertron** [comment]
Number 1 is definitely something that I would not agree with – forcing users to post content in a certain way.

Again, this is not specific issue about fixing or developing the software. This is a discussion starter, and as such belongs in the [Features and Ideas](https://discourse.diasporafoundation.org/c/features-and-ideas) section of Discourse, not in GitHub. Please once again close this issue and start your discussion in Discourse.

Please read the [GitHub Feature request guidelines](https://wiki.diasporafoundation.org/Feature_request_guidelines), as well as our community guidelines and Code of Conduct, which @denschub posted for you in [the last ticket you opened](/diaspora/diaspora/issues/7891). And *please* use GitHub and Discourse in the way they are intended for from now on.

**Comment by SuperTux88** [comment]
This is an issue tracker for bugs and actionable feature requests. For feature ideas and discussions, please head over to the ["Features and Ideas" section of our discourse](https://discourse.diasporafoundation.org/c/features-and-ideas).
