### ISSUE TITLE
Bug report: Link previews not always working

### ISSUE THREAD

**Issue by Bodhipaksa** [diaspora/diaspora#7908]
Sometimes when I include a link in a post, a preview (thumbnail, headline, text snippet) are appended. Sometimes that doesn't happen. I assume this is a bug of some sort.

It also seems odd that no preview appears when I initially paste the link into the post, unlike in Facebook, G+, etc. I'd like that to happen, but I guess that's a feature request.

**Comment by SuperTux88** [comment]
> I assume this is a bug of some sort.

No, diaspora uses [Open Graph](http://ogp.me/) to create this previews, and it can only create a preview if the website you link to provides this information. So sites which don't get a preview just don't provide the information which are needed for the preview.

> It also seems odd that no preview appears when I initially paste the link into the post

Currently diaspora only queries this information after a post is sent, but there is already a feature request to also show this information in the post preview: #4465

**Comment by Bodhipaksa** [comment]
> No, diaspora uses Open Graph to create this previews, and it can only create a preview if the website you link to provides this information. So sites which don't get a preview just don't provide the information which are needed for the preview.

The articles I'm linking to do use OG. Here's [an example of a post](https://pluspora.com/posts/45c31e90bb570136b86300505608f9fe) where a preview hasn't displayed: 

And the [linked article](https://www.globalresearch.ca/the-empty-brain/5646021) has og properties specified. According to what you say it should therefore generate a preview.

So, again, this seems to be a bug.

**Comment by SuperTux88** [comment]
Yes, it contains opengraph in the browser, but when diaspora tries to get this URL (and also when you just use `curl https://www.globalresearch.ca/the-empty-brain/5646021 -v` on the terminal) you just get a 403, where obviously now information is included. So it's still not a bug in diaspora, this site is simply blocking some requests.

It looks like it's based on the user-agent, so this works:
`curl 'https://www.globalresearch.ca/the-empty-brain/5646021' -H 'User-Agent: Mozilla/5.0 foobar' -v`
but this doesn't work:
`curl 'https://www.globalresearch.ca/the-empty-brain/5646021' -H 'User-Agent: foobar' -v`

If you know this site, you can ask them why they do that and if they could allow all user agents, but there is nothing else we can do.

**Comment by Bodhipaksa** [comment]
Thanks for the clarification. I have no connection with the site, but I'll let them know they have a problem.
