### ISSUE TITLE
Add line mentioning diaspora* on the splash page

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#7910]
It turns out that a lot of confusion that people coming over from G+ have had understanding that diaspora* is a federated network with lots of different nodes is because the line on the splash page that they reach says, in big letters:

> # Welcome to pluspora
> #### The online social world where you are in control

We show only the pod name there, which does not necessarily have any relation to the diaspora\* name.

To remove at least this point of confusion, I'd like to add the following line between them:

> #### Part of the diaspora\* federated network

Linked to https://diasporafoundation.org/

So that the page reads:

> # Welcome to %{pod_name}
> #### Part of the [diaspora\* federated network](https://diasporafoundation.org/)
> #### The online social world where you are in control

Everyone OK with this?

**Comment by Flaburgan** [comment]
@gooberton do you want to jump in and do it? You now have a docker image to easily set up a dev environment ;)

**Comment by goobertron** [comment]
Not for a couple of weeks, at least. There's too much else going on. Maybe after that, if no one else has. I guess it would be a good incentive for me to try that Docker image to finally get my local install working again!
