### ISSUE TITLE
Dev-Docker: Mismatch between the exposed port and `url` config

### ISSUE THREAD

**Issue by denschub** [diaspora/diaspora#7927]
The dev docker container exposes diaspora to port `8080`, but the default `url` config is `http://localhost:3000/`. This causes issues, for example when uploading images, as the URL will be prefixed with `http://localhost:3000/`, which ain't workin.

We have two options here: One is to change the port we run to 3000, the second one is to modify `diaspora.yml`.

**Comment by SuperTux88** [comment]
I think changing the port to 3000 would be better, because if there is already a `diaspora.yml`, it probably would already be 3000, and we don't want to change/overwrite existing configs.

**Comment by denschub** [comment]
Yes.
