### ISSUE TITLE
Profile name and pictures are public

### ISSUE THREAD

**Issue by ita1024** [diaspora/diaspora#7945]
On Diaspora* 0.7.8, any profile is accessible to all (in particular to non-logged users) using a URL such as:  `/u/name@podname.domain`

This URL is easy to brute-force/guess and anonymous access is granted, despite having unchecked the box `"Allow for people to search for you within diaspora*"`.

I believe that this is important to limit profile visibility to only friends when the checkbox is unchecked, and/or to make it clear that the profile (name, surname and photo) are public for anyone to access!

**Comment by denschub** [comment]
This is not a bug. See #4330, and the bugs linked in there. Closing as a duplicate of the still-open feature request #4330.
