### ISSUE TITLE
Mobile Web client has no feedback link

### ISSUE THREAD

**Issue by dredmorbius** [diaspora/diaspora#7949]
The Diaspora mobile Web client has no feedback link.

Suggestion:  provide a feedback link, preferably to this Github repository.

From:  <https://joindiaspora.com/posts/a266fa40d636013693740218b79d8c8d> (comments).

Thank you.

**Comment by tory-brown** [comment]
is this assigned to anyone yet, also what excatly is needed? a new page design showing clients feedbacks is that like a testimonial page
