### ISSUE TITLE
Opengraph previews unreliable

### ISSUE THREAD

**Issue by creckord** [diaspora/diaspora#7954]
The Opengraph embed for links in posts is quite unreliable. I frequently cross-post links on several social media channels (d*, mostly Google+, occasionally Twitter or Facebook), and while the other sites embed the OG preview very consistently, with d* it's really hit and miss.

An example: 

https://www.tagesspiegel.de/berlin/escape-rooms-ein-solcher-fall-ist-in-berlin-undenkbar/23831608.html

This has the OG metadata available, even when getting it from the command line with curl or similar, and it renders fine elsewhere, but not in d*.

The problem is exacerbated by the missing OG embed in the post preview (issue #4465). So right now, if having the OG preview matters, the only sane workflow is to first post privately to yourself to see how the post renders, delete and repost publicly.

**Comment by SuperTux88** [comment]
tagespiegel.de doesn't return a `Content-Type: text/html` header when doing a `HEAD` request with `Accept: text/html`, so diaspora (or to be more precise [the opengraph parser](https://github.com/jhass/open_graph_reader) diaspora uses) thinks that this URL doesn't provide html to get the opengraph tags from it. If you know somebody from tagespiegel.de you can ask them to fix that.
