### ISSUE TITLE
Add support for Markdown footnote syntax

### ISSUE THREAD

**Issue by diewald** [diaspora/diaspora#7960]
I added Markdown footnotes to my initial post - and they did not work. That is, I wrote "blah blah[^1]" followed at the bottom of the post with "[^1]: more blahs." This should have created a superscript link "1" after blah, linking to the [^1] at the bottom of the post. The bottom should have looked like "1: more blahs" 

Instead, the original "[^1]" text strings are at both location, looking odd.

Reference used: https://en.support.wordpress.com/markdown-quick-reference/

**Comment by Flaburgan** [comment]
Hi @diewald and thank you for taking time to open an issue!

If someone wants to work on that: diaspora* uses an external library to parse markdown: https://github.com/markdown-it/markdown-it. Some specific syntaxes like the foot notes are dealt with by external plugins. To support it, we would need to add https://github.com/markdown-it/markdown-it-footnote to diaspora*. See the plugins already added in [the Gemfile](https://github.com/diaspora/diaspora/blob/develop/Gemfile#L110)

**Comment by tclaus** [comment]
@denschub 
To fix this 'https://github.com/markdown-it/markdown-it-footnote' should be added to https://gems.diasporafoundation.org before it can be added to gem file and 
Maybe fussilicode fails on this?

Buy the way: markdown-it is currently at version 12.x and some plugins also updated.

**Comment by denschub** [comment]
> To fix this 'https://github.com/markdown-it/markdown-it-footnote' should be added to https://gems.diasporafoundation.org before it can be added to gemfile.

Done, `rails-assets-markdown-it-footnote (3.0.3)` now exists. If you need a different version, do let me know.

> Buy the way: markdown-it is currently at version 12.x and some plugins also updated.

If you're serious about updating other asset gems - and I shall warn you: that's going to be an annoying and painful process - then please reach out to me in private (check [here](https://overengineer.dev/me/card.html) for all available channels) and I can walk you through building asset gems locally to test things.
