### ISSUE TITLE
Sign up: specify that space isn't allowed for username

### ISSUE THREAD

**Issue by SansPseudoFix** [diaspora/diaspora#7965]
Hello.

Right now, when you try to sign up, is specified:

> Pick a username (only letters, numbers, and underscores)

but users sometimes use space but nothing indicate what's wrong.

Maybe add:

> Pick a username (only letters, numbers, and underscores; no space)

Can be even better to use popover like email's one, though.

**Comment by HankG** [comment]
I know I can try this but does it fail noticeably if they put a space in the name or does it do something else?

**Comment by SuperTux88** [comment]
Well, "only letters, numbers, and underscores" includes "no space", because a space is neither a letter nor a number nor a underscore. We also don't say "no minus, no point, no slash, no backslash, no quote, no ...". The current list of allowed chars should be clear enough (and everything else is not allowed).

**Comment by goobertron** [comment]
> Well, "only letters, numbers, and underscores" includes "no space", because a space is neither a letter nor a number nor a underscore. We also don't say "no minus, no point, no slash, no backslash, no quote, no ...". The current list of allowed chars should be clear enough (and everything else is not allowed).

This is my feeling about this as well. We'd end up specifying each character that isn't allowed. I think it's clear enough as it is.

The warning defaults to the browser language, which means that in most cases at least it'll be displayed in the language with which the user is most comfortable. So it shouldn't be a language issue.

If there really is a perceived need to make this more explicit, perhaps there could be an addition to the warning based on the character entered. If someone includes a space:

> Pick a username (only letters, numbers, and underscores)
> You need to remove the space from your username

**Comment by SuperTux88** [comment]
> If there really is a perceived need to make this more explicit, perhaps there could be an addition to the warning based on the character entered.

We use a browser-feature here, we define a format that needs to be matched and a message that's displayed when it doesn't match, then the browser does all the validating. So we can't display a message based on what's entered, or we would need to do everything ourselves.

But I really think that it's clear enough to mention what's allowed and not list everything that is not allowed, so I close this issue.
