### ISSUE TITLE
Prepare DB for MySQL8

### ISSUE THREAD

**Issue by tferreira** [diaspora/diaspora#7969]
Hello!

As MySQL8 is coming with lots of performance improvements, I wanted to check wether it would be complicated or not to migrate our Diaspora DB.
MySQL actually released a script on their recent `mysql-shell` tool to check if our 5.7 servers are ready for in-place upgrade:
`mysqlsh root@localhost:3306 -p -e "util.checkForServerUpgrade();"`

The only warning raised (even if it's not on a critical table and won't be an issue) looks pretty simple to fix:
```
3) Usage of utf8mb3 charset
  Warning: The following objects use the utf8mb3 character set. It is
    recommended to convert them to use utf8mb4 instead, for improved Unicode
    support.
  More information:
    https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8mb3.html

  diaspora_production.ar_internal_metadata.key - column's default character
    set: utf8
```

Is this something the community is already talking about ? Do you guys think it would be okay to try a migration like that ?

Thank you!

**Comment by Flaburgan** [comment]
We migrated all tables to utf8mb4 in 2015. The migration file now has been removed but you can read it [here](https://github.com/diaspora/diaspora/pull/5865/files). I don't know Active Record enough to now if that table wasn't there at that time or if it was included as it is an internal table.

So we need to investigate to know if this column charset can be safely changed, or simply ignore the warning as it's not a table manage by ourselves, so if AR team didn't migrate it then it's fine to keep it like that.

**Comment by tferreira** [comment]
Thanks for the answer, so I think it's okay to give it a try.
I'll do very soon an in-place upgrade of MySQL on a replica of my prod database and check if it's running fine.

**Comment by Flaburgan** [comment]
Thank you for testing that, I look forward to see the results :)

**Comment by tferreira** [comment]
I just imported a dump of my database on a test server running MySQL 5.7 under Ubuntu Xenial 16.04, and tried one of the long-running queries to display my feed:

```
mysql> (SELECT DISTINCT posts.id, posts.updated_at AS updated_at, posts.created_at AS created_at FROM `posts` LEFT OUTER JOIN share_visibilities ON share_visibilities.shareable_id = posts.id AND share_visibilities.shareable_type = 'Post' WHERE `posts`.`author_id` IN (1229, 3549, 14842, 1294, 38317, 43077, 35659, 3, 4, 5, 6, 7, 8, 9, 22, 25, 28, 74, 87, 96, 2388, 61, 2582, 410, 417, 3312, 3003, 3013, 2079, 124, 1849, 822, 129, 3799, 4089, 4037, 3322, 4396, 718, 133, 764, 1829, 355, 1534, 1702, 192, 288, 4397, 522, 4398, 581, 59, 4399, 47, 4400, 381, 738, 4155, 4401, 554, 4402, 602, 4583, 3824, 5798, 6396, 6919, 1612, 7294, 872, 7545, 7730, 8443, 158, 10512, 10631, 10507, 10262, 10862, 6665, 10953, 11070, 11542, 12141, 5234, 3061, 2359, 10108, 10497, 9507, 12030, 12639, 11909, 14476, 8101, 10711, 6351, 13463, 13474, 14473, 2533, 14498, 10223, 3565, 19330, 21010, 21745, 32134, 13206, 32467, 15835, 9109, 109, 12618, 34033, 34042, 34966, 34842, 12695, 36035, 35298, 33095, 32963, 32720, 32713, 31172, 31279, 38346, 23279, 39026, 38688, 19747, 6812, 37475, 1282, 3347, 3207, 8495, 31840, 273, 5817, 4593, 214, 17606, 23284, 14999, 36276, 6148, 7326, 7327, 7328) AND (`share_visibilities`.`user_id` = 1 AND `share_visibilities`.`shareable_type` = 'Post' AND `share_visibilities`.`hidden` = 0 OR `posts`.`public` = 1) AND `posts`.`type` IN ('StatusMessage', 'Reshare') AND (`posts`.`created_at` < '2019-01-24 18:49:53') ORDER BY posts.created_at DESC LIMIT 15) UNION ALL (SELECT DISTINCT posts.id, posts.updated_at AS updated_at, posts.created_at AS created_at FROM `posts` WHERE `posts`.`author_id` = 1 AND `posts`.`type` IN ('StatusMessage', 'Reshare') AND (`posts`.`created_at` < '2019-01-24 18:49:53') ORDER BY posts.created_at DESC LIMIT 15) ORDER BY created_at DESC LIMIT 15;

15 rows in set (13.31 sec)
```

Then I installed MySQL 8 using Percona's recommendations (see: [Installing MySQL 8.0 on Ubuntu 16.04 LTS in Five Minutes](https://www.percona.com/blog/2018/05/14/installing-mysql-8-on-ubuntu-16-04-lts/).

I replaced configuration files by the new ones when installing. Then I copy-pasted my old 5.7 configuration settings, and obviously starting the MySQL server failed.
I recommend to remove all deprecated or useless config options by checking this page, listing all removed options: [Options and Variables Removed in MySQL 8.0](https://dev.mysql.com/doc/refman/8.0/en/added-deprecated-removed.html#optvars-removed)

This was enough to start the server. Then I noticed a `show databases;` was failing:
```
mysql> show databases;
ERROR 1449 (HY000): The user specified as a definer ('mysql.infoschema'@'localhost') does not exist
```

I found how to fix it here: [StackOverflow - MySQL 8 error](https://stackoverflow.com/questions/49992868/mysql-errorthe-user-specified-as-a-definer-mysql-infoschemalocalhost-doe), which is basically running a `mysql_upgrade` cmd.

The same query now running MySQL 8.0.14:

```
mysql> (SELECT DISTINCT posts.id, posts.updated_at AS updated_at, posts.created_at AS created_at FROM `posts` LEFT OUTER JOIN share_visibilities ON share_visibilities.shareable_id = posts.id AND share_visibilities.shareable_type = 'Post' WHERE `posts`.`author_id` IN (1229, 3549, 14842, 1294, 38317, 43077, 35659, 3, 4, 5, 6, 7, 8, 9, 22, 25, 28, 74, 87, 96, 2388, 61, 2582, 410, 417, 3312, 3003, 3013, 2079, 124, 1849, 822, 129, 3799, 4089, 4037, 3322, 4396, 718, 133, 764, 1829, 355, 1534, 1702, 192, 288, 4397, 522, 4398, 581, 59, 4399, 47, 4400, 381, 738, 4155, 4401, 554, 4402, 602, 4583, 3824, 5798, 6396, 6919, 1612, 7294, 872, 7545, 7730, 8443, 158, 10512, 10631, 10507, 10262, 10862, 6665, 10953, 11070, 11542, 12141, 5234, 3061, 2359, 10108, 10497, 9507, 12030, 12639, 11909, 14476, 8101, 10711, 6351, 13463, 13474, 14473, 2533, 14498, 10223, 3565, 19330, 21010, 21745, 32134, 13206, 32467, 15835, 9109, 109, 12618, 34033, 34042, 34966, 34842, 12695, 36035, 35298, 33095, 32963, 32720, 32713, 31172, 31279, 38346, 23279, 39026, 38688, 19747, 6812, 37475, 1282, 3347, 3207, 8495, 31840, 273, 5817, 4593, 214, 17606, 23284, 14999, 36276, 6148, 7326, 7327, 7328) AND (`share_visibilities`.`user_id` = 1 AND `share_visibilities`.`shareable_type` = 'Post' AND `share_visibilities`.`hidden` = 0 OR `posts`.`public` = 1) AND `posts`.`type` IN ('StatusMessage', 'Reshare') AND (`posts`.`created_at` < '2019-01-24 18:49:53') ORDER BY posts.created_at DESC LIMIT 15) UNION ALL (SELECT DISTINCT posts.id, posts.updated_at AS updated_at, posts.created_at AS created_at FROM `posts` WHERE `posts`.`author_id` = 1 AND `posts`.`type` IN ('StatusMessage', 'Reshare') AND (`posts`.`created_at` < '2019-01-24 18:49:53') ORDER BY posts.created_at DESC LIMIT 15) ORDER BY created_at DESC LIMIT 15;
15 rows in set (0.06 sec)
```

I'm pretty sure that it's just about the way the MySQL engine is using the indexes and stuff, and we can't just compare such a specific query, but this looks very interesting!

I'll probably test it on my pod this week.

**Comment by denschub** [comment]
Everything is "prepared" for MySQL 8 as there isn't anything you need to do for it to be MySQL 8 compatible.

The warning about utf8mb3 only affects the ActiveRecord's internal tables, because as @Flaburgan pointed out, we migrated all tables containing actual data to mb4 a long time ago. ARs metadata table is, in production, only accessed on startup, so even if there were a performance hit for that, we wouldn't care. Also, given it's an AR metadata table, the chance for non-ASCII data to be in there is more than unlikely (for example, migrations can't have non-ASCII chars in their names anyway, because funny things happen if they do - unrelated to the database).

Because it's an AR-internal table that is managed by AR and irrelevant to our application logic, there is no reason to manually mess with those tables.

If you find an issue where something within diaspora fails because of MySQL 8, please open dedicated issues for each problem you face, so we can work on those.
