### ISSUE TITLE
Change privacy of old posts

### ISSUE THREAD

**Issue by mtbaddict** [diaspora/diaspora#7970]
I need to be able to change privacy of previous posts, like edit privacy feature.

**Comment by goobertron** [comment]
Can't be done. This is by design, and won't be changed.

**Comment by denschub** [comment]
There are multiple discussions on Discourse, [this one seems to be the most active](https://discourse.diasporafoundation.org/t/reshare-old-posts-with-new-contacts/600). As far as I can tell, there is no general agreement on whether we should do it or not, and if so, how. If you have an opinion that's not yet covered by the Discourse thread linked above, please contribute there. :)

If we eventually decide this is a feature we want, and we have an idea on how it should look like, we can open an issue on GitHub to track its implementation.
