### ISSUE TITLE
CC-BY-ND 2.0 License is not compatible with DFSG

### ISSUE THREAD

**Issue by utkarsh2102** [diaspora/diaspora#7972]
Hi,

While packaging diaspora for Debian repositories, it was found that the file dandelion.jpg (https://github.com/diaspora/diaspora/blob/develop/graphics/README.md) is licensed under `CC-BY-ND 2.0` which is not compatible with DFSG (Debian Free Software Guidelines).

So to fix that, there are following two possible ways:
1. Either, someone among us recreates the picture and use it instead of the one being used now.
2. Or, we ask the original author to change the license.

Amongst the two, I strongly believe that 1st workaround is pretty much doable.

Would like to hear your thoughts on the same.
Also, this requires an urgent fix. Hence, expecting to hear from you asap :)

**Comment by utkarsh2102** [comment]
@jhass @SuperTux88,  thoughts?

**Comment by Flaburgan** [comment]
Thank you for reporting this issue. Can you please try to contact the original author and see if he's willing to change the licence?

**Comment by utkarsh2102** [comment]
@Flaburgan or how about I create a similar picture using Photoshop and license it under MIT? :P

**Comment by utkarsh2102** [comment]
Hope that would suffice?
If so, I shall make the PR today itself. Do let me know :)
