### ISSUE TITLE
.well-known webfinger doesn't accept full profile URL

### ISSUE THREAD

**Issue by MrPetovan** [diaspora/diaspora#7982]
https://diaspora.koehn.com/.well-known/webfinger.xml?resource=bkoehn@diaspora.koehn.com gives the following output:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<XRD xmlns="http://docs.oasis-open.org/ns/xri/xrd-1.0">
  <Subject>acct:bkoehn@diaspora.koehn.com</Subject>
  <Alias>https://diaspora.koehn.com/people/349ab82134669a3b</Alias>
  <Link rel="http://microformats.org/profile/hcard" type="text/html" href="https://diaspora.koehn.com/hcard/users/349ab82134669a3b"/>
  <Link rel="http://joindiaspora.com/seed_location" type="text/html" href="https://diaspora.koehn.com/"/>
  <Link rel="http://webfinger.net/rel/profile-page" type="text/html" href="https://diaspora.koehn.com/u/bkoehn"/>
  <Link rel="http://schemas.google.com/g/2010#updates-from" type="application/atom+xml" href="https://diaspora.koehn.com/public/bkoehn.atom"/>
  <Link rel="salmon" href="https://diaspora.koehn.com/receive/users/349ab82134669a3b"/>
  <Link rel="http://ostatus.org/schema/1.0/subscribe" template="https://diaspora.koehn.com/people?q={uri}"/>
  <Link rel="http://openid.net/specs/connect/1.0/issuer" href="http://diaspora.koehn.com/"/>
</XRD>
```

While this URL https://diaspora.koehn.com/.well-known/webfinger.xml?resource=https://diaspora.koehn.com/u/bkoehn gives a 404 error since Feb 16th

This makes all the contact update operation fail, which ends up automatically hiding the contact in Friendica.

https://diaspora.koehn.com/nodeinfo/2.0 reports:
```json
{
  "version": "2.0",
  "software": {
    "name": "diaspora",
    "version": "0.7.9.0"
  },
  "protocols": [
    "diaspora"
  ],
  "services": {
    "inbound": [],
    "outbound": [
      "twitter",
      "tumblr",
      "wordpress"
    ]
  },
  "openRegistrations": true,
  "usage": {
    "users": {
      "total": 863,
      "activeHalfyear": 264,
      "activeMonth": 72
    },
    "localPosts": 15128
  },
  "metadata": {
    "nodeName": "diaspora.koehn.com",
    "xmppChat": false,
    "camo": {
      "markdown": false,
      "opengraph": false,
      "remotePods": false
    },
    "adminAccount": "bkoehn"
  }
}
```

Parallel issue open on https://github.com/friendica/friendica/issues/6760

## Additional example

Success: https://pod.mttv.it/.well-known/webfinger.xml?resource=lorenzoancora@pod.mttv.it
Failure: https://pod.mttv.it/.well-known/webfinger.xml?resource=https://pod.mttv.it/u/lorenzoancora
NodeInfo: https://pod.mttv.it/nodeinfo/2.0
```json
{
  "version": "2.0",
  "software": {
    "name": "diaspora",
    "version": "0.7.9.0-p1edcb001"
  },
  "protocols": [
    "diaspora"
  ],
  "services": {
    "inbound": [],
    "outbound": []
  },
  "openRegistrations": true,
  "usage": {
    "users": {
      "total": 235,
      "activeHalfyear": 92,
      "activeMonth": 33
    },
    "localPosts": 298,
    "localComments": 656
  },
  "metadata": {
    "nodeName": "pod.mttv.it",
    "xmppChat": false,
    "camo": {
      "markdown": false,
      "opengraph": false,
      "remotePods": false
    },
    "adminAccount": "mitja"
  }
}
```

**Comment by MrPetovan** [comment]
Ha, never mind, we try a bunch of different Webfinger calls, but my log only show HTTP errors at the moment.

**Comment by denschub** [comment]
Yeah. :)

Just for the record, I don't think we ever supported the profile URL in webfinger, because it's not the actual account identifier. [Per spec](https://diaspora.github.io/diaspora_federation/discovery/webfinger.html), we only support `/.well-known/webfinger?resource=acct:alice@example.org`, and although it appears to work without the `acct:` prefix, you shouldn't rely on it.

Also, the XML version is technically still working, but it has been deprecated for ages, was never part of the spec, and will eventually stop working.

**Comment by MrPetovan** [comment]
For the XML version, we probe https://diaspora.koehn.com/.well-known/host-meta first, and the result is 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<XRD xmlns="http://docs.oasis-open.org/ns/xri/xrd-1.0">
  <Link rel="lrdd" type="application/xrd+xml" template="https://diaspora.koehn.com/.well-known/webfinger.xml?resource={uri}"/>
</XRD>
```

**Comment by denschub** [comment]
Huh, you are right. Now, the web-finger spec doesn't actually require `.well-known/host-meta` as it defines `.well-known/webfinger`, so I assume the `host-meta` is part of some larger legacy that will be addressed in the future. However, I actually don't know, and @SuperTux88 is the person who probably already has this in mind. :)

**Comment by annando** [comment]
We are using this URL probing to detect the remote network system. Some do react to probing of the URL. Same is with the ```host-meta``` stuff.

**Comment by SuperTux88** [comment]
Yes, `/.well-known/host-meta` is deprecated too, it belongs to the old pre-RFC-7033-webfinger, but diaspora will only support RFC-7033-webfinger in the future, so it would be better to try that first and only fall-back to pre-RFC-webfinger if that fails.
