### ISSUE TITLE
Watermarked photo not diaplayed in correct portrait orientation

### ISSUE THREAD

**Issue by RoyTheNewbie** [diaspora/diaspora#7986]
I have a problem that _I don't think_ is a duplicate of previous issues.
If I want to display in a post a watermarked photo that is in a portrait orientation it is displayed incorrectly, in landscape orientation. FYI, the Image Viewer that I use in Ubuntu displays it correctly. I use GIMP, the Ubuntu photo app, to insert the watermark.
_The very same photo, if not watermarked, is displayed correctly in pluspora._ 
Can you suggest how I can change my watermarking procedure, to avoid this problem?

https://pluspora.com/uploads/images/scaled_full_a1e622ada0b3b952a48d.JPG

**Comment by denschub** [comment]
You have two options:

* Either rotate the image itself, instead of simply writing the target rotation into the EXIF data; or
* disabling metadata strip from `/privacy` could also help.

**Comment by denschub** [comment]
If it doesn't help, please head over to https://discourse.diasporafoundation.org/c/support - this is probably a support request, and not a bug. :)
