### ISSUE TITLE
Add support for Matrix protocol

### ISSUE THREAD

**Issue by homebeach** [diaspora/diaspora#7988]
Add support for [Matrix protocol](https://matrix.org). Here is corresponding issue in Matrix wishlist: https://github.com/turt2live/matrix-wishlist/issues/67.

**Comment by denschub** [comment]
diaspora\* is a social network, not a instant messaging application. Same arguments as in #7422 do apply, so if anything, we'd have to have a long discussion here. As such, this is not a directly actionable task. If you're feeling strongly, please open a discussion on Discourse.

**Comment by MasterOfTheTiger** [comment]
The only reason I see that Matrix should be supported is as an alternative/replacement for XMPP. That's what you mean, right @homebeach? Otherwise, it doesn't make any sense to support the Matrix protocol.

**Comment by homebeach** [comment]
Matrix has benefits over XMPP and it is also actively developed. So it is worth keeping eye on it.
