### ISSUE TITLE
Android version crashing when sharing

### ISSUE THREAD

**Issue by omniviator** [diaspora/diaspora#7991]
Hello there! I'm surprised nobody in this forum has posted sth on this issue. It's been years now that I cannot share anything from the Web. It keeps crashing as soon as I chose Diaspora to share a link. So I keep manually sharing or not sharing at all because it takes more time than Mastodon that never crashes. Any hints to resolve this would be very appreciated. Warmest greetings, Dimitri 
#bug #mobile #android

**Comment by Flaburgan** [comment]
Hi dimitri! Thank you for taking time to report a problem. The diaspora foundation doesn't provide any official android app. Can you tell us if you are simply visiting your diaspora* pod from a browser, or if you are using an unofficial android application?

**Comment by omniviator** [comment]
Hi Flaburgan! Thanks for answering! I'm probably using the unofficial app. There is a github page bu they don't seem to update anymore : https://github.com/mdev88/Diaspora-Native-WebApp

**Comment by Flaburgan** [comment]
se currently recommend to simply access your pod using a web browser but if you want to use an unofficial app dandelion is currently the best one. You can find it on the f-droid store.

**Comment by omniviator** [comment]
Thank you! :-) I will check that out.
