### ISSUE TITLE
PhantomJS isn't maintained anymore

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#7999]
We use it to run our cucumber tests. It actually prints a lot of warning about CSP properties when running any test:

```
Unrecognized Content-Security-Policy directive 'form-action'.

Unrecognized Content-Security-Policy directive 'frame-ancestors'.

Unrecognized Content-Security-Policy directive 'manifest-src'.

Unrecognized Content-Security-Policy directive 'form-action'.

Unrecognized Content-Security-Policy directive 'frame-ancestors'.

Unrecognized Content-Security-Policy directive 'manifest-src'.

The source list for Content Security Policy directive 'script-src' contains an invalid source: ''nonce-rH0RfdTm7tFMtfDKdqEgnqWdv0NwDZMRaycP1PqBEB=''. It will be ignored.
```
Which makes noise. Those properties are valid but phantomjs engine is old and as it isn't maintained anymore there is no new version coming. We will need to replace it by something else at some point.

**Comment by tclaus** [comment]
Is replaced by Apparition. Could be closed.

**Comment by Flaburgan** [comment]
Thank you for spotting that. Closed by https://github.com/diaspora/diaspora/pull/8234
