### ISSUE TITLE
Inconsistent constraint from HTML5 and model validate function. 

### ISSUE THREAD

**Issue by jwjwyoung** [diaspora/diaspora#8007]
when login, the constraint for username is `[A-Za-z0-9_.@\-]+` https://github.com/diaspora/diaspora/blob/d486fbce8cdfb70ddd30e6f0b7f8f0e07585bf1a/app/views/sessions/_form.haml#L22
But when saving the user, the username has the constraint `/\A[A-Za-z0-9_]+\z/`, https://github.com/diaspora/diaspora/blob/d486fbce8cdfb70ddd30e6f0b7f8f0e07585bf1a/app/models/user.rb#L39, which is different from the login requirement. 

Which is quite confusing, when I login into Diaspora with a username contains '@', they will give the error information saying "your password is incorrect", but the truth is the username doesn't exist at all.

**Comment by SuperTux88** [comment]
You can log in using the mail-address, that's why @ is allowed there.
