### ISSUE TITLE
Improve registration process, give more info to the user

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#8009]
I'm planning to work on improving our registration process. As I have other tasks I need to finish first, I didn't started to work on it "for real" but I wanted to open that issue to not lose what I have in mind and get early feedback.

My target is to:
- Better explain to the subscribers what they are filling and for what purpose
- Indicate more clearly what's public and what's not, what can be changed and what can't
- Have a responsive design, to be ready to drop the mobile version

The idea is to better integrate the "getting started" step and be globally more verbose about what's going on.

Here are some mockups about how I see it (not designed, it's more about the content and the  flow itself)

![Capture d’écran - 2019-05-05 à 13 15 57](https://user-images.githubusercontent.com/930064/57193101-f40eb600-6f37-11e9-9be8-a14dd4ad2123.png)
*Reminder: it is **not** designed*

So what did I do here?
- Remind the users on which pod they are registering by adding the podname in the title and the end of the id (@podurl.tld) next to the id field. This should also help for https://github.com/diaspora/diaspora/issues/3540 and users trying to sign in on wrong pods
- Remove the tooltip which told the email wasn't public as this doesn't work well on mobile
- Display more information about the id, what it is used for, and that it can't be changed
- Display more information about the email, why we ask it

Clicking on the register button will, as it does now, create the account and go to the getting_started page. However, I want to change "getting started" to have the same design than the first registration page, so the user is still in the same flow.

On that second page, we'll find the same fields that we actually have (username, profile pictures), but in the same spirit, with more infos about what's going on. Especially, indicate to the users the visibility of the info they are filling. I still have to think about it but I would like to also deal with https://github.com/diaspora/diaspora/issues/5294 at that point: explaining to the users how diaspora* is tag focused, allowing them to choose their profile tags and the one they want to follow. It would also be a good place to give some links about the help. I don't know if all this should be on the 2nd step or if we need a 3rd one. I'll think about it.

Any other things that should be included in the getting started?

**Comment by SuperTux88** [comment]
> Display more information about the id, what it is used for, and that it can be changed

Well, technically it can be changed with the upcoming migration work, but then only one way (so no rename back to your first username). But I don't think it's the right place to explain how migration works, so I'm fine with how it is at the moment, and we can probably just drop that it can't be changed in the future when it can be changed (with restrictions).
