### ISSUE TITLE
[Feature] Mobile Client

### ISSUE THREAD

**Issue by asddsaz** [diaspora/diaspora#8011]
**Feature**: [FLOSS](https://www.wikipedia.org/wiki/Free_and_open-source_software#FLOSS) [Mobile Client](https://www.wikipedia.org/wiki/Mobile_app) for all major [mobile OSes](https://www.wikipedia.org/wiki/Mobile_operating_system).
(Android, SailfishOS, IOS, Ubuntu Touch, e.c.t)

______

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/73900217-feature-mobile-client)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

**Comment by Flaburgan** [comment]
Hi @asddsaz and thank you for taking time to open an issue. We choose to not develop an native client for diaspora* at the moment, as the web is the platform. However, unofficial clients already exist (like dandelion for Android, available on f-droid). Moreover, an API for diaspora* is almost ready (see https://github.com/diaspora/diaspora/pull/7462) and would allow those tier-party clients to be more than an extended web view.

**Comment by Flaburgan** [comment]
As we're focusing on building a nice mobile experience directly in the browser at the moment and that a discussion about creating a native client should happen [on discourse](https://discourse.diasporafoundation.org/c/features-and-ideas) anyway, I'm closing this issue. We would open a new github repository if we decide to have native apps anyway.
