### ISSUE TITLE
Individual Profile related images shouldn't be kept in Public Folder

### ISSUE THREAD

**Issue by GruLab** [diaspora/diaspora#8013]
The images posted as Individual Login, are saved in Public folder. By getting the image path, it can be accessible without login.

![snap](https://user-images.githubusercontent.com/8300079/57505202-02cce280-7315-11e9-9928-6b2aa7680f2d.jpg)

**Comment by jhass** [comment]
This is essentially a duplicate of #7946. Please follow the reasoning there.
