### ISSUE TITLE
Do not show getting started after account import

### ISSUE THREAD

**Issue by jhass** [diaspora/diaspora#8018]
Make sure to set the flag to false when creating a user from an account migration

**Comment by Flaburgan** [comment]
Why do we want to set it to something else than what was in the DB?

**Comment by SuperTux88** [comment]
There is no "what was in the DB" since it is a "new user", so it sets it to default true (as for new users), but the default doesn't know that this is an imported user, so in that case it should be set to false, which this issue is about.

**Comment by Flaburgan** [comment]
I was talking about the DB of the "from" pod. I thought this info could be in the archive, so can be restored. But I agree in 99.99% it will be false.

**Comment by SuperTux88** [comment]
I think settings aren't exported, and also can't be fully imported, because your target pod maybe doesn't have the same themes as your old pod.

**Comment by Danielshow** [comment]
Hi, @Danielshow here, I am a newcomer and will like to contribute to this project by working on this.

**Comment by jhass** [comment]
Cool, just ask if  you need any pointers :)

**Comment by Danielshow** [comment]
Sure @jhass

**Comment by theRealNG** [comment]
@jhass & @SuperTux88 Can one of you point me where the exact feature to import users from another pod is, i'm unable to find it.

**Comment by SuperTux88** [comment]
The import is currently only a rake task [`accounts:migration`](https://github.com/diaspora/diaspora/blob/develop/lib/tasks/accounts.rake), and since it is neither completely finished nor released yet, it isn't well documented yet.

But @Danielshow also said he wants to work on this, so you should talk to each other before you both start working on this issue.

**Comment by theRealNG** [comment]
@Danielshow are you working on this?

**Comment by Danielshow** [comment]
@theRealNG You can pick it up, finding it hard to set up the projects. I will pick another once I am done

**Comment by Flaburgan** [comment]
@Danielshow use `script/diaspora-dev` to set up a development env easily with docker.

**Comment by Danielshow** [comment]
Thanks, @Flaburgan, I will try that now
