### ISSUE TITLE
[Feature] Diaspora over I2p

### ISSUE THREAD

**Issue by hgjkhg** [diaspora/diaspora#8024]
**Objective**: Enabling Disapora to be used fully over i2p (+ documentation)

**Discussion**: What would it take to run an Diaspora instance with i2p?
Is there an i2p instance for Disapora?

**Why?**: Mainly for privacy and security but also to promote decentralized web communications.

**Related Links:**
https://www.invidio.us/watch?v=2ylW85vc7SA

https://geti2p.net/

https://git.pleroma.social/pleroma/pleroma/wikis/I2P-Federation

https://www.wikipedia.org/wiki/I2p

_____________________

Want to support this issue? Post a bounty on it! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

**Comment by SuperTux88** [comment]
Duplicate of #2243
