### ISSUE TITLE
Add username in "Forgot my password" email

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#8030]
We recently had a user who didn't remember her username. She didn't know she can use her e-mail to log in. She used the "forgot my email" feature hoping for a link to connect. She received the e-mail and changed her password but... she was still not logged in.

So I suggest to add the username in the email to remind it to the user.

**Comment by FeruzOripov** [comment]
Hi! I'm new here. Can you assign this issue to me ?

**Comment by SuperTux88** [comment]
@Flaburgan is already working on this issue, see #8037.

**Comment by FeruzOripov** [comment]
Oh, I see, thanks.

**Comment by SuperTux88** [comment]
This was fixed with #8037 in 0.7.16.0
