### ISSUE TITLE
How are query parameters of stream being generated

### ISSUE THREAD

**Issue by f-person** [diaspora/diaspora#8038]
i want to get all posts from a user but user's post are being displayed with js, so i can't just parse them. but i noticed that there's get request being sent to something like https://pod.url/people/id/stream?_=1561977476530 when opening user's profile in browser. then i sent that request and got 15 first posts as a response text, then when i scrolled down a new get request was sent with the same headers but one new query parameter: max_time=1553429696.417 . can you tell me how are those 2 parameters being generated? Thanks.

**Comment by jhass** [comment]
Please don't abuse this as an API, it's none. As soon as we merge #7462 you'll have a documented stable API to go against.

Anyway. it's just the unix time of the last post in the previous request: https://github.com/diaspora/diaspora/blob/develop/app/assets/javascripts/app/models/stream.js#L68

**Comment by denschub** [comment]
Also, please don't ask in two IRC channels and GitHub at the same time. You will get an answer, there is no reason to spam your question everywhere. ;)
