### ISSUE TITLE
Question: How do you stop people from forking the code and making modifications?

### ISSUE THREAD

**Issue by theRealNG** [diaspora/diaspora#8040]
A developer can fork the repo making modifications that violate privacy or security. He can then deploy this code on a server and join the diaspora community, which in turn affects everyone. How are you people stopping this from happening?

**Comment by denschub** [comment]
> How are you people stopping this from happening?

You don't.

diapsora\* [is licensed under a free and open source license, the GNU Affero General Public License](https://github.com/diaspora/diaspora/blob/e92eb887824046941904749fc6584f312dece80e/LICENSE). The sole point of this license is to **ensure** the code stays free, open, and modifiable for everyone. The only big limitation here, and a quite significant one, is the fact that a podmin who runs modified code **has to** make those modifications available to their users, so they can actually validate those changes, if necessary.
