### ISSUE TITLE
 The specified email address is not listed on your account. 

### ISSUE THREAD

**Issue by leenzh** [diaspora/diaspora#8045]
i have another account and i forget my password and when i want to reset it gives me this error 
can you help me with this

**Comment by denschub** [comment]
Hey! Do you know which pod (which means "which server") you signed up on?

**Comment by leenzh** [comment]
actually i dont know 
but this is what i got
![Capture](https://user-images.githubusercontent.com/45848415/61189270-0d7b5f00-a659-11e9-9609-e220e677e023.PNG)

**Comment by denschub** [comment]
That's GitHub, not diaspora. If you're having trouble with your GitHub account, please contact GitHub at https://github.com/contact.
