### ISSUE TITLE
Photo seems to use ActiveRecord validation API incorrectly

### ISSUE THREAD

**Issue by whoisutsav** [diaspora/diaspora#8048]
Hi,

In app/models/photo.rb, there is the following code:
```rb
validate :ownership_of_status_message
...
def ownership_of_status_message
  message = StatusMessage.find_by_guid(self.status_message_guid)
  if self.status_message_guid && message
    self.diaspora_handle == message.diaspora_handle
  else
    true
  end
end
```
Since this adds nothing to the record's errors array, it is my understanding that the validation result is ignored, since Rails uses the errors array to check if the object is valid or not: https://github.com/rails/rails/blob/7cd414897358c61d9eb3e80b73580a82f6c74d19/activerecord/lib/active_record/validations.rb#L69

The fix is straightforward, I believe (in addition to testing):
```rb
  def ownership_of_status_message
    message = StatusMessage.find_by_guid(self.status_message_guid)
    if self.status_message_guid && message && self.diaspora_handle != message.diaspora_handle
      errors.add(:base, "Photo must have the same owner as status message")
    end
  end
```

Just a small improvement.

Thanks

**Comment by jhass** [comment]
Good catch! Pull request with tests welcome!
