### ISSUE TITLE
Double extension files aren't showing proper error message

### ISSUE THREAD

**Issue by GruLab** [diaspora/diaspora#8054]
**POD Version:** v0.7.10.0

**Steps to reproduce:**
1. Login into the diaspora instance >> Profile >> Edit my profile
2. Click "Upload a new profile photo!"

**Expected behavior:**
Check for double extensions such as ".php.png". Restrict file types accepted for upload: check the file extension, content type and MIME-type and allow only required files types to be uploaded. Use a white-list approach instead of a blacklist. Change the permissions of the upload folder so the files within it are not executable. If possible, rename the files that are uploaded.

**Actual behavior:**
Double extension files aren't showing proper error message.

It exists here also:
https://xx.xxx.xx.xxx/posts
https://xx.xxx.xx.xxx/stream

![2019-09-04_10-14-48](https://user-images.githubusercontent.com/8300079/64227762-508fdb00-cf02-11e9-97a6-92f2e9244262.jpg)

**Comment by jhass** [comment]
I don't understand the issue here. Given your previous posts and continued ignorance to our responsible disclosure process via security@diasporafoundation.org, I suspect you suspect some kind of security related issue. Could you go into more detail?

**Comment by GruLab** [comment]
@jhass I posted here, as it's a functional issue.
Whenever uploading any "double extension file<rename xyz.pdf into xyz.pdf.jpg>", it should show the same error message when a .txt file is uploaded.

**Comment by jhass** [comment]
Well I cannot reproduce any functional issue, uploading an actual image with a double extension works just fine:

<img width="640" alt="Screenshot 2019-09-04 at 10 19 24" src="https://user-images.githubusercontent.com/141294/64237871-8bdbdb00-cefd-11e9-80f3-7143043dd65a.png">

Uploading a text file with the extension `php.png` just hangs indefinitely for me. Which is not great UX but nothing to worry about too much also.

**Comment by GruLab** [comment]
You are using a .png file, try to rename any **xyz.pdf** file into xyz.pdf.png

**Comment by jhass** [comment]
> Uploading a text file with the extension php.png just hangs indefinitely for me. Which is not great UX but nothing to worry about too much also

**Comment by GruLab** [comment]
Then fine @jhass

**Comment by SuperTux88** [comment]
Also, duplicate of #7577 for the hanging frontend (has nothing to do with double extensions).
