### ISSUE TITLE
Field Validation isn't proper

### ISSUE THREAD

**Issue by GruLab** [diaspora/diaspora#8055]
POD Version: v0.7.10.0

Steps to reproduce:
1. Login into the diaspora instance >> Profile >> Edit my profile >> My extended profile 
2. "Your bio", "Your location" & "Your gender" is accepting any character/symbol

Expected behavior:
Blacklisting is an approach which consists of checking the input data for malicious characters but
a more effective approach is whitelisting. Whitelisting consists of only allowing certain characters to be submitted.

Actual behavior:
Input Fields are accepting any character/symbol.

It exists here also:
https://xx.xxx.xx.xxx/stream
https://xx.xxx.xx.xxx/aspects
https://xx.xxx.xx.xxx/followed_tags
https://xx.xxx.xx.xxx/public
https://xx.xxx.xx.xxx/user/edit
https://xx.xxx.xx.xxx/contacts
https://xx.xxx.xx.xxx/admins/user_search

![2019-09-04_10-53-59](https://user-images.githubusercontent.com/8300079/64227901-cdbb5000-cf02-11e9-9f47-7f870d2ed01a.jpg)

**Comment by GruLab** [comment]
"Gender" Field can be a Drop-down.

**Comment by jhass** [comment]
If we render the field without proper XSS escaping or encoding somewhere, please open an issue about that. Otherwise these are intended to be entirely free-form.

**Comment by denschub** [comment]
> "Gender" Field can be a Drop-down.

[No](http://www.sarahmei.com/blog/2010/11/26/disalienation/).
