### ISSUE TITLE
Dead links to deleted users' profiles

### ISSUE THREAD

**Issue by ciubotaru** [diaspora/diaspora#8061]
The "weekly user stats" tab of the admin panel shows users registered during a week and links to their profiles. However, the link is useless in case the user deleted their account. Clicking on such a link just brings up an info message saying the account is deleted. From a usability perspective is would be good to remove links to deleted users, or display their usernames crossed over.

If this issue gets support, I'd volunteer to prepare a tentative PR.

**Comment by SuperTux88** [comment]
I'd say: go for it. As you said, the current behaviour isn't very useful and if you can replace it with something more useful, that's always a good idea :)

**Comment by ciubotaru** [comment]
I opened a PR a while ago. Any chance to see it merged?
