### ISSUE TITLE
Diaspora* embedded youtube links not working.

### ISSUE THREAD

**Issue by richard1234567891** [diaspora/diaspora#8074]
On https://diaspora.flidais.net/ YouTube links vanish after I hit enter. (and of course the embedded video doesn't appear either) that's the problem, embedded videos aren't playing, because now  they aren't even showing up to begin with. Not even the link shows after I hit enter. The only way for me to get the link to show is for me to enter the link in the name "description" of the first link that was entered. but even this just leaves a blue link that once clicking on it will open a new tab directed to that youtube video.

it was working just fine yesterday, (and NO it's not because the author of the video unchecked the box to allow embedding) I know because its my videos that aren't working, and I have those settings checked to allow embedding. Yet since this morning, not mine nor anyone else's youtube videos will even show up 
and yes, the videos do allow for embedding, I checked.

**Comment by goobertron** [comment]
This sounds very much like an issue with either your pod or your browser. You'll need to contact your podmin, if you can find their contact details.

I've just tested it on a couple of pods, and it worked fine. So it's not an issue with the software.

This Github tracker is only for issues with the core diaspora\* software itself, so unless this can be reproduced on other pods, this isn't the place for this issue.

If you can't get in touch with the podmin and want support, try posting in diaspora\*'s Discourse forum: https://discourse.diasporafoundation.org/c/support/

**Comment by richard1234567891** [comment]
Never mind, it's working again now. :)
