### ISSUE TITLE
Not an issue but a support question

### ISSUE THREAD

**Issue by memo-567** [diaspora/diaspora#8078]
Dear diaspora community and developers.

I like to run an own diaspora pod on a debian 10 server but the only install instruction I found, is this very old one for debian 8 server: 

https://wiki.diasporafoundation.org/Installation/Debian/Jessie

Is there somewhere an install instruction which is up to date?

Regards Memo

**Comment by Flaburgan** [comment]
Hi @memo-567 and thank you for using diaspora*!

I personally run the framasphere.org pod on debian 10 without any problem. I indeed upgraded from debian 8 initially, but I think the instruction you linked should mainly work just fine. Please try and ask us if you encounter issues either by joining the #diaspora IRC channel on freenode, or by posting a question on [our forum](https://discourse.diasporafoundation.org) as we don't use github for support.

Thank you again!

**Comment by memo-567** [comment]
> I think the instruction you linked should mainly work just fine. 

Mainly? Doesn't sound very trustworthy 😄

Okay - I'll give it a try these days and it either works - or it doesn't.
