### ISSUE TITLE
Aspects not translated

### ISSUE THREAD

**Issue by beppeben** [diaspora/diaspora#8081]
If I switch to French, I still see the aspect names in English in the UI (that is Family, Work, Acquaintances). It seems strange as they appear to be translated correctly in the fr.yml file (for example there is an entry acquaintances: "Connaissances"). Any idea why that happens?

**Comment by SuperTux88** [comment]
The default aspects are created on signup with the language you had on signup. After an aspect is created it has a fixed name, and we don't change names of your aspects when you switch langauges. But you can just rename them or create aspects with names you want, the four default aspects are just an example.
