### ISSUE TITLE
Create a connector in Zapier platform

### ISSUE THREAD

**Issue by madvik** [diaspora/diaspora#8110]
Hello,

I want to post on diaspora with zapier, but I can't find a connector in the zapier's library.
I try to create on zapier platform this connector. 
But I don't have enough knowledge on Rest-API for build-it.
Must it create a diaspora's service for it ?
thx

**Comment by jhass** [comment]
Looking at https://platform.zapier.com/docs/auth it looks like they don't support OpenID Connect with dynamic client registration, which would be needed for the upcoming (not in a release yet) diaspora* API. 

This  means you would need a centrally hosted bridge application which users can sign up to using their diaspora* account through OpenID Connect. Then that application could provide a classic oAuth (2) interface to Zappier. With a bit of work this probably could be integrated into a quite seamless flow, where the sign up to the gateway application using OpenID Connect is integrated into the authentication and authorization flow with Zappier.
