### ISSUE TITLE
API: undefined method `map' when trying to create a conversation

### ISSUE THREAD

**Issue by DeadSuperHero** [diaspora/diaspora#8116]
Hey there! I'm following along with the Diaspora API docs. So far, they work pretty well, but I'm hitting a snag with trying to [create a new conversation](https://diaspora.github.io/api-documentation/routes/conversations.html).

Basically, I'm doing a POST request that looks like this: 

```
0.0.0.0:3000/api/v1/conversations?subject=Hello&recipients=10bd9110573d01385fab2ce0106b0125&body=Hi
```

`subject` is "Hello"
`recipients` is "10bd9110573d01385fab2ce0106b0125"
`body` is "Hi"

Doing this results in a 500 error, with the message ```undefined method `map' for \"10bd9110573d01385fab2ce0106b0125\":String\nDid you mean?  tap```

Gut-checks:
- My app has access to the `conversations` scope
- I'm correctly authorized
- I know for certain that the `recipients` value is correct, as it matches the `person_guid`

Am I doing something wrong here, or is something not working?

**Comment by DeadSuperHero** [comment]
I thought perhaps a mistake I made was that maybe new conversations also require to have the sender as a recipient in the conversation?

So, I tried settings `recipients` to an array: `recipients=["c4d5759056d70138264d2ce0106b0125", "10bd9110573d01385fab2ce0106b0125"]`, but I still ended up with ```undefined method `map' for #<String:0x00007f2da7853d48>\nDid you mean?  tap```

**Comment by DeadSuperHero** [comment]
Curiously, the methods for reading and updating existing conversations and parsing the message contents works without issue. I'm just stuck on creating new conversations.

**Comment by denschub** [comment]
Our API works by POST'ing JSON payloads, not by specifying URL parameters. Please POST JSON, and don't try what you're trying - there is no guarantee that will work, and it's not how we designed the API to work.

**Comment by DeadSuperHero** [comment]
Hmmm, this seems to be a shortcoming in how I've set Postman up. Thanks for the pointer, I'll double-check the tool documentation when I get home! 😅
