### ISSUE TITLE
Mobile app crash at startup on Android 9.1.0.38

### ISSUE THREAD

**Issue by sylock** [diaspora/diaspora#8117]
On my smartphone with android 9.1.0.38 the application crash at startup. When going to the task manager of android to switch between applications, I see that the app is still opened, and see the beginning of the title of the page: select... But I cannot do anything. If I click on the app to give it the focus, it disappear from my screen after a few seconds. On the android playstore, I can see that other users with version 9 of Android have the same issue.

**Comment by MasterOfTheTiger** [comment]
This is the repository for the diaspora* software itself. It comes with no official app. If you are referring to the dandelion* app that is available to use diaspora*, this is not the right place to report the bug. Here is the [issue tracker for dandelion](https://github.com/gsantner/dandelion/issues) if that is what you are looking for.
