### ISSUE TITLE
Unnecessary subquery makes query slow

### ISSUE THREAD

**Issue by wtune** [diaspora/diaspora#8120]
From Database Log we found a slow query(561175 Nanosecond) with redundant subquery produced by [user_methods.rb#L34](https://github.com/diaspora/diaspora/blob/002d427f34170afc21d5ba38252536dbf2c8d8f3/spec/support/user_methods.rb#L34) as follows:
```
SELECT 
  `aspects`.* 
FROM 
  `aspects` 
WHERE 
  `aspects`.`user_id` = 1 
  AND `aspects`.`id` IN (
    SELECT 
      `aspects`.`id` 
    FROM 
      `aspects` 
    WHERE 
      `aspects`.`user_id` = 1 
    ORDER BY 
      order_id ASC
  ) 
ORDER BY 
  order_id ASC

```
It's obvious this subquery is redundant and we should remove it as shown below:
```
SELECT 
  `aspects`.* 
FROM 
  `aspects` 
WHERE 
  `aspects`.`user_id` = 1 
ORDER BY 
  order_id ASC
```
According to our tests this can improve the performance of query by 18%(from 561175 to 456319 Nanosecond).

**Comment by jhass** [comment]
Huh, you would expect the optimizer to optimize something like that easily, no?
