### ISSUE TITLE
Distributed or Decentralized?

### ISSUE THREAD

**Issue by maverick74** [diaspora/diaspora#8124]
In some places it is mentioned diaspora is Distributed, in others it is mentioned it is Decentralized.

Since there is actually a difference, which one is it? 

Distributed or Decentralized?

**Comment by jhass** [comment]
Well, the terms are pretty vague and up to interpretation honestly.

Diaspora uses a federated model like E-Mail or XMPP does for example, so it's not a peer-to-peer network where each individual user participates in the message exchange. Instead you sign up like you would sign up to an installation of the software like you would for any normal website or E-Mail provider.

**Comment by maverick74** [comment]
So, that means it is actually more kind of "decentralized" than "distributed"?

There are a few articles about this on the web. Most, like you said, are a bit vague...

**Comment by jhass** [comment]
I really don't want to get into a debate about the definition of the terms really, sorry.

If there's something unclear about how Diaspora works still, I'm happy to answer to that.

**Comment by maverick74** [comment]
No, no debates for me either. Thank You! :) They usually end up right where they started, with no conclusions and a bunch of people "mad" about them. ahaha.

About diaspora, from what i get, there's still the need from servers somewhere, right? 
I mean, it's not as easy as just 2 persons connected to each other with no dedicated server between them...

**Comment by jhass** [comment]
Yes, same as  E-Mail. You sign up at some provider (diaspora's brand terminology here is pod), which provides a server. That gives you a user ID that looks just like an E-Mail address,  `yourname@your_provider_domain`. Just like with E-Mail you could spin up your own instance on some server somewhere and just like with E-Mail it's something you should only do with some experience in administering servers.

**Comment by maverick74** [comment]
OK, understood :). 

Thank you for clarifying it to me :).

You can close the issue if you want to.
