### ISSUE TITLE
CORS issues running api/v1

### ISSUE THREAD

**Issue by valdahus** [diaspora/diaspora#8126]
Hi,

So I'm using a dev-server of diaspora 0.8.0.0 hosted on a ec2 aws instance. 

I did modify this file/config:
https://github.com/diaspora/diaspora/blob/develop/config/initializers/cors.rb

By adding:
resource "/api/v1/*", methods: %i(delete get post)

But when I run my webb-app I'm still getting CORS issues.
Is there any other settings that I need to enable to allow all domains to access the new API? The webbapp is running from my localhost (domain is localhost).

**Comment by denschub** [comment]
Make sure you actually see the CORS headers on the request. It's possible that those headers get eaten by your reverse proxy's configuration (apache/nginx) or some load-balancer in front of it.

**Comment by valdahus** [comment]
I installed Diaspora from the wiki-guide on Ubuntu (16).
Did not config any proxy on front. On the AWS, I'm just using an EC2 instance, meaning there is no proxy-solution in front of it.

The other request from that file works fine, like "/.well-known/openid-configuration" (GET) works fine. But anything to /api/v1 fails due CORS.

**Comment by denschub** [comment]
You're actually right, we don't actually set CORS headers for the new API endpoints. So far, nobody did notice this since our test clients are native applications, but we should absolutely fix that.

**Comment by denschub** [comment]
This should be fixed in the current `develop` branch. Give it a try, and let us know if it doesn't work!
