### ISSUE TITLE
Rename "master" branch to "stable"

### ISSUE THREAD

**Issue by denschub** [diaspora/diaspora#8128]
There's no reason why we need to stick with git's default terminology here, especially since it's a loaded term, and in our case actually misleading. I suggest renaming it to "stable" or something similarly descriptive, because that's actually more akin to what our workflow actually looks like. We probably should also do a global sweep in our codebase to check for other terms we shouldn't be using.

Because we tell people to install their production pods by cloning the git repo, this has to wait for a major release, because it requires manual interaction from podmins (mainly changing the default branch). Other than that, though, we should be fairly good, with the exception of a couple manual steps:

- [ ] Adjust all mentions in the documentations, especially installation docs, but also docs explaining our Git workflow
- [ ] Adjusting CI configs
- [ ] Adjusting the build scripts on `starsupport` to allow-list the `stable` branch for codestyle checks.

We already have `develop` set as the default branch on GitHub and for checkouts, so that's good. Also, there should be no stale PRs opened against the default branch, so that shouldn't really affect us in any way.

Unfortunately, we cannot do the same switch for some of our other repos, like the `diaspora_federation` repo, because we use GitHub pages there, [and there is no way to use another branch besides `master` for in-tree pages](https://help.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site), unfortunately. Let's hope this will get addressed soon.

**Comment by denschub** [comment]
Note that the best way to transition is probably during the 0.8.0.0 release, where we have the chance to keep the `master` branch around for a couple of weeks with the outdated 0.7.x.x code, while explicitly forcing people to switch branches in our 0.8.0.0 upgrade guide. People have to read those for a major update anyway, and switching the branch while you do manual upgrade action is not a large task for podmins.

**Comment by maxwell** [comment]
✊

**Comment by SuperTux88** [comment]
We have now switched to the `main` branch with the 0.9.0.0 release.
