### ISSUE TITLE
Serve public folder from app, instead of Nginx or Apache

### ISSUE THREAD

**Issue by Cleanshooter** [diaspora/diaspora#8135]
I'm curious if it would be possible to offer a configuration option that would have the application serve the public folder rather than requiring a web server (Apache/Nginx) to handle it.

**Comment by jhass** [comment]
Yes, that's that's what the `server.assets.serve` setting is for. However is it discouraged outside development. You will need a reverse proxy for TLS termination anyhow, shouldn't run diaspora as root to listen on port 80 and nginx and Apache are much much more efficient at serving static files.

**Comment by Cleanshooter** [comment]
Thanks for the reply @jhass, I'll try that out!  I'm running diaspora in a docker container (so it's not on root or port 80) and using Traefik for reverse proxy and TLS termination but, by my research Traefik doesn't have other web server capabilities (e.g. serving static files).  For this kind of setup it seemed like a waste of time to run another container (Apache/Nginx) to serve static files but I could be wrong... Seems like the major reason to use them is for TSL termination and load balancing, which I have another solution for.

Thanks again 👍
