### ISSUE TITLE
Twitter Integration && Patriot Act

### ISSUE THREAD

**Issue by braindef** [diaspora/diaspora#8136]
Hello Diaspora Team

i don't wanna play the paranoid guy, but couldn't it be a problem to reference eg. external things like the nice [twitter|youtube] inline content?

derivation of this thought:

1. USA has the Patriot Act
2. they definitely would force twitter with the patriot act to provide the possibility to inject 0days (XXS)
(maybe not for all people, but for those that are somehow relevant, they would use something like Access Based Ennumeration, eg. on IP Address, BrowserFingerprint...)
3. so you could be owned with your timeline?

![Screenshot from 2020-08-11 01-38-03](https://user-images.githubusercontent.com/7793611/89841761-17310800-db74-11ea-9385-6380abf4669a.png)

**Comment by Flaburgan** [comment]
Hi @braindef and thank you for taking time to report an issue about diaspora*.
We're aware of that situation. Diaspora* currently allows podmins to set up Camo as a reverse proxy for images, allowing the pod to protect users from several integration sources. Unfortunately, sources loaded through oEmbed such as YouTube and Twitter aren't included in that protection yet. There already is an issue about that problem, https://github.com/diaspora/diaspora/issues/6377, so I'm closing this one as a duplicate.
Have a good day.
