### ISSUE TITLE
sidekiq crashes

### ISSUE THREAD

**Issue by norayr** [diaspora/diaspora#8143]
it crashes always. every couple of minutes.

i think this is the important line:

`magic_envelope.rb:149: [BUG] Segmentation fault at 0x0000000000000048`

and [here](http://norayr.am/tmp/ruby-2020-09-12.txt) is the trace.

**Comment by norayr** [comment]
i guess that is ` privkey.sign(DIGEST, subject)` call.

**Comment by norayr** [comment]
after full rebuild of ruby and gems i have:

```/home/spyurk/diaspora/vendor/bundle/ruby/2.6.0/gems/ethon-0.12.0/lib/ethon/multi/operations.rb:174: [BUG] Segmentation fault at 0x0000000000000048```

[here](http://norayr.am/tmp/ruby_ethon_2020-09-12.txt) the trace now.

**Comment by norayr** [comment]
the call is
`code = Curl.multi_perform(handle, running_count_pointer)` now.

**Comment by norayr** [comment]
i have `curl` built with `adns -threads` USE flags.
since long ago. there is a comment: "for diaspora".

these flags are mutually exclusive. you cannot have both. for some reason i enabled adns, thinking it is necessary for diaspora. i guess there were crashes again?

now rebuild curl with threads and without adns support, testing diaspora.

**Comment by norayr** [comment]
ok i think i solved it.
let me keep this open for some time.

**Comment by norayr** [comment]
i can see the number of processed jobs raised

![](https://spyurk.am/uploads/images/fd3d3f485171ea42f9fa.png)

**Comment by norayr** [comment]
ah the rise starts Sep 10, this may reflect the problem, but not the situation after the given solution.

**Comment by denschub** [comment]
There's no need to ask questions on IRC and here at the same time. As we've told you before, this looks like something in your build is wrong, and we also told you how to debug, how to get help, and the fact that we have no idea what you're doing. :) This is not a bug in diaspora\*, but an issue with your setup. If you need help, please open a thread in Discourse at https://discourse.diasporafoundation.org, not here.

**Comment by norayr** [comment]
ok, sorry, and thank you. (:
i think i solved it by recompiling curl with threads support.
