### ISSUE TITLE
[Missing Information] Installation/Ubuntu/Xenial

### ISSUE THREAD

**Issue by AllanKlaus** [diaspora/diaspora#8157]
I've been setupping the project on my local machine. It's Ubuntu 20, I'm following the [doc](https://wiki.diasporafoundation.org/Installation/Ubuntu/Xenial) to do it.

I got an error to install `idn-ruby` i solved installing `libidn11-dev` and `libldap2-dev` I saw that you are migrating the wiki, it's good to add both dependencies on `apt install`

**Comment by SuperTux88** [comment]
`libldap2-dev` shouldn't be needed (at least I don't need it on debian, which should be similar enough), and `libidn11-dev` is known to be needed, but it's only needed for the `develop` branch, and it's also listed in the wiki already if you switch it to [Development](https://wiki.diasporafoundation.org/Installation/Ubuntu/Xenial?db=postgres&mode=development#Versions_of_this_guide)

**Comment by denschub** [comment]
I have confirmed that there is no need for `libldap2-dev`, and for `libidn`, what @SuperTux88 says is true.

By the way, we try not to use GitHub issues as a support channel. I'll close this issue as it appears to be resolved, and I invite you to ask further questions on https://discourse.diasporafoundation.org/ :)
