### ISSUE TITLE
Use compliant HTML in templates (to avoid future incompatibilities)

### ISSUE THREAD

**Issue by asdofindia** [diaspora/diaspora#8158]
There are some places in the code where HTML tags that need mandatory opening and closing tags are used with a self-closing tag.

Eg:
 
- [textarea](https://github.com/diaspora/diaspora/blob/4ca68a71d92218809ab7c32d7122c26566e8dd0e/app/assets/templates/comment-stream_tpl.jst.hbs#L31)
- [i](https://github.com/diaspora/diaspora/blob/4ca68a71d92218809ab7c32d7122c26566e8dd0e/app/assets/templates/aspect_membership_dropdown_tpl.jst.hbs#L32)

As of now, things work because we use a jquery version older than 3.5. But with jquery 3.5 [this will stop working](https://jquery.com/upgrade-guide/3.5/#description-of-the-change) and cause breakages like [this](https://joindiaspora.com/posts/19102750)

For avoiding future issues, it is easier to fix these templates by adding closing tags.

**Comment by pravi** [comment]
Using https://stackoverflow.com/a/7854998 as a reference, I was able to fix the issue by replacing all the invalid self closing tags.

**Comment by pravi** [comment]
If we can add rails-assets-jquery 3.5.1 to gems.diasporafoundation.org, then I can try to update jquery to 3.5.1 and include these changes.

**Comment by pravi** [comment]
It seems the latest version of rails-assets-jquery seems 3.4.1 at rails-assets.org. I think we should switch to jquery-rails only and remove rails-assets-jquery.

**Comment by pravi** [comment]
Though this would mean replacing all rails-assets-jquery-* gems as well, which won't be easy. As mentioned in #8147 switching to rails 6 and webpacker may be the best long term option.

**Comment by pravi** [comment]
Another short term option could be to manually update rails-assets-jquery to 3.5.1.

**Comment by denschub** [comment]
> If we can add rails-assets-jquery 3.5.1 to gems.diasporafoundation.org

Done. Let me know if that gem works. It looks fine, but since rails-assets.org is even more broken than usual, I have no "known-good" gem to compare it to. :)

**Comment by pravi** [comment]
@denschub seems working, tests passed locally.
