### ISSUE TITLE
Switching from poltergeist/phantomjs to selenium-webdriver/firefox (or chrome)

### ISSUE THREAD

**Issue by pravi** [diaspora/diaspora#8163]
PhantomJS is no longer actively maintained https://github.com/ariya/phantomjs/issues/15344. I was able to get the cucumber tests working with selenium-webdriver/geckodriver/firefox. Would you be interested in a pull request?

**Comment by jhass** [comment]
We started out with selenium-webdriver and switched to phantomjs because it cut the build time in half, at least. Is selenium much faster these days?

**Comment by pravi** [comment]
Were you running tests in headless mode? This is one benchmark I could find, which finds headless chrome is faster. I could not find anything for firefox (I'd prefer Firefox over chrome).

https://hackernoon.com/benchmark-headless-chrome-vs-phantomjs-e7f44c6956c

**Comment by jhass** [comment]
It needs to be compared on our actual testsuite. Synthetic benchmarks are rarely worth much IME.

**Comment by denschub** [comment]
> Were you running tests in headless mode?

Headless Firefox was not a thing back then. It is now, though.

**Comment by pravi** [comment]
This was the cucumber tests summary with headless firefox, there is some errors related to missing methods and handling cookies. I will run the same tests with phantomjs and report the time.

This was a small vm with 2GB RAM (2GB swap), cpu MHz : 3392.294 (two cores) and it has another diaspora service running inside an lxc container.

```
273 scenarios (81 failed, 1 flaky, 191 passed)
6036 steps (325 failed, 1827 skipped, 3884 passed)
93m31.447s
```

```
    And I click to delete the first post                                        # features/step_definitions/stream_steps.rb:70
    And I log out                                                               # features/step_definitions/session_steps.rb:57
      undefined method `clear_cookies' for #<Capybara::Selenium::Driver:0x00007fcb551251d8> (NoMethodError)
      ./features/support/user_cuke_helpers.rb:58:in `logout'
      ./features/step_definitions/session_steps.rb:58:in `/^I (?:log|sign) out$/'
      features/mobile/reshare.feature:38:in `And I log out'
    And I sign in as "bob@bob.bob" on the mobile website         
```

**Comment by jhass** [comment]
A runtime with so many failing tests is not very representative, capybara based tests have the tendency of being a lot faster when they pass.

**Comment by pravi** [comment]
I will try to fix as many failing tests I can.

**Comment by pravi** [comment]
This is time taken with phantomjs. 

```
273 scenarios (21 failed, 252 passed)
3857 steps (84 failed, 480 skipped, 3293 passed)
58m27.720s
```
The errors were like this,
```

Unrecognized Content-Security-Policy directive 'frame-ancestors'.

Unrecognized Content-Security-Policy directive 'manifest-src'.

The source list for Content Security Policy directive 'script-src' contains an invalid source: ''nonce-uhFR8KCQnaUgEWOqCC2Ou+TmAv9MQnz4cng5V3OsHw8=''. It will be ignored.
  Scenario: back out of posting a photo-only post   
```

It may be something caused by phantomjs version from debian.

**Comment by pravi** [comment]
There is another error with selenium webdriver/firefox

```
   And I add the person to my "Besties" aspect                                         # features/step_definitions/user_steps.rb:128
      Capybara::Driver::Node#trigger (Capybara::NotSupportedByDriverError)
      ./features/step_definitions/aspects_steps.rb:21:in `toggle_aspect_via_ui'
      ./features/step_definitions/user_steps.rb:130:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/web_steps.rb:18:in `with_scope'
      ./features/step_definitions/user_steps.rb:129:in `/^I (?:add|remove) the person (?:to|from) my "([^\"]*)" aspect(?: within "([^"]*)")?$/'
      features/desktop/auto_follow_back.feature:17:in `And I add the person to my "Besties" aspect'

```

**Comment by pravi** [comment]
This seems to be the issue https://medium.com/@yuliaoletskaya/capybara-inconsistent-click-behavior-and-flickering-tests-f50b5fae8ab2

**Comment by Flaburgan** [comment]
Just to share my experience, at work we're all using Firefox to develop but the tests suite is run by Selenium with chromium headless, which is way faster (~20%) than Firefox unfortunately.

**Comment by pravi** [comment]
Now failures are down to 63 and current work is at https://github.com/pravi/diaspora/tree/switch-poltergeist-to-selenium-webdriver
