### ISSUE TITLE
in develop-branch gem 'kostya-sigar' is referenced to v 2.0.6 which won't built under osX

### ISSUE THREAD

**Issue by tclaus** [diaspora/diaspora#8164]
Fetched current develop-branch, setup Dev environment and run
bundler install

got a 
`An error occurred while installing kostya-sigar (2.0.6), and Bundler cannot continue.`
which is referenced by eye gem and on a fixed version (2.0.6) 
However kostya-siga has a updated Gem (v2.0.8) which builds in a Mac. 

After manual setting version from 2.0.6 to 2.0.8 in Gemfile.lock bundle install works.

**Comment by jhass** [comment]
Fixed with 2aaf37659d1e9abff1bed659de2e87a56b91640f

**Comment by Flaburgan** [comment]
Thank you for taking time to report the issue @tclaus and @jhass for the quick fix!
