### ISSUE TITLE
Notifications guid sometimes null in database

### ISSUE THREAD

**Issue by jhass** [diaspora/diaspora#8186]
... which should never happen because there's an `after_initialize` always setting it. Which also makes this bug quite opaque, as a new random value is set each time one of those records are loaded.

However it breaks the API which is using the guid as identifier, so the backend would not find those records next time around the client wants to do something with them.

I've been testing to just enforce a `NOT NULL` constraint on the column on my pod for a few weeks, in hope of uncovering the origin of these. So far without any success. Put positively, adding the constraint seems to fix the error without any downsides.

**Comment by denschub** [comment]
I have been testing the same, and also have not found any issues.
