### ISSUE TITLE
In producer 'upload Photos' allows to select any filetype

### ISSUE THREAD

**Issue by tclaus** [diaspora/diaspora#8189]
But when uploading, only some image file types are permitted.
A form upload may filter only allowed file types just in the file-dialog.

<img width="701" alt="Bildschirmfoto 2020-12-03 um 18 23 53" src="https://user-images.githubusercontent.com/501326/101064984-e3e80e00-3594-11eb-9f4b-8b8e52551f0f.png">

**Comment by denschub** [comment]
Setting the [`accept` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#accept) would address this. However, this field is generated by FineUploader, not us. FineUploader is [no longer being maintained](https://github.com/FineUploader/fine-uploader/issues/2073), so I'm not sure what to do here.
