### ISSUE TITLE
Drop relay example configuration (and potentially implementation)

### ISSUE THREAD

**Issue by denschub** [diaspora/diaspora#8192]
As raised by @dmorley in https://github.com/diaspora/diaspora/commit/08395cc8773978f2dff3aaebe89b66102512bdf1#r45272407, there are no relay servers anymore, the idea was never very popular, and the implementation is unmaintained.

We should either find motivation to own this, or make sure that its deprecated state is known and properly handled.

**Comment by annando** [comment]
There is the relay server https://social-relay.isurf.ca/

**Comment by denschub** [comment]
> The relay server https://social-relay.isurf.ca/ is active.

With only 91 nodes subscribing, 447 posts turned over in the last 24 hours, and it being based on code [that hasn't even received security-updates for its dependencies since May 2019](https://github.com/jaywink/social-relay/commits/master), that only confirms that relays are, in fact, dead.

**Comment by annando** [comment]
Well, I guess that this server isn't so well known. But I surely won't fight for keeping the relay implementation in the Diaspora core. I just wanted to point out that there still is at least one relay server out there.
