### ISSUE TITLE
Mentions by ignored users generate mails

### ISSUE THREAD

**Issue by basxto** [diaspora/diaspora#8195]
I get emails when an ignored user mentions me in a comment.
That should not happen and this gets abused by spammers.

**Comment by denschub** [comment]
diaspora\* [does not create notifications for blocked actors](https://github.com/diaspora/diaspora/blob/1f329991259dcaf201d3b0ca1e5ca3be306ce10b/app/models/notification.rb#L36), and thus also does not dispatch a notification email. Besides looking this up in code, I also verified this on Geraspora with two test accounts - no notification, no email.

Most likely you got mention-spammed by a different account that just has/had the same profile name.
