### ISSUE TITLE
non-secure http links in diaspora main page

### ISSUE THREAD

**Issue by ford--prefect** [diaspora/diaspora#8198]
I noticed two items in the diaspora main page in version 0.7.14.0.

The first one appears in the head section of the html:
> `<head` prefix='og: http://ogp.me/ns# article: http://ogp.me/ns/article# profile: http://ogp.me/ns/profile#'>

And the second one are the links to the diaspora foundation in the lower left column:
> `<a href="http://wiki.diasporafoundation.org/Welcoming_Committee">`
> `<a target="_blank" href="http://wiki.diasporafoundation.org">Wiki</a>`

While I don't understand the purpose of the first one, the second appearance is an easy fix.

**Comment by tclaus** [comment]
Good finding - There are lots of other places with legacy (http) protocols. most of them now have the secure variant. 
Some others are not available any more.

**Comment by ford--prefect** [comment]
Sounds like you would appreciate some help finding all the other insecure protocol uses? I feel I can do that. Merge request coming.

**Comment by ford--prefect** [comment]
Created a pull request (#8201) for this.

**Comment by denschub** [comment]
Please only change links you have a really good reason to change something (i.e. a link that is actually affecting users), because your mass-change would just completely ruin the git logs with no reason whatsoever.

**Comment by denschub** [comment]
And just to clarify what I mean:

* Links like the sidebar links to the wiki: Great! Those get exposed to the user, so changing those is great.
* Links in templates, like the default front page: Also great, they can be clicked by users.
* HTML namespaces like the opengraph example: No need - those URLs are for spec-purposes only, they will not get queried by a browser.
* URLs in tests: No reason to change those, they have no user impact.

Please also **do not** touch translations. It's fine to edit the `en.yml`s, but everything else is handled outside of GitHub at WebTranslateIt - if you change the English main version, the languages will eventually sync.
