### ISSUE TITLE
wiki.diasporafoundation.org site deploy steps for CentOS 8 refer to diaspora.yml.example, file no longer in master

### ISSUE THREAD

**Issue by wvw999** [diaspora/diaspora#8199]
The wiki deploy steps refer to /diaspora/config/diaspora.yml.example, but the file now shipping with master is diaspora.toml.example

https://wiki.diasporafoundation.org/Installation/CentOS/8?db=postgres&mode=development#Copy_files

Additionally, there are no instructions for what to do with this file in the deploy steps.

The steps for Ubuntu also contain this info, others may also need an update.

**Comment by jhass** [comment]
The master branch still uses diaspora.yml: https://github.com/diaspora/diaspora/tree/master/config

You're probably looking at our default branch, which is develop.

We will update the guides in time with the next release switching to diaspora.toml of course.

**Comment by wvw999** [comment]
Ah, yes- I was working through the steps for a development install- I will revise the issue to refer to those instructions
