### ISSUE TITLE
ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by patrick-L91** [diaspora/diaspora#8211]
when  trying to connect to  https://www.diaspora-fr.org   I   have the error : 

Votre connexion n’est pas privée
Des individus malveillants tentent peut-être de subtiliser vos informations personnelles sur le site diaspora-fr.org (mots de passe, messages ou numéros de carte de crédit, par exemple). En savoir plus
NET::ERR_CERT_DATE_INVALID

so  I  would  like   you to  renew the certificat   who  send  the error ERR_CERT_DATE_INVALID

I have put somme comments  and pictures and   in case on long time   failure   thanks to   return  me   my pictures from your site.   

thank's  for your respons.

**Comment by SuperTux88** [comment]
This is not a bug in diaspora and there is nothing we as a project can do about this, since this is an issue with a single pod. So please just contact your podmin directly to fix the issue (in this case @Flaburgan).
