### ISSUE TITLE
[Feature request] Photo albums

### ISSUE THREAD

**Issue by stemy2** [diaspora/diaspora#8219]
Hello,

While this is possible to post photos, it seems unable to reorganize them into photos albums. I think it would be more ergonomic if we had this possibility.

**Comment by goobertron** [comment]
Please see the discussion about [organising photos](https://discourse.diasporafoundation.org/t/organising-photos/253).

There's an old GitHub ticket for photo albums: https://github.com/diaspora/diaspora/issues/3904

I'm going to close this GitHub ticket, as it's not needed. Please search for existing tickets before opening new ones. Thank you!
