### ISSUE TITLE
[Feature request] See local posts only

### ISSUE THREAD

**Issue by stemy2** [diaspora/diaspora#8220]
Hello,

It seems not possible to see only the post locally published on my pod (i mean, by users with "@mypod.tld" in their usernames), it make the moderation really difficult. Is it possible to implement a such functionality ?

**Comment by tclaus** [comment]
As a Podmins or moderator, auch a function would be nice and useful.
Could be realized by an Admin-function or by a search term.

**Comment by tclaus** [comment]
After thinking about it - 
Only local (public) posts on a pod would mean on some pods: Just my own posts, if the pod has closed registrations and the podmin (and invites) are the only guests. 

The other idea is, that local posts mean to view a more streamlined list of posts, more like the 'people in my favorite pup', then the 'public posts list'. The later means ( in my view) a more or less random list of posts linked in any case with the pod. 

So should this be better an option a podmin might switch on and off? Should booth options be visible or just one of them? 
Any ideas about this?

**Comment by jhass** [comment]
I'm pretty sure this idea came up previously but I'm unable to find any prior discussions currently. If anyone stumbles upon them, please cross-link.

**Comment by tclaus** [comment]
Eric Wright requests here: https://discourse.diasporafoundation.org/t/newhere-posts-or-local-posts-highlighted/1979 to 'see' local #newhere - posts to send a message . (2018)
