### ISSUE TITLE
Bug:CI After CI Upgrades to Ubuntu 20.04 git build fails

### ISSUE THREAD

**Issue by tclaus** [diaspora/diaspora#8221]
Git / CI Updates recently to 20.04.2. 

Till then build fails with 'LoadError: libffi.so.6: cannot open shared object file: No such file or directory'

All builds currently fail with these.

**Comment by tclaus** [comment]
a) set runs-on to fixed "ubuntu-18.04" for now. 
b) solve Problem 

For a) I can make a quick PR

Hint: don't run jobs on "latest" OS - you never know what to get.

**Comment by Flaburgan** [comment]
Hm, actually, most of the pods should be running 20.04 now so I would be in favor of fixing the CI instead of downgrading to 18.04.
