### ISSUE TITLE
mimemagic (0.3.5) ruby_rails_code

### ISSUE THREAD

**Issue by mass34** [diaspora/diaspora#8229]
Hello. This question will be solved? I can not install diaspora
> bin/bundle install --full-index
Fetching source index from https://gems.diasporafoundation.org/
Fetching source index from https://rubygems.org/

> Your bundle is locked to mimemagic (0.3.5), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources,

> that means the author of mimemagic (0.3.5) has removed it. You'll need to update your bundle to a version other than mimemagic (0.3.5) that hasn't been removed
in order to install.
[ruby_rails_code](https://www.theregister.com/2021/03/25/ruby_rails_code/)

**Comment by EvyBongers** [comment]
`mimemagic` is not defined in `Gemfile` but is locked in `Gemfile.lock` lines [398](https://github.com/diaspora/diaspora/blob/master/Gemfile.lock#L397-L398) and [407](https://github.com/diaspora/diaspora/blob/master/Gemfile.lock#L407).
In the develop and next-minor branches it's on the same version. Please update `Gemfile.lock`.

**Comment by pravi** [comment]
gitlab switched to https://rubygems.org/gems/ruby-magic-static which could be an option. But since diaspora itself is AGPL, we can use a GPLed version with shared-mime-info if they make it available later.
