### ISSUE TITLE
/api/v1 endpoints not found

### ISSUE THREAD

**Issue by rkbennett** [diaspora/diaspora#8245]
Using v0.7.15.0 on docker
Followed various instructions to register app, configure user authorization, and get access token.
When using the received access token all documented /api/v1 endpoints return a 404. I even went to verify by running bin/rake routes on the diaspora container, and there are no routes which start with /api/v1 listed

**Comment by jhass** [comment]
API is part of the next major diaspora release, 0.8. You need to run the develop branch :)

**Comment by rkbennett** [comment]
Ah, my bad, thought it was in 0.7.15.0, just not fully supported. Is there an estimate on when 0.8 will be getting a tagged release @jhass?

**Comment by tclaus** [comment]
@rkbennett You can run the dev branch or find a pod running 0.7.99 on podupti.me
But that's "living on the edge".
