### ISSUE TITLE
Default post visibility not respected and editable in mobile view

### ISSUE THREAD

**Issue by mmuman** [diaspora/diaspora#8247]
As co-host of a radio show, I've set the default visibility preference to "public" for our show's account, hoping it would work for my friend who now handles the social media posting because I noticed she forgot to set them to public at first.
Now I noticed the last posts were limited again, via mobile. I asked her to check, and then I noticed the mobile interface didn't show the setting nor respect it.

I know there were reasons given for this in implementation in #7118 of #4319, and it's probably not useful for most users, but for our use-case it's annoying.

Couldn't the drop-down propose the current list of aspects as single option, then each aspect, and then public ?

**Comment by tclaus** [comment]
In mobile, the default aspects should be set.

**Comment by tclaus** [comment]
Can / will be fixed after migration of https://github.com/diaspora/diaspora/pull/8217

**Comment by SuperTux88** [comment]
Closing this as duplicate of #7333
