### ISSUE TITLE
Problem archiving posts or tags in Archive.org

### ISSUE THREAD

**Issue by HackersCardgame** [diaspora/diaspora#8248]
i guess we should take archive.org and diaspora into the domain model of the problem

... and YES i am 42 and still have a teddy bear.

archive org censorship diaspora
https://www.youtube.com/watch?v=SyU7uRAaz_4
https://www.youtube.com/watch?v= S y U 7 u R A a z _ 4 

mirror of Video:
https://gitlab.com/HackersCardgame/hackerscardgame-notes5/-/blob/master/TODO/archive-org-censorship-diaspora.mkv

Sincerely your hackerscardgame.

**Comment by jhass** [comment]
I don't see the issue. That user content should be archived in archive.org does not seem obvious to me at all.

**Comment by tclaus** [comment]
@jhass I also don't see a special problem here wayback-machine seems to store posts with text and images well. 
But may there be a problem with camo images? The links are huge and more annoying, they don't have a file-suffix. (.jpg / .jpeg).

**Comment by jhass** [comment]
I see no action points.
