### ISSUE TITLE
autofollow_on_join can break registration

### ISSUE THREAD

**Issue by jhass** [diaspora/diaspora#8253]
Even a wrong setting should not lead to a broken user experience.

See https://discourse.diasporafoundation.org/t/the-change-you-wanted-was-rejected/3990

**Comment by SuperTux88** [comment]
I thought this might also be a problem in other cases (like when the autofollow account was closed?), but I just tested that and couldn't make this fail anymore, so maybe #8273 was the only thing needed to fix this? Closing this for now, since I can't reproduce it making it fail :man_shrugging:
