### ISSUE TITLE
Question: Does Diaspora accept literal HTML in incoming messages at all?

### ISSUE THREAD

**Issue by MrPetovan** [diaspora/diaspora#8271]
Related to https://github.com/friendica/friendica/issues/10495

Markdown accepts literal HTML for the features it lacks, but this feature doesn't seem to be supported by Diaspora. Before we strip all HTML tags from outgoing messages from Friendica to Diaspora, I'd like to confirm it is indeed the case.

**Comment by jhass** [comment]
On the desktop web we render using markdown-it and some plugins, so basically we support the CommonMark spec: https://spec.commonmark.org/current/

**Comment by MrPetovan** [comment]
Thank you for your answer, it seems like we aren't adding the necessary end condition (a blank line) for the `<details>` tags we use BBCode to render internally.
