### ISSUE TITLE
Import shouldn't fail when a pod certificate is invalid

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#8300]
`DiasporaFederation::Discovery::DiscoveryError: Failed to fetch https://diaspora.eigenlab.org/.well-known/webfinger?resource=acct:vcuculo@diaspora.eigenlab.org for vcuculo@diaspora.eigenlab.org: Faraday::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate)`

See full stack trace:
https://gist.githubusercontent.com/Flaburgan/beb704a006ae1a299f4e1caf11bd70c2/raw/e1a7729bd002dbe42171172a0a830f279151fa91/Import%2520from%2520diasp.org

**Comment by tclaus** [comment]
diaspora.eigenlab.org uses a self signed, expired certificate. So this should not be used. The diaspora service is down. 
So this is informative message and can be ignored.

**Comment by tclaus** [comment]
Reopen, because it seems that migration stops if a pod is not fetchable. In this case, by SSL problem.

**Comment by tclaus** [comment]
@SuperTux88 

Should a rescue 'OpenSSL::SSL::SSLError' be added to the 'entity_importer.rb

https://github.com/diaspora/diaspora/blob/274edf7589620915b402e594b2fc0ce185cde76e/lib/archive_importer/entity_importer.rb#L15

?

**Comment by SuperTux88** [comment]
No, `OpenSSL::SSL::SSLError` is way too low-level and shouldn't be handled there, the federation code always (or should if it doesn't already) either raises a `DiscoveryError` or `NotFetchable` if something goes wrong on a lower level (connection problem, 404, SSL-errors, or whatever). The import code shouldn't need to handle all these low-level problems.

And this is actually weird, in this case it's a `DiasporaFederation::Federation::Fetcher::NotFetchable` that causes the problem, which is already handled there, so it shouldn't fail anymore? Was this test done with old code without `NotFetchable` already being handled there?

**Comment by Flaburgan** [comment]
That test has been done [the 8th of September](https://discourse.diasporafoundation.org/t/backup-and-restore-account-migration/544/183?u=flaburgan) with the commits from https://github.com/diaspora/diaspora/pull/8274 at that time.
