### ISSUE TITLE
Warning:  Namespace test not found in config/diaspora.toml

### ISSUE THREAD

**Issue by hasandiwan** [diaspora/diaspora#8323]
The tests still run fine, but I'm just curious how to sort this warning.

**Comment by pseacrest** [comment]
I see the same warning here? Glitch?

**Comment by jhass** [comment]
You can safely ignore this warning. It's harmless and just an artifact of how the configuration system works. If you're very deeply annoyed by it you can just add an empty `test` section to `diaspora.toml` :)
