### ISSUE TITLE
implement a feature to enforce payments from users

### ISSUE THREAD

**Issue by sfindeisen** [diaspora/diaspora#8335]
Hi, is there a feature in Diaspora to enforce payments from users? In cryptocurrency perhaps?
I think that could make the job of running a pod much more interesting.
Part of the money could also be used to incentivize Diaspora development.

I am coming from joindiaspora.com, which is [dying](https://joindiaspora.com/posts/22282896).

Thanks

**Comment by goobertron** [comment]
There isn't, and this is something that is extremely unlikely to be built into diaspora\*'s core code base for various reasons.

By the way, Github is for tracking technical matters (bugs and so forth). General questions and discussions (such as feature suggestions) are better made in our [Discourse forum](https://discourse.diasporafoundation.org). You will find existing discussions on issues similar to what you're asking, including on specifically on the issue of micropayments. For that reason, I'm going to close this ticket, as it's not something that can usefully be handled in Github.
