### ISSUE TITLE
Post removal request of old & deleted account

### ISSUE THREAD

**Issue by mightydeamon78** [diaspora/diaspora#8339]
Hi there,

there is a old post i made years ago with an account i once deleted, but there was a bug,
and so google is still showing up.

Please, would someone do me the favour and delete this post?
It was really stressfull to clean up my google results, so it would be great to have this last job done...

https://diaspora-fr.org/posts/44dcf310e6b40132c1f252540061b601

Thank you very much!

**Comment by goobertron** [comment]
Hi there,
Github isn't the right place for this request, as this concerns the admin of an individual pod and not changes in the core software.
I'll therefore close this issue, but I'll ping the podmin of diaspora-fr, so that they can help you. Calling  @Flaburgan !
