### ISSUE TITLE
Making posts "Public" by default

### ISSUE THREAD

**Issue by prp-e** [diaspora/diaspora#8354]
I have a local instance of diaspora, my problem is when I want to post, it is set on "All Aspects". How can I force it to be public in the configurations?

**Comment by denschub** [comment]
Go into your user settings, `/user/edit`, find the "Default aspects selected for posting" setting, and set it to "public".

**Comment by tclaus** [comment]
@denschub This is true for the desktop view, but won't work for the mobile view.
https://github.com/diaspora/diaspora/pull/8217 is a precondition for fixing this on the mobile view. 
So this issue should be reopened.

**Comment by denschub** [comment]
@tclaus you have permissions to reopen issues. ;D

**Comment by SuperTux88** [comment]
Duplicate of #7333
