### ISSUE TITLE
Support ruby 3

### ISSUE THREAD

**Issue by SuperTux88** [diaspora/diaspora#8369]
I already fixed some issues to support ruby 3 in #8368, but there are still some issues that don't work yet with ruby 3.0.x:

* [x] [i18n-inflector-rails](https://rubygems.org/gems/i18n-inflector-rails) isn't compatible with ruby 3, and the last release is from 2013. But there has been some activity in the [Repo](https://github.com/siefca/i18n-inflector-rails), and it looks like the issue with ruby 3 [was fixed](https://github.com/siefca/i18n-inflector-rails/pull/10) ... but there hasn't been a release yet. And the fix also changed the requirement to be ruby `>= 3`, so we can't support ruby 2.7 at the same time (which means as soon as we would ruby 3 support with it, we need to drop 2.7, so we can't have a release that supports 2.7 AND 3). There are multiple options now:
  * Wait until a new version is released, update to that, and drop ruby 2.7
  * Find a different solution to achieve the same, which maybe already works with ruby 3 (and also 2.7)
  * Drop the dependency, as far as I can tell it's only used in 8 translation strings (mostly in `pl`)
* [x] there is a problem with [carrierwave](https://rubygems.org/gems/carrierwave) and `mini_magick`. Basically the feature added in #7924 doesn't work in ruby 3: ``convert: unrecognized gravity type `{:combine_options=>{:unsharp=>"1.5x1+0.7+0.02"}}' @ error/convert.c/ConvertImageCommand/1762.``, because it adds the `combine_options` to the `gravity` parameter. As far as I can tell there isn't a fix for that yet.
* [x] With ruby 3.1 the tests don't even start, and I haven't looked closer into that. Lets first focus on getting ruby 3.0 in a working state.

**Comment by Neustradamus** [comment]
@SuperTux88: Any news on it?

Ruby 2.7.x is EOL.

**Comment by SuperTux88** [comment]
The `develop` branch now support ruby 3.0 and 3.1, and 2.7 got dropped.
