### ISSUE TITLE
Setting up an account - failing big time at "human verification"

### ISSUE THREAD

**Issue by aventurin1** [diaspora/diaspora#8401]
Dear team,

i tried to open up an account at https://wk3.org/ and i have big issues to identify the image value for the "human verification process". Therefore i failed like a robot.

After failing for some minutes I have done some examples because i dont want to accept this. In this process i finally achieved victory over the machine. I think i was lucky.
![image](https://user-images.githubusercontent.com/116192793/196748224-bdbb2ea4-1ea1-4301-8ffd-37718a303350.png)
- I knew that i had to find 5 characters only after checking in on another pod which apparently uses another imagegenerator
- the 2nd to 4th character is mostly readable, but sometimes even them are blurred into oblivion
- in the end its mostly guesswork - not the thing i would expect from a captcha. I am sure, machines are better at guessing than i am.

Thank you for your time!
mika

(I found this https://github.com/diaspora/diaspora/issues/6432 - unresolved, but helpful for me as i was just giving up. The answers gave me the hint for checking another pod + open this ticket with more information)

**Comment by SuperTux88** [comment]
Well, that's not the default (you can see on other pods how it's supposed to look) and there is not much we can do about that as a project, as it looks like wk3.org modified the captcha in some way to make it harder readable. You'll need to contact the admin of wk3.org if you want that solved.
