### ISSUE TITLE
Please make a new stable release with ruby 3.1

### ISSUE THREAD

**Issue by pravi** [diaspora/diaspora#8440]
As ruby 2.7 is no longer supported and 1.0 release can take a while. Suggested by Fla here https://mastodon.social/@fla/111764549297906300

As https://endoflife.date/ruby support Ended 9 months ago (31 Mar 2023). We managed to fix this with two patches

https://salsa.debian.org/ruby-team/diaspora-installer/-/blob/master-sid/debian/ruby3.patch?ref_type=heads and
https://salsa.debian.org/ruby-team/diaspora-installer/-/blob/master-sid/debian/i18n.patch?ref_type=heads

But it'd be nice to have an officially supported version so we don't have to keep maintaining that patch for long.

**Comment by denschub** [comment]
What Fla said in his social media post was correct. We have concrete plans for that, well knowing that we can't finish a 1.0 anytime soon. But no timeline, as there is a bit of stuff left to fix that's actually broken right now. We will release a version as soon as we're ready to do so.

This isn't a bug either way, so I'm closing this.

**Comment by WeepingClown13** [comment]
@denschub I couldn't see any recent issues indicating serious bugs, so I was wondering exactly what sort of breakages we were looking at. And while I understand that stable release might take some time, is there any point in expecting any interim/pre releases? If that could be done, it'll help a lot.
