### ISSUE TITLE
Only default avatars for Friendica account

### ISSUE THREAD

**Issue by haheute** [diaspora/diaspora#8443]
Hello,

maybe somebody can help me:

Since some days, or so, the avatar pictures of my [Friendica account](https://boerdica.de/profile/noidea) don't show up on my [Diaspora account](https://diaspora.schoenf.de/u/xy). Instead a default picture is displayed. I opened an issue here : https://github.com/friendica/friendica/issues/13939 , where is said, maybe the updating of the avatar photo needs to be triggered..

Does someone here have an idea what could be done?
I have already set another avatar in friendica and then switched again back to the first picture. And I have unfriended my friendica account and the followed it again, but doesn't seem to have resolved the problem.

**Comment by annando** [comment]
PR https://github.com/friendica/friendica/pull/13967 will fix this. But you have to change something in your profile, so that the updated profile data is transmitted to your Diaspora followers.

**Comment by haheute** [comment]
I see the avatar photos again. Thank you very much.
