### ISSUE TITLE
Update Description for Debian 11

### ISSUE THREAD

**Issue by memo-567** [diaspora/diaspora#8450]
I don't know whether it is necessary in all circumstances, but in my installation, it is necessary to use `rvm use 3.3.3` after calling `rvm install 3.3`.

Maybe it makes sense to include this in the update description?

**Comment by SuperTux88** [comment]
If you follow the [upgrade instructions](https://wiki.diasporafoundation.org/Updating#Updating_diaspora*_0.7_to_diaspora*_0.9), and do the `cd .. && cd -` after you installed ruby 3.3 and after you switched to the `main` branch and pulled the new code, it should use ruby 3.3 automatically. But the cd command is essential, and the order matters.

**Comment by memo-567** [comment]
I did this in the same way, but it didn't work for me. Maybe it's due to a special configuration of my system somewhere. Just thought I should mention it in case anyone is facing the same hurdle.

**Comment by denschub** [comment]
GitHub is not a support forum, [our Discourse is](https://discourse.diasporafoundation.org/).

**Comment by denschub** [comment]
Also, if you *have* to use `rvm use`, then please do `rvm use 3.3@diaspora`, to make sure to install the Gems into the right Gemset.

**Comment by denschub** [comment]
What does `rvm list gemsets` say?

**Comment by memo-567** [comment]
It depends on the directory. In /home/diaspora/diaspora it is => ruby-3.3.3@diaspora [ x86_64 ]

 In /home/diaspora it is => ruby-3.1.4 [ x86_64 ]



![20240616-1808](https://github.com/diaspora/diaspora/assets/58190287/692fcb25-67a9-41a6-88a6-a6db88e04756)

**Comment by denschub** [comment]
It's expected that the output changes depending in the directory you're in. We have two special files, `.ruby-version` and `.ruby-gemset` in the project directory, which tell RVM exactly which Ruby we want it to use. That's also the reason we tell you to re-change into the directory after updating sources.

Looks like you're fine, though. If you ever run into issues with something complaining about "missing gems" or something, just run `bin/bundle install --full-index` again and it should be resolved.

**Comment by memo-567** [comment]
Thanks for the detailed explanation 👍
