### ISSUE TITLE
Support ActivityPods

### ISSUE THREAD

**Issue by outlaw-dame** [diaspora/diaspora#8451]
I believe there’s a lot of overlap of what Diaspora cares about as well as the Solid community. I think it would be a benefit to have Diaspora connect to the broader AP Fediverse and provide people with another platform to choose from that may more align with their interests.

https://activitypods.org/
https://github.com/activitypods/activitypods

**Comment by denschub** [comment]
We have no intentions of supporting ActivityPub, Solid, or any other protocol that's not diaspora\*s protocol. Our Discourse instance has all the details and backstory of that.
